### ISSUE TITLE
🐛 [CLOUD_FIRESTORE] The service is currently unavailable.

### ISSUE THREAD

**Issue by levent-kantaroglu** [FirebaseExtended/flutterfire#3521] opened 2020-09-10 20:23 UTC
## Bug report

I'm try to use Firestore with Flutter Deskop (MacOS). But I'm getting always this error since my first try for a month.
```
[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
```

### Steps to reproduce

1. Created iosApp on Firebase and downloaded GoogleService-Info.plist file to macos project
2. AppBundle (in Runner.xcworkspace) is edited like on Firebase
3. Creted a collection and document on Firebase (myCollection/myDocument)
(All steps on https://firebase.flutter.dev/docs/installation/macos)

### Expected behavior

I wish to get name value from myDocument on Firebase

---

## Additional context

main.dart
```
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp()
      .then((value) => print("connected " + value.options.asMap.toString()))
      .catchError((e) => print(e.toString()));
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  FirebaseFirestore firestore = FirebaseFirestore.instance;

  void _initializeApp() async {
    await Firebase.initializeApp();
  }

  @override
  void initState() {
    _initializeApp();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    CollectionReference users =
        FirebaseFirestore.instance.collection('myCollection');

    return Scaffold(
      appBar: AppBar(),
      body: FutureBuilder<DocumentSnapshot>(
        future: users.doc("myDocument").get(),
        builder:
            (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot) {
          if (snapshot.hasError) {
            print(snapshot.error.toString());
            return Text(snapshot.error.toString());
          }

          if (snapshot.connectionState == ConnectionState.done) {
            Map<String, dynamic> data = snapshot.data.data();
            return Text("Name: ${data['name']}");
          }

          return Text("loading");
        },
      ),
    );
  }
}

```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel dev, 1.22.0-9.0.pre, on Mac OS X 10.15.5 19F101, locale en-TR)
    • Flutter version 1.22.0-9.0.pre at /Users/leventkantaroglu/Development/flutter
    • Framework revision 7a43175198 (13 days ago), 2020-08-28 23:18:04 -0400
    • Engine revision 07e2520d5d
    • Dart version 2.10.0 (build 2.10.0-73.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/leventkantaroglu/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.0.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.48.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.14.1

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.5 19F101
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.0-73.0.dev
Flutter SDK 1.22.0-9.0.pre
flutter_desktop_macos 1.0.0+1

dependencies:
- cloud_firestore 0.14.0+2 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 0.1.3
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety [collection]
- boolean_selector 2.1.0-nullsafety [source_span string_scanner]
- characters 1.1.0-nullsafety.2
- charcode 1.2.0-nullsafety
- clock 1.1.0-nullsafety
- cloud_firestore_platform_interface 2.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+1 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.2
- fake_async 1.1.0-nullsafety [clock collection]
- firebase 7.3.0 [http http_parser js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.2
- matcher 0.12.10-nullsafety [stack_trace]
- meta 1.3.0-nullsafety.2
- path 1.8.0-nullsafety
- pedantic 1.9.0
- plugin_platform_interface 1.0.2 [meta]
- quiver 2.1.3 [matcher meta]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety [path]
- stream_channel 2.1.0-nullsafety [async]
- string_scanner 1.1.0-nullsafety [charcode source_span]
- term_glyph 1.2.0-nullsafety
- test_api 0.2.19-nullsafety [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.2 [collection]
- vector_math 2.1.0-nullsafety.2
```

</details>

---

**Comment by darshankawar** [comment] 2020-09-11 12:32
Hi @kaiserleka,
Can you create a fresh Flutter project and try below steps to see if it works ?

1. Setup a default Flutter project.
2. Add `cloud_firestore` and `firebase_core` to `pubspec.yaml`. 
3. Create a project in Firestore. Create a collection. Create a single simple document in that collection.
4. Follow the instructions at https://firebase.flutter.dev/docs/installation/macos to install GoogleService-Info.plist file.
5. Initialize Firebase, following the FutureBuilder / Stateful example here: https://firebase.flutter.dev/docs/overview/#initializing-flutterfire
6. Add import 'package:cloud_firestore/cloud_firestore.dart';
7. Use your code sample provided above.
8. Run app and see if you still get same error ?

Thanks.

**Comment by kaiserleka** [comment] 2020-09-11 14:42
> Hi @kaiserleka,
> Can you create a fresh Flutter project and try below steps to see if it works ?


> 1. Setup a default Flutter project.

I have created a new Flutter project and enabled desktop support.

<img width="751" alt="Screen Shot 2020-09-11 at 16 25 59" src="https://user-images.githubusercontent.com/46875013/92931227-cc90fd00-f44b-11ea-8b74-8c09264b6984.png">

> 2. Add `cloud_firestore` and `firebase_core` to `pubspec.yaml`.

I have added both of that packages to pubspec.yaml

<img width="769" alt="Screen Shot 2020-09-11 at 16 15 03" src="https://user-images.githubusercontent.com/46875013/92929902-f812e800-f449-11ea-905e-f9678bd1d383.png">

> 3. Create a project in Firestore. Create a collection. Create a single simple document in that collection.

I have created new Firestore project and created a collection named "testCollection"

<img width="888" alt="Screen Shot 2020-09-11 at 16 13 09" src="https://user-images.githubusercontent.com/46875013/92930068-3c9e8380-f44a-11ea-84c4-764023b880d3.png">


> 4. Follow the instructions at https://firebase.flutter.dev/docs/installation/macos to install GoogleService-Info.plist file.

4.1 I have name my named my project

<img width="435" alt="Screen Shot 2020-09-11 at 16 21 18" src="https://user-images.githubusercontent.com/46875013/92930508-d6663080-f44a-11ea-84d4-555dfa765ed4.png">

<img width="1026" alt="Screen Shot 2020-09-11 at 16 26 32" src="https://user-images.githubusercontent.com/46875013/92938979-e20b2480-f455-11ea-9940-6ed6b1f1e7be.png">

<img width="958" alt="Screen Shot 2020-09-11 at 16 26 45" src="https://user-images.githubusercontent.com/46875013/92939042-f6e7b800-f455-11ea-92d5-4c2dbb1d184e.png">
<img width="815" alt="Screen Shot 2020-09-11 at 16 27 24" src="https://user-images.githubusercontent.com/46875013/92939071-00712000-f456-11ea-9dda-742e4987e09c.png">


> 5. Initialize Firebase, following the FutureBuilder / Stateful example here:
> https://firebase.flutter.dev/docs/overview/#initializing-flutterfire

I have located that stateful example onto my main.dart. **When I run it, it works** 

```
import 'package:flutter/material.dart';
// Import the firebase_core plugin
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

void main() {
  runApp(MaterialApp(home: App()));
}

class App extends StatefulWidget {
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  // Set default `_initialized` and `_error` state to false
  bool _initialized = false;
  bool _error = false;

  // Define an async function to initialize FlutterFire
  void initializeFlutterFire() async {
    try {
      // Wait for Firebase to initialize and set `_initialized` state to true
      await Firebase.initializeApp().catchError((e) => print(e));
      setState(() {
        _initialized = true;
      });
    } catch (e) {
      // Set `_error` state to true if Firebase initialization fails
      print(e);
      setState(() {
        _error = true;
      });
    }
  }

  @override
  void initState() {
    initializeFlutterFire();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // Show error message if initialization failed
    if (_error) {
      print("_error : " + _error.toString());
      return Scaffold(
        body: Center(
          child: Text("Error: " + _error.toString()),
        ),
      );
    }

    // Show a loader until FlutterFire is initialized
    if (!_initialized) {
      return Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      );
    }
    return Scaffold(
      body: Center(
        child: Text("initialized"),
      ),
    );
  }
}

```


> 6. Add import 'package:cloud_firestore/cloud_firestore.dart';

I have added 

> 7. Use your code sample provided above.

I have updated my code with firestore. **Event I run Firebase.initializeApp(), it says _"[core/no-app] No Firebase App '[DEFAULT]' has been created - call Firebase.initializeApp()"_**

```
import 'package:flutter/material.dart';
// Import the firebase_core plugin
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

void main() {
  runApp(MaterialApp(home: App()));
}

class App extends StatefulWidget {
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  // Set default `_initialized` and `_error` state to false
  bool _initialized = false;
  bool _error = false;

  // Define an async function to initialize FlutterFire
  void initializeFlutterFire() async {
    try {
      // Wait for Firebase to initialize and set `_initialized` state to true
      await Firebase.initializeApp().catchError((e) => print(e));
      setState(() {
        _initialized = true;
      });
    } catch (e) {
      // Set `_error` state to true if Firebase initialization fails
      print(e);
      setState(() {
        _error = true;
      });
    }
  }

  @override
  void initState() {
    initializeFlutterFire();
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    // Show error message if initialization failed
    if (_error) {
      print("_error : " + _error.toString());
      return Scaffold(
        body: Center(
          child: Text("Error: " + _error.toString()),
        ),
      );
    }

    // Show a loader until FlutterFire is initialized
    if (!_initialized) {
      return Scaffold(
        body: Center(
          child: CircularProgressIndicator(),
        ),
      );
    }
    CollectionReference users =
        FirebaseFirestore.instance.collection('testCollection');
    return Scaffold(
      body: Center(
        child: Column(children: [
          Text("initialized"),
          Divider(),
          FutureBuilder<DocumentSnapshot>(
            future: users.doc("testDocument").get(),
            builder: (BuildContext context,
                AsyncSnapshot<DocumentSnapshot> snapshot) {
              if (snapshot.hasError) {
                print(snapshot.error.toString());
                return Text(snapshot.error.toString());
              }

              if (snapshot.connectionState == ConnectionState.done) {
                Map<String, dynamic> data = snapshot.data.data();
                return Text("Value: ${data['testField']}");
              }

              return Text("loading");
            },
          ),
        ]),
      ),
    );
  }
}
```

<img width="1002" alt="Screen Shot 2020-09-11 at 17 39 28" src="https://user-images.githubusercontent.com/46875013/92938840-c0aa3880-f455-11ea-81b9-4269b340e997.png">

**Comment by darshankawar** [comment] 2020-09-14 11:11
@kaiserleka,
Since `firebase_core` is the first and foremost important plugin after migration, initializing it is the first step to integrate firebase in your app. You can do that inside main() method itself, like below and see if it works for you.

```
void main() async {
  await Firebase.initializeApp();
  runApp(MyApp());
}
```

**Comment by kaiserleka** [comment] 2020-09-14 15:28
> @kaiserleka,
> Since `firebase_core` is the first and foremost important plugin after migration, initializing it is the first step to integrate firebase in your app. You can do that inside main() method itself, like below and see if it works for you.
> 
> ```
> void main() async {
>   await Firebase.initializeApp();
>   runApp(MyApp());
> }
> ```

I'm getting : **[core/not-initialized] Firebase has not been initialized. Please check the documentation for your platform.**

```
bool isFirebaseReady = true;
void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp().catchError((e) {
    isFirebaseReady = false;
    print(e);
  });
  runApp(MaterialApp(home: App()));
}
```

Why I can't find any complete Flutter Firestore Macos project :(

**Comment by evanpon** [comment] 2020-09-19 23:29
@kaiserleka - is your macos app in App Sandbox mode, and if so, did you add the com.apple.security.network.client entitlement?

**Comment by kaiserleka** [comment] 2020-09-20 04:49
> @kaiserleka - is your macos app in App Sandbox mode, and if so, did you add the com.apple.security.network.client entitlement?

I have also added this to entitlement files but still getting : _[core/not-initialized] Firebase has not been initialized. Please check the documentation for your platform._
```
<key>com.apple.security.network.client</key>
<true/>
```

**Comment by evanpon** [comment] 2020-09-20 05:27
My apologies, my comment wasn't very helpful without additional context. I don't know why you are getting the _Firebase has not been initialized._ error. I tried looking through your code, but I'm pretty new to Flutter and wasn't able to spot the issue.

My comment about the entitlement was to address your original problem, which was that you were getting an error message about cloud_firestore being unavailable.

That said, here is a main.dart file that successfully connects to Firestore for me on macos. I imagine all the other setup (pubspec, entitlements, etc is now similar to mine so I won't paste it all).

```
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

void main() {
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
        // Initialize FlutterFire:
        future: Firebase.initializeApp(),
        builder: (context, snapshot) {
          // Check for errors
          if (snapshot.hasError) {
            return const Text("Error", textDirection: TextDirection.ltr);
          }
          if (snapshot.connectionState == ConnectionState.done) {
            return MaterialApp(
              title: 'Flutter Demo',
              theme: ThemeData(
                primarySwatch: Colors.blue,
                visualDensity: VisualDensity.adaptivePlatformDensity,
              ),
              home: MyHomePage(title: 'Flutter Demo Home Page'),
            );
          }
          return const Text("Loading", textDirection: TextDirection.ltr);
        });
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: StreamBuilder(
          stream: FirebaseFirestore.instance.collection('mycollection').snapshots(),
          builder: (context, snapshot) {
            if (!snapshot.hasData) return const Text('Loading');

            return ListView.builder(
                itemExtent: 80,
                itemCount: snapshot.data.documents.length,
                itemBuilder: (context, index) => ListTile(
                        title: Row(
                      children: [
                        Expanded(
                          child: Text(
                              snapshot.data.documents[index].data().toString()),
                        )
                      ],
                    )));
          }),
    );
  }
}

```

**Comment by kaiserleka** [comment] 2020-09-20 18:23
> That said, here is a main.dart file that successfully connects to Firestore for me on macos. I imagine all the other setup (pubspec, entitlements, etc) is now similar to mine so I won't paste it all.

Could you share those files and related macos files just in case? Your dart code still giving that error @evanpon

**Comment by evanpon** [comment] 2020-09-21 03:31
I created a new project from scratch, and made the (I think) minimum changes to make it work for Firestore. You can see the repo and look at the commits here: https://github.com/evanpon/macos_firestore. The one piece it doesn't have is the GoogleService-Info.plist file, since you'll need that from your own project.

**Comment by tgpsantos** [comment] 2020-09-23 20:16
I'm also looking for a solution to this error. In my case I get it only when my device (Android) is offline.

**Comment by findnizam** [comment] 2020-10-13 05:17
Anyone found a solution for this. I have been trying for the last two days and couldnt find a solution.

**Comment by shinriyo** [comment] 2020-10-17 14:52
[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
Steps to reproduce


it happened recently.
google products always have annoying bugs

**Comment by StephanCassel** [comment] 2020-10-21 19:16
Same here. 

Used to work like a charm but not anymore.

  await Firebase.initializeApp();  

  await authService.signinAnonymously(); // OK

 var documentSnapshot =  await FirebaseFirestore.instance.collection('user').doc(deviceId).get();  // HANG

after 10 seconds or so: 
**The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.**

**Comment by zzterrozz** [comment] 2020-11-03 22:50
Same error on iOS 14 physical device. Anyone found a solution ?

**Comment by mtcliatt** [comment] 2020-11-04 05:49
Similar issue on macos: `Resource temporarily unavailable`

**Comment by mtcliatt** [comment] 2020-11-04 05:55
Same issue on macos with firebase_core 0.5.1 and cloud_firestore 0.14.2

**Comment by mtcliatt** [comment] 2020-11-04 06:01
Adding the network client entitlement fixed my issue (`com.apple.security.network.client`). I'm guessing that App Sandbox mode is the default for macos Flutter apps, so this step should probably be added to the documentation.

**Comment by iktakahiro** [comment] 2020-11-06 11:30
Hi, same error here, **on physical Android devices**. Firestore client throws same error randomly.

```
[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
```

* firebase_core: 0.5.1
* cloud_firestore: 0.14.2

In my case, a network connection of those devices were active. In addition, I already implemented a retry process using the exponential backoff algorithm. However, this issue is not resolved.

**Comment by jakesterrr123** [comment] 2020-11-11 09:39
Same here. My app was working fine until about 2 weeks ago, and now I'm getting that error about 70% of the times I try and start the app

**Comment by nelstein** [comment] 2020-11-19 08:24
Make sure that in your android/build.gradle there is **classpath 'com.google.gms:google-services:4.3.3'**
Emphasis on the version. Took me the whole day

**Comment by ElaineSchwner** [comment] 2020-11-23 17:42
The same is happening here https://github.com/FirebaseExtended/flutterfire/issues/2753
Sadly, it is almost impossible to work with Flutter and Firebase.

**Comment by Donneto** [comment] 2020-11-24 00:05
Any solution on this?

**Comment by mdalihusain** [comment] 2020-11-24 14:52
I also encountered this problem, but the issue has been resolved a few days back on one of my devices.
@Ehesp I would like to confirm that this issue was not limited to FlutterFire, native Android Firebase Apps were not working as well.
I was in contact with Firebase Support, they told me that there are some issues with ISPs on which they are working to get them resolved.
For me, things are working fine now, but once in a couple of weeks, I still face this issue for 5-10 mins. And, I have noticed that when this issue occurs, even YouTube takes a long time in loading.

**Comment by dgilperez** [comment] 2020-11-26 22:00
@nelstein do you mean, as opposed to 4.3.4, or to 3.x? 

I am also being hit hard by this error.

**Comment by ElaineSchwner** [comment] 2020-11-27 11:42
I downgraded to   cloud_firestore: 0.13.6
And it started working

**Comment by Auuufff** [comment] 2020-12-10 08:45
I have the same error in one user in production. It's totally inappropriate behavior.

**Comment by BastianHandly** [comment] 2020-12-16 01:03
Facing this issue too, but only on ios simulator

**Comment by zzterrozz** [comment] 2020-12-21 17:42
```
[cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
```

Keeps happening...!! what is going on ?

**Comment by iktakahiro** [comment] 2021-01-05 02:56
https://github.com/FirebaseExtended/flutterfire/issues/3521#issuecomment-723031748

Since last December 24, the same error suddenly stopped occurring. I have not made any configuration changes or upgraded any packages. Therefore, for reasons unknown, my Sentry client has gone quiet. What about you?

**Comment by BastianHandly** [comment] 2021-01-23 02:59
@iktakahiro 

I had the issue also being solved on its own. The problem is that it's still appearing here and there which is super annoying.
It's not really explainable what the reason could be, right?

**Comment by Mayb3Nots** [comment] 2021-01-25 04:47
I have this issue with some users but not all. Still no fix?

**Comment by nhat-tr** [comment] 2021-02-07 18:16
I have the same issue with cloud_firestore 0.16.0
This is my first time using cloud firestore, and just want to do very simple tasks(add, get) but it doesn't work. Cloud Firestore seems to be not so reliable.

**Comment by RamanathanN** [comment] 2021-02-23 08:06
I have the same issue. Same code working fine most of the time. One or two times it throws this error. Any solution for this?

**Comment by febg11** [comment] 2021-03-03 22:03
Just started getting this on ipad.

**Comment by pravchuk** [comment] 2021-03-04 13:45
> Make sure that in your android/build.gradle there is **classpath 'com.google.gms:google-services:4.3.3'**
> Emphasis on the version. Took me the whole day

Thanks a lot! I updated to 4.3.4

**Comment by roeniss** [comment] 2021-03-07 16:48
I just got the error in @zzterrozz comment suddenly. So I tried everything that 'maybe' solved this problem, and **it works**. I hope someone get rescue by this rambling solutions:

1. Execute `rm -rf ios/Podfile ios/Podfile.lock pubspec.lock ios/Pods && flutter clean && flutter pub get`
2. Change second line in `ios/Podfile` : `platform :ios, '10.0'` (no '#')
3. pubspec.yaml :
```yaml
# ... 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  firebase_auth: ^0.20.1
  firebase_crashlytics: ^0.4.0+1
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.15
  firebase_analytics: ^7.0.1

  intl: ^0.16.0
  equatable: ^2.0.0
  url_launcher: ^6.0.2
  device_info: ^2.0.0
  shared_preferences: ^2.0.3
  fluttertoast: ^7.1.8
  provider: ^5.0.0
  flutter_html:
  dio:
  html: 0.14.0

# ...
```

_Today morning I upgraded to flutter 2.0. So I thought maybe it would the cause. So I tried to upgrade every firebase-related dependencies to 'null-safety version (e.g. 1.0.0)'. but it doesn't work so re-downgraded all._

4. flutter doctor -v 
```bash
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.15.7 19H15 darwin-x64, locale ko-KR)
    • Flutter version 2.0.1 at /usr/local/Caskroom/flutter/2.0.1/flutter
    • Framework revision c5a4b4029c (3 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/roeniss/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/roeniss/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/roeniss/Library/Android/sdk
    • Java binary at: /Users/roeniss/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Users/roeniss/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/193.6626763/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Ultimate Edition (version 2020.3.2)
    • IntelliJ at /Users/roeniss/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.54.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 11 Pro Max (mobile) • A09F8BAA-5C6A-40E7-A3D1-BACED0EB2DBC • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 88.0.4324.192

• No issues found!
```

5. Created and used another simulator.
6. Every time I tried something, I fully quitted/deleted my debug app. 

If someone need more information about my settings, please mention me. I'll gladly responded to you.

**Comment by marcsinner** [comment] 2021-04-03 14:27
Cold restarting my flutter emulator solved it for me. 

This can be done by setting "cold restart" in Android studio, see here: https://stackoverflow.com/questions/49949818/firebaseinstanceid-token-retrieval-failed-service-not-available

**Comment by IAmJulianAcosta** [comment] 2021-04-07 03:48
This happened to me too, but it only happened if I use release buildType, if I use debug, it works fine. It fixed after rebuilding a couple of times

**Comment by vhmolinar** [comment] 2021-04-08 17:58
That error might occur whenever device is offline and there is no data inside firestore local cache. And accordingly to firebase sdk developers, it is the normal behaviour.
So, try to wrap get calls in a try/catch, handle the failure normally and you should be fine.

**Comment by dgilperez** [comment] 2021-04-09 08:57
@vhmolinar thanks! Can you share a link to where firebase SDK developers state that, or maybe some example code about how to work around / handle this failure, please? We're seeing this error occasionally on production / release and do not know how to work around it yet. Thanks a lot!

**Comment by Salakar** [comment] 2021-04-09 09:08
Moving to discussions as this isn't an issue with FlutterFire itself. Let's continue 'discussions' there.

**Closed** 2021-04-09 09:09 UTC
Labels: platform: macos, plugin: cloud_firestore, type: documentation
