### ISSUE TITLE
🐛 [firebase_crashlytics] Crashes does not show up in console

### ISSUE THREAD

**Issue by HermanKullberg** [FirebaseExtended/flutterfire#3676] opened 2020-09-28 08:22 UTC
## Bug report

**Describe the bug**

When I try to integrate firebase_crashlytics into our Flutter app and try crash it with FirebaseCrashlytics.instance.crash() the app crashes but nothing shows up in the console. It's just a spinner awaiting the first crash. This is on Android and a real device.

I'm getting the following error messages on launch:

- binding to the service failed

- Failed to retrieve settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:XXXXXXXXXXXX:android:XXXXXXXXXXXXXXXXXX/settings

I have followed the Flutterfire installation documentation found here https://firebase.flutter.dev/docs/crashlytics/overview/ and downloaded the google-service.json file and placed inside app folder.

It seems that some crashes show up on the project start page but on Crashlyctics page there is just a spinner indicating awaiting crashes.

### Expected behavior

Crashes to show up in console.

### Steps to reproduce

- Create a new flutter app.
- Create a new firebase app.
- Add firebase_crashlytics plugin to flutter.
- Configure the android build.gradle files.
- Run the app.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.4, on Microsoft Windows [Version 10.0.18363.1082], locale sv-SE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.9.2
Flutter SDK 1.20.4
KrubbApp 1.0.0+1

dependencies:
- carousel_slider 2.2.1 [flutter]
- cupertino_icons 0.1.3
- custom_navigator 0.3.0 [flutter]
- firebase_analytics 6.0.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.0 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- get_it 5.0.1 [async meta]
- http 0.12.2 [http_parser path pedantic]
- provider 4.3.2+2 [flutter nested collection]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.4.2 [collection]
- boolean_selector 2.0.0 [source_span string_scanner]
- characters 1.0.0
- charcode 1.1.3
- clock 1.0.1 [meta]
- collection 1.14.13
- fake_async 1.1.0 [clock collection]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.0.0 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.2
- matcher 0.12.8 [stack_trace]
- meta 1.1.8
- nested 0.0.4 [flutter]
- path 1.7.0
- pedantic 1.9.0
- plugin_platform_interface 1.0.2 [meta]
- quiver 2.1.3 [matcher meta]
- sky_engine 0.0.99
- source_span 1.7.0 [charcode collection meta path term_glyph]
- stack_trace 1.9.5 [path]
- stream_channel 2.0.0 [async]
- string_scanner 1.0.5 [charcode meta source_span]
- term_glyph 1.1.0
- test_api 0.2.17 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.2.0 [collection]
- vector_math 2.0.8
```

</details>

---

**Comment by darshankawar** [comment] 2020-10-01 10:34
@HermanKullberg 
A new plugin version was rolled out yesterday, https://pub.dev/packages/firebase_crashlytics/changelog.
Please upgrade and try again to see if it works for you.
Thanks.

**Comment by HermanKullberg** [comment] 2020-10-01 12:54
@darshankawar 
I have updated the plugin to the new version 0.2.1 and tried crash the app but are still receiving the same error in Android Studio console and no errors are being logged in Firebase console. I have tried on emulator with and without Google Play installed.

**Comment by SogoGolf** [comment] 2020-10-02 02:15
We are same - updated to latest version and not seeing a thing in the Firebase console. Need this resolved asap.

In addition, we run 2 x app flavors. The google-services.json for the 2nd flavor is not being seen/used (it is in the correct directory).

**Comment by TahaTesser** [comment] 2020-10-02 12:15
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/3683

**Closed by TahaTesser** 2020-10-02 12:15 UTC
Labels: Needs Attention
