### ISSUE TITLE
[Firestore_Messaging] release build failing due to androidx incompatibility

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#305] opened 2019-10-13 16:39 UTC
Note: C:\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_messaging-4.0.0+4\android\src\main\java\io\flutter\plugins\firebasemessaging\FlutterFirebaseInstanceIDService.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

debug build is working fine
release is failing

**Comment by kroikie** [comment] 2019-10-13 16:39
@bij0y

The issue at https://github.com/flutter/flutter/issues/42042 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment] 2019-10-21 13:48
Hi @bij0y
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by bij0y** [comment] 2019-10-22 18:20
Hi @iapicca 
I was using stable channel, error occurred then I switched to dev channel still got the same issue.
Then I switched to master channel it's fixed.
So I don't really know what was the problem.
I'm sorry i won't be able give you  `flutter doctor -v` & `flutter run --verbose` because my project is going on.
Thanks for your reply.
If it comes again I'll definitely post here.

**Comment by iapicca** [comment] 2019-10-23 12:15
Hi @kroikie 
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/17)addressing the case you described.
I apologize for missing it earlier.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2019-10-23 12:15 UTC
Labels: bug, waiting for customer response
