### ISSUE TITLE
🐛 [firebase_messaging] Depreciated API?

### ISSUE THREAD

**Issue by mark8044** [FirebaseExtended/flutterfire#7906] opened 2022-01-20 03:31 UTC
I'm getting the following message when I try to compile the app for a device.  App and functions seem to work ok regardless

```
Note: /.pub-cache/hosted/pub.dartlang.org/firebase_messaging-11.2.5/android/src/main/java/io/flutter/plugins/firebase/messaging/JobIntentService.java uses or overrides a deprecated API.
```

I recently had to **upgrade** Kotlin for another project and around the same time I noticed this, so I'm not sure if its related

**Comment by darshankawar** [comment] 2022-01-20 09:54
Closing this as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/7702

**Closed by darshankawar** 2022-01-20 09:54 UTC
Labels: type: bug, Needs Attention, in triage
