### ISSUE TITLE
I am not getting notification in my flutter app when app is closed.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#503] opened 2019-10-13 18:32 UTC
I am not getting notification in my flutter app when app is closed, i am using `c103 mobile`. I am using `firebase_messaging` plugin. I am getting result when app is background or foreground but when app is closed at that time I am not getting notifications. I am sending notifications from firebase console. Anyone know how to solve this problem?

here is my code
```dart
import 'package:flutter/material.dart';
import 'package:firebase_messaging/firebase_messaging.dart';

void main(){
  runApp(MaterialApp(
    home: MyApp(),
  ));
}

class MyApp extends StatefulWidget {
  @override
    State<StatefulWidget> createState() {
      return MyAppState();
    }
}

class MyAppState extends State<MyApp> {
  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();

  @override
  void initState(){
    super.initState();
    _firebaseMessaging.configure(
      onLaunch: (data){
         showDialog(
           context: context,
           builder: (BuildContext context){
             return AlertDialog(
               title: Text(data.toString()),
             );
           }
         ); 
      },
      onMessage: (data){
        showDialog(
           context: context,
           builder: (BuildContext context){
             return AlertDialog(
               title: Text(data.toString()),
             );
           }
         );
      },
      onResume: (data){
        showDialog(
           context: context,
           builder: (BuildContext context){
             return AlertDialog(
               title: Text(data.toString()),
             );
           }
         );
      }
    );
    _firebaseMessaging.getToken().then((token){
      print(token);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(),
      body: Center(
        child: Text("data"),
      ),
    );
  }
}
```

**Comment by kroikie** [comment] 2019-10-13 18:32
@91priyansh

The issue at https://github.com/flutter/flutter/issues/26692 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment] 2019-10-22 13:33
Hi @91priyansh
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by budieprof** [comment] 2019-10-28 01:26
I also had this issue, I observed that the notification works Ok on my Samsung tablet running android 5.0 lollipop but failed to work (when the app is closed) on my android phone (techno camon x pro) running android 8.0. the app in question is currently app store "https://play.google.com/store/apps/details?id=com.lascodia.churchlounge".

**Comment by iapicca** [comment] 2019-11-20 14:53
Hi @budieprof 
could you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by kirstywilliams** [comment] 2020-04-21 15:11
Closing due to lack of update w/ enough information. If experiencing this issue with an up-to-date version then please reopen.

**Closed by kirstywilliams** 2020-04-21 15:11 UTC
Labels: type: bug
