### ISSUE TITLE
Flutter messaging cloud service not working on Archived IPA 

### ISSUE THREAD

**Issue by hamza-gaya** [FirebaseExtended/flutterfire#4581] opened 2021-01-06 16:22 UTC
My token is correct. Although I have tried revoking the certificate and APN key and generated a new provisioning profile for my flutter iOS app and reconfigured my app again with this new certificate, provisioning profile and the APN key. I also removed the reference of my google info.plist file in runner in xcode and re added the reference again. I also removed my entire app from the firebase and then generated a new file google-info.plist file and then added the reference again in the xcode in main runner folder but nothing worked. Also I have tried deleting the reference and file of entitlement included in the runner folder and reconfigured capabilities of background modes and push notification but still no luck. One day before it worked magically after some time but now it’s not working on Archive IPA, Although we are recieving notifications in debug and release mode while building our app from mac. I don’t know what the fuck is going on in this stupid IOS technology. However all things are working fine and smoothly on android apk. In short I have tried all things but nothing works.
This is my raw json data while testing from post man:
{
	“to” :
    “esvDPL_gZ0PckAzrH35KWo:APA91bHMA23iTQii7y8V1Ws2BSBkVqQXA0edfcFJATdZNyHJTLUoWZbCRiPcBVjqiTAWarc4OdzyBdMVItj4V1P4MBo0i5ivoXdOFzU89XBUwsYBq7EzHDfzyiLwyGhxzVjtdQw8JYHO”,
	“collapse_key” : “New Message”,
	“notification” : {
        “body” : “Body of Your Notification”,
        “title”: “Title of Your Notification”
	},
	“data” : {
        “body” : “Body of Your Notification”,
        “title”: “Title of Your Notification”
	}
}
below is my screen shot of the result
<img width="1440" alt="Screenshot 2021-01-06 at 1 03 59 PM" src="https://user-images.githubusercontent.com/62129887/103792308-4e451000-5065-11eb-8493-b12a3b47a728.png">

**Comment by hamza-gaya** [comment] 2021-01-06 16:27
I build my flutter app using mac and xcode tool in it now it generated a fresh token and we are able to receive the notification. But when generating archive IPA and uninstalling that previous build from the iphone and then reinstalling IPA in the phone again it generates the previous token which was generated while debugging on mac.

**Comment by hamza-gaya** [comment] 2021-01-07 06:33
There is a token issue  are generated duplicate which discards both the tokens by firebase, I don't know either the problem is in ios or in the flutter messaging plugin. But in my opinion the issue persists on both the sides

**Comment by markusaksli-nc** [comment] 2021-01-13 10:34
Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4577

**Closed by markusaksli-nc** 2021-01-13 10:34 UTC
