### ISSUE TITLE
Firebase Storage PDF file is not showing in Webview only showing white screen

### ISSUE THREAD

**Issue by narimetisaigopi** [FirebaseExtended/flutterfire#2821] opened 2020-06-23 01:32 UTC
String url =
      "https://firebasestorage.googleapis.com/v0/b/campusfriend-1adac.appspot.com/o/courses%2Fbcom%2FClass%20Notes%2Fhb.pdf?alt=media&token=c8be5d46-8335-43ad-a557-99670bdb256d";
 
return WebView(
           javascriptMode: JavascriptMode.unrestricted,
           initialUrl: url,
);

**Comment by TahaTesser** [comment] 2020-06-26 10:35
Hi @narimetisaigopi 
if you're trying it on Android, there is a known [issue](https://github.com/flutter/flutter/issues/48245)

if you're facing this on iOS, from what I can see, the issue is related to a webview plugin rather than to flutterfire itself. Please open the issue in the dedicated [repository](https://github.com/flutter/flutter/issues).
Closing, as this isn't an issue with flutterfire itself. If you disagree, please write in the comments, I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-26 10:35 UTC
