### ISSUE TITLE
[firebase_messaging:^10.0.4] FirebaseMessaging.instance.getToken() don't work

### ISSUE THREAD

**Issue by gracegyu** [FirebaseExtended/flutterfire#6938] opened 2021-09-02 02:48 UTC
When I use Flutter 1.x, I successfully send push message from node.js server to my flutter app using firebase_messaging:7.0.3
I sent a token to server with below code.
```
FirebaseMessaging _firebaseMessaging;
_firebaseMessaging.getToken().then((String notiToken) {
// Code to send token to server
});
```

I migrated my flutter project to v2.x. I had to use firebase_messaging:10.0.4. And I changed my code about firebase_messaging.
```
    FirebaseMessaging.instance
        .getInitialMessage()
        .then((RemoteMessage? message) {
      if (message != null) {
        // show notification
      }
    });

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      RemoteNotification? notification = message.notification;
      AndroidNotification? android = message.notification?.android;
      if (notification != null && android != null && !kIsWeb) {
        flutterLocalNotificationsPlugin!.show(
            notification.hashCode,
            notification.title,
            notification.body,
            NotificationDetails(
              android: AndroidNotificationDetails(
                channel!.id,
                channel!.name,
                channel!.description,
                // TODO add a proper drawable resource to android, for now using
                //      one that already exists in example app.
                icon: 'launch_background',
              ),
            ));
      }
    });

    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('A new onMessageOpenedApp event was published!');
       // show notification
    });


    FirebaseMessaging.instance.getToken().then((String? token) {
      print("firebaseMessaging token : $token");
      // Code to send token to server
    });

```

I have successfully sent the token to the server. 
However, when a push notification is sent to node.js using that token, a message does not come as in v1.x.
Is the token wrong? I can't tell if the code is wrong.

Please help.

**Comment by markusaksli-nc** [comment] 2021-09-02 07:04
Hi @gracegyu 
What is the server response if you try to send to the token through node? Have you tried running the official example code?
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib
Thank you

**Comment by gracegyu** [comment] 2021-09-02 23:41
Hi @markusaksli-nc 

I looked at the source code you said and wrote my source code.
When node.js sends a push notification, a success message is output to stdout as shown below. But I don't get any notifications on my iPhone.

```
{
  multicast_id: 6460141253226654000,
  success: 1,
  failure: 0,
  canonical_ids: 0,
  results: [ { message_id: '0:1630625742453788%9be3ad159be3ad15' } ]
}
```

**Comment by gracegyu** [comment] 2021-09-03 00:00
Hi @markusaksli-nc 

Build and run your example code.
Execution works fine, but when the send button is pressed, the following message appears on the console, but no message is displayed on the screen.

```
flutter: FCM request for device sent!
```

**Comment by markusaksli-nc** [comment] 2021-09-03 06:00
Have you carefully followed all of the steps in the documentation?
https://firebase.flutter.dev/docs/messaging/apple-integration

You should also upgrade to the latest `firebase_messaging: ^10.0.6` just in case.

**Comment by gracegyu** [comment] 2021-09-06 00:00
Hi, @markusaksli-nc 

I'll try. By the way, I don't get notifications on Android either, is there any guide for that?

**Comment by gracegyu** [comment] 2021-09-06 03:01
Everything was set up according to the guide.
But the foreground notification doesn't come like the first time either.

**Comment by gracegyu** [comment] 2021-09-06 05:19
Hi, @markusaksli-nc

By setting according to your guide, ios background push notification was successful in flutter v1.x.
But in flutter v2.x, both foreground and background notifications still failed.

**Comment by markusaksli-nc** [comment] 2021-09-06 06:25
The older version of the plugin you mentioned was before a rework that completely removed a deprecated FCM channel for notifications on iOS. On the newer version, it will only send through APNs so you need to double-check that your values are all still valid and correct. Make sure the APNs key you have generated has not expired.

As for android there should be no additional configuration required after installing the plugin and doing https://firebase.flutter.dev/docs/installation/android
I have not been able to reproduce these issues on either android or iOS so the problem should be somewhere in your config. Are you overriding any native versions in your `ios/Podfile` or `android/app/build.gradle`?

**Comment by gracegyu** [comment] 2021-09-07 00:09
I will apply the sample code to my code more carefully.

**Comment by gracegyu** [comment] 2021-09-07 04:20
Hi, @markusaksli-nc

Finally, the push notification has arrived successfully.
However, push notifications do not come from the iPhone simulator. Only Real iPhones receive push notifications. What's the reason?

**Comment by markusaksli-nc** [comment] 2021-09-07 06:04
That's great news. 

What you mentioned is also documented at https://firebase.flutter.dev/docs/messaging/usage#receiving-messages
This is just a native limitation of the APNs platform so it's not really something we can fix.

Since everything else is working as intended here I'm going to close the issue for now.

**Closed by markusaksli-nc** 2021-09-07 06:04 UTC
Labels: type: bug, Needs Attention, in triage
