### ISSUE TITLE
Google Play Games Services - Social authentication

### ISSUE THREAD

**Issue by jdaibello** [FirebaseExtended/flutterfire#5303] opened 2021-03-11 00:33 UTC
Hi, good day!

Do you have a date to include the documentation of Google Play Games Services (Social Auth) implementation in https://firebase.flutter.dev/docs/auth/overview/ website? I'm looking forward to implement GPGS functionalities in my Flutter app but I think it's difficult and it isn't into the docs.

**Comment by markusaksli-nc** [comment] 2021-03-11 12:34
Hi @jdaibello 
GPGS isn't a part of native Firebase functionality, it is just a credential provider you could use for Firebase auth.

There is native documentation on how to do what you want to do https://firebase.google.com/docs/auth/android/play-games#integrate_play_games_sign-in_into_your_game but this still requires you to integrate GPGS in native, which won't work for Flutter.

As for how to use GPGS in Flutter currently - there are plugins like https://pub.dev/packages/play_games and https://pub.dev/packages/games_services but there is no official implementation yet https://github.com/FirebaseExtended/flutterfire/issues/982

As it hasn't been implemented yet and there is nothing to document I'm going to close this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/982
Thank you

**Closed by markusaksli-nc** 2021-03-11 12:34 UTC
