### ISSUE TITLE
[6.0.13] Missing Default Notification Channel metadata in AndroidManifest

### ISSUE THREAD

**Issue by z-dmitri** [FirebaseExtended/flutterfire#2266] opened 2020-03-30 13:28 UTC
When app in the background and receive push notification - error appear:
"Missing Default Notification Channel metadata in AndroidManifest"

- it is few related issues about - but no any solution

**To Reproduce**
1. Start mobile app
2. Switch to the other app
3. Send push notification for this device
4. "Missing Default Notification Channel metadata in AndroidManifest" error appear

**Comment by TahaTesser** [comment] 2020-03-30 13:42
Duplicate of [#88](https://github.com/FirebaseExtended/flutterfire/issues/88)

**Closed by TahaTesser** 2020-03-30 13:42 UTC
Labels: bug
