### ISSUE TITLE
🐛 [firebase_analytics 7.1.0] Analytics dependency causes version solving to fail with other firebase core 1.0.0 packages

### ISSUE THREAD

**Issue by Ragnaroek** [FirebaseExtended/flutterfire#5202] opened 2021-03-03 20:18 UTC
## Bug report

**Describe the bug**
Upgrading to flutter 2 fails although all firestore dependencies are updated to the latest versions.

### Steps to reproduce

flutter pub get:
Because every version of <package> from path depends on firebase_analytics 7.1.0 which depends on firebase_analytics_web ^0.2.0, every version of <package> from path requires firebase_analytics_web ^0.2.0.
And because every version of firebase_analytics_web depends on firebase ^7.3.0 which depends on http_parser ^3.0.0, every version of <package> from path requires http_parser ^3.0.0.
And because firebase_auth >=1.0.0 depends on firebase_auth_web ^1.0.0 which depends on http_parser ^4.0.0, <package> from path is incompatible with firebase_auth >=1.0.0.
So, because <app> depends on both firebase_auth 1.0.0 and <package> from path, version solving failed.

### Expected behavior

upgrade works with all firestore packages updated to the latest version

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.0, on macOS 11.2.2 20D80 darwin-x64, locale en-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.53.2)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65

(since pub get fails as described above)
```

</details>

---

**Comment by rogiervandenberg** [comment] 2021-03-03 21:36
Yes, indeed, e.g. last version of `firebase_storage` is 8.0.0. But, `firebase_storage >=8.0.0 depends on firebase_storage_web ^1.0.0 which depends on http ^0.13.0`

You cannot combine that with the latest `firebase_analytics`:
```
Because every version of firebase_analytics_web depends on firebase ^7.3.0 which depends on http >=0.11.3 <0.13.0, every version of firebase_analytics_web requires http >=0.11.3 <0.13.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0, firebase_analytics >=7.1.0 requires http >=0.11.3 <0.13.0.
So, because embrosa_pics depends on both firebase_analytics ^7.1.0 and http ^0.13.0, version solving failed.
```

..as it needs http 0.12

**Comment by markusaksli-nc** [comment] 2021-03-04 13:29
Seems like analytics is causing all the issues, everything else is compatible.
```yaml
  cloud_firestore: ^1.0.0
  cloud_functions: ^1.0.0
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0
  firebase_remote_config: ^0.9.0-dev.0
  firebase_dynamic_links: ^0.8.0
  firebase_performance: ^0.6.0
  google_mobile_ads: ^0.11.0+1
  #firebase_analytics: ^7.1.0
```

**Comment by markusaksli-nc** [comment] 2021-03-04 13:47
Seems like both `https` and `http_parser` cause issues
```
Because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, firebase_analytics >=7.1.0 requires firebase ^7.3.0.
And because firebase >=5.0.3 <9.0.0 depends on http >=0.11.3 <0.13.0, firebase_analytics >=7.1.0 requires http >=0.11.3 <0.13.0.
And because firebase_storage >=8.0.0 depends on firebase_storage_web ^1.0.0 which depends on http ^0.13.0, firebase_analytics >=7.1.0 is incompatible with firebase_storage >=8.0.0.
So, because triage depends on both firebase_storage ^8.0.0 and firebase_analytics ^7.1.0, version solving failed.
```

**Comment by comlaterra** [comment] 2021-03-04 17:17
If I'm not wrong you can just remove the `firebase_analytics_web: ^0.2.0` dependency from analytics.
I think it is not even used

**Comment by finroly** [comment] 2021-03-04 17:47
firebase_analytics_web is included in firebase_analytics. how can we remove? Please explain

**Comment by gianlucainnocente** [comment] 2021-03-04 18:59
Same problem here

**Comment by augustkimo** [comment] 2021-03-04 23:28
Today I migrated to Flutter 2.0 and started using all the newest Firebase packages, but like others the only one I can't use is Analytics due to compatibility problems. Hopefully we get a fix soon, thanks!

```
  firebase_auth: ^1.0.0 #auth
  cloud_functions: ^1.0.0 #functions
  cloud_firestore: ^1.0.0 #just used to handle timestamp objects
  firebase_storage: ^8.0.0 #upload media/files to storage
  firebase_core: ^1.0.0
  firebase_analytics: ^7.0.0
```
```
Because no versions of firebase_storage match >8.0.0 <9.0.0 and firebase_storage 8.0.0 depends on firebase_storage_web ^1.0.0, firebase_storage ^8.0.0 requires firebase_storage_web ^1.0.0.
And because no versions of firebase_storage_web match >1.0.0 <2.0.0 and firebase_storage_web 1.0.0 depends on http ^0.13.0, firebase_storage ^8.0.0 requires http ^0.13.0.
And because every version of firebase_analytics_web depends on firebase ^7.3.0 which depends on http >=0.11.3 <0.13.0, firebase_storage ^8.0.0 is incompatible with firebase_analytics_web.
Because firebase_analytics >=5.0.16 <7.1.0 depends on firebase_analytics_web ^0.1.0 and firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0, firebase_analytics >=5.0.16 requires firebase_analytics_web ^0.1.0 or ^0.2.0.
Thus, firebase_storage ^8.0.0 is incompatible with firebase_analytics >=5.0.16.
So, because simple_money depends on both firebase_storage ^8.0.0 and firebase_analytics ^7.0.0, version solving failed.
```

When it says "Because no versions of firebase_storage match >8.0.0", it's saying the version needs to be great than, or equal to or greater than 8.0.0? Because v8.0.0 of storage is the newest available.

**Comment by HughesWang** [comment] 2021-03-05 05:53
I got the same problem.

**Comment by w3ggy** [comment] 2021-03-05 07:06
Same problem

**Comment by dukaric1991** [comment] 2021-03-05 07:46
I removed firebase_analytics_web: ^0.2.0 from firebase_analytics and still not working.

**Comment by markusaksli-nc** [comment] 2021-03-05 09:27
Please thumbs up the original issue comment instead of commenting that you have the same issue unless you have something to add to the discussion. That allows us to better track how many are facing the problem.

**Comment by shic** [comment] 2021-03-05 11:53
My packages are:

```
  cloud_firestore: ^1.0.0
  firebase_analytics: ^7.1.0
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  firebase_crashlytics: ^1.0.0
  firebase_messaging: ^9.0.0
  firebase_storage: ^8.0.0

```

and got error:
```


Because no versions of firebase_storage match >8.0.0 <9.0.0 and firebase_storage 8.0.0 depends on firebase_storage_web ^1.0.0, firebase_storage ^8.0.0 requires firebase_storage_web ^1.0.0.
And because no versions of firebase_storage_web match >1.0.0 <2.0.0, firebase_storage ^8.0.0 requires firebase_storage_web 1.0.0.
And because firebase_storage_web 1.0.0 depends on http ^0.13.0 and firebase >=5.0.3 <9.0.0 depends on http >=0.11.3 <0.13.0, firebase_storage ^8.0.0 is incompatible with firebase >=5.0.3 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, firebase_storage ^8.0.0 is incompatible with firebase_analytics >=7.1.0.
So, because leopard depends on both firebase_analytics ^7.1.0 and firebase_storage ^8.0.0, version solving failed.
pub get failed (1; So, because leopard depends on both firebase_analytics ^7.1.0 and firebase_storage ^8.0.0, version solving failed.)
```

**Comment by devHamza** [comment] 2021-03-05 12:06
I've tried to upgrade my firebase dependencies, got the same issue with firebase_analytics : 

```
  firebase_core: ^1.0.0
  firebase_auth: ^1.0.0
  firebase_crashlytics: ^1.0.0
  firebase_database: ^6.1.0
  firebase_messaging: ^9.0.0
  firebase_analytics: ^7.1.0
  cloud_firestore: ^1.0.0
  firebase_storage: ^8.0.0
  cloud_functions: ^1.0.0
```

I got : 

```
Because no versions of firebase_storage match >8.0.0 <9.0.0 and firebase_storage 8.0.0 depends on firebase_storage_web ^1.0.0, firebase_storage ^8.0.0 requires firebase_storage_web ^1.0.0.
And because no versions of firebase_storage_web match >1.0.0 <2.0.0, firebase_storage ^8.0.0 requires firebase_storage_web 1.0.0.
And because firebase_storage_web 1.0.0 depends on http ^0.13.0 and firebase >=5.0.3 <9.0.0 depends on http >=0.11.3 <0.13.0, firebase_storage ^8.0.0 is incompatible with firebase >=5.0.3 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, firebase_storage ^8.0.0 is incompatible with firebase_analytics >=7.1.0.
So, because cait_mobile depends on both firebase_analytics ^7.1.0 and firebase_storage ^8.0.0, version solving failed.
pub get failed (1; So, because cait_mobile depends on both firebase_analytics ^7.1.0 and firebase_storage ^8.0.0, version solving failed.)

```

when I remove the `firebase_analytics` dependency everything works well.

**Comment by marcosmko** [comment] 2021-03-05 23:56
for now, I downgraded firebase_analytics to `5.0.15`, don't know why but I can use it with the other packages
```
  firebase_analytics: ^5.0.15
  firebase_auth: ^1.0.0
  firebase_auth_web: ^1.0.0
  firebase_core: ^1.0.0
  firebase_crashlytics: ^1.0.0
```

(I'm actually in process of migrating my project, don't know if it can run yet)

**Comment by SwiftWinds** [comment] 2021-03-06 01:58
> for now, I downgraded firebase_analytics to `5.0.15`, don't know why but I can use it with the other packages
> 
> ```
>   firebase_analytics: ^5.0.15
>   firebase_auth: ^1.0.0
>   firebase_auth_web: ^1.0.0
>   firebase_core: ^1.0.0
>   firebase_crashlytics: ^1.0.0
> ```
> 
> (I'm actually in process of migrating my project, don't know if it can run yet)

While this does allow `flutter pub get` to run without errors, I get `Unhandled Exception: LateInitializationError: Field '_debugId@633412286' has not been initialized.` while running the app.

**Comment by MohamedEL-Torky** [comment] 2021-03-07 10:04
Use 
`
firebase_analytics: any
`
This lets the analyzer choose the version that would work with your project which is probably 5.0.15.
Why 5.0.15, because firebase analytics web was not introduced at this version yet. Anyway after doing so keep an eye on this issue or on pub dev for any updates to be able to use all the latest features when they release a fix.

**Comment by Djmartel** [comment] 2021-03-07 16:46
> Use
> `firebase_analytics: any`
> This lets the analyzer choose the version that would work with your project which is probably 5.0.15.
> Why 5.0.15, because firebase analytics web was not introduced at this version yet. Anyway after doing so keep an eye on this issue or on pub dev for any updates to be able to use all the latest features when they release a fix.

If I do this I get

**Comment by MohamedEL-Torky** [comment] 2021-03-07 16:55
> > Use
> > `firebase_analytics: any`
> > This lets the analyzer choose the version that would work with your project which is probably 5.0.15.
> > Why 5.0.15, because firebase analytics web was not introduced at this version yet. Anyway after doing so keep an eye on this issue or on pub dev for any updates to be able to use all the latest features when they release a fix.
> 
> If I do this I get
> `[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
> In snapshot (Podfile.lock):
> Firebase/CoreOnly (= 7.3.0)
> 
> ```
>   In Podfile:
>     firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 0.0.1, which depends on
>       Firebase/Analytics (~> 6.0) was resolved to 6.0.0, which depends on
>         Firebase/Core (= 6.0.0) was resolved to 6.0.0, which depends on
>           Firebase/CoreOnly (= 6.0.0)
> 
>     firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 1.0.0, which depends on
>       Firebase/CoreOnly (= 7.3.0)`
> ```

Try the following

`
#
# Other packages
#
firebase_analytics: 7.1.0
#
# Other packages
#
dependency_overrides:
  http: ^0.13.0
`
This might work but you will override every package calling http as a dependency to that specific version and it might cause some unexpected errors.

**Comment by Djmartel** [comment] 2021-03-07 17:16
@MohamedEL-Torky Getting this now 
`    [!] CocoaPods could not find compatible versions for pod "nanopb":
      In snapshot (Podfile.lock):
        nanopb (= 2.30907.0, ~> 2.30907.0)

      In Podfile:
        firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 7.1.0, which depends on
          Firebase/Analytics (= 7.3.0) was resolved to 7.3.0, which depends on
            Firebase/Core (= 7.3.0) was resolved to 7.3.0, which depends on
              FirebaseAnalytics (= 7.3.0) was resolved to 7.3.0, which depends on
                nanopb (~> 2.30906.0)

        firebase_database (from `.symlinks/plugins/firebase_database/ios`) was resolved to 6.1.0, which depends on
          Firebase/Database (= 7.3.0) was resolved to 7.3.0, which depends on
            FirebaseDatabase (~> 7.3.0) was resolved to 7.3.0, which depends on
              FirebaseCore (~> 7.0) was resolved to 7.3.0, which depends on
                FirebaseCoreDiagnostics (~> 7.0) was resolved to 7.7.0, which depends on
                  nanopb (~> 2.30907.0)`

**Comment by MohamedEL-Torky** [comment] 2021-03-07 17:30
Try reproducing your pod files again

```
flutter clean
cd ios/
pod deintegrate
pod cache clean --all
rm Podfile
flutter pub get
flutter run -v
```

and keep a close eye on the output of the -v maybe there is an internal error with one of the packages. if it does work we can't do anything else only wait for a hotfix

> @MohamedEL-Torky Getting this now
> ` [!] CocoaPods could not find compatible versions for pod "nanopb":
> In snapshot (Podfile.lock):
> nanopb (= 2.30907.0, ~> 2.30907.0)
> 
> ```
>   In Podfile:
>     firebase_analytics (from `.symlinks/plugins/firebase_analytics/ios`) was resolved to 7.1.0, which depends on
>       Firebase/Analytics (= 7.3.0) was resolved to 7.3.0, which depends on
>         Firebase/Core (= 7.3.0) was resolved to 7.3.0, which depends on
>           FirebaseAnalytics (= 7.3.0) was resolved to 7.3.0, which depends on
>             nanopb (~> 2.30906.0)
> 
>     firebase_database (from `.symlinks/plugins/firebase_database/ios`) was resolved to 6.1.0, which depends on
>       Firebase/Database (= 7.3.0) was resolved to 7.3.0, which depends on
>         FirebaseDatabase (~> 7.3.0) was resolved to 7.3.0, which depends on
>           FirebaseCore (~> 7.0) was resolved to 7.3.0, which depends on
>             FirebaseCoreDiagnostics (~> 7.0) was resolved to 7.7.0, which depends on
>               nanopb (~> 2.30907.0)`
> ```

Try reproducing your pod files again

```
flutter clean
cd ios/
pod deintegrate
pod cache clean --all
rm Podfile
flutter pub get
flutter run -v
```

and keep a close eye on the output of the -v maybe there is an internal error with one of the packages. if it does work we can't do anything else only wait for a hotfix

**Comment by yamauchieduardo** [comment] 2021-03-08 14:05
I don't update my projet to Flutter 2.0 because of this. We have some dates to the new version of analytics, compatible with the core 1.0?

**Comment by samtstern** [comment] 2021-03-09 10:20
@FirebaseExtended/invertase can someone take a look at this one?

**Comment by woutervanwijk** [comment] 2021-03-09 10:46
Internally inconsistent versioning should not happen in important packages like firebase. And it should be fixed asap

**Comment by rrousselGit** [comment] 2021-03-09 10:58
`firebase` is maintained by a completely different team, hence why that happened.

But we got a fix

**Closed** 2021-03-09 11:38 UTC
Labels: impact: crowd, plugin: analytics, type: bug

**Comment by Salakar** [comment] 2021-03-09 12:11
:wave: `firebase_analytics` version `7.1.1` is now available with a fix.

**Comment by mibo-fdc** [comment] 2021-03-10 16:17
This worked for us! Thanks for the fix!
