### ISSUE TITLE
Firebase Crashlytics: Upgrade from Fabric to Firebase Crashlytics SDK

### ISSUE THREAD

**Issue by sur950** [FirebaseExtended/flutterfire#2849] opened 2020-06-26 07:32 UTC
**Is your feature request related to a problem? Please describe.**
When I tried to upgrade my Crashlytics Plugin, it throws could not find method.

**Describe the solution you'd like**
I realised that this need to be implemented from plugin side as well.

Here's the link to new implementation
https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android

P.S: I get mails from firebase team to upgrade the Crashlytics SDK as the existing one is going to be deprecated. 

Thanks.

**Comment by TahaTesser** [comment] 2020-06-26 12:41
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2038

**Closed by TahaTesser** 2020-06-26 12:41 UTC
