### ISSUE TITLE
🐛 [cloud_firestore] "Error: unsupported_event at https://www.gstatic.com/firebasejs/8.4.1/firebase-auth.js:1:104874"

### ISSUE THREAD

**Issue by Ryeori** [FirebaseExtended/flutterfire#6129] opened 2021-05-12 18:14 UTC
When adding firebase_auth and cloud_firestore (both simultaneously) to a project - web app will throw an firestore exception.

### Steps to reproduce

1. Create clean flutter project
2. Add a "firebase_core", "firebase_auth" and "cloud_firestore" dependencies to a pubspec.yaml
3. In Firebase console add new web app
4. Paste firebase config to your index.html body tag.
5. add firestore and auth CDN link's in index.html
6. Add binding and firebase initialization into main.dart

`void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}`

7. Enable all breakpoints in your IDE
8. Run web app

### Expected behavior

The counter app will opens up in chrome and no errors should be in debug or anywhere else.

## Additional context

This issue only shows up in web and when both auth and cloud_firestore are added to a project.
Used CDN's - 8,4.1, 8.5.0, 8.6.0. Nothing worked.

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.0.6, on Microsoft Windows [Version 10.0.19042.746], locale ru-RU)
    • Flutter version 2.0.6 at C:\src\flutter
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Daniil\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6842174)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/windows#android-setup for detailed instructions).

[√] IntelliJ IDEA Community Edition (version 2021.1)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2021.1.1
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] VS Code (version 1.56.1)
    • VS Code at C:\Users\Daniil\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.22.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.56
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.3  
Flutter SDK 2.0.6
testerror 1.0.0+1

dependencies:
- cloud_firestore 2.1.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- firebase_auth 1.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.0.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.0.1 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 4.2.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.0.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---
### Test repository
https://github.com/Ryeori/event_error_test

**Comment by rrousselGit** [comment] 2021-05-13 11:59
I tried but don't have any issue.

Maybe you could create a reproduction repository?

**Comment by clockwiser** [comment] 2021-05-13 15:24
I met the similar problem.

Exception has occurred.
"Error: unsupported_event
    at https://www.gstatic.com/firebasejs/8.6.1/firebase-auth.js:1:104874"

**Comment by clockwiser** [comment] 2021-05-15 13:56
Well, that error disappeared, don't know why. I can't reproduce the error.

**Comment by Ryeori** [comment] 2021-05-19 23:15
> I tried but don't have any issue.
> 
> Maybe you could create a reproduction repository?

So, i really have no idea, i tested on flutter 2.0.6 and 2.2.0 with firebase CDN 8.6.1 on clean project(nothing more than a firebase core, auth and firestore with analytics, firebase initialization in main()) and the error is still occurs. I've created a repository thats throws me an error(turn on all exceptions to make sure) https://github.com/Ryeori/event_error_test

**Comment by Beautylivery** [comment] 2021-08-18 09:00
I now run into a similar issue using the web.
The Error strangely occurs after I implemented Phone authentication and registered my first user with Phone and Pin. 
Afterward, I deleted the user in firebase, and since then, I get the same error thrown in this method.

`/// Stream of [AppUser] which will emit the current user when
  /// the authentication state changes.
  ///
  /// Emits [AppUser.empty] if the user is not authenticated.
  Stream<AppUser> get user {
    return _firebaseAuth.authStateChanges().map((firebaseUser) {
      User? firebaseUser = _firebaseAuth.currentUser;
      if (firebaseUser != null)
        _user = AppUser(
            id: firebaseUser.uid,
            name: firebaseUser.displayName,
            phone: firebaseUser.phoneNumber);
      else
        _user = AppUser.empty;
      return _user;
    });
  }`

**Comment by markusaksli-nc** [comment] 2021-09-10 09:41
I tried to reproduce this on the latest versions
```yaml
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.0
  cloud_firestore: ^2.5.1
  firebase_analytics: ^8.3.2
```
```html
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-analytics.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js"></script>
```
but I'm not seeing anything.

Based off of https://github.com/FirebaseExtended/flutterfire/issues/6129#issuecomment-844559194 (`turn on all exceptions to make sure`) could this be just another VSCode over-eager debugger issue that isn't reproducible in other IDEs or in release?

**Comment by russellwheatley** [comment] 2021-09-14 09:20
@Beautylivery, that is a warning message indicating that Flutterfire is only tested against `firebase-js-sdk` version `8.6.1`. You're free to use `8.9.1` but none of the plugins are tested against it so the API may differ causing you issues.

**Comment by russellwheatley** [comment] 2021-09-14 09:24
As @markusaksli-nc, your test project isn't reproducible which suggests a problem in your setup (perhaps VS Code as mentioned). Closing for now, but just to reiterate, make sure you use version `8.6.1` as every plugin uses in each `/example` project.

**Closed by russellwheatley** 2021-09-14 09:24 UTC
Labels: type: bug, plugin: cloud_firestore, platform: web, resolution: needs-repro
