### ISSUE TITLE
🐛 [firebase_messaging] getToken() throws an exception in some cases

### ISSUE THREAD

**Issue by Giuspepe** [FirebaseExtended/flutterfire#7112] opened 2021-10-01 15:02 UTC
## Bug report

**Describe the bug**
Our app calls `getToken()` when initializing. This normally works.

When running integration tests on Firebase Test Lab however, the call to `getToken()` sometimes throws an error and we have no idea why. If I rerun the integration tests on the same device type it works again.

### Steps to reproduce
No idea.

This is the relevant log I see in Firebase Test Lab:
```
java.lang.Exception: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following FirebaseException was thrown running a test:
[firebase_messaging/unknown] java.io.IOException:
java.util.concurrent.ExecutionException: java.io.IOException:
AUTHENTICATION_FAILED
When the exception was thrown, this was the stack:
#0 MethodChannelFirebaseMessaging.getToken (package:firebase_messaging_platform_interface/src/method_channel/method_channel_messaging.dart:229:7)
```

### Expected behavior

Print more details on why the exception is thrown. Or better, do not throw an exception at all.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.2 20D64 darwin-x64, locale en-DE)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2021.2.2)
[✓] VS Code (version 1.60.2)
[✓] Connected device (2 available)

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.2
Flutter SDK 2.5.1
hallesche4u 1.0.3+37

dependencies:
- alh_file_picker 0.0.1 [flutter file_picker]
- alh_pdf_view 0.0.1 [flutter]
- api_alh_service 0.0.1 [flutter equatable http dartz]
- carousel_slider 4.0.0 [flutter]
- collection 1.15.0
- dartz 0.10.0
- device_info 2.0.2 [flutter device_info_platform_interface]
- encrypt 5.0.1 [args asn1lib clock collection crypto pointycastle]
- equatable 2.0.3 [collection meta]
- firebase_core 1.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.2.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 10.0.7 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.3.0 [flutter bloc provider]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_jailbreak_detection 1.8.0 [flutter]
- flutter_local_notifications 8.2.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_secure_storage 4.2.1 [meta flutter]
- flutter_speed_dial 3.0.5 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- get_it 6.1.1 [async collection]
- image 3.0.5 [archive meta xml]
- in_app_review 2.0.3 [flutter in_app_review_platform_interface]
- intersperse 2.0.0
- intl 0.17.0 [clock path]
- local_auth 1.1.8 [flutter flutter_plugin_android_lifecycle intl meta platform]
- logger 1.0.0
- lottie 1.2.1 [archive characters flutter path vector_math]
- modal_bottom_sheet 2.0.0 [flutter]
- overflow_view 0.3.1 [flutter value_layout_builder]
- overlay_support 1.2.1 [flutter async]
- package_info 2.0.2 [flutter]
- path 1.8.0
- path_provider 2.0.5 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- pdf 3.6.0 [archive barcode crypto image meta path_parsing vector_math xml]
- pedantic 1.11.1
- photo_view 0.12.0 [flutter]
- platform 3.0.0
- printing 5.6.0 [ffi flutter flutter_web_plugins http image js meta pdf plugin_platform_interface]
- scanbot_sdk 2.6.0 [logging json_annotation flutter]
- share_plus 2.1.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- storeanythin_alh_service 0.0.1 [flutter equatable get_storage path_provider collection encrypt]
- url_launcher 6.0.12 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.4 [crypto]
- webview_flutter 2.1.1 [flutter webview_flutter_platform_interface webview_flutter_android webview_flutter_wkwebview]

dev dependencies:
- bloc_test 8.2.0 [bloc meta mocktail test]
- build_runner 1.12.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service archive async boolean_selector characters charcode clock collection crypto fake_async file matcher meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math webdriver]
- mocktail 0.1.4 [collection matcher test]
- test 1.17.10 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 26.0.0 [meta]
- analyzer 2.3.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.3.0
- asn1lib 1.0.2
- async 2.8.1 [collection meta]
- barcode 2.1.0 [meta qr]
- bloc 7.2.1 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.3 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.7 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 6.1.12 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.2 [built_collection collection fixnum meta]
- characters 1.1.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.3 [meta path]
- clock 1.1.0
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- convert 3.0.1 [typed_data]
- coverage 1.0.3 [args logging package_config path source_maps stack_trace vm_service]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.2.0 [analyzer args path pub_semver source_span]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- file_picker 4.1.2 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.2 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.5 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_local_notifications_platform_interface 4.0.1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.3 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- get 4.3.8 [flutter]
- get_storage 2.0.3 [flutter get path_provider]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 1.0.0
- http 0.13.3 [async http_parser meta path pedantic]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- in_app_review_platform_interface 2.0.2 [flutter url_launcher plugin_platform_interface platform]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.1.0 [meta]
- logging 1.0.2
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- node_preamble 2.0.1
- package_config 2.0.2 [path]
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- petitparser 4.3.0 [meta]
- plugin_platform_interface 2.0.1 [meta]
- pointycastle 3.3.4 [collection convert js]
- pool 1.5.0 [async stack_trace]
- process 4.2.3 [file path platform]
- provider 6.0.1 [collection flutter nested]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.1.0 [checked_yaml collection json_annotation pub_semver yaml]
- qr 2.1.0 [meta]
- rxdart 0.27.2
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.3.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.0 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timezone 0.8.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- value_layout_builder 0.3.1 [flutter]
- vector_math 2.1.0
- vm_service 7.1.1
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.0.0 [logging]
- webview_flutter_android 2.0.14 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.0.0 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.0.14 [flutter webview_flutter_platform_interface]
- win32 2.2.9 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-10-04 07:26
Hi @Giuspepe 
This is a native issue in the SDK, not our plugins. The issue is tracked on the repo [here](https://github.com/firebase/firebase-android-sdk/issues/1286), it also has its own ticket [here](https://issuetracker.google.com/issues/143413382) on the Google issue tracker.

This concerns both error messages: `SERVICE_UNAVAILABLE` & `AUTHENTICATION_FAILED`. There are a number of workarounds on the repo ticket such as updating Google Play Store on the device, but you might want to try this [first](https://github.com/firebase/firebase-android-sdk/issues/1286#issuecomment-884117864) if it helps although this is two major versions behind the version currently used by `Flutterfire`.  

I'm closing this issue as there isn't anything for us to fix, this issue needs to be resolved upstream.
Thank you

**Closed by markusaksli-nc** 2021-10-04 07:26 UTC
Labels: type: bug, Needs Attention, in triage
