### ISSUE TITLE
🐛 [cloud_firestore] Null safety support is broken on the Web

### ISSUE THREAD

**Issue by lukaszciastko** [FirebaseExtended/flutterfire#5283] opened 2021-03-09 19:22 UTC
Whenever I try to use cloud_firestore on the Web with null safety enabled, I get the following error:

```
[cloud_firestore/unknown] Expected a value of type '((Object?) => Object)?', but got one of type '(Object) => Object?'
```

To reproduce, create a simple document in a collection. For example:

<img width="561" alt="Screenshot 2021-03-09 at 20 17 33" src="https://user-images.githubusercontent.com/964414/110525125-84aa1480-8114-11eb-8209-adad7cd12fd0.png">

And then try to listen to this collection in a Flutter web app:

```dart
class TestView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return StreamBuilder<QuerySnapshot>(
      stream: snapshots(),
      builder: (context, snapshot) {
        if (snapshot.hasError) {
          return Center(
            child: Text('Error: ${snapshot.error}'),
          );
        }
        return Center(
          child: Text('Documents: ${snapshot.data?.docs.length ?? 0}'),
        );
      },
    );
  }

  Stream<QuerySnapshot> snapshots() {
    return FirebaseFirestore.instance.collection('public').snapshots();
  }
}
```

Expected:

<img width="222" alt="Screenshot 2021-03-09 at 20 19 55" src="https://user-images.githubusercontent.com/964414/110525433-dd79ad00-8114-11eb-8347-d875129239cb.png">

Actual:

<img width="819" alt="Screenshot 2021-03-09 at 20 20 05" src="https://user-images.githubusercontent.com/964414/110525450-e36f8e00-8114-11eb-8016-80f70bfcc0f6.png">

As soon as I disable null safety, everything works as expected (by running with --no-sound-null-safety).

This issue only exists on the web - on mobile and desktop, everything is OK.

```
Flutter (Channel stable, 2.0.1, on macOS 11.1 20C69 darwin-x64, locale en-GB)

    firebase_core: ^1.0.0
    firebase_auth: ^1.0.0
    cloud_firestore: ^1.0.0
```

**Comment by markusaksli-nc** [comment] 2021-03-10 08:23
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/5050 and already fixed

**Closed by markusaksli-nc** 2021-03-10 08:23 UTC
Labels: Needs Attention, type: bug
