### ISSUE TITLE
[Firebase_messaging] PluginRegistry cannot be converted to FlutterEngine

### ISSUE THREAD

**Issue by Nagarajnaidu921** [FirebaseExtended/flutterfire#2238] opened 2020-03-26 15:55 UTC
**Describe the bug**
In my application I had to implement the FCM with background notification. To implement that I followed the steps given in official doc [Docs](https://pub.dev/packages/firebase_messaging#optionally-handle-background-messages) but got the Error saying **PluginRegistry cannot be converted to FlutterEngine** and the build failed

  firebase_messaging: ^6.0.9
and 
'com.google.firebase:firebase-messaging:20.1.3' is used
![Screenshot from 2020-03-26 21-21-58](https://user-images.githubusercontent.com/20486700/77667345-11ad9980-6fa8-11ea-994a-175bdeeeda16.png)

`flutter doctor`
`[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.43.2)
[✓] Connected device (1 available)

• No issues found!
`
please help me to solve the issue

**Comment by TahaTesser** [comment] 2020-03-27 09:17
duplicate of [#1729](https://github.com/FirebaseExtended/flutterfire/issues/1729)

**Closed by TahaTesser** 2020-03-27 09:17 UTC
Labels: bug
