### ISSUE TITLE
`firebase_core` not found for flutter_web (Flutter 1.9)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1128] opened 2019-10-13 19:43 UTC
I upgraded my flutter to 1.9, and trying out flutter-web for an existing project. Got stuck at "firebase_core" is not found error  anyone experiencing the same issue ? Here's error:
```
i$ flutter run -d Chrome
Launching lib/main.dart on Chrome in debug mode...
Skipping compiling flutter_widgets|lib/main_web_entrypoint.dart with ddc because some of its
transitive libraries have sdk dependencies that not supported on this platform:
firebase_core|lib/firebase_core.dart
```

**Comment by kroikie** [comment] 2019-10-13 19:43
@ptyagicodecamp

The issue at https://github.com/flutter/flutter/issues/40360 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by johnpryan** [comment] 2019-10-28 20:22
Is this a dupe of https://github.com/FirebaseExtended/flutterfire/issues/40?

**Comment by BondarenkoStas** [comment] 2019-10-29 11:15
@johnpryan thank you, you are right, rather a more specific case. So I think it would be correct to close this one, please upvote and follow it in #40.

**Closed by BondarenkoStas** 2019-10-29 11:15 UTC
Labels: enhancement
