### ISSUE TITLE
🐛 [firebase_core/cloud_firestore] timestamp value in DocumentSnapshot represented differently between iOS and Web platform

### ISSUE THREAD

**Issue by alexagat** [FirebaseExtended/flutterfire#4149] opened 2020-11-19 06:38 UTC
## Bug report

**Describe the bug**
After updating from `firebase_core: 0.5.1` to `firebase_core: 0.5.2` and `cloud_firestore: 0.14.2` to `cloud_firestore: 0.14.3` (which appear to happen together) Firestore timestamp data is represented differently between iOS and web platforms, and breaks existing code.

On mobile (e.g. iOS), data stored in Firestore as a timestamp is returned in the `DoucmentSnapshot` as the following type: `Timestamp (Timestamp(seconds=1566212558, nanoseconds=0))`

On web, data stored in Firestore as a timestamp is returned in the `DoucmentSnapshot` as the following type:`Map (2 items), 0: "seconds" -> 1566212558, 1: "nanoseconds: -> 0`

In the previous versions (0.5.1 and 0.14.2 respectively), the data was returned consistently as: `Timestamp (Timestamp(seconds=1566212558, nanoseconds=0))`

This breaks converting the data to a Dart DateTime object as such: `doc['timestamp'].toDate()` for web.

### Steps to reproduce

1. Add timestamp data to your Firestore database
2. Pull the data down and inspect the relevant `DocumentSnapshot` that contains the timestamp value

### Expected behavior

Consistent representation of same data type across iOS/Android/Web platforms

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.51.1)
[✓] Connected device (4 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.11.0-213.1.beta
Flutter SDK 1.23.0-18.1.pre
study 0.1.8+3

dependencies:
- cloud_firestore 0.14.3 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.0
- firebase_analytics 6.2.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.3 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
```

</details>

---

**Comment by yelkamel** [comment] 2020-11-19 13:20
it's the same here

**Comment by yelkamel** [comment] 2020-11-19 13:21
I have the same issue, I don't know how to fix it :/ 

Do you think if I downgrade it's will work ?

**Comment by alexagat** [comment] 2020-11-19 14:49
> I have the same issue, I don't know how to fix it :/
> 
> Do you think if I downgrade it's will work ?

Yes, you can fix the versions of these packages in the `pubspec.yaml` as follows:

```
dependencies:
  flutter:
    sdk: flutter
  ...other depedencies
  cloud_firestore: 0.14.2
  firebase_core: 0.5.1
```

**Comment by markusaksli-nc** [comment] 2020-11-20 10:45
Hi @alexagat 
Could you share the import in your `index.html`? I could not reproduce this on the latest master `1.24.0-8.0.pre.321` with
```yaml
  firebase_core: ^0.5.2
  cloud_firestore: ^0.14.3
```
```html
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>
```
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.321, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.321 at C:\Development\flutter_master
    • Framework revision 05dadb0120 (9 hours ago), 2020-11-20 07:33:05 +0530
    • Engine revision a0da844845
    • Dart version 2.12.0 (build 2.12.0-50.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 86.0.4240.198
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 86.0.622.68

• No issues found!

```
</details>
<details>
 <summary>Code sample</summary>

```dart
import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text("Timestamp example"),
        ),
        body: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceEvenly,
            children: [
              RaisedButton(
                child: Text("Set timestamp"),
                onPressed: () async {
                  await FirebaseFirestore.instance.collection('test').doc('testTime').set({"time": Timestamp.now()}).catchError((e, s) => print("$e\n$s"));
                  print("Set successfully");
                },
              ),
              RaisedButton(
                onPressed: () async {
                  var doc = (await FirebaseFirestore.instance.collection('test').doc('testTime').get());
                  print(doc['time']);
                  print(doc['time'].toDate());
                },
                child: Text("Get timestamp"),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
```
</details>

Produces the same output on both Android and web
```
Set successfully
Timestamp(seconds=1605868814, nanoseconds=456000000)
2020-11-20 12:40:14.456
```

**Comment by alexagat** [comment] 2020-11-20 17:54
@markusaksli-nc ok, I've realized that there is more to this issue! First, to answer your question, I was on the `beta` channel and was importing version `8.0.0` in my `index.html` (although I see `8.1.1` is latest), but that is not the problem.

I realized through setting up a sample project (using your code from above), the issue crops up when I have a timestamp value set on a map that is embedded inside an `array`.

![firestore-doc](https://user-images.githubusercontent.com/1205855/99832596-677e1580-2b26-11eb-8de6-b92619ffc1f5.png)

The issue can **not** be reproduced with just a standalone timestamp value on a `document`, like I originally thought. For example, your sample code above works with the upgraded `firebase_core ` and `cloud_firestore` package versions. BUT, when I modify the code as below, I can reproduce the original issue only with the upgraded firestore packages, and hopefully, you can too.

To clarify, if I run the sample code below with the downgraded versions of `firebase_core: 0.5.1` and `cloud_firestore: 0.14.2` I do not receive any errors, and data is properly updated in my Firestore collection.

### Sample Code To Reproduce Issue
`pubspec.yaml`

```
firebase_core: ^0.5.2
cloud_firestore: ^0.14.3
```

`index.html`

```
<script src="https://www.gstatic.com/firebasejs/8.0.0/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/8.0.0/firebase-firestore.js"></script>
```

`main.dart`
<details><summary>Click To Expand</summary>

```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Flutter Demo',
      home: HomeView(),
    );
  }
}

class HomeView extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Timestamp example"),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          children: [
            RaisedButton(
              child: Text("Set timestamp"),
              onPressed: () async {
                await FirebaseFirestore.instance
                    .collection('test')
                    .doc('doc')
                    .set({
                  "times": [
                    {
                      "time": DateTime.now(),
                    }
                  ]
                }).catchError((e, s) => print("$e\n$s"));
                print("Set successfully");
              },
            ),
            RaisedButton(
              onPressed: () async {
                var doc = (await FirebaseFirestore.instance
                    .collection('test')
                    .doc('doc')
                    .get());
                print(doc['times']);
                print(doc['times'][0]['time'].toDate());
              },
              child: Text("Get timestamp"),
            ),
          ],
        ),
      ),
    );
  }
}

```

</details>

---

### Debug Console Output, trying to set a new value in an empty collection:

<details><summary>Click To Expand</summary>

```
[cloud_firestore/unknown] Invalid argument (dartObject): Could not convert: Instance of 'DateTime'
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 216:49  throw_
packages/cloud_firestore_web/src/document_reference_web.dart 36:7             set
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:12           _async
packages/cloud_firestore_web/src/document_reference_web.dart 29:19            set
packages/cloud_firestore/src/document_reference.dart 82:22                    set
packages/flutter_web_timestamp/main.dart 38:26                                <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54            runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 123:12           _async
packages/flutter_web_timestamp/main.dart 35:26                                <fn>
packages/flutter/src/material/ink_well.dart 985:14                            [_handleTap]
packages/flutter/src/material/ink_well.dart 1101:38                           <fn>
packages/flutter/src/gestures/recognizer.dart 183:24                          invokeCallback
packages/flutter/src/gestures/tap.dart 598:48                                 handleTapUp
packages/flutter/src/gestures/tap.dart 287:5                                  [_checkUp]
packages/flutter/src/gestures/tap.dart 222:7                                  handlePrimaryPointer
packages/flutter/src/gestures/recognizer.dart 476:9                           handleEvent
packages/flutter/src/gestures/pointer_router.dart 77:12                       [_dispatch]

```

</details>

### Debug Console Output, when a timestamp value already exists in Firestore

<details><summary>Click To Expand</summary>

```
[{time: {seconds: 1605884460, nanoseconds: 0}}]
Error: NoSuchMethodError: 'toDate'
Dynamic call of null.
Receiver: Instance of 'LinkedMap<String, dynamic>'
Arguments: []
    at Object.throw_ [as throw] (http://localhost:55861/dart_sdk.js:4339:11)
    at Object.defaultNoSuchMethod (http://localhost:55861/dart_sdk.js:4784:15)
    at LinkedMap.new.noSuchMethod (http://localhost:55861/dart_sdk.js:5858:19)
    at Object.noSuchMethod (http://localhost:55861/dart_sdk.js:4780:30)
    at callNSM (http://localhost:55861/dart_sdk.js:4512:19)
    at Object._checkAndCall (http://localhost:55861/dart_sdk.js:4514:27)
    at Object.callMethod (http://localhost:55861/dart_sdk.js:4592:17)
    at Object.dsend (http://localhost:55861/dart_sdk.js:4595:17)
    at http://localhost:55861/packages/flutter_web_timestamp/main.dart.lib.js:459:35
    at Generator.next (<anonymous>)
    at http://localhost:55861/dart_sdk.js:37679:33
    at _RootZone.runUnary (http://localhost:55861/dart_sdk.js:37533:58)
    at _FutureListener.thenAwait.handleValue (http://localhost:55861/dart_sdk.js:32507:29)
    at handleValueCallback (http://localhost:55861/dart_sdk.js:33054:49)
```

</details>

---

**Comment by markusaksli-nc** [comment] 2020-11-23 11:43
I can confirm your findings as reproducible but then this is exactly the same as https://github.com/FirebaseExtended/flutterfire/issues/4063 and has been fixed already in https://github.com/FirebaseExtended/flutterfire/pull/4076. The plugin update with that fix just hasn't landed yet.

Closing this as a duplicate.

**Closed by markusaksli-nc** 2020-11-23 11:43 UTC
Labels: Needs Attention, type: bug
