### ISSUE TITLE
🐛 [firebase] dependency issue with firebase and google API 

### ISSUE THREAD

**Issue by raghavan-mookiah** [FirebaseExtended/flutterfire#5274] opened 2021-03-09 00:19 UTC
## Bug report

**Describe the bug**

After upgrading to flutter 2.0 , there is a dependency issue with firebase and google API 
Because googleapis >=2.0.0 depends on _discoveryapis_commons ^1.0.0 which depends on http_parser ^4.0.0, googleapis >=2.0.0 requires http_parser ^4.0.0.
And because firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0, googleapis >=2.0.0 is incompatible with firebase >=7.0.0 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, googleapis >=2.0.0 is incompatible with firebase_analytics >=7.1.0.
And because firebase_analytics >=7.0.1 <7.1.0 depends on firebase_core ^0.7.0 and myproject depends on firebase_core ^1.0.0, googleapis >=2.0.0 is incompatible with firebase_analytics >=7.0.1.

### Steps to reproduce

1. upgrade to flutter 2.0
2. pubspec.yaml
# Google Signin and API plugins
  google_sign_in: ^5.0.0
  googleapis: ^2.0.0

# FIREBASE CORE
  firebase_core: ^1.0.0
  # FIREBASE CRASHLYTICS
  firebase_crashlytics: ^1.0.0
  # FIREBASE ANALYTICS
  firebase_analytics: ^7.1.0
  #FIREBASE ADMOB
  google_mobile_ads: ^0.11.0+2

3. flutter pub get

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Because googleapis >=2.0.0 depends on _discoveryapis_commons ^1.0.0 which depends on http_parser ^4.0.0, googleapis >=2.0.0 requires http_parser ^4.0.0.
And because firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0, googleapis >=2.0.0 is incompatible with firebase >=7.0.0 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, googleapis >=2.0.0 is incompatible with firebase_analytics >=7.1.0.
So, because note_ec depends on both firebase_analytics ^7.1.0 and googleapis ^2.0.0, version solving failed.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-03-09 10:17
Hi @raghavan-mookiah 
There is already an open issue to track the dependency problems with `firebase_analytics` https://github.com/FirebaseExtended/flutterfire/issues/5202.
Since this is caused by the same underlying `http_parser ^3.0.0` dependency I'm going to close this as a duplicate.
Could you please follow up on the mentioned issue?
Thank you

**Closed by markusaksli-nc** 2021-03-09 10:17 UTC
Labels: Needs Attention, type: bug
