### ISSUE TITLE
🐛 [firebase_storage] Object not found exception

### ISSUE THREAD

**Issue by santosh-2095** [FirebaseExtended/flutterfire#4908] opened 2021-02-02 07:45 UTC
## Bug report
 When trying to get file reference from downloadUrl, firebase storage throws object not found exception while the object is present in the storage.

**Describe the bug**
Previously raised issue [#4218](https://github.com/FirebaseExtended/flutterfire/issues/4218#issue-750442851), the crash was not caused due to downloading the file but the refFromUrl method was throwing the exception

### Steps to reproduce

1.Upload a file to firebase storage with file name (eg: audio session.mp3)
2.Get the download url
3.Now from app, try this ` FirebaseStorage.instance.refFromURL(downloadUrl)`
4.This throws storage exception (attached crash logs)

### Expected behavior

It should return the firebase storage reference to that file

---

## Additional context

_**Crash Logs**_

`E/StorageException(15412): StorageException has occurred.`
`E/StorageException(15412): Object does not exist at location.`
`E/StorageException(15412):  Code: -13010 HttpResult: 404`
`E/StorageException(15412): {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}`
`E/StorageException(15412): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}`

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
teal 2.4.7+42

dependencies:
- agora_rtc_engine 3.2.1 [flutter flutter_web_plugins json_annotation]
- animations 1.1.2 [flutter]
- app_settings 4.0.4 [flutter]
- apple_sign_in 0.1.0 [flutter]
- audio_service 0.16.2 [audio_session rxdart flutter_isolate flutter_cache_manager sqflite js flutter flutter_web_plugins]
- audio_session 0.0.11 [flutter flutter_web_plugins rxdart]
- audioplayers 0.17.0 [uuid path_provider flutter flutter_web_plugins]
- camera 0.7.0+1 [flutter camera_platform_interface pedantic quiver]
- chewie 0.12.2 [cupertino_icons flutter video_player wakelock]
- cloud_firestore 0.16.0 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.9.0 [meta flutter firebase_core firebase_core_platform_interface cloud_functions_platform_interface cloud_functions_web]
- connectivity 2.0.2 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- crypto 2.1.5 [collection convert typed_data]
- device_apps 1.2.0 [flutter]
- dio 3.0.10 [http_parser path]
- extended_image 1.5.0 [flutter extended_image_library meta]
- firebase_analytics 7.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.20.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.4.0+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_database 6.0.0 [flutter firebase_core]
- firebase_dynamic_links 0.7.0+1 [flutter firebase_core]
- firebase_messaging 8.0.0-dev.14 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- firebase_performance 0.5.0+1 [flutter firebase_core]
- firebase_remote_config 0.6.0 [flutter firebase_core]
- firebase_storage 7.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- fit_kit 1.1.2 [flutter]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_conditional_rendering 1.1.1 [flutter]
- flutter_date_pickers 0.1.10 [flutter intl flutter_localizations]
- flutter_document_picker 4.0.0 [flutter]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_icons 1.1.0 [flutter]
- flutter_image_compress 0.7.0 [flutter]
- flutter_local_notifications 4.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_phone_state 0.5.9 [flutter url_launcher logging uuid stream_transform]
- flutter_rating_bar 3.2.0+1 [flutter]
- flutter_swiper 1.1.6 [flutter transformer_page_view flutter_page_indicator]
- flutter_widget_from_html_core 0.5.1+4 [flutter html]
- flutter_youtube_view 1.1.9 [flutter]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- just_audio 0.6.9 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- launch_review 2.0.0 [flutter]
- liquid_progress_indicator 0.3.2 [flutter]
- loading_indicator 1.2.0 [flutter async]
- open_file 3.0.3 [flutter ffi]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- popup_menu 1.0.5 [flutter]
- provider 4.3.3 [collection flutter nested]
- razorpay_flutter 1.2.3 [flutter eventify]
- rxdart 0.24.1
- sembast 2.4.8+1 [meta path synchronized]
- share 0.6.5+4 [meta mime flutter]
- url_launcher 5.4.11 [flutter url_launcher_platform_interface url_launcher_web url_launcher_macos]
- uuid 2.2.2 [crypto convert]
- video_player 1.0.1 [meta video_player_platform_interface video_player_web flutter]
- wakelock 0.2.1+1 [flutter meta wakelock_platform_interface wakelock_web]
dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- camera_platform_interface 1.5.0 [flutter meta plugin_platform_interface cross_file stream_transform]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 3.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 4.0.1 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 3.1.3 [firebase_core firebase_core_web cloud_functions_platform_interface flutter flutter_web_plugins http_parser meta js]
- collection 1.15.0-nullsafety.3
- connectivity_for_web 0.3.1 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+1 [flutter]
- connectivity_platform_interface 1.0.3 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- cross_file 0.1.0 [flutter http meta]
- csslib 0.16.1 [source_span]
- cupertino_icons 1.0.0
- eventify 0.1.4
- extended_image_library 0.3.0 [flutter path_provider http_client_helper crypto path]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.0 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+6 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.6 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_messaging_platform_interface 1.0.0-dev.10 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.5 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- firebase_storage_platform_interface 1.0.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+3 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_cache_manager 1.4.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_isolate 1.0.0+14 [flutter uuid]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_page_indicator 0.0.3 [flutter]
- flutter_plugin_android_lifecycle 1.0.6 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.1 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.14.0+3 [csslib source_span]
- http_client_helper 0.2.1 [http]
- http_parser 3.1.3 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.0 [flutter meta http plugin_platform_interface]
- import_js_library 1.0.2 [flutter html flutter_web_plugins js]
- js 0.6.2
- json_annotation 3.1.1
- just_audio_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- just_audio_web 0.2.3 [just_audio_platform_interface flutter flutter_web_plugins meta]
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.1
- path_provider_linux 0.0.1+1 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.8.0+1
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- service_worker 0.2.4 [js]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.6.1 [path]
- transformer_page_view 0.1.6 [flutter]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_macos 0.0.1+4 [flutter]
- url_launcher_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.1+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- vector_math 2.1.0-nullsafety.3
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock_platform_interface 0.1.0+1 [flutter meta]
- wakelock_web 0.1.0+3 [flutter flutter_web_plugins import_js_library js wakelock_platform_interface]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.0 [path process flutter]

```

</details>

---

**Comment by Ehesp** [comment] 2021-02-02 12:04
@santosh-2095 Could you confirm the file name on your bucket? I suspect there might be an issue with the name being resolved.

**Comment by santosh-2095** [comment] 2021-02-02 12:11
> @santosh-2095 Could you confirm the file name on your bucket? I suspect there might be an issue with the name being resolved.

"Test" is the folder name and "Balance Vinayasa-Camatkarasana- One leg plank- Side plank leg lift - Vinayasa - left .mp4" is the file name

**Comment by santosh-2095** [comment] 2021-02-02 12:21
> @santosh-2095 Could you confirm the file name on your bucket? I suspect there might be an issue with the name being resolved.

I am able to stream the video, download video using the downloadUrl but when i try to get the the reference from downloadUrl I am getting the exception

**Comment by markusaksli-nc** [comment] 2021-02-03 10:14
Reproducible on the latest master `1.26.0-18.0.pre.156`.
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 1.26.0-18.0.pre.156, on Microsoft Windows [Version 10.0.19041.746], locale et-EE)
    • Flutter version 1.26.0-18.0.pre.156 at C:\Development\flutter_master
    • Framework revision 45508985b1 (6 hours ago), 2021-02-02 22:46:04 -0500
    • Engine revision 2c144c3eeb
    • Dart version 2.12.0 (build 2.12.0-282.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.746]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 88.0.4324.104
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 88.0.705.56

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'dart:async';
import 'package:firebase_core/firebase_core.dart' as firebase_core;
import 'package:firebase_storage/firebase_storage.dart' as firebase_storage;
import 'package:flutter/material.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await firebase_core.Firebase.initializeApp();
  runApp(StorageExampleApp());
}

class StorageExampleApp extends StatefulWidget {
  @override
  _StorageExampleAppState createState() => _StorageExampleAppState();
}

class _StorageExampleAppState extends State<StorageExampleApp> {
  String download;
  TextEditingController ctr;

  @override
  void initState() {
    ctr = TextEditingController(text: "test/audio session.wav");
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Storage Example App',
      theme: ThemeData.dark(),
      home: Scaffold(
        body: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            TextFormField(controller: ctr),
            Text("$download"),
            ElevatedButton(
              child: const Text("Get link"),
              onPressed: () async {
                String downloadTemp = await firebase_storage.FirebaseStorage.instance.ref(ctr.text).getDownloadURL();
                setState(() => download = downloadTemp);
              },
            ),
            ElevatedButton(
              child: const Text("Check download link"),
              onPressed: () async {
                String tempDownload = await firebase_storage.FirebaseStorage.instance.refFromURL(download).getDownloadURL();
                print(tempDownload);
                setState(() => download = tempDownload);
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

It does seem to be caused by a space in the filename.

**Comment by zahidshaikh08** [comment] 2021-02-18 07:21
I have the same issue on stable channel 1.22.4 with firebase_storage: ^5.2.0 

and i can't upgrade dependencies because of different firebase dependencies, i tried a lot but could not figured out whats getting wrong and why this is happening. 

i also tried removing all spaces from reference as suggested but it still returns the same response.

earlier it was working perfectly with same code and everything but it just suddenly started giving this issues and exceptions from nowhere.

<details>
  <summary>Storage Exception</summary>

```
StorageException has occurred.
E/StorageException(12947): Object does not exist at location.
E/StorageException(12947):  Code: -13010 HttpResult: 404
E/StorageException(12947): {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException(12947): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found.  Could not get object",    "status": "GET_OBJECT"  }}
E/StorageException(12947): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:434)
E/StorageException(12947): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:451)
E/StorageException(12947): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:442)
E/StorageException(12947): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
E/StorageException(12947): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:286)
E/StorageException(12947): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:70)
E/StorageException(12947): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:62)
E/StorageException(12947): 	at com.google.firebase.storage.GetDownloadUrlTask.run(GetDownloadUrlTask.java:76)
E/StorageException(12947): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException(12947): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException(12947): 	at java.lang.Thread.run(Thread.java:923)

```
</details>

<details>

<summary>flutter doctor -v</summary>
  
```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H114 darwin-x64, locale en-IN)
    • Flutter version 1.22.4 at /Volumes/Tecocraft [A]/FLUTTER_SDK/flutter_1.22.4/flutter
    • Framework revision 1aafb3a8b9 (3 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4
```


</details>

<details>

<summary>Upload file and get download url method code</summary>

```
Future<Map<String, dynamic>> uploadImageToStorage(File imageFile, String fileName) async {
    try {
      Reference _storageReference = FirebaseStorage.instance.ref(fileName);
      UploadTask uploadTask = _storageReference.putFile(imageFile);

      var url = await (uploadTask.snapshot).ref.getDownloadURL();

      var name = _storageReference.name;
      print("image name ======>> $name");
      print("image url ======>> $url");

      return {"url": url, "name": name};
    } catch (e) {
      print("uploadImageToStorage exception ======>> $e");
      return null;
    }
  }
```

</details>

**Comment by zzterrozz** [comment] 2021-02-23 22:42
Unfortunately getting the error too :
`[firebase_storage/object-not-found] No object exists at the desired reference.`

I tried
```
final Reference fileRefFromUrl = FirebaseStorage.instance.refFromURL(fileUrl);
await FirebaseStorage.instance.ref(fileRefFromUrl.fullPath).delete();
```
also 
```
final Reference fileRef = FirebaseStorage.instance.refFromURL(fileUrl);
await fileRef.delete();
```

I have been stuck for hours and can't find any solution. Any idea please ?

**Comment by zzterrozz** [comment] 2021-02-24 00:44
I actually finally found a fix for this. The issue is from the non alphanumeric caracters in the file name.

Here is a way to clean the name if it can help anyone :
```
final String fileName = "yourFile|#“Ç[Ç#“.pdf";
String fileNameClean = fileName.split('.')[0];
fileNameClean = fileNameClean.replaceAll(RegExp('[^a-zA-Z0-9 ]'),"");
fileNameClean = fileNameClean.replaceAll(" ","-");
```

**Comment by pureimpro** [comment] 2021-04-03 19:20
Hi,

FirebaseStorage.instance.refFromURL() does not handle `%20` delimiters in URLs, resulting in truncating the returned string
**Is there a way to handle this special characters with refFromURL() ?**

```
firebase_storage: ^8.0.1
flutter version: 2.0.3
```

For example, with this URL containg a **%20** delimiter : https://firebasestorage.googleapis.com/v0/b/appmighty-3dfd7.appspot.com/o/groupFiles%2FiRrBzTMUbRXe5UZSoQQ1%2FRecordFile-Thierry%20Family-iRrBzTMUbRXe5UZSoQQ1-AUD-20190924-WA0000.mp3

Notice the filename : **RecordFile-Thierry%20Family-iRrBzTMUbRXe5UZSoQQ1-AUD-20190924-WA0000.mp3**

Try with raw Url String (trackFile) and decoded String (_decodeduri )
```
String trackFile= https://firebasestorage.googleapis.com/v0/b/appmighty-3dfd7.appspot.com/o/groupFiles%2FiRrBzTMUbRXe5UZSoQQ1%2FRecordFile-Thierry%20Family-iRrBzTMUbRXe5UZSoQQ1-AUD-20190924-WA0000.mp3;
String _decodeduri = Uri.decodeFull(trackFile);
```

Good raw URL :
```
print("trackFile : ${trackFile}");
trackFile : https://firebasestorage.googleapis.com/v0/b/appmighty-3dfd7.appspot.com/o/groupFiles%2FiRrBzTMUbRXe5UZSoQQ1%2FRecordFile-Thierry%20Family-iRrBzTMUbRXe5UZSoQQ1-AUD-20190924-WA0000.mp3
```

Good decoded URL :
```
print("_decodeduri : ${_decodeduri}");
_decodeduri : https://firebasestorage.googleapis.com/v0/b/appmighty-3dfd7.appspot.com/o/groupFiles/iRrBzTMUbRXe5UZSoQQ1/RecordFile-Thierry Family-iRrBzTMUbRXe5UZSoQQ1-AUD-20190924-WA0000.mp3?alt=media&token=72d2b5ea-d712-4dca-8173-06ec08e58aa8
```

**BUT TRUNCATED RESULT AFTER %20 IN BOTH CASES WITH refFromURL :**
```
print("refFromURL(trackFile).fullPath : ${FirebaseStorage.instance.refFromURL("$trackFile").fullPath}");
refFromURL(trackFile).fullPath : groupFiles/iRrBzTMUbRXe5UZSoQQ1/RecordFile-Thierry
```

```
print("refFromURL(trackFile).name : ${FirebaseStorage.instance.refFromURL("$trackFile").name}");
refFromURL(trackFile).name : RecordFile-Thierry
```

```
print("refFromURL(_decodeduri).fullPath : ${FirebaseStorage.instance.refFromURL("$_decodeduri").fullPath}");
refFromURL(_decodeduri).fullPath : groupFiles/iRrBzTMUbRXe5UZSoQQ1/RecordFile-Thierry
```

```
print("refFromURL(_decodeduri).name : ${FirebaseStorage.instance.refFromURL("$_decodeduri").name}");
refFromURL(_decodeduri).name : RecordFile-Thierry
```

```
print("refFromURL(trackFile) : ${FirebaseStorage.instance.refFromURL("$trackFile")}");
refFromURL(trackFile) : Reference(app: [DEFAULT], fullPath: groupFiles/iRrBzTMUbRXe5UZSoQQ1/RecordFile-Thierry)
```

```
print("refFromURL(trackFile) : ${FirebaseStorage.instance.refFromURL("$_decodeduri")}");
refFromURL(trackFile) : Reference(app: [DEFAULT], fullPath: groupFiles/iRrBzTMUbRXe5UZSoQQ1/RecordFile-Thierry)
```


**And subsequent delete() fail, obviously:**
await FirebaseStorage.instance.refFromURL("$_decodeduri").delete();
await FirebaseStorage.instance.refFromURL("$trackFile").delete();

**Comment by alextat120** [comment] 2021-04-07 07:16
Is this going to be fixed on the firebase side or do we handle this ourselves? I saw this issue happened with a react native firebase package too.

**Comment by alextat120** [comment] 2021-04-07 07:19
> Is this going to be fixed on the firebase side or do we handle this ourselves? I saw this issue happened with a react native firebase package too.

Seems like this PR should fix it:
#5682

**Closed** 2021-04-07 14:19 UTC
Labels: plugin: storage, type: bug
