### ISSUE TITLE
🐛 [firebase_messaging-v8.0.0-dev.14] Can't call method channel methods on onBackgroundMessage

### ISSUE THREAD

**Issue by moda20** [FirebaseExtended/flutterfire#4958] opened 2021-02-05 12:09 UTC
## Bug report

**Describe the bug**
i am trying to catch a background message and call a native java function using the method channels. i have my channel set up (and working if called form elsewhere) and my method is in my main java class (`MainActivity`)

### Expected behavior

actually calling the method channel method and seeing the logs from the java side of code.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on macOS 11.0.1 20B50 darwin-x64, locale
    en-FR)
 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (2 available)```

</details>

The plugins are installed but they just don't show up here.
---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter:
    sdk: flutter

  firebase_messaging:
    git:
      url: https://github.com/FirebaseExtended/flutterfire
      ref: firebase_messaging-v8.0.0-dev.14
      path: packages/firebase_messaging/firebase_messaging

  flutter_local_notifications: 3.0.1+4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0```

</details>

---

### My code 

dart : 

```
  @override
  void initState() {
    super.initState();
    initializeFirebaseMessaging();
  }

  void initializeFirebaseMessaging() async {
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

    await FirebaseMessaging.instance.getAPNSToken().then((c) => print(c));
    _createNewChannel();
  }
```

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
 // await Firebase.initializeApp();
  const MethodChannel _channel = MethodChannel('android_app_retain');
  print('Handling a background message ${message.messageId}');
  _channel.invokeMethod('wakeFromBackground');
}
```

java : 

```
public class MainActivity extends FlutterActivity {
    private static final String CHANNEL = "android_app_retain";
    private MethodChannel methodChannel;


    @Override
    public void configureFlutterEngine(@NonNull FlutterEngine flutterEngine) {
        GeneratedPluginRegistrant.registerWith(flutterEngine);
        methodChannel = new MethodChannel(flutterEngine.getDartExecutor().getBinaryMessenger(), CHANNEL);
        methodChannel.setMethodCallHandler(
                (methodCall, result) -> {
                    Map<String, Object> arguments = methodCall.arguments();
                    android.util.Log.d("TAGTAGTAGTAG", "configureFlutterEngine: "+methodCall.method);
                    if (methodCall.method.equals("wakeFromBackground")) {
                        wakeupfrombackground(getApplicationContext());
                    }
                }
        );
    }

    public void wakeupfrombackground(Context context) {
        android.util.Log.d("TAGTAGTGTAGTAG", "wakeupfrombackground: LOGGGGGGGGING WOOOOOOOOOOOO");
        Intent closeDialog = new Intent(Intent.ACTION_CLOSE_SYSTEM_DIALOGS);
        context.sendBroadcast(closeDialog);
        String packageName = context.getPackageName();
        PackageManager pm = context.getPackageManager();
        Intent launchIntent = pm.getLaunchIntentForPackage(packageName);
        context.startActivity(launchIntent);
    }

}
```

The issue here is that the logs from before the method call in the java side are not called. and the response when calling the  method is that it doesn't exist. 

```
Unhandled Exception: MissingPluginException(No implementation found for method wakeFromBackground on channel android_app_retain)
```

is on background message being called on an isolate? and it can't communicate with my java code?

my flutter deps

```Dart SDK 2.10.4
Flutter SDK 1.22.5
testnotifhemel 1.0.0+1

dependencies:
- cupertino_icons 1.0.0
- firebase_messaging 8.0.0-dev.14 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_local_notifications 3.0.1+4 [flutter platform flutter_local_notifications_platform_interface timezone]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- fake_async 1.2.0-nullsafety.1 [clock collection]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_messaging_platform_interface 1.0.0-dev.10 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.5 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- flutter_local_notifications_platform_interface 2.0.0+1 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- quiver 2.1.5 [matcher meta]
- service_worker 0.2.4 [js]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.5.9 [path]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
```

**Comment by markusaksli-nc** [comment] 2021-02-05 12:21
Hi @moda20 
Please provide your `flutter pub deps -- --style=compact` as well.
Thank you

**Comment by moda20** [comment] 2021-02-05 13:21
@markusaksli-nc i edited them into my og post

**Comment by markusaksli-nc** [comment] 2021-02-08 10:29
Could you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) (`main.dart`) to demonstrate the issue?

**Comment by moda20** [comment] 2021-02-10 20:28
@markusaksli-nc here, i made a repo with the same issue
https://github.com/moda20/testnotification.git

**Comment by markusaksli-nc** [comment] 2021-02-11 10:34
Hi @moda20 
Thanks for the example. It was a bit broken but digging through the code it's clear that this is just a duplicate of https://github.com/flutter/flutter/issues/13937
Not being able to call platform channel methods from a secondary isolate is just a limitation of flutter for now. I can try to get around this using a package like `isolate_handler` but given that the background message handler is already in a secondary isolate it will probably still take some tinkering to get to work.
Since this is a limitation on the flutter side there isn't much we can do here.
Thank you

**Closed by markusaksli-nc** 2021-02-11 10:34 UTC
Labels: Needs Attention, type: bug
