### ISSUE TITLE
🐛 [url_launcher] url_launcher not working on safari through Flutter web after firebase await call

### ISSUE THREAD

**Issue by rats24** [FirebaseExtended/flutterfire#5753] opened 2021-04-13 16:04 UTC
## Bug report

**url_launcher doesn't work after firebase document get call in safari through Flutter WEB**

### Steps to reproduce

Here is a demo code snippet:

```dart
Future getAndLaunchUrl() async{
final linkToOpen = await FirebaseFirestore.instance.collection(<COLLECTION_NAME>).doc(<DOC_ID>).get(); //fetch any document from firebase firestore.
launch('http://www.google.com'); //This fails on Safari- but works perfectly on Chrome
}
```

### Expected behaviour

A new tab pointing towards google.com should get opened.
---

### pubspec.yaml:

```
_name: nushala
description: NuShala Web Application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.12+24

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
  cloud_firestore: ^1.0.1
  provider: ^5.0.0
  firebase_storage: ^8.0.0
  intl: ^0.17.0
  url_launcher: ^6.0.3
  photo_view: ^0.9.2
  path: ^1.7.0
  uuid: ^3.0.1
  http: ^0.13.0
  flutter_datetime_picker: ^1.5.0
  characters: ^1.0.0
  firebase_messaging: ^9.0.0
  fluttertoast: ^8.0.1-nullsafety.0
  fluttericon: ^2.0.0
  getwidget: ^2.0.0-nullsafety.2
  rxdart: ^0.26.0
  shared_preferences: ^2.0.3
  flutter_bloc: ^7.0.0-nullsafety.4
  image_picker: ^0.7.3
  universal_html: ^2.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/_
```

### index.html:

```
<!DOCTYPE html>
<html>

<head>
  <meta charset="UTF-8">
  <meta content="IE=Edge" http-equiv="X-UA-Compatible">
  <meta name="description" content="NuShala">


  <!-- iOS meta tags & icons -->
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="apple-mobile-web-app-title" content="NuShala">
  <link rel="apple-touch-icon" href="icons/Icon-192.png">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="favicon.png" />

  <title>NuShala</title>
  <link rel="manifest" href="manifest.json">
</head>

<body>
  <!-- The core Firebase JS SDK is always required and must be listed first -->
  <script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-messaging.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-auth.js"></script>
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-firestore.js"></script>  <!-- Cannot use latest version as complex queries fail on latest version -->
  <script src="https://www.gstatic.com/firebasejs/7.20.0/firebase-storage.js"></script>

  <!-- TODO: Add SDKs for Firebase products that you want to use
       https://firebase.google.com/docs/web/setup#available-libraries -->
  <script src="https://www.gstatic.com/firebasejs/8.2.10/firebase-analytics.js"></script>

  <script>
    // Your web app's Firebase configuration
    var firebaseConfig = {
      apiKey: "apiKey",
      authDomain: "authDomain",
      databaseURL: "databaseURL",
      projectId: "projectId",
      storageBucket: "storageBucket",
      messagingSenderId: "messagingSenderId",
      appId: "appId",
      measurementId: "measurementId"
    };
    firebase.initializeApp(firebaseConfig);
    firebase.analytics();
  </script>
  <script>
    if ('serviceWorker' in navigator) {
      window.addEventListener('load', function () {
        navigator.serviceWorker.register('flutter_service_worker.js');
      });
    }
  </script>
  <script src="main.dart.js?v=1.0.50" type="application/javascript"></script>

</body>

</html>
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.0.1 20B29 darwin-x64, locale en-IN)
    • Flutter version 2.0.1 at /Users/ratindra/Documents/AAKALAN/mobileDevelopment/flutter
    • Framework revision c5a4b4029c (6 weeks ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/ratindra/Library/Android/sdk/
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/ratindra/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    ! CocoaPods 1.8.4 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 89.0.4389.114
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.1
nushala 1.2.12+24

dependencies:
- characters 1.1.0
- cloud_firestore 1.0.1 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.0
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.0.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 8.0.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.0-nullsafety.4 [flutter bloc provider]
- flutter_datetime_picker 1.5.0 [flutter]
- fluttericon 2.0.0 [flutter]
- fluttertoast 8.0.1-nullsafety.0 [flutter flutter_web_plugins]
- getwidget 2.0.0-nullsafety.2 [flutter]
- http 0.13.0 [http_parser meta path pedantic]
- image_picker 0.7.3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl 0.17.0 [clock path]
- path 1.8.0
- photo_view 0.9.2 [flutter]
- provider 5.0.0 [collection flutter nested]
- rxdart 0.26.0
- shared_preferences 2.0.3 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- universal_html 2.0.7 [async csslib charcode collection html meta source_span typed_data universal_io]
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]
- uuid 3.0.1 [crypto]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- bloc 7.0.0-nullsafety.3 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.1 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.0 [collection typed_data]
- csslib 0.17.0 [source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.1 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_plugin_android_lifecycle 2.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- html 0.15.0 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.1.0 [file path platform]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- universal_io 2.0.3 [collection crypto meta typed_data]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- win32 2.0.0 [ffi]
- xdg_directories 0.2.0 [meta path process]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-04-14 08:34
Hi @rats24 
Where exactly is this code failing? Are there any error messages logged?
Does the firestore query returen the value?
Thank you

**Comment by rats24** [comment] 2021-04-14 12:53
Hi @markusaksli-nc ,

Since we cannot connect safari through the debug mode, so exactly the point OR code at which it is failing is hard to point down.

For the firestore query result, yes, the firestore queries run perfectly fine, but the problem comes in the url_launcher library, and specifically after firestore query. Otherwise url_launcher library runs perfectly smooth.

The console of safari browser and the network tracker doesn't print any error or unusual log.

The expected outcome is - after fetching the document from firebase, a new tab should get opened.

Thanks in advance
The current outcome is - after fetching the document from firebase, nothing happens in safari.

This scenario is reproducible with the given code on Flutter web.

**Comment by markusaksli-nc** [comment] 2021-04-15 11:29
Well it's pretty clear why it's happening. Safari and Firefox block the page as a popup, only Chrome opens it up. Not sure why the firestore query specifically causes it to be blocked but it's easily reproducible.

Was able to reproduce the issue with
```yaml
  firebase_core: ^1.0.3
  cloud_firestore: ^1.0.5
  url_launcher: ^6.0.3
```
<details>
 <summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 2.2.0-11.0.pre.103, on macOS 11.2.3 20D91
    darwin-arm, locale en-GB)
    • Flutter version 2.2.0-11.0.pre.103 at
      /Users/nevercode/development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f0c9710493 (34 hours ago), 2021-04-13 20:29:40 -0500
    • Engine revision 04cd0db032
    • Dart version 2.13.0 (build 2.13.0-232.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 89.0.4389.128

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:url_launcher/url_launcher.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(FirestoreExampleApp());
}

class FirestoreExampleApp extends StatelessWidget {
  MaterialApp withMaterialApp(Widget body) {
    return MaterialApp(
      title: 'Firestore Example App',
      theme: ThemeData.dark(),
      home: Scaffold(
        body: body,
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return withMaterialApp(
      Center(
        child: Column(
          children: [
            ElevatedButton(
              onPressed: () {
                launch("http://www.google.com");
              },
              child: const Text("Open link"),
            ),
            ElevatedButton(
              onPressed: () async {
                print((await FirebaseFirestore.instance.collection("test").doc("link").get()).get("link"));
              },
              child: const Text("Get doc"),
            ),
            ElevatedButton(
              onPressed: () async {
                var link = (await FirebaseFirestore.instance.collection("test").doc("link").get()).get("link"); //also just http://google.com
                print(link);
                launch(link);
              },
              child: const Text("Open link from doc"),
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

**Comment by rats24** [comment] 2021-04-15 14:21
Hi @markusaksli-nc 

That is why I posted the issue here, because the problem persists only after a Firestore call. Otherwise, in both Safari and Firefox, I can open as many pages as I want as popup if I don't use Firestore call.

**Comment by russellwheatley** [comment] 2021-06-10 10:35
Hey folks, I'm going to close this issue as there isn't much we can do about it. We just wrap around the Firebase web sdk making the API request that causes the browser to change state somehow and thus blocking the launcher from opening the new window.

**Closed by russellwheatley** 2021-06-10 10:35 UTC
Labels: platform: web, plugin: cloud_firestore, type: bug

**Comment by Salakar** [comment] 2021-06-10 10:40
I'd suggest raising this over at https://github.com/firebase/firebase-js-sdk instead, since as mentioned above FlutterFire is just a wrapper to the FIrebase JS SDK.
