### ISSUE TITLE
[cloud_firestore] NullPointerException

### ISSUE THREAD

**Issue by ZatacaSystems** [FirebaseExtended/flutterfire#2423] opened 2020-04-23 15:12 UTC
When I try to send a message the app crashes. It's strange cause it works nice the 1st time the app is launched, then I reopen the app and then it crashes, and then I close again an reopen again and it works again, and that goes on and on:

```
D/AndroidRuntime(25841): Shutting down VM
E/AndroidRuntime(25841): FATAL EXCEPTION: main
E/AndroidRuntime(25841): Process: com.example.social_doctor_app, PID: 25841
E/AndroidRuntime(25841): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(25841):        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:451)
E/AndroidRuntime(25841):        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:433)
E/AndroidRuntime(25841):        at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.0:1025)
E/AndroidRuntime(25841):        at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
E/AndroidRuntime(25841):        at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.0:42)
E/AndroidRuntime(25841):        at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
E/AndroidRuntime(25841):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(25841):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25841):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(25841):        at android.app.ActivityThread.main(ActivityThread.java:6865)
E/AndroidRuntime(25841):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25841):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
E/AndroidRuntime(25841):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
my code:

```dart
InkResponse(
                    onTap: () {
                      if (_tecMessage.text.isNotEmpty) {
                        _blocChat.add(
                          Event(
                            ChatEventType.sendMessageButtonPressed,
                            data: _tecMessage.text.trim(),
                          ),
                        );
                        _tecMessage.clear();
                      }
                    },
                    child: Container(
                      margin: EdgeInsets.all(5.0),
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        color: Theme.of(context).primaryColor,
                      ),
                      padding: EdgeInsets.all(12.0),
                      child: SvgPicture.asset(
                        'lib/main/images/ic_chat_send_white.svg',
                      ),
                    ),
                  ),
```

pressing the button executes this code on the bloc:

```dart
case ChatEventType.sendMessageButtonPressed:
        try {
          await _firestore.collection(_tableName).add(<String, dynamic>{
            'message': event.data,
            'date': FieldValue.serverTimestamp(),
            'fk_from': _userType == 1 ? _patientId : _doctorId,
          });
        } catch (e, s) {
          print('${this.runtimeType} -> $e | $s');
        }
        yield event;
        break;
```

Flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale es-ES)
    • Flutter version 1.12.13+hotfix.8 at /Users/jose/developement/flutter
    • Framework revision 0b8abb4724 (2 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jose/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • 5024D EEA • V7LB18BBMMC01BI • android-arm64 • Android 9 (API 28)

• No issues found!
```

I have tried with flutter run and with flutter run --release

`cloud_firestore: ^0.13.5`

**Comment by TahaTesser** [comment] 2020-04-23 15:29
duplicate of [#2390](https://github.com/FirebaseExtended/flutterfire/issues/2390)

**Closed by TahaTesser** 2020-04-23 15:29 UTC
