### ISSUE TITLE
[FIREBASE_AUTH] Email address is not returned when there is a authentication collision between google and other provider

### ISSUE THREAD

**Issue by premtemp1** [FirebaseExtended/flutterfire#1773] opened 2020-01-06 20:23 UTC
The Firebase_auth plugin does not return the user email when there is a collision with another provider.

Scenario:

1: Enable user to have multiple providers --same email address in firebase
2: User login with google and the account is created in firebase
3: User logout of google from the app
4: User now login with Facebook (flutter_facebook_login 3.0.0).
   -- error is thrown  --"`ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL` "

However: the email for the user is not returned. So, there no option to get the list of the previous providers for this user. Basically, you cannot use [fetchSignInMethodsForEmail] because the email is not returned...

Can you please fix the plugin so that it returns the email

Here is the block of code in your plugin that is called

```
/// Asynchronously signs in to Firebase with the given 3rd-party credentials
  /// (e.g. a Facebook login Access Token, a Google ID Token/Access Token pair,
  /// etc.) and returns additional identity provider data.
  ///
  /// If successful, it also signs the user in into the app and updates
  /// the [onAuthStateChanged] stream.
  ///
  /// If the user doesn't have an account already, one will be created automatically.
  ///
  /// **Important**: You must enable the relevant accounts in the Auth section
  /// of the Firebase console before being able to use them.
  ///
  /// Errors:
  ///   • `ERROR_INVALID_CREDENTIAL` - If the credential data is malformed or has expired.
  ///   • `ERROR_USER_DISABLED` - If the user has been disabled (for example, in the Firebase console)
  ///   • `ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL` - If there already exists an account with the email address asserted by Google.
  ///       Resolve this case by calling [fetchSignInMethodsForEmail] and then asking the user to sign in using one of them.
  ///       This error will only be thrown if the "One account per email address" setting is enabled in the Firebase console (recommended).
  ///   • `ERROR_OPERATION_NOT_ALLOWED` - Indicates that Google accounts are not enabled.
  ///   • `ERROR_INVALID_ACTION_CODE` - If the action code in the link is malformed, expired, or has already been used.
  ///       This can only occur when using [EmailAuthProvider.getCredentialWithLink] to obtain the credential.
  Future<AuthResult> signInWithCredential(AuthCredential credential) async {
    assert(credential != null);
    final Map<String, dynamic> data =
        await channel.invokeMapMethod<String, dynamic>(
      'signInWithCredential',
      <String, dynamic>{
        'app': app.name,
        'provider': credential._provider,
        'data': credential._data,
      },
    );
    final AuthResult authResult = AuthResult._(data, app);
    return authResult;
  }
```

**Comment by awhitford** [comment] 2020-02-29 08:17
Yes, I am running into the same issue.  It applies to any kind of third party _Sign In Provider_ (Google, Facebook, etc.).

**Comment by awhitford** [comment] 2020-04-06 22:17
Related, I am a little confused how it seems that when using Email/Password, Google, and Apple Sign In, the account is *merged* so that as long as you authenticate successfully with the same email address, you get the same `uid`.  However, when you authenticate using Facebook, you get `ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL` instead.  Why the inconsistency?

**Comment by awhitford** [comment] 2020-04-06 22:42
Regarding my last comment, it was recently explained to me that Google and Apple are considered _authoritative sources of email_ (i.e., they know for certain that you own it) while Facebook is not, hence why it does not merge.  _Is this documented somewhere?_

**Comment by premtemp1** [comment] 2020-04-06 23:44
I did not see this documented anywhere. Also, it would be helpful if plugin returns the previous provider for that user when you get the error =>
"ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL"

e.g
user login previously with google . Now they login with FB . This will throw the error "ERROR_ACCOUNT_EXISTS_WITH_DIFFERENT_CREDENTIAL". It would be helpful if the API also returns the previous provider - Google or LinkedIn  etc. 
Then the UI can redirect the user to authenticate with that provider

Please let me know if you find any information for this issue

**Comment by Ehesp** [comment] 2020-04-22 08:08
I believe this is a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1318 - the error isn't returning the `email` property which it should be doing, so it makes account linking hard.

Will close and track on the other issue.

**Closed by Ehesp** 2020-04-22 08:08 UTC
Labels: type: bug
