### ISSUE TITLE
Crashlytics no longer building on 2.1.0

### ISSUE THREAD

**Issue by tomquercia** [FirebaseExtended/flutterfire#6622] opened 2021-07-15 21:29 UTC
As of 2.1.0, trying to build our iOS app fails when building crashlytics, saying FIRAnalyticsInterop.h cannot be found.

This was added as part of ffba1fc3d01c3facfd8511f6aa34fb9bfffd4716.

```~/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.1.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.m:12:9: fatal error:
    'FirebaseCrashlytics/FIRAnalyticsInterop.h' file not found
    #import <FirebaseCrashlytics/FIRAnalyticsInterop.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    ~/.pub-cache/hosted/pub.dartlang.org/firebase_crashlytics-2.1.0/ios/Classes/FLTFirebaseCrashlyticsPlugin.m:12:9: note: did not find header
    'FIRAnalyticsInterop.h' in framework 'FirebaseCrashlytics' (loaded from
    '~/project/build/ios/Release-iphoneos/FirebaseCrashlytics')
    1 error generated.
```

Indeed, FirebaseCrashlytics.framework does _not_ have the header included:

![image](https://user-images.githubusercontent.com/2738273/125860011-4e4a9f48-186d-4e7d-bfac-08bf96412f5c.png)

Flutter doctor output:

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.0.3, on Mac OS X 10.15.7 19H1217 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.52.1)
[✓] Proxy Configuration
[✓] Connected device (1 available)

• No issues found!
```

**Comment by pintalubaf** [comment] 2021-07-15 22:17
Same to me.

**Comment by Piero512** [comment] 2021-07-15 22:37
Seems that #6623 is a duplicate of this issue.

**Comment by Salakar** [comment] 2021-07-16 12:09
Closing as duplicate of #6623

**Closed by Salakar** 2021-07-16 12:09 UTC
