### ISSUE TITLE
[firebase_messaging] not customizing notification when app is not in foreground

### ISSUE THREAD

**Issue by antigones** [FirebaseExtended/flutterfire#2312] opened 2020-04-06 12:09 UTC
I tried to group notifications and grouping works when the app is in foreground but when the app is in the background, notifications just arrive as single notifications and the grouping customization is not applied.
This is my "flutter doctor -v" output:

[√] Flutter (Channel master, v1.18.1-pre.9, on Microsoft Windows [Versione 10.0.17763.1098], locale it-IT)
• Flutter version 1.18.1-pre.9 at D:\flutter
• Framework revision f9c58bea49 (8 hours ago), 2020-04-04 21:31:55 -0700
• Engine revision cb6fc30534
• Dart version 2.8.0 (build 2.8.0-dev.20.0 80ae6ed91d)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
• Android SDK at D:\sdk
• Platform android-29, build-tools 29.0.2
• ANDROID_HOME = D:\sdk
• Java binary at: D:\Program Files\Android\Android Studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
• All Android licenses accepted.

[√] Android Studio (version 3.6)
• Android Studio at D:\Program Files\Android\Android Studio
• Flutter plugin version 45.0.1
• Dart plugin version 192.7761
• Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] VS Code, 64-bit edition (version 1.43.2)
• VS Code at C:\Program Files\Microsoft VS Code
• Flutter extension version 3.8.1

[√] Connected device (1 available)
• AOSP on IA Emulator • emulator-5554 • android-x86 • Android 9 (API 28) (emulator)

• No issues found!

Here is a link of my [source code](https://github.com/antigones/flutter_fcm_notifications).
In the same repository you will find screenshots of the issue.

**Comment by TahaTesser** [comment] 2020-04-07 11:30
Duplicate of [#1736](https://github.com/FirebaseExtended/flutterfire/issues/1736)

**Closed by TahaTesser** 2020-04-07 11:30 UTC
Labels: bug
