### ISSUE TITLE
🐛 [cloud_firestore] Problems with WI-FI connection on Samsung J6 J4

### ISSUE THREAD

**Issue by ElaineSchwner** [FirebaseExtended/flutterfire#4121] opened 2020-11-13 19:03 UTC
Hello,

I have some Flutter applications, everything works fine in every device, but Samsung.
Users have complained about the app not getting any data when connected on wifi.

I bought a Samsung J6, just for testing, and I installed one of my apps from the play Store and it was completely blank. After 3 minutes, just staring the screen, the data showed.

Detail: I have other app pubished but with SQL database. This one worked well. So I think it is something related to Firebase.

Antoher detail: the same code from Web works.

I think the problem is it takes a long time to get wi-fi connection from Samsung.

One detail: this device only connects in wi-fi 2.4ghz

With the debub app and completely connected in wi-fi, we get this:
```
W/Firestore(32621): (21.3.0) [OnlineStateTracker]: Could not reach Cloud Firestore backend. Backend didn't respond within 10 seconds
W/Firestore(32621):
W/Firestore(32621): This typically indicates that your device does not have a healthy Internet connection at the moment. The client will operate in offline mode until it is able to successfully connect to the backend.
```
After 3 minutes, it finally shows data.

I put the installed apk for debugger and I think this verbose may be important:
```
2020-11-13 13:59:38.721 28883-25297/? W/NetworkScheduler: Error inserting flex_time=3534000 job_id=-1 period=7069000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=203915000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1605286778713 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0, error message: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE[2067]) [CONTEXT service_id=218 ]
```

I get the following erros from the published app:
```
2020-11-13 13:54:09.753 3300-3534/? E/NetdEventListenerService: handleMessage: { when=0 what=10001 obj=com.android.server.connectivity.NetdEventListenerService$DnsResultParams@c36a3bb target=com.android.server.connectivity.NetdEventListenerService$DnsEventHandler }
2020-11-13 13:54:12.569 3816-5647/? E/#IMSCR: 11-13 13:54:12 0x12060000:N,REFR:0
2020-11-13 13:54:12.605 3816-5647/? E/#IMSCR: 11-13 13:54:12 0x12060001:N,REFR:FOUND:0
2020-11-13 13:54:12.898 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:12.898 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0 mTagName : SurfaceFlinger
2020-11-13 13:54:12.900 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:12.901 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:13.414 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:13.414 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1 mTagName : SurfaceFlinger
2020-11-13 13:54:13.414 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:13.414 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:14.415 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:14.415 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU , mTagName : SurfaceFlinger
2020-11-13 13:54:14.416 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU()
2020-11-13 13:54:14.417 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:14.577 22613-22613/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-11-13 13:54:14.578 22613-22613/? E/Zygote: accessInfo : 1
2020-11-13 13:54:14.595 22613-22613/? E/d.mobileservic: Not starting debugger since process cannot load the jdwp agent.
2020-11-13 13:54:14.817 22632-22632/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-11-13 13:54:14.818 22632-22632/? E/Zygote: accessInfo : 1
2020-11-13 13:54:14.827 22632-22632/? E/android:drmSer: Not starting debugger since process cannot load the jdwp agent.
2020-11-13 13:54:14.989 22613-22613/? E/SEMS:DataAdapterLog_11.1.0: [SEMS][2][GroupDBHelper] Instance null
2020-11-13 13:54:17.905 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:17.905 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0 mTagName : SurfaceFlinger
2020-11-13 13:54:17.908 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:17.908 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:18.420 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:18.421 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1 mTagName : SurfaceFlinger
2020-11-13 13:54:18.422 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:18.422 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:19.423 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:19.423 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU , mTagName : SurfaceFlinger
2020-11-13 13:54:19.425 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU()
2020-11-13 13:54:19.425 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:22.894 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:22.894 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0 mTagName : SurfaceFlinger
2020-11-13 13:54:22.896 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:22.896 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:23.410 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:23.410 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1 mTagName : SurfaceFlinger
2020-11-13 13:54:23.411 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:23.411 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:24.412 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:24.412 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU , mTagName : SurfaceFlinger
2020-11-13 13:54:24.414 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU()
2020-11-13 13:54:24.414 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:27.901 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:27.901 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0 mTagName : SurfaceFlinger
2020-11-13 13:54:27.903 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:27.903 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:28.417 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:28.417 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1 mTagName : SurfaceFlinger
2020-11-13 13:54:28.417 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:28.417 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:29.418 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:29.418 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU , mTagName : SurfaceFlinger
2020-11-13 13:54:29.420 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU()
2020-11-13 13:54:29.420 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:30.855 3300-3324/? E/Watchdog: !@sync 198 [2020-11-13 13:54:30.855] FD count : 520, wdog_way : softdog
2020-11-13 13:54:32.907 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:32.907 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0 mTagName : SurfaceFlinger
2020-11-13 13:54:32.910 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:32.910 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:33.423 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:33.423 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 1 mTagName : SurfaceFlinger
2020-11-13 13:54:33.425 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:33.425 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:34.426 2893-4381/? E/NativeSemDvfsGpuManager: release:: Start
2020-11-13 13:54:34.426 2893-4381/? E/NativeSemDvfsGpuManager: release():: mIsAcquired = 1 , mName = GPU , mTagName : SurfaceFlinger
2020-11-13 13:54:34.428 2893-4381/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::releaseGPU()
2020-11-13 13:54:34.428 2893-4381/? E/NativeSemDvfsGpuManager: release:: End
2020-11-13 13:54:34.729 7825-22606/? E/InternalPeopleServiceGrpcClient: Error making Grpc request.
clxm: DEADLINE_EXCEEDED: deadline exceeded after 24.969990846s. [buffered_nanos=24970205597, waiting_for_connection]
at clxl.c(:com.google.android.gms@203915035@20.39.15 (120306-335085812):3)
at snn.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):65)
at apeo.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):34)
at apeq.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):18)
at aper.run(:com.google.android.gms@203915035@20.39.15 (120306-335085812):2)
at java.lang.Thread.run(Thread.java:919)
2020-11-13 13:54:34.729 7825-22606/? E/FSA2_GroupSyncGrpc: getGroups() failed
clxm: DEADLINE_EXCEEDED: deadline exceeded after 24.969990846s. [buffered_nanos=24970205597, waiting_for_connection]
at clxl.c(:com.google.android.gms@203915035@20.39.15 (120306-335085812):3)
at snn.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):65)
at apeo.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):34)
at apeq.a(:com.google.android.gms@203915035@20.39.15 (120306-335085812):18)
at aper.run(:com.google.android.gms@203915035@20.39.15 (120306-335085812):2)
at java.lang.Thread.run(Thread.java:919)
2020-11-13 13:54:37.897 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
2020-11-13 13:54:37.897 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: timeout = 1000 mIsAcquired = 0 mTagName : SurfaceFlinger
2020-11-13 13:54:37.899 2893-4382/? E/NativeCustomFrequencyManager: [NativeCFMS] BpCustomFrequencyManager::requestGPU()
2020-11-13 13:54:37.899 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: End
2020-11-13 13:54:38.413 2893-4382/? E/NativeSemDvfsGpuManager: acquire:: Start
```
There is this error too: 

There is this error:
```
2020-11-13 14:57:22.263 14098-14115/com.oneplanet.historiasparadormir E/MediaHTTPConnection: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.URLConnection java.net.URL.openConnection()' on a null object reference
at android.media.MediaHTTPConnection.seekTo(MediaHTTPConnection.java:256)
at android.media.MediaHTTPConnection.getMIMEType(MediaHTTPConnection.java:475)
at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:159)
at android.os.Binder.execTransactInternal(Binder.java:1056)
at android.os.Binder.execTransact(Binder.java:1029)
2020-11-13 14:57:22.265 14098-14115/com.oneplanet.historiasparadormir E/MediaHTTPConnection: java.lang.NullPointerException: Attempt to invoke virtual method 'java.net.URLConnection java.net.URL.openConnection()' on a null object reference
at android.media.MediaHTTPConnection.seekTo(MediaHTTPConnection.java:256)
at android.media.MediaHTTPConnection.getSize(MediaHTTPConnection.java:461)
at android.media.IMediaHTTPConnection$Stub.onTransact(IMediaHTTPConnection.java:151)
at android.os.Binder.execTransactInternal(Binder.java:1056)
at android.os.Binder.execTransact(Binder.java:1029)
```

**Comment by markusaksli-nc** [comment] 2020-11-16 11:29
I can't reproduce this on a 2.4 wifi connection with my SM G950F. 
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.252, on Microsoft Windows [Version 10.0.19041.572], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.252 at C:\Development\flutter_master
    • Framework revision bf2c9dfc05 (32 hours ago), 2020-11-14 22:38:02 -0500
    • Engine revision 3e77d854a7
    • Dart version 2.12.0 (build 2.12.0-45.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.7660.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 86.0.4240.193
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 86.0.622.68

• No issues found!
```
</details>

Could just be a weak wifi connection issue but leaving this open due to the potentially useful logs.

**Comment by ElaineSchwner** [comment] 2020-11-16 12:14
> I can't reproduce this on a 2.4 wifi connection with my SM G950F.
> 
> flutter doctor -v
> Could just be a weak wifi connection issue but leaving this open due to the potentially useful logs.

It's not a weak wi-fi connection. YouTube is working normally. 
It's something really important because apps are blank when opening after installing from Play Store.

Please connect with this issue too https://github.com/FirebaseExtended/flutterfire/issues/2753

Check the app form Play Store:
https://play.google.com/store/apps/details?id=br.com.app.gpu2267713.gpu8af3893f7b7132a68c9f751e4d05c6da

Or this one: 
https://play.google.com/store/apps/details?id=com.oneplanet.historiasparadormir

It opens completely normal from some devices, but for Samsung J6 and J4 it is blank.

Thank you!

**Comment by Salakar** [comment] 2021-04-01 12:23
Closing in favour of #2753.

**Closed by Salakar** 2021-04-01 12:23 UTC
Labels: plugin: cloud_firestore, type: bug
