### ISSUE TITLE
[connection] nw_endpoint_handler_set_adaptive_read_handler 

### ISSUE THREAD

**Issue by desmeit** [FirebaseExtended/flutterfire#7125] opened 2021-10-04 11:00 UTC
Every time I login, whether email, Apple ID or Google, I get the following error message:

```
[connection] nw_endpoint_handler_set_adaptive_read_handler [C27.1 2a00:1450:4016:809::200a.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for read_timeout failed
[connection] nw_endpoint_handler_set_adaptive_write_handler [C27.1 2a00:1450:4016:809::200a.443 ready channel-flow (satisfied (Path is satisfied), viable, interface: en0, ipv4, ipv6, dns)] unregister notification for write_timeout failed
```

I do not have push notifications installed. Only local notifications but it only occurs at actions with firebase auth. What could be the reason?

**Comment by markusaksli-nc** [comment] 2021-10-05 08:31
Seeing this as well.

**Comment by markusaksli-nc** [comment] 2021-10-05 08:32
Closing as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/7136

**Closed by markusaksli-nc** 2021-10-05 08:32 UTC
Labels: type: bug, Needs Attention, in triage
