### ISSUE TITLE
[📚] SHA Key generation installation link navigate to Page Not Found

### ISSUE THREAD

**Issue by prateekcode** [FirebaseExtended/flutterfire#7013] opened 2021-09-17 05:01 UTC
In the Social Authentication (https://firebase.flutter.dev/docs/auth/social/),  while reading the Google sign-in method on clicking Installation documentation, it navigates to the page that showing 'Page not found, Please contact the owner'.
Please add the correct link to this Hyperlink text.

**Comment by markusaksli-nc** [comment] 2021-09-17 07:59
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6751

**Closed by markusaksli-nc** 2021-09-17 07:59 UTC
Labels: type: documentation, good first issue, in triage

**Comment by markusaksli-nc** [comment] 2021-09-17 08:01
FYI the correct link is https://firebase.flutter.dev/docs/installation/android/#generating-firebase-credentials
