### ISSUE TITLE
Firebase Core error: No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core

### ISSUE THREAD

**Issue by sondresorbye** [FirebaseExtended/flutterfire#7105] opened 2021-09-30 19:31 UTC
I have the latest version of firebase core (firebase_core: ^1.7.0). I just installed version 2.5.1 of flutter and got this runtime error on iOS:

`No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core`

This works on a previous version of flutter and runs fine on android. I have tried all tricks like flutter clean, pod install etc.

Any suggestions?

**Comment by markusaksli-nc** [comment] 2021-10-01 07:13
You could try all of these in your `ios` directory
```bash
rm -rf build
rm -rf Pods
rm -rf Podfile.lock
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
pod cache clean --all
flutter clean
flutter pub get
pod repo update
pod install
```
Other than that this is a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4455

**Closed by markusaksli-nc** 2021-10-01 07:13 UTC
Labels: type: bug, Needs Attention, in triage
