### ISSUE TITLE
[firebase_auth] The reload() function on a FirebaseUser doesn't seem to be working.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#717] opened 2019-10-13 18:57 UTC
Hey, 

when calling the .reload() function on a FirebaseUser nothing seems to happen, as the data of the user I called reload() on doesn't change and the data of a user when calling FirebaseAuth.instance.currentUser() change nontheless, even when not calling reload().

What makes matter more confusing is that on the [Stackoverflow Problem I opened](https://stackoverflow.com/questions/51709733/what-use-case-has-the-reload-function-of-a-firebaseuser-in-flutter) "Frank van Puffelen", a Firebase Developer at Google said

> If the user was already signed in, requesting auth.currentUser() does not refresh their profile data from the server.  

which makes matter only more confusing, as this is not the case with my tested code.

Here is the example:

```dart
static stackOverflowProblem() async {
    FirebaseUser user = await FirebaseAuth.instance.currentUser();
    print("Name of User: ${user.displayName}"); //prints foo

    //Renaming the name from "foo" to "bar"
    UserUpdateInfo userInfo = UserUpdateInfo();
    userInfo.displayName = "bar";
    await _auth.updateProfile(userInfo);

    print("\nBefore calling user.reload:");
    print("Name of user: ${user.displayName}"); //prints foo
    print("Name of FirebaseAuth.instance.currentUser: ${(await FirebaseAuth.instance.currentUser()).displayName}"); //prints bar

    await user.reload();

    print("\nAfter calling user.reload:");
    print("Name of user: ${user.displayName}"); //prints foo
    print("Name of FirebaseAuth.instance.currentUser: ${(await FirebaseAuth.instance.currentUser()).displayName}"); //prints bar
  }
```   
Output:
```dart
I/flutter (19989): Name of User: Foo
I/flutter (19989): 
I/flutter (19989): Before calling user.reload:
I/flutter (19989): Name of user: Foo
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: bar
I/flutter (19989): 
I/flutter (19989): After calling user.reload:
I/flutter (19989): Name of user: Foo
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: bar
```

The output i would assume, based on the answer from Frank van Puffelen and from my assumption about how the reload method should work, is:
```dart
I/flutter (19989): Name of User: Foo
I/flutter (19989): 
I/flutter (19989): Before calling user.reload:
I/flutter (19989): Name of user: Foo
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: Foo
I/flutter (19989): 
I/flutter (19989): After calling user.reload:
I/flutter (19989): Name of user: bar
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: Foo
```
Maybe also like this, as IMO FirebaseAuth.instance.currentUser() should always give the newest information, atleast that's how I think it works/should work.
```dart
[...]
I/flutter (19989): After calling user.reload:
I/flutter (19989): Name of user: bar
I/flutter (19989): Name of FirebaseAuth.instance.currentUser: bar
```

So any help with that, what is reload() for? Am I just confusing the method should work, or what is happening?!
Please also look at the [Stackoverflow Question](https://stackoverflow.com/questions/51709733/what-use-case-has-the-reload-function-of-a-firebaseuser-in-flutter).
Thanks!

**Comment by kroikie** [comment] 2019-10-13 18:57
@JSANL

The issue at https://github.com/flutter/flutter/issues/20390 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by gabrielscr** [comment] 2019-10-19 19:17
Please fix this

**Comment by iapicca** [comment] 2019-10-24 13:43
Hi @JSANL
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by gabrielscr** [comment] 2019-10-26 20:47
I solved by using this:

  Future<void> updatePhoto(String photo) async {
    UserUpdateInfo userInfo = UserUpdateInfo();

    userInfo.photoUrl = photo;
    await _user.updateProfile(userInfo);
    await _user.reload();
    _user = await _auth.currentUser();
  }

**Comment by awhitford** [comment] 2019-10-27 02:16
@iapicca What might make sense is to introduce a `Stream<User>` listener so that User reloads can be broadcast.  The main issue that I see is that widgets have stale information, and we need an easy way to refresh them.

**Comment by livetalabs** [comment] 2019-12-07 08:43
The problem with not being able to get a change notification of isEmailValidated and also the value not refreshing after invoking reload() was driving me crazy for hours until I found the workaround in this post. Like others I feel the reload() method is not behaving like we expect it to but at least the workaround works.  I can finally move on to my next problem.

**Comment by feinstein** [comment] 2019-12-30 18:39
I sent a pull request with a solution for this, anyone interested please take a look at #1741.

**Comment by Marvioso** [comment] 2020-01-22 13:39
Hi @livetalabs  what was your workaround?

**Comment by feinstein** [comment] 2020-01-22 13:43
@Marvioso yes, they are reluctant to approve a change in the API that doesn't reflect the Android and iOS ones, so they prefer that I publish it as a separete package, which I probably will.

For now you can just see my modifications on the the Pull-Request and understand how they work and make something similar for your project, that's how I am doing on mine and it works fine.

**Comment by feinstein** [comment] 2020-01-24 15:55
So, since this won't be fixed on `fireabase_auth`, I made a package to solve this and get reloaded users and auth state changes on a `Stream` as well.

Grab it here: [firebase_user_stream](https://pub.dev/packages/firebase_user_stream) 

The Readme shows examples and all the ways we can use the package and how it simplifies this whole process.

Enjoy!

**Comment by bean5** [comment] 2020-02-11 21:29
So, I guess this should be closed as "Won't do?"

**Comment by AndrsDev** [comment] 2020-02-21 23:46
Same problem here, I need the firebase `authStateStream` to be working as expected on `.reload();`

**Comment by ajaygautam** [comment] 2020-05-31 03:06
Ran into this issue too! I somehow seem to remember this working earlier!

Anyway... this is really serious and needs to be fixed ASAP.
Bad user experience for users to be working with stale data!

**Comment by erf** [comment] 2020-06-03 14:12
I made a hack solution for missing `onAuthStateChanged` events in #2690 using `rx.BehaviourSubject`

**Comment by feinstein** [comment] 2020-06-03 16:05
@erf you can also use [firebase_user_stream](https://pub.dev/packages/firebase_user_stream)

**Comment by erf** [comment] 2020-06-03 16:33
@feinstein thanks, but i already have the `oldUser`, so i'm thinking it might be extra work / delay in getting that. Also i had some timing issues when unlinking providers from the current user. I had to add some delay before calling `currentUser`, in order for `providerData` to be up to date. Have you done some testing on this? That is if all the data are present after updating some data?

**Comment by feinstein** [comment] 2020-06-03 16:48
I am sorry but I don't understand what your issue is, I never had any timing issues, once the call to reload completes I get everything.

**Comment by erf** [comment] 2020-06-03 17:07
@feinstein here is an example of what i do. 

```
      await firebaseUser.unlinkFromProvider(PhoneAuthProvider.providerId);
      await firebaseUser.reload();
      _appState.forceAuthStreamUpdate();
```

After this i want to use `firebaseUser.providerData` and i should see "phone provider" is gone.

Before this i linked a phone account to an anonymous account.

Have you tested this?

**Comment by feinstein** [comment] 2020-06-03 17:11
No I didn't, it's hard to test all the interfaces as they need network connections so can't be used on unit tests, but I can't see why it wouldn't work with my package, if you try it and have a problem, please file an issue for me please (but again, I expect it to work just fine).

**Comment by feinstein** [comment] 2020-06-03 17:46
That's not because of the delay, that's because of how `reload` works, it's counter intuitive and the Firebase team already said they aren't going to change it, that's why I made my package.

**Comment by erf** [comment] 2020-06-03 17:54
I read your source code, and i was pretty much doing everything you did, except the initial call to get the "old user" since i already had it. I also did call `reload`. So the only thing i can see is different is the delay with you retreiveing the "old user".

**Comment by feinstein** [comment] 2020-06-03 18:56
No, you also need to call the new user again to get it all updated, as I said, I explain this on the Readme.

I don't want to fill everyone's inbox with this, so if you have any further questions you can contact me on my email or in my projects repo.

**Comment by awhitford** [comment] 2020-07-08 04:13
@feinstein Thank you for the [firebase_user_stream](https://pub.dev/packages/firebase_user_stream) package.  Leveraging it was a snap and now my `FirebaseUser` instance is reliable.

**Comment by Ehesp** [comment] 2020-07-14 16:15
As part of https://github.com/FirebaseExtended/flutterfire/issues/2582 we've introduced a `userChanges` stream, which triggers whenever auth state, id token or profile changes occur. Essentially, this acts as a way to obtain realtime changes on currently stateless functionality (such as `updateProfile`).

**Closed by Ehesp** 2020-07-14 16:15 UTC
Labels: impact: crowd, plugin: auth, type: bug

**Comment by bulwinkel** [comment] 2020-07-27 23:36
Is it known yet which version of [firebase_auth](https://pub.dev/packages/firebase_auth/) the `userChanges` stream will be released in?
