### ISSUE TITLE
[firebase-crashlytics] Crashes hide exception information and have no stack trace 

### ISSUE THREAD

**Issue by escamoteur** [FirebaseExtended/flutterfire#216] opened 2019-09-25 09:07 UTC
Hi I came about this while triaging Flutter issues. Could you have a look at it if this is still an issue?
https://github.com/flutter/flutter/issues/30147

**Comment by BondarenkoStas** [comment] 2019-10-23 19:16
Closing it as the issue is moved here https://github.com/FirebaseExtended/flutterfire/issues/1151

**Closed by BondarenkoStas** 2019-10-23 19:16 UTC
Labels: bug
