### ISSUE TITLE
Dynamic link login is working on emulators but not on devices, getting RROR_INVALID_ACTION_CODE. Platform exception action code in the link is malformed, expired.

### ISSUE THREAD

**Issue by lsurage** [FirebaseExtended/flutterfire#1672] opened 2019-12-17 13:09 UTC
I am using flutter.
Dynamic link login is working on emulators but not on devices, getting 
ERROR_INVALID_ACTION_CODE. Platform exception action code in the link is malformed, expired, or has already been used.
This was working fine few days before, we checked our old builds also, where the were working fine, but old build are also throwing same error.

Below are code snippets i am using for email link generation:
`    PackageInfo packageInfo = await PackageInfo.fromPlatform();
    String packageName = packageInfo.packageName;
    String link;
    if (packageName == ConstantStrings.app_package_name_prod) {
      link = ConstantStrings.app_dynamic_link_prod;
    } else {
      packageName = ConstantStrings.app_package_name_dev;
      link = ConstantStrings.app_dynamic_link_dev;
    }
    final FirebaseAuth user = FirebaseAuth.instance;
    try {
      user.sendSignInWithEmailLink(
          email: email,
          androidInstallIfNotAvailable: true,
          androidMinimumVersion: "24",
          androidPackageName: packageName,
          iOSBundleID: packageName,
          url: link,
          handleCodeInApp: true);
      PreferencesHelper.setString(Preferences.id, email);
      Navigator.popAndPushNamed(context, Routes.checkYourEmail);
    } catch (e) {
      Dialogs.showPopUp(context, e.toString());
      return false;
    }
    return true;

Code where i am trying to log in using dynamic link:

static Future<void> signInWithEmailAndLink(
      String email, String link, BuildContext context, Function success) async {
    final FirebaseAuth user = FirebaseAuth.instance;
    bool validLink = await user.isSignInWithEmailLink(link);
    if (validLink) {
      try {
        AuthResult result = await user.signInWithEmailAndLink(
            email: email,
//            email: email ?? PreferencesHelper.getString(Preferences.id),
            link: link);
        if (result.user.isEmailVerified) {
          success();
        }
      } catch (e) {
        print(e);
        Dialogs.showPopUp(context, e.toString());
      }
    }
  }

this is working fine on emulatore and few devices, but few devices its thwoing the mentioned exception.

**Comment by lsurage** [comment] 2019-12-18 12:50
My findings about the deffect:

When I debugged deeper, found that when i tap on the new link recieved in mail, it takes me to my app but in method below where we receive the link back, i am always getting the very old link which i might have used days back, tried uninstalling the app also, even then i receive the old link. 
When i factory reset my device after that only its working and i am getting new link.
_```
FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {
      final Uri deepLink = dynamicLink?.link;

      if (deepLink != null && !_appStateStore.isUserSignedIn) {
        FirebaseUtils.signInWithEmailAndLink(
            await PreferencesHelper.getString(Preferences.id),
            deepLink.toString(),
            context,
            _onEmailLinkSignInSuccess);
      }
    }, onError: (OnLinkErrorException e) async {
      Dialogs.showPopUp(context, "Login Failed");
    });
```_


i think issue here with dynamic link cached in system memory.

**Comment by kirstywilliams** [comment] 2020-04-20 11:27
This is a duplicate of [#1537](https://github.com/FirebaseExtended/flutterfire/issues/1537) so will go ahead and close this so we can track the issue there.

**Closed by kirstywilliams** 2020-04-20 11:27 UTC
Labels: type: bug
