### ISSUE TITLE
Somebody have problem with RemoteNotification ?

### ISSUE THREAD

**Issue by lsahidin** [FirebaseExtended/flutterfire#6493] opened 2021-06-28 13:55 UTC
Could somebody help to understand the issue with RemoteNotification ? and how to solve.

![image](https://user-images.githubusercontent.com/12827784/123647678-7eba7980-d852-11eb-80c1-e6eb0b03dcaa.png)

in this code I cannot solved, based on attached pic

```
  FirebaseMessaging.onMessage.listen((RemoteMessage message) async {
    RemoteNotification notification = message.notification;
```
do I need to downgrade version? 

my dependencies:
  firebase_core: ^1.2.0
  firebase_messaging: ^10.0.0
  flutter_local_notifications: ^6.0.0

with Flutter: 2.2.0

thanks in advance

**Comment by varadkulk** [comment] 2021-06-28 15:30
Looks like the issue is with null handling
Try replace `message.notification` with `message!.notification!`

**Comment by gabrielrf97** [comment] 2021-06-28 15:34
Hey @lsahidin, hope you're doing well.

Actually, the error that you posted above is not related to the package itself, neither with your dependencies, but with Dart itself. 

Since flutter 2.0 upgrade, now null-safety is supported and you might check that out [here](https://dart.dev/null-safety/understanding-null-safety).

Summarizing, when given method, function or variable can have `null` as value, you can make it clearer by assigning the `?` operator. By doing so, you will know on compile time, that a null value can come as output there, and act accordingly.

To solve it, you can force-cast the value, doing the following:
`message!.notification!`, but you´ll see in your studies that this approach should be avoided. because if the value is null, a crash will be caused.

A second way to do this unwrapping is doing the following:
if (message != null) {
var _message = message!
//rest of your code goes here.
}

That will ensure that you check the optional value before force-casting it.

**Comment by darshankawar** [comment] 2021-06-29 08:13
@lsahidin 
This doesn't seem to be flutterfire specific issue. I suggest you to ask this question on support channels like StackOverflow. 
Closing from here.

**Closed by darshankawar** 2021-06-29 08:13 UTC
Labels: in triage
