### ISSUE TITLE
[Cloud functions>] Unable to call function FUNCTION_NAME

### ISSUE THREAD

**Issue by blaster92** [FirebaseExtended/flutterfire#1788] opened 2020-01-09 16:20 UTC
**Describe the bug**
Getting "Unable to call function FUNCTION_NAME" when running Flutter code on iOS device.

**Expected behavior**
The function returns the output of a cloud function routine.

**Comment by helenaford** [comment] 2020-04-20 13:01
Closing this due to lack of clarification. If still experiencing the issue, please create a new one with steps on how to reproduce.

**Closed by helenaford** 2020-04-20 13:01 UTC
Labels: type: bug
