### ISSUE TITLE
userAccessGroup Keychain setting not working according to docs

### ISSUE THREAD

**Issue by OGmetamonkey** [FirebaseExtended/flutterfire#6547] opened 2021-07-06 02:26 UTC
The description of the userAccessGroup keychain sharing feature says: "Set the property to your team group ID or set to null to remove sharing capabilities." I have my extensions configured to share keychains and have tested them successfully outside of flutter auth/firebase. 

When doing this with firebase_auth, I get this error:

> [firebase_auth/keychain-error] An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered

Setting:
```
  String userAccessGroupShared = "com.project.project-flutter";
  await user.setSettings(
            appVerificationDisabledForTesting: true, userAccessGroup: userAccessGroupShared);
          await user.signInWithEmailLink(email: _email, emailLink: _link); //ERROR OCCURS HERE
```
I used the Keychain Sharing - Keychain Groups attribute (from XCode config) for the "team group ID". Is this right?

**Comment by OGmetamonkey** [comment] 2021-07-06 20:36
I also tried this using the "Team ID" from [https://developer.apple.com/account/#/membership/](https://developer.apple.com/account/#/membership/) . Same result. 

```
String userAccessGroupShared = "TEAMIDFROMLINK";
  await user.setSettings(
            appVerificationDisabledForTesting: true, userAccessGroup: userAccessGroupShared);
```

> 2021-07-06 16:32:17.795340-0400 Runner[843:79577] flutter: [firebase_auth/keychain-error] An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered
> 2021-07-06 16:32:17.796084-0400 Runner[843:79577] flutter: catch exception for valid link above
> 2021-07-06 16:32:17.796696-0400 Runner[843:79577] flutter: [firebase_auth/keychain-error] An error occurred when accessing the keychain. The @c NSLocalizedFailureReasonErrorKey field in the @c NSError.userInfo dictionary will contain more information about the error encountered
> 2021-07-06 16:32:17.797230-0400 Runner[843:79577] flutter: USER NULL: null

**Comment by markusaksli-nc** [comment] 2021-07-07 09:34
Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6552

**Closed by markusaksli-nc** 2021-07-07 09:34 UTC
Labels: good first issue, in triage, type: documentation
