### ISSUE TITLE
[firebase_ml_vision] Custom model request

### ISSUE THREAD

**Issue by fatihbaltaci** [FirebaseExtended/flutterfire#2424] opened 2020-04-23 21:15 UTC
Hi, 
I want to use my custom models on Firebase mlkit with flutter. Is there any plan to release this feature?

Thanks.

**Comment by TahaTesser** [comment] 2020-04-24 10:26
Duplicate of [#401](https://github.com/FirebaseExtended/flutterfire/issues/401)

**Closed by TahaTesser** 2020-04-24 10:26 UTC
