### ISSUE TITLE
[cloud_firestore] disableNetwork and enableNetwork

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#676] opened 2019-10-13 18:52 UTC
For my app it would be nice to be able to enable and disable the synchronisation.
On SDKs for other platforms this is already possible, but Firestore for Flutter is missing this feature.
[https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#disableNetwork](https://firebase.google.com/docs/reference/js/firebase.firestore.Firestore#disableNetwork)

**Comment by kroikie** [comment] 2019-10-13 18:52
@GigaDroid

The issue at https://github.com/flutter/flutter/issues/21300 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by amatveyakin** [comment] 2020-05-06 10:11
A duplicate of #211?

**Comment by Ehesp** [comment] 2020-05-31 08:05
Will be supported as part of #2582

**Closed** 2020-05-31 08:06 UTC
Labels: plugin: cloud_firestore, resolution: duplicate, type: enhancement
