### ISSUE TITLE
🐛 [firebase_auth] iOS app crashes on Hot restart after upgrading to firebase_auth 1.1.3

### ISSUE THREAD

**Issue by bendiscz** [FirebaseExtended/flutterfire#6036] opened 2021-05-05 12:19 UTC
## Bug report

After upgrading to firebase_auth 1.1.3, my application started to crash on Hot restart (no problems with Hot reload) and I was able to reproduce this bug with `packages/firebase_auth/firebase_auth/example` application from this repository. This bug does not happen with firebase_auth 1.1.2 and before.

### Steps to reproduce

1. Go to `packages/firebase_auth/firebase_auth/example` (commit 8884d7e20b16af99a9dc1a7dc3aafdc843b5b1b9)
2. Comment out line `await FirebaseAuth.instance.useEmulator('http://localhost:9099');` in `lib/main.part` (disable Firebase Auth emulator use)
3. Start iOS Simulator (tested with iPhone 12 mini)
4. `flutter run`
5. Tap the 'Sign In' button
6. Hot restart the application
7. Application crashes (`Lost connection to device.`)

### Expected behavior

The application should restart and show the home page.

### Sample project

Please use the firebase_auth example application – commit 8884d7e20b16af99a9dc1a7dc3aafdc843b5b1b9 (firebase_auth@1.1.3) crashes on Hot restart, commit 79d6a62ebd429a728637909f6c4ea62e373ee9fd (firebase_auth@1.1.2) works fine.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.3 20E232 darwin-x64, locale cs-CZ)
    • Flutter version 2.0.6 at /usr/local/Caskroom/flutter/2.0.5/flutter
    • Framework revision 1d9032c7e1 (6 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/mbenda/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/mbenda/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/mbenda/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at /Users/mbenda/Applications/JetBrains Toolbox/IntelliJ IDEA Ultimate.app
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart

[✓] VS Code (version 1.55.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (2 available)
    • iPhone 12 mini (mobile) • BE52DE7F-39CB-4B19-8A69-274EECB1EFEA • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)            • chrome                               • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.3
Flutter SDK 2.0.6
firebase_auth_example 0.0.0

dependencies:
- firebase_auth 1.1.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.2 [firebase_core flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_signin_button 1.1.0 [flutter font_awesome_flutter]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]

dev dependencies:
- drive 0.1.0 [test_api flutter_test flutter_driver stack_trace universal_platform flutter]
- flutter_driver 0.0.0 [file meta path vm_service webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- http 0.13.3 [async http_parser meta path pedantic]
- test 1.16.5 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- firebase_auth 1.1.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_platform_interface 4.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_dynamic_links 2.0.2 [firebase_core flutter]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- coverage 0.15.2 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0 [clock collection]
- file 6.0.0 [meta path]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 8.12.0 [flutter]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- node_preamble 1.4.13
- package_config 1.9.3 [path charcode]
- path 1.8.0
- pedantic 1.11.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.0.0 [file path platform]
- pub_semver 2.0.0 [collection]
- quiver 3.0.1 [matcher]
- shelf 1.1.1 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.1 [path shelf shelf_static]
- shelf_static 0.2.9+2 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.2.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.15 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.0 [collection]
- universal_platform 0.1.3
- vector_math 2.1.0
- vm_service 5.5.0 [meta]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.0.0 [logging]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by mrgnhnt96** [comment] 2021-05-05 18:22
Glad to know I wasn't the only one. Any news when this will be fixed?

**Comment by walsha2** [comment] 2021-05-05 19:40
Same exact issue, except my error (upon a hot restart) is very cryptic and ugly. Through a lot of trial and error, I came to the same conclusion that `firebase_auth: ^1.1.3` was causing the problem.

```
Restarted application in 1,262ms.
-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x280c27570
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x280c27570'
*** First throw call stack:
(0x183b5986c 0x198b72c50 0x183a6095c 0x183b5c438 0x183b5e740 0x104f93878 0x104f959cc 0x104fa49dc 0x104fa2700 0x104fa167c 0x10662c694 0x105dcc038 0x1060cb41c 0x10606a81c 0x10606ced4 0x183ad5fa0 0x183ad5ba0 0x183ad4ffc 0x183aceee4 0x183ace21c 0x19b698784 0x18650eee8 0x18651475c 0x104efe710 0x18378e6b0)
libc++abi.dylib: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b1aa9414 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b1aa9414 <+8>:  b.lo   0x1b1aa9434               ; <+40>
    0x1b1aa9418 <+12>: pacibsp
    0x1b1aa941c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b1aa9420 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.

```

# Solution

Reverting to `firebase_auth: ^1.1.2` avoids the problem and I do not run into this issue.

**Comment by diegogarciar** [comment] 2021-05-05 19:43
I suggest reverting back to 1.1.1 as 1.1.2 had the auth events stream issue #5952

**Comment by hdavidmb** [comment] 2021-05-06 03:42
I'm having the same issue. I'll have to go back to 1.1.1 again.

**Comment by jonmountjoy** [comment] 2021-05-06 07:59
Yep - I noted it here and link to what I think caused it: https://github.com/FirebaseExtended/flutterfire/commit/eecdf7331913c1b5b062d12fa0659f698937e817#commitcomment-50357894

**Comment by GyuriMajercsik** [comment] 2021-05-06 09:02
Something similar happens on MacOS as well. Is this related or should I open a different issue ? 

```
2021-05-06 11:54:52.298 deescus[5511:959447] -[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x7fd861f8f260
2021-05-06 11:54:52.301 deescus[5511:959447] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x7fd861f8f260'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff206a098b __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007fff203d8d92 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff207233ad -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff206089bb ___forwarding___ + 1448
	4   CoreFoundation                      0x00007fff20608388 _CF_forwarding_prep_0 + 120
	5   deescus                             0x000000010561693e -[FLTFirebaseAuthPlugin cleanupWithCompletion:] + 398
	6   deescus                             0x0000000105618ddf -[FLTFirebaseAuthPlugin didReinitializeFirebaseCore:] + 63
	7   deescus                             0x00000001056286a2 -[FLTFirebasePluginRegistry didReinitializeFirebaseCore:] + 834
	8   deescus                             0x0000000105625ea4 -[FLTFirebaseCorePlugin initializeCoreWithMethodCallResult:] + 276
	9   deescus                             0x0000000105624b68 -[FLTFirebaseCorePlugin handleMethodCall:result:] + 504
	10  FlutterMacOS                        0x0000000109c0063d __56-[FlutterEngineRegistrar addMethodCallDelegate:channel:]_block_invoke + 45
	11  FlutterMacOS                        0x000000010a7ba6e7 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 119
	12  FlutterMacOS                        0x0000000109c029e0 -[FlutterEngine engineCallbackOnPlatformMessage:] + 272
	13  FlutterMacOS                        0x0000000109c0141c _ZL17OnPlatformMessagePK22FlutterPlatformMessageP13FlutterEngine + 44
	14  FlutterMacOS                        0x000000010a40c32d _ZNSt3__110__function6__funcIZ23FlutterEngineInitializeE4$_49NS_9allocatorIS2_EEFvN3fml6RefPtrIN7flutter15PlatformMessageEEEEEclEOS9_ + 125
	15  FlutterMacOS                        0x000000010a41d70a _ZN7flutter20PlatformViewEmbedder21HandlePlatformMessageEN3fml6RefPtrINS_15PlatformMessageEEE + 74
	16  FlutterMacOS                        0x000000010a180af9 _ZNSt3__110__function6__funcIZN7flutter5Shell29OnEngineHandlePlatformMessageEN3fml6RefPtrINS2_15PlatformMessageEEEE4$_38NS_9allocatorIS8_EEFvvEEclEv + 137
	17  FlutterMacOS                        0x000000010a41ab67 _ZN7flutter18EmbedderTaskRunner8PostTaskEy + 759
	18  FlutterMacOS                        0x000000010a402a1c FlutterEngineRunTask + 44
	19  FlutterMacOS                        0x0000000109c03a57 __60-[FlutterEngine postMainThreadTask:targetTimeInNanoseconds:]_block_invoke + 71
	20  libdispatch.dylib                   0x00007fff20382603 _dispatch_call_block_and_release + 12
	21  libdispatch.dylib                   0x00007fff203837e6 _dispatch_client_callout + 8
	22  libdispatch.dylib                   0x00007fff2038fb2f _dispatch_main_queue_callback_4CF + 940
	23  CoreFoundation                      0x00007fff206636f8 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	24  CoreFoundation                      0x00007fff206258e2 __CFRunLoopRun + 2755
	25  CoreFoundation                      0x00007fff2062475c CFRunLoopRunSpecific + 563
	26  HIToolbox                           0x00007fff28846203 RunCurrentEventLoopInMode + 292
	27  HIToolbox                           0x00007fff28845f65 ReceiveNextEventCommon + 587
	28  HIToolbox                           0x00007fff28845d03 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	29  AppKit                              0x00007fff22e20b32 _DPSNextEvent + 864
	30  AppKit                              0x00007fff22e1f305 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1364
	31  AppKit                              0x00007fff22e11679 -[NSApplication run] + 586
	32  AppKit                              0x00007fff22de585c NSApplicationMain + 816
	33  deescus                             0x0000000105605ccd main + 13
	34  libdyld.dylib                       0x00007fff20548f3d start + 1
	35  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi: terminating with uncaught exception of type NSException
```

**Comment by djphoenix** [comment] 2021-05-06 13:03
Crash is gone for me with patched `-[FLTFirebaseAuthPlugin cleanupWithCompletion:]` method:

```objc
- (void)cleanupWithCompletion:(void (^)(void))completion {
  // Cleanup credentials.
  [_credentials removeAllObjects];

  for (NSString *name in self->_eventChannels) {
    FlutterEventChannel *channel = [self->_eventChannels objectForKey:name];
    [channel setStreamHandler:nil];
  }
  [self->_eventChannels removeAllObjects];
  for (NSString *name in self->_streamHandlers) {
    NSObject<FlutterStreamHandler> *handler = [self->_streamHandlers objectForKey:name];
    [handler onCancelWithArguments:nil];
  }
  [self->_streamHandlers removeAllObjects];

  if (completion != nil) completion();
}
```

The original issue is caused by `for..in` loop that was iterated over dictionary keys but uses them as values.

**Comment by markusaksli-nc** [comment] 2021-05-06 13:42
Reproducible with auth `firebase_auth: ^1.1.3`
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.227, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.227 at /Users/nevercode/development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7f1d1414cc (23 hours ago), 2021-05-04 06:17:19 -0700
    • Engine revision 378e4dbc41
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.5
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 11.2.3 20D91 darwin-arm
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 90.0.4430.93

• No issues found!
```
</details>
<details>
 <summary>Logs</summary>

```
Performing hot restart...
Syncing files to device Nevercode’s iPhone...
Restarted application in 1,029ms.
-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x280b0bc50
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFString setStreamHandler:]: unrecognized selector sent to instance 0x280b0bc50'
*** First throw call stack:
(0x181de3128 0x195af6480 0x181cf2138 0x181de5784 0x181de79ac 0x1043cb574 0x1043cd654 0x1043db70c 0x1043d9678 0x1043d86cc 0x104c8c4f0 0x10499a7a4 0x104ca6910 0x104c3fe5c 0x104c4348c 0x181d62f80 0x181d62b80 0x181d62054 0x181d5c38c 0x181d5b6a8 0x19840b570 0x184679370 0x18467e8ec 0x1043bcd44 0x181a3a140)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001ada787b0 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1ada787b0 <+8>:  b.lo   0x1ada787cc               ; <+36>
    0x1ada787b4 <+12>: stp    x29, x30, [sp, #-0x10]!
    0x1ada787b8 <+16>: mov    x29, sp
    0x1ada787bc <+20>: bl     0x1ada551fc               ; cerror_nocancel
Target 0: (Runner) stopped.
```
</details>

**Comment by rod86** [comment] 2021-05-06 15:16
I have the same error and the solution by **djphoenix** solved this error.

**Comment by ericel** [comment] 2021-05-09 07:11
@djphoenix  where exactly is this piece of code should go? This has been driving me crazy.

**Comment by mafreud** [comment] 2021-05-09 16:49
Same problem

> Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked
Error handling 'serviceExtension' custom request: Bad state: No element

**Comment by Applitom** [comment] 2021-05-09 19:25
Hello,
I'm facing the same problem. I get the following errors:
> Restarted application in 777ms.
> Error handling 'checkPlatformOverride' custom request: method not available: ext.flutter.platformOverride
> Error handling 'checkBrightnessOverride' custom request: method not available: ext.flutter.brightnessOverride
> Error handling 'serviceExtension' custom request: method not available: ext.flutter.inspector.setPubRootDirectories
> Error handling 'checkIsWidgetCreationTracked' custom request: method not available: ext.flutter.inspector.isWidgetCreationTracked

Downgrade to `firebase_auth` 1.1.1 didn't help but implementing @djphoenix patch did work.
I'm using the following firebase versions:
>   firebase_auth: ^1.1.3
>   cloud_firestore: ^2.0.0
>   firebase_analytics: ^8.0.3
>   firebase_core: ^1.1.0
>   firebase_crashlytics: ^2.0.2

`flutter doctor`
> Doctor summary (to see all details, run flutter doctor -v):
> [✓] Flutter (Channel stable, 2.0.6, on Mac OS X 10.15.7 19H524 darwin-x64, locale en-IL)
> [✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
> [✓] Xcode - develop for iOS and macOS
> [✓] Chrome - develop for the web
> [✓] Android Studio (version 3.5)
> [✓] VS Code (version 1.56.0)
> [✓] Connected device (4 available)

Any idea?

**Closed** 2021-05-10 14:49 UTC
Labels: impact: crowd, platform: ios, plugin: auth, type: crash

**Comment by mark-taeyoung** [comment] 2021-05-11 00:51
My working solution is

**flutter clean && dart pub cache repair**

I'm using the following versions.

  firebase_auth: ^1.1.4
  firebase_core: ^1.1.0
  cloud_firestore: ^2.1.0
  google_sign_in: ^5.0.2
