### ISSUE TITLE
🐛 [firebase_admob] page ad, ios, "closed event" NOT fired but somehow fire "clicked event"

### ISSUE THREAD

**Issue by peterweb2005** [FirebaseExtended/flutterfire#4390] opened 2020-12-13 08:35 UTC
## Bug report

**Describe the bug**
android is ok,
but in ios, after closed the page ad, can only see "clicked event",

android always fire "closed event" since i used the sdk & page ad for 4 years
and the issue only found in ios just for 1 or 2 weeks

### Steps to reproduce

just normal use, and log every events of page ad

### Expected behavior

in ios,
expected the log show the ad event is "closed event" instead of the "clicked event"

### Flutter doctor

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-HK)
    • Flutter version 1.22.5 at /Users/peter/development/flutter
    • Framework revision 7891006299 (3 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[!] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/peter/Library/Android/sdk
    ✗ Flutter requires Android SDK 29 and the Android BuildTools 28.0.3
      To update the Android SDK visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • F9C8A894-4A33-4E5E-96B3-F43CF480CC1F • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-1 (simulator)
```

**Comment by darshankawar** [comment] 2020-12-14 11:40
@peterweb2005 
I tried the official `admob` plugin [example](https://pub.dev/packages/firebase_admob/example) on iOS simulator and logging each BannerAd event shows me below log:

```
flutter: Banner ad show callback success
flutter: BannerAd event MobileAdEvent.loaded
flutter: BannerAd loaded
flutter: BannerAd event MobileAdEvent.leftApplication
```

Are you referring to any specific ad (interstitial, banner) in your case ? Also can you provide when do you get `clicked event` for that ad ?

**Comment by peterweb2005** [comment] 2020-12-14 20:58
yes, sorry

the "page ad" is interstitial ad

when click to close the page ad
in android, fire "closed event"
but in ios, fire "clicked event"

and the ios incident just happens lately in 1-3 weeks

**Comment by darshankawar** [comment] 2020-12-15 08:01
@peterweb2005 
Thanks for clarifying. Below is what I see after tapping on `load interstitial` and then `show interstitial`:

iOS (simulator):

```
flutter: InterstitialAd event MobileAdEvent.loaded
flutter: InterstitialAd event MobileAdEvent.clicked
flutter: InterstitialAd event MobileAdEvent.impression
flutter: InterstitialAd event MobileAdEvent.closed

```
Android:

```
I/flutter (21412): InterstitialAd event MobileAdEvent.loaded
I/flutter (21412): InterstitialAd event MobileAdEvent.opened
I/flutter (21412): InterstitialAd event MobileAdEvent.closed

```
Per your above comment, you see `clicked event` when we close `interstitial ad`, but I see `flutter: InterstitialAd event MobileAdEvent.closed` as expected on both platforms.

<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (5 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!



```

</details>

**Comment by darshankawar** [comment] 2020-12-15 08:02
Related https://github.com/FirebaseExtended/flutterfire/issues/4302

**Comment by peterweb2005** [comment] 2020-12-15 10:16
> Related #4302

seems yes

**Comment by darshankawar** [comment] 2020-12-15 10:45
@peterweb2005 
Per your original issue, I wasn't able to replicate it, since I see `closed` event after closing interstitial ad. Are you still not getting `closed` event on iOS ?
Can you try the official plugin example and see if you get similar behavior ?

**Comment by peterweb2005** [comment] 2020-12-15 10:49
as my page ad not always show, i cant test frequently

and i can just recall that my case is that, in ios, the clicked event wrongly replaced closed event

**Comment by darshankawar** [comment] 2020-12-15 12:38
@peterweb2005 
As you can see the logs I shared above, I see the `closed` event being triggered after closing interstitial ad. I'd suggest you to  check the plugin example.

**Comment by peterweb2005** [comment] 2020-12-15 13:20
yes, 
but i opened this issue because i cant see the "closed event", (also checked NO once today when i could test the page ad)

here is the version i am using
```
  firebase_admob:
    dependency: "direct main"
    description:
      name: firebase_admob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.3"
```

and before that i checked the issue you have stated

**Comment by peterweb2005** [comment] 2020-12-16 01:02
can only see loaded and clicked

```
  @override
  onEvent(dynamic event) async {
    log.fine('**onEvent()');
    log.finest('event: ', event);
```

```
flutter: 2020-12-16 08:59:13.609420 FINE [PageAdHandler] load()
flutter: 2020-12-16 08:59:13.609809 FINEST [PageAdHandler] state:
flutter: 2020-12-16 08:59:13.672260 FINE [AdHandler] tryStartTimer()
flutter: 2020-12-16 08:59:13.674009 FINEST [AdHandler] state: AdState.Queuing
flutter: 2020-12-16 08:59:13.675677 FINEST [AdHandler] onData()
flutter: 2020-12-16 08:59:13.677482 FINEST [AdHandler] event: 0
flutter: 2020-12-16 08:59:13.679091 FINE [PageAdHandler] loadThenShow()
flutter: 2020-12-16 08:59:13.682285 FINEST [AdUtil] load: true
flutter: 2020-12-16 08:59:14.686706 FINEST [AdHandler] onData()
flutter: 2020-12-16 08:59:14.687001 FINEST [AdHandler] event: 1
flutter: 2020-12-16 08:59:14.934444 FINE [PageAdHandler] **onEvent()
flutter: 2020-12-16 08:59:14.934778 FINEST [PageAdHandler] event: MobileAdEvent.loaded
flutter: 2020-12-16 08:59:14.935165 FINEST [PageAdHandler] appInactive: false
flutter: 2020-12-16 08:59:14.937897 FINE [PageAdHandler] **onEvent()
flutter: 2020-12-16 08:59:14.939295 FINEST [PageAdHandler] event: MobileAdEvent.clicked
flutter: 2020-12-16 08:59:14.940707 FINE [AdHandler] stopTimer()
flutter: 2020-12-16 08:59:14.942730 FINE [AdHandler] dispose()
flutter: 2020-12-16 08:59:14.955100 FINEST [AdUtil] show: true
flutter: 2020-12-16 08:59:14.964397 FINEST [PageAdHandler] _onShown: Closure: () => dynamic
```

**Comment by darshankawar** [comment] 2020-12-16 07:33
@peterweb2005 
We would need a complete reproducible code sample that we can run locally to replicate the issue.

**Comment by peterweb2005** [comment] 2020-12-16 08:04
i am not familiar with ios app, finding it hard to run the example code in ios

does any other developer encounter this issue?
does clicking close button would fire "clicked event"

**Comment by darshankawar** [comment] 2020-12-16 08:27
@peterweb2005 
I am not aware of any other dev coming across such issue, apart from the one I related earlier, https://github.com/FirebaseExtended/flutterfire/issues/4302.
And in order to better address issue, please provide a minimal reproducible code sample, otherwise we will just keep talking about the issue and run around the bush. I'd advise you to look at whatever code implementation you have, with the plugin example and see if there's any missing section, due to which you are not able to see the `closed` event.

**Comment by peterweb2005** [comment] 2020-12-21 05:05
yes, i can see the "closed event"

i tested the example app, with an test id (cant use the default as below problem),
which the "page ad" would play movie like that happening in my issue,

i dont know, maybe i dispose something too early

flutter: InterstitialAd event MobileAdEvent.loaded
flutter: InterstitialAd event MobileAdEvent.clicked
flutter: InterstitialAd event MobileAdEvent.impression
flutter: InterstitialAd event MobileAdEvent.closed
flutter: InterstitialAd event MobileAdEvent.loaded
flutter: InterstitialAd event MobileAdEvent.clicked
flutter: InterstitialAd event MobileAdEvent.impression
flutter: InterstitialAd event MobileAdEvent.closed

**Comment by darshankawar** [comment] 2020-12-21 06:06
@peterweb2005 Thanks for getting back and good to know you are seeing the expected behavior.
Closing this as non-issue.

**Closed by darshankawar** 2020-12-21 06:06 UTC
Labels: Needs Attention
