### ISSUE TITLE
[cloud_firestore] permission_denied is not being emitted by the stream of snapshots.

### ISSUE THREAD

**Issue by allco** [FirebaseExtended/flutterfire#2334] opened 2020-04-09 13:00 UTC
In pubspec.yaml:
`cloud_firestore: 0.13.4+2`

Consider the following stream:
```
    Firestore.instance
        .collection('users')
        .document(firebaseUserId)
        .snapshots()
        .listen(
          (data) => print('onData: $data'),
          onError: (err, stack) => print('onError: $err'),
        );
```

Everything works fine until it gets `permission_denied` error which I can see in logs but the stream emits nothing. `onError` handler is not being called (along with `onData` with some erroneous data inside).
The worst part here is silence.

**To Reproduce**
1. Listen for a stream of snapshots of a document which current `firebaseUserId` don't have access to.

**Actual behavior**
Silence in the consumer code. 
And message in logs:
```
I/System.out( 3174): com.google.firebase.firestore.FirebaseFirestoreException: PERMISSION_DENIED: Missing or insufficient permissions.
```

**Expected behavior**
The Error somehow is being delivered to the consumer code, as onError or onData. 
And message in logs (which is already perfect).

**Additional context**
```
➜  ~ flutter doctor -v
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-GB)
    • Flutter version 1.12.13+hotfix.9 at /Users/alsk/Library/flutter
    • Framework revision f139b11009 (10 days ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/alsk/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.0.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[!] IntelliJ IDEA Community Edition (version 2019.3.4)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin version 193.6911.31
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] VS Code (version 1.43.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

I am using Android Studio as IDE.

**Comment by TahaTesser** [comment] 2020-04-14 14:54
Hi @allco 
This indicates missing permission
Please check out this [answer](https://stackoverflow.com/a/54444948)
Thank you

**Comment by allco** [comment] 2020-04-14 16:41
Yes, the reason is clear. But the problem is that the app isn't getting any signals of the error. From the app's prospective basically nothing happens which is bad since the has to react on errors.

**Comment by helenaford** [comment] 2020-04-21 11:38
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/384.

**Closed by helenaford** 2020-04-21 11:38 UTC
Labels: plugin: cloud_firestore, type: bug
