### ISSUE TITLE
[firebase_messaging] _TypeError (type 'List<dynamic>' is not a subtype of type 'List<String>')

### ISSUE THREAD

**Issue by csbence10** [FirebaseExtended/flutterfire#4359] opened 2020-12-09 16:42 UTC
**Description**
flutter version: 1.22.4
firebase_messaging version: 8.0.0-dev.11

I get the following error:
`_TypeError (type 'List<dynamic>' is not a subtype of type 'List<String>')`

The exception is caught in `remote_notification.dart` while calling:
```
return RemoteNotification(
      title: map['title'],
      titleLocArgs: map['titleLocArgs'] ?? [],
      titleLocKey: map['titleLocKey'],
      body: map['body'],
      bodyLocArgs: map['bodyLocArgs'] ?? [],
      bodyLocKey: map['bodyLocKey'],
      android: _android,
      apple: _apple,
    );
```
The exception is thrown by `titleLocArgs` and `bodyLocArgs`. These are defined as `List<String>`. 

Seems like these lists are truly `List<String>`s but somehow Dart cannot cast them and they appear as `List<dynamic>` therefore I get the error mentioned above. When I place a breakpoint in the constructor and check the type this way:
`map['titleLocArgs'] is List<String>` I get false.
The interesting part is I created a map in DartPad which is structured the same way and it says the expression is true. 
Any ideas why this happens? Dart version is 2.10.4 both for Flutter and DartPad.

**Comment by darshankawar** [comment] 2020-12-10 07:56
@csbence10 
Can you provide a minimal complete reproducible code sample that shows the issue ?
Thanks.

**Comment by csbence10** [comment] 2020-12-10 10:42
@darshankawar 
Of course. Open Postman and compose the following API request:

Method: POST
URL: https://fcm.googleapis.com/fcm/send

Headers: 
- Content-Type: application/json
- Authorization: key=<your_server_key>  <- found in the Firebase Console - Project settings - Cloud messaging menu

Body:
```
{
	"to" : "<your_fcm_token>",
	"collapse_key" : "whatever_you_prefer",
        "notification": {
                "body" : "Body",
		"title": "Title",
                "android": {},
                "title_loc_args": [""],
                "body_loc_args": [""]
    },
	"data" : {
        "click_action": "FLUTTER_NOTIFICATION_CLICK"
	}
}
```

Then click send. If the you get a `success = 1` in the response, everything is fine. 
Your app should be in the background and when you get the notification pull down the "notification center" or whatever it's called on Android and click on the notification. Your app comes back to the foreground and you get the error message I mentioned in my original post.

I hope that helps reproduce the issue. If not tell me and I'll help.
Cheers.

**Comment by darshankawar** [comment] 2020-12-10 12:39
@csbence10 Thanks for the details. I was able to replicate the error and get:

`_TypeError (type 'List<dynamic>' is not a subtype of type 'List<String>')`

The `titleLocArgs` and `bodyLocArgs` are indeed declared as `List<String>` in RemoteNotification.dart inside `firebase_messaging_platform_interface` : https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_notification.dart

`final List<String> titleLocArgs;`
`final List<String> bodyLocArgs;`

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details>

**Comment by Ehesp** [comment] 2020-12-10 12:42
Hmm, these might need changing to:

```
titleLocArgs: List<String>.from(map['titleLocArgs']) ?? [],
```

I guess the type from native is coming through as dynamic.

**Comment by Ehesp** [comment] 2020-12-11 10:04
@csbence10 I've just pushed a PR for this, however my local setup is complaining about running tests which I'm looking into (some local Dart thing). That fix should solve it (I think..) however I want to get a proper test in place.

I think you can pull locally via

```
  firebase_messaging_platform_interface:
    git:
      url: https://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_messaging/firebase_messaging_platform_interface
      ref: 20a8a33276d07d7d0386fc59e773d257b46b3c71
```

**Comment by csbence10** [comment] 2020-12-11 14:11
@Ehesp, thank you!

Works fine!

**Comment by drosa88** [comment] 2020-12-12 12:42
I have the same issue when receiving a background notification. Then the app crashes. How can I include your fix to my project?

The following...

`  firebase_messaging: "^8.0.0-dev.11"
    firebase_messaging_platform_interface:
    git:
      url: https://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_messaging/firebase_messaging_platform_interface
      ref: 20a8a33276d07d7d0386fc59e773d257b46b3c71`

..gives me the error: _Because firebase_messaging 8.0.0-dev.11 depends on firebase_messaging_platform_interface ^1.0.0-dev.7 and no versions of firebase_messaging match >8.0.0-dev.11 <9.0.0, firebase_messaging ^8.0.0-dev.11 requires firebase_messaging_platform_interface from hosted._

**Comment by Smartiiez** [comment] 2020-12-12 18:07
Hi 👋
I have a similar issue when I use..  ```
String token = await messaging.getToken(
  vapidKey: "BGpdLRs......",
);
```
..I got : 
`I/flutter (12122): type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'String' in type cast`

**Comment by csbence10** [comment] 2020-12-12 19:01
@drosa88 
I had the same problem. I found a workaround:
```
dependencies:
<your_dependencies_here>
firebase_messaging: 8.0.0-dev.11

dependency_overrides:
  firebase_messaging_platform_interface:
    git:
      url: https://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_messaging/firebase_messaging_platform_interface
      ref: 20a8a33276d07d7d0386fc59e773d257b46b3c71
```
However, I don't know whether this is the proper way or not. Also, I deleted the pubspec.lock file and the 
`<your_path_to_flutter>/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_platform_interface-1.0.0-dev.7 ` just to be sure.

**Comment by drosa88** [comment] 2020-12-13 08:55
> @drosa88 
> 
> I had the same problem. I found a workaround:
> 
> ```
> 
> dependencies:
> 
> <your_dependencies_here>
> 
> firebase_messaging: 8.0.0-dev.11
> 
> 
> 
> dependency_overrides:
> 
>   firebase_messaging_platform_interface:
> 
>     git:
> 
>       url: https://github.com/FirebaseExtended/flutterfire
> 
>       path: packages/firebase_messaging/firebase_messaging_platform_interface
> 
>       ref: 20a8a33276d07d7d0386fc59e773d257b46b3c71
> 
> ```
> 
> However, I don't know whether this is the proper way or not. Also, I deleted the pubspec.lock file and the 
> 
> `<your_path_to_flutter>/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging_platform_interface-1.0.0-dev.7 ` just to be sure.

Thank you! 👍

**Comment by JustChris** [comment] 2021-02-27 11:10
The trick is to use the fix version `firebase_messaging: 8.0.0-dev.14` without the `^`.
In my case it automatically updated the dev version to `8.0.0-dev.15` (which has obviously a bug in it) because of the `^`.
After removing it and running `pub get` it worked as expected.

Can't wait for the next stable version, which apparently will be 9 instead of 8.

Hope that helps :)

**Comment by JustChris** [comment] 2021-02-27 11:31
The trick is to use the fix version 

> The trick is to use the fix version `firebase_messaging: 8.0.0-dev.14` without the `^`.
> In my case it automatically updated the dev version to `8.0.0-dev.15` (which has obviously a bug in it) because of the `^`.
> After removing it and running `pub get` it worked as expected.
> 
> Can't wait for the next stable version, which apparently will be 9 instead of 8.
> 
> Hope that helps :)

Sry to disappoint you: It worked once for me for some reason and then it stopped working even with version `8.0.0-dev.14`..

**Comment by JustChris** [comment] 2021-02-27 11:52
Fun Fact: This problem only exists on a physical iPhone. On the Simulator it works fine.

**Comment by Salakar** [comment] 2021-04-08 17:48
Closing as this was fixed in https://github.com/FirebaseExtended/flutterfire/pull/4382 by @Ehesp a while back.

**Closed by Salakar** 2021-04-08 17:48 UTC
Labels: plugin: messaging, type: bug
