### ISSUE TITLE
Flutter web app - Google cloud functions - throws “firebase_functions/internal” internal error - listFruit

### ISSUE THREAD

**Issue by hallr-boulder** [FirebaseExtended/flutterfire#5428] opened 2021-03-22 20:05 UTC
Originally posted on SO here:
https://stackoverflow.com/questions/66615501/flutter-web-app-google-cloud-functions-throws-firebase-functions-internal
Is this a bug??

I've been struggling with an "internal error" in from a simple Flutter Web app that uses Google cloud functions for a couple of weeks and am looking for advice on what to try next to resolve this issue. 

My (test) Flutter app is very simple: a copy/paste of https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_functions/cloud_functions/example/lib/main.dart

This app uses cloud_functions to do an httpsCallable call to a Google cloud function called "listFruit2." When the call is made however the callable() method throws "[firebase_functions/internal] internal"

My real app does the same thing.

The Flutter App

A fragment of the dart code

    floatingActionButton: Builder(
      builder: (context) => FloatingActionButton.extended(
        onPressed: () async {
          // See index.js in the functions folder for the example function we
          // are using for this example
          HttpsCallable callable = FirebaseFunctions.instance.httpsCallable(
              'listFruit2',
              options: HttpsCallableOptions(
                  timeout: const Duration(seconds: 5)));

          await callable().then((v) {
            setState(() {
              fruit.clear();
              v.data.forEach((f) {
                fruit.add(f);
              });
            });
          }).catchError((e) {
            ScaffoldMessenger.of(context).showSnackBar(SnackBar(
              content: Text('ERROR: $e'),
            ));
          });
        },
        label: const Text('Call Function'),
        icon: const Icon(Icons.cloud),
        backgroundColor: Colors.deepOrange,
      ),
The index.html:

I have tried firebase-functions versions 7.14.4/7.22.1/8.2.1:

```
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Cloud Functions example app</title>
</head>
<body>
<!-- The core Firebase JS SDK is always required and must be listed first -->
<script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-firestore.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.22.1/firebase-functions.js"></script>

<!-- Initialize Firebase -->
<script>
  var firebaseConfig = {
    apiKey: "=====",
    authDomain: "=====.firebaseapp.com",
    databaseURL: "=====.firebaseio.com",
    projectId: "=====",
    storageBucket: "=====.appspot.com",
    messagingSenderId: "=====",
    appId: "====="
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
</script>
<script src="main.dart.js" type="application/javascript"></script>
</body>
</html>
```

The pubspec.yaml:

```
version: 1.0.0+1

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  cloud_functions: ^1.0.0
  firebase_core: ^1.0.1

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
```

The Cloud Function

```
// The Cloud Functions for Firebase SDK to create Cloud Functions and setup triggers.
const functions = require('firebase-functions');

exports.listFruit2 = functions.https.onCall(() => {
  return ["Apple", "Banana", "Cherry", "Date", "Fig", "Grapes"]
});
```

The package.json

```
{
    "name": "functions",
    "description": "Cloud Functions for Firebase",
    "engines": {
        "node": "12"
    },
    "main": "lib/index.js",
    "dependencies": {
        "firebase-admin": "^9.2.0",
        "firebase-functions": "^3.11.0" 
    },
    "private": true
}
```

The deploy parameters

`gcloud functions deploy listFruit2 --entry-point listFruit2 --trigger-http --runtime nodejs12`

Gcloud describe: 

```
availableMemoryMb: 256 
buildId: 149b08ba-5d6d-46b2-8e9c-6e3273e273ab 
entryPoint: listFruit2 
httpsTrigger: 
securityLevel: SECURE_OPTIONAL 
url: us-central1-====.cloudfunctions.net/listFruit2 
ingressSettings: ALLOW_ALL 
labels: 
deployment-tool: 
console-cloud name: projects/====/locations/us-central1/functions/listFruit2 
runtime: nodejs12 
serviceAccountEmail: ====@appspot.gserviceaccount.com 
sourceUploadUrl: storage.googleapis.com/gcf-upload-us-central1-... 
status: ACTIVE 
timeout: 60s 
updateTime: '2021-03-13T16:31:37.980Z' 
versionId: '7' –
```

Flutter doctor

```
[√] Flutter (Channel beta, 2.0.1, on Microsoft Windows [Version 10.0.19042.867], locale en-US)
    • Flutter version 2.0.1 at C:\flutter_sdk
    • Framework revision c5a4b4029c (9 days ago), 2021-03-04 09:47:48 -0800
    • Engine revision 40441def69
    • Dart version 2.12.0

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\hallr\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 88.0.4324.190
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 89.0.774.50

• No issues found!
```

Other Info

- The cloud functions work correctly from the cmd line using gcloud
- There is no indication in the cloud function logs that "listFruit2" ran from the Flutter app
- Identical "internal error" using Chrome & Edge
- No problems using cloud functions with other triggers: create/change/delete (i.e. problem only occurs using httpsCallable/onCall)
- No problems accessing/modifying Firebase storage from more complex Flutter apps

**Comment by markusaksli-nc** [comment] 2021-03-23 12:20
Hi @hallr-boulder 
Are you using the emulator? The example app uses it by default so you need to start the emulator in order for it to work. This is a slightly modified example with a boolean (default off)
<details>
 <summary>Code sample</summary>

```dart
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// @dart=2.9

import 'dart:async';
import 'dart:core';

import 'package:cloud_functions/cloud_functions.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

const USE_EMULATOR = false;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  if(USE_EMULATOR) {
    FirebaseFunctions.instance
        .useFunctionsEmulator(origin: 'http://localhost:5001');
  }
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  MyApp({Key key}) : super(key: key);
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  List fruit = [];

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Firebase Functions Example'),
        ),
        body: Center(
            child: ListView.builder(
                itemCount: fruit.length,
                itemBuilder: (context, index) {
                  return ListTile(
                    title: Text('${fruit[index]}'),
                  );
                })),
        floatingActionButton: Builder(
          builder: (context) => FloatingActionButton.extended(
            onPressed: () async {
              // See index.js in the functions folder for the example function we
              // are using for this example
              HttpsCallable callable = FirebaseFunctions.instance.httpsCallable(
                  'listFruit',
                  options: HttpsCallableOptions(
                      timeout: const Duration(seconds: 5)));

              await callable().then((v) {
                setState(() {
                  fruit.clear();
                  v.data.forEach((f) {
                    fruit.add(f);
                  });
                });
              }).catchError((e) {
                ScaffoldMessenger.of(context).showSnackBar(SnackBar(
                  content: Text('ERROR: $e'),
                ));
              });
            },
            label: const Text('Call Function'),
            icon: const Icon(Icons.cloud),
            backgroundColor: Colors.deepOrange,
          ),
        ),
      ),
    );
  }
}
```
</details>

As for which JS version to use please refer to the official documentation at 
https://firebase.flutter.dev/docs/functions/overview#3-web-only-add-the-sdk
We test against a fixed JS SDK version so if you use a newer version it is not guaranteed to work.
Thank you

**Comment by hallr-boulder** [comment] 2021-03-23 13:39
Hi @markusaksli-nc 

Thanks for your comments. 

1. No, I am not using the emulator. Sorry for not making this clear.
2. I have tested against various JS versions but unfortunately all (including 7.20.0) throw the same exception

Very puzzling. Thanks again.

**Comment by hallr-boulder** [comment] 2021-03-23 23:30
Tested cloud_functions 1.0.1 : no change

**Comment by markusaksli-nc** [comment] 2021-03-24 11:43
Strange, I'm not seeing this. Could you provide the full stack trace you are getting?

**Comment by hallr-boulder** [comment] 2021-03-24 14:41
Using JS version 7.20.0 and Flutter run -v:  Is this what you need?

```
[  +50 ms] executing: [C:\flutter_sdk/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[  +51 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[        ] c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] executing: [C:\flutter_sdk/] git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[  +43 ms] Exit code 0 from: git tag --points-at c5a4b4029c0798f37c4a39b479d7cb75daa7b05c
[        ] 2.0.1
[  +27 ms] executing: [C:\flutter_sdk/] git rev-parse --abbrev-ref --symbolic @{u}
[  +33 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\flutter_sdk/] git ls-remote --get-url origin
[  +27 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[  +53 ms] executing: [C:\flutter_sdk/] git rev-parse --abbrev-ref HEAD
[  +29 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +54 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +45 ms] executing: C:\Users\hallr\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[  +31 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +56 ms] executing: C:\Users\hallr\AppData\Local\Android\sdk\platform-tools\adb.exe devices -l
[   +8 ms] Skipping pub get: version match.
[  +15 ms] Found plugin cloud_functions at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\cloud_functions-1.0.1\
[   +5 ms] Found plugin cloud_functions_web at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-4.0.2\
[   +7 ms] Found plugin firebase_core at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.0.2\
[   +2 ms] Found plugin firebase_core_web at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\
[  +85 ms] Found plugin cloud_functions at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\cloud_functions-1.0.1\
[   +1 ms] Found plugin cloud_functions_web at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-4.0.2\
[   +4 ms] Found plugin firebase_core at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.0.2\
[   +1 ms] Found plugin firebase_core_web at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\
[  +24 ms] Generating C:\RDevelopment\CloudPlayground\listfruit_example\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[  +50 ms] List of devices attached
[  +42 ms] Launching lib\main.dart on Chrome in debug mode...
[  +13 ms] List of devices attached
[  +71 ms] Updating assets
Waiting for connection from debug service on Chrome...
[  +89 ms] Found plugin cloud_functions at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\cloud_functions-1.0.1\
[   +1 ms] Found plugin cloud_functions_web at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-4.0.2\
[   +3 ms] Found plugin firebase_core at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.0.2\
[   +1 ms] Found plugin firebase_core_web at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\
[  +21 ms] Found plugin cloud_functions at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\cloud_functions-1.0.1\
[   +1 ms] Found plugin cloud_functions_web at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\cloud_functions_web-4.0.2\
[   +3 ms] Found plugin firebase_core at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.0.2\
[   +1 ms] Found plugin firebase_core_web at C:\flutter_sdk\.pub-cache\hosted\pub.dartlang.org\firebase_core_web-1.0.2\
[  +55 ms] <- reset
[   +4 ms] C:\flutter_sdk\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev C:\flutter_sdk\bin\cache\artifacts\engine\windows-x64\frontend_server.dart.snapshot --sdk-root C:\flutter_sdk\bin\cache\flutter_web_sdk/ --incremental --target=dartdevc --debugger-module-names --experimental-emit-debug-metadata -Dflutter.inspector.structuredErrors=true -DFLUTTER_WEB_AUTO_DETECT=true --output-dill C:\Users\hallr\AppData\Local\Temp\flutter_tools.a325561\flutter_tool.953bedd1\app.dill --libraries-spec file:///C:/flutter_sdk/bin/cache/flutter_web_sdk/libraries.json --packages C:\RDevelopment\CloudPlayground\listfruit_example\.dart_tool\package_config.json -Ddart.vm.profile=false -Ddart.vm.product=false --enable-asserts --track-widget-creation --filesystem-root C:\Users\hallr\AppData\Local\Temp\flutter_tools.a325561\flutter_tools.309f813f --filesystem-scheme org-dartlang-app --initialize-from-dill build\f58ed05f7a6fba8f3451773989665e4b.cache.dill.track.dill --platform file:///C:/flutter_sdk/bin/cache/flutter_web_sdk/kernel/flutter_ddc_sdk.dill --no-sound-null-safety
[   +5 ms] <- compile org-dartlang-app:/web_entrypoint.dart
[+11200 ms] Synced 29.3MB.
[        ] <- accept
[        ] Caching compiled dill
[ +536 ms] Using Opening in existing browser session.

[+1068 ms] [CHROME]:
[        ] [CHROME]:DevTools listening on ws://127.0.0.1:50264/devtools/browser/f8129ad2-0d77-4e30-a4bd-d6068f750366
[+1176 ms] DwdsInjector: Received request for entrypoint at http://localhost:50201/main_module.bootstrap.js
[   +3 ms] MetadataProvider: Loading debug metadata...
[   +6 ms] MetadataProvider: Loaded debug metadata
[   +4 ms] DwdsInjector: Injected debugging metadata for entrypoint at http://localhost:50201/main_module.bootstrap.js
[+3401 ms] DevHandler: Debug service listening on ws://127.0.0.1:50297/FcTJVL45Ja8=/ws

[   +5 ms] Debug service listening on ws://127.0.0.1:50297/FcTJVL45Ja8=/ws
[        ] Running with unsound null safety
[        ] For more information see https://dart.dev/null-safety/unsound-null-safety
Debug service listening on ws://127.0.0.1:50297/FcTJVL45Ja8=/ws
[+6894 ms] Error: [firebase_functions/internal] internal


               at Object.throw_ [as throw] (http://localhost:50201/dart_sdk.js:5334:11)
               at https_callable_web.HttpsCallableWeb.new.call (http://localhost:50201/packages/cloud_functions_web/https_callable_web.dart.lib.js:55:23)
               at call.throw (<anonymous>)
               at http://localhost:50201/dart_sdk.js:39038:38
               at _RootZone.runBinary (http://localhost:50201/dart_sdk.js:38894:58)
               at _FutureListener.thenAwait.handleError (http://localhost:50201/dart_sdk.js:33887:48)
               at handleError (http://localhost:50201/dart_sdk.js:34451:51)
               at Function._propagateToListeners (http://localhost:50201/dart_sdk.js:34477:17)
               at _Future.new.[_completeError] (http://localhost:50201/dart_sdk.js:34323:23)
               at async._AsyncCallbackEntry.new.callback (http://localhost:50201/dart_sdk.js:34362:31)
               at Object._microtaskLoop (http://localhost:50201/dart_sdk.js:39176:13)
               at _startMicrotaskLoop (http://localhost:50201/dart_sdk.js:39182:13)
               at http://localhost:50201/dart_sdk.js:34689:9
[+11261 ms] DevHandler: Stopped debug service on ws://127.0.0.1:50295
```

**Comment by markusaksli-nc** [comment] 2021-03-25 08:58
Seems like this is a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2558

Could you follow up on that issue and comment that this occurs on the latest version?

**Closed by markusaksli-nc** 2021-03-25 08:58 UTC
Labels: Needs Attention

**Comment by hallr-boulder** [comment] 2021-03-25 15:23
I've tested JS 7.22.1 (as mentioned above in this thread) with and without the options request to the browser. Still seeing the exception.  I'm not sure this issue should be closed just yet.

**Comment by markusaksli-nc** [comment] 2021-03-26 11:04
Closed due to this being a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2558 which is already an open issue tracking this

**Comment by hallr-boulder** [comment] 2021-03-26 15:44
Making a very big assumption here that the issue is the same.  The comment quoted below from #2558 indicates that JS 7.22.1 works while that is not what I am seeing.

> Seems 7.22.0 version is broken for cloud functions, but for 7.22.1, it is working.

**Comment by markusaksli-nc** [comment] 2021-03-29 13:57
That seems to be what one user commented. You could comment with what versions you are facing the issue on. Since the error is the same, I don't really see a reason to keep this open as a separate issue since the only difference is the JS SDK versions.
