### ISSUE TITLE
🐛 [firebase_analytics] Web app in Safari does not work if dependency is added.

### ISSUE THREAD

**Issue by Andranjo97** [FirebaseExtended/flutterfire#6968] opened 2021-09-08 17:33 UTC
## Bug report

**Describe the bug**
Just by adding the dependency `firebase_analytics: ^7.0.1` to my `pubspec.yaml`, and running the app in safari, causes a crash.

### Steps to reproduce

1. Add `firebase_analytics: ^7.0.1` to the pubspec.yaml
2. Run the app in Safari
4. White screen appears and in the console you can see the following:
```
Unhandled Promise Rejection: FirebaseError: Firebase: No Firebase App '[DEFAULT]' has been created - call Firebase App.initializeApp() (app/no-app).
```

I do not call the function `Firebase.initializeApp()` when the browser is Safari. This is because I use firebase messaging. And, firebase messaging is not supported in Safari. I had the same issue with firebase messaging, but they solved it [here](https://github.com/FirebaseExtended/flutterfire/issues/4473)

### Expected behavior

Safari should not break if dependency is added to a project's dependencies.

### Sample project

my file `main.dart` looks like this:

```
import 'package:platform_detect/platform_detect.dart';

void main() async {
  if (!browser.isSafari) await Firebase.initializeApp();
  runApp(MyApp())
}
```

---

## Additional context

I do not call the function `Firebase.initializeApp()` when the browser is Safari. This is because I use firebase messaging. And, firebase messaging is not supported in Safari. I had the same issue with firebase messaging, but they solved it [here](https://github.com/FirebaseExtended/flutterfire/issues/4473)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel unknown, 2.0.0, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.60.0)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.0
myapp 1.40.1

dependencies:
- bloc_test 5.1.0 [bloc mockito test meta]
- cached_network_image 2.5.1 [flutter flutter_cache_manager octo_image]
- carousel_slider 2.3.4 [flutter]
- csv 4.1.0
- cupertino_icons 0.1.3
- dartz 0.9.2
- equatable 1.2.6 [collection meta]
- firebase_analytics 7.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_dynamic_links 0.7.0+1 [flutter firebase_core]
- firebase_messaging 8.0.0-dev.15 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- flex_color_picker 1.1.5 [flutter]
- fluro 1.7.8 [flutter]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 4.0.1 [flutter bloc provider]
- flutter_redux 0.7.0 [meta redux flutter]
- flutter_web_auth 0.2.4 [flutter]
- fluttertoast 7.1.8 [flutter flutter_web_plugins]
- font_awesome_flutter 8.12.0 [flutter]
- get_it 4.0.4 [async meta]
- hexcolor 1.0.6 [flutter flutter_web_plugins]
- intl 0.16.1 [path]
- intl_phone_field 1.4.4 [flutter]
- intl_phone_number_input 0.6.0 [flutter meta libphonenumber libphonenumber_plugin equatable]
- json_annotation 3.1.1
- mailto 2.0.0
- pdf 2.1.0 [archive barcode crypto image meta path_parsing vector_math xml]
- percent_indicator 2.1.9+1 [flutter]
- plaid_flutter 2.1.1 [flutter flutter_web_plugins js]
- platform_detect 1.4.0 [meta pub_semver]
- redux 4.0.0+3
- redux_thunk 0.3.0 [redux]
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- stripe_sdk 3.2.0 [flutter http url_launcher mask_text_input_formatter flutter_slidable simple_animations supercharged awesome_card uni_links]
- timezone 0.5.9 [path]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- uuid 2.2.2 [crypto convert]
- validators 2.0.1 [vin_decoder]

dev dependencies:
- build_runner 1.11.5 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 3.5.1 [analyzer build build_config json_annotation meta path source_gen]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0 [collection]
- awesome_card 1.1.5 [flutter]
- barcode 1.17.1 [meta qr]
- basic_utils 2.7.1 [http logging json_annotation pointycastle convert crypto]
- bloc 4.0.0 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.6.2 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.6 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.3 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.10 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- coverage 0.15.2 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- dart_style 1.3.12 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_messaging_platform_interface 1.0.0-dev.10 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.6 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- fixnum 1.0.0
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_slidable 0.5.7 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 0.2.0
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- io 0.3.5 [meta path string_scanner]
- js 0.6.3
- libphonenumber 1.0.2 [flutter meta]
- libphonenumber_platform_interface 0.2.0 [flutter plugin_platform_interface]
- libphonenumber_plugin 0.1.0 [flutter flutter_web_plugins libphonenumber_platform_interface libphonenumber_web]
- libphonenumber_web 0.1.1 [flutter flutter_web_plugins js libphonenumber_platform_interface]
- logging 0.11.4
- mask_text_input_formatter 1.2.1 [flutter]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 0.9.7
- mockito 4.1.4 [analyzer build code_builder collection dart_style matcher meta source_gen test_api]
- nested 1.0.0 [flutter]
- node_preamble 1.4.13
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.28 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.5 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 3.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 2.0.1
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- provider 4.3.3 [collection flutter nested]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.8 [checked_yaml json_annotation pub_semver yaml]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- random_string 2.1.0
- rxdart 0.25.0
- sa_v1_migration 1.1.2 [flutter]
- service_worker 0.2.4 [js]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.1 [path shelf shelf_static]
- shelf_static 0.2.9+2 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- simple_animations 2.5.1 [flutter supercharged sa_v1_migration pedantic]
- sky_engine 0.0.99
- source_gen 0.9.10+3 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- supercharged 1.12.0 [supercharged_dart flutter]
- supercharged_dart 1.4.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test 1.16.5 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.15 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0 [collection]
- uni_links 0.4.0 [flutter]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0
- vin_decoder 0.1.3 [meta basic_utils http random_string]
- vm_service 6.2.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- webkit_inspection_protocol 0.7.5 [logging]
- win32 2.0.5 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-09-09 08:36
Hi @Andranjo97 
I'm pretty sure this is a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/3962 but correct me if I'm wrong.
Closing it as such for now.
Thank you

**Closed by markusaksli-nc** 2021-09-09 08:36 UTC
Labels: type: bug, Needs Attention, in triage
