### ISSUE TITLE
🐛 [firebase_remote_config] FormatException: Invalid envelope

### ISSUE THREAD

**Issue by feinstein** [FirebaseExtended/flutterfire#7063] opened 2021-09-24 19:19 UTC
I am using the latest version of remote config, 0.11.0 and when an Android App starts offline the method `fetchAndActivate` throws an exception `FormatException: Invalid Envelope`.

Everything works fine if the app phone is online. 

Also, if I surround the call in a `try catch`, so the app doesn't crash, the lib won't load the defaults I am passing before I call `fetchAndUpdate`. 

Thus, I don't see the point of having defaults, if the lib crashes while offline and no value is loaded from defaults.

**Comment by markusaksli-nc** [comment] 2021-09-27 18:05
Hi @feinstein 
I would consider this a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6993 so closing as such.
Thank you

**Closed by markusaksli-nc** 2021-09-27 18:05 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by feinstein** [comment] 2021-09-27 18:19
@markusaksli-nc they are not the same. Mine only happens when the phone is offline. The other issue happens all the time, not regarding the connectivity status.

**Comment by markusaksli-nc** [comment] 2021-09-27 18:48
Well given that this is a subset of the other one I'd rather track it in the same place to avoid confusion. Since we can clearly reproduce it when the app starts offline then it can give some clues on why people are seeing this issue more generally.
