### ISSUE TITLE
🐛 [firebase_analytics] flutter pub get fails

### ISSUE THREAD

**Issue by josefwilhelm** [FirebaseExtended/flutterfire#5277] opened 2021-03-09 11:53 UTC
## Bug report

**Describe the bug**
Running 'flutter pub get fails' with following error message

> Because firebase_auth >=1.0.0 depends on firebase_auth_web ^1.0.0 which depends on http_parser ^4.0.0, firebase_auth >=1.0.0 requires http_parser ^4.0.0.
> 
> And because firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0, firebase_auth >=1.0.0 is incompatible with firebase >=7.0.0 <9.0.0.
> 
> And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, firebase_auth >=1.0.0 is incompatible with firebase_analytics >=7.1.0.
> So, because tag_me depends on both firebase_analytics ^7.1.0 and firebase_auth ^1.0.0, version solving failed.
> 
> pub get failed (1; So, because tag_me depends on both firebase_analytics ^7.1.0 and firebase_auth ^1.0.0, version solving failed.)
> exit code 1

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.1 20C69 darwin-x64, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.54.1)
[✓] Connected device (2 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

Can't run it because flutter pub get fails

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by theniceboy** [comment] 2021-03-09 11:56
Same here

**Comment by Salakar** [comment] 2021-03-09 12:12
Duplicate of #5202.

**Closed by Salakar** 2021-03-09 12:12 UTC
Labels: Needs Attention, type: bug
