### ISSUE TITLE
Crashlytics test crash does not work on iOS

### ISSUE THREAD

**Issue by nhatzbulawan** [FirebaseExtended/flutterfire#5003] opened 2021-02-10 10:44 UTC
Hi, 

I have the same issue with https://github.com/FirebaseExtended/flutterfire/issues/4022.

I tried to search for some fixes but I cannot find one. I tried https://github.com/FirebaseExtended/flutterfire/issues/3837 and https://github.com/FirebaseExtended/flutterfire/issues/3904#issuecomment-713095148 but still no success.

I noticed this log message while running but cannot find a better article to describe this log
[connection] nw_resolver_start_query_timer_block_invoke [C1] Query fired: did not receive all answers in time for firebaselogging-pa.googleapis.com:443

I also added the logs below.

<details>
 <summary>flutter run -v</summary>
[flutter run 1.txt](https://github.com/FirebaseExtended/flutterfire/files/5957528/flutter.run.1.txt)

Added the FirebaseApp.configure() in AppDelegate.swift
[flutter run 2.txt](https://github.com/FirebaseExtended/flutterfire/files/5957529/flutter.run.2.txt)
</details>

<details>
 <summary>flutter pub deps -- --style=compact</summary>
Dart SDK 2.12.0-133.7.beta
Flutter SDK 1.25.0-8.3.pre
animaldietformulator 1.0.0+1

dependencies:
- cupertino_icons 1.0.2
- device_info 1.0.0 [flutter device_info_platform_interface]
- dotted_border 1.0.7 [flutter path_drawing]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.4.0+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_performance 0.5.0+1 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_modular 2.0.1 [flutter]
- flutter_speed_dial 2.1.1 [flutter]
- flutter_svg 0.19.2+1 [flutter meta path_drawing vector_math xml]
- font_awesome_flutter 8.11.0 [flutter]
- form_field_validator 1.0.1 [flutter intl]
- google_fonts 1.1.2 [flutter http path_provider crypto]
- hive 1.4.4+1 [meta crypto]
- hive_flutter 0.3.1 [flutter hive path_provider path]
- http 0.12.2 [http_parser path pedantic]
- modal_bottom_sheet 1.0.0+1 [flutter]
- recase 3.0.1
- rxdart 0.25.0
- universal_io 1.0.2 [crypto meta zone_local]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]

dev dependencies:
- build_runner 1.11.1 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.8.1 [image args yaml path]
- flutter_native_splash 0.2.11 [yaml image xml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 0.8.2 [build source_gen hive analyzer dartx]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.3 [collection]
- boolean_selector 2.1.0-nullsafety.3 [source_span string_scanner]
- build 1.6.2 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.5 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.7 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.3 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.7 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.5
- charcode 1.2.0-nullsafety.3
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.3
- code_builder 3.6.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.5
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- dart_style 1.3.11 [analyzer args path pub_semver source_span]
- dartx 0.5.0 [collection path crypto characters time meta]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0-nullsafety.3 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.6 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3-nullsafety.3
- json_annotation 3.1.1
- logging 0.11.4
- matcher 0.12.10-nullsafety.3 [stack_trace]
- meta 1.3.0-nullsafety.6
- mime 0.9.7
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.3
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.7 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.5 [matcher meta]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.4 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 0.9.10+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.4 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.6 [path]
- stream_channel 2.1.0-nullsafety.3 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.3 [charcode source_span]
- term_glyph 1.2.0-nullsafety.3
- test_api 0.2.19-nullsafety.6 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- time 1.4.0
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0-nullsafety.5 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0-nullsafety.5
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- win32 1.7.4+1 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
- zone_local 0.1.2

</details>
<details>
  <summary>flutter -v</summary>
  
[✓] Flutter (Channel beta, 1.25.0-8.3.pre, on macOS 11.1 20C69 darwin-arm, locale en-AE)
    • Flutter version 1.25.0-8.3.pre at /Users/furchildit/Downloads/flutter
    • Framework revision 5d36f2e7f5 (4 weeks ago), 2021-01-14 15:57:49 -0800
    • Engine revision 7a8f8ca02c
    • Dart version 2.12.0 (build 2.12.0-133.7.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/furchildit/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (2 available)
    • iPhone (mobile)            • 56f051c91195dd4a87e378041c19b91636c19f94 • ios • iOS 14.4
    • iPhone 12 Pro Max (mobile) • DCE0E14A-ECC3-4A63-BBEE-EC7E26D93A81     • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

• No issues found!
</details>

**Comment by markusaksli-nc** [comment] 2021-02-12 13:21
Hi @nhatzbulawan 
Did I understand correctly that the issue is that the crash does not crash the app? Or is it that the crash is not logged in Firebase console?
Is this on a simulator or physical device?
Thank you

**Comment by nhatzbulawan** [comment] 2021-02-13 07:46
Hi @markusaksli-nc ,

The crash is not logged in Firebase Console.
I tried both in simulator and physical device(debug mode)

**Comment by markusaksli-nc** [comment] 2021-02-15 11:37
Have you done https://firebase.flutter.dev/docs/crashlytics/overview#b-ios

**Comment by nhatzbulawan** [comment] 2021-02-15 13:28
@markusaksli-nc, yes I did. But not item 4.

**Comment by markusaksli-nc** [comment] 2021-02-15 14:10
In that case it should work. Are you getting any messages about missing dSYMs in Firebase Console?

Are the other logs working?

**Comment by nhatzbulawan** [comment] 2021-02-15 14:19
@markusaksli-nc, no I am not. In the logs I attached in this comment https://github.com/FirebaseExtended/flutterfire/issues/5003#issue-805395752, I can see the log for the crash

> *** Terminating app due to uncaught exception 'FirebaseCrashlyticsTestCrash', reason: 'This is a test crash caused by calling .crash() in Dart.

However, it is not sending the information to Firebase Console.

**Comment by markusaksli-nc** [comment] 2021-02-15 14:46
I meant the other functionalities of the crashlytics plugin. (such as in the official example).

**Comment by nhatzbulawan** [comment] 2021-02-16 06:40
@markusaksli-nc,

I already managed to make it work. 

Upon researching, I came across this comment.

> Xcode debugger does NOT allow Crashlytics to process crash reports. Yeah, that seem weird even to me when I read that first time but it is a fact (Source). That's is the reason we never see crash report When:
> - running app in Simulator
> - running app on iDevice by directly build and run from Xcode with debugger on.
> 
> To make sure a crash is reported during your testing (copied from Crashlytics support site):
> 1. Launch simulator
> 2. Press stop
> 3. Launch your app and force a crash
> 4. Relaunch the app from simulator
> 5. See the crash report in the web dashboard.

However, since iOS14+ you cannot launch the app without using Debugging tools such as Flutter tooling or xCode.

To bypass the restriction, I build it in release mode using this step.

1. Edit Scheme -> Build Configuration (Release).
2. Be sure to uncheck or remove the "-FIRAnalyticsDebugEnabled"
2. Before building the app, check the Release Signing and Capabilities Configuration

Hope this comment, can help someone that has the same issue. Or maybe your team can also add some comments in the flutter fire website steps for configuration.

**Comment by markusaksli-nc** [comment] 2021-02-16 07:31
Thanks, closing this as solved

**Closed by markusaksli-nc** 2021-02-16 07:31 UTC
Labels: Needs Attention, type: bug
