### ISSUE TITLE
W/BiChannelGoogleApi(27734): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@832113d

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#352] opened 2019-10-13 18:12 UTC
Hello.
I'm working on a mobile application using Flutter and Firebase from a while but only now i encounter some problems as you can see here https://stackoverflow.com/questions/57211271/flutter-firebaseapp-with-name-default-doesnt-exist . 
So i decided to upgrade all the frameworks (firebase_auth: ^0.11.1+12 ),  google gms and also gradle. 
I moved to the 4.3.0 of google gms and 3.3.1 gradle. 
Also i notice some changes into the tutorial to download the google-service.json file and so i add into the dependencies of my android application that:

    implementation 'com.google.firebase:firebase-core:17.0.0'
    implementation 'com.google.firebase:firebase-auth:18.1.0'

I don't know if all this changes help me to solve my previous error because now i'm facing another problem:
W/BiChannelGoogleApi(27734): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@832113d

And i don't know what can i do. Can you help me? This means that i solve the previous problem? 

Thanks.

**Comment by kroikie** [comment] 2019-10-13 18:12
@upalatucci

The issue at https://github.com/flutter/flutter/issues/37015 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment] 2019-10-22 10:17
Hi @upalatucci
are you still experiencing this issue with the latest version of Flutter?
If so can you please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-20 13:54
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-20 13:54 UTC
Labels: waiting for customer response

**Comment by basitsaleem007** [comment] 2019-11-22 12:17
in my case i just update my class path in build gradle project module to 
classpath 'com.google.gms:google-services:latest-version'

**Comment by aloksguha** [comment] 2020-03-08 15:29
Totally fed up with this issue, can anyone please provide a straight solution, I just updated everything still it's not working. same error

I/BiChannelGoogleApi( 2503): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@281dca8

**Comment by boygiandi** [comment] 2020-04-07 11:37
I have this issue today. It still work fine yesterday. 
Now, ios work but android emulator doesn't work. I didn't test android real device yet. 
I tried everything but can't make it work. Every firebase function hang and console log only this 
`I/BiChannelGoogleApi(29258): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@6deb1d3`

**Comment by iapicca** [comment] 2020-04-08 11:02
Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so it's always better to open new issues and reference related issues.

**Comment by boygiandi** [comment] 2020-04-08 12:15
I created a new emulator and there is no problem on it. Please try

**Comment by hiranlakshika** [comment] 2020-04-13 15:02
I have the same error. I tried in a real Android device as well. But I'm still getting the same error. I have updated everything. Therefore no issues with the classpath.

**Comment by hiranlakshika** [comment] 2020-04-13 15:16
I wipe the data of the emulator. Then the play support libraries were updated. Now it works fine.

**Comment by amanuel15** [comment] 2020-05-02 13:29
It is probably because of connection. So what you can do is check if your device or emulator has internet connection, then check if google play services are enabled (and if so check if they are blocked from using mobile data), if all doesn't work try it on another device or emulator

**Comment by woutervanwijk** [comment] 2020-05-22 12:31
Same here:
I/BiChannelGoogleApi( 8641): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@7ae0dbd

Connection is ok, Play Libraries updated, same error. No emails are sent when I use the sendSignInWithEmailLink function. Also using 

classpath 'com.google.gms:google-services:4.3.3'

---------------flutter doctor -v

[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.4 19E287, locale nl-NL)
    • Flutter version 1.17.1 at /Users/wouter/Library/flutter
    • Framework revision f7a6a7906b (9 days ago), 2020-05-12 18:39:00 -0700
    • Engine revision 6bc433c6b6
    • Dart version 2.8.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/wouter/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/wouter/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 8.1.0 (API 27) (emulator)

• No issues found!

**Comment by woutervanwijk** [comment] 2020-05-22 15:44
It was a configuration issue in Firebase console. I configured a custom smtp server which Amazon somehow removed (while I was only sending 1 email a week on the thing 8-/ 

Disabling the custom smtp did it for me. 

That said, the error message is reeeaallly bad, but that is mostly firebase's fault I guess

**Comment by ollydixon** [comment] 2020-06-07 12:06
For me, the emulator didn't have a solid connection to the internet but had a connection to the localhost. Very strange.

**Comment by j33tmane** [comment] 2020-06-20 10:38
i resolved this error by adding SHA 1 Key in Firebase console
![Untitled](https://user-images.githubusercontent.com/20676577/85199846-33e95600-b310-11ea-8ede-0fd393f1542c.png)

**Comment by ranahyder87** [comment] 2020-06-30 06:51
In my case, this was just internet connection problem. I was tesing on Android emulator.

**Comment by bhaskar-nair2** [comment] 2020-07-21 14:40
Running the app on two devices and this issue comes up on the one running on Android 8.1.
I saw the same version for [this](https://github.com/FirebaseExtended/flutterfire/issues/352#issuecomment-632667452) comment. Perhaps it is an issue with older version of android.

Libraries
```
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_database: 3.1.6
  firebase_auth: 0.16.0
  cloud_functions: 0.5.0
  google_sign_in: ^4.0.1+1
```

Here is the output of `flutter doctor -v` with both devices connected:
```
[✓] Flutter (Channel stable, v1.17.5, on Linux, locale en_GB.UTF-8)
    • Flutter version 1.17.5 at /home/bhaskar/flutter
    • Framework revision 8af6b2f038 (3 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/bhaskar/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /home/bhaskar/Android/Sdk
    • Java binary at: /home/bhaskar/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[!] Android Studio (version 3.5)
    • Android Studio at /home/bhaskar/android-studio
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (2 available)
    • Redmi Note 8 Pro • 6l9p5hojijjno7so • android-arm64 • Android 9 (API 28)
    • Redmi 5A         • bf4a07f77d15     • android-arm64 • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```

**Comment by bhaskar-nair2** [comment] 2020-07-21 15:34
If you wrap the signin method around a try-catch block, you will get the correct error message associated with it.

```dart
try {
      var _authRes = await _auth.signInAnonymously();
    } catch (error) {
      print(error);
    }
```
Maybe that can help correct the issue. Mine was a stupid network problem, so..
