### ISSUE TITLE
 Bad state: field does not exist within the DocumentSnapshotPlatform

### ISSUE THREAD

**Issue by Shaban-ali** [FirebaseExtended/flutterfire#6511] opened 2021-06-30 14:41 UTC
i am developing an app for selling material i used image slider using flutter 2.3.1 v  when i double tap on slider its not showing the multiple images not going to imageslide screen 

  GestureDetector(
                    onDoubleTap: () {
                      Route newRoute = MaterialPageRoute(builder: (_)=>ImageSliderScreen(
                      title: items.docs[i].get('itemModel'),
                        itemColor: items.docs[i].get('itemColor'),
                        userNumber: items.docs[i].get('userNumber'),
                        description: items.docs[i].get('description'),
                        lat: items.docs[i].get('lat'),
                        lng: items.docs[i].get('lng'),
                        address: items.docs[i].get("address"),
                        urlImage1:items.docs[i].get("urlImage1"),
                        urlImage2:items.docs[i].get("urlImage2"),
                        urlImage3:items.docs[i].get("urlImage3"),
                      ));
                      Navigator.pushReplacement(context, newRoute);
                    },

**Comment by darshankawar** [comment] 2021-07-01 08:11
@Shaban-ali 
I don't think your issue is related to flutterfire since I don't see any firebase plugin usage in the code you shared. Please ask support questions on StackOverflow.

If you think this is related to firebase plugin and is a bug in it, write in comments with all required details as requested in the new issue template, so that we can properly address this issue.

Closing for now.

**Closed by darshankawar** 2021-07-01 08:11 UTC
Labels: Needs Attention, in triage, type: bug

**Comment by solokingjec** [comment] 2021-07-01 08:42
Something has been broken lately on how firestore was handling non existing field.

before, I could do like 
String name= document.data['name']??"no name";//this way. the null was being handled gracefully..

After the introduction of the get method, the code changes to
String name= document.get('name');
if the field doesn't exist, an error is thrown and there is no way of handling the exception. 

could we have a method like tryGet("field name",'default value in case of null');
I know that this could be due to null safety but then we have huge databases with a lot of fields missing..

**Comment by darshankawar** [comment] 2021-07-01 12:22
@solokingjec 
Please open a new issue filing the template with your findings, so that we can properly address your issue.
Thanks.

**Comment by solokingjec** [comment] 2021-07-02 09:20
The problem is very easy. With the latest firestore plugin, using the DocumentSnapshots get method, there is no cleaner way of handy a situation where the field does not exist. Just try to call get method on document for a field that does not exist.

**Comment by solokingjec** [comment] 2021-07-03 10:54
> @Shaban-ali
> I don't think your issue is related to flutterfire since I don't see any firebase plugin usage in the code you shared. Please ask support questions on StackOverflow.
> 
> If you think this is related to firebase plugin and is a bug in it, write in comments with all required details as requested in the new issue template, so that we can properly address this issue.
> 
> Closing for now.

His problem is related to firestore as its obvious that the variable items is data from a QuerySnapshot.. The problem here is that some of the fields are missing in some documents and he should probably use the null operator. However with the latest plugin, the null operator will not work either.. I have been forced to revert to an older version.. Very frustrating..
