### ISSUE TITLE
🐛 [firebase_database] Crashed: com.apple.main-thread EXC_BAD_ACCESS KERN_INVALID_ADDRESS

### ISSUE THREAD

**Issue by Tom3652** [FirebaseExtended/flutterfire#7642] opened 2021-12-17 09:36 UTC
## Steps to Reproduce

Unfortunately i am unable to reproduce it for now and it happens only in ```release``` mode affecting my beta testers.

It seems to be related to ```firebase_database``` but i am not sure, simply saying this because of the last log trace.
i am using the ```firebase_database: ^9.0.3```.

I am getting this error in my ```crashlytics``` dashboard so i will attach the full trace.

<img width="1444" alt="Capture d’écran 2021-12-17 à 10 30 47" src="https://user-images.githubusercontent.com/32631467/146522236-9d2c617b-e6db-42b2-9167-fcb5229096cb.png">

**Expected results:** 

The app should not crash.

**Actual results:** 

The app is crashing.

<details>
  <summary>Logs</summary>

```
Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x15c8 objc_msgSend + 8
1  Flutter                        0x4f02a0 (Missing)
2  Flutter                        0x3c654 (Missing)
3  Flutter                        0x3bc1f4 (Missing)
4  Flutter                        0x2eb0c8 (Missing)
5  Flutter                        0x2ee694 (Missing)
6  CoreFoundation                 0xae268 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
7  CoreFoundation                 0x32c40 __CFRunLoopDoTimer + 1076
8  CoreFoundation                 0x2d43c __CFRunLoopDoTimers + 328
9  CoreFoundation                 0xbc58 __CFRunLoopRun + 1944
10 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
11 GraphicsServices               0x138c GSEventRunModal + 164
12 UIKitCore                      0x5196a8 -[UIApplication _run] + 1100
13 UIKitCore                      0x2987f4 UIApplicationMain + 2092
14 Runner                         0x7ab0 main + 7 (AppDelegate.swift:7)
15 ???                            0x106d71a24 (Missing)

com.apple.uikit.eventfetch-thread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Foundation                     0x18354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  Foundation                     0x59c28 -[NSRunLoop(NSRunLoop) runUntilDate:] + 92
7  UIKitCore                      0x4928a4 -[UIEventFetcher threadMain] + 524
8  Foundation                     0x6836c __NSThread__start__ + 808
9  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
10 libsystem_pthread.dylib        0xea0 thread_start + 8

io.flutter.1.ui
0  Flutter                        0x5f10dc (Missing)
1  Flutter                        0x50a58c (Missing)
2  Flutter                        0x5f0088 (Missing)
3  Flutter                        0x5f15c4 (Missing)
4  Flutter                        0x5f44bc (Missing)
5  Flutter                        0x5f3e3c (Missing)
6  Flutter                        0x5ee9e0 (Missing)
7  Flutter                        0x5efc48 (Missing)
8  Flutter                        0x4eb834 (Missing)
9  Flutter                        0x3b8f2c (Missing)
10 Flutter                        0x3ae0a0 (Missing)
11 Flutter                        0x2eb0c8 (Missing)
12 Flutter                        0x2ee694 (Missing)
13 CoreFoundation                 0xae268 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
14 CoreFoundation                 0x32c40 __CFRunLoopDoTimer + 1076
15 CoreFoundation                 0x2d43c __CFRunLoopDoTimers + 328
16 CoreFoundation                 0xbc58 __CFRunLoopRun + 1944
17 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
18 Flutter                        0x2ee560 (Missing)
19 Flutter                        0x2edd20 (Missing)
20 libsystem_pthread.dylib        0x19a4 _pthread_start + 148
21 libsystem_pthread.dylib        0xea0 thread_start + 8

io.flutter.1.raster
0  Flutter                        0x1b2cf4 (Missing)
1  Flutter                        0x1e1b64 (Missing)
2  Flutter                        0x43cd0 (Missing)
3  Flutter                        0x1931f8 (Missing)
4  Flutter                        0x1877e4 (Missing)
5  Flutter                        0x187b98 (Missing)
6  Flutter                        0x5566c (Missing)
7  Flutter                        0x4f9264 (Missing)
8  Flutter                        0x47e548 (Missing)
9  Flutter                        0x3b46f4 (Missing)
10 Flutter                        0x3b4c10 (Missing)
11 Flutter                        0x2ec858 (Missing)
12 Flutter                        0x3b4308 (Missing)
13 Flutter                        0x3b5c40 (Missing)
14 Flutter                        0x3b4ec4 (Missing)
15 Flutter                        0x3bd304 (Missing)
16 Flutter                        0x2eb0c8 (Missing)
17 Flutter                        0x2ee694 (Missing)
18 CoreFoundation                 0xae268 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
19 CoreFoundation                 0x32c40 __CFRunLoopDoTimer + 1076
20 CoreFoundation                 0x2d43c __CFRunLoopDoTimers + 328
21 CoreFoundation                 0xbc58 __CFRunLoopRun + 1944
22 CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
23 Flutter                        0x2ee560 (Missing)
24 Flutter                        0x2edd20 (Missing)
25 libsystem_pthread.dylib        0x19a4 _pthread_start + 148
26 libsystem_pthread.dylib        0xea0 thread_start + 8

io.flutter.1.io
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Flutter                        0x2ee560 (Missing)
6  Flutter                        0x2edd20 (Missing)
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.1
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8918 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.2
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8918 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.3
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8918 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.4
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8918 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.5
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8918 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

io.worker.6
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  Flutter                        0x2e8918 (Missing)
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

dart:io EventHandler
0  libsystem_kernel.dylib         0x2e7c kevent + 8
1  Flutter                        0x4b14cc (Missing)
2  Flutter                        0x4e04d8 (Missing)
3  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
4  libsystem_pthread.dylib        0xea0 thread_start + 8

JavaScriptCore bmalloc scavenger
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8254 _pthread_cond_wait + 1228
2  libc++.1.dylib                 0x9ddc std::__1::condition_variable::wait(std::__1::unique_lock<std::__1::mutex>&) + 28
3  JavaScriptCore                 0x11b21d4 void std::__1::condition_variable_any::wait<std::__1::unique_lock<bmalloc::Mutex> >(std::__1::unique_lock<bmalloc::Mutex>&) + 108
4  JavaScriptCore                 0x11b69a4 bmalloc::Scavenger::threadRunLoop() + 340
5  JavaScriptCore                 0x11b6544 bmalloc::Scavenger::Scavenger(std::__1::scoped_lock<bmalloc::Mutex> const&) + 14
6  JavaScriptCore                 0x11b7a00 std::__1::__thread_specific_ptr<std::__1::__thread_struct>::set_pointer(std::__1::__thread_struct*) + 46
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

com.google.firebase.crashlytics.MachExceptionServer
0  FirebaseCrashlytics            0x1f44c FIRCLSProcessRecordAllThreads + 184
1  FirebaseCrashlytics            0x1f82c FIRCLSProcessRecordAllThreads + 1176
2  FirebaseCrashlytics            0x167f0 FIRCLSHandler + 48
3  FirebaseCrashlytics            0x195b8 FIRCLSMachExceptionServer + 1248
4  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
5  libsystem_pthread.dylib        0xea0 thread_start + 8

AVAudioSession Notify Thread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  AudioSession                   0x6308 CADeprecated::GenericRunLoopThread::Entry(void*) + 164
6  AudioSession                   0xfd64 CADeprecated::CAPThread::Entry(CADeprecated::CAPThread*) + 92
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

com.apple.NSURLConnectionLoader
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  CFNetwork                      0x27a6a0 _CFURLStorageSessionCopyIdentifier + 59784
6  Foundation                     0x6836c __NSThread__start__ + 808
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

com.squareup.SocketRocket.NetworkThread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  Foundation                     0x18354 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 236
6  FirebaseDatabase               0x52f5c -[_FSRRunLoopThread main] + 252
7  Foundation                     0x6836c __NSThread__start__ + 808
8  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
9  libsystem_pthread.dylib        0xea0 thread_start + 8

com.apple.CFSocket.private
0  libsystem_kernel.dylib         0x21d0 select$DARWIN_EXTSN + 8
1  libsystem_kernel.dylib         0x21d0 __select + 8
2  CoreFoundation                 0xaa740 __CFSocketManager + 648
3  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
4  libsystem_pthread.dylib        0xea0 thread_start + 8

com.apple.CoreMotion.MotionThread
0  libsystem_kernel.dylib         0x1504 mach_msg_trap + 8
1  libsystem_kernel.dylib         0x1b9c mach_msg + 76
2  CoreFoundation                 0x7688 __CFRunLoopServiceMachPort + 372
3  CoreFoundation                 0xb97c __CFRunLoopRun + 1212
4  CoreFoundation                 0x1f3b8 CFRunLoopRunSpecific + 600
5  CoreFoundation                 0x9fa78 CFRunLoopRun + 64
6  CoreMotion                     0x13544 CLMotionActivity::isTypeInVehicle(CLMotionActivity::Type) + 21264
7  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
8  libsystem_pthread.dylib        0xea0 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1b2c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1140 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe94 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1b2c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1140 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe94 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1b2c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1140 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe94 start_wqthread + 8

DartWorker
0  Flutter                        0x50a4f4 (Missing)
1  Flutter                        0x5f0088 (Missing)
2  Flutter                        0x5f15c4 (Missing)
3  Flutter                        0x5f2104 (Missing)
4  Flutter                        0x5e851c (Missing)
5  Flutter                        0x5a1b34 (Missing)
6  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
7  libsystem_pthread.dylib        0xea0 thread_start + 8

DartWorker
0  libsystem_kernel.dylib         0x1f90 __psynch_cvwait + 8
1  libsystem_pthread.dylib        0x8280 _pthread_cond_wait + 1272
2  Flutter                        0x5a220c (Missing)
3  Flutter                        0x5e8624 (Missing)
4  Flutter                        0x5a1b34 (Missing)
5  libsystem_pthread.dylib        0x19a4 _pthread_start + 148
6  libsystem_pthread.dylib        0xea0 thread_start + 8

Thread
0  libsystem_kernel.dylib         0x1b2c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1140 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe94 start_wqthread + 8

FirebaseWorker
0  libobjc.A.dylib                0x1878 objc_msgSendSuper2 + 24
1  FirebaseDatabase               0x2d1d0 -[FLLRBValueNode initWithKey:withValue:withColor:withLeft:withRight:] + 72
2  FirebaseDatabase               0x2d4a4 -[FLLRBValueNode copyWith:withValue:withColor:withLeft:withRight:] + 380
3  FirebaseDatabase               0x2e590 -[FLLRBValueNode colorFlip] + 404
4  FirebaseDatabase               0x2df04 -[FLLRBValueNode fixUp] + 472
5  FirebaseDatabase               0x2eb98 -[FLLRBValueNode remove:withComparator:] + 1332
6  FirebaseDatabase               0x2e91c -[FLLRBValueNode remove:withComparator:] + 696
7  FirebaseDatabase               0x2e91c -[FLLRBValueNode remove:withComparator:] + 696
8  FirebaseDatabase               0x2e91c -[FLLRBValueNode remove:withComparator:] + 696
9  FirebaseDatabase               0x2eb38 -[FLLRBValueNode remove:withComparator:] + 1236
10 FirebaseDatabase               0x2eb38 -[FLLRBValueNode remove:withComparator:] + 1236
11 FirebaseDatabase               0x2e91c -[FLLRBValueNode remove:withComparator:] + 696
12 FirebaseDatabase               0x5e534 -[FTreeSortedDictionary removeKey:] + 172
13 FirebaseDatabase               0xb99c -[FChildrenNode updateImmediateChild:withNewChild:] + 192
14 FirebaseDatabase               0x18e00 -[FIndexedNode updateChild:withNewChild:] + 116
15 FirebaseDatabase               0x2c930 __57-[FLimitedFilter updateFullNode:withNewNode:accumulator:]_block_invoke + 552
16 FirebaseDatabase               0x19950 __52-[FIndexedNode enumerateChildrenReverse:usingBlock:]_block_invoke + 128
17 FirebaseDatabase               0x5edf4 __67-[FTreeSortedDictionary enumerateKeysAndObjectsReverse:usingBlock:]_block_invoke + 40
18 FirebaseDatabase               0x2d758 -[FLLRBValueNode reverseTraversal:] + 176
19 FirebaseDatabase               0x2d700 -[FLLRBValueNode reverseTraversal:] + 88
20 FirebaseDatabase               0x2d700 -[FLLRBValueNode reverseTraversal:] + 88
21 FirebaseDatabase               0x2d700 -[FLLRBValueNode reverseTraversal:] + 88
22 FirebaseDatabase               0x5ece8 -[FTreeSortedDictionary enumerateKeysAndObjectsReverse:usingBlock:] + 172
23 FirebaseDatabase               0x14c68 -[FImmutableSortedSet enumerateObjectsReverse:usingBlock:] + 156
24 FirebaseDatabase               0x19868 -[FIndexedNode enumerateChildrenReverse:usingBlock:] + 248
25 FirebaseDatabase               0x2c5e0 -[FLimitedFilter updateFullNode:withNewNode:accumulator:] + 892
26 FirebaseDatabase               0x67ba0 -[FViewProcessor generateEventCacheAfterServerEvent:path:writesCache:source:accumulator:] + 1388
27 FirebaseDatabase               0x68390 -[FViewProcessor applyServerOverwriteTo:changePath:snap:writesCache:completeCache:filterServerNode:accumulator:] + 1468
28 FirebaseDatabase               0x67218 -[FViewProcessor applyOperationOn:operation:writesCache:completeCache:] + 1336
29 FirebaseDatabase               0x65c74 -[FView applyOperation:writesCache:serverCache:] + 252
30 FirebaseDatabase               0x53414 -[FSyncPoint applyOperation:toView:writesCache:serverCache:] + 80
31 FirebaseDatabase               0x53920 __53-[FSyncPoint applyOperation:writesCache:serverCache:]_block_invoke + 44
32 CoreFoundation                 0x40664 __NSDICTIONARY_IS_CALLING_OUT_TO_A_BLOCK__ + 24
33 CoreFoundation                 0x5877c -[__NSDictionaryM enumerateKeysAndObjectsWithOptions:usingBlock:] + 208
34 FirebaseDatabase               0x53870 -[FSyncPoint applyOperation:writesCache:serverCache:] + 428
35 FirebaseDatabase               0x59e70 -[FSyncTree applyOperationDescendantsHelper:syncPointTree:serverCache:writesCache:] + 452
36 FirebaseDatabase               0x599fc -[FSyncTree applyOperationHelper:syncPointTree:serverCache:writesCache:] + 188
37 FirebaseDatabase               0x59bb0 -[FSyncTree applyOperationHelper:syncPointTree:serverCache:writesCache:] + 624
38 FirebaseDatabase               0x59bb0 -[FSyncTree applyOperationHelper:syncPointTree:serverCache:writesCache:] + 624
39 FirebaseDatabase               0x598f4 -[FSyncTree applyOperationToSyncPoints:] + 192
40 FirebaseDatabase               0x55b38 -[FSyncTree applyServerOverwriteAtPath:newData:] + 284
41 FirebaseDatabase               0x44568 -[FRepo onDataUpdate:forPath:message:isMerge:tagId:] + 656
42 FirebaseDatabase               0x39588 -[FPersistentConnection onDataPushWithAction:andBody:] + 556
43 FirebaseDatabase               0x35de4 -[FPersistentConnection onDataMessage:withMessage:] + 640
44 FirebaseDatabase               0x10c88 -[FConnection onDataMessage:] + 132
45 FirebaseDatabase               0x10ba4 -[FConnection onMessage:withMessage:] + 300
46 FirebaseDatabase               0x6b838 -[FWebSocketConnection appendFrame:] + 372
47 FirebaseDatabase               0x6b8c8 -[FWebSocketConnection handleIncomingFrame:] + 92
48 FirebaseDatabase               0x4fdd8 __31-[FSRWebSocket _handleMessage:]_block_invoke + 132
49 libdispatch.dylib              0x2914 _dispatch_call_block_and_release + 32
50 libdispatch.dylib              0x4660 _dispatch_client_callout + 20
51 libdispatch.dylib              0xbde4 _dispatch_lane_serial_drain + 672
52 libdispatch.dylib              0xc958 _dispatch_lane_invoke + 392
53 libdispatch.dylib              0x171a8 _dispatch_workloop_worker_thread + 656
54 libsystem_pthread.dylib        0x10f4 _pthread_wqthread + 288
55 libsystem_pthread.dylib        0xe94 start_wqthread + 8

Thread
0  libsystem_kernel.dylib         0x1b2c __workq_kernreturn + 8
1  libsystem_pthread.dylib        0x1140 _pthread_wqthread + 364
2  libsystem_pthread.dylib        0xe94 start_wqthread + 8
```

```
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.1 21C52 darwin-x64, locale fr-FR)
    • Flutter version 2.8.0 at /Users/foxtom/Desktop/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cf44000065 (8 days ago), 2021-12-08 14:06:50 -0800
    • Engine revision 40a99c5951
    • Dart version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/foxtom/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.1)
    • VS Code at /Users/foxtom/Desktop/Visual Studio Code.app/Contents
    • Flutter extension version 3.29.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.1 21C52 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 96.0.4664.110

• No issues found!

```

</details>

**Comment by darshankawar** [comment] 2021-12-17 13:10
@Tom3652 
Can't really be sure from the logs though as what could be causing this crash. Is there a way for you to provide symbolicated crash log ?, that will hopefully help.

**Comment by Tom3652** [comment] 2021-12-17 13:35
I saw that there is a Flutter bot that can help doing so, but it is not available here right ? 

<img width="918" alt="Capture d’écran 2021-12-17 à 14 33 29" src="https://user-images.githubusercontent.com/32631467/146552281-ecbf6ac0-6417-4873-94cd-d6b83f67893a.png">
 
I don't know how to symbolize crash logs, i saw few things on SOF but i don't really understand what should I do sorry...

**Comment by darshankawar** [comment] 2021-12-20 12:06
> but it is not available here right ?

That's right. The bot is only available for flutter/flutter repo. 

Leaving it open and labeling for further insights, because looking at the logs, I am not sure if this is a database plugin issue or not.


/cc @russellwheatley

**Comment by Tom3652** [comment] 2021-12-20 13:08
Thanks for the investigation.

I am not sure either that this is due to the `firebase_database` plugin.

I will update here if i find something else.

**Comment by RomainFranceschini** [comment] 2021-12-20 18:28
Hi, I'm facing a similar issue on iOS. 

I'm not sure if the issue is related to the Flutter engine or `firebase_database` since the issue started to appear when we rolled out our app from:

- flutter 2.5.3
- firebase_core 1.10.0
- firebase_database 8.1.0

to:

- flutter 2.8.{0,1} and 
- firebase_core 1.10.5
- firebase_database 9.0.2

Below is a public link to a sentry issue with symbolication: https://sentry.io/share/issue/715ae351e141453da7731bb01276b1f9/.

**Comment by Tom3652** [comment] 2021-12-20 18:49
Thanks for sharing.

Same for me actually, after upgrading `flutter` and all flutterfire plugins to their latest version as you mentioned.

**Comment by russellwheatley** [comment] 2021-12-22 09:58
@Tom3652 Here is the wiki on symbolising iOS release stack traces [here](https://github.com/flutter/flutter/wiki/Crashes) if you're interested. Would be useful in figuring out exactly what is happening. Just from the error message though, it looks like something there is an object being used that no longer exists perhaps.

**Comment by ajdll5dev** [comment] 2021-12-25 02:29
I have same issue. but im not using firebase_database. 
Im upgrade 2.8.1 and change pubspec.yaml like blew.

```

firebase_core: 1.10.0 -> 1.10.5
firebase_messaging: 11.1.0 -> 11.2.3
firebase_analytics: 8.3.4 -> 9.0.3
firebase_crashlytics: 2.3.0 -> 2.4.3
google_mobile_ads: 1.0.1 -> 0.13.6
flutter_local_notifications: 9.1.5 -> 9.1.4
get: 4.6.1 -> 4.3.8
dio: 4.0.4 -> 4.0.3
cached_network_image: 3.2.0 -> 3.1.0+1
reorderables: 0.4.2 -> 0.4.1

```

any idea?

**Comment by CubitSpeed** [comment] 2021-12-25 03:36
> I have same issue. but im not using firebase_database. Im upgrade 2.8.1 and change pubspec.yaml like blew.
> 
> ```
> 
> firebase_core: 1.10.0 -> 1.10.5
> firebase_messaging: 11.1.0 -> 11.2.3
> firebase_analytics: 8.3.4 -> 9.0.3
> firebase_crashlytics: 2.3.0 -> 2.4.3
> google_mobile_ads: 1.0.1 -> 0.13.6
> flutter_local_notifications: 9.1.5 -> 9.1.4
> get: 4.6.1 -> 4.3.8
> dio: 4.0.4 -> 4.0.3
> cached_network_image: 3.2.0 -> 3.1.0+1
> reorderables: 0.4.2 -> 0.4.1
> ```
> 
> ![image](https://user-images.githubusercontent.com/92976718/147376185-031caf8d-4daa-4d6e-8a66-cb028a5fddc1.png)
> 
> any idea?

From your screenshot, this does not look like the same type of crash. What would make you think it's similar to these crashes?

If you have a reason, please share. Otherwise you will be better served opening a new issues elsewhere.

**Comment by ajdll5dev** [comment] 2021-12-25 04:07
@CubitSpeed 
blew is coreFoundation's detail screen.

![image](https://user-images.githubusercontent.com/92976718/147377137-958e8129-de22-4bab-b318-7362e60c1649.png)

**Comment by Tom3652** [comment] 2021-12-25 11:46
It's the same error but not regarding the same thing. 
The crash title in my case is : 

```
libobjc.A.dylib
objc_msgSend
```

You should open a new issue for your use case but thanks for sharing.

**Comment by CubitSpeed** [comment] 2021-12-27 20:17
Update: Upon downgrading to `8.1.0`, I no longer am seeing this crash. I've collected several days worth of data.

This heavily implies Firebase Database, as already suspected, is the core reason for these crashes.

Can we please add the "severe: regression" label to this issue?

**Comment by deepak786** [comment] 2022-01-05 17:56
has the same issue.

```
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000100000000

Crashed: com.apple.main-thread
0  libobjc.A.dylib                0x15c8 objc_msgSend + 8
1  Flutter                        0x4f02a0 (Missing)
2  Flutter                        0x3c654 (Missing)
3  Flutter                        0x3bc1f4 (Missing)
4  Flutter                        0x2eb0c8 (Missing)
5  Flutter                        0x2ee694 (Missing)
6  CoreFoundation                 0xae278 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
7  CoreFoundation                 0x32c50 __CFRunLoopDoTimer + 1076
8  CoreFoundation                 0x2d44c __CFRunLoopDoTimers + 328
9  CoreFoundation                 0xbc68 __CFRunLoopRun + 1944
10 CoreFoundation                 0x1f3c8 CFRunLoopRunSpecific + 600
11 GraphicsServices               0x138c GSEventRunModal + 164
12 UIKitCore                      0x51b060 -[UIApplication _run] + 1100
13 UIKitCore                      0x298b8c UIApplicationMain + 2124
14 Agenda BOA                     0x8154 main + 5 (AppDelegate.swift:5)
15 ???                            0x1043e9a24 (Missing)
```

**Comment by deepak786** [comment] 2022-02-04 12:35
It seems that flutter's latest stable `2.10.0` or master will solve this issue.

**Comment by russellwheatley** [comment] 2022-02-08 16:02
@deepak786, thanks for the report. 

Hey @Tom3652, could you let us know if the latest release (including https://github.com/FirebaseExtended/flutterfire/pull/7859), and the latest Flutter stable version resolves your issue? Thanks.

**Comment by russellwheatley** [comment] 2022-02-15 10:18
Hey @Tom3652, as ever, thank you for the update. I'll close this out for now if it is a Flutter issue. However, I'm happy to reopen if there is also something to be resolved on Flutterfire.

**Closed by russellwheatley** 2022-02-15 10:18 UTC
Labels: type: bug, plugin: database, resolution: needs-repro, type: crash
