### ISSUE TITLE
bnjr j'ai rencontrer le problème:

### ISSUE THREAD

**Issue by pascalsarr** [FirebaseExtended/flutterfire#6606] opened 2021-07-13 23:18 UTC
The build failed likely due to AndroidX incompatibilities in a plugin. The tool is about totry using Jetifier to solve the incompatibility.
Building plugin cloud_firestore...
Exception: The plugin cloud_firestore could not be built due to the issue above.
Running Gradle task 'assembleAarRelease'...

**Comment by markusaksli-nc** [comment] 2021-07-14 11:34
Hi @pascalsarr 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.
Thank you.

**Closed by markusaksli-nc** 2021-07-14 11:34 UTC
Labels: in triage

**Comment by pascalsarr** [comment] 2021-07-14 14:46
![Captkdxcure](https://user-images.githubusercontent.com/39752128/125642408-7533b22f-df34-4151-8b1f-200ef77fb5e2.JPG)

**Comment by markusaksli-nc** [comment] 2021-07-15 08:08
Not sure what the issue is exactly without the full logs. As I mentioned you can open a new issue and fill out the template. Also please just copy/paste the logs instead of providing screenshots.
