### ISSUE TITLE
[firebase_messaging] MissingPluginException when building for macOS

### ISSUE THREAD

**Issue by NickM-27** [FirebaseExtended/flutterfire#1608] opened 2019-12-11 21:59 UTC
**Describe the bug**
When building for macOS and using the firebase messaging plugin the app gives a MissingPluginException error

**To Reproduce**
1. Create a macOS project
2. Add and use firebase messaging plugin

**Expected behavior**
No crash

**Additional context**
Flutter Doctor:

[✓] Flutter (Channel dev, v1.13.0, on Mac OS X 10.15.1 19B88, locale en-US)
    • Flutter version 1.13.0 at /Users/nickmowen/Library/Android/flutter
    • Framework revision 09126abb22 (8 days ago), 2019-12-03 17:43:00 -0800
    • Engine revision 6179380243
    • Dart version 2.7.0 (build 2.7.0-dev.2.1 a4d799c402)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nickmowen/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio 3.6 Preview.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio
    • Android Studio at /Applications/Android Studio 3.6 Preview.app/Contents
    • Flutter plugin version 42.0.2
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] Connected device (1 available)
    • macOS • macOS • darwin-x64 • Mac OS X 10.15.1 19B88

**Comment by iapicca** [comment] 2019-12-12 14:18
Hi @NickM-27 
can you please provide your `flutter run --verbose`?
Thank you

possible duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1606

**Comment by Ahmadre** [comment] 2019-12-13 23:11
@NickM-27 which version did you use? Maybe upgrade you firebase_messaging version, because I had that with another firebase feature package and after the update it was solved.

**Comment by NickM-27** [comment] 2019-12-13 23:46
@Ahmadre Definitely not, I have tried 6.0.3, 6.0.7, and the new 6.0.8. I have seen similar components with changelogs that include "support for macos" and I am guessing that this one just does not have it yet.

**Comment by paulosigales** [comment] 2020-02-19 12:51
@NickM-27 Hey, please edit your comment with debug log because it's linking a lot of issues.

**Comment by Salakar** [comment] 2020-08-25 14:30
Closing this issue as we're tracking macOS support on #1653 instead.

**Closed by Salakar** 2020-08-25 14:30 UTC
Labels: impact: customer, platform: macos, plugin: messaging, type: bug
