### ISSUE TITLE
🐛 [Firebase Messaging] Flutter Firebase Messaging error after upgrading all firebase plugin in ios xcode

### ISSUE THREAD

**Issue by abu0435** [FirebaseExtended/flutterfire#5200] opened 2021-03-03 15:17 UTC
Recently i have upgrade the all firebase plugin. Can't build for iOS app.

Error output from Xcode build:
↳
** BUILD FAILED **

Xcode's output:
↳
While building module 'FirebaseMessaging' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Headers/Public/Firebase/Firebase.h:78:
In file included from :1:
In file included from /Users/Studio Projects/S2B_v3.3/ios/Pods/Target Support Files/FirebaseMessaging/FirebaseMessaging-umbrella.h:13:
In file included from /Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FirebaseMessaging/FirebaseMessaging.h:18:
/Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessagingExtensionHelper.h:34:38: warning: 'UNMutableNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
- (void)populateNotificationContent:(UNMutableNotificationContent *)content
^
In module 'UserNotifications' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessagingExtensionHelper.h:19:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationContent.h:63:12: note: 'UNMutableNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
@interface UNMutableNotificationContent : UNNotificationContent
^
While building module 'FirebaseMessaging' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Headers/Public/Firebase/Firebase.h:78:
In file included from :1:
In file included from /Users/Studio Projects/S2B_v3.3/ios/Pods/Target Support Files/FirebaseMessaging/FirebaseMessaging-umbrella.h:13:
In file included from /Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FirebaseMessaging/FirebaseMessaging.h:18:
/Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessagingExtensionHelper.h:34:1: note: annotate 'populateNotificationContent:withContentHandler:' with an availability attribute to silence this warning
- (void)populateNotificationContent:(UNMutableNotificationContent *)content
^
/Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessagingExtensionHelper.h:35:47: warning: 'UNNotificationContent' is only available on iOS 10.0 or newer [-Wunguarded-availability]
withContentHandler:(void (^)(UNNotificationContent *_Nonnull))contentHandler;
^
In module 'UserNotifications' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessagingExtensionHelper.h:19:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UserNotifications.framework/Headers/UNNotificationContent.h:16:12: note: 'UNNotificationContent' has been marked as being introduced in iOS 10.0 here, but the deployment target is iOS 8.0.0
@interface UNNotificationContent : NSObject <NSCopying, NSMutableCopying, NSSecureCoding>
^
While building module 'FirebaseMessaging' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Headers/Public/Firebase/Firebase.h:78:
In file included from :1:
In file included from /Users/Studio Projects/S2B_v3.3/ios/Pods/Target Support Files/FirebaseMessaging/FirebaseMessaging-umbrella.h:13:
In file included from /Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FirebaseMessaging/FirebaseMessaging.h:18:
/Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseMessaging/FirebaseMessaging/Sources/Public/FirebaseMessaging/FIRMessagingExtensionHelper.h:34:1: note: annotate 'populateNotificationContent:withContentHandler:' with an availability attribute to silence this warning
- (void)populateNotificationContent:(UNMutableNotificationContent *)content
^
2 warnings generated.
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:190:43: error: expected a type
- (void)applicationReceivedRemoteMessage:(FIRMessagingRemoteMessage *)remoteMessage {
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:285:53: error: nullability specifier 'nonnull' conflicts with existing specifier 'nullable'
didReceiveRegistrationToken:(nonnull NSString *)fcmToken {
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:290:24: error: expected a type
didReceiveMessage:(FIRMessagingRemoteMessage *)remoteMessage {
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:136:30: error: property 'shouldEstablishDirectChannel' not found on object of type 'FIRMessaging *'
[FIRMessaging messaging].shouldEstablishDirectChannel = true;
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:155:21: warning: 'FIRInstanceID' is deprecated: FIRInstanceID is deprecated, please use FIRInstallations for installation identifier handling and use FIRMessaging for FCM registration token handling. [-Wdeprecated-declarations]
[[FIRInstanceID instanceID]
^
In module 'FirebaseInstanceID' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Headers/Public/Firebase/Firebase.h:74:
/Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseInstanceID/Firebase/InstanceID/Public/FIRInstanceID.h:190:1: note: 'FIRInstanceID' has been explicitly marked deprecated here
__deprecated_msg("FIRInstanceID is deprecated, please use FIRInstallations for installation "
^
In module 'UIKit' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sys/cdefs.h:191:48: note: expanded from macro '__deprecated_msg'
#define __deprecated_msg(_msg) attribute((deprecated(_msg)))
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:156:33: warning: 'FIRInstanceIDResult' is deprecated: FIRInstanceIDResult is deprecated, please use FIRInstallations for app instance identifier handling and use FIRMessaging for FCM registration token handling. [-Wdeprecated-declarations]
instanceIDWithHandler:^(FIRInstanceIDResult *_Nullable instanceIDResult,
^
In module 'FirebaseInstanceID' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Headers/Public/Firebase/Firebase.h:74:
/Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseInstanceID/Firebase/InstanceID/Public/FIRInstanceID.h:153:1: note: 'FIRInstanceIDResult' has been explicitly marked deprecated here
__deprecated_msg("FIRInstanceIDResult is deprecated, please use FIRInstallations "
^
In module 'UIKit' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sys/cdefs.h:191:48: note: expanded from macro '__deprecated_msg'
#define __deprecated_msg(_msg) attribute((deprecated(_msg)))
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:156:9: warning: 'instanceIDWithHandler:' is deprecated: Use Installations.installationID(completion:) to get the app instance identifier instead. Use Messaging.token(completion:) to get FCM registration token instead. [-Wdeprecated-declarations]
instanceIDWithHandler:^(FIRInstanceIDResult *_Nullable instanceIDResult,
^
In module 'FirebaseInstanceID' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Headers/Public/Firebase/Firebase.h:74:
/Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseInstanceID/Firebase/InstanceID/Public/FIRInstanceID.h:215:5: note: 'instanceIDWithHandler:' has been explicitly marked deprecated here
__deprecated_msg("Use Installations.installationID(completion:) to get the app instance "
^
In module 'UIKit' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sys/cdefs.h:191:48: note: expanded from macro '__deprecated_msg'
#define __deprecated_msg(_msg) attribute((deprecated(_msg)))
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:166:21: warning: 'FIRInstanceID' is deprecated: FIRInstanceID is deprecated, please use FIRInstallations for installation identifier handling and use FIRMessaging for FCM registration token handling. [-Wdeprecated-declarations]
[[FIRInstanceID instanceID] deleteIDWithHandler:^void(NSError *_Nullable error) {
^
In module 'FirebaseInstanceID' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Headers/Public/Firebase/Firebase.h:74:
/Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseInstanceID/Firebase/InstanceID/Public/FIRInstanceID.h:190:1: note: 'FIRInstanceID' has been explicitly marked deprecated here
__deprecated_msg("FIRInstanceID is deprecated, please use FIRInstallations for installation "
^
In module 'UIKit' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sys/cdefs.h:191:48: note: expanded from macro '__deprecated_msg'
#define __deprecated_msg(_msg) attribute((deprecated(_msg)))
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:166:33: warning: 'deleteIDWithHandler:' is deprecated: Use Installations.delete(completion:) instead. Also check Messaging.deleteData(completion:)if you want to delete FCM registration token. [-Wdeprecated-declarations]
[[FIRInstanceID instanceID] deleteIDWithHandler:^void(NSError *_Nullable error) {
^
In module 'FirebaseInstanceID' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Headers/Public/Firebase/Firebase.h:74:
/Users/Studio Projects/S2B_v3.3/ios/Pods/FirebaseInstanceID/Firebase/InstanceID/Public/FIRInstanceID.h:321:33: note: 'deleteIDWithHandler:' has been explicitly marked deprecated here
__deprecated_msg("Use Installations.delete(completion:) instead. "
^
In module 'UIKit' imported from /Users/Studio Projects/S2B_v3.3/ios/Pods/Target Support Files/firebase_messaging/firebase_messaging-prefix.pch:2:
In module 'Foundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIKit.h:8:
In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In module 'Darwin' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.2.sdk/usr/include/sys/cdefs.h:191:48: note: expanded from macro '__deprecated_msg'
#define __deprecated_msg(_msg) attribute((deprecated(_msg)))
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:191:52: error: property 'appData' not found on object of type '__strong id'
[self didReceiveRemoteNotification:remoteMessage.appData];
^
/Users/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:291:63: error: property 'appData' not found on object of type '__strong id'
[_channel invokeMethod:@"onMessage" arguments:remoteMessage.appData];
^
7 warnings and 6 errors generated.
note: Using new build system
note: Planning build
note: Constructing build description

Could not build the precompiled application for the device.

I have tried delete podfile and podfile.lock
flutter pub get
pod install

Relevant packages:

auto_size_text: ^2.1.0
contacts_service: ^0.4.6
cupertino_icons: ^1.0.0
date_range_picker: ^1.0.6
datetime_picker_formfield: ^1.0.0
#device_info: ^1.0.0
#devicelocale: ^0.3.0 #^0.3.3
dio: ^3.0.10
dropdown_search: ^0.4.6
dropdownfield: ^1.0.3
feature_discovery: ^0.12.1
firebase_messaging: ^7.0.3
firebase_analytics: ^6.3.0
firebase_auth_web: ^0.3.3
firebase_auth: ^0.20.1
firebase_core_platform_interface: ^3.0.1
firebase_core: ^0.7.0
firebase_auth_oauth: ^0.2.4
firebase_auth_oauth_web: ^0.2.1
firebase_storage: ^7.0.0
flutter_html: ^1.0.2
flutter_masked_text: ^0.8.0
flutter_money_formatter: ^0.8.3
flutter_multiselect: ^0.5.1
flutter_speed_dial: ^1.2.5
flutter_webview_plugin: ^0.3.11
#fluttertoast: ^7.1.1
font_awesome_flutter: ^8.10.0
global_configuration: ^1.6.0
google_sign_in: ^4.5.6
http: ^0.12.2
image_picker: ^0.6.7+14
in_app_purchase: ^0.3.5+1
intl: ^0.15.8
intro_slider: ^2.3.3
keyboard_actions: ^3.3.1+1
modal_bottom_sheet: ^1.0.0+1
package_info: ^0.4.3+2
path_provider: ^1.6.24
permission_handler: ^5.0.1+2
progress_dialog: ^1.2.4
random_string: ^2.1.0
shared_preferences: ^0.5.12+4
shimmer: ^1.1.2
splashscreen: ^1.3.5
toast: ^0.1.5
url_launcher: ^5.7.10
wifi: ^0.1.5
country_codes: ^1.0.3
#file_picker: ^2.1.0
flutter_document_picker: ^4.0.0
reorderables: ^0.3.2
flutter_calendar_carousel: ^1.5.1
#charts_flutter: ^0.9.0
fl_chart: ^0.12.0
appsflyer_sdk: ^6.2.0 #6.0.5+3
#charts_common: ^0.9.0
charts_flutter: ^0.9.0
printing: ^3.7.1
flutter_facebook_auth: ^1.0.2+2
flutter_signature_pad: ^2.0.2
flutter_cached_pdfview: ^0.3.3
month_picker_dialog: ^0.3.3
pub_semver: ^1.4.4
store_launcher: ^1.0.1

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Log</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-KW)
    • Flutter version 1.22.4 at /Users/mazenammar/TahakkomFiles/flutter
    • Framework revision 1aafb3a8b9 (4 months ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/mazenammar/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • Abdul’s iPhone (mobile) • 7064e6f0afa75bd4c202d206736b49200b20eb4f • ios • iOS 13.5.1

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.4

dependencies:
- appsflyer_sdk 6.2.1+5 [flutter]
- auto_size_text 2.1.0 [flutter]
- charts_flutter 0.9.0 [charts_common collection flutter intl logging meta]
- contacts_service 0.4.6 [flutter collection quiver]
- country_codes 1.0.3 [flutter]
- cupertino_icons 1.0.0
- date_range_picker 1.0.6 [flutter]
- datetime_picker_formfield 1.0.0 [flutter intl]
- dio 3.0.10 [http_parser path]
- dropdown_search 0.4.9 [flutter]
- dropdownfield 1.0.3 [flutter]
- feature_discovery 0.12.1 [flutter provider shared_preferences]
- firebase_analytics 6.3.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.20.1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_auth_oauth 0.2.4 [flutter firebase_auth firebase_auth_oauth_platform_interface firebase_auth_oauth_web firebase_core]
- firebase_auth_oauth_web 0.2.2 [flutter flutter_web_plugins firebase firebase_auth firebase_auth_oauth_platform_interface firebase_core js]
- firebase_auth_web 0.3.3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- firebase_storage 7.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- fl_chart 0.12.3 [flutter path_drawing equatable pedantic]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_cached_pdfview 0.3.5 [flutter flutter_pdfview flutter_cache_manager path_provider path]
- flutter_calendar_carousel 1.5.3 [intl flutter]
- flutter_document_picker 4.0.1 [flutter]
- flutter_facebook_auth 1.0.2+2 [flutter]
- flutter_html 1.2.0 [html csslib css_colors flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter]
- flutter_masked_text 0.8.0 [flutter]
- flutter_money_formatter 0.8.3 [flutter intl]
- flutter_multiselect 0.5.1 [flutter]
- flutter_signature_pad 2.0.3 [flutter]
- flutter_speed_dial 1.2.5 [flutter]
- flutter_webview_plugin 0.3.11 [flutter]
- font_awesome_flutter 8.11.0 [flutter]
- global_configuration 1.6.0 [flutter http]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- in_app_purchase 0.3.5+1 [async collection flutter json_annotation meta]
- intl 0.16.1 [path]
- intro_slider 2.3.4 [flutter]
- keyboard_actions 3.3.1+1 [flutter]
- modal_bottom_sheet 1.0.0+1 [flutter]
- month_picker_dialog 0.3.3 [flutter flutter_localizations intl flutter_cupertino_localizations rxdart]
- package_info 0.4.3+4 [flutter]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 5.0.1+2 [flutter meta permission_handler_platform_interface]
- printing 3.7.2 [flutter flutter_web_plugins image js meta pdf plugin_platform_interface]
- progress_dialog 1.2.4 [flutter]
- pub_semver 1.4.4 [collection]
- random_string 2.1.0
- reorderables 0.3.2 [flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 1.1.2 [flutter]
- splashscreen 1.3.5 [flutter]
- store_launcher 1.0.1 [flutter]
- toast 0.1.5 [flutter]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- wifi 0.1.5 [flutter]

dev dependencies:
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

dependency overrides:
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- intl 0.16.1 [path]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- barcode 1.17.1 [meta qr]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- charts_common 0.9.0 [collection intl logging meta vector_math]
- chewie 0.12.2 [cupertino_icons flutter video_player wakelock]
- chewie_audio 1.1.2 [video_player cupertino_icons flutter]
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- css_colors 1.0.2 [flutter]
- csslib 0.16.2 [source_span]
- equatable 1.2.6 [collection meta]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_oauth_platform_interface 0.2.2 [flutter firebase_auth firebase_core]
- firebase_auth_platform_interface 3.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_storage_platform_interface 1.0.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+3 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_cache_manager 2.1.1 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_cupertino_localizations 1.0.1 [flutter flutter_localizations]
- flutter_layout_grid 0.10.5 [collection flutter meta quiver]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_pdfview 1.0.4 [flutter]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.14.0+4 [csslib source_span]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_platform_interface 1.1.6 [flutter meta http plugin_platform_interface]
- import_js_library 1.0.2 [flutter html flutter_web_plugins js]
- js 0.6.2
- json_annotation 3.1.1
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- nested 0.0.4 [flutter]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pdf 1.13.0 [archive barcode crypto image meta path_parsing vector_math xml]
- pedantic 1.9.2 [meta]
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- provider 4.3.3 [collection flutter nested]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- rxdart 0.24.1
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.2+3 [flutter sqflite_common path]
- sqflite_common 1.0.3+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- video_player 1.0.1 [meta video_player_platform_interface video_player_web flutter]
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.2.1+1 [flutter meta wakelock_platform_interface wakelock_web]
- wakelock_platform_interface 0.1.0+1 [flutter meta]
- wakelock_web 0.1.0+3 [flutter flutter_web_plugins import_js_library js wakelock_platform_interface]
- webview_flutter 1.0.7 [flutter]
- win32 1.7.4+1 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-03-04 13:39
Hi @abu0435 
You are using heavily outdated versions of all the packages. I'm closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/5198
Once that gets solved please let me know if you are facing this issue on all the latest versions and I will re-open this.
Thank you

**Closed by markusaksli-nc** 2021-03-04 13:39 UTC
Labels: Needs Attention, type: bug
