### ISSUE TITLE
[firebase_admob] Keyboard won't show up after tapping on ads

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#522] opened 2019-10-13 18:35 UTC
the complete example : https://github.com/Maherr/flutter_firebase_admob_bug

Keyboard won't show up after tapping on ad and returning back to the app but works fine before that. also, if the app has multiple screens it with multiple text fields they wont work either. the only way to make the keyboard show up again when pressing a text field is to force close the app and launch again.

**Comment by kroikie** [comment] 2019-10-13 18:35
@Maherr

The issue at https://github.com/flutter/flutter/issues/26064 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment] 2019-10-22 13:49
Hi @Maherr
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by Maherr** [comment] 2019-10-22 20:23
> 
> 
> Hi @Maherr
> If you are still experiencing this issue
> with the latest version of Flutter and FlutterFire plugin
> can you please provide your updated `flutter doctor -v`
> and your and your `flutter run --verbose`/`flutter build --verbose` ?
> Also, to better address the issue, would be helpful
> if you could post a self contained app on github
> or the steps to reproduce it.
> Thank you

The issue seems to be fixed, i just tested it with the last version of flutter

**Comment by iapicca** [comment] 2019-10-24 12:19
Hi @Maherr 
given your last message I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by iapicca** 2019-10-24 12:19 UTC
Labels: waiting for customer response
