### ISSUE TITLE
[cloud_firestore] How to force write to cloud instead of local queue

### ISSUE THREAD

**Issue by prokyhb** [FirebaseExtended/flutterfire#2249] opened 2020-03-27 17:41 UTC
Hi there,

I'm bit confused and I need to admit, I need help. I can't find any solution how to make sure, that add/update/set tasks has been succesfully writen to cloud firebase. Not local queue, cloud firebase.

`var firestore = Firestore.instance;
 firestore.settings(persistenceEnabled: false);
try {
await firestore.document(path).updateData(data);
} catch (e) {
        print(e);
      }
`

This goes wihout any issues when triggered offline, when I go back online, update is actually performed and exception fired, if there is no such document. So it uses internal queue. I need to get rid of that behavior.

I need to let user know right away, that the task failed, that the user is offline, or document does not exists, or any other reason why write failed. The application can not lay on internal queue.

I've also tried run the query in transaction, because transactions needs to run online. But I have way more problems here. I can't catch an exception and the application crashes. I do use transactions (much more complex) and they works. When I'm online.

Let's see:

```
final DocumentReference documentReference = firestore.document(path);
    await firestore.runTransaction((Transaction tx) async {
      try {
        DocumentSnapshot activitySnapshot = await tx.get(documentReference);
        if (activitySnapshot.exists) {
          await tx.update(documentReference, data);
        } else {
          await tx.set(documentReference, data);
        }
      } catch (e) {
        print(e);
      }
    });```

This code leads to exceptions when triggered offline, IDK, about 5 ones, in the end the app crashes. I've tried catch the exception, it does not catch the first one, when I send the request one more time, it fires all the exceptions (see bellow), catch catches them one by one, but the last one actually  leads to crash of the app.

So, that's it, I simply need to make sure, the app, at least critical writes, are performed at the time users presses the "save button" and if something goes wrong, I need to tell them. No offline support at all.

Is there any easy way how to do that? I can check the connection itself before sending updates, but I think it's not good enough. I'd like to be 100% sure, it's in there, in the cloud, written as I wanted to :-).

Thanks a lot.

Here is what I get:

```D/EGL_emulation(10861): eglMakeCurrent: 0xdb71aa80: ver 2 0 (tinfo 0xdb7d0010)
V/MediaPlayer(10861): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(10861): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(10861): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(10861): cleanDrmObj: mDrmObj=null mDrmSessionId=null
D/EGL_emulation(10861): eglMakeCurrent: 0xdb71aa80: ver 2 0 (tinfo 0xdb7d0010)
E/CloudFirestorePlugin(10861): Timed out waiting for Task
E/CloudFirestorePlugin(10861): java.util.concurrent.TimeoutException: Timed out waiting for Task
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:32)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:527)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:479)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$0(com.google.firebase:firebase-firestore@@21.3.0:301)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$5.call(Unknown Source:6)
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin(10861): 	at java.lang.Thread.run(Thread.java:919)
D/EGL_emulation(10861): eglMakeCurrent: 0xdb71aa80: ver 2 0 (tinfo 0xdb7d0010)
W/ManagedChannelImpl(10861): [{0}] Failed to resolve name. status={1}
W/sticr.warehous(10861): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
V/MediaPlayer(10861): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(10861): cleanDrmObj: mDrmObj=null mDrmSessionId=null
V/MediaPlayer(10861): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
V/MediaPlayer(10861): cleanDrmObj: mDrmObj=null mDrmSessionId=null
W/ManagedChannelImpl(10861): [{0}] Failed to resolve name. status={1}
D/EGL_emulation(10861): eglMakeCurrent: 0xdb71aa80: ver 2 0 (tinfo 0xdb7d0010)
W/ManagedChannelImpl(10861): [{0}] Failed to resolve name. status={1}
E/CloudFirestorePlugin(10861): Timed out waiting for Task
E/CloudFirestorePlugin(10861): java.util.concurrent.TimeoutException: Timed out waiting for Task
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:32)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:527)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:479)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$0(com.google.firebase:firebase-firestore@@21.3.0:301)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$5.call(Unknown Source:6)
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin(10861): 	at java.lang.Thread.run(Thread.java:919)
E/CloudFirestorePlugin(10861): Timed out waiting for Task
E/CloudFirestorePlugin(10861): java.util.concurrent.TimeoutException: Timed out waiting for Task
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:32)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:527)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:479)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$0(com.google.firebase:firebase-firestore@@21.3.0:301)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$5.call(Unknown Source:6)
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin(10861): 	at java.lang.Thread.run(Thread.java:919)
W/ManagedChannelImpl(10861): [{0}] Failed to resolve name. status={1}
E/CloudFirestorePlugin(10861): Timed out waiting for Task
E/CloudFirestorePlugin(10861): java.util.concurrent.TimeoutException: Timed out waiting for Task
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:32)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:527)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:479)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$0(com.google.firebase:firebase-firestore@@21.3.0:301)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$5.call(Unknown Source:6)
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin(10861): 	at java.lang.Thread.run(Thread.java:919)
E/CloudFirestorePlugin(10861): Timed out waiting for Task
E/CloudFirestorePlugin(10861): java.util.concurrent.TimeoutException: Timed out waiting for Task
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:32)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:527)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:479)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$0(com.google.firebase:firebase-firestore@@21.3.0:301)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$5.call(Unknown Source:6)
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin(10861): 	at java.lang.Thread.run(Thread.java:919)
I/flutter (10861): PlatformException(Error performing Transaction#get, UNAVAILABLE: Keepalive failed. The connection is likely gone, null)
E/CloudFirestorePlugin(10861): java.lang.Exception: DoTransaction failed: UNAVAILABLE: Keepalive failed. The connection is likely gone
E/CloudFirestorePlugin(10861): java.util.concurrent.ExecutionException: java.lang.Exception: DoTransaction failed: UNAVAILABLE: Keepalive failed. The connection is likely gone
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:33)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:527)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:479)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$0(com.google.firebase:firebase-firestore@@21.3.0:301)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$5.call(Unknown Source:6)
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin(10861): 	at java.lang.Thread.run(Thread.java:919)
E/CloudFirestorePlugin(10861): Caused by: java.lang.Exception: DoTransaction failed: UNAVAILABLE: Keepalive failed. The connection is likely gone
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4$1$1.error(CloudFirestorePlugin.java:509)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:210)
E/CloudFirestorePlugin(10861): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:111)
E/CloudFirestorePlugin(10861): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:652)
E/CloudFirestorePlugin(10861): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CloudFirestorePlugin(10861): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/CloudFirestorePlugin(10861): 	at android.os.Looper.loop(Looper.java:174)
E/CloudFirestorePlugin(10861): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/CloudFirestorePlugin(10861): 	at java.lang.reflect.Method.invoke(Native Method)
E/CloudFirestorePlugin(10861): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/CloudFirestorePlugin(10861): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
W/ManagedChannelImpl(10861): [{0}] Failed to resolve name. status={1}
I/flutter (10861): PlatformException(Error performing Transaction#get, UNAVAILABLE: Unable to resolve host firestore.googleapis.com, null)
E/CloudFirestorePlugin(10861): java.lang.Exception: DoTransaction failed: UNAVAILABLE: Unable to resolve host firestore.googleapis.com
E/CloudFirestorePlugin(10861): java.util.concurrent.ExecutionException: java.lang.Exception: DoTransaction failed: UNAVAILABLE: Unable to resolve host firestore.googleapis.com
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.Tasks.zzb(Unknown Source:61)
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.Tasks.await(Unknown Source:33)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:527)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4.apply(CloudFirestorePlugin.java:479)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore.lambda$runTransaction$0(com.google.firebase:firebase-firestore@@21.3.0:301)
E/CloudFirestorePlugin(10861): 	at com.google.firebase.firestore.FirebaseFirestore$$Lambda$5.call(Unknown Source:6)
E/CloudFirestorePlugin(10861): 	at com.google.android.gms.tasks.zzv.run(Unknown Source:2)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/CloudFirestorePlugin(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/CloudFirestorePlugin(10861): 	at java.lang.Thread.run(Thread.java:919)
E/CloudFirestorePlugin(10861): Caused by: java.lang.Exception: DoTransaction failed: UNAVAILABLE: Unable to resolve host firestore.googleapis.com
E/CloudFirestorePlugin(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$4$1$1.error(CloudFirestorePlugin.java:509)
E/CloudFirestorePlugin(10861): 	at io.flutter.plugin.common.MethodChannel$IncomingResultHandler.reply(MethodChannel.java:210)
E/CloudFirestorePlugin(10861): 	at io.flutter.embedding.engine.dart.DartMessenger.handlePlatformMessageResponse(DartMessenger.java:111)
E/CloudFirestorePlugin(10861): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessageResponse(FlutterJNI.java:652)
E/CloudFirestorePlugin(10861): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/CloudFirestorePlugin(10861): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/CloudFirestorePlugin(10861): 	at android.os.Looper.loop(Looper.java:174)
E/CloudFirestorePlugin(10861): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/CloudFirestorePlugin(10861): 	at java.lang.reflect.Method.invoke(Native Method)
E/CloudFirestorePlugin(10861): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/CloudFirestorePlugin(10861): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/AndroidRuntime(10861): FATAL EXCEPTION: AsyncTask #3
E/AndroidRuntime(10861): Process: com.komtesa.elasticr.warehouse, PID: 10861
E/AndroidRuntime(10861): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(10861): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(10861): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10861): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(10861): Caused by: java.lang.AssertionError: INTERNAL ASSERTION FAILED: A transaction object cannot be used after its update callback has been invoked.
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.util.Assert.fail(com.google.firebase:firebase-firestore@@21.3.0:46)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.util.Assert.hardAssert(com.google.firebase:firebase-firestore@@21.3.0:31)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.core.Transaction.ensureCommitNotCalled(com.google.firebase:firebase-firestore@@21.3.0:246)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.core.Transaction.lookup(com.google.firebase:firebase-firestore@@21.3.0:81)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.Transaction.getAsync(com.google.firebase:firebase-firestore@@21.3.0:191)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.Transaction.get(com.google.firebase:firebase-firestore@@21.3.0:228)
E/AndroidRuntime(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:569)
E/AndroidRuntime(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:564)
E/AndroidRuntime(10861): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10861): 	... 4 more
E/AndroidRuntime(10861): FATAL EXCEPTION: AsyncTask #2
E/AndroidRuntime(10861): Process: com.komtesa.elasticr.warehouse, PID: 10861
E/AndroidRuntime(10861): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(10861): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(10861): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10861): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(10861): Caused by: java.lang.AssertionError: INTERNAL ASSERTION FAILED: A transaction object cannot be used after its update callback has been invoked.
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.util.Assert.fail(com.google.firebase:firebase-firestore@@21.3.0:46)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.util.Assert.hardAssert(com.google.firebase:firebase-firestore@@21.3.0:31)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.core.Transaction.ensureCommitNotCalled(com.google.firebase:firebase-firestore@@21.3.0:246)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.core.Transaction.lookup(com.google.firebase:firebase-firestore@@21.3.0:81)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.Transaction.getAsync(com.google.firebase:firebase-firestore@@21.3.0:191)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.Transaction.get(com.google.firebase:firebase-firestore@@21.3.0:228)
E/AndroidRuntime(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:569)
E/AndroidRuntime(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:564)
E/AndroidRuntime(10861): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10861): 	... 4 more
E/AndroidRuntime(10861): FATAL EXCEPTION: AsyncTask #5
E/AndroidRuntime(10861): Process: com.komtesa.elasticr.warehouse, PID: 10861
E/AndroidRuntime(10861): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(10861): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(10861): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10861): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(10861): Caused by: java.lang.AssertionError: INTERNAL ASSERTION FAILED: A transaction object cannot be used after its update callback has been invoked.
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.util.Assert.fail(com.google.firebase:firebase-firestore@@21.3.0:46)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.util.Assert.hardAssert(com.google.firebase:firebase-firestore@@21.3.0:31)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.core.Transaction.ensureCommitNotCalled(com.google.firebase:firebase-firestore@@21.3.0:246)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.core.Transaction.lookup(com.google.firebase:firebase-firestore@@21.3.0:81)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.Transaction.getAsync(com.google.firebase:firebase-firestore@@21.3.0:191)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.Transaction.get(com.google.firebase:firebase-firestore@@21.3.0:228)
E/AndroidRuntime(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:569)
E/AndroidRuntime(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:564)
E/AndroidRuntime(10861): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10861): 	... 4 more
E/AndroidRuntime(10861): FATAL EXCEPTION: AsyncTask #4
E/AndroidRuntime(10861): Process: com.komtesa.elasticr.warehouse, PID: 10861
E/AndroidRuntime(10861): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime(10861): 	at android.os.AsyncTask$4.done(AsyncTask.java:399)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime(10861): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
E/AndroidRuntime(10861): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime(10861): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime(10861): 	at java.lang.Thread.run(Thread.java:919)
E/AndroidRuntime(10861): Caused by: java.lang.AssertionError: INTERNAL ASSERTION FAILED: A transaction object cannot be used after its update callback has been invoked.
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.util.Assert.fail(com.google.firebase:firebase-firestore@@21.3.0:46)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.util.Assert.hardAssert(com.google.firebase:firebase-firestore@@21.3.0:31)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.core.Transaction.ensureCommitNotCalled(com.google.firebase:firebase-firestore@@21.3.0:246)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.core.Transaction.lookup(com.google.firebase:firebase-firestore@@21.3.0:81)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.Transaction.getAsync(com.google.firebase:firebase-firestore@@21.3.0:191)
E/AndroidRuntime(10861): 	at com.google.firebase.firestore.Transaction.get(com.google.firebase:firebase-firestore@@21.3.0:228)
E/AndroidRuntime(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:569)
E/AndroidRuntime(10861): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:564)
E/AndroidRuntime(10861): 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
E/AndroidRuntime(10861): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime(10861): 	... 4 more
I/Process (10861): Sending signal. PID: 10861 SIG: 9
Failed to send request: {"jsonrpc":"2.0","id":"89","method":"resume","params":{"isolateId":"isolates/3358128556027691"}}```

**Comment by TahaTesser** [comment] 2020-03-31 12:11
Hi @prokyhb 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by ZedTheLed** [comment] 2020-04-14 13:37
I think I'm experiencing the same issue.
It seems that calling `firestore.settings(persistenceEnabled: false)` has no effect.

Tested on Android physical device and iOS simulator, with `cloud_firestore: ^0.13.4+2`.

### Minimal Code Sample:

```dart
final firestore = Firestore.instance;

await firestore.settings(
  persistenceEnabled: false,
);

try {
  final dataBefore = (await firestore
          .collection("testCollection")
          .document("testDocument")
          .get())
              .data;

  print(dataBefore);
} catch (e) {
  print(e);
}

firestore
    .collection("testCollection")
    .document("testDocument")
    .setData({"greeting": "Hello World"}).then(
          (_) {
            print("Success");
          },
          onError: (_) {
            print("Failure");
         },
);

try {
  final dataAfter = (await firestore
          .collection("testCollection")
          .document("testDocument")
          .get())
              .data;

  print(dataAfter);
} catch (e) {
  print(e);
}
```

### Actual Result

If my Firestore database is empty and my phone is in airplane mode, I call the code I get:
```
flutter: PlatformException(Error 14, FIRFirestoreErrorDomain, Failed to get document because the client is offline.)
flutter: {greeting: Hello World}
```
If I stay in airplane mode, the Future returned by calling `setData` on Firestore never completes.

If I connect back to the internet, the future completes successfully (data gets uploaded to Firestore), and I get:
```
flutter: Success
```

### Expected Result

If `persistenceEnabled` is set to `false` and phone is in airplane mode, the future returned by calling `setData` should complete with an error.

I should get:
```
flutter: PlatformException(Error 14, FIRFirestoreErrorDomain, Failed to get document because the client is offline.)
flutter: PlatformException(Error 14, FIRFirestoreErrorDomain, Failed to get document because the client is offline.)
flutter: Failure
```

### Flutter doctor -v

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.15.4 19E266, locale en-US)
    • Flutter version 1.12.13+hotfix.9 at /Users/zed/Tools/flutter
    • Framework revision f139b11009 (2 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/zed/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.0

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • A0001             • 793b4d8b                             • android-arm • Android 9 (API 28)
    • iPhone 11 Pro Max • 4AC50F8E-CA8C-4A1B-9A6A-1B91B667C63D • ios         • com.apple.CoreSimulator.SimRuntime.iOS-13-4 (simulator)

• No issues found!
```

**Comment by AndroidNils** [comment] 2020-06-01 23:04
Same issue. `firestore.settings(persistenceEnabled: false)` has no effect. Tested on web with firestore `^0.13.5`.

**Comment by Ehesp** [comment] 2020-06-02 08:01
Whenever you trigger a write request, it is always written to the local database first. If the sync with the server is successful the request will resolve. If for example there is no internet connection, any listeners will still trigger (since the local DB has been updated), however the request will not resolve.

**Comment by Salakar** [comment] 2020-07-09 15:03
Hey all, as part of our on-going work for #2582, the various persistence related APIs are now working on all platforms in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you

**Closed by Salakar** 2020-07-09 15:03 UTC
Labels: impact: customer, plugin: cloud_firestore
