### ISSUE TITLE
Problem in fetching parameters from Firebase dynamic link in flutter

### ISSUE THREAD

**Issue by Abosrie** [FirebaseExtended/flutterfire#2178] opened 2020-03-16 15:17 UTC
I have a problem receiving the parameters in the firebase dynamic link. What I need is to fetch the **UserId** from the dynamic link But I am getting only _https://albyrak.page.link/referral_

**How I am creating the Dynamic Link**

```
Future<Uri> createDynamicLink({@required String userId}) async {
    final DynamicLinkParameters parameters = DynamicLinkParameters(
      uriPrefix: 'https://albyrak.page.link/referral',
      link: Uri.parse('?userId=$userId'),
      androidParameters: AndroidParameters(
        packageName: 'albyrak.cvit',
        minimumVersion: 1,
      ),
      iosParameters: IosParameters(
        bundleId: 'com.cvit.albyrak',
        minimumVersion: '1',
        appStoreId: '1479999546',
      ),
    );

    final link = await parameters.buildUrl();
    return link;
  }

```

**How I am receiving the Dynamic link**

 ```
 void initDynamicLinks() async {
    print("Deep link function");
    final PendingDynamicLinkData data =
        await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;
    print(deepLink);

    if (deepLink != null) {
      print("Deep link is not null");
      print(deepLink);
      Navigator.pushNamed(context, deepLink.path);
    }

    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {
      print(dynamicLink.link);
      final Uri deepLink = dynamicLink?.link;
      print(deepLink);
      if (deepLink != null) {
        print(deepLink.queryParameters['userId']);
        
      }
    }, onError: (OnLinkErrorException e) async {
      print('onLinkError');
      print(e.message);
    });
  }
```

**Comment by iapicca** [comment] 2020-03-20 08:35
Hi @Abosrie 
thank you for providing the code sample

can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`and
your `pubspec.yaml` as well
Thank you

**Comment by Ehesp** [comment] 2020-04-22 12:27
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1289

**Closed by Ehesp** 2020-04-22 12:27 UTC
Labels: blocked: customer-response, plugin: dynamic_links, type: bug, type: enhancement
