### ISSUE TITLE
🐛 firebase_analytics not support null safety

### ISSUE THREAD

**Issue by farhanroy** [FirebaseExtended/flutterfire#5479] opened 2021-03-26 03:24 UTC
## Bug report

**Describe the bug**
firebase_analytics_web.dart:1:1: Error: A library can't opt out of null safety by default, when using sound null safety.
[   +3 ms] // @dart=2.9

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Expected behavior

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by friebetill** [comment] 2021-03-26 09:45
Duplicate of #5207.

**Closed** 2021-03-26 09:51 UTC
Labels: Needs Attention, type: bug
