### ISSUE TITLE
Firebase/MLVisionBarcodeModel was resolved to 5.0.0,

### ISSUE THREAD

**Issue by laopaoer-wallet** [FirebaseExtended/flutterfire#4804] opened 2021-01-25 02:15 UTC
```
firebase_core: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
firebase_crashlytics: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
firebase_ml_vision: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
[!] CocoaPods could not find compatible versions for pod "Firebase/CoreOnly":
  In Podfile:
    Firebase/MLVisionBarcodeModel was resolved to 5.0.0, which depends on
      Firebase/CoreOnly (= 5.0.0)

    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
      Firebase/CoreOnly (= 7.3.0)

    firebase_messaging (from `.symlinks/plugins/firebase_messaging/ios`) was resolved to 7.0.3, which depends on
      Firebase/CoreOnly (~> 7.3.0)

CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
      Firebase/CoreOnly (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebaseCore (= 7.3.0)

    firebase_ml_vision (from `.symlinks/plugins/firebase_ml_vision/ios`) was resolved to 0.1.1, which depends on
      Firebase/MLVision (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebaseMLVision (~> 7.3.0-beta) was resolved to 7.3.0-beta, which depends on
          FirebaseCore (~> 7.0)

CocoaPods could not find compatible versions for pod "nanopb":
  In Podfile:
    firebase_core (from `.symlinks/plugins/firebase_core/ios`) was resolved to 0.7.0, which depends on
      Firebase/CoreOnly (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebaseCore (= 7.3.0) was resolved to 7.3.0, which depends on
          FirebaseCoreDiagnostics (~> 7.0) was resolved to 7.4.0, which depends on
            nanopb (~> 2.30907.0)

    firebase_crashlytics (from `.symlinks/plugins/firebase_crashlytics/ios`) was resolved to 0.4.0-1, which depends on
      Firebase/Crashlytics (= 7.3.0) was resolved to 7.3.0, which depends on
        FirebaseCrashlytics (~> 7.3.0) was resolved to 7.3.0, which depends on
          nanopb (~> 2.30906.0)
```

**Comment by jeroen-meijer** [comment] 2021-01-25 12:00
Seems like a duplicate of #4625
Still not fixed though...

**Comment by markusaksli-nc** [comment] 2021-01-25 12:02
There are some other incompatibilities but the issue is quite vague and this will depend on https://github.com/FirebaseExtended/flutterfire/issues/4625 anyway.

Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4625

**Closed by markusaksli-nc** 2021-01-25 12:02 UTC
Labels: Needs Attention, type: bug
