### ISSUE TITLE
🐛 [firebase_analytics] Value and revenue is always 0 in console, although values received by firebase via logEvent

### ISSUE THREAD

**Issue by gerripro** [FirebaseExtended/flutterfire#5135] opened 2021-02-24 19:51 UTC
## Bug report
Value and revenue is always 0 in console, although values received by firebase via logEvent. That's the issue:
![image](https://user-images.githubusercontent.com/74319105/109056893-7c0c1400-76fa-11eb-8b9a-b016aa0a37ae.png)

that's my method for logging. It is not even custom method:
```
getIt<AnalyticsService>().analytics.logAddToCart(
        itemId: preorderItem.id,
        itemName: preorderItem.name,
        itemCategory: null,
        quantity: 1,
        currency: "USD",
        price: (preorderItem.amountCents.toDouble()/100),
        value: (preorderItem.amountCents.toDouble()/100),
    );
```
My debug panel:

![image](https://user-images.githubusercontent.com/74319105/109056600-115ad880-76fa-11eb-8b40-b1f142cf54ad.png)

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel flutter-1.24-candidate.10, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1379], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Android Studio (version 4.1.0)
[√] Connected device (1 available)

• No issues found!

```

</details>

**Comment by markusaksli-nc** [comment] 2021-02-25 08:58
Hi @gerripro 
Could you please provide your `flutter pub deps -- --style=compact` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by gerripro** [comment] 2021-02-25 13:06
**Flutter pub deps**
`Dart SDK 2.12.0-29.10.beta
Flutter SDK 1.24.0-10.2.pre
nown_app 3.13.6+411
<details>
dependencies:
- assorted_layout_widgets 3.0.1 [matrix4_transform flutter]
- audioplayers 0.17.4 [uuid path_provider flutter flutter_web_plugins]
- auto_size_text 2.1.0 [flutter]
- carousel_slider 2.3.4 [flutter]
- country_code_picker 1.7.0 [flutter modal_bottom_sheet]
- credit_card_type_detector 1.1.0
- encrypt 4.1.0 [args asn1lib clock collection crypto pointycastle]
- expandable 4.1.4 [flutter]
- feather_icons_flutter 4.7.4 [flutter]
- firebase_analytics 7.0.1 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.4.0+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_messaging 8.0.0-dev.15 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_advanced_networkimage 0.8.0 [flutter http path_provider path flutter_svg]
- flutter_beacon 0.3.0 [flutter]
- flutter_form_builder 3.14.1 [flutter flutter_typeahead intl flutter_chips_input datetime_picker_formfield flutter_colorpicker signature validators date_range_pick
er flutter_touch_spin image_picker image_picker_for_web rating_bar country_pickers phone_number]
- flutter_html 0.11.1 [html flutter]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_masked_text 0.8.0 [flutter]
- flutter_stetho 0.5.2 [flutter]
- flutter_svg 0.19.2+1 [flutter meta path_drawing vector_math xml]
- fluttercontactpicker 3.1.1 [flutter]
- frideos 1.0.1 [flutter rxdart]
- geolocator 5.3.2+2 [flutter meta equatable google_api_availability location_permissions vector_math]
- get_it 5.0.6 [async meta]
- gradient_text 1.0.2 [flutter]
- http 0.12.2 [http_parser path pedantic]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- in_app_review 1.0.4 [flutter in_app_review_platform_interface]
- intl 0.16.1 [path]
- json_annotation 3.1.1
- maps_launcher 1.2.2+2 [flutter flutter_web_plugins url_launcher]
- money 0.2.1
- open_appstore 1.0.2 [flutter]
- package_info 0.4.3+4 [flutter]
- palette_generator 0.2.3 [flutter collection path]
- permission_handler 5.1.0+2 [flutter meta permission_handler_platform_interface]
- qr_flutter 3.2.0 [flutter qr]
- retry 3.0.1
- screen 0.0.5 [flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_pr
eferences_windows]
- sms_autofill 1.3.1 [pin_input_text_field flutter]
- socket_io_client 0.9.12 [logging socket_io_common]
- tinycolor 1.0.3 [pigment meta flutter]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- uuid 2.2.2 [crypto convert]
- webview_flutter 1.0.7 [flutter]

dev dependencies:
- build_runner 1.11.1 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi
_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel ya
ml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span
stream_channel string_scanner term_glyph typed_data]
- json_serializable 3.5.1 [analyzer build build_config json_annotation meta path source_gen]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- asn1lib 0.8.1
- async 2.5.0-nullsafety.3 [collection]
- basic_utils 2.7.1 [http logging json_annotation pointycastle convert crypto]
- boolean_selector 2.1.0-nullsafety.3 [source_span string_scanner]
- build 1.6.2 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.5 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.8 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.3 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.7 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watc
her yaml]
- built_collection 5.0.0
- built_value 8.0.0-nullsafety.0 [built_collection collection fixnum]
- characters 1.1.0-nullsafety.5
- charcode 1.2.0-nullsafety.3
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.3
- code_builder 3.6.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.5
- convert 2.1.1 [charcode typed_data]
- country_pickers 1.3.0 [flutter]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.12 [analyzer args path pub_semver source_span]
- date_range_picker 1.0.6 [flutter]
- datetime_picker_formfield 1.0.0 [flutter intl]
- equatable 1.2.6 [collection meta]
- fake_async 1.2.0-nullsafety.3 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.6 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_messaging_platform_interface 1.0.0-dev.10 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.6 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- fixnum 1.0.0
- flutter_chips_input 1.9.5 [flutter]
- flutter_colorpicker 0.3.5 [flutter]
- flutter_keyboard_visibility 4.0.4 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 1.0.1 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_touch_spin 1.0.1 [flutter intl]
- flutter_typeahead 1.9.3 [flutter flutter_keyboard_visibility]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_api_availability 2.0.4 [flutter]
- graphs 0.2.0
- html 0.14.0+4 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_for_web 0.1.0+2 [image_picker_platform_interface flutter flutter_web_plugins meta js]
- image_picker_platform_interface 1.1.6 [flutter meta http plugin_platform_interface]
- in_app_review_platform_interface 1.0.5 [flutter url_launcher plugin_platform_interface platform]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3-nullsafety.3
- location_permissions 3.0.0+1 [flutter meta]
- logging 0.11.4
- matcher 0.12.10-nullsafety.3 [stack_trace]
- matrix4_transform 1.1.7 [flutter]
- meta 1.3.0-nullsafety.6
- mime 1.0.0
- modal_bottom_sheet 1.0.0+1 [flutter]
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.3
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.10.0
- permission_handler_platform_interface 2.0.2 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- phone_number 0.6.3 [flutter]
- pigment 1.0.3 [flutter]
- pin_input_text_field 3.3.1 [flutter]
- platform 3.0.0
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 2.0.1
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.8 [checked_yaml json_annotation pub_semver yaml]
- qr 1.3.0 [meta]
- quiver 2.1.5 [matcher meta]
- random_string 2.1.0
- rating_bar 0.2.0 [flutter]
- rxdart 0.24.1
- service_worker 0.2.4 [js]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- signature 3.2.0 [flutter image]
- sky_engine 0.0.99
- socket_io_common 0.9.2 [logging]
- source_gen 0.9.10+3 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.4 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.6 [path]
- stream_channel 2.1.0-nullsafety.3 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.3 [charcode source_span]
- term_glyph 1.2.0-nullsafety.3
- test_api 0.2.19-nullsafety.6 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0-nullsafety.5 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- validators 2.0.1 [vin_decoder]
- vector_math 2.1.0-nullsafety.5
- vin_decoder 0.1.3 [meta basic_utils http random_string]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- win32 1.7.4+1 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
`</details>

**Flutter doctor -v**
<details>
`[√] Flutter (Channel flutter-1.24-candidate.10, 1.24.0-10.2.pre, on Microsoft Windows [Version 10.0.18363.1379], locale ru-RU)
    • Flutter version 1.24.0-10.2.pre at D:\flutter
    • Framework revision 022b333a08 (3 months ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at C:\Users\Georgy\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 11 (API 30) (emulator)

• No issues found!
`
</details>

**Comment by gerripro** [comment] 2021-02-25 14:15
Hi ** @markusaksli-nc**
**minimal complete reproducible code sample** 
**Main.dart**
<details>
`// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// @dart=2.9

import 'dart:async';
import 'package:flutter/material.dart';
import 'package:get_it/get_it.dart';
import 'analytics.service.dart';
import 'initialize.app.dart';

Future<void> main() async {
  await InitializeApp.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  final GetIt getIt = GetIt.instance;

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firebase Analytics Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      navigatorObservers: [getIt<AnalyticsService>().getAnalyticsObserver()],
      home: MyHomePage(
        title: 'Firebase Analytics Demo',
      ),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title})
      : super(key: key);

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  final GetIt getIt = GetIt.instance;

  String _message = '';
  int _counter = 0;
  int priceCents = 295;
  String name = 'Americano';
  void _incrementCounter() {
    setState(() {
      _counter++;
    });
  }
  void setMessage(String message) {
    setState(() {
      _message = message;
    });
  }

  @override
  Widget build(BuildContext context) {
    getIt<AnalyticsService>().setCurrentScreen('HomePage', 'Home Page');
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            Container(
              child: Row(children: [
                SizedBox(width: 135,),
                Text('Americano',style: TextStyle(fontWeight: FontWeight.bold)),
                SizedBox(width: 15,),
                Text('${priceCents.toDouble()/100}\$', style: TextStyle(fontWeight: FontWeight.bold)),
              ],),
            ),
            Text(
                'Press floating button to add Americano to your cart',
                style: TextStyle(fontWeight: FontWeight.w300)
            ),
            Text(
              'Amount of Americano\s in your cart:',style: TextStyle(fontWeight: FontWeight.bold),
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.headline4,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          getIt<AnalyticsService>().analytics.logAddToCart(
            itemId: '12131',
            itemName: name,
            itemCategory: null,
            quantity: 1,
            currency: "USD",
            price: (priceCents.toDouble()/100),
            value: (priceCents.toDouble()/100),
          );
          _incrementCounter();
        },
        tooltip: 'Add to cart',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}
`
</details>

**initialize.app**
<details>
`import 'dart:async';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:get_it/get_it.dart';
import 'analytics.service.dart';

class InitializeApp {
  static void initializeServices() {
    var getIt = GetIt.instance;
    getIt.registerSingleton<AnalyticsService>(AnalyticsService());
    return;
  }

  static Future<void> initializeFirebase() async {
    await Firebase.initializeApp();
    await AnalyticsService().setAnalyticsCollectionEnabled();
  }
  static Future<void> initializeApp() async {
    WidgetsFlutterBinding.ensureInitialized();
    await initializeFirebase();
    initializeServices();
  }
}
`
</details>

**analytics.service**
<details>
`import 'package:get_it/get_it.dart';
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_analytics/observer.dart';

class AnalyticsService {
  // Singleton Service
  // Every instantiation of this class will reference the same class instance
  static final AnalyticsService _analyticsService =
  AnalyticsService._internal();

  factory AnalyticsService() {
    return _analyticsService;
  }

  AnalyticsService._internal();

  final GetIt getIt = GetIt.instance;

  final FirebaseAnalytics analytics = FirebaseAnalytics();

  FirebaseAnalyticsObserver getAnalyticsObserver() =>
      FirebaseAnalyticsObserver(analytics: analytics);

  Future<void> setCurrentScreen(String screenName, String className) async {
    await analytics.setCurrentScreen(
      screenName: screenName,
      screenClassOverride: className,
    );
  }

  Future<void> setAnalyticsCollectionEnabled() async {
    await analytics.setAnalyticsCollectionEnabled(false);
    await analytics.setAnalyticsCollectionEnabled(true);
  }

  Future<void> sendPurchaseEvent(String name) async {
    await analytics.logEvent(
      name: 'purchase_complete',
      parameters: <String, dynamic>{
        'purchase_complete': '$name',
      },
    );
  }
}
`
</details>

**Comment by markusaksli-nc** [comment] 2021-02-26 13:27
I'm not sure I understand the problem here. The value is being logged correctly but this is just the add to cart event so it shouldn't count as revenue. That is why revenue is 0 in the outlined places in console.

**Comment by gerripro** [comment] 2021-02-26 13:51
@markusaksli-nc 
How do I track value for add-to-cart event? 
I need to see it in a graph

**Comment by markusaksli-nc** [comment] 2021-02-26 14:03
Those graphs are set up by Firebase team so you could ask for a feature request for more fine grain control over the displayed properties in graphs https://firebase.google.com/support 

Other than that you could always export the CSV and create local graphs or expose the events to Metabase or something else through the API.

This repository however just wraps the upstream native Firebase SDKs so they could be used with Flutter and since there doesn't seem to be any issue with our plugins here I'm going to close the issue.

**Closed by markusaksli-nc** 2021-02-26 14:03 UTC
Labels: Needs Attention, type: bug

**Comment by gerripro** [comment] 2021-02-26 20:21
@markusaksli-nc But this is what mentioned in native Firebase Documentation. Correct me if I am wrong but it seems to me it says if I enter value and currency it would reflect revenue or at least value on the graph
![image](https://user-images.githubusercontent.com/74319105/109349067-cb834900-788e-11eb-9494-6ca79f48cd34.png)
