### ISSUE TITLE
firebase_messaging with local notification

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1062] opened 2019-10-13 19:35 UTC
i know firebase_messaging can't work fine with local notification pub.
let me know solution about using firebase_messaging with local notifi feature or you must create similar feature inside firebase_messaging package. please !

**Comment by kroikie** [comment] 2019-10-13 19:35
@minh98

The issue at https://github.com/flutter/flutter/issues/31492 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment] 2019-10-21 14:18
@minh98 do you still encounter the issue?

**Comment by tbm98** [comment] 2019-10-21 15:50
@BondarenkoStas  yes. it's a bug from [#111](https://github.com/MaikuB/flutter_local_notifications/issues/111)

**Comment by Ehesp** [comment] 2020-04-23 09:21
Duplicate of https://github.com/MaikuB/flutter_local_notifications/issues/111

**Closed by Ehesp** 2020-04-23 09:21 UTC
Labels: type: bug
