### ISSUE TITLE
firebase_crashyltics Incorrect documentation (fabric.io)

### ISSUE THREAD

**Issue by GuruJohn** [FirebaseExtended/flutterfire#2871] opened 2020-06-30 23:38 UTC
**Describe the bug**
The documentation shows how to setup using fabric.io but fabric.io is shuting down Ma‌y 4, 2020.

https://pub.dev/packages/firebase_crashlytics has setup instruction like:
```
url 'https://maven.fabric.io/public'
````
```
classpath 'io.fabric.tools:gradle:1.26.1'
````

There is also the issue that if you click the install tab it has a different set of instructions.

https://pub.dev/packages/firebase_crashlytics#-installing-tab- seem to say you don't need to make any changes to the build.gradle files? 

Which one is correct?

**To Reproduce**
Goto https://pub.dev/packages/firebase_crashlytics and look

**Expected behavior**
Instructions on how to setup firebase_crashlytics on firebase not on fabric

**Comment by RyosukeOK** [comment] 2020-07-01 05:05
duplicate of #2038

**Comment by TahaTesser** [comment] 2020-07-01 08:29
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2038

**Closed by TahaTesser** 2020-07-01 08:29 UTC
