### ISSUE TITLE
🐛 [cloud_firestore: ^0.14.4] where 'isLessThan' don't work correctly on iOS

### ISSUE THREAD

**Issue by jpoh281** [FirebaseExtended/flutterfire#4449] opened 2020-12-21 02:36 UTC
```
Future<List<TimeLog>>fetchMoreTimeLog(List<TimeLog> timeLog,String petKey) async{
     var timeLogSnapshot =  await firestore.collection('report').doc(petKey).collection('timelog').where('createdAt',isLessThan : timeLog.last.createdAt).orderBy('createdAt', descending: true).limit(8).get();
     print("My Last TimeStamp : ${timeLog.last.createdAt}");
     List<TimeLog> myTimeLog = [];
     if (timeLogSnapshot.size != 0) {
       myTimeLog =
           timeLogSnapshot.docs.map((e) => TimeLog.fromJson(e.data(), e.id))
               .toList();
       print("Get New TimeStamp : ${myTimeLog[0].createdAt}");
     }
       return myTimeLog;
  }
```
![image](https://user-images.githubusercontent.com/54665433/102733433-a818bb00-4380-11eb-8d0f-e661ac10d0b2.png)

why isLessThan work  like isLessThanOrEqualTo ?

**Comment by markusaksli-nc** [comment] 2020-12-21 14:22
Hi @j05u3 
I was not able to reproduce this on the latest master `1.26.0-2.0.pre.86` with `cloud_firestore: ^0.14.4`.
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.86, on macOS 11.0.1 20B29 darwin-arm, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.86 at /Users/nevercode/development/flutter_master
    • Framework revision b793285329 (3 days ago), 2020-12-18 10:14:36 -0800
    • Engine revision 7983c6fda0
    • Dart version 2.12.0 (build 2.12.0-167.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios • iOS 14.3

! Doctor found issues in 1 category.
```
</details>
<details>
 <summary>Minimal code sample</summary>

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  runApp(MyApp());
}

class MyApp extends StatefulWidget {
  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  var time = Timestamp.now();

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Scaffold(
        appBar: AppBar(
          title: const Text('Sample'),
        ),
        body: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            RaisedButton(
              child: const Text("Set"),
              onPressed: () async {
                await FirebaseFirestore.instance.collection('test').doc('testA').set({"time":time});
                await FirebaseFirestore.instance.collection('test').doc('testB').set({"time":Timestamp.fromMicrosecondsSinceEpoch(time.microsecondsSinceEpoch - 100)});
              },
            ),
            RaisedButton(
              child: const Text("Get LessThan"),
              onPressed: () async {
                var timeLogSnapshot =  await FirebaseFirestore.instance.collection('test').where('time',isLessThan : time).orderBy('time', descending: true).limit(8).get();
                print(timeLogSnapshot.docs.length);
                print('max time: ${DateTime.fromMicrosecondsSinceEpoch(time.microsecondsSinceEpoch)}');
                if (timeLogSnapshot.size != 0) {
                  for (var timestamp in timeLogSnapshot.docs){
                    print('entry time: ${DateTime.fromMicrosecondsSinceEpoch(timestamp.get("time").microsecondsSinceEpoch)}');
                  }
                }
              },
            ),
            RaisedButton(
              child: const Text("Get LessThanOrEqualTo"),
              onPressed: () async {
                var timeLogSnapshot =  await FirebaseFirestore.instance.collection('test').where('time',isLessThanOrEqualTo : time).orderBy('time', descending: true).limit(8).get();
                print(timeLogSnapshot.docs.length);
                print('max time: ${DateTime.fromMicrosecondsSinceEpoch(time.microsecondsSinceEpoch)}');
                if (timeLogSnapshot.size != 0) {
                  for (var timestamp in timeLogSnapshot.docs){
                    print('entry time: ${DateTime.fromMicrosecondsSinceEpoch(timestamp.get("time").microsecondsSinceEpoch)}');
                  }
                }
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

Are you able to reproduce the issue with the sample I provided?
Could you provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by jpoh281** [comment] 2020-12-26 13:56
```
[✓] Flutter (Channel stable, 1.22.3, on macOS 11.1 20C69, locale ko-KR)
    • Flutter version 1.22.3 at /Users/jpoh/flutter
    • Framework revision 8874f21e79 (8 weeks ago), 2020-10-29 14:14:35 -0700
    • Engine revision a1440ca392
    • Dart version 2.10.3

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/jpoh/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
```

<img width="351" alt="image" src="https://user-images.githubusercontent.com/54665433/103152658-84fd6980-47cd-11eb-9b05-7e8887b2e695.png">

no issue... I don't know why my code doesn't work

**Comment by j05u3** [comment] 2020-12-26 17:31
> Hi @j05u3
> I was not able to reproduce this on the latest master `1.26.0-2.0.pre.86` with `cloud_firestore: ^0.14.4`.
> 
> flutter doctor -v
> Minimal code sample
> Are you able to reproduce the issue with the sample I provided?
> Could you provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
> Thank you

hehe, I am not involved in this issue

**Comment by markusaksli-nc** [comment] 2020-12-28 07:05
Sorry, github mentions sometimes just lists random users instead of the actual reporter

**Comment by markusaksli-nc** [comment] 2020-12-28 07:10
@jpoh281 Since this doesn't seem like an issue with the plugin itself I'm going to close the issue for now. If it turns out to only be reproducible in some specific context or with a specific document structure let me know and I'll reopen it.

Other than that I reccomend you try to debug your own code and check where the difference comes from.

**Closed by markusaksli-nc** 2020-12-28 07:10 UTC
Labels: Needs Attention, type: bug
