### ISSUE TITLE
App receives different push notification structure (in onMessage) on Android and iOS, document ways o handle this in the app

### ISSUE THREAD

**Issue by vytautas-pranskunas-** [FirebaseExtended/flutterfire#3779] opened 2020-10-05 20:48 UTC
I am sending push notification to iOS. When run-in gin emulator I receive push notification with notification object notification":{"body":"Test","title":"Test" }, however when app is built and deployed I receive same title in "app": {"alert": {"title": "test"} }

It is deployed on Apple 6 but iOS 13.

This behaviour looks similar to message["data"] ?? message however not mentioned anywhere in docs.
How should I behave? Should I add same check or it is a bug?

Also body property is missing

![image](https://user-images.githubusercontent.com/3918999/95134206-c0564200-0762-11eb-8f7d-6a0a0639ebf2.png)

**Comment by darshankawar** [comment] 2020-10-07 12:04
@vytautas-pranskunas- 
Please provide `flutter doctor -v` and a minimal complete reproducible code sample.
Thanks.

**Comment by vytautas-pranskunas-** [comment] 2020-10-07 12:21
![image](https://user-images.githubusercontent.com/3918999/95329998-2698ad00-08a8-11eb-9fbd-0a908e63f14b.png)

```
class PushNotificationsService {
  final FirebaseMessaging _firebaseMessaging = new FirebaseMessaging();
  final _bgService = GetIt.instance<BackgroundNotificationsService>();
  final _securityService = GetIt.instance<SecurityService>();
  final _authService = GetIt.instance<AuthService>();
  final _fgService = GetIt.instance<ForegroundNotificationsService>();

  init() async {
    if (Platform.isIOS) {
      _firebaseMessaging
          .requestNotificationPermissions(IosNotificationSettings());
    }

    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        _fgService.handle(message['data'] ?? message); // If you look at message here you will see that structure when running on iPhone 6 with iOS 12
      },
      onBackgroundMessage: Platform.isIOS ? null : myBackgroundMessageHandler,
      onLaunch: (Map<String, dynamic> message) async {
        _bgService.handle(message['data'] ?? message, true);
      },
      onResume: (Map<String, dynamic> message) async {
        _bgService.handle(message['data'] ?? message, false);
      },
    );
  }

}
```

**Comment by TahaTesser** [comment] 2020-10-20 14:35
Hi @vytautas-pranskunas- 
I think it is working as intended since both platforms have different notifications requirements but labelling the issue for documentation
![Screenshot_2020-10-20-19-59-09-53_5d4307624a4f1d89720c9dd67a5130d1](https://user-images.githubusercontent.com/48603081/96601426-a21a4580-130f-11eb-863f-3f04bb064b85.jpg)
![Image from iOS](https://user-images.githubusercontent.com/48603081/96601430-a34b7280-130f-11eb-8f3e-b2b5abbe9e84.png)

**Comment by vytautas-pranskunas-** [comment] 2020-10-20 14:44
I see your screenshots and i see that body is there but for it did not worked. I had this code:
```
_fgService.handle(message['data'] ?? message,
            message['notification'] ?? message["aps"]["alert"]);
```

and inside handle function i was calling 

```
notification['body']
```

my push notification structure sent from rst client was:
```
{
     "notification": {
       "title": "Test User",
       "text": "Test message test message"
     },
     "data": {
     	"click_action": "FLUTTER_NOTIFICATION_CLICK",
     },
     "priority": "high",
     "to": ..."
   }
```

**Comment by TahaTesser** [comment] 2020-10-21 11:42
Hi @vytautas-pranskunas- 
Using the official example with the following has no issue son latest packages with body 

<details> 
<summary>complete code sample</summary> 

```dart
// Copyright 2019 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

import 'dart:async';

import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';

Future<dynamic> myBackgroundMessageHandler(Map<String, dynamic> message) {
  if (message.containsKey('data')) {
    // Handle data message
    final dynamic data = message['data'];
  }

  if (message.containsKey('notification')) {
    // Handle notification message
    final dynamic notification = message['notification'];
  }

  // Or do other work.
}

final Map<String, Item> _items = <String, Item>{};
Item _itemForMessage(Map<String, dynamic> message) {
  final dynamic data = message['data'] ?? message;
  final String itemId = data['id'];
  final Item item = _items.putIfAbsent(itemId, () => Item(itemId: itemId))
    ..status = data['status'];
  return item;
}

class Item {
  Item({this.itemId});
  final String itemId;

  StreamController<Item> _controller = StreamController<Item>.broadcast();
  Stream<Item> get onChanged => _controller.stream;

  String _status;
  String get status => _status;
  set status(String value) {
    _status = value;
    _controller.add(this);
  }

  static final Map<String, Route<void>> routes = <String, Route<void>>{};
  Route<void> get route {
    final String routeName = '/detail/$itemId';
    return routes.putIfAbsent(
      routeName,
      () => MaterialPageRoute<void>(
        settings: RouteSettings(name: routeName),
        builder: (BuildContext context) => DetailPage(itemId),
      ),
    );
  }
}

class DetailPage extends StatefulWidget {
  DetailPage(this.itemId);
  final String itemId;
  @override
  _DetailPageState createState() => _DetailPageState();
}

class _DetailPageState extends State<DetailPage> {
  Item _item;
  StreamSubscription<Item> _subscription;

  @override
  void initState() {
    super.initState();
    _item = _items[widget.itemId];
    _subscription = _item.onChanged.listen((Item item) {
      if (!mounted) {
        _subscription.cancel();
      } else {
        setState(() {
          _item = item;
        });
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Item ${_item.itemId}"),
      ),
      body: Material(
        child: Center(child: Text("Item status: ${_item.status}")),
      ),
    );
  }
}

class PushMessagingExample extends StatefulWidget {
  @override
  _PushMessagingExampleState createState() => _PushMessagingExampleState();
}

class _PushMessagingExampleState extends State<PushMessagingExample> {
  String _homeScreenText = "Waiting for token...";
  bool _topicButtonsDisabled = false;

  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging();
  final TextEditingController _topicController =
      TextEditingController(text: 'topic');

  Widget _buildDialog(BuildContext context, Item item) {
    return AlertDialog(
      content: Text("Item ${item.itemId} has been updated"),
      actions: <Widget>[
        FlatButton(
          child: const Text('CLOSE'),
          onPressed: () {
            Navigator.pop(context, false);
          },
        ),
        FlatButton(
          child: const Text('SHOW'),
          onPressed: () {
            Navigator.pop(context, true);
          },
        ),
      ],
    );
  }

  void _showItemDialog(Map<String, dynamic> message) {
    showDialog<bool>(
      context: context,
      builder: (_) => _buildDialog(context, _itemForMessage(message)),
    ).then((bool shouldNavigate) {
      if (shouldNavigate == true) {
        _navigateToItemDetail(message);
      }
    });
  }

  void _navigateToItemDetail(Map<String, dynamic> message) {
    final Item item = _itemForMessage(message);
    // Clear away dialogs
    Navigator.popUntil(context, (Route<dynamic> route) => route is PageRoute);
    if (!item.route.isCurrent) {
      Navigator.push(context, item.route);
    }
  }

  @override
  void initState() {
    super.initState();
    _firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        print("onMessage: $message");
        _showItemDialog(message);
      },
      onBackgroundMessage: myBackgroundMessageHandler,
      onLaunch: (Map<String, dynamic> message) async {
        print("onLaunch: $message");
        _navigateToItemDetail(message);
      },
      onResume: (Map<String, dynamic> message) async {
        print("onResume: $message");
        _navigateToItemDetail(message);
      },
    );
    _firebaseMessaging.requestNotificationPermissions(
        const IosNotificationSettings(
            sound: true, badge: true, alert: true, provisional: true));
    _firebaseMessaging.onIosSettingsRegistered
        .listen((IosNotificationSettings settings) {
      print("Settings registered: $settings");
    });
    _firebaseMessaging.getToken().then((String token) {
      assert(token != null);
      setState(() {
        _homeScreenText = "Push Messaging token: $token";
      });
      print(_homeScreenText);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: const Text('Push Messaging Demo'),
        ),
        // For testing -- simulate a message being received
        floatingActionButton: FloatingActionButton(
          onPressed: () => _showItemDialog(<String, dynamic>{
            "data": <String, String>{
              "id": "2",
              "status": "out of stock",
            },
          }),
          tooltip: 'Simulate Message',
          child: const Icon(Icons.message),
        ),
        body: Material(
          child: Column(
            children: <Widget>[
              Center(
                child: Text(_homeScreenText),
              ),
              Row(children: <Widget>[
                Expanded(
                  child: TextField(
                      controller: _topicController,
                      onChanged: (String v) {
                        setState(() {
                          _topicButtonsDisabled = v.isEmpty;
                        });
                      }),
                ),
                FlatButton(
                  child: const Text("subscribe"),
                  onPressed: _topicButtonsDisabled
                      ? null
                      : () {
                          _firebaseMessaging
                              .subscribeToTopic(_topicController.text);
                          _clearTopicText();
                        },
                ),
                FlatButton(
                  child: const Text("unsubscribe"),
                  onPressed: _topicButtonsDisabled
                      ? null
                      : () {
                          _firebaseMessaging
                              .unsubscribeFromTopic(_topicController.text);
                          _clearTopicText();
                        },
                ),
              ])
            ],
          ),
        ));
  }

  void _clearTopicText() {
    setState(() {
      _topicController.text = "";
      _topicButtonsDisabled = true;
    });
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  runApp(
    MaterialApp(
      home: PushMessagingExample(),
    ),
  );
}
```

</details> 

```js
const functions = require('firebase-functions');

// // Create and Deploy Your First Cloud Functions
// // https://firebase.google.com/docs/functions/write-firebase-functions
//
// exports.helloWorld = functions.https.onRequest((request, response) => {
//  response.send("Hello from Firebase!");
// });


const admin = require('firebase-admin');
admin.initializeApp(functions.config().firebase);


const payload = {
    'notification': {
        'title': 'this is a title',
        'body': 'this is a body',

    },
    'data': {
        'click_action': 'FLUTTER_NOTIFICATION_CLICK',
        'id': '1',
        'status': 'done'
    }
};

exports.sendnotification = functions.https.onRequest((request, response) => {

    const tokens = request.query.fcm || "Unknown"
    response.send("Notification is sent to".concat(tokens));

    return admin.messaging().sendToDevice(tokens, payload);
});


```

**Comment by Salakar** [comment] 2021-05-06 13:39
Closing in favour of using the latest packages, as mentioned above.

**Closed by Salakar** 2021-05-06 13:39 UTC
Labels: plugin: messaging, type: documentation
