### ISSUE TITLE
Cloud Firestore Plugin Incompatibilty

### ISSUE THREAD

**Issue by CarltonK** [FirebaseExtended/flutterfire#2757] opened 2020-06-14 10:39 UTC
I encounter the following error when trying to build an apk. It seems that the plugin sms (0.2.0) is incompatible with androidX causing cloud firestore to fail

```
[ +855 ms] > Task :sms:verifyReleaseResources FAILED
[ +109 ms] FAILURE: Build failed with an exception.
[  +86 ms] * What went wrong:
[ +213 ms] Execution failed for task ':sms:verifyReleaseResources'.
[  +10 ms] > A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
[   +7 ms]    > 1 exception was raised by workers:
[   +9 ms]      com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
[   +4 ms]      C:\Users\USER-PC\.gradle\caches\transforms-2\files-2.1\73d97523cc97593d1afe3ee6b2453434\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource
android:attr/fontVariationSettings not found.
[   +9 ms]      C:\Users\USER-PC\.gradle\caches\transforms-2\files-2.1\73d97523cc97593d1afe3ee6b2453434\core-1.1.0\res\values\values.xml:142:5-173:25: AAPT: error: resource android:attr/ttcIndex not
found.
[  +13 ms] * Try:
[   +3 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[   +2 ms] * Get more help at https://help.gradle.org
[   +4 ms] BUILD FAILED in 2m 23s
[   +4 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +2 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +3 ms] See https://docs.gradle.org/6.1.1/userguide/command_line_interface.html#sec:command_line_warnings
[   +5 ms] 944 actionable tasks: 12 executed, 932 up-to-date
[ +434 ms] Running Gradle task 'assembleRelease'... (completed in 145.0s, longer than expected)
[  +15 ms] The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
[  +37 ms] Building plugin cloud_firestore...
[  +12 ms] Running Gradle task 'assembleAarRelease'...
[  +34 ms] "flutter apk" took 148,538ms.
The plugin cloud_firestore could not be built due to the issue above.

#0      throwToolExit (package:flutter_tools/src/base/common.dart:14:3)
#1      buildPluginsAsAar (package:flutter_tools/src/android/gradle.dart:773:7)
#2      _asyncErrorWrapperHelper.errorCallback (dart:async-patch/async_patch.dart:86:61)
#3      _rootRunBinary (dart:async/zone.dart:1204:38)
#4      _CustomZone.runBinary (dart:async/zone.dart:1093:19)
#5      _FutureListener.handleError (dart:async/future_impl.dart:155:20)
#6      Future._propagateToListeners.handleError (dart:async/future_impl.dart:694:47)
#7      Future._propagateToListeners (dart:async/future_impl.dart:715:24)
#8      Future._completeError (dart:async/future_impl.dart:534:5)
#9      Future._asyncCompleteError.<anonymous closure> (dart:async/future_impl.dart:582:7)
#10     _rootRun (dart:async/zone.dart:1184:13)
#11     _CustomZone.run (dart:async/zone.dart:1077:19)
#12     _CustomZone.runGuarded (dart:async/zone.dart:979:7)
#13     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1019:23)
#14     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#15     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#16     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#17     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

```
flutter doctor -v [Response]
[√] Flutter (Channel stable, v1.17.3, on Microsoft Windows [Version 10.0.18363.900], locale en-US)
    • Flutter version 1.17.3 at C:\Flutter\flutter
    • Framework revision b041144f83 (10 days ago), 2020-06-04 09:26:11 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\USER-PC\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.0)
    • VS Code at C:\Users\USER-PC\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

**Comment by TahaTesser** [comment] 2020-06-15 13:49
Hi @CarltonK 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/babariviere/flutter_sms/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Closed by TahaTesser** 2020-06-15 13:49 UTC
