### ISSUE TITLE
[firebase_crashlytics] Non-fatal exceptions are not reported until the next application restart.

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1138] opened 2019-10-13 19:44 UTC
We have a partner who is developing mobile apps using Flutter and Firebase, and currently use the firebase_crashlytics plugin.

In Flutter uncaught exceptions do not crash or kill the app so we are limited to reporting all issues as non-fatal. These non-fatal exceptions are not reported until the next application restart. This means we get reports of errors very late and in some cases it is possible that errors will never be reported as the SDK only keeps a finite collection to be sent upon app restart. We need reliable error reporting and we would like to continue to use Firebase for this purpose.

In the long term can you look into this problem and consider supporting Flutter as a first class use case?

In the short term is it possible to add an API that would allow to configure sending non-fatal errors immediate or at a regular interval?

**Comment by kroikie** [comment] 2019-10-13 19:44
@PartnerDevRel

The issue at https://github.com/flutter/flutter/issues/42202 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by tp** [comment] 2020-04-09 11:52
@kroikie As this request is directed more towards Crashlytics behavior and not the Flutter bridge, do you know if there is any interest from their side to change this?

I wasn't able to find any recent Firebase Crashlytics docs on this behavior, just this older quote

> To reduce your users' network traffic, Crashlytics batches logged exceptions together and sends them the next time the app launches. If you don't see logged exceptions in your Crashlytics web dashboard, try restarting your app!

Source: https://support.crashlytics.com/knowledgebase/articles/202805-logging-caught-exceptions

Another point to note:

> Note: Crashlytics only stores the most recent eight exceptions in a given app session. If your app throws more than eight exceptions in a session, older exceptions are lost.

Source: https://firebase.google.com/docs/crashlytics/customize-crash-reports-new-sdk?platform=ios

So it seems like Crashlytics is not a full replacement for tools like Sentry that can collect non-crash exceptions right away and without any limitations imposed by the platform.

**Comment by Ehesp** [comment] 2020-04-21 10:38
As @tp has mentioned, this is by design of Crashlytics and I don't believe there is anyway to change this, at least not in the scope of Flutter/FlutterFire.

I'll close this one down to reduce noise but happy to discuss any conversations about this.

**Closed by Ehesp** 2020-04-21 10:38 UTC
Labels: type: bug, type: enhancement
