### ISSUE TITLE
🐛 [firebase_messaging] onBackgroundMessage on iOs

### ISSUE THREAD

**Issue by adriancsbna** [FirebaseExtended/flutterfire#6112] opened 2021-05-11 17:52 UTC
Hi all.

I'm trying to get onBackgroundMessage to work in iOs, but I can't get it to work.

Notifications being onBackground or terminated arrive correctly, but the onBackgroundMessage method is never executed. On Android it works perfectly.

I use Flutter 2.0.6, firebase_core: ^1.1.0, firebase_messaging: ^9.1.3

In the Xcode capabilities I have marked in Background Modes: Background fetch, Remote notifications and Background processing.
It also has Push Notifications.

Do you know what I can be doing wrong?

Best regards

**Comment by phamduoc** [comment] 2021-05-12 03:35
i have same issue like that too

**Comment by markusaksli-nc** [comment] 2021-05-12 06:09
Hi @phamduoc 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
What exact device and iOS version is this happening on?
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) or see if the issue persists when you use the official example?
https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib
Thank you

**Comment by phamduoc** [comment] 2021-05-12 06:42
Hi @markusaksli-nc 
thank you and i would like to send my env info:

>flutter doctor -v
[✓] Flutter (Channel stable, 2.0.6, on macOS 11.2.3 20D91 darwin-x64, locale en-VN)
    • Flutter version 2.0.6 at .../development/flutter
    • Framework revision 1d9032c7e1 (12 days ago), 2021-04-29 17:37:58 -0700
    • Engine revision 05e680e202
    • Dart version 2.12.3
...
[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1
[✓] Connected device (2 available)
    • Duoc Pham’s iPhone (mobile) • ... • ios            • iOS 14.4.2
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 90.0.4430.212

> flutter pub deps -- --style=compact
dependencies:
- firebase_core 1.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.1.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]

transitive dependencies:
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.0.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]

> my device: iOS 14.4.2
please help me check it, thank you.

**Comment by phamduoc** [comment] 2021-05-14 06:52
hi @adriancsbna 
There are two types of FCM:
1. Notification message: These messages trigger the onMessage() callback only (mode foreground), not trigger the onBackgroundMessage() callback (mode backgroud, terminal)
2. Data message: These messages trigger both the onMessage() and onBackgroundMessage() callback (mode foreground and background)
So, my solutions is that send 2 messages (1 notification message and 1 data message).

**Comment by adriancsbna** [comment] 2021-05-14 14:27
Hi @phamduoc 

The notification I send has both types, it has a notification message and also data.
Did you say to separate the notifications? The data on one side and the notification message on the other?

Best regards

**Comment by phamduoc** [comment] 2021-05-17 04:52
> Hi @phamduoc
> 
> The notification I send has both types, it has a notification message and also data.
> Did you say to separate the notifications? The data on one side and the notification message on the other?
> 
> Best regards

that's right, you have to separate the notifications, one notification message that contains notification, one data message that contains data.
when the data message arrived, it will trigger onBackgroundMessage(), after that you read data message to get data in the onBackgroundMessage() method.

Example my code:
1. On backend:
- notification message:
{
    "to": "xyz",
    "notification": {
      "title": "there is a new message",
      "body": "A sent you a message"
    },
}
- data message:
{
    "to" : "xyz",
    "data" : {
        "badge":10
     },
    "content_available": true
}

2. On frontend (main.dart): please focus to comment line
**// callback when data message arrived in background**
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  if (message.data != null && message.data['badge'] != null) {
    int badge = int.parse(message.data['badge']);
    if (badge > 0) {
      FlutterAppBadger.updateBadgeCount(badge);
    } else {
      FlutterAppBadger.removeBadge();
    }
  }
}
...

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  await flutterLocalNotificationsPlugin.resolvePlatformSpecificImplementation<AndroidFlutterLocalNotificationsPlugin>()
      ?.createNotificationChannel(channel);

  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );

  await FirebaseMessaging.instance.requestPermission(
    alert: true,
    badge: true,
    sound: true,
    provisional: false
  );
  runApp(MyApp());
}

class _MyAppState extends State<MyApp> {
...
@override
  void initState() {
    super.initState();
    if (Platform.isIOS) {
      FirebaseMessaging.instance.requestPermission();
    }
    FirebaseMessaging.instance
        .getInitialMessage()
        .then((RemoteMessage message) {
      if (message != null) {
        print("Message received");
      }
    });
   
   **// callback when data message or notification message arrived in background**
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      **// proccess notification message**
      RemoteNotification notification = message.notification;
      AndroidNotification android = message.notification?.android;
      if (notification != null && android != null) {
        flutterLocalNotificationsPlugin.show(
          notification.hashCode,
          notification.title,
          notification.body,
          NotificationDetails(
            android: AndroidNotificationDetails(
              channel.id,
              channel.name,
              channel.description,
              icon: 'app_icon',
            ),
          ),
        );
      }
      
     **// process data message**
      if (message.data != null && message.data['badge'] != null) {
        int badge = int.parse(message.data['badge']);
        if (badge > 0) {
          FlutterAppBadger.updateBadgeCount(badge);
        } else {
          FlutterAppBadger.removeBadge();
        }
      }
    });

**Comment by markusaksli-nc** [comment] 2021-05-17 13:32
@adriancsbna Have you added the `content-available` key to your notification. Tested this with the official example with `firebase_messaging: ^9.1.4` and everything works as expected.

**Comment by adriancsbna** [comment] 2021-05-17 15:10
Hi @markusaksli-nc.

I haven't had time to test it yet, I will try between today and tomorrow.
From what I've seen, in the Firebase console it doesn't allow to add this content-available. Does the console not allow it, can only be done from the backend?
I want to use it for promotions, and the console allows me to bias users by many parameters.

Best regards

**Comment by tstarasinic** [comment] 2021-05-18 06:25
`content-available` partly solved my problem on ios when receiving silent notifications (only data notifications), now sometimes notification is shown sometimes not, there are some conditions that prevent silent notifications to show, like low data mode or battery saver. Does someone had the same os similar problem ?

**Comment by markusaksli-nc** [comment] 2021-05-18 08:11
Please read
https://firebase.flutter.dev/docs/messaging/usage#message-types
https://firebase.flutter.dev/docs/messaging/usage#low-priority-messages
and take a look at https://github.com/FirebaseExtended/flutterfire/issues/4611#issuecomment-757917877 for an example of how to send messages through the API instead of firebase console.

The official payload reference is at https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

Closing this since background messages without `content-available` will not wake the process and cannot trigger the background handler. This is the native behavior on iOS and we do not control it. FYI if you send data-only notifications the FCM v1 API will automatically add `content-available` for iOS.

**Closed by markusaksli-nc** 2021-05-18 08:11 UTC
Labels: Needs Attention, in triage, type: bug

**Comment by adriancsbna** [comment] 2021-05-18 08:17
Hi @markusaksli-nc 
I have not been able to test it yet, but the messages I send are not only data messages, they also have a notification with title and body.
When they arrive to Android, the onBackgroundMessage is executed perfectly and reads the data of that message, but not in iOs, onBackgroundMessage is never executed.

**Comment by markusaksli-nc** [comment] 2021-05-18 08:22
As mentioned if you are just sending from firebase console they likely do not have the `content-available` key because they also contain the `notification` key. You can get past this by using the API directly (which I provided some links to get started on).

**Comment by hasanzia1993** [comment] 2021-05-28 06:22
I have a similar issue, I also have content-available as well, everything works fine but if batter is below 10% or low power mode is turned on, onBackgroundMessage does not execute. It works fine if battery is charged above 20% for iPhone. In low power mode, background processing is turned off by Apple, is there  a workaround for it? I need to update the app's local database with new message content as it is a chat app, can't rely on user that their battery is above 20% and don't have low power mode turned one.

**Comment by MaheshKumarM-SCE** [comment] 2021-06-05 12:46
Hi @hasanzia1993 I have a problem. for me, onBackgroundMessage is working fine in Android but its working in iOS when the app is terminated. Can you please check if it works for you in iOS when the app is terminated.
