### ISSUE TITLE
🐛 [firebase_messaging] When sending notifications to IOS, No Response

### ISSUE THREAD

**Issue by pengw00** [FirebaseExtended/flutterfire#5706] opened 2021-04-08 17:48 UTC
Bug report
When sending notifications to IOS, nothing happens on the app.
The same message works when sending notifications to Android.

Steps to reproduce

Send a message to any IOS.
Nothing enters on FirebaseMessaging.onBackgroundMessage or FirebaseMessaging.onMessage.listen.
Expected behavior
Receiving remote notifications in IOS applications as in Android or iOS, where everything works.

**Comment by roufroufrouf** [comment] 2021-04-09 02:57
i have the same problem.

and the second is that getToken () always refreshes new tokens when reopening the app, even though I didn't delete the token. sad

**Comment by pengw00** [comment] 2021-04-09 05:44
> i have the same problem.
> 
> and the second is that getToken () always refreshes new tokens when reopening the app, even though I didn't delete the token. sad

I don't know if any body come across this issue, it is been a while since upgrade flutter 2.0.  I am not sure if my configuration is wrong or not, but android, it can trigger messages. any body got it works, letting me know pls, I have an app blocking a lot of changes we want to release but ..

**Comment by darshankawar** [comment] 2021-04-09 06:45
@pengw00 
Have you gone through the iOS integration document and confirm you've the setup correctly for it ?  

https://firebase.flutter.dev/docs/messaging/overview/#4-apple-integration and https://firebase.flutter.dev/docs/messaging/apple-integration/

**Comment by pengw00** [comment] 2021-04-10 03:37
> @pengw00
> Have you gone through the iOS integration document and confirm you've the setup correctly for it ?
> 
> https://firebase.flutter.dev/docs/messaging/overview/#4-apple-integration and https://firebase.flutter.dev/docs/messaging/apple-integration/

yes, I have checked the process many times since I upgrade to flutter 2.0 and use this plugin 9.0+ version, it is everyone is working only mine is not working?

**Comment by pengw00** [comment] 2021-04-10 03:39
> @darshankawar 
> Have you gone through the iOS integration document and confirm you've the setup correctly for it ?
> 
> https://firebase.flutter.dev/docs/messaging/overview/#4-apple-integration and https://firebase.flutter.dev/docs/messaging/apple-integration/

I saw this PR is merged, it is built and related to my issue? can you check please?

**Comment by markusaksli-nc** [comment] 2021-04-12 09:56
There have been two messaging versions since that PR was merged and it likely doesn't have anything to do with your issue. Have you requested permission for notifications on the device? Are the notifications sent successfully?

Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?

**Comment by tattivitorino** [comment] 2021-04-13 19:16
I'm having the same problem here after upgrading to flutter 2.0.. I was able to make it work on android but iOS doesnt work at all.. have tried all possible combinations of versions for firebase_core, firebase_messaging.. read the firebase docs and the migration docs.. 

here's my flutter doctor -v
```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-BR)
    • Flutter version 2.0.3 at /Users/tattivitorino/Tools/flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tattivitorino/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/tattivitorino/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/tattivitorino/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0
```

and my flutter pub deps -- --style=compact
```
Dart SDK 2.12.2
Flutter SDK 2.0.3
evom_app 1.0.0+1

dependencies:
- apple_sign_in 0.1.0 [flutter]
- autocomplete_textfield 1.7.3 [flutter]
- carousel_slider 3.0.0 [flutter]
- clipboard_manager 0.0.4 [flutter]
- config 1.0.0
- connectivity 3.0.2 [flutter meta connectivity_platform_interface connectivity_macos]
- cupertino_icons 1.0.2
- device_info 2.0.0 [flutter device_info_platform_interface]
- dotted_border 1.0.7 [flutter path_drawing]
- firebase_analytics 7.1.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 1.0.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 9.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_barcode_scanner 1.0.2 [flutter flutter_plugin_android_lifecycle]
- flutter_flavor 1.1.3 [flutter]
- flutter_local_notifications 5.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_masked_text 0.8.0 [flutter]
- flutter_secure_storage 4.1.0 [meta flutter]
- google_maps_flutter 0.5.26+4 [flutter flutter_plugin_android_lifecycle]
- google_sign_in 5.0.0 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- gson 0.1.4 [colorize]
- hidden_drawer_menu 2.0.1 [flutter]
- http 0.13.0 [http_parser meta path pedantic]
- intl 0.17.0 [clock path]
- location 4.1.1 [flutter location_platform_interface location_web meta]
- mask_text_input_formatter 1.2.1 [flutter]
- mockito 5.0.1 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- package_info 2.0.0 [flutter]
- progress_dialog 1.2.4 [flutter]
- provider 5.0.0 [collection flutter nested]
- qr_flutter 4.0.0 [flutter qr]
- screen 0.0.5 [flutter]
- url_launcher 6.0.2 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]

dev dependencies:
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _fe_analyzer_shared 18.0.0 [meta]
- analyzer 1.2.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.6.3 [analyzer async convert crypto glob logging meta path]
- built_collection 5.0.0
- built_value 8.0.3 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- colorize 2.0.0
- connectivity_macos 0.2.0 [flutter]
- connectivity_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.0.0 [typed_data]
- crypto 3.0.0 [collection typed_data]
- dart_style 1.3.14 [analyzer args path pub_semver source_span]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0 [clock collection]
- file 6.1.0 [meta path]
- firebase 9.0.0 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 2.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.0 [async collection file path pedantic string_scanner]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.1 [archive meta xml]
- js 0.6.3
- location_platform_interface 2.1.0 [flutter meta plugin_platform_interface]
- location_web 3.0.0 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logging 1.0.0
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- package_config 2.0.0 [path]
- path 1.8.0
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- pedantic 1.11.0
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pub_semver 2.0.0 [collection]
- qr 2.0.0 [meta]
- quiver 3.0.0 [matcher]
- sky_engine 0.0.99
- source_gen 0.9.10+3 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0-nullsafety.0 [path]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- xml 5.0.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

**Comment by markusaksli-nc** [comment] 2021-04-14 10:06
@tattivitorino What exactly are you having issues with? Are the notifications not received by the device or do the streams not fire as expected?

I'm going to reccommend the same that you try to run just the official example code to see if the issue could be in your code.

https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib

If you have already followed the documentation this might not matter but make sure you have carefully done everything in https://firebase.flutter.dev/docs/messaging/apple-integration since iOS notification now only go through APNs so it has to work for them to be received.

**Comment by tattivitorino** [comment] 2021-04-14 18:31
@markusaksli-nc thx for the reply..
This project has been upgraded to Flutter 2.0 and we already had all apple requirements setup.. push worked before the upgrade. 
I am trying to receive a test notification sent from the firebase UI.. but the device does not receive anything at all.. 

I even tried a new project totally clean with only the firebase setup where I followed carefully all instructions, had all certificates properly installed and uploaded the APNS key to firebase, but nothing happens on my device..

No changes were made in the AppDelegate.swift code as the docs say and I am able to retrieve both the APNS token and the FCM token.

Please see all info in my system for this project (not the same I posted above):

flutter doctor -v
```
[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-BR)
    • Flutter version 2.0.3 at /Users/tattivitorino/Tools/flutter
    • Framework revision 4d7946a68d (4 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/tattivitorino/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/tattivitorino/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/tattivitorino/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 51.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.55.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • SM A105M (mobile)                • RQ8N206FFNZ                              • android-arm    • Android 10 (API 29)
    • Tatti Vitorino Iphone 7 (mobile) • add7277fe85425530dd4e56429d63f436af836e3 • ios            • iOS 14.1
    • macOS (desktop)                  • macos                                    • darwin-x64     • Mac OS X 10.15.7 19H2 darwin-x64
    • Chrome (web)                     • chrome                                   • web-javascript • Google Chrome 70.0.3538.77

• No issues found!
```

flutter pub deps -- --style=compact
```
Dart SDK 2.12.2
Flutter SDK 2.0.3
push_app 1.0.0+1

dependencies:
- cupertino_icons 1.0.2
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_local_notifications 5.0.0+1 [flutter flutter_local_notifications_platform_interface platform timezone]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

my main.dart
I made it really simple so I could just try to receive something, but nothing happens when I send the notification through the Firebase UI using the fcm token retrieved from the code.. 

```
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter_local_notifications/flutter_local_notifications.dart';

// Define a top-level named handler which background/terminated messages will
/// call.
///
/// To verify things are working, check out the native platform logs.
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  // If you're going to use other Firebase services in the background, such as Firestore,
  // make sure you call `initializeApp` before using other Firebase services.
  await Firebase.initializeApp();
  print('BG MESSAGE: ${message.messageId}');
}

/// Initialize the [FlutterLocalNotificationsPlugin] package.
final FlutterLocalNotificationsPlugin flutterLocalNotificationsPlugin =
    FlutterLocalNotificationsPlugin();

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  print('FB INITIALIZED');
  // Set the background messaging handler early on, as a named top-level function
  FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

  /// Update the iOS foreground notification presentation options to allow
  /// heads up notifications.
  await FirebaseMessaging.instance.setForegroundNotificationPresentationOptions(
    alert: true,
    badge: true,
    sound: true,
  );
  print('IOS FGOPTIONS OK');

  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Messaging Example App',
      theme: ThemeData.dark(),
      routes: {
        '/': (context) => MyHomePage(),
      },
    );
  }
}

class MyHomePage extends StatefulWidget {
  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  String _token;

  @override
  void initState() {
    super.initState();
    FirebaseMessaging.instance
        .getInitialMessage()
        .then((RemoteMessage message) {
      if (message != null) {
        print('GETINITIALMESSAGE: ${message.messageId}');
      }
    });

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print('FG MESSAGE: ${message.messageId}');
    });

    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('OPENED MESSAGE ${message.messageId}!');
    });

    _retrieveToken();
  }

  void _retrieveToken() {
    FirebaseMessaging.instance.getToken().then((token) {
      print('FCM TOKEN: $token');
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Push App',
        theme: ThemeData(
          primarySwatch: Colors.green,
          accentColor: Colors.greenAccent,
        ),
        home: Scaffold(
          appBar: AppBar(
            title: Text('Home'),
          ),
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                Text(
                  'Push Initialised',
                ),
              ],
            ),
          ), // This trailing comma makes auto-formatting nicer for build methods.
        ));
  }
}
```

**Comment by markusaksli-nc** [comment] 2021-04-15 12:26
Have you tried sending the notification through the API directly to the FCM token or directly through APNs?
Take a look at https://github.com/FirebaseExtended/flutterfire/issues/4611#issuecomment-757917877
I ran the code you provided with the latest
```yaml
  firebase_core: ^1.0.3
  firebase_messaging: ^9.1.1
  flutter_local_notifications: ^5.0.0+1
```
and it worked as expected however there isn't a call to `FirebaseMessaging.instance.requestPermission` anywhere in your code. This is why I recommended you take a look at the official example.

**Comment by tattivitorino** [comment] 2021-04-15 14:38
@markusaksli-nc 
I was trying through the Firebase UI, Cloud Messaging / Send test message! It should work, shouldnt it?
I copied all the /lib from the example into my project, ran it but nothing happens.. I'm still trying through the Firebase UI as I could not get your suggestion above #4611 to work..

**Comment by pengw00** [comment] 2021-04-16 05:42
I had checked several times for the configuration, but I don't think I miss anything. @markusaksli-nc  do you have any app works with flutter 2.0 with firebase_messaging. I just really confused, we are waiting this to release our changes

**Comment by pengw00** [comment] 2021-04-16 05:52
> @markusaksli-nc
> I was trying through the Firebase UI, Cloud Messaging / Send test message! It should work, shouldnt it?
> I copied all the /lib from the example into my project, ran it but nothing happens.. I'm still trying through the Firebase UI as I could not get your suggestion above #4611 to work..

@tattivitorino  since your app messaging works in android, did you get any value from data map of RemoteMessage?  I didnt get any data from the data ```this.data = const <String, dynamic>{},```, before that 1.0 is working, now come to a disaster @markusaksli-nc

**Comment by markusaksli-nc** [comment] 2021-04-16 14:09
@pengw00 I'm assuming you have requested and allowed notifications for the app?

@tattivitorino Sending through Firebase UI should be fine, it's just much easier to use node. You should be able to just run the provided JS code once you get the dependencies through `npm`.

**Comment by pengw00** [comment] 2021-04-18 16:34
> @pengw00 I'm assuming you have requested and allowed notifications for the app?
> 
> @tattivitorino Sending through Firebase UI should be fine, it's just much easier to use node. You should be able to just run the provided JS code once you get the dependencies through `npm`.

yes, that has been allowed.

**Comment by markusaksli-nc** [comment] 2021-04-23 12:48
@tattivitorino Is this still an issue? Have you tried sending the notification directly to the fcm token using Firebase Admin SDK or through a curl request?

**Comment by pengw00** [comment] 2021-04-25 17:30
> @pengw00 @tattivitorino Is this still an issue? Have you tried sending the notification directly to the fcm token using Firebase Admin SDK or through a curl request?

can you elaborate in more details? I don't understand. I actually get token from firebase instance and send to the backend side. code as below:
```
 String token = await _firebaseMessaging.getToken();
    print("fdfdf4343243");
    print(token);
```
But when I try to get the apn key from firebase instance, it returns null
  ```String apnToken = await _firebaseMessaging.getAPNSToken();```
not sure it is affect the messaging coming or not

**Comment by pengw00** [comment] 2021-04-25 17:36
@tattivitorino ```
_firebaseMessaging.getInitialMessage()
        .then((RemoteMessage message) {
      print("init message");
      if (message != null) {
        print("init not null message");
      }
    });
```
in android the message is not null, but in ios, the message is null, idk how other people to resolve this...

**Comment by awaik** [comment] 2021-04-26 05:23
Maybe it could help to figure out the bug reason.
I also faced this issue after Flutter upgrade to 2.0 and the plugin to `firebase_messaging: ^9.1.2`.
I have 2 cases:
1. It is strange - pushes stopped working on the real device when I run the app from the laptop. 
2. But they work if I uploading the app to the TestFlight.
Before this upgrade pushes worked on the 1st case as well.
So, for debugging, I now have to use a real device with Android.

**Comment by falc0n33** [comment] 2021-04-26 08:43
@pengw00 @awaik 
I had similar problems after the update to the flutter 2.0 and firebase_messaging: 8.+.
Android still works well on the emulator, but the iOS simulator has no messages coming.
The official documentation says "IOS SIMULATORS: FCM via APNs does not work on iOS Simulators. To receive messages & notifications a real device is required."
So I ran the app on the iPhone 10 and now messages are coming. Try to test your app on a real iOS device.

**Comment by awaik** [comment] 2021-04-26 09:36
> @pengw00 @awaik
> I had similar problems after the update to the flutter 2.0 and firebase_messaging: 8.+.
> Android still works well on the emulator, but the iOS simulator has no messages coming.
> The official documentation says "IOS SIMULATORS: FCM via APNs does not work on iOS Simulators. To receive messages & notifications a real device is required."
> So I ran the app on the iPhone 10 and now messages are coming. Try to test your app on a real iOS device.

I wrote that `pushes stopped working on the REAL device when I run the app from the laptop`

**Comment by pengw00** [comment] 2021-04-27 22:36
> > @pengw00 @awaik
> > I had similar problems after the update to the flutter 2.0 and firebase_messaging: 8.+.
> > Android still works well on the emulator, but the iOS simulator has no messages coming.
> > The official documentation says "IOS SIMULATORS: FCM via APNs does not work on iOS Simulators. To receive messages & notifications a real device is required."
> > So I ran the app on the iPhone 10 and now messages are coming. Try to test your app on a real iOS device.
> 
> I wrote that `pushes stopped working on the REAL device when I run the app from the laptop`

@awaik  so yours still not working in app has been released in app store? @awaik , mine didn't work in testflight either.  do you have any advice@markusaksli-nc

**Comment by pengw00** [comment] 2021-04-27 22:36
> @pengw00 @awaik
> I had similar problems after the update to the flutter 2.0 and firebase_messaging: 8.+.
> Android still works well on the emulator, but the iOS simulator has no messages coming.
> The official documentation says "IOS SIMULATORS: FCM via APNs does not work on iOS Simulators. To receive messages & notifications a real device is required."
> So I ran the app on the iPhone 10 and now messages are coming. Try to test your app on a real iOS device.

did you change any configuration about apn key after flutter 2.0?

**Comment by markusaksli-nc** [comment] 2021-04-28 13:33
I'm still not seeing any issues with the package running the official example code on iOS with the latest version. Everything seems to be working as expected.

I understand that this seems to be a genuine issue report here but unless you provide a specific example code that fails or show that the official example code doesn't work for you even with all of the setup done correctly the issue is just too ambiguous. The easiest way to test if you've done the setup correctly is to send a notification directly to the device token you receive through the API and to print the response to see if it works (such as with the previously mentioned https://github.com/FirebaseExtended/flutterfire/issues/4611#issuecomment-757917877).

If you just send a notification to the entire package identifier through firebase console and don't receive it on your device there are any number of user errors in the setup that could cause it so we just have no idea what to fix or where the issue could be coming from.

**Comment by pengw00** [comment] 2021-05-04 18:46
My issue is resolved after v9.1.3 in **test flight & app store**, not so clear what is going on, so I am going to closed this issue, anyone have problems can ping me.

**Comment by mustafa-707** [comment] 2021-05-05 03:11
> @tattivitorino
> 
> ```
> _firebaseMessaging.getInitialMessage()
>         .then((RemoteMessage message) {
>       print("init message");
>       if (message != null) {
>         print("init not null message");
>       }
>     });
> ```
> 
> in android the message is not null, but in ios, the message is null, idk how other people to resolve this...

I'm facing same problem with real devices iOS , I tried everything in flutterfire and this firebase_messaging docs but nothing happens , I'm using firebase_messaging  : ^8.0.0-dev.15 and cant go to the new one cause it need flutter 2 which i have much problem with it

**Comment by markusaksli-nc** [comment] 2021-05-05 10:53
Closing based on https://github.com/FirebaseExtended/flutterfire/issues/5706#issuecomment-832163575

**Closed by markusaksli-nc** 2021-05-05 10:53 UTC
Labels: Needs Attention, type: bug

**Comment by pengw00** [comment] 2021-06-03 04:39
> > @tattivitorino
> > ```
> > _firebaseMessaging.getInitialMessage()
> >         .then((RemoteMessage message) {
> >       print("init message");
> >       if (message != null) {
> >         print("init not null message");
> >       }
> >     });
> > ```
> > 
> > 
> > in android the message is not null, but in ios, the message is null, idk how other people to resolve this...
> 
> I'm facing same problem with real devices iOS , I tried everything in flutterfire and this firebase_messaging docs but nothing happens , I'm using firebase_messaging : ^8.0.0-dev.15 and cant go to the new one cause it need flutter 2 which i have much problem with it

you might need to check the config in Xcode IDE for background messaging.

**Comment by pengw00** [comment] 2021-06-03 04:42
I finally got what's going on for the no response in IOS, need to enable background mode for 9.0+
![Screen Shot 2021-06-02 at 11 41 39 PM](https://user-images.githubusercontent.com/6376970/120588100-37c89800-c3fc-11eb-8445-460ebf5eda7e.png)
