### ISSUE TITLE
[firebase_auth] Reset Password Email Not Localized

### ISSUE THREAD

**Issue by kevin-induro** [FirebaseExtended/flutterfire#6496] opened 2021-06-28 15:46 UTC
In my Android app, using the `FirebaseAuth.instance.setLanguageCode` to set the language code successfully changes the language for email verification emails, but does not change the language for password reset emails.

**Comment by darshankawar** [comment] 2021-06-29 08:21
@kevin-induro 
Can you provide `flutter doctor -v`, `flutter pub deps -- --style=compact` and a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows this issue ?
Thanks.

**Comment by kevin-induro** [comment] 2021-07-08 01:11
While easy to provide the requested outputs, it will take longer to get the minimal reproducible example as I only have so much time to work on this project.

[flutter-doctor.txt](https://github.com/FirebaseExtended/flutterfire/files/6780788/flutter-doctor.txt)
[pub-deps.txt](https://github.com/FirebaseExtended/flutterfire/files/6780789/pub-deps.txt)

**Comment by markusaksli-nc** [comment] 2021-07-08 11:11
Hi @kevin-induro 
What language did this issue occur with? I can't reproduce it on `firebase_auth: ^2.0.0`. Both email are in the desired language.
Thank you

**Comment by kevin-induro** [comment] 2021-07-12 12:25
I believe I was trying in French and Spanish, but I can't imagine this being language dependent.

That said, as my pub-deps said, I'm running `firebase_auth: 1.1.3`. Since it sounds like this has been fixed in later versions, I can certainly try to upgrade.

**Comment by markusaksli-nc** [comment] 2021-07-13 09:45
Let me know if it persists on the latest version, I'll close this for now since I couldn't reproduce it

**Closed by markusaksli-nc** 2021-07-13 09:45 UTC
Labels: Needs Attention, in triage
