### ISSUE TITLE
🐛 [firebase_admob] Interstitial ads cannot be closed on iOS

### ISSUE THREAD

**Issue by talent-apps** [FirebaseExtended/flutterfire#3946] opened 2020-10-24 09:39 UTC
## Bug report

Some interstitial ads on iOS cannot be closed. It seems like the issue occurs when the "X" button is located on the iOS status bar. This results in a very bad user experience since users have to force quit the app, lose their changes and relaunch the app.
Example from an iPhone Xs Max device:
![Interstitial_ad_bug](https://user-images.githubusercontent.com/48091135/97078518-658f6800-15f5-11eb-85dd-0ffc3b0c7f45.PNG)

### Steps to reproduce

1. Display an interstitial ad with "X" button in the iOS status bar area.
2. Try to close the app by pressing the "X" button.

### Expected behavior

Interstitial ads can be closed with no problems.

**Comment by Tibbs** [comment] 2020-10-26 11:12
I have the same issue for most of my apps, but not all. Which is strange.
From what viewcontroller do you display the ad?
Mine is a navigationViewController

**Comment by markusaksli-nc** [comment] 2020-10-26 13:03
Hi @talent-apps 
Can you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Is anything relevant logged with `flutter run -v` when you try to close the ad?
Thank you

**Comment by igoriuz** [comment] 2020-10-26 15:54
I've experienced the same issue on iOS

**Comment by avbk** [comment] 2020-10-26 15:56
This problem ist not only relevant on iOS but on any device with curved edges. For example I can reproduce this behaviour on a Google Pixel 4 as well. 

The interstitial does not respect any SafeAreas and thus sometimes cannot be closed by the user. I don't think this problem is related to the flutter version or any logs @markusaksli-nc, it's just a rendering problem.

**Comment by markusaksli-nc** [comment] 2020-10-27 07:21
My bad, in this case, this is just a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/3090

Please follow the mentioned issue for updates and comment if you have anything useful to add to the discussion.

Closing this as duplicate.

**Closed by markusaksli-nc** 2020-10-27 07:21 UTC
Labels: blocked: customer-response, type: bug
