### ISSUE TITLE
FIREBASE: CLOUD_FIRESTORE Plugin project not found

### ISSUE THREAD

**Issue by xdagee** [FirebaseExtended/flutterfire#2879] opened 2020-07-02 01:31 UTC
**Describe the bug**
Running Gradle task 'assembleDebug'...
Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :cloud_firestore_web not found. Please update settings.gradle.

**To Reproduce**
1. add cloud_firestore: ^0.13.7 to the pubspec.yaml file
2. get packages
3. run project

**Expected behavior**
 

**Additional context**
...

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[√] Flutter (Channel beta, 1.19.0-4.2.pre, on Microsoft Windows [Version 10.0.19042.330], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 4.0)
[√] VS Code (version 1.46.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-07-06 11:51
Clsoing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2599#issuecomment-632651771 https://github.com/FirebaseExtended/flutterfire/issues/2796

**Closed by TahaTesser** 2020-07-06 11:51 UTC
