### ISSUE TITLE
In IOS only, Firebase Core error: No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core

### ISSUE THREAD

**Issue by YuvarajaCPR** [FirebaseExtended/flutterfire#7343] opened 2021-11-11 07:01 UTC
**My case**
I have native IOS and native Android project separately
Required to add flutter module in IOS project
Create button in IOS project and call flutter module.
I have situation to use cloud firebase in flutter module
so I adding required firebase plugin dependency in pubspec.yaml (eg. firebase_core, cloud_firebase)
Add 'await Firebase.initializeApp()' in my flutter main function.
When I run my application and It calling flutter main, then this issue arise 'No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core'

```
**IOS Project calling function like**
FlutterViewController* flutterViewController =
[[FlutterViewController alloc] initWithProject:nil
initialRoute:routeStr
nibName:nil
bundle:nil
];
flutterViewController.modalPresentationStyle = UIModalPresentationCustom;
[self presentViewController:flutterViewController animated:YES completion:nil];

**Flutter Main function**
Future main() async{
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();
runApp(MyAppState());
}
```

So need a solution for my case, but In Android project it is working fine

**Comment by darshankawar** [comment] 2021-11-11 12:15
@YuvarajaCPR 
Can you provide `flutter doctor -v`, `pubspec.yaml` and a complete minimal code sample that we can directly use to verify this issue ? or you may create a demo app (that replicates the issue), push it to github and share repo link here that we can clone .
Thanks.

**Comment by YuvarajaCPR** [comment] 2021-11-11 12:52
**Flutter doctor**
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-x64, locale en-GB)
    • Flutter version 2.5.3 at /Users/yuvarajacpr/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/yuvarajacpr/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/yuvarajacpr/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.27.0

[✓] Connected device (2 available)
    • SM J600G (mobile) • 520096ffc0c25517 • android-arm    • Android 10 (API 29)
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 95.0.4638.69
    ! Device emulator-5554 is offline.
    ! Error: iPhone is not connected. Xcode will continue when iPhone is connected. (code -13)

• No issues found!


**pubspec.yaml**
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  bubble: ^1.2.1
  flutter_svg: ^0.21.0-nullsafety.0
  get: ^4.3.8
  dio: ^4.0.1
  http: ^0.13.4
  fluttertoast: ^8.0.8
  firebase_core: ^1.8.0
  intl: ^0.17.0
  firebase_auth: ^3.1.4
  cloud_firestore: ^2.5.4
  cached_network_image:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.conferenceapp_flutter
    iosBundleIdentifier: com.conferenceappFlutter

**Comment by darshankawar** [comment] 2021-11-11 13:22
> complete minimal code sample that we can directly use to verify this issue ? or you may create a demo app (that replicates the issue), push it to github and share repo link here that we can clone .

@YuvarajaCPR

**Comment by YuvarajaCPR** [comment] 2021-11-16 06:14
**Github Link **

https://github.com/YuvarajaCPR/testfirebase.

Also use README.file in the project

**Comment by darshankawar** [comment] 2021-11-16 10:39
@YuvarajaCPR 
Cloned the repo and followed the instructions, but getting an error while running `pod install`:

```
### Error

RuntimeError - [Xcodeproj] Unknown object version.
/Library/Ruby/Gems/2.6.0/gems/xcodeproj-1.19.0/lib/xcodeproj/project.rb:227:in `initialize_from_file'

```

The error you are getting `no implementation found`, usually indicates that the method isn't registered before it can be called.

Can you try below steps and see if it works ?

```
rm -rf build
rm -rf Pods
rm -rf Podfile.lock
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
pod cache clean --all
flutter clean
flutter pub get
pod repo update
pod install

```

**Comment by YuvarajaCPR** [comment] 2021-11-22 04:36
Above steps cannot work for me

**Comment by darshankawar** [comment] 2021-11-29 06:33
Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4455. Please follow-up in linked issue for further updates.

**Closed by darshankawar** 2021-11-29 06:33 UTC
Labels: type: bug, Needs Attention, in triage
