### ISSUE TITLE
[cloud_firestore] Stream is empty when on iOS but not Android

### ISSUE THREAD

**Issue by sgalway00** [FirebaseExtended/flutterfire#4267] opened 2020-11-30 03:44 UTC
## Bug report

I can successfully read and write to a cloud firestore database from within my flutter app. However, when running on an iOS simulator (or real device) I cannot listen to a stream for realtime changes to a document. No errors or exceptions are thrown when listening to the stream. The stream exists, it just doesn't have data in it. This problem DOES NOT exist when running on an Android emulator.

### Steps to reproduce

```
final athletePos = Provider<GPSPoint>((ref) {
  GPSPoint _curPos;

  print('athletePos is active');

  Stream _docStream = FirebaseFirestore.instance.collection('Athlete1').doc('currentPosition').snapshots();

  if (_docStream.isBroadcast == true) {
    print('Stream is broadcasting');
  }

  _docStream.listen((event) {
    print('athletePos stream event received');
    _curPos = GPSPoint.fromFSMap(event.data());
  });

  return _curPos;
});
```
### Expected behavior

Expect both print statements to fire.  On iOS only "Stream is broadcasting" will fire.  On Android, both will fire.

---

### Flutter doctor
```

[✓] Flutter (Channel beta, 1.24.0-10.2.pre, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-US)
    • Flutter version 1.24.0-10.2.pre at /Users/sgalway/development/flutter
    • Framework revision 022b333a08 (11 days ago), 2020-11-18 11:35:09 -0800
    • Engine revision 07c1eed46b
    • Dart version 2.12.0 (build 2.12.0-29.10.beta)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/sgalway/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] IntelliJ IDEA Community Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 47.1.3
    • Dart plugin version 201.7846.93

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • iPhone 11 Pro (mobile) • 21B0C3BA-D8B9-4AF2-81A5-FC8176E49F24 • ios            •
      com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)
    • Web Server (web)       • web-server                           • web-javascript • Flutter Tools
    • Chrome (web)           • chrome                               • web-javascript • Google Chrome 86.0.4240.198

• No issues found!
```

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0-29.10.beta
Flutter SDK 1.24.0-10.2.pre
yonav2 0.0.1+1
|-- auto_size_text 2.1.0
|   '-- flutter...
|-- background_locator 1.2.2+1
|   '-- flutter...
|-- battery 1.0.7
|   |-- battery_platform_interface 1.0.0
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- flutter...
|   '-- meta...
|-- bloc 4.0.0
|   '-- meta...
|-- build_runner 1.10.6
|   |-- args...
|   |-- async...
|   |-- build...
|   |-- build_config 0.4.3
|   |   |-- checked_yaml 1.0.2
|   |   |   |-- json_annotation...
|   |   |   |-- source_span...
|   |   |   '-- yaml...
|   |   |-- json_annotation 3.1.1
|   |   |-- meta...
|   |   |-- path...
|   |   |-- pubspec_parse...
|   |   '-- yaml...
|   |-- build_daemon 2.1.4
|   |   |-- built_collection 4.3.2
|   |   |   |-- collection...
|   |   |   '-- quiver...
|   |   |-- built_value 7.1.0
|   |   |   |-- built_collection...
|   |   |   |-- collection...
|   |   |   |-- fixnum 0.10.11
|   |   |   '-- quiver...
|   |   |-- http_multi_server...
|   |   |-- logging...
|   |   |-- path...
|   |   |-- pedantic...
|   |   |-- pool...
|   |   |-- shelf...
|   |   |-- shelf_web_socket...
|   |   |-- stream_transform...
|   |   |-- watcher...
|   |   '-- web_socket_channel...
|   |-- build_resolvers 1.4.3
|   |   |-- analyzer...
|   |   |-- build...
|   |   |-- crypto...
|   |   |-- graphs...
|   |   |-- logging...
|   |   |-- meta...
|   |   |-- package_config...
|   |   |-- path...
|   |   |-- pool...
|   |   '-- pub_semver...
|   |-- build_runner_core 6.1.1
|   |   |-- async...
|   |   |-- build...
|   |   |-- build_config...
|   |   |-- build_resolvers...
|   |   |-- collection...
|   |   |-- convert...
|   |   |-- crypto...
|   |   |-- glob...
|   |   |-- graphs...
|   |   |-- json_annotation...
|   |   |-- logging...
|   |   |-- meta...
|   |   |-- package_config...
|   |   |-- path...
|   |   |-- pedantic...
|   |   |-- pool...
|   |   |-- timing...
|   |   |-- watcher...
|   |   '-- yaml...
|   |-- code_builder 3.5.0
|   |   |-- built_collection...
|   |   |-- built_value...
|   |   |-- collection...
|   |   |-- matcher...
|   |   '-- meta...
|   |-- collection...
|   |-- crypto...
|   |-- dart_style 1.3.10
|   |   |-- analyzer...
|   |   |-- args...
|   |   |-- path...
|   |   '-- source_span...
|   |-- glob 1.2.0
|   |   |-- async...
|   |   |-- collection...
|   |   |-- node_io 1.2.0
|   |   |   |-- file 5.2.1
|   |   |   |   |-- intl...
|   |   |   |   |-- meta...
|   |   |   |   '-- path...
|   |   |   |-- node_interop 1.2.1
|   |   |   |   '-- js...
|   |   |   '-- path...
|   |   |-- path...
|   |   |-- pedantic...
|   |   '-- string_scanner...
|   |-- graphs 0.2.0
|   |-- http_multi_server 2.2.0
|   |   '-- async...
|   |-- io 0.3.4
|   |   |-- charcode...
|   |   |-- meta...
|   |   |-- path...
|   |   '-- string_scanner...
|   |-- js 0.6.3-nullsafety.3
|   |-- logging 0.11.4
|   |-- meta...
|   |-- mime 0.9.7
|   |-- path...
|   |-- pedantic...
|   |-- pool 1.4.0
|   |   |-- async...
|   |   '-- stack_trace...
|   |-- pub_semver 1.4.4
|   |   '-- collection...
|   |-- pubspec_parse 0.1.5
|   |   |-- checked_yaml...
|   |   |-- json_annotation...
|   |   |-- pub_semver...
|   |   '-- yaml...
|   |-- shelf 0.7.9
|   |   |-- async...
|   |   |-- collection...
|   |   |-- http_parser...
|   |   |-- path...
|   |   |-- stack_trace...
|   |   '-- stream_channel...
|   |-- shelf_web_socket 0.2.3
|   |   |-- shelf...
|   |   |-- stream_channel...
|   |   '-- web_socket_channel...
|   |-- stack_trace 1.10.0-nullsafety.6
|   |   '-- path...
|   |-- stream_transform 1.2.0
|   |-- timing 0.1.1+2
|   |   '-- json_annotation...
|   |-- watcher 0.9.7+15
|   |   |-- async...
|   |   |-- path...
|   |   '-- pedantic...
|   |-- web_socket_channel 1.1.0
|   |   |-- async...
|   |   |-- crypto...
|   |   '-- stream_channel...
|   '-- yaml 2.2.1
|       |-- charcode...
|       |-- collection...
|       |-- source_span...
|       '-- string_scanner...
|-- cloud_firestore 0.14.3+1
|   |-- cloud_firestore_platform_interface 2.2.0
|   |   |-- collection...
|   |   |-- firebase_core...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- plugin_platform_interface...
|   |-- cloud_firestore_web 0.2.1+1
|   |   |-- cloud_firestore_platform_interface...
|   |   |-- firebase_core...
|   |   |-- firebase_core_web...
|   |   |-- flutter...
|   |   |-- flutter_web_plugins 0.0.0
|   |   |   |-- characters...
|   |   |   |-- collection...
|   |   |   |-- flutter...
|   |   |   |-- js...
|   |   |   |-- meta...
|   |   |   |-- typed_data...
|   |   |   '-- vector_math...
|   |   |-- http_parser 3.1.4
|   |   |   |-- charcode...
|   |   |   |-- collection...
|   |   |   |-- source_span...
|   |   |   |-- string_scanner...
|   |   |   '-- typed_data...
|   |   |-- js...
|   |   '-- meta...
|   |-- firebase_core 0.5.2+1
|   |   |-- firebase_core_platform_interface...
|   |   |-- firebase_core_web 0.2.1+1
|   |   |   |-- firebase_core_platform_interface...
|   |   |   |-- flutter...
|   |   |   |-- flutter_web_plugins...
|   |   |   |-- js...
|   |   |   '-- meta...
|   |   |-- flutter...
|   |   |-- meta...
|   |   '-- quiver...
|   |-- firebase_core_platform_interface 2.1.0
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- plugin_platform_interface...
|   |   '-- quiver...
|   |-- flutter...
|   |-- meta...
|   '-- quiver 2.1.5
|       |-- matcher...
|       '-- meta...
|-- cupertino_icons 0.1.3
|-- direct_select_flutter 1.0.6
|   |-- cupertino_icons...
|   |-- flutter...
|   '-- rect_getter 0.1.0
|       '-- flutter...
|-- flutter 0.0.0
|   |-- characters 1.1.0-nullsafety.5
|   |-- collection 1.15.0-nullsafety.5
|   |-- meta 1.3.0-nullsafety.6
|   |-- sky_engine 0.0.99
|   |-- typed_data 1.3.0-nullsafety.5
|   |   '-- collection...
|   '-- vector_math 2.1.0-nullsafety.5
|-- flutter_riverpod 0.12.1
|   |-- collection...
|   |-- flutter...
|   |-- meta...
|   |-- riverpod 0.12.1
|   |   |-- collection...
|   |   |-- freezed_annotation 0.12.0
|   |   |   |-- collection...
|   |   |   |-- json_annotation...
|   |   |   '-- meta...
|   |   |-- meta...
|   |   '-- state_notifier...
|   '-- state_notifier 0.6.0
|       '-- meta...
|-- flutter_slidable 0.5.7
|   '-- flutter...
|-- flutter_test 0.0.0
|   |-- async...
|   |-- boolean_selector 2.1.0-nullsafety.3
|   |   |-- source_span...
|   |   '-- string_scanner...
|   |-- characters...
|   |-- charcode 1.2.0-nullsafety.3
|   |-- clock 1.1.0-nullsafety.3
|   |-- collection...
|   |-- fake_async 1.2.0-nullsafety.3
|   |   |-- clock...
|   |   '-- collection...
|   |-- flutter...
|   |-- matcher 0.12.10-nullsafety.3
|   |   '-- stack_trace...
|   |-- meta...
|   |-- path...
|   |-- source_span 1.8.0-nullsafety.4
|   |   |-- charcode...
|   |   |-- collection...
|   |   |-- path...
|   |   '-- term_glyph...
|   |-- stack_trace...
|   |-- stream_channel 2.1.0-nullsafety.3
|   |   '-- async...
|   |-- string_scanner 1.1.0-nullsafety.3
|   |   |-- charcode...
|   |   '-- source_span...
|   |-- term_glyph 1.2.0-nullsafety.3
|   |-- test_api 0.2.19-nullsafety.6
|   |   |-- async...
|   |   |-- boolean_selector...
|   |   |-- collection...
|   |   |-- matcher...
|   |   |-- meta...
|   |   |-- path...
|   |   |-- source_span...
|   |   |-- stack_trace...
|   |   |-- stream_channel...
|   |   |-- string_scanner...
|   |   '-- term_glyph...
|   |-- typed_data...
|   '-- vector_math...
|-- geolocator 6.1.7
|   |-- flutter...
|   '-- geolocator_platform_interface 1.0.8
|       |-- flutter...
|       |-- meta...
|       |-- plugin_platform_interface...
|       '-- vector_math...
|-- get 3.17.1
|   '-- flutter...
|-- google_fonts 1.1.1
|   |-- crypto...
|   |-- flutter...
|   |-- http 0.12.2
|   |   |-- http_parser...
|   |   |-- path...
|   |   '-- pedantic...
|   |-- path_provider...
|   '-- pedantic 1.9.2
|       '-- meta...
|-- google_maps_flutter 1.0.6
|   |-- flutter...
|   |-- flutter_plugin_android_lifecycle 1.0.11
|   |   '-- flutter...
|   '-- google_maps_flutter_platform_interface 1.0.5
|       |-- flutter...
|       |-- meta...
|       |-- plugin_platform_interface...
|       '-- stream_transform...
|-- hive 1.4.4+1
|   |-- crypto 2.1.5
|   |   |-- collection...
|   |   |-- convert 2.1.1
|   |   |   |-- charcode...
|   |   |   '-- typed_data...
|   |   '-- typed_data...
|   '-- meta...
|-- hive_generator 0.8.2
|   |-- analyzer 0.40.6
|   |   |-- _fe_analyzer_shared 12.0.0
|   |   |   '-- meta...
|   |   |-- args...
|   |   |-- cli_util 0.2.0
|   |   |   '-- path...
|   |   |-- collection...
|   |   |-- convert...
|   |   |-- crypto...
|   |   |-- glob...
|   |   |-- meta...
|   |   |-- package_config 1.9.3
|   |   |   |-- charcode...
|   |   |   '-- path...
|   |   |-- path...
|   |   |-- pub_semver...
|   |   |-- source_span...
|   |   |-- watcher...
|   |   '-- yaml...
|   |-- build 1.5.1
|   |   |-- analyzer...
|   |   |-- async...
|   |   |-- convert...
|   |   |-- crypto...
|   |   |-- glob...
|   |   |-- logging...
|   |   |-- meta...
|   |   '-- path...
|   |-- dartx 0.5.0
|   |   |-- characters...
|   |   |-- collection...
|   |   |-- crypto...
|   |   |-- meta...
|   |   |-- path...
|   |   '-- time 1.4.0
|   |-- hive...
|   '-- source_gen 0.9.8
|       |-- analyzer...
|       |-- async...
|       |-- build...
|       |-- dart_style...
|       |-- glob...
|       |-- meta...
|       |-- path...
|       |-- pedantic...
|       '-- source_span...
|-- implicitly_animated_reorderable_list 0.3.2
|   |-- async 2.5.0-nullsafety.3
|   |   '-- collection...
|   |-- flutter...
|   '-- meta...
|-- intl 0.16.1
|   '-- path 1.8.0-nullsafety.3
|-- path_provider 1.6.24
|   |-- flutter...
|   |-- path_provider_linux 0.0.1+2
|   |   |-- flutter...
|   |   |-- path...
|   |   |-- path_provider_platform_interface...
|   |   '-- xdg_directories 0.1.2
|   |       |-- meta...
|   |       |-- path...
|   |       '-- process 3.0.13
|   |           |-- file...
|   |           |-- intl...
|   |           |-- meta...
|   |           |-- path...
|   |           '-- platform...
|   |-- path_provider_macos 0.0.4+6
|   |   '-- flutter...
|   |-- path_provider_platform_interface 1.0.4
|   |   |-- flutter...
|   |   |-- meta...
|   |   |-- platform 2.2.1
|   |   '-- plugin_platform_interface 1.0.3
|   |       '-- meta...
|   '-- path_provider_windows 0.0.4+3
|       |-- ffi 0.1.3
|       |-- flutter...
|       |-- meta...
|       |-- path...
|       |-- path_provider_platform_interface...
|       '-- win32 1.7.4
|           '-- ffi...
|-- permission_handler 5.0.1+1
|   |-- flutter...
|   |-- meta...
|   '-- permission_handler_platform_interface 2.0.1
|       |-- flutter...
|       |-- meta...
|       '-- plugin_platform_interface...
|-- rename 1.2.0
|   |-- args 1.6.0
|   '-- logger 0.9.4
|-- rxdart 0.24.1
'-- wakelock 0.1.4+2
    '-- flutter...
```

</details>

---

**Comment by markusaksli-nc** [comment] 2020-11-30 14:45
Hi @sgalway00 
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)? You could change the official example code for example.
Thank you

**Comment by TahaTesser** [comment] 2020-11-30 14:57
It's firing both messages in the console when the latest `cloud_firestore: ^0.14.3+1`

<details> 
<summary>code sample</summary> 

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  final _db = FirebaseFirestore.instance;

  @override
  void initState() {
    super.initState();

    Stream<DocumentSnapshot> _docStream = FirebaseFirestore.instance
        .collection('Athlete1')
        .doc('currentPosition')
        .snapshots();

    if (_docStream.isBroadcast == true) {
      print('Stream is broadcasting');
    }

    _docStream.listen((event) {
      print('athletePos stream event received');
      print(event.data().toString());
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
``` 

</details>


### iOS
```bash
Launching lib/main.dart on iPhone 12 in debug mode...
lib/main.dart:1
Warning: Podfile is out of date
  This can cause issues if your application depends on plugins that do not support iOS.
  See https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms for details.
  If you have local Podfile edits you would like to keep, see https://github.com/flutter/flutter/issues/45197 for instructions.
To regenerate the Podfile, run:
  rm ios/Podfile

Xcode build done.                                           228.4s
Connecting to VM Service at ws://127.0.0.1:61612/ivaXgY8pNEo=/ws
flutter: Stream is broadcasting
flutter: athletePos stream event received
flutter: {content: dummy_content, title: dummy_title}
```

### Android
```bash
I/flutter ( 6858): Stream is broadcasting
W/DynamiteModule( 6858): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 6858): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 6858): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
I/flutter ( 6858): athletePos stream event received
I/flutter ( 6858): {title: dummy_title, content: dummy_content}
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • RMX2001 (mobile)                   • EUYTFEUSQSRGDA6D
      • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554
      • android-x86   • Android 8.0.0 (API 26) (emulator)
    • iPhone 12 (mobile)                 • BBCEDCF6-A80B-49DC-86EE-C9B542A9AD1B
      • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by sgalway00** [comment] 2020-11-30 17:50
Code below shows using a simple .get() and a .listen().  The terminal shows that the get() works, but the listen() does not.  

`import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

class MapPageView extends StatefulWidget {
  const MapPageView({Key key}) : super(key: key);

  @override
  _MapPageViewState createState() => _MapPageViewState();
}

class _MapPageViewState extends State<MapPageView> {
  @override
  void initState() {
    super.initState();

    readCurPos();

    Stream<DocumentSnapshot> _docStream = FirebaseFirestore.instance.
      collection('Athlete1').
      doc('currentPosition').snapshots();

    if (_docStream.isBroadcast == true) {
      print('Stream is broadcasting');
    }

    _docStream.listen((event) {
      print('athletePos stream event received');
      print(event.data().toString());
    });
  }

  Future<void> readCurPos() async {
    DocumentSnapshot _docSnap = await FirebaseFirestore.instance.
      collection('Athlete1').
      doc('currentPosition').get();

    var dataSnap = _docSnap.data();

    double lat = dataSnap["lat"];
    double long = dataSnap["long"];

    print('Lat: $lat, Long: $long');
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: Container(
          child: Text('Hello World'),
        ),
      ),
      floatingActionButton: FloatingActionButton(
        child: Icon(Icons.add),
        onPressed: () {},
      ),
    );
  }
}
`

terminal output iOS:

`Launching lib/main.dart on iPhone 12 in debug mode...
lib/main.dart:1
Xcode build done.                                           41.8s
Connecting to VM Service at ws://127.0.0.1:56796/5mn4fA8mzlU=/ws
flutter: InitFirebase started
[GETX] "GetMaterialController" has been initialized
flutter: Firebase init
flutter: ConfigDash windowStream is loading
flutter: InitWindows has run
flutter: Stream is broadcasting
flutter: Lat: 29.709576813683668, Long: -95.94260267789087
`

terminal output Android:
`I/flutter (14360): InitWindows has run
I/flutter (14360): Stream is broadcasting
I/flutter (14360): athletePos stream event received
I/flutter (14360): {waypoint: none, vmg: 0.0, smoothHeading: 173, smoothSpeed: 0.2, accuracy: 19.84856861039839, lat: 29.709576813683668, long: -95.94260267789087, timestamp: Timestamp(seconds=1606699, nanoseconds=476999000)}
I/flutter (14360): Lat: 29.709576813683668, Long: -95.94260267789087
`

**Comment by markusaksli-nc** [comment] 2020-12-01 10:09
Seems to be working fine for me as well on the latest master `1.24.0-8.0.pre.375` using `cloud_firestore: ^0.14.3+1`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.375, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.375 at C:\Development\flutter_master
    • Framework revision a7f5fd5360 (22 hours ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.8194.7
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```
</details>

Android
```
I/flutter (10615): athletePos stream event received
I/flutter (10615): {long: 1.01, lat: 1.01}
I/flutter (10615): Lat: 1.01, Long: 1.01
```
iOS
```
flutter: athletePos stream event received
flutter: {lat: 1.01, long: 1.01}
flutter: Lat: 1.01, Long: 1.01
```

**Comment by pschuegr** [comment] 2020-12-26 06:35
I believe I'm seeing this problem with 0.14.4.  It is reproducible for me in ios emulator and on device, while android build and macos build produce stream snapshots normally.

**Comment by pschuegr** [comment] 2020-12-27 08:09
It looks like my problem is caused by https://github.com/FirebaseExtended/flutterfire/issues/3671.  The fix by sc4v3ng3r here https://github.com/FirebaseExtended/flutterfire/issues/3671#issuecomment-746990151 seems to resolve it.

**Comment by markusaksli-nc** [comment] 2020-12-28 07:23
@sgalway00 Can you confirm what @pschuegr commented?

If the root cause is #3671 I would prefer closing this issue and just tracking it there.

**Comment by pschuegr** [comment] 2020-12-28 15:33
I have a up-to-date fork of the flutterfire repo with sc4v3ng3r's fix applied at https://github.com/pschuegr/flutterfire, if you want to check quickly.

**Comment by ened** [comment] 2020-12-29 15:01
@pschuegr perhaps you can check the comment on https://github.com/FirebaseExtended/flutterfire/issues/3671#issuecomment-751704186 including the link to the PR which hopefully resolves a variety of Isolate issues. Thank you.

**Comment by pschuegr** [comment] 2020-12-29 16:30
@ened, @markusaksli-nc the PR for #3671 resolves this for me.

**Closed** 2021-01-08 16:33 UTC
Labels: platform: ios, plugin: cloud_firestore, type: bug
