### ISSUE TITLE
🐛 [firebase_auth] PhoneAuthCredential returns null for smsCode  in verificationCompleted

### ISSUE THREAD

**Issue by Melak12** [FirebaseExtended/flutterfire#3583] opened 2020-09-18 14:42 UTC
## Bug report

When tried to capture the SMS code inside **verificationComplete** callback but the PhoneAuthCredential's smsCode field returns null.

### Steps to reproduce

```
Future<void> loginWithPhone(String phoneNumber,
      final OnSMSCodeSent onSMSCodeSent,
      final OnVerificationFailed onVerificationFailed) async {
    return await _auth.verifyPhoneNumber(
        phoneNumber: phoneNumber,
        timeout: timeOut,
        codeSent: onSMSCodeSent,
        codeAutoRetrievalTimeout: (String verificationId) {},
        //ANDROID ONLY: Verify SMS Code automatically.
        verificationCompleted: (PhoneAuthCredential credential) async {
          // ANDROID ONLY!
          AppLogger.log(TAG,
              message: "Auto SMS Code Verification is Completed! OTP CODE = ${credential.smsCode}");
          // Sign the user in (or link) with the auto-generated credential
        await _auth.signInWithCredential(credential);
        },
        verificationFailed: onVerificationFailed,
    );
  
}
```

```
I/flutter ( 6777): │ [PhoneAuthHandler] Auto SMS Code Verification is Completed! OTP CODE = null
```

**Comment by TahaTesser** [comment] 2020-09-22 11:59
<details> 
<summary>code sample</summary> 

```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_signin_button/flutter_signin_button.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Material App Bar'),
      ),
      body: Center(
        child: _PhoneSignInSection(
            // Scaffold.of(context),
            ),
      ),
    );
  }
}

final FirebaseAuth _auth = FirebaseAuth.instance;

class _PhoneSignInSection extends StatefulWidget {
  // _PhoneSignInSection(this._scaffold);

  // final ScaffoldState _scaffold;

  @override
  State<StatefulWidget> createState() => _PhoneSignInSectionState();
}

class _PhoneSignInSectionState extends State<_PhoneSignInSection> {
  final TextEditingController _phoneNumberController = TextEditingController();
  final TextEditingController _smsController = TextEditingController();

  String _message = '';
  String _verificationId;

  @override
  Widget build(BuildContext context) {
    if (kIsWeb) {
      return Card(
        child: Padding(
            padding: EdgeInsets.all(16),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Container(
                  padding: EdgeInsets.only(bottom: 16),
                  child: const Text('Test sign in with phone number',
                      style: TextStyle(fontWeight: FontWeight.bold)),
                  alignment: Alignment.center,
                ),
                Text(
                    "Sign In with Phone Number on Web is currently unsupported")
              ],
            )),
      );
    }
    return Card(
      child: Padding(
          padding: EdgeInsets.all(16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              Container(
                child: const Text('Test sign in with phone number',
                    style: TextStyle(fontWeight: FontWeight.bold)),
                alignment: Alignment.center,
              ),
              TextFormField(
                controller: _phoneNumberController,
                decoration: const InputDecoration(
                    labelText: 'Phone number (+x xxx-xxx-xxxx)'),
                validator: (String value) {
                  if (value.isEmpty) {
                    return 'Phone number (+x xxx-xxx-xxxx)';
                  }
                  return null;
                },
              ),
              Container(
                padding: const EdgeInsets.symmetric(vertical: 16.0),
                alignment: Alignment.center,
                child: SignInButtonBuilder(
                  icon: Icons.contact_phone,
                  backgroundColor: Colors.deepOrangeAccent[700],
                  text: "Verify Number",
                  onPressed: () async {
                    _verifyPhoneNumber();
                  },
                ),
              ),
              TextField(
                controller: _smsController,
                decoration:
                    const InputDecoration(labelText: 'Verification code'),
              ),
              Container(
                padding: const EdgeInsets.only(top: 16.0),
                alignment: Alignment.center,
                child: SignInButtonBuilder(
                    icon: Icons.phone,
                    backgroundColor: Colors.deepOrangeAccent[400],
                    onPressed: () async {
                      _signInWithPhoneNumber();
                    },
                    text: 'Sign In'),
              ),
              Visibility(
                visible: _message == null ? false : true,
                child: Container(
                  alignment: Alignment.center,
                  padding: const EdgeInsets.symmetric(horizontal: 16),
                  child: Text(
                    _message,
                    style: TextStyle(color: Colors.red),
                  ),
                ),
              )
            ],
          )),
    );
  }

  // Example code of how to verify phone number
  void _verifyPhoneNumber() async {
    setState(() {
      _message = '';
    });

    PhoneVerificationCompleted verificationCompleted =
        (PhoneAuthCredential phoneAuthCredential) async {
      await _auth.signInWithCredential(phoneAuthCredential);
      print('ssss');
      print('SMS: ${phoneAuthCredential.smsCode}');

      // widget._scaffold.showSnackBar(SnackBar(
      //   content: Text(
      //       "Phone number automatically verified and user signed in: ${phoneAuthCredential}"),
      // ));
    };

    PhoneVerificationFailed verificationFailed =
        (FirebaseAuthException authException) {
      setState(() {
        _message =
            'Phone number verification failed. Code: ${authException.code}. Message: ${authException.message}';
      });
    };

    PhoneCodeSent codeSent =
        (String verificationId, [int forceResendingToken]) async {
      // widget._scaffold.showSnackBar(const SnackBar(
      //   content: Text('Please check your phone for the verification code.'),
      // ));
      _verificationId = verificationId;
    };

    PhoneCodeAutoRetrievalTimeout codeAutoRetrievalTimeout =
        (String verificationId) {
      _verificationId = verificationId;
    };

    try {
      await _auth.verifyPhoneNumber(
          phoneNumber: _phoneNumberController.text,
          timeout: const Duration(seconds: 5),
          verificationCompleted: (PhoneAuthCredential credential) async {
            print('SMS: ${credential.smsCode}');
            await _auth.signInWithCredential(credential);
          },
          verificationFailed: verificationFailed,
          codeSent: codeSent,
          codeAutoRetrievalTimeout: codeAutoRetrievalTimeout);
    } catch (e) {
      // widget._scaffold.showSnackBar(SnackBar(
      //   content: Text("Failed to Verify Phone Number: ${e}"),
      // ));
    }
  }

  // Example code of how to sign in with phone.
  void _signInWithPhoneNumber() async {
    try {
      final AuthCredential credential = PhoneAuthProvider.credential(
        verificationId: _verificationId,
        smsCode: _smsController.text,
      );
      final UserCredential userCredential =
          (await _auth.signInWithCredential(credential));
      print(userCredential.credential);
      // final AuthCredential emailCredential = EmailAuthProvider.credential(
      //     email: 'helina@triage.team', password: '123456');

      // await phoneCredential.user.linkWithCredential(emailCredential);

      // await credential.user.linkWithCredential(emailCredential);

      // widget._scaffold.showSnackBar(SnackBar(
      //   content: Text("Successfully signed in UID: ${user.uid}"),
      // ));
    } catch (e) {
      print(e);
      // widget._scaffold.showSnackBar(SnackBar(
      //   content: Text("Failed to sign in"),
      // ));
    }
  }
}

```

</details> 

```
  firebase_auth: ^0.18.0+1
  firebase_core: ^0.5.0
```

**Comment by russellwheatley** [comment] 2020-09-23 12:45
Hey @Melak12, this is actually expected in some [instances](https://stackoverflow.com/a/48906032/5681607). It should still work as the Android device is effectively verifying the phone number without needing the SMS code. In those moments, `smsCode` is `null`. 

I think this is probably a documentation issue. Thoughts, @Salakar?

**Comment by Ehesp** [comment] 2020-10-01 09:40
@russellwheatley I don't think that's correct. The Android `onVerificationCompleted` callback is only called on auto-verification which provides a `PhoneAuthCredential`, which has a sms code getter on it: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java#L790

Imagine you have entered your phone number, and some input boxes pop up but Android automatically verifies, you may want to show the code for a second before closing it for better UX. 

As to why it's `null`, I'm not sure. The code just checks the provided credential so I don't really know what else we can do here.

**Comment by Melak12** [comment] 2020-10-01 10:54
> @russellwheatley I don't think that's correct. The Android `onVerificationCompleted` callback is only called on auto-verification which provides a `PhoneAuthCredential`, which has a sms code getter on it: https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_auth/firebase_auth/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java#L790
> 
> Imagine you have entered your phone number, and some input boxes pop up but Android automatically verifies, you may want to show the code for a second before closing it for better UX.
> 
> As to why it's `null`, I'm not sure. The code just checks the provided credential so I don't really know what else we can do here.

Thanks @Ehesp, that is what exactly what I need. For better UX, I need to show SMS code but still, I am not getting the SMS code.

**Comment by Ehesp** [comment] 2020-10-01 11:03
Yeah makes sense, just not sure why :D

@russellwheatley can you check whether code exists on native? if so, could be an issue with it being passed down.

**Comment by russellwheatley** [comment] 2020-10-09 08:59
The [documentation](https://firebase.google.com/docs/auth/android/phone-auth#onverificationcompletedphoneauthcredential) says this method: `onVerificationCompleted `  is called in two situations; `InstantVerification` & `Auto-retrieval`.

Quotes:
>Instant verification: in some cases the phone number can be instantly verified without needing to send or enter a verification code.

>In either case, the user's phone number has been verified successfully, and you can use the PhoneAuthCredential object that's passed to the callback to sign in the user.


The reason why the sms code is `null` is because no code is sent to the user.

You could say it's bad UX. Unfortunately, it's not something we have control over as it's an Android Firebase SDK implementation.

**Comment by Melak12** [comment] 2020-10-12 15:08
@russellwheatley thanks for the detailed explanation. Unfortunately, it's sad to hear the SMS is code is still not sent to the user and you don't have control over it. I will keep using the current options to auto verify the phone number without showing the SMS code instantly.

**Comment by Ehesp** [comment] 2020-10-12 16:22
When building things out, I did see it coming through on my own device. It could be a device specific issue?

**Comment by russellwheatley** [comment] 2021-04-20 10:38
As mentioned previously, this is expected behaviour for the android platform. So I'm going to close this issue.

**Closed by russellwheatley** 2021-04-20 10:38 UTC
Labels: plugin: auth
