### ISSUE TITLE
🐛 [firebase_messaging] firebase_messaging/unknown Authentication Failed

### ISSUE THREAD

**Issue by rymesaint** [FirebaseExtended/flutterfire#6729] opened 2021-07-29 12:19 UTC
## Bug report

**Describe the bug**
This problem only produce on production when the user getting a token from firebase return the response "java.io.IOException: AUTHENTICATION_FAILED" its not always error like this but after a few minutes then this error just disappear.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-x64, locale en-ID)
    • Flutter version 2.2.3 at /Users/ridwanfauzan/Documents/flutter
    • Framework revision f4abaa0735 (4 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/ridwanfauzan/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.4 20F71 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 92.0.4515.107

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4
Flutter SDK 2.2.3
wss_mobile 3.1.14+122

dependencies:
- archive 3.1.2 [crypto path]
- audioplayers 0.19.0 [uuid path_provider http flutter flutter_web_plugins]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- chewie 1.2.2 [cupertino_icons flutter provider video_player wakelock]
- chewie_audio 1.2.0 [cupertino_icons flutter video_player]
- connectivity 3.0.6 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- cool_stepper 1.2.1 [flutter another_flushbar]
- cupertino_icons 1.0.3
- device_info 2.0.0 [flutter device_info_platform_interface]
- dio 4.0.0 [http_parser path]
- dio_cache_interceptor 3.0.1 [dio path uuid]
- duration 2.0.15
- environment_config 3.0.0 [dart_style code_builder args yaml]
- file_picker 3.0.2+2 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- filesystem_picker 1.0.4 [flutter path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics 8.1.2 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 10.0.2 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.7.0+5 [firebase_core flutter]
- fl_chart 0.20.1 [flutter path_drawing equatable pedantic]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_calendar_carousel 2.0.1 [intl flutter]
- flutter_exif_rotation 0.4.1 [flutter]
- flutter_html 2.1.0 [html csslib flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter_math_fork collection numerus flutter]
- flutter_local_notifications 6.0.0 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_mailer 1.0.1 [flutter]
- flutter_markdown 0.6.2 [flutter markdown meta path]
- flutter_neat_and_clean_calendar 0.2.2+10 [flutter intl]
- flutter_offline 2.0.0 [flutter connectivity wifi_info_flutter]
- flutter_rating_bar 4.0.0 [flutter]
- flutter_screenutil 5.0.0+2 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- flutter_typeahead 3.1.3 [flutter flutter_keyboard_visibility]
- flutter_windowmanager 0.1.0 [flutter]
- flutter_zoom_drawer 2.1.0 [flutter]
- font_awesome_flutter 8.12.0 [flutter]
- gallery_saver 2.1.0 [flutter path_provider http path]
- geolocator 7.1.0 [flutter geolocator_platform_interface geolocator_web]
- get 4.1.4 [flutter]
- get_storage 2.0.3 [flutter get path_provider]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- google_maps_flutter 2.0.6 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- grouped_list 4.1.0 [flutter]
- html_unescape 2.0.0
- image_cropper 1.4.0 [flutter]
- image_picker 0.8.2 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- infinite_scroll_pagination 3.0.1 [flutter sliver_tools]
- intl 0.17.0 [clock path]
- launch_review 3.0.1 [flutter]
- loading_indicator 2.1.1 [flutter async]
- location 4.1.1 [flutter location_platform_interface location_web meta]
- logging 1.0.1
- network_to_file_image 3.0.0 [flutter]
- package_info 2.0.0 [flutter]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 8.1.1 [flutter meta permission_handler_platform_interface]
- photo_view 0.11.1 [flutter]
- pigment 1.0.4 [flutter]
- pull_to_refresh 2.0.0 [flutter]
- qr_code_scanner 0.5.1 [js flutter flutter_web_plugins]
- qr_flutter 4.0.0 [flutter qr]
- screenshot 1.2.1 [flutter]
- timeago 3.0.2
- timer_count_down 2.2.0 [flutter]
- trust_location 2.0.13 [flutter]
- url_launcher 6.0.6 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.1.6 [flutter flutter_test meta video_player_platform_interface video_player_web]
- wakelock 0.5.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- whatsapp_unilink 2.0.0
- youtube_plyr_iframe 2.0.6 [flutter flutter_inappwebview]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- _fe_analyzer_shared 22.0.0 [meta]
- analyzer 1.7.1 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- another_flushbar 1.10.23 [pedantic flutter]
- args 2.1.1
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- connectivity_for_web 0.4.0 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.2.0 [flutter]
- connectivity_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- convert 3.0.0 [typed_data]
- cross_file 0.3.1+4 [flutter meta]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.0 [source_span]
- dart_style 2.0.1 [analyzer args path pub_semver source_span]
- device_info_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- equatable 2.0.0 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.2 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_inappwebview 5.3.2 [flutter]
- flutter_keyboard_visibility 5.0.2 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_layout_grid 1.0.1 [flutter collection meta quiver]
- flutter_local_notifications_platform_interface 4.0.0 [flutter plugin_platform_interface]
- flutter_math_fork 0.3.3+1 [flutter flutter_svg provider meta collection tuple]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- geolocator_platform_interface 2.1.1 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.3 [flutter flutter_web_plugins geolocator_platform_interface]
- glob 2.0.0 [async collection file path pedantic string_scanner]
- google_maps_flutter_platform_interface 2.1.0 [collection flutter meta plugin_platform_interface stream_transform]
- html 0.15.0 [csslib source_span]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.1 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.2.0 [flutter http meta plugin_platform_interface cross_file]
- js 0.6.3
- location_platform_interface 2.3.0 [flutter meta plugin_platform_interface]
- location_web 3.1.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- markdown 4.0.0 [args charcode meta]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- numerus 1.1.1
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- permission_handler_platform_interface 3.6.0 [flutter meta plugin_platform_interface]
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.0 [file path platform]
- provider 5.0.0 [collection flutter nested]
- pub_semver 2.0.0 [collection]
- qr 2.0.0 [meta]
- quiver 3.0.1 [matcher]
- rxdart 0.27.1
- sky_engine 0.0.99
- sliver_tools 0.2.0 [flutter]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.1 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock_macos 0.1.0+1 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.1+1 [flutter meta]
- wakelock_web 0.2.0+1 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.0 [async path pedantic]
- webview_flutter 2.0.8 [flutter]
- wifi_info_flutter 2.0.0 [flutter wifi_info_flutter_platform_interface]
- wifi_info_flutter_platform_interface 2.0.0 [plugin_platform_interface flutter]
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-07-29 12:55
Hi @rymesaint 
Could you please provide the full error with a stacktrace?
Are these errors specific to any devices?
Thank you

**Comment by rymesaint** [comment] 2021-07-29 13:37
> Hi @rymesaint
> Could you please provide the full error with a stacktrace?
> Are these errors specific to any devices?
> Thank you

i can't get any error log because it happen sometimes and its gone
no there is no specific devices this happen

**Comment by russellwheatley** [comment] 2021-07-30 09:35
I'm fairly sure this is an `firebase-android-sdk`. The issue is tracked on the repo [here](https://github.com/FirebaseExtended/flutterfire/pull/6728), it also has its own ticket [here](https://issuetracker.google.com/issues/143413382) on the Google issue tracker.

This concerns both error messages: `SERVICE_UNAVAILABLE` & `AUTHENTICATION_FAILED`. There are a number of workarounds on the repo ticket such as updating Google Play Store on the device, but you might want to try this [first](https://github.com/firebase/firebase-android-sdk/issues/1286#issuecomment-884117864) if it helps although this is two major versions behind the version currently used by `Flutterfire`.  

I'm closing this issue as there isn't anything for us to fix, this issue needs to be resolved upstream.

**Closed by russellwheatley** 2021-07-30 09:35 UTC
Labels: plugin: messaging, type: bug
