### ISSUE TITLE
🐛 [cloud_firestore] INVALID_ARGUMENT: missing stream

### ISSUE THREAD

**Issue by maciejbrzezinski** [FirebaseExtended/flutterfire#5866] opened 2021-04-21 17:43 UTC
## Bug report

When I'm running writing operations to firestore (being online) I'm getting randomly errors, there is no repeatability, when I'm for example trying to save new document, two times I will get the error, and third time will work properly. 

When I have stream builder to show values from some collection, then do write operation, change is visible for a second in refreshed UI, then error occurs and value is rolled back 

`com.google.firebase.firestore.FirebaseFirestoreException: INVALID_ARGUMENT: missing stream token`

`Client specified an invalid argument. Note that this differs from failed-precondition. invalid-argument indicates arguments that are problematic regardless of the state of the system (e.g., an invalid field name).`

```
E/flutter ( 6002): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [cloud_firestore/invalid-argument] Client specified an invalid argument. Note that this differs from failed-precondition. invalid-argument indicates arguments that are problematic regardless of the state of the system (e.g., an invalid field name).
E/flutter ( 6002): #0      MethodChannelDocumentReference.set (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:43:7)
E/flutter ( 6002): <asynchronous suspension>
E/flutter ( 6002): #1      dao.save (lala/mm/mm.dart:51:7)
E/flutter ( 6002): <asynchronous suspension>`
```
### Steps to reproduce

1. Invoke any write operation

### Expected behavior

Document is saved

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19041.928], locale pl-PL)
[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2017.3)
[√] IntelliJ IDEA Community Edition (version 2020.2)
[√] IntelliJ IDEA Community Edition (version 2020.3)
[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
[√] VS Code (version 1.55.2)
[√] Connected device (3 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.3
Flutter SDK 2.0.5
tadek_android 1.0.0+1

dependencies:
- cloud_firestore 1.0.6 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.2
- date_time_picker 2.0.0 [flutter intl]
- easy_localization 3.0.0 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- firebase_core 1.0.4 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_colorpicker 0.4.0 [flutter]
- flutter_local_notifications 5.0.0+1 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_native_timezone 1.0.10 [flutter]
- material_tag_editor 0.1.1 [flutter]
- moor_flutter 4.0.0 [moor sqflite path flutter]
- provider 5.0.0 [collection flutter nested]
- theme_provider 0.5.0 [flutter shared_preferences]

dev dependencies:
- build_runner 2.0.0 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime package_config path pedantic pool pub_semver pubspec_parse sh
elf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- moor_generator 4.2.2 [charcode collection recase meta path json_annotation stream_transform args logging cli_util moor sqlite3 sqlparser analyzer analyzer_plugin_fork source_span build build_resolvers build_config dart_style source_gen]

transitive dependencies:
- _fe_analyzer_shared 21.0.0 [meta]
- analyzer 1.5.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- analyzer_plugin_fork 0.5.1 [analyzer dart_style meta pub_semver]
- args 2.0.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.1 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform]
- build_runner_core 7.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.2 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.6 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.0 [analyzer args path pub_semver source_span]
- easy_logger 0.0.2 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_local_notifications_platform_interface 3.0.0 [flutter plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- graphs 2.0.0
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- moor 4.2.1 [async convert collection meta pedantic stream_channel sqlite3]
- nested 1.0.0 [flutter]
- package_config 2.0.0 [path]
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- recase 4.0.0
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- sqlite3 1.0.0 [collection ffi meta]
- sqlparser 0.15.0 [meta collection source_span charcode]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-04-22 06:41
Hi @maciejbrzezinski 
Are you using the `whereIn` filter? Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue for you?
Thank you

**Comment by maciejbrzezinski** [comment] 2021-04-22 07:03
Sample code causing error (all write operations can cause it):
`CollectionReference _list = FirebaseFirestore.instance.collection('lists');
return await _list.add(taskList.toMap()).then((value) => value.id);`
Data sent:
![image](https://user-images.githubusercontent.com/34410554/115670212-73763980-a349-11eb-94ee-ac78a72e0000.png)

**Comment by markusaksli-nc** [comment] 2021-04-22 07:11
So this operation will fail a few times and then succeed even though you pass the same arguments?

**Comment by maciejbrzezinski** [comment] 2021-04-22 07:27
That's right, the same arguments are working differently, it seems like it is getting worse, because today I couldn't finish any write operation, reading works perfectly.
 
Just checked writing through firestore webpage console, and it seems like it is not a problem with plugin, but with my Firestore. When I'm editing some document, I'm having this error and values are rolled back 
![image](https://user-images.githubusercontent.com/34410554/115673352-d5846e00-a34c-11eb-8b31-2c75e72d1257.png)

**Comment by markusaksli-nc** [comment] 2021-04-23 08:55
In this case it doesn't seem to be so much a problem with the packages as with the native Firebase side. It could be specific to your region since we are not seeing this.

I'm going to close the issue since it seems like our packages arent at fault here but you can open a support request at https://firebase.google.com/support

**Closed by markusaksli-nc** 2021-04-23 08:55 UTC
Labels: Needs Attention, type: bug
