### ISSUE TITLE
[firebase_in_app_messaging] iOS compiler error 

### ISSUE THREAD

**Issue by ravivlb** [FirebaseExtended/flutterfire#2822] opened 2020-06-23 02:21 UTC
**Describe the bug**
After adding in-app messaging flutter give the error on the package (iOS)

**To Reproduce**
1. Go to 'pubspec.yaml'
2. add firebase_in_app_messaging: ^0.1.2
3. run the flutter
4. See an error or incorrect behavior

/.pub-cache/hosted/pub.dartlang.org/firebase_in_app_messaging-0.1.2/ios/Classes/FirebaseInAppMessagingPlugin.m:33:42: error: no known class method for selector 'inAppMessaging'
          FIRMessaging *fiam = [FIRMessaging inAppMessaging];
                                             ^~~~~~~~~~~~~~
/.pub-cache/hosted/pub.dartlang.org/firebase_in_app_messaging-0.1.2/ios/Classes/FirebaseInAppMessagingPlugin.m:34:11: error: no visible @interface for 'FIRMessaging' declares the selector 'triggerEvent:'
        [fiam triggerEvent:eventName];
         ~~~~ ^~~~~~~~~~~~
/.pub-cache/hosted/pub.dartlang.org/firebase_in_app_messaging-0.1.2/ios/Classes/FirebaseInAppMessagingPlugin.m:38:42: error: no known class method for selector 'inAppMessaging'
          FIRMessaging *fiam = [FIRMessaging inAppMessaging];
                                             ^~~~~~~~~~~~~~
/rs/.pub-cache/hosted/pub.dartlang.org/firebase_in_app_messaging-0.1.2/ios/Classes/FirebaseInAppMessagingPlugin.m:39:10: error: property 'messageDisplaySuppressed' not found on object of type 'FIRMessaging *'

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Paste output here
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.5 19F101, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

• No issues found!

**Comment by koji-1009** [comment] 2020-06-25 07:05
Hi! I have the same problem.

Maybe, this issue is duplicated is a duplicated of #2151. 
#2701 fixes this problem.

**Comment by TahaTesser** [comment] 2020-06-26 10:37
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2151

**Closed by TahaTesser** 2020-06-26 10:37 UTC
