### ISSUE TITLE
🐛 [CLOUD_FIRESTORE] fatal error: module 'cloud_firestore' not found

### ISSUE THREAD

**Issue by imdarpn** [FirebaseExtended/flutterfire#5198] opened 2021-03-03 12:37 UTC
## Bug report

**Describe the bug**
fatal error: module 'cloud_firestore' not found

### Steps to reproduce
flutter clean
flutter pub get
cd ios
pod install
cd ..
flutter build ios 
### Expected behavior

its will be run in simulator or any iOS device
## Additional context

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.2.2 20D80 darwin-x64, locale en-IN)
    • Flutter version 1.22.6 at /Users/home/code/flutter
    • Framework revision 9b2d32b605 (6 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/home/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = /Users/home/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.0

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 1660D7FC-9C03-4295-A47D-0B689681F7A6 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)

• No issues found!


```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
app 1.0.0+1

dependencies:
- cached_network_image 2.5.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- connectivity 0.4.9+5 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- cupertino_icons 0.1.3
- dio 3.0.10 [http_parser path]
- firebase_analytics 6.3.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.4 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_database 4.4.0 [flutter firebase_core]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- firebase_storage 4.0.1 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_cupertino_date_picker 1.0.26+2 [flutter]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_libphonenumber 0.3.12 [flutter devicelocale]
- flutter_page_transition 0.1.6 [flutter]
- flutter_spinkit 4.1.2+1 [flutter]
- flutter_staggered_animations 0.1.2 [flutter]
- flutter_staggered_grid_view 0.3.4 [flutter]
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]
- flutter_tags 0.4.9+1 [flutter]
- flutter_typeahead 1.9.3 [flutter flutter_keyboard_visibility]
- fluttertoast 7.1.8 [flutter flutter_web_plugins]
- font_awesome_flutter 8.11.0 [flutter]
- geocoder 0.2.1 [meta flutter]
- geocoding 1.0.5 [flutter geocoding_platform_interface url_launcher]
- geolocator 6.2.1 [flutter geolocator_platform_interface geolocator_web]
- getflutter 1.1.3 [flutter]
- google_maps_flutter 0.5.33 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_maps_place_picker 0.10.0 [flutter google_maps_flutter geolocator permission_handler provider google_maps_webservice tuple http]
- google_sign_in 4.5.9 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.7+22 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- intl_phone_number_input 0.5.2+2 [flutter meta libphonenumber equatable]
- jiffy 3.0.1 [intl]
- libphonenumber 1.0.2 [flutter meta]
- location 3.2.4 [flutter location_platform_interface location_web meta]
- lottie 0.7.0+1 [archive characters charcode collection flutter logging meta path vector_math]
- page_transition 1.1.7+6 [flutter]
- page_view_indicators 1.4.1 [flutter]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pin_code_fields 6.1.0 [flutter]
- provider 4.3.3 [collection flutter nested]
- recase 3.0.1
- rxdart 0.24.1
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 1.1.2 [flutter]
- sliding_up_panel 1.0.2 [flutter]
- speech_bubble 0.0.7 [flutter]
- steps_indicator 0.3.1 [flutter]
- syncfusion_flutter_core 18.4.46 [flutter]
- syncfusion_flutter_sliders 18.4.46-beta [flutter intl syncfusion_flutter_core]
- timeago 2.0.30
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- walkthrough 0.0.3 [flutter]
- webview_flutter 0.3.24 [flutter]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- connectivity_for_web 0.3.1+4 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+7 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- devicelocale 0.3.3 [flutter]
- equatable 1.2.6 [collection meta]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.4 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.1 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_keyboard_visibility 4.0.6 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 1.0.1 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- geocoding_platform_interface 1.0.1+1 [flutter meta plugin_platform_interface]
- geolocator_platform_interface 1.0.9 [flutter meta plugin_platform_interface vector_math]
- geolocator_web 1.0.1 [flutter flutter_web_plugins geolocator_platform_interface]
- google_maps_flutter_platform_interface 1.2.0 [flutter meta plugin_platform_interface stream_transform collection]
- google_maps_webservice 0.0.19 [http meta]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_platform_interface 1.1.6 [flutter meta http plugin_platform_interface]
- js 0.6.2
- location_platform_interface 1.1.0 [flutter meta plugin_platform_interface]
- location_web 1.0.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- octo_image 0.3.0 [flutter flutter_blurhash]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- permission_handler 5.1.0+2 [flutter meta permission_handler_platform_interface]
- permission_handler_platform_interface 2.0.2 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.2+3 [flutter sqflite_common path]
- sqflite_common 1.0.3+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- tuple 1.0.3 [quiver]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+3 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.4+1 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-03-03 13:09
Hi @imdarpn 
Could you please try upgrading to the latest `cloud_firestore: ^0.16.0+1`?
What is the full error you get?
Thank you

**Comment by imdarpn** [comment] 2021-03-03 15:54
Hi @markusaksli-nc if I upgrade the version of `cloud_firestore` its show me other errors like 

`Because app depends on cloud_firestore ^0.16.0+1 which depends on firebase_core ^0.7.0, firebase_core ^0.7.0 is required.
So, because app depends on firebase_core ^0.5.0, version solving failed.
pub get failed (1; So, because app depends on firebase_core ^0.5.0, version solving failed.)
`
and if I update `firebase_core` version to `0.7.0` than its throws error 
`
Because firebase_storage >=4.0.0 <5.0.0-dev.3 depends on firebase_core ^0.5.0 and app depends on firebase_core ^0.7.0, firebase_storage >=4.0.0 <5.0.0-dev.3 is forbidden.
So, because app depends on firebase_storage ^4.0.0, version solving failed.
pub get failed (1; So, because app depends on firebase_storage ^4.0.0, version solving failed.)
`


current Firebase version are as belows :

cloud_firestore: ^0.14.3
  firebase_analytics: ^6.0.0
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_crashlytics: ^0.2.3
  firebase_database: ^4.0.0
  firebase_messaging: ^7.0.0
  firebase_storage: ^4.0.0

**Comment by Dolls1** [comment] 2021-03-03 21:34
i get this error


Because firebase_admob 0.11.0+1 depends on firebase_core ^0.7.0 and no versions of firebase_admob match >0.11.0+1 <0.12.0, firebase_admob ^0.11.0+1 requires firebase_core ^0.7.0.
So, because imageidentifier3 depends on both firebase_admob ^0.11.0+1 and firebase_core ^1.0.0, version solving failed.
pub get failed (1; So, because imageidentifier3 depends on both firebase_admob ^0.11.0+1 and firebase_core ^1.0.0, version solving failed.)


 i have
firebase_core: ^1.0.0
firebase_storage: ^8.0.0
firebase_admob: ^0.11.0+1
cloud_firestore: ^1.0.0

**Comment by markusaksli-nc** [comment] 2021-03-04 13:37
I'm going to close this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/5202 for now, once that gets solved we can reopen this if you are facing the issue on the latest version.

**Closed by markusaksli-nc** 2021-03-04 13:37 UTC
Labels: Needs Attention, type: bug
