### ISSUE TITLE
🐛 [CLOUD_FUNCTIONS] The plugin `cloud_functions` uses a deprecated version of the Android embedding

### ISSUE THREAD

**Issue by moxajuine** [FirebaseExtended/flutterfire#6971] opened 2021-09-08 19:35 UTC
## Bug report

**Describe the bug**
When adding the cloud_functions: ^ 3.0.2 dependency to pubspec.yaml and executing the flutter pub get command, the error "The plugin` cloud_functions` uses a deprecated version of the Android embedding "appears. 

1. Create a new flutter project
2. Add dependency cloud_functions to pubspec.yaml: ^ 3.0.2
3. Run flutter pub get 

### Expected behavior

No error appears

### Sample project

Just create a new flutter project.

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.0, on Microsoft Windows [Version 10.0.19042.1165], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] Connected device (2 available)

• No issues found!

```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- cloud_functions_platform_interface 5.0.10 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.12 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core 1.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.0.1 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0

```

</details>

---

**Comment by dbeulen** [comment] 2021-09-08 19:43
duplicate #6770

**Comment by markusaksli-nc** [comment] 2021-09-09 08:45
What they said. Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6770

**Closed by markusaksli-nc** 2021-09-09 08:45 UTC
Labels: type: bug, Needs Attention, in triage
