### ISSUE TITLE
🐛 [firebase_auth] Email link auth not working with custom dynamic links domain

### ISSUE THREAD

**Issue by essarn** [FirebaseExtended/flutterfire#5672] opened 2021-04-06 01:10 UTC
## Bug report

When using a custom dynamic links domain (not a `*.page.link`) will the sent sign in link not open in app.

### Expected behavior

The sign in link should open as expected in app and not in the browser.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.2.3 20D91 darwin-arm, locale sv-SE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.0)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.4

dependencies:
- auto_route 1.0.2 [flutter path collection]
- cupertino_icons 1.0.2
- easy_localization 3.0.0 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- firebase_analytics 8.0.0-dev.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.2 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.0-dev.0 [firebase_core flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_hooks 0.16.0 [flutter]
- flutter_svg 0.21.0-nullsafety.0 [flutter meta path_drawing vector_math xml]
- font_awesome_flutter 9.0.0 [flutter]
- freezed_annotation 0.14.1 [collection json_annotation meta]
- get_it 6.0.0 [async collection]
- hooks_riverpod 0.14.0 [collection flutter flutter_hooks flutter_riverpod riverpod state_notifier]
- http 0.13.1 [http_parser meta path pedantic]
- injectable 1.2.2 [get_it]
- intl 0.17.0 [clock path]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- sembast 3.0.0+4 [meta path synchronized pedantic]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]

dev dependencies:
- auto_route_generator 1.0.2 [build source_gen analyzer path build_runner code_builder dart_style auto_route]
- build_runner 1.12.2 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_native_splash 1.1.7+1 [image meta path xml yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 0.14.1+1 [analyzer build build_config meta source_gen freezed_annotation]
- injectable_generator 1.2.2 [build source_gen path glob analyzer code_builder dart_style injectable collection]
- json_serializable 4.1.0 [analyzer build build_config collection json_annotation meta path source_gen]
- pedantic 1.11.0

transitive dependencies:
- _fe_analyzer_shared 18.0.0 [meta]
- analyzer 1.2.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.0 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.7 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.0 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform]
- build_runner_core 6.1.12 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.0 [collection typed_data]
- dart_style 2.0.0 [analyzer args path pub_semver source_span]
- easy_logger 0.0.2 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.0-dev.0 [flutter meta]
- firebase_analytics_web 0.3.0-dev.0 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_riverpod 0.14.0 [collection flutter meta riverpod state_notifier]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.0 [async collection file path pedantic string_scanner]
- graphs 1.0.0
- http_multi_server 3.0.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- logging 1.0.0
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- package_config 2.0.0 [path]
- path_drawing 0.5.0-nullsafety.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0-nullsafety.0 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- riverpod 0.14.0 [collection freezed_annotation meta state_notifier]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.0 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment] 2021-04-06 09:44
@essarn 
Can you provide a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) ? Also, can you try to use [latest](https://pub.dev/packages/firebase_dynamic_links/install) `firebase_dynamic_link` plugin version and see if issue still persists with it or not ?
Thanks.

**Comment by darshankawar** [comment] 2021-04-06 09:46
Also check if [this](https://github.com/FirebaseExtended/flutterfire/issues/5051) sounds similar to your issue.

**Comment by essarn** [comment] 2021-04-07 00:44
> Also check if [this](https://github.com/FirebaseExtended/flutterfire/issues/5051) sounds similar to your issue.

Yes it looks to be the same problem. The only difference is that my custom domain is not using a path prefix as described in that issue.

**Comment by darshankawar** [comment] 2021-04-07 06:36
Thanks. It'll be better to track it separately, so, can you provide steps to replicate along with code sample (with custom link domain) to properly address this issue ?

**Comment by essarn** [comment] 2021-04-12 18:28
I don't want to publicly disclose my custom domain here and I have already described what causes the issue. The dynamic link opens in the app when using a `.page.link` domain but not with a custom one.

**Comment by markusaksli-nc** [comment] 2021-04-13 10:52
Is this on Android or iOS? Have you properly set up the intent filter on Android and added the domain in Xcode?

**Comment by essarn** [comment] 2021-04-13 12:01
The problem occurs on Android and I have not added any intent filters. Is there any documentation on how to do that?

**Comment by markusaksli-nc** [comment] 2021-04-13 12:07
https://firebase.google.com/docs/dynamic-links/android/receive#add-an-intent-filter-for-deep-links

**Comment by essarn** [comment] 2021-04-13 21:54
> https://firebase.google.com/docs/dynamic-links/android/receive#add-an-intent-filter-for-deep-links
> 
> Try to see if this fixes the issue (and if the dynamic link data is received on the flutter side as expected).

That solved the problem by adding the intent filter for my custom domain. The email auth link now correctly opens in the app and the correct link is received. But is there a reason for why manually created deep links with the custom domain worked before adding the intent filter and not email auth links?

**Comment by markusaksli-nc** [comment] 2021-04-14 07:39
It probably has to do with the generated link page that is loaded after you open the dynamic link. For manually created deep links they should try to open the app or redirect if opened on desktop but for email verification links they might default to verifying in-browser.

Not really sure since this behavior is controlled by the Firebase side, not us.

Closing this as solved.

**Closed by markusaksli-nc** 2021-04-14 07:39 UTC
Labels: Needs Attention, type: bug
