### ISSUE TITLE
[Firebase-in_app-messaging] canot run app after installing this to my app. error below

### ISSUE THREAD

**Issue by fusicdesigns** [FirebaseExtended/flutterfire#2954] opened 2020-07-14 15:28 UTC
/Users/chrisstanley/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_in_app_messaging-0.1.2/ios/Classes/FirebaseInAppMessagingPlugin.m:43:50: error: no known class method for selector 'inAppMessaging'
        FIRInAppMessaging *fiam = [FIRInAppMessaging inAppMessaging];
                                                     ^~~~~~~~~~~~~~
    /Users/chrisstanley/tools/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_in_app_messaging-0.1.2/ios/Classes/FirebaseInAppMessagingPlugin.m:44:10: error: property 'automaticDataCollectionEnabled' not found on object of type 'FIRMessaging *'
        fiam.automaticDataCollectionEnabled = [enabled boolValue];
             ^
    12 errors generated.

**Comment by obrunsmann** [comment] 2020-07-15 18:16
Seems like a duplicate for me https://github.com/FirebaseExtended/flutterfire/issues/2151

**Comment by TahaTesser** [comment] 2020-07-16 10:47
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2151

**Closed by TahaTesser** 2020-07-16 10:47 UTC
