### ISSUE TITLE
Firebase Analytics Duplicate Event in Debug View 

### ISSUE THREAD

**Issue by Kravchenko1996** [FirebaseExtended/flutterfire#7858] opened 2022-01-13 13:44 UTC
Hi everyone!
I send event with help of Firebase Analytics 9.0.5 (the latets) in my Flutter app. The problem is that one of the events is duplicated (screenshot #1). I am using the only one function for sending all events (screenshot #2). I am sure it's not triggered in the another part of app (screenshot #3) the same as it's not triggered twice (screenshot #4).
![photo_2022-01-13_15-40-52](https://user-images.githubusercontent.com/63616961/149340820-26358cca-bf2a-4f75-a7b2-66da2a9bf472.jpg)
![image](https://user-images.githubusercontent.com/63616961/149340914-e70756aa-4f0f-40fa-ade7-3f0755e06500.png)
![image](https://user-images.githubusercontent.com/63616961/149341017-459fc70f-3d52-4c7f-bdd7-f91a3052602d.png)
![image](https://user-images.githubusercontent.com/63616961/149341045-bbf5afaf-e543-4a3c-986f-9f1c9051216c.png)
Here are my firebase all dependencies:
  firebase_core: ^1.10.6
  firebase_crashlytics: ^2.4.4
  firebase_core_platform_interface: ^4.2.3
  firebase_performance: ^0.8.0+3
  firebase_messaging: ^11.2.4
  firebase_dynamic_links: ^4.0.3
  firebase_analytics: ^9.0.5
Could we consider it as the bug of Firebase Analytics or the problem is in my code?

**Comment by darshankawar** [comment] 2022-01-14 11:37
@Kravchenko1996 
This looks similar / duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4045.
See [this](https://github.com/FirebaseExtended/flutterfire/issues/4045#issuecomment-999548148) comment from flutterfire team member indicating this behavior isn't specific to analytics plugin but could be an issue / behavior coming from underlying firebase android sdk. 
I am going to close this in favor of the comment as not a plugin issue. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-01-14 11:37 UTC
Labels: type: bug, Needs Attention, in triage
