### ISSUE TITLE
[cloud_firestore] snapshots().listen not getting called

### ISSUE THREAD

**Issue by scarranca** [FirebaseExtended/flutterfire#2544] opened 2020-05-12 18:49 UTC
I'm trying to perform a query and to get real time update to that query, the first time i launched it worked but it always returned me an old value, then i restart the app and the query isn't getting called at all, and it's not giving me any errors.

**To Reproduce**
1. Set rules to give permissions to read that documents.
2.-  Make the query    _firestore.collection('products').where('id',isEqualTo: widget.id).snapshots().listen((event)
//THIS IS NEVER CALLED
})

**Expected behavior**
Get realtime updates on that single document.

**Additional context**
  cloud_firestore: ^0.13.5

**Flutter doctor**
```
[✓] Flutter (Channel stable, v1.17.0, on Mac OS X 10.15.4 19E287, locale en-MX)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.0)
[✓] Connected device (1 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-05-13 14:17
issue exist
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2225

**Closed by TahaTesser** 2020-05-13 14:17 UTC
