### ISSUE TITLE
[firebase_crashlytics] File names are incorrect on Android

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [FirebaseExtended/flutterfire#80] opened 2019-09-02 12:46 UTC
I just noticed that the Dart files in Firebase Crashlytics Android reports from Flutter have `.java` file endings. It is a bit confusing, but I can confirm that these ".java" files are actually the Dart files in my project, i.e. the line numbers match up with what I have in them.  
However, the file names are always `<Dart class name>.java`. For example:

```
GestureRecognizer.invokeCallback (GestureRecognizer.java:182)
TapGestureRecognizer.handleTapUp (TapGestureRecognizer.java:486)
BaseTapGestureRecognizer._checkUp (BaseTapGestureRecognizer.java:282)
```

The Dart files are not named after the classes and definitely do not have a `.java` file extension.

I am not exactly sure why this happens looking at the implementation.

(Moved from https://github.com/flutter/flutter/issues/38718)

**Comment by rinverardi** [comment] 2020-05-15 11:51
Same here. The behavior depends on how the app is built.

$ cd example
$ flutter build apk --debug # [1]
$ flutter build apk --release # [2]
$ flutter build apk --release --no-shrink [3]

For [1] and [3], the stack traces in the Firebase Console are correct. For [2], the stack traces in the Firebase Consoles are incorrect (all the file extensions and some of the filenames are wrong).

**Comment by Nico04** [comment] 2020-05-27 11:05
Any clue on how to fix this ?
Calling --no-shrink is a great workaround but it's easy to forget it when you build a release...

**Comment by SimeonZV** [comment] 2021-03-17 23:14
I started experiencing this issue just yesterday after deploying a new app version with the upgraded firebase_crashlytics library (and all other firebase libs)

firebase_crashlytics: ^0.2.4 - was showing .dart in stack-traces 
firebase_crashlytics: ^1.0.0 - shows .java  in stack-traces

**Comment by Pitazzo** [comment] 2021-03-21 20:53
> Same here. The behavior depends on how the app is built.
> 
> $ cd example
> $ flutter build apk --debug # [1]
> $ flutter build apk --release # [2]
> $ flutter build apk --release --no-shrink [3]
> 
> For [1] and [3], the stack traces in the Firebase Console are correct. For [2], the stack traces in the Firebase Consoles are incorrect (all the file extensions and some of the filenames are wrong).

Passing ` --no-shrink` has any side effect?

**Comment by doc-rj-celltrak** [comment] 2021-03-29 19:45
Here's a screenshot with firebase_crashlytics version 0.2.4. Looks like i need an upgrade, but the behavior is still broken according to comments above. Anyhow, you can see the filename shows as .java only. . The next line .ReportExceptionAction is the class name.

![Screen_Shot_2021-03-29_at_2_35_55_PM](https://user-images.githubusercontent.com/55109813/112890576-aad02e00-909c-11eb-900f-225b7a9ac9ca.png)

**Comment by SimeonZV** [comment] 2021-04-13 22:25
Good news - the problem is resolved for me after upgrading firebase_crashlytics to 2.0.0

**Comment by Salakar** [comment] 2021-04-16 14:50
@SimeonZV thanks for confirming this is now working on the latest release. I'm going to go ahead and close this issue now. Thanks everyone.

**Closed by Salakar** 2021-04-16 14:50 UTC
Labels: impact: customer, platform: android, plugin: crashlytics, type: bug

**Comment by SimeonZV** [comment] 2021-04-17 18:16
@Salakar: I'm sorry, but I was too quick concluding that the problem is solved after upgrading firebase_crashlytics :-( Unfortunately the issue is still there. I just saw the correct stack-traces with .dart coming from the app running in the debug mode and it simply confirmed the point made above in https://github.com/FirebaseExtended/flutterfire/issues/80#issuecomment-629191779. Sorry for this confusion, but this issue should be reopened as I still see .java in crashlytics.

**Comment by doc-rj-celltrak** [comment] 2021-04-17 18:30
The problem still happens when the R8 shrinker is enabled, and it's enabled by default for release builds.

**Comment by Pitazzo** [comment] 2021-04-20 14:46
The problem is definetly still present

**Comment by Pitazzo** [comment] 2021-04-23 17:14
@SimeonZV @doc-rj-celltrak may be we should open a new issue...

**Comment by creativecreatorormaybenot** [comment] 2021-04-23 17:20
@Salakar please **reopen**. This exact issue has not been addressed.
