### ISSUE TITLE
[<firebase_storage>] <upload image for Flutter for Web>

### ISSUE THREAD

**Issue by shinriyo** [FirebaseExtended/flutterfire#2687] opened 2020-06-02 15:52 UTC
**Is your feature request related to a problem? Please describe.**

I want to upload image on FireStorage by `Flutter for Web`
I used `firebase_storage 3.1.6` but I can't.
I hope Web support.

**Describe the solution you'd like**

I'm not sure.

**Additional context**

If I use `firebase_storage 3.1.6` for `Flutter For Web`
it happned.

```
errors.dart:167 Uncaught (in promise) Error: Unsupported operation: _Namespace
    at Object.throw_ [as throw] (errors.dart:216)
    at Function.get _namespace [as _namespace] (io_patch.dart:202)
    at io._File.fromRawPath.existsSync (file_impl.dart:250)
    at firebase_storage.StorageReference.__.putFile (storage_reference.dart:62)
    at uploadPic (banners.dart:251)
    at uploadPic.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at uploadPic (banners.dart:242)
    at banners.dart:262
    at Generator.next (<anonymous>)
    at runBody (async_patch.dart:86)
    at Object._async [as async] (async_patch.dart:125)
    at ink_well.InkWell.new.<anonymous> (banners.dart:241)
    at _InkResponseState.new.[_handleTap] (ink_well.dart:772)
    at ink_well.dart:855
    at tap.TapGestureRecognizer.new.invokeCallback (recognizer.dart:182)
    at tap.TapGestureRecognizer.new.handleTapUp (tap.dart:522)
    at tap.TapGestureRecognizer.new.[_checkUp] (tap.dart:282)
    at tap.TapGestureRecognizer.new.handlePrimaryPointer (tap.dart:217)
    at tap.TapGestureRecognizer.new.handleEvent (recognizer.dart:475)
    at pointer_router.PointerRouter.new.[_dispatch] (pointer_router.dart:76)
    at pointer_router.dart:122
    at LinkedMap.new.forEach (linked_hash_map.dart:23)
    at pointer_router.PointerRouter.new.[_dispatchEventToRoutes] (pointer_router.dart:120)
    at pointer_router.PointerRouter.new.route (pointer_router.dart:106)
    at binding$5.WidgetsFlutterBinding.new.handleEvent (binding.dart:218)
    at binding$5.WidgetsFlutterBinding.new.dispatchEvent (binding.dart:198)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerEvent] (binding.dart:156)
    at binding$5.WidgetsFlutterBinding.new.[_flushPointerEventQueue] (binding.dart:102)
    at binding$5.WidgetsFlutterBinding.new.[_handlePointerDataPacket] (binding.dart:86)
    at Object._invoke1 (window.dart:592)
    at _engine.EngineWindow.new.invokeOnPointerDataPacket (window.dart:238)
    at _engine.PointerBinding.__.[_onPointerData] (pointer_binding.dart:129)
    at pointer_binding.dart:479
    at pointer_binding.dart:440
    at pointer_binding.dart:210
DartError @ errors.dart:167
throw_ @ errors.dart:216
get _namespace @ io_patch.dart:202
existsSync @ file_impl.dart:250
putFile @ storage_reference.dart:61
uploadPic @ banners.dart:250
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
uploadPic @ banners.dart:242
(anonymous) @ banners.dart:262
runBody @ async_patch.dart:86
_async @ async_patch.dart:125
(anonymous) @ banners.dart:214
[_handleTap] @ ink_well.dart:771
(anonymous) @ ink_well.dart:843
invokeCallback @ recognizer.dart:180
handleTapUp @ tap.dart:521
[_checkUp] @ tap.dart:280
handlePrimaryPointer @ tap.dart:216
handleEvent @ recognizer.dart:473
[_dispatch] @ pointer_router.dart:75
(anonymous) @ pointer_router.dart:121
forEach @ linked_hash_map.dart:23
[_dispatchEventToRoutes] @ pointer_router.dart:118
route @ pointer_router.dart:105
handleEvent @ binding.dart:217
dispatchEvent @ binding.dart:196
[_handlePointerEvent] @ binding.dart:155
[_flushPointerEventQueue] @ binding.dart:101
[_handlePointerDataPacket] @ binding.dart:85
_invoke1 @ window.dart:592
invokeOnPointerDataPacket @ window.dart:238
[_onPointerData] @ pointer_binding.dart:129
(anonymous) @ pointer_binding.dart:479
(anonymous) @ pointer_binding.dart:440
(anonymous) @ pointer_binding.dart:210
Promise.then (async)
_scheduleImmediateWithPromise @ async_patch.dart:169
_scheduleImmediate @ async_patch.dart:138
_scheduleAsyncCallback @ schedule_microtask.dart:73
_rootScheduleMicrotask @ zone.dart:1245
scheduleMicrotask @ zone.dart:1459
[_asyncCompleteWithValue] @ future_impl.dart:561
[_asyncComplete] @ future_impl.dart:554
complete @ future_impl.dart:43
[_complete] @ ticker.dart:379
ticker$.TickerFuture.complete @ ticker.dart:375
[_animateToInternal] @ animation_controller.dart:590
reverse @ animation_controller.dart:495
deactivate @ ink_highlight.dart:92
updateHighlight @ ink_well.dart:650
[_handleTap] @ ink_well.dart:767
(anonymous) @ ink_well.dart:843
invokeCallback @ recognizer.dart:180
handleTapUp @ tap.dart:521
[_checkUp] @ tap.dart:280
handlePrimaryPointer @ tap.dart:216
handleEvent @ recognizer.dart:473
[_dispatch] @ pointer_router.dart:75
(anonymous) @ pointer_router.dart:121
forEach @ linked_hash_map.dart:23
[_dispatchEventToRoutes] @ pointer_router.dart:118
route @ pointer_router.dart:105
handleEvent @ binding.dart:217
dispatchEvent @ binding.dart:196
[_handlePointerEvent] @ binding.dart:155
[_flushPointerEventQueue] @ binding.dart:101
[_handlePointerDataPacket] @ binding.dart:85
_invoke1 @ window.dart:592
invokeOnPointerDataPacket @ window.dart:238
[_onPointerData] @ pointer_binding.dart:129
(anonymous) @ pointer_binding.dart:479
(anonymous) @ pointer_binding.dart:440
(anonymous) @ pointer_binding.dart:210
Show 43 more frames
```

**Comment by TahaTesser** [comment] 2020-06-03 09:57
Hi @shinriyo 
Looks like `firebase_storage` isn't for web yet
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1972

**Closed by TahaTesser** 2020-06-03 09:57 UTC
