### ISSUE TITLE
BUG [cloud_firestore]: App could not be installed on IOS simulator, once cloud_firestore is added

### ISSUE THREAD

**Issue by baxri** [FirebaseExtended/flutterfire#4262] opened 2020-11-29 17:18 UTC
I created new flutter application with the following command

```
flutter create testapp
```

then added cloud_firestore dependencie

```
dependencies:
  cloud_firestore: ^0.14.3+1
```

When trying to run application it throw following error. from terminal and also same from xcode

```
This app could not be installed at this time.
Domain: IXUserPresentableErrorDomain
Code: 1
Failure Reason: Could not install at this time.
Recovery Suggestion: Failed to load Info.plist from bundle at path /Users/mac/Library/Developer/CoreSimulator/Devices/3AC428EF-B059-4729-86CE-304EF2760826/data/Library/Caches/com.apple.mobile.installd.staging/temp.LKpV2s/extracted/Runner.app/Frameworks/grpcpp.framework
--
Failed to load Info.plist from bundle at path /Users/mac/Library/Developer/CoreSimulator/Devices/3AC428EF-B059-4729-86CE-304EF2760826/data/Library/Caches/com.apple.mobile.installd.staging/temp.LKpV2s/extracted/Runner.app/Frameworks/grpcpp.framework
Domain: MIInstallerErrorDomain
Code: 35
User Info: {
    FunctionName = "-[MIBundle _validateWithError:]";
    LegacyErrorString = PackageInspectionFailed;
    SourceFileLine = 39;
}
--


System Information

macOS Version 10.15.6 (Build 19G2021)
Xcode 12.2 (17535) (Build 12B45b)
Timestamp: 2020-11-29T21:15:01+04:00
```

**Comment by TahaTesser** [comment] 2020-11-30 14:26
Hi @baxri 
Just tried to reproduce the issue following your steps, apps run fine without modifying main.dart, are you call firestore code? 
In that case, you need to do a complete iOS flutterfire setup https://flutter-firebase-docs.web.app/docs/installation/ios and add Google services plist file 

```bash
[ +514 ms] executing: xcrun simctl install BBCEDCF6-A80B-49DC-86EE-C9B542A9AD1B
/Users/tahatesser/AndroidStudioProjects/myapp/build/ios/iphonesimulator/Runner.app
[+1904 ms] executing: /usr/bin/plutil -convert json -o -
/Users/tahatesser/AndroidStudioProjects/myapp/build/ios/iphonesimulator/Runner.app/Info.plist
[  +10 ms] Exit code 0 from: /usr/bin/plutil -convert json -o -
/Users/tahatesser/AndroidStudioProjects/myapp/build/ios/iphonesimulator/Runner.app/Info.plist
[        ]
{"CFBundleName":"myapp","DTXcode":"1220","DTSDKName":"iphonesimulator14.2","UILaunchStoryboardName":"LaunchScreen","CFBundleIcons~
ipad":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60","AppIcon76x76","App
Icon83.5x83.5"],"CFBundleIconName":"AppIcon"}},"DTSDKBuild":"18B79","CFBundleDevelopmentRegion":"en","CFBundleVersion":"1","BuildM
achineOSBuild":"20B29","DTPlatformName":"iphonesimulator","CFBundlePackageType":"APPL","UIMainStoryboardFile":"Main","CFBundleSupp
ortedPlatforms":["iPhoneSimulator"],"CFBundleShortVersionString":"1.0.0","CFBundleInfoDictionaryVersion":"6.0","CFBundleExecutable
":"Runner","DTCompiler":"com.apple.compilers.llvm.clang.1_0","UISupportedInterfaceOrientations~ipad":["UIInterfaceOrientationPortr
ait","UIInterfaceOrientationPortraitUpsideDown","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"Min
imumOSVersion":"9.0","CFBundleIdentifier":"com.example.myapp","UIDeviceFamily":[1,2],"DTPlatformVersion":"14.2","CFBundleSignature
":"????","CFBundleIcons":{"CFBundlePrimaryIcon":{"CFBundleIconFiles":["AppIcon20x20","AppIcon29x29","AppIcon40x40","AppIcon60x60"]
,"CFBundleIconName":"AppIcon"}},"DTXcodeBuild":"12B45b","LSRequiresIPhoneOS":true,"UISupportedInterfaceOrientations":["UIInterface
OrientationPortrait","UIInterfaceOrientationLandscapeLeft","UIInterfaceOrientationLandscapeRight"],"UIViewControllerBasedStatusBar
Appearance":false,"NSBonjourServices":["_dartobservatory._tcp"],"DTPlatformBuild":"18B79","NSLocalNetworkUsageDescription":"Allow
Flutter tools on your computer to connect and debug your application. This prompt will not appear on release builds."}
[   +8 ms] executing: xcrun simctl launch BBCEDCF6-A80B-49DC-86EE-C9B542A9AD1B com.example.myapp --enable-dart-profiling
--enable-checked-mode --verify-entry-points --observatory-port=0
[ +563 ms] com.example.myapp: 60145
[        ] Waiting for observatory port to be available...
[+1147 ms] Observatory URL on device: http://127.0.0.1:59230/HR1IsFEQygs=/
[   +5 ms] Caching compiled dill
[ +102 ms] Connecting to service protocol: http://127.0.0.1:59230/HR1IsFEQygs=/
[   +1 ms] DDS is currently disabled due to https://github.com/flutter/flutter/issues/62507
[ +134 ms] Successfully connected to service protocol: http://127.0.0.1:59230/HR1IsFEQygs=/
[        ] Waiting for iPhone 12 to report its views...
[   +8 ms] Waiting for iPhone 12 to report its views... (completed in 7ms)
[   +8 ms] DevFS: Creating new filesystem on the device (null)
[  +11 ms] DevFS: Created new filesystem on the device
(file:///Users/tahatesser/Library/Developer/CoreSimulator/Devices/BBCEDCF6-A80B-49DC-86EE-C9B542A9AD1B/data/Containers/Data/Applic
ation/7C003E78-A191-4950-877F-B25B35B8D226/tmp/myapp9yGhLu/myapp/)
[   +2 ms] Updating assets
[ +201 ms] Syncing files to device iPhone 12...
[   +3 ms] Scanning asset files
[   +5 ms] <- reset
[        ] Compiling dart to kernel with 0 updated files
[   +3 ms] <- recompile package:myapp/main.dart 39bf21a5-6e1a-401e-a318-6abd3779653a
[        ] <- 39bf21a5-6e1a-401e-a318-6abd3779653a
[ +289 ms] Updating files
[  +83 ms] DevFS: Sync finished
[        ] Syncing files to device iPhone 12... (completed in 386ms)
[        ] Synced 1.8MB.
[   +1 ms] <- accept
[   +1 ms] Connected to _flutterView/0x7fb761837220.
[   +1 ms] Flutter run key commands.
[   +2 ms] r Hot reload. 🔥🔥🔥
[   +1 ms] R Hot restart.
[        ] h Repeat this help message.
[        ] d Detach (terminate "flutter run" but leave application running).
[        ] c Clear the screen
[        ] q Quit (terminate the application on the device).
[        ] An Observatory debugger and profiler on iPhone 12 is available at: http://127.0.0.1:59230/HR1IsFEQygs=/
```

<details> 
<summary>flutter doctor -v</summary> 

```bash
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-GB)
    • Flutter version 1.22.4 at /Users/tahatesser/Code/flutter_stable
    • Framework revision 1aafb3a8b9 (2 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Volumes/Extreme/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.10.0

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • RMX2001 (mobile)                   • EUYTFEUSQSRGDA6D
      • android-arm64 • Android 10 (API 29)
    • Android SDK built for x86 (mobile) • emulator-5554
      • android-x86   • Android 8.0.0 (API 26) (emulator)
    • iPhone 12 (mobile)                 • BBCEDCF6-A80B-49DC-86EE-C9B542A9AD1B
      • ios           • com.apple.CoreSimulator.SimRuntime.iOS-14-2 (simulator)

! Doctor found issues in 1 category.
```

</details>

**Comment by baxri** [comment] 2020-12-02 08:46
Hey @TahaTesser . Thanks for your response. I am not modifying marin.dart file. I am not calling anything in the code, just adding this new dependencie on fresh flutter app (cloud_firestore: ^0.14.3+1) and thats it. App stops running on simulator. :|

**Comment by TahaTesser** [comment] 2020-12-02 09:49
Hi @baxri 
Can you please complete the setup for iOS and try again? add your Googleservice.plist, etc

**Comment by baxri** [comment] 2020-12-02 18:31
@TahaTesser I tried and getting same error. then I added "firebase_core: ^0.5.2+1" as dependencie and it works now. So when we using firebase we need both

`firebase_core` and `cloud_firestore `

???

**Comment by TahaTesser** [comment] 2020-12-03 11:27
Hi @baxri 
Yes, we do, core is required since https://pub.dev/packages/cloud_firestore/changelog#0140
Given your last message I feel safe to close this issue if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-12-03 11:27 UTC
Labels: Needs Attention
