### ISSUE TITLE
Google gms version conflict in android when using firebase_core

### ISSUE THREAD

**Issue by Faiyyazauxy** [FirebaseExtended/flutterfire#4362] opened 2020-12-10 05:47 UTC
## Bug report

**Describe the bug**
When i add the firebase_core package to my project and i try to build the app then i get the following error

```
Could not resolve com.google.android.gms:play-services-basement:[15.0.0,16.0.0).
```

### Steps to reproduce

1. Add any package which have gms used internally
2. Add firebase_core package
3. Try to build release app

### Expected behavior

The conflict should not happen or atleast there should be a way to avoid such issues
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_IN)
    • Flutter version 1.22.4 at /home/faiyyaz/snap/flutter/common/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /home/faiyyaz/Android/Sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /usr/bin/java
    • Java version Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
    • All Android licenses accepted.

[!] Android Studio (not installed)
    • Android Studio not found; download from https://developer.android.com/studio/index.html
      (or visit https://flutter.dev/docs/get-started/install/linux#android-setup for detailed instructions).

[!] VS Code (version 1.51.1)
    • VS Code at /usr/share/code
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected device
    ! No devices available

! Doctor found issues in 3 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.4
kyc_sample 1.0.0+1

dependencies:
- cupertino_icons 1.0.0
- dio_cookie_manager 1.0.0 [cookie_jar dio]
- dotted_line 2.0.2 [flutter]
- easy_localization 2.3.3 [flutter intl shared_preferences args path flutter_localizations]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.7+14 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- imei_plugin 1.2.0 [flutter]
- kyc_sdk 0.0.1 [flutter]
- percent_indicator 2.1.8 [flutter]
- phone_number 0.8.1 [meta flutter]
- qr_code_scanner 0.0.13 [flutter]
- translator 0.1.5 [http]
- uuid 2.2.2 [crypto convert]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- cookie_jar 1.0.1
- crypto 2.1.5 [collection convert typed_data]
- dio 3.0.10 [http_parser path]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
```

</details>

---

**Comment by darshankawar** [comment] 2020-12-10 09:37
@Faiyyazauxy 
Tried your steps mentioned above in sample app which already has gms implementation:

`apply plugin: 'com.google.gms.google-services'`

Then I added latest `firebase_core` plugin and ran `flutter build apk` which compiled and built apk properly:

```
Removed unused resources: Binary resource data reduced from 221KB to 198KB: Removed 10%
Running Gradle task 'assembleRelease'...                                
Running Gradle task 'assembleRelease'... Done                      59.4s
✓ Built build/app/outputs/flutter-apk/app-release.apk (17.1MB).
dhs@Dhss-MacBook-Pro firebase_messaging_example % 

```

```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  firebase_messaging: ^7.0.3
  firebase_core: ^0.5.3
```

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.4 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • sdk gphone x86 arm (mobile)         • emulator-5554
      • android-x86 • Android 11 (API 30) (emulator)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!

```

</details>

Can you provide a complete minimal complete reproducible code sample along with app level and project level `build.gradle` ?

**Comment by Faiyyazauxy** [comment] 2020-12-10 09:41
@darshankawar Mine is happening if plugin has different version. Example one of my plugin has 15.0.0 and one has 17.0.0

**Comment by Faiyyazauxy** [comment] 2020-12-10 09:56
@darshankawar the exact error log of the issue

```
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Could not determine the dependencies of task ':app:lintVitalRelease'.   
> Could not resolve all artifacts for configuration ':app:debugAndroidTestRuntimeClasspath'.
   > Could not resolve com.google.android.gms:play-services-base:[15.0.0,16.0.0).
     Required by:                                                       
         project :app > com.google.android.gms:play-services-vision:15.0.0
         project :app > com.google.android.gms:play-services-vision-common:15.0.0
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Unable to load Maven meta-data from https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml'. Received status code 401 from server: Unauthorized
   > Could not resolve com.google.android.gms:play-services-basement:[15.0.0,16.0.0).
     Required by:                                                       
         project :app > com.google.android.gms:play-services-vision:15.0.0
         project :app > com.google.android.gms:play-services-vision-common:15.0.0
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 401 from server: Unauthorized
   > Could not resolve com.google.android.gms:play-services-base:[15.0.1,16.0.0).
     Required by:                                                       
         project :app > com.google.android.gms:play-services-clearcut:15.0.1
         project :app > com.google.android.gms:play-services-phenotype:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Unable to load Maven meta-data from https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml'. Received status code 401 from server: Unauthorized
   > Could not resolve com.google.android.gms:play-services-basement:[15.0.1,16.0.0).
     Required by:                                                       
         project :app > com.google.android.gms:play-services-clearcut:15.0.1
         project :app > com.google.android.gms:play-services-phenotype:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 401 from server: Unauthorized
   > Could not resolve com.google.android.gms:play-services-tasks:[15.0.1,16.0.0).
     Required by:                                                       
         project :app > com.google.android.gms:play-services-clearcut:15.0.1
         project :app > com.google.android.gms:play-services-phenotype:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-tasks.
         > Unable to load Maven meta-data from https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-tasks/maven-metadata.xml.
            > Could not get resource 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-tasks/maven-metadata.xml'.
               > Could not GET 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-tasks/maven-metadata.xml'. Received status code 401 from server: Unauthorized
   > Could not resolve com.google.android.gms:play-services-base:[15.0.1].
     Required by:                                                       
         project :app > com.google.android.gms:play-services-flags:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-base.
         > Unable to load Maven meta-data from https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml'. Received status code 401 from server: Unauthorized
   > Could not resolve com.google.android.gms:play-services-basement:[15.0.1].
     Required by:                                                       
         project :app > com.google.android.gms:play-services-flags:15.0.1
      > Failed to list versions for com.google.android.gms:play-services-basement.
         > Unable to load Maven meta-data from https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-basement/maven-metadata.xml.
            > Could not get resource 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-basement/maven-metadata.xml'.
               > Could not GET 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-basement/maven-metadata.xml'. Received status code 401 from server: Unauthorized
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org   
```

**Comment by ekasetiawans** [comment] 2020-12-10 10:13
@Faiyyazauxy looks like you have used a custom repository

**Comment by Faiyyazauxy** [comment] 2020-12-10 11:22
> @Faiyyazauxy looks like you have used a custom repository
> 
> afaik https://repo.aadhaarbridge.com is not one of the original repositories.

Yes it is a custom repository.

**Comment by darshankawar** [comment] 2020-12-10 11:48
@Faiyyazauxy 
If you remove this custom repo and try again, do you still get the error ?
All the errors are pointing to that repo:

```
Unable to load Maven meta-data from https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml.
            > Could not get resource 'https://repo.aadhaarbridge.com/repository/android-sdk/com/google/android/gms/play-services-base/maven-metadata.xml'.
               > Could not GET 'https://repo.aadhaarbridge.com/repository/android
```
If you are not getting the error after removing it, then it could indicate an issue with that custom repo.

**Comment by Faiyyazauxy** [comment] 2020-12-10 11:50
@darshankawar No i don't get any error after removing the dependency

**Comment by darshankawar** [comment] 2020-12-10 11:57
@Faiyyazauxy Thanks for verifying. It indicates this is not an issue with Firebase core, but with the repo you are using and you may have to open this issue in that repo.
Closing from here.

**Closed by darshankawar** 2020-12-10 11:57 UTC
Labels: Needs Attention
