### ISSUE TITLE
Firebase Realtime - Implement ServerValue.increment

### ISSUE THREAD

**Issue by zenkog** [FirebaseExtended/flutterfire#3108] opened 2020-08-06 02:13 UTC
**Is your feature request related to a problem? Please describe.**
ServerValue.increment is available but is not implemented here

**Describe the solution you'd like**
Being able to use ServerValue.increment as atomic process from Flutter

**Additional context**
Transaction is an atomic process but it has to read the data first before incrementing. So we want to be able to increment simultaneously when there are concurrent connections without first reading the value. Makes things faster and more efficient.

**Comment by puf** [comment] 2020-08-06 03:41
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2437

**Closed** 2020-08-26 22:25 UTC
Labels: plugin: database, type: enhancement
