### ISSUE TITLE
Error on Background Messages - PluginRegistry cannot be converted to FlutterEngine

### ISSUE THREAD

**Issue by OrlinAlvarado** [FirebaseExtended/flutterfire#2664] opened 2020-05-29 13:43 UTC
I try to implement de this plugin, but I followed all the steps, a It didn't work.
https://pub.dev/packages/firebase_messaging

- Remember that in new Versions of Flutter projects there is not MainActivity.java File, now we have a file called MainActivity.java

This is the original Code for Application.java is:

```java
package io.flutter.plugins.firebasemessagingexample;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
    GeneratedPluginRegistrant.registerWith(registry);
  }
}
```

**I changed for**

```java
package com.example.push_local;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  @Override
    public void registerWith(PluginRegistry registry) {
      FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
    }
}
```

**This is the changed line:**
```java
FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
```

**Comment by TahaTesser** [comment] 2020-06-02 13:03
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2055

**Closed by TahaTesser** 2020-06-02 13:03 UTC
