### ISSUE TITLE
Error while signInWithCredential is used with Google Credential

### ISSUE THREAD

**Issue by DCodez804** [FirebaseExtended/flutterfire#5785] opened 2021-04-15 15:29 UTC
![Screenshot (1)](https://user-images.githubusercontent.com/52531507/114895248-f9b3ec80-9e2c-11eb-8fde-16d9915c1d49.png)
Google user is getting created successfully but when using the auth credential from GoogleAuthProvider in the method signInWithCredential , the following error is thrown.

**Comment by markusaksli-nc** [comment] 2021-04-16 14:32
Hi @DCodez804 
When opening an issue, please try to provide all of the information indicated in the template and refrain from using screenshots as they make the issue harder to search for.
Closing this issue, since the issue is too ambiguous.
Thank you.

**Closed by markusaksli-nc** 2021-04-16 14:32 UTC
