### ISSUE TITLE
🐛 [firebase_messaging] Error when getting the FCM token in ^8.0.0-dev.7

### ISSUE THREAD

**Issue by GyuriMajercsik** [FirebaseExtended/flutterfire#4088] opened 2020-11-11 09:30 UTC
## Bug report

I found the following error in Crashlytics on a Nexus 5X with Android 6.0.1 

```
Non-fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: type '_InternalLinkedHashMap<dynamic, dynamic>' is not a subtype of type 'String' in type cast
       at .platformExceptionToFirebaseException(.java:26)
       at .convertPlatformException(.java:15)
       at MethodChannelFirebaseMessaging.getToken(MethodChannelFirebaseMessaging.java:227)
       at ._asyncErrorWrapperHelper(.java)
       at .startApplication(.java:190)
       at ._asyncThenWrapperHelper(.java)
       at main.<fn>(main.java:38)
       at Chain.capture(Chain.java)
       at main.<fn>(main.java:37)
       at _installCrashlytics.<fn>(_installCrashlytics.java:49)
       at _installCrashlytics.<fn>(_installCrashlytics.java:48)
       at .runZoned(.java)
       at ._installCrashlytics(.java:48)

```

**Comment by markusaksli-nc** [comment] 2020-11-11 10:44
Hi @GyuriMajercsik 
Could you share your `flutter pub deps -- --style=compact` and `flutter doctor -v` logs?
Could the issue be with your own code?
Thank you

**Comment by paynekw** [comment] 2020-11-11 10:53
Looks like it's related to #4048 which was merged in 8.0.0-dev.6.
https://github.com/FirebaseExtended/flutterfire/pull/4048/commits/c8d9adf939c23902f8f491042ac0699c8d7336be

**Comment by GyuriMajercsik** [comment] 2020-11-11 11:24
<details><summary>flutter doctor</summary>

```
[✓] Flutter (Channel beta, 1.23.0-18.1.pre, on Mac OS X 10.15.7 19H2 x86_64, locale en-GB)
    • Flutter version 1.23.0-18.1.pre at /Users/gyuri/tools/flutter
    • Framework revision 198df796aa (4 weeks ago), 2020-10-15 12:04:33 -0700
    • Engine revision 1d12d82d9c
    • Dart version 2.11.0 (build 2.11.0-213.1.beta)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/gyuri/Library/Android/sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.9.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)


[✓] VS Code (version 1.50.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (3 available)
    • Web Server (web)      • web-server                • web-javascript • Flutter Tools
    • Chrome (web)          • chrome                    • web-javascript • Google Chrome 86.0.4240.193

• No issues found!

```

</details>

<details><summary>flutter pub deps</summary>

```
Dart SDK 2.11.0-213.1.beta
Flutter SDK 1.23.0-18.1.pre

dependencies:
- after_layout 1.0.7+2 [flutter]
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- connectivity 2.0.1 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- country_pickers 1.3.0 [flutter]
- cupertino_icons 0.1.3
- device_id 0.2.0 [flutter]
- device_info 1.0.0 [flutter device_info_platform_interface]
- dio 3.0.10 [http_parser path]
- enum_to_string 1.0.13
- equatable 1.2.5 [collection meta]
- firebase_analytics 6.2.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.3 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_dynamic_links 0.6.2 [flutter firebase_core]
- firebase_messaging 8.0.0-dev.7 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface]
- firebase_remote_config 0.4.2 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.1.0 [flutter bloc provider]
- flutter_cupertino_date_picker 1.0.26+2 [flutter]
- flutter_cupertino_localizations 1.0.1 [flutter flutter_localizations]
- flutter_keyboard_visibility 3.3.0 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_secure_storage 3.3.5 [meta flutter]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- get_it 4.0.4 [async meta]
- google_fonts 1.1.1 [flutter http path_provider crypto pedantic]
- google_maps_flutter 1.0.6 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- http 0.12.2 [http_parser path pedantic]
- logging 0.11.4
- meta 1.3.0-nullsafety.5
- package_info 0.4.3+2 [flutter]
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- stack_trace 1.10.0-nullsafety.5 [path]
- store_redirect 1.0.2 [flutter]
- stripe_payment 1.0.8 [flutter]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- video_player 1.0.0 [meta video_player_platform_interface video_player_web flutter]
- webview_flutter 1.0.6 [flutter]

dev dependencies:
- bloc_test 7.0.6 [bloc test meta mockito]
- flutter_driver 0.0.0 [file json_rpc_2 meta path web_socket_channel vm_service_client webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async matcher platform process pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_launcher_icons 0.7.5 [image args yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- test 1.16.0-nullsafety.7 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

dependency overrides:
- flutter_cupertino_date_picker 1.0.26+2 [flutter]
- platform 3.0.0-nullsafety.1

transitive dependencies:
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.2 [collection]
- bloc 6.1.0 [meta]
- boolean_selector 2.1.0-nullsafety.2 [source_span string_scanner]
- build 1.5.0 [analyzer async convert crypto logging meta path glob]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.4
- charcode 1.2.0-nullsafety.2
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.2
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.4
- connectivity_for_web 0.3.1+2 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+5 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- coverage 0.14.1 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0-nullsafety.2 [clock collection]
- ffi 0.1.3
- file 6.0.0-nullsafety.3 [meta path]
- firebase 7.3.2 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.3 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_messaging_platform_interface 1.0.0-dev.5 [flutter meta firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.0.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [json_rpc_2 process web_socket_channel flutter_test flutter_driver archive args async boolean_selector charcode clock collection convert crypto fake_async file matcher meta path platform pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math vm_service_client webdriver]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_maps_flutter_platform_interface 1.0.4 [flutter meta plugin_platform_interface stream_transform]
- html 0.14.0+4 [csslib source_span]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.18 [archive xml meta]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.3-nullsafety.2
- json_rpc_2 2.2.2 [stack_trace stream_channel]
- matcher 0.12.10-nullsafety.2 [stack_trace]
- mime 0.9.7
- mockito 4.1.2 [analyzer build code_builder collection dart_style matcher meta source_gen test_api]
- nested 0.0.4 [flutter]
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- node_preamble 1.4.12
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.2
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.21 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.10.0-nullsafety.1
- petitparser 3.1.0 [meta]
- plugin_platform_interface 1.0.3 [meta]
- pool 1.5.0-nullsafety.1 [async stack_trace]
- process 4.0.0-nullsafety.3 [file path platform]
- provider 4.3.2+2 [flutter nested collection]
- pub_semver 1.4.4 [collection]
- quiver 2.1.3 [matcher meta]
- rxdart 0.24.1
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.0 [path shelf shelf_static]
- shelf_static 0.2.8 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0-nullsafety.2 [path stack_trace source_maps]
- source_maps 0.10.10-nullsafety.1 [source_span]
- source_span 1.8.0-nullsafety.3 [charcode collection path term_glyph]
- sqflite 1.3.1+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stream_channel 2.1.0-nullsafety.2 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.2 [charcode source_span]
- sync_http 0.2.0
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.2
- test_api 0.2.19-nullsafety.4 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.12-nullsafety.7 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.0-nullsafety.4 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.4
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- vm_service 5.2.0 [meta]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 0.7.3 [logging]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```
</details>

**Comment by Salakar** [comment] 2020-11-11 11:27
This is an old error based on it coming from Crashlytics console, this was fixed in the latest release as @paynekw mentioned. Could you update, thanks.

**Closed by Salakar** 2020-11-11 11:27 UTC
Labels: Needs Attention, type: bug

**Comment by GyuriMajercsik** [comment] 2020-11-11 11:30
@Salakar , could you please confirm that this is fixed in ^8.0.0-dev.8 ? 
@paynekw mentioned that it might be related to a merge in 8.0.0-dev.6 which is an older version than ^8.0.0-dev.7 (the one I'm using)

**Comment by muccy** [comment] 2020-11-25 08:41
I am planning to make a release containing 8.0.0-dev.9 in the coming days. If I'll spot a drop of problems on Crashlytics, I'll be back to report the bug is really solved

**Comment by Salakar** [comment] 2020-11-25 10:25
Can confirm this was fixed

**Comment by lijy91** [comment] 2020-11-26 12:15
@Salakar same problem

**Comment by muccy** [comment] 2020-11-30 17:27
Sadly I've still bug reports coming from Crashlytics after updating to 8.0.0-dev.9. In the next days I'll report if there are less errors

**Comment by muccy** [comment] 2020-12-03 17:46
It's better, much better, but the issue is still there, as you can see there:
![image](https://user-images.githubusercontent.com/18466/101067350-bd77a200-3597-11eb-8fc7-1f406a7bb072.png)
