### ISSUE TITLE
firebase_admob Appstore requirement

### ISSUE THREAD

**Issue by duge86** [FirebaseExtended/flutterfire#2546] opened 2020-05-13 07:41 UTC
Appstore requires WKWebView instead of UIWebview, however before the versions of 7.55.0 admob versions this is not sufficient, therefore we cant publish new apps with the current versions. Please use a version newer than 7.55.0 in the next update.

**Comment by blasten** [comment] 2020-05-15 00:25
@bparrishMines is this a requirement of the AdMob SDK or us?

**Comment by blasten** [comment] 2020-05-15 00:30
Internal bug:  b/140559063

**Comment by blasten** [comment] 2020-05-15 00:50
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2232

**Closed** 2020-05-15 00:50 UTC
Labels: platform: ios, plugin: admob
