### ISSUE TITLE
🐛 [cloud_firestore] Adding a document hangs when device is in airplane mode

### ISSUE THREAD

**Issue by mentoc3000** [FirebaseExtended/flutterfire#3842] opened 2020-10-11 16:01 UTC
## Bug report

**Describe the bug**
When a device is in airplane mode, `add`ing a document to a collection hangs and does not return. If the app is restarted, that addition will appear, but [`set`](https://github.com/FirebaseExtended/flutterfire/blob/2273334b4d661850f5120b5b3c96bb617a964d05/packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart#L45) within `add` never returns its `await`ed value.

### Steps to reproduce

1. Clone the [demo app](https://github.com/mentoc3000/firestore-airplane-test)
1. Run the app
2. Go into airplane mode
3. Tap the FAB
4. Observe: `onPressed` hangs at [line 50](https://github.com/mentoc3000/firestore-airplane-test/blob/5a6c68ddec9eaa7b45a7ba727ea7ac77869d627b/lib/main.dart#L50) and never prints the snapshot data at [line 64](https://github.com/mentoc3000/firestore-airplane-test/blob/5a6c68ddec9eaa7b45a7ba727ea7ac77869d627b/lib/main.dart#L64).

<details><summary>Command line output</summary>

```
Restarted application in 877ms.
W/irestoreexampl( 6855): Accessing hidden method Ldalvik/system/CloseGuard;->close()V (greylist,core-platform-api, linking, allowed)
W/DynamiteModule( 6855): Local module descriptor class for providerinstaller not found.
I/DynamiteModule( 6855): Considering local module providerinstaller:0 and remote module providerinstaller:0
W/ProviderInstaller( 6855): Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.

════════ Exception caught by image resource service ════════════════════════════
The following ArgumentError was thrown resolving an image codec:
Invalid argument(s): No host specified in URI file:///

When the exception was thrown, this was the stack
#0      _HttpClient._openUrl  (dart:_http/http_impl.dart:2313:9))
#1      _HttpClient.getUrl  (dart:_http/http_impl.dart:2208:48))
#2      NetworkImage._loadAsync 
package:flutter/…/painting/_network_image_io.dart:90
#3      NetworkImage.load 
package:flutter/…/painting/_network_image_io.dart:51
#4      ImageProvider.resolveStreamForKey.<anonymous closure> 
package:flutter/…/painting/image_provider.dart:505
...
Image provider: NetworkImage("", scale: 1.0)

```

</details>

### Expected behavior

`onPressed` should complete and print the data from the snapshot obtained from the cache.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 1.20.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
    • Flutter version 1.20.3 at C:\git\flutter
    • Framework revision 216dee60c0 (6 weeks ago), 2020-09-01 12:24:47 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\jpshe\AppData\Local\Android\sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.50.0)
    • VS Code at C:\Users\jpshe\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.15.0

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.9.2
Flutter SDK 1.20.3
cloud_firestore_example 0.0.0

dependencies:
- cloud_firestore 0.14.1+3 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- firebase_core 0.5.0+1 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- drive 0.0.1-6.0.pre [test_api flutter_test flutter_driver cli_util stack_trace universal_platform source_map_stack_trace flutter]
- flutter_driver 0.0.0 [file json_rpc_2 meta path web_socket_channel vm_service_client webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async intl matcher platform process pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- pedantic 1.9.0
- test 1.15.2 [analyzer async boolean_selector coverage http http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 7.0.0 [meta]
- analyzer 0.39.17 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.4.2 [collection]
- boolean_selector 2.0.0 [source_span string_scanner]
- characters 1.0.0
- charcode 1.1.3
- cli_util 0.1.4 [path]
- clock 1.0.1 [meta]
- cloud_firestore_platform_interface 2.1.2 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.0+4 [flutter flutter_web_plugins firebase http_parser meta firebase_core cloud_firestore_platform_interface js]
- collection 1.14.13
- convert 2.1.1 [charcode typed_data]
- coverage 0.14.1 [args logging package_config path source_maps stack_trace vm_service]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- fake_async 1.1.0 [clock collection]
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [json_rpc_2 process web_socket_channel flutter_test flutter_driver archive args async boolean_selector charcode clock collection convert crypto fake_async file intl matcher meta path platform pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math vm_service_client webdriver]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- html 0.14.0+4 [csslib source_span]
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_rpc_2 2.2.1 [stack_trace stream_channel]
- logging 0.11.4
- matcher 0.12.8 [stack_trace]
- meta 1.1.8
- mime 0.9.7
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- node_preamble 1.4.12
- package_config 1.9.3 [path charcode]
- path 1.7.0
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- quiver 2.1.3 [matcher meta]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 2.0.0 [path shelf shelf_static]
- shelf_static 0.2.8 [convert http_parser mime path shelf]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.0.0 [path stack_trace source_maps]
- source_maps 0.10.9 [source_span]
- source_span 1.7.0 [charcode collection meta path term_glyph]
- stack_trace 1.9.5 [path]
- stream_channel 2.0.0 [async]
- string_scanner 1.0.5 [charcode meta source_span]
- sync_http 0.2.0
- term_glyph 1.1.0
- test_api 0.2.17 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.10 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.2.0 [collection]
- universal_platform 0.1.3
- vector_math 2.0.8
- vm_service 4.2.0 [meta]
- vm_service_client 0.2.6+2 [async collection json_rpc_2 pub_semver source_span stack_trace stream_channel web_socket_channel]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 0.7.3 [logging]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by Ehesp** [comment] 2020-10-14 13:25
This is intended behaviour, it's just not very well documented/clear.

Basically the Future will only resolve if it's successfully writes to the Firebase servers (on both add/set/update). However, the record should be updated locally, which means any listeners will fire and your app should still update. 

If you're working with async/await, this might trip you up:

```dart
someOnClickButtonHander() async {
  // validate
  await ref.add({...});
  // show some success UI
}
```

In this case, you will be blocked if offline and the "show some success UI" code won't be executed. You can get around this though:

```dart
someOnClickButtonHander() {
  // validate
 ref.add({...}).then(() {
   // Added & is on live servers
 });
  // show some success UI
}
```

**Comment by dackers86** [comment] 2020-10-14 13:39
Thanks @Ehesp.

Closing for now

**Closed by dackers86** 2020-10-14 13:39 UTC
Labels: Needs Attention, type: bug
