### ISSUE TITLE
[crashlytics]: Building iOS not possible

### ISSUE THREAD

**Issue by Ahmadre** [FirebaseExtended/flutterfire#5354] opened 2021-03-16 04:17 UTC
![Bildschirmfoto 2021-03-16 um 05 14 45](https://user-images.githubusercontent.com/18512224/111255083-b2142800-8616-11eb-8c0b-352b4af8e607.png)

```yaml
  firebase_core: ^1.0.1
  firebase_crashlytics: ^1.0.0
```

Same configuration works for android without problems

**Comment by Ahmadre** [comment] 2021-03-16 04:21
And no this: https://github.com/FirebaseExtended/flutterfire/issues/3272 didn't help because I use the very latest versions...

**Comment by markusaksli-nc** [comment] 2021-03-16 11:09
Hi @Ahmadre 
Please take a look at https://github.com/FirebaseExtended/flutterfire/issues/5284 https://github.com/FirebaseExtended/flutterfire/issues/5059
The issue seems to be caused by something in Xcode cache that previously people have been able to solve by just replacing the ios directory with a new one created with swift.
You can still try to run these commands first in your `ios` console
```bash
rm -rf Pods
rm -rf Podfile.lock
rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
pod cache clean --all
flutter clean
flutter pub get
pod repo update
pod install
```
If they do not fix it try to see if the dependencies work on a new `flutter create` project and if they do just do the same thing and replace the `ios` directory.

As you have provided none of the information in the template I'm going to close this issue. If the mentioned steps do not work please open a new issue and provide all of the details in the template and refrain from using screenshots, as they make referencing the error message impossible (just provide your build logs).
Thank you

**Closed by markusaksli-nc** 2021-03-16 11:09 UTC

**Comment by Ahmadre** [comment] 2021-03-16 16:51
> Hi @Ahmadre 
> 
> Please take a look at https://github.com/FirebaseExtended/flutterfire/issues/5284 https://github.com/FirebaseExtended/flutterfire/issues/5059
> 
> The issue seems to be caused by something in Xcode cache that previously people have been able to solve by just replacing the ios directory with a new one created with swift.
> 
> You can still try to run these commands first in your `ios` console
> 
> ```bash
> 
> rm -rf Pods
> 
> rm -rf Podfile.lock
> 
> rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
> 
> pod cache clean --all
> 
> flutter clean
> 
> flutter pub get
> 
> pod repo update
> 
> pod install
> 
> ```
> 
> If they do not fix it try to see if the dependencies work on a new `flutter create` project and if they do just do the same thing and replace the `ios` directory.
> 
> 
> 
> As you have provided none of the information in the template I'm going to close this issue. If the mentioned steps do not work please open a new issue and provide all of the details in the template and refrain from using screenshots, as they make referencing the error message impossible (just provide your build logs).
> 
> Thank you

Already saw and tried these steps. Guess what the issue was?

You had to put your iOS Pods inside the:

```plist
target Runner do
  Pod 'Firebase/Core'
...
```

That solved my errors

**Comment by Ahmadre** [comment] 2021-03-16 16:58
Here: https://pub.dev/packages/firebase_crashlytics

and here: https://pub.dev/packages/firebase_core

and here: https://pub.dev/packages/firebase_auth

and here: https://pub.dev/packages/firebase_storage

and here: https://pub.dev/packages/firebase_messaging

**Comment by markusaksli-nc** [comment] 2021-03-17 11:59
Sorry if it came off as judging, that was not my intention. We simply close issues that do not provide the information indicated in the template as they are lacking critical information (such as flutter version, a complete list of packages, etc).

As for the documentation. There is a dedicated website with detailed steps for general setup and for setup for all of the specific packages at https://firebase.flutter.dev/docs/overview If you think the documentation is lacking then please open a documentation issue and recommend the changes you wish to see.

As this issue seems to be exceedingly rare (I've never been able to reproduce this) and for most users the packages work without such a workaround there has not been a request yet to add anything regarding this to the documentation.

**Comment by Ahmadre** [comment] 2021-03-18 21:09
> Sorry if it came off as judging, that was not my intention. We simply close issues that do not provide the information indicated in the template as they are lacking critical information (such as flutter version, a complete list of packages, etc).
> 
> As for the documentation. There is a dedicated website with detailed steps for general setup and for setup for all of the specific packages at https://firebase.flutter.dev/docs/overview If you think existing lack of documentation is a serious issue and makes developing a mess then please open a documentation issue and recommend the changes you wish to see.
> 
> As this issue seems to be exceedingly rare (I've never been able to reproduce this) and for most users, the packages work without such a workaround there has not been a request yet to add anything regarding this to the documentation.

You're definetly right! I never saw that page before, so sorry If I was too harsh, I was just upset because I really fought with Firebase configuration since Flutter was released in Dec. 2019. But you're right, I had to look deeper into the official page rather then searching on github and stackoverflow.
