### ISSUE TITLE
🐛 [google_sign_in] Missing Plugin Exception

### ISSUE THREAD

**Issue by prajwal27** [FirebaseExtended/flutterfire#6251] opened 2021-05-26 22:45 UTC
## Bug report

**Describe the bug**
I'm trying to implement google sign in my app. I get  `
Unhandled Exception: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)
E/flutter (22251): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:156:7)
E/flutter (22251): <asynchronous suspension>
E/flutter (22251): #1      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:233:5)
E/flutter (22251): <asynchronous suspension>
E/flutter (22251): #2      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart)
E/flutter (22251): <asynchronous suspension>
E/flutter (22251):
`

---

## Additional context

We are not yet migrated to null safety. Would this be a problem?

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.985], locale en-IN)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] IntelliJ IDEA Community Edition (version 2019.2)
[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.3
Flutter SDK 2.0.5
soul 1.0.0+1

dependencies:
- animated_text_kit 4.2.1 [flutter characters]
- audio_service 0.17.0 [audio_session rxdart flutter_isolate flutter_cache_manager js flutter flutter_web_plugins]
- audioplayers 0.19.0 [uuid path_provider http flutter flutter_web_plugins]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 2.2.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- firebase_analytics 8.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.2.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.2.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 8.1.0 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_facebook_auth 3.4.0 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- fluttertoast 8.0.7 [flutter flutter_web_plugins]
- gesture_x_detector 1.0.0 [flutter vector_math]
- google_sign_in 5.0.4 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- just_audio 0.7.4+1 [just_audio_platform_interface just_audio_web audio_session rxdart path path_provider async uuid crypto meta flutter]
- like_button 2.0.2 [flutter]
- modal_progress_hud 0.1.3 [flutter]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- rflutter_alert 2.0.2 [flutter]

dev dependencies:
- curved_navigation_bar 0.4.0-nullsafety.0 [flutter meta]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed
_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.5.0 [collection]
- audio_session 0.1.0 [flutter flutter_web_plugins rxdart]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.1.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.1.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.0
- file 6.1.1 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.2.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.1.0 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.1.0 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.2 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_auth_platform_interface 2.6.0 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.6.0 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_isolate 2.0.0 [flutter uuid]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 9.0.0 [flutter]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- intl 0.17.0 [clock path]
- js 0.6.3
- just_audio_platform_interface 3.0.0 [flutter plugin_platform_interface]
- just_audio_web 0.3.1 [just_audio_platform_interface flutter flutter_web_plugins]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.1 [collection meta petitparser]

```

</details>

---

**Comment by darshankawar** [comment] 2021-05-27 06:11
@prajwal27 
Are you getting this error when you use only `google_sign_in` plugin ? Or with combination with other firebase plugins ?
Because, `google_sign_in` is maintained by flutter/flutter repo and not here, so you would want to open this issue in https://github.com/flutter/flutter/issues.

If you are facing any issues related to firebase plugins then it makes sense to open related issues here.

**Comment by prajwal27** [comment] 2021-05-27 06:32
I'm using `google_sign_in` with firebase.

**Comment by darshankawar** [comment] 2021-05-27 07:17
@prajwal27 
Provide a complete minimal reproducible code sample that shows this issue.
Not having migrated to Null safety should not be a problem.

**Comment by prajwal27** [comment] 2021-05-27 08:16
Future<void> signInWithGoogle() async {
    //try {
      // Trigger the authentication flow
      final GoogleSignInAccount? googleUser = await GoogleSignIn().signIn();
      print("${googleUser?.email??'s'}");
      // Obtain the auth details from the request
      if(googleUser != null) {
        final GoogleSignInAuthentication googleAuth = await googleUser.authentication;

        // Create a new credential
        final credential = GoogleAuthProvider.credential(
          accessToken: googleAuth.accessToken,
          idToken: googleAuth.idToken,
        );

        // Once signed in, return the UserCredential
        UserCredential userCredential = await FirebaseAuth.instance.signInWithCredential(credential);
        if (userCredential != null) {
          Navigator.pushNamed(context, Nav.id);
        }
      } else {

      }

    /*} catch (e) {
      print("message ${e.toString()}");
    }*/

  }

This is the code I'm executing after adding google_sign_in package in the pubspec.yaml and I get the error mentioned in the issue

**Comment by darshankawar** [comment] 2021-05-27 10:39
@prajwal27 
Can you check if you get the same issue using the plugin's [example](https://pub.dev/packages/google_sign_in/example) too ?

**Comment by prajwal27** [comment] 2021-05-27 10:55
@darshankawar  yes. I commented the code in my project's main.dart and used the plugin's example code. I do get the same error again.

**Comment by darshankawar** [comment] 2021-05-27 11:50
@prajwal27 
Thanks for confirming. Looking at the error, it seems somehow the plugin isn't registered at native side and hence the exception. Maybe the android embedding could be an issue too. See this issue for your reference, https://github.com/flutter/flutter/issues/44161.


Moreover, since you are seeing the issue using standalone plugin without firebase, I'd suggest you to open this issue in flutter repo: https://github.com/flutter/flutter/issues

There while opening issue, do provide a complete code sample without any 3rd party plugins (like, firebase) so that it'll be easier to address.

Closing from here, as it isn't related to firebase plugins as mentioned above. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2021-05-27 11:50 UTC
Labels: Needs Attention, in triage, type: bug
