### ISSUE TITLE
firebase_storage: 10.0.3: getDownloadURL not working on iOS (works on Web)

### ISSUE THREAD

**Issue by EricPHassey** [FirebaseExtended/flutterfire#6919] opened 2021-08-31 18:22 UTC
Using the following "pseudo" code:

`String anteriorOD = await FirebaseStorage.instance.ref().child(data[1]).getDownloadURL();`

Works fine on Flutter Web, zero issues. Won't do anything when trying to run this on iPhone 12 Pro Max simulator. The code just hangs right at this line.

Are any special permissions required on iOS that isn't on web? Didn't notice anything in the documentation.

Using firebase_storage v10.0.3 and Flutter master channel 2.6.0-1.0.pre.105

[✓] Flutter (Channel master, 2.6.0-1.0.pre.105, on macOS 11.5.2 20G95 darwin-x64, locale en-US)
[✗] Android toolchain - develop for Android devices
    ✗ Unable to locate Android SDK.
      Install Android Studio from: https://developer.android.com/studio/index.html
      On first launch it will assist you in installing the Android SDK components.
      (or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions).
      If the Android SDK has been installed to a custom location, please use
      `flutter config --android-sdk` to update to that location.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (2 available)

**Comment by markusaksli-nc** [comment] 2021-09-01 10:49
Hi @EricPHassey 
I tried to reproduce this on an iOS 14.5 12 Pro Max simulator but I don't see the issue. Are you not even seeing any errors or relevant warnings in the logs?
Just in case - have you carefully followed the instructions?
https://firebase.flutter.dev/docs/installation/ios
This should be all that is necessary for the plugin to work on iOS.
Thank you

**Comment by markusaksli-nc** [comment] 2021-09-02 06:49
Wait so in what part of the code are you using these strings? Is the issue with getting a reference, not the actual call to `refFromURL`?

Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by EricPHassey** [comment] 2021-09-02 06:57
> Wait so in what part of the code are you using these strings? Is the issue with getting a reference, not the actual call to `refFromURL`?
> 
> Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

Sure.

This DOES NOT work on iOS but DOES work on Web (haven't tested Android yet):
String test = await FirebaseStorage.instance.ref().child('gs://test.appspot.com/path_to_file.png').getDownloadURL();

This DOES work on both iOS and Web:
String test = await FirebaseStorage.instance.ref().child('path_to_file.png').getDownloadURL();

Removing 'gs://test.appspot.com/' appears to solve the problem.

I don't believe it has anything to do with getDownloadURL and more so the issues somehow in child where on iOS it's not processing the bucket name correctly, however on web it somehow is able to.

My hack to resolve this was to just remove the bucket name in a crude manner, but obviously I'd prefer this to be fixed on both for my reasons and anyone else that may have experienced this.

**Comment by markusaksli-nc** [comment] 2021-09-02 07:42
Well this is reproducibe on `firebase_storage: ^10.0.3` with
```html
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-storage.js"></script>
```
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.6.0-1.0.pre.160, on macOS 11.5.2 20G95 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-1.0.pre.160 at /Users/nevercode/development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f77c453ab6 (2 hours ago), 2021-09-02 00:58:19 -0400
    • Engine revision d877a4bbcd
    • Dart version 2.15.0 (build 2.15.0-68.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android
      Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.5.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/203.7621141/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[✓] Connected device (4 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.7.1 18G82
    • iPhone 12 Pro Max (mobile)  • 70FAF0FF-11C3-4D94-A759-C6F4C0D7EF56     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5
      (simulator)
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 11.5.2 20G95 darwin-arm
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 93.0.4577.63

• No issues found!

```
</details>

But the behavior is expected for iOS since both `ref()` and `child()` expect a path in the storage bucket directories, not a URL (that's what `refFromURL()` is for). FYI the `child()` call in your code is redundant since calling `ref()` will just return the root reference without an argument. The behavior for this issue is the exact same if you check the argument with just `ref()`.

The question here should really be why this even works on web. But this isn't something we can answer since for both `child()` and `ref()` we just pass the argument to the native SDK through the delegate. This means the discrepancy shouldn't be coming from any hidden bug in the plugin dart code, but rather from somewhere in the Firebase JS SDK.

Since the issue isn't actionable for us I'm going to close it. Feel free to contact https://firebase.google.com/support or open an issue in https://github.com/firebase/firebase-js-sdk/issues regarding this.

Thank you

**Closed by markusaksli-nc** 2021-09-02 07:42 UTC
Labels: type: bug, Needs Attention, in triage
