### ISSUE TITLE
./gradlew signingReport does not work

### ISSUE THREAD

**Issue by Hekhy** [FirebaseExtended/flutterfire#6322] opened 2021-06-05 19:02 UTC
Whenever I put the command it does not work, my plugin is at the latest version and I have it set in the build.gradle ...
I don't know what could be happening.
![sad](https://user-images.githubusercontent.com/70041483/120902541-3f2cb300-c641-11eb-97d6-25836361a653.jpg)

![wada](https://user-images.githubusercontent.com/70041483/120902542-42c03a00-c641-11eb-9ad0-3875a757fe2f.jpg)

**Comment by markusaksli-nc** [comment] 2021-06-07 12:47
Hi @Hekhy 
Have you tried `flutter clean` and `flutter pub get`?
Thank you

**Comment by Hekhy** [comment] 2021-06-08 22:16
Yes, I have tried it now and the same thing happens
![ghdrergh](https://user-images.githubusercontent.com/70041483/121264773-00546280-c8b8-11eb-8bed-f54483305084.jpg)

**Comment by markusaksli-nc** [comment] 2021-06-09 11:06
Have you tried adding a direct firebase core dependency to your `pubspec.yaml`?
```yaml
firebase_core: ^1.2.1
```

**Comment by Hekhy** [comment] 2021-06-09 17:11
Yes, and here is the same error
![ghdrergh](https://user-images.githubusercontent.com/70041483/121399195-7dceb000-c956-11eb-9762-83d6561b2b13.jpg)

**Comment by Hekhy** [comment] 2021-06-09 17:49
I have tried directly executing the gradlew.bat file and I get this error
![ghdrergh](https://user-images.githubusercontent.com/70041483/121403715-7a89f300-c95b-11eb-9247-2f13082e3192.jpg)
Apparently the gradle that android uses is version 6.7 as you can see in the left panel the folder with version 6.7 appears, but it needs version 7.0
This seems to be a flutter error when generating the android files, because I also tried deleting the android folder and executing the flutter create command. and it remains the same, I even tried a new project and the same thing happens.

**Comment by Hekhy** [comment] 2021-06-09 18:51
Hello, here again, sorry to be annoyed but doing more testing, delete one of the files that firebase_messaging creates
specifically this:
![rtqwewert](https://user-images.githubusercontent.com/70041483/121411484-f9832980-c963-11eb-9752-2d9746954f2f.jpg)

After deleting it, I tried again to execute the command ./gradlew signingReport and it worked, although it still says that the version has to be 7.0, it worked well and even generated many versions of my sha1, not just one as in the previous message.
Here the image:
![wefwerq](https://user-images.githubusercontent.com/70041483/121411781-47982d00-c964-11eb-82dc-146f741148bd.jpg)
I just covered it up but I still know
it may have worked.

I don't know what can happen but it seems to be that file that is causing problems.

**Comment by markusaksli-nc** [comment] 2021-06-10 11:14
I haven't been able to reproduce the issue and as far as I can see there are no other who have faced it. What I can recommend is that you upgrade your flutter to the latest version on whatever channel you are using and then see if the gradle plugin version and the dependencies in both the android folder build.gradle and app-level build.gradle are the same.

SInce we can't reproduce this and you have somewhat of a workaround that solves the issue for you I'm going to close the issue.

**Closed by markusaksli-nc** 2021-06-10 11:14 UTC
Labels: Needs Attention, in triage, type: bug

**Comment by Hekhy** [comment] 2021-06-10 12:02
I have the updated version for a long time, I do not know what the problem is but it is clear that something is happening, I understand that the problem is closed but they should work on it.
![efwwe](https://user-images.githubusercontent.com/70041483/121521571-85dd2d00-c9f4-11eb-8e5f-4584f4f5e1cf.png)
