### ISSUE TITLE
🐛 [firebase_core] Should this really depend on firebase-common?

### ISSUE THREAD

**Issue by schricb** [FirebaseExtended/flutterfire#6316] opened 2021-06-04 18:58 UTC
## Bug report

**Describe the bug**
Android app failing to build.

### Steps to reproduce
Upgraded firebase_core package in Flutter pubspec.yaml from ^0.5.3 to ^1.2.1.
flutter build apk

Build fails:
Execution failed for task ':firebase_core:generateDebugRFile'.
> Could not resolve all files for configuration ':firebase_core:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-common:.
     Required by:
         project :firebase_core
---

## Additional context

I noticed after v0.5.3 that the firebase_core Android/build.gradle was changed from depending on firebase-core to firebase-common. Is this intentional? A Gradle sync on ~/.pub-cache/hosted/pub.dartlang.org/firebase_core-1.2.1/android/build.gradle shows the following warning:

Failed to resolve: com.google.firebase:firebase-common:
Affected Modules: firebase_core
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.2.1, on macOS 11.4 20F71 darwin-x64, locale en-US)
    • Flutter version 2.2.1 at ~//src/flutter
    • Framework revision 02c026b03c (8 days ago), 2021-05-27 12:24:44 -0700
    • Engine revision 0fdb562ac8
    • Dart version 2.13.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at ~/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode-12.4.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.56.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.22.0

[✓] Connected device (3 available)
    • moto e6 (mobile)       • ZF6522SV8N                               • android-arm    • Android 9 (API 28)
    • Bill’s iPhone (mobile) • f954cc12fe99c26b1031fd5ff9740993ea9778cd • ios            • iOS 14.4.2
    • Chrome (web)           • chrome                                   • web-javascript • Google Chrome 91.0.4472.77

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.1
Flutter SDK 2.2.1

dependencies:
- another_flushbar 1.10.23 [pedantic flutter]
- auto_size_text 2.1.0 [flutter]
- chewie 1.2.0 [cupertino_icons flutter provider video_player wakelock]
- cloud_firestore 2.2.1 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- datetime_picker_formfield 2.0.0 [flutter intl]
- device_apps 2.1.1 [flutter]
- enum_to_string 2.0.1
- equatable 2.0.2 [collection meta]
- firebase_analytics 8.1.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.3.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.2.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.0.5 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flare_flutter 3.0.1 [collection flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.1 [flutter bloc provider]
- flutter_masked_text 0.8.0 [flutter]
- flutter_offline 2.0.0 [flutter connectivity wifi_info_flutter]
- flutter_rating_bar 4.0.0 [flutter]
- flutter_secure_storage 4.2.0 [meta flutter]
- flutter_staggered_grid_view 0.4.0 [flutter]
- flutter_swiper 1.1.6 [flutter transformer_page_view flutter_page_indicator]
- fluttertoast 8.0.7 [flutter flutter_web_plugins]
- font_awesome_flutter 9.0.0 [flutter]
- http 0.13.3 [async http_parser meta path pedantic]
- image_picker 0.8.0+1 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl 0.17.0 [clock path]
- intro_slider 2.4.3 [flutter]
- location_permissions 4.0.0 [flutter meta]
- logging 1.0.1
- map_launcher 2.0.0 [flutter]
- meta 1.3.0
- open_file 3.2.1 [flutter ffi]
- outline_material_icons 0.1.1 [flutter]
- package_info 2.0.2 [flutter]
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- pin_code_text_field 1.8.0 [flutter]
- recase 4.0.0
- retry 3.1.0
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 2.0.0 [flutter]
- url_launcher 6.0.6 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- us_states 1.1.0
- uuid 3.0.4 [crypto]
- webview_flutter 2.0.8 [flutter]
- xml2json 5.2.0 [xml]

dev dependencies:
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_launcher_icons 0.9.0 [args image path yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- git_hooks 0.1.6 [path yaml meta]
- image 3.0.2 [archive meta xml]
- test 1.16.8 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 22.0.0 [meta]
- analyzer 1.7.1 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.6.1 [meta collection]
- bloc 7.0.0 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.1.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.1.1 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- connectivity 3.0.6 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- connectivity_for_web 0.4.0 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.2.0 [flutter]
- connectivity_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.0.0 [typed_data]
- coverage 1.0.3 [args logging package_config path source_maps stack_trace vm_service]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.3
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.2.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.0.5 [collection firebase_core flutter meta plugin_platform_interface]
- flutter_page_indicator 0.0.3 [flutter]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.1.0 [flutter meta http plugin_platform_interface]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- mime 1.0.0
- nested 1.0.0 [flutter]
- node_preamble 2.0.0
- package_config 2.0.0 [path]
- path 1.8.0
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- provider 5.0.0 [collection flutter nested]
- pub_semver 2.0.0 [collection]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.4 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.0.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.3.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.19 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- transformer_page_view 0.1.6 [flutter]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- video_player 2.1.5 [flutter flutter_test meta video_player_platform_interface video_player_web]
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.1 [flutter flutter_web_plugins meta video_player_platform_interface]
- vm_service 6.2.0
- wakelock 0.5.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.1.0+1 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.1+1 [flutter meta]
- wakelock_web 0.2.0+1 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- webkit_inspection_protocol 1.0.0 [logging]
- wifi_info_flutter 2.0.2 [flutter wifi_info_flutter_platform_interface]
- wifi_info_flutter_platform_interface 2.0.1 [plugin_platform_interface flutter]
- win32 2.1.3 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-06-07 11:13
Hi @schricb 
Have you followed the migration guide?
https://firebase.flutter.dev/docs/migration#a-android-installation
Thank you

**Comment by schricb** [comment] 2021-06-07 12:17
Yes I have. That's where I came across this issue. In my case, I need to support Flutter 2.x, but on the Android side I am dependent on a 3rd party library that requires older versions of firebase-core and firebase-messaging so I am overriding the flutter versions as stated in the migration doc:

rootProject.ext {
    set('FlutterFire', [
            FirebaseSDKVersion: '25.10.0'
    ])
}

When I add the above is when the build failure occurs.

**Comment by markusaksli-nc** [comment] 2021-06-07 12:42
So the build is actually failing because of the SDK version override?

As the guide says this is something you should remove unless you absolutely need it since we test against the internally managed version and update it accordingly. You may be able to get the older version working if you add the required dependencies (like `com.google.firebase:firebase-common`) into your app-level build.gradle file.

**Comment by schricb** [comment] 2021-06-07 12:51
Yes, when I add the SDK version override, I begin seeing the attached in Android Studio after Gradle Sync. And then building fails as noted in my original comment. I've tried pulling in the older version as you suggest, but that does not seem to work as well.
![Screen Shot 2021-06-07 at 8 46 51 AM](https://user-images.githubusercontent.com/64926426/121019444-6e404300-c76d-11eb-8a03-f76478b900bf.png)

**Comment by schricb** [comment] 2021-06-07 16:18
Just to be clear what my goal is. I have a Flutter app that is using the latest Firebase plugins (Flutter version 2.2.1). On the Android side, I'm using a 3rd party library that depends on specific older versions of firebase-core and firebase-messaging. I thought the "recommended" way of handling this was by adding the SDK override to my android/app/build.gradle. If this is not the case, then what is the approved/recommended way to handle this scenario??

**Comment by markusaksli-nc** [comment] 2021-06-09 11:49
It looks like the dependency in question is missing from the older BoM version you are using 
https://firebase.google.com/support/release-notes/android#bom_v25-10-0

In this case your best bet is to maybe use an older version plugin that isn't using this dependency? This will likely limit the versions of the other firebase plugins you are using ultimately massively restricting your dependencies.

The more reasonable solution here is to figure out how to support the latest Android BoM version by either replacing the third-party dependencies you are using or attempting to adapt them.

This, however, is out of our scope since the FlutterFire plugins are working as intended here and we can't be held responsible for compatibility with outdated BoM versions or third-party native dependencies so I'm going to close this issue.

**Closed by markusaksli-nc** 2021-06-09 11:49 UTC
Labels: Needs Attention, in triage, type: bug
