### ISSUE TITLE
Twitter Login with firebase not working 

### ISSUE THREAD

**Issue by Gursewak-Uppal** [FirebaseExtended/flutterfire#1398] opened 2019-11-11 07:14 UTC
I tried to login with firebase using [flutter_twitter](https://pub.dev/packages/flutter_twitter) but it's not working ( I tested with android only)

Code 

    final AuthCredential credential = TwitterAuthProvider.getCredential(
       authToken: session.token,
       authTokenSecret: session.secret,
     );
     final AuthResult response =
        await _auth.signInWithCredential(credential);

Exception

    E/AndroidRuntime(17566): FATAL EXCEPTION: main 
    E/AndroidRuntime(17566): Process: com.boffincoders.chat_app, PID: 17566 
    E/AndroidRuntime(17566): java.lang.IllegalArgumentException: Unsupported value: null
    E/AndroidRuntime(17566): at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294) 
    E/AndroidRuntime(17566): at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291) 
    E/AndroidRuntime(17566): at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291) 
    E/AndroidRuntime(17566): at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291) 
    E/AndroidRuntime(17566): at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
    E/AndroidRuntime(17566): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225) 
    E/AndroidRuntime(17566): at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$SignInCompleteListener.onComplete(FirebaseAuthPlugin.java:691)
    E/AndroidRuntime(17566): at com.google.android.gms.tasks.zzj.run(Unknown Source:4) 
    E/AndroidRuntime(17566): at android.os.Handler.handleCallback(Handler.java:873) 
    E/AndroidRuntime(17566): at android.os.Handler.dispatchMessage(Handler.java:99) 
    E/AndroidRuntime(17566): at android.os.Looper.loop(Looper.java:201) 
    E/AndroidRuntime(17566): at android.app.ActivityThread.main(ActivityThread.java:6823) 
    E/AndroidRuntime(17566): at java.lang.reflect.Method.invoke(Native Method) 
    E/AndroidRuntime(17566): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
    E/AndroidRuntime(17566): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
    I/Process (17566): Sending signal. PID: 17566 SIG: 9 
    Lost connection to device.

**Comment by iapicca** [comment] 2019-11-11 13:24
Hi @Gursewak-Uppal 
the plugin you are referring to is not a FlutterFire plugin,
you might want to open an issue in the dedicated [github](https://github.com/roughike/flutter_twitter_login).

Closing, as this isn't an issue with FlutterFire itself,
if you disagree please write in the comments and I will reopen it
Thank you

**Comment by iamvivekkaushik** [comment] 2019-11-17 12:14
This issue is with the Firebase Auth itself as twitter login is working fine the crash occurs when we call the function `signInWithCredential` to get the firebase user.

```
    var twitterLogin = new TwitterLogin(
        consumerKey: twitterKeys['api_key'],
        consumerSecret: twitterKeys['secret_key']);

    final TwitterLoginResult result = await twitterLogin.authorize();

    switch (result.status) {
      case TwitterLoginStatus.loggedIn:
        debugPrint("Twitter login Success");
        var session = result.session;
        AuthCredential authCredential = TwitterAuthProvider.getCredential(
            authToken: session.token, authTokenSecret: session.secret);

        // This is where the crash occurs
        AuthResult authResult =
            await _auth.signInWithCredential(authCredential);
        firebaseUser = authResult.user;

        await updateUserData(linkedTwitter: true);

        return firebaseUser;
        break;
      case TwitterLoginStatus.cancelledByUser:
        debugPrint("Twitter Canceled by user");
        throw (result.errorMessage);
        break;
      case TwitterLoginStatus.error:
        print("Error Occurred while logging with twitter");
        throw (result.errorMessage);
        break;
    }
```

Exception:

```
E/AndroidRuntime( 7073): java.lang.IllegalArgumentException: Unsupported value: null
E/AndroidRuntime( 7073): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:294)
E/AndroidRuntime( 7073): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime( 7073): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime( 7073): 	at io.flutter.plugin.common.StandardMessageCodec.writeValue(StandardMessageCodec.java:291)
E/AndroidRuntime( 7073): 	at io.flutter.plugin.common.StandardMethodCodec.encodeSuccessEnvelope(StandardMethodCodec.java:57)
E/AndroidRuntime( 7073): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime( 7073): 	at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$SignInCompleteListener.onComplete(FirebaseAuthPlugin.java:691)
E/AndroidRuntime( 7073): 	at com.google.android.gms.tasks.zzj.run(Unknown Source:4)
E/AndroidRuntime( 7073): 	at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime( 7073): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7073): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime( 7073): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime( 7073): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7073): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime( 7073): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by iamvivekkaushik** [comment] 2019-11-17 12:17
This seems to be the same issue as #348.

**Comment by iapicca** [comment] 2020-01-28 07:52
Hi @Gursewak-Uppal 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.
Thank you

**Comment by Ehesp** [comment] 2020-04-21 14:56
Closing in favour of issue https://github.com/FirebaseExtended/flutterfire/issues/138 - will keep track of progress there.

**Closed by Ehesp** 2020-04-21 14:56 UTC
Labels: blocked: customer-response, impact: customer, plugin: auth, type: bug
