### ISSUE TITLE
🐛 [firebase_database] `onValue` with Tabs throws `Bad state: Stream has already been listened to` and `MissingPluginException` errors

### ISSUE THREAD

**Issue by tmthecoder** [FirebaseExtended/flutterfire#7618] opened 2021-12-15 18:51 UTC
## Bug report

**Describe the bug**
When using the `onValue` listener with a TabController as the parent view (I had two listeners each on a separate tab), and navigating from tabs and back, `Bad state: Stream has already been listened to.` is thrown.

Also on a separate note, I came across this bug while dealing with another on `onValue` streams, where a `No implementation found for method cancel on channel usage-counter/moOmk97GjEV1QMaQ2HiVz6y82sl1-[DEFAULT]-null-DatabaseEventType.value-[]#6` is thrown when navigating in the TabView on a separate app. I was unable to replicate this, but I wonder if it's a similar issue, so I'll include it here. Sorry if it isn't and this information is redundant. I cannot share the code for the application that threw this exception, but will share the one with the Stream listen error.

### Steps to reproduce

1. Open the Sample Repo
2. Run the Code
3. Go back and forth between tabs
4. See the thrown `StateError`

### Expected behavior

The StreamController should continue to function across tab navigation

### Sample project

https://github.com/tmthecoder/database_stream_bug
---

## Additional context

None except the mention about the other error I received. In the case this is a lower priority issue, I can work on a fix if an issue is found. I couldn't seem to pinpoint it myself when looking through the firebase_database implementation. 

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-x64, locale
    en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.
[✓] Xcode - develop for iOS and macOS (Xcode 13.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2.1)
[✓] Connected device (3 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.15.0
Flutter SDK 2.8.0
firebase_database_bug_sample 1.0.0+1

dependencies:
- cupertino_icons 1.0.4
- firebase_core 1.10.5 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 9.0.3 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.2.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.2.2 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database_platform_interface 0.2.0+2 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+2 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.0.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.1

```

</details>

---

**Comment by darshankawar** [comment] 2021-12-16 11:17
@tmthecoder 
Thanks for the report. Although I get the same exception `Bad state: Stream has already been listened to.`, I think it may not be occurring due to database plugin, but could be the way `StreamBuilder` is implemented.

It seems that TabBarView is maintaining the child (StreamBuilder) state and reusing it.
Can you try to wrap StreamBuilder with a Builder to ensure that a new instance of the Stream is called and not the state version in memory from TabBarView ?

**Comment by tmthecoder** [comment] 2021-12-16 16:07
@darshankawar Upon using a builder, the listener works temporarily then does no longer work in live-time. You can test this with the second-to-latest commit to the repo above, clicking back snd forth between tabs and changing values works initially but after some back and forth between tabs, it no longer updates in live-time, and after a few back and forth, the app on my emulator crashed.

Additionally, if I leave one of the tabs as it was before, and wrap one around in a builder, the `MissingPluginException` I referred to before comes up. If one is wrapped in builder (let's say 1st tab), click the button a few times and see live-time updates. Then go to the second tab and click buttons a few time there and see 2nd live-time update. Once you go back to the first, it will no longer live update, and going back to the second gives two different exceptions: `StateError` and `MissingPluginException`. This can be seen by the latest commit to the repo.

The stack trace for the second paragraph is here:

```
======== Exception caught by widgets library =======================================================
The following StateError was thrown building KeyedSubtree-[<1>]:
Bad state: Stream has already been listened to.

The relevant error-causing widget was: 
  TabBarView-[GlobalKey#983c7] TabBarView:file:///Users/tejasmehta/Desktop/Development/test/firebase_database_bug_sample/lib/main.dart:64:13
When the exception was thrown, this was the stack: 
#6      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:134:38)
#7      _StreamBuilderBaseState.initState (package:flutter/src/widgets/async.dart:108:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4728:57)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#11     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#12     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (42 frames)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#56     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1243:37)
#57     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1228:20)
#58     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2531:19)
#59     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1221:12)
#60     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#61     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1962:59)
#62     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:910:15)
#63     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1962:14)
#64     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#65     RenderSliverMultiBoxAdaptor.insertAndLayoutChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:484:5)
#66     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:250:17)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#68     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#69     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#71     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#72     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#73     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#74     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1707:7)
#75     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:879:18)
#76     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#77     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#78     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#79     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#80     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#81     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#85     _invoke (dart:ui/hooks.dart:150:10)
#86     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#87     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 9 frames from dart:async)
====================================================================================================

======== Exception caught by services library ======================================================
The following MissingPluginException was thrown while de-activating platform stream on channel test-val-[DEFAULT]-null-DatabaseEventType.value-[]#2:
MissingPluginException(No implementation found for method cancel on channel test-val-[DEFAULT]-null-DatabaseEventType.value-[]#2)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:165:7)
<asynchronous suspension>
#1      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:518:9)
<asynchronous suspension>
====================================================================================================
```

**Comment by darshankawar** [comment] 2021-12-17 10:43
@tmthecoder 
Thanks for the update. Looking at the exception you are getting related to `Bad state: Stream has already been listened to`, it seems to be coming from flutter:
```

`#6      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:134:38)
#7      _StreamBuilderBaseState.initState (package:flutter/src/widgets/async.dart:108:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4728:57)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4561:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3631:14)
#11     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6261:36)
#12     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6272:32)`
```

Is there a way for you to narrow it down without the database plugin and just keep framework code which will be enough to replicate the exception ?

**Comment by tmthecoder** [comment] 2021-12-17 15:04
@darshankawar I wasn't able to replicate this bug with any other tabbed Stream setup, or StreamBuilder setup, so I'm not sure what else I can do to narrow down the issue. 

As of now, my thoughts were that the second exception I listed (MissingPluginException) seems to be related to, if not causing, the stream issue. That issue is clearly database related given the error lists the database listened Native Stream.

**Comment by darshankawar** [comment] 2021-12-21 10:24
@tmthecoder 
I am unable to replicate the `MissingPluginException` behavior using the description you mentioned earlier. Can you provide the exact code and steps so that we can use to verify it properly ?
Thanks.

**Comment by tmthecoder** [comment] 2021-12-21 17:21
@darshankawar Please see the attached video. The code is the latest commit on the above repo.

You should be able to reproduce by doing the same as the video. Also, note the first tab (with the builder) no longer live-time updates when the button is clicked after coming back to it.

https://user-images.githubusercontent.com/50885454/146972163-fd34b3ff-a1a7-45c5-8b03-704125c4a3f9.mov

**Comment by darshankawar** [comment] 2021-12-22 10:02
Thanks. I now get the error as below:

<details> 
<summary> error log </summary>

```

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY
╞═══════════════════════════════════════════════════════════
The following StateError was thrown building KeyedSubtree-[<1>]:
Bad state: Stream has already been listened to.

The relevant error-causing widget was:
  TabBarView-[GlobalKey#b9034]
  TabBarView:file:///Users/dhs/Documents/NCFlutter/database_stream_bug/lib/main.
  dart:64:13

When the exception was thrown, this was the stack:
#6      _StreamBuilderBaseState._subscribe
(package:flutter/src/widgets/async.dart:134:38)
#7      _StreamBuilderBaseState.initState
(package:flutter/src/widgets/async.dart:108:5)
#8      StatefulElement._firstBuild
(package:flutter/src/widgets/framework.dart:4728:57)
#9      ComponentElement.mount
(package:flutter/src/widgets/framework.dart:4561:5)
#10     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3631:14)
#11     MultiChildRenderObjectElement.inflateWidget
(package:flutter/src/widgets/framework.dart:6261:36)
#12     MultiChildRenderObjectElement.mount
(package:flutter/src/widgets/framework.dart:6272:32)
...     Normal element mounting (42 frames)
#54     Element.inflateWidget
(package:flutter/src/widgets/framework.dart:3631:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3383:18)
#56     SliverMultiBoxAdaptorElement.updateChild
(package:flutter/src/widgets/sliver.dart:1243:37)
#57     SliverMultiBoxAdaptorElement.createChild.<anonymous closure>
(package:flutter/src/widgets/sliver.dart:1228:20)
#58     BuildOwner.buildScope
(package:flutter/src/widgets/framework.dart:2531:19)
#59     SliverMultiBoxAdaptorElement.createChild
(package:flutter/src/widgets/sliver.dart:1221:12)
#60     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure>
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#61     RenderObject.invokeLayoutCallback.<anonymous closure>
(package:flutter/src/rendering/object.dart:1962:59)
#62     PipelineOwner._enableMutationsToDirtySubtrees
(package:flutter/src/rendering/object.dart:910:15)
#63     RenderObject.invokeLayoutCallback
(package:flutter/src/rendering/object.dart:1962:14)
#64     RenderSliverMultiBoxAdaptor._createOrObtainChild
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#65     RenderSliverMultiBoxAdaptor.insertAndLayoutChild
(package:flutter/src/rendering/sliver_multi_box_adaptor.dart:484:5)
#66     RenderSliverFixedExtentBoxAdaptor.performLayout
(package:flutter/src/rendering/sliver_fixed_extent_list.dart:250:17)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#68     RenderSliverEdgeInsetsPadding.performLayout
(package:flutter/src/rendering/sliver_padding.dart:137:12)
#69     _RenderSliverFractionalPadding.performLayout
(package:flutter/src/widgets/sliver_fill.dart:167:11)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1852:7)
#71     RenderViewportBase.layoutChildSequence
(package:flutter/src/rendering/viewport.dart:510:13)
#72     RenderViewport._attemptLayout
(package:flutter/src/rendering/viewport.dart:1580:12)
#73     RenderViewport.performLayout
(package:flutter/src/rendering/viewport.dart:1489:20)
#74     RenderObject._layoutWithoutResize
(package:flutter/src/rendering/object.dart:1707:7)
#75     PipelineOwner.flushLayout
(package:flutter/src/rendering/object.dart:879:18)
#76     RendererBinding.drawFrame
(package:flutter/src/rendering/binding.dart:497:19)
#77     WidgetsBinding.drawFrame
(package:flutter/src/widgets/binding.dart:883:13)
#78     RendererBinding._handlePersistentFrameCallback
(package:flutter/src/rendering/binding.dart:363:5)
#79     SchedulerBinding._invokeFrameCallback
(package:flutter/src/scheduler/binding.dart:1145:15)
#80     SchedulerBinding.handleDrawFrame
(package:flutter/src/scheduler/binding.dart:1082:9)
#81     SchedulerBinding._handleDrawFrame
(package:flutter/src/scheduler/binding.dart:996:5)
#85     _invoke (dart:ui/hooks.dart:150:10)
#86     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:270:5)
#87     _drawFrame (dart:ui/hooks.dart:114:31)
(elided 9 frames from dart:async)

════════════════════════════════════════════════════════════════════════════════
════════════════════

Another exception was thrown: MissingPluginException(No implementation found for
method cancel on channel test-val-[DEFAULT]-null-DatabaseEventType.value-[]#2)

```

</details>

<details>
<summary> stable, master flutter doctor -v </summary>

```
[[✓] Flutter (Channel stable, 2.8.1, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-GB)
    • Flutter version 2.8.1 at /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 77d935af4d (13 hours ago), 2021-12-16 08:37:33 -0800
    • Engine revision 890a5fca2e
    • Dart version 2.15.1

[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!

[✓] Flutter (Channel master, 2.9.0-1.0.pre.156, on Mac OS X 10.15.4 19E2269
    darwin-x64, locale en-GB)
    • Flutter version 2.9.0-1.0.pre.156 at
      /Users/dhs/documents/fluttersdk/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 27ad488747 (87 minutes ago), 2021-12-21 22:39:19 -0500
    • Engine revision 4eabb883af
    • Dart version 2.16.0 (build 2.16.0-126.0.dev)
    • DevTools version 2.9.2
    
[✓] Android toolchain - develop for Android devices (Android SDK version 30)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • ANDROID_HOME = /Users/dhs/Library/Android/sdk
    • Java binary at: /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.    

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/dhs/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/202.7486908/Android
      Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)        

[✓] VS Code (version 1.57.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.21.0

[[✓] Connected device (4 available)
    • Darshan's iphone (mobile)  • 21150b119064aecc249dfcfe05e259197461ce23 •
      ios            • iOS 14.4.1 18D61
    • iPhone 12 Pro Max (mobile) • A5473606-0213-4FD8-BA16-553433949729     •
      ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)            • macos                                    •
      darwin-x64     • Mac OS X 10.15.4 19E2269 darwin-x64
    • Chrome (web)               • chrome                                   •
      web-javascript • Google Chrome 93.0.4577.82


• No issues found!




```

</details>

**Comment by russellwheatley** [comment] 2022-01-27 14:29
Hey @tmthecoder, [this PR](https://github.com/FirebaseExtended/flutterfire/pull/7859) has just been merged and should be getting released later today. Do you mind letting us know if this resolves your issue, please? Thanks.

**Comment by tmthecoder** [comment] 2022-01-27 20:17
@russellwheatley The PR seems to fix the `MissingPluginException` that's thrown, but if I use the `StreamBuilder` without a `Builder` widget surrounding it, I still get the `BadState: Stream has already been listened to` after going between tabs a few times. For now, surrounding it in a builder seems to work without any errors.

**Comment by russellwheatley** [comment] 2022-02-03 14:12
Hey @tmthecoder, not 100% sure what you mean. Do you mind posting another code snippet that reproduces the bug, please?

**Comment by tmthecoder** [comment] 2022-02-03 22:39
Sure! 

Just a little elaborating from my end: The `MissingPluginException` that was thrown is fixed, so this isn't as critical to me anymore. 

However, there's another exception that's thrown while using a `StreamBuilder` to listen to the Database's `onValue` stream  in a Tab, which seems to throw a `Bad state` exception after I navigate back to it from another tab.

I've attached the code below:

<details><summary>Click To Expand</summary>

```
import 'dart:math';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_database/firebase_database.dart';
import 'package:firebase_database_bug_sample/second_page.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key}) : super(key: key);

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> with SingleTickerProviderStateMixin {

  late final TabController _controller = TabController(length: 2, vsync: this);
  GlobalKey tabKey = GlobalKey();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text("Demo"),
        bottom: TabBar(
          controller: _controller,
          tabs: const [
            Tab(text: "Tab 1",),
            Tab(text: "Tab 2",),
          ],
        ),
        actions: [
          IconButton(
            onPressed: () => Navigator.of(context).push(MaterialPageRoute(builder: (_) => const SecondPage())),
            icon: const Icon(Icons.settings))
        ],
      ),
      body: TabBarView(
        controller: _controller,
        key: tabKey,
        children: [
          Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: <Widget>[
                StreamBuilder<DatabaseEvent>(
                  stream: FirebaseDatabase.instance.ref('test-val').onValue,
                  builder: (context, snapshot) {
                    String value = (snapshot.data?.snapshot.value ?? "") as String;
                    return Text("Database Value: $value");
                  },
                ),
                ElevatedButton(
                  onPressed: () {
                    Random r = Random();
                    String nVal = "${r.nextInt(1000)}";
                    FirebaseDatabase.instance.ref('test-val').set(nVal);
                  },
                  child: const Text("Change Value")
                ),
              ],
            ),
          ),
          Center(
            child: Column(
              children: const [
                Text("Tab 2")
              ],
            ),
          )
        ],
      ),
    );
  }
}

```

</details>

When I run that program, and go from Tab 1 to Tab 2 and back to Tab 1, this stacktrace is given:


```

======== Exception caught by widgets library =======================================================
The following StateError was thrown building KeyedSubtree-[<0>]:
Bad state: Stream has already been listened to.

The relevant error-causing widget was: 
  TabBarView-[GlobalKey#e5d80] TabBarView:file:///Users/tejasmehta/Desktop/Development/test/firebase_database_bug_sample/lib/main.dart:64:13
When the exception was thrown, this was the stack: 
#6      _StreamBuilderBaseState._subscribe (package:flutter/src/widgets/async.dart:134:38)
#7      _StreamBuilderBaseState.initState (package:flutter/src/widgets/async.dart:108:5)
#8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4893:57)
#9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4729:5)
#10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#11     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6422:36)
#12     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6433:32)
...     Normal element mounting (42 frames)
#54     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3790:14)
#55     Element.updateChild (package:flutter/src/widgets/framework.dart:3540:18)
#56     SliverMultiBoxAdaptorElement.updateChild (package:flutter/src/widgets/sliver.dart:1243:37)
#57     SliverMultiBoxAdaptorElement.createChild.<anonymous closure> (package:flutter/src/widgets/sliver.dart:1228:20)
#58     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2600:19)
#59     SliverMultiBoxAdaptorElement.createChild (package:flutter/src/widgets/sliver.dart:1221:12)
#60     RenderSliverMultiBoxAdaptor._createOrObtainChild.<anonymous closure> (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:349:23)
#61     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:1997:59)
#62     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:918:15)
#63     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:1997:14)
#64     RenderSliverMultiBoxAdaptor._createOrObtainChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:338:5)
#65     RenderSliverMultiBoxAdaptor.insertAndLayoutLeadingChild (package:flutter/src/rendering/sliver_multi_box_adaptor.dart:454:5)
#66     RenderSliverFixedExtentBoxAdaptor.performLayout (package:flutter/src/rendering/sliver_fixed_extent_list.dart:225:32)
#67     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#68     RenderSliverEdgeInsetsPadding.performLayout (package:flutter/src/rendering/sliver_padding.dart:137:12)
#69     _RenderSliverFractionalPadding.performLayout (package:flutter/src/widgets/sliver_fill.dart:167:11)
#70     RenderObject.layout (package:flutter/src/rendering/object.dart:1887:7)
#71     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:510:13)
#72     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1580:12)
#73     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1489:20)
#74     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:1731:7)
#75     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:887:18)
#76     RendererBinding.drawFrame (package:flutter/src/rendering/binding.dart:497:19)
#77     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:883:13)
#78     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#79     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1144:15)
#80     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1081:9)
#81     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:995:5)
#85     _invoke (dart:ui/hooks.dart:151:10)
#86     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#87     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 9 frames from dart:async)
====================================================================================================

```

**Comment by russellwheatley** [comment] 2022-02-10 15:25
Hey @tmthecoder, you can solve your problem by making the stream a broadcast stream. A standard stream only lets you listen once. You can change this line:

```dart
stream: FirebaseDatabase.instance.ref('test-val').onValue.asBroadcastStream(),
``` 

and the problem ought to go away. Let me know if this helps.

**Closed** 2022-02-10 15:48 UTC
Labels: type: bug, plugin: database, Needs Attention
