### ISSUE TITLE
🐛 [cloud_firestore] Can't run parts of application that don't utilize cloud firestore separately 

### ISSUE THREAD

**Issue by joshpetit** [FirebaseExtended/flutterfire#6585] opened 2021-07-11 17:52 UTC
## Bug report

**Describe the bug**
I've added firebase to my application and am using the firestore and authentication plugins. I am also using [storybook](https://pub.dev/packages/storybook_flutter) to get a look at the UI. The app is only going to be for android and iOS so I don't have it configured for the web. Ever since adding cloud_firestore to the project, I have not been able to run the file that contains the stories although they don't import any file that imports filestore (or authentication) packages.

### Steps to reproduce
1. Install firebase
2. Install firebase_auth
3. Create a simple storybook file
4. run it, it should work
5. add cloud_firestore
6. run same storybook file, it doesn't work.

1. Run a file that does not import any cloud firestore functionality
4. See error output (bellow)

This is the error output, and it's indicative of firestore [not being configured to run on web](https://github.com/FirebaseExtended/flutterfire/issues/2455)
```
TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (http://localhost:34151/packages/firebase_core_web/src/interop/core.dart.lib.js:31:101)
    at new cloud_firestore_web.FirebaseFirestoreWeb.new (http://localhost:34151/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:776:64)
    at Function.registerWith (http://localhost:34151/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:692:73)
    at Object.registerPlugins (http://localhost:34151/packages/milestone5/generated_plugin_registrant.dart.lib.js:15:46)
    at main (http://localhost:34151/web_entrypoint.dart.lib.js:31:35)
    at main.next (<anonymous>)
    at runBody (http://localhost:34151/dart_sdk.js:37422:34)
    at Object._async [as async] (http://localhost:34151/dart_sdk.js:37453:7)
    at main (http://localhost:34151/web_entrypoint.dart.lib.js:30:18)
    at http://localhost:34151/main_module.bootstrap.js:19:10
    at Array.forEach (<anonymous>)
    at window.$dartRunMain (http://localhost:34151/main_module.bootstrap.js:18:32)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:34151/dwds/src/injected/client.js:8825:21)
    at http://localhost:34151/dwds/src/injected/client.js:22713:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:34151/dwds/src/injected/client.js:3851:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:34151/dwds/src/injected/client.js:11063:12)
    at Object._asyncStartSync (http://localhost:34151/dwds/src/injected/client.js:3815:20)
    at main__closure1.$call$body$main__closure (http://localhost:34151/dwds/src/injected/client.js:22725:16)
    at main__closure1.call$1 (http://localhost:34151/dwds/src/injected/client.js:22652:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:34151/dwds/src/injected/client.js:4185:16)
    at _CustomZone.runUnary$2$2 (http://localhost:34151/dwds/src/injected/client.js:12436:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:34151/dwds/src/injected/client.js:12383:14)
    at _ControllerSubscription._sendData$1 (http://localhost:34151/dwds/src/injected/client.js:11959:19)
    at _DelayedData.perform$1 (http://localhost:34151/dwds/src/injected/client.js:12148:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:34151/dwds/src/injected/client.js:12197:14)
    at Object._microtaskLoop (http://localhost:34151/dwds/src/injected/client.js:4023:24)
    at StaticClosure._startMicrotaskLoop (http://localhost:34151/dwds/src/injected/client.js:4029:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:34151/dwds/src/injected/client.js:10932:9)
    at invokeClosure (http://localhost:34151/dwds/src/injected/client.js:1259:26)
    at MutationObserver.<anonymous> (http://localhost:34151/dwds/src/injected/client.js:1278:18)
```

### Expected behavior

I expect to be able to run files that don't import cloud firestore anywhere, just as I was able to do so with only firebase auth installed.

---

## Additional context

Everything worked up until I added the firestore sdk. When I checkout a branch that doesn't have the package installed and run the story and then go back to the branch with firestore installed, everything runs perfectly fine after hot reloading. It's the act of starting that's not working.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4
Flutter SDK 2.2.3
APP_NAME 1.0.0+1

dependencies:
- cloud_firestore 2.3.0 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- firebase_auth 2.0.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- provider 5.0.0 [collection flutter nested]
- storybook_flutter 0.5.0+1 [collection device_frame flutter freezed_annotation provider recase]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.2.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.2.0 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- device_frame 0.4.2 [flutter_svg path_drawing freezed_annotation flutter]
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 5.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 2.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- freezed_annotation 0.14.2 [collection json_annotation meta]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- petitparser 4.1.0 [meta]
- plugin_platform_interface 2.0.0 [meta]
- recase 4.0.0
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- xml 5.1.2 [collection meta petitparser]
```

</details>

---

and ofc thank you so much for make firebase so easy to integrate with flutter, this makes both applications my first choice for any app dev :).

**Comment by markusaksli-nc** [comment] 2021-07-12 11:24
Hi @joshpetit 

Have you completed the setup for web?
https://firebase.flutter.dev/docs/installation/web
https://firebase.flutter.dev/docs/firestore/overview#3-web-only-add-the-sdk

This error occurs at the plugin registration step so there is no way to get around it, for now, other than to complete the setup. If that's what you mean then I would consider this a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/3962

Let me know if you disagree.
Thank you

**Closed by markusaksli-nc** 2021-07-12 11:24 UTC
Labels: Needs Attention, in triage, type: bug

**Comment by joshpetit** [comment] 2021-07-12 12:47
Yes I understand that. I am trying to run a flutter file that doesn't import anything related to firebase, however. When I was just using firebase authentication alongside yhe firebase sdk, I could run my storybook file to view my ui widgets (which did not import anything related to firebase or authentication). Then when I added the cloud Firestore plugin I was not able to run the storybook file. Is this only the case with cloud Firestore? If so, and there is no way around this, I understand, thank you for your time!

**Comment by markusaksli-nc** [comment] 2021-07-13 09:55
This is the case with firestore and some of the other plugins that create the instance at registration. There is some more discussion on this at the issue I mentioned.

**Comment by joshpetit** [comment] 2021-07-13 10:52
@markusaksli-nc Oh my fault I thought you linked the issue I already referenced in the issue description :facepalm:. This is definitely a duplicate then after reading it, thanks for your time and apologies!
