### ISSUE TITLE
🐛 [firebase_core] it shows an error when i start debugging the project 

### ISSUE THREAD

**Issue by AimenSayoud** [FirebaseExtended/flutterfire#6714] opened 2021-07-26 15:44 UTC
i came from 
#6703
i don't know why **markusaksli-nc**  close it and the problem still not solved 

anyway this is the problem 

when i start building the app it shows me this error

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':firebase_core:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':firebase_core:debugCompileClasspath'.
   > Could not find com.google.firebase:firebase-common:.
     Required by:
         project :firebase_core

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
Exception: Gradle task assembleDebug failed with exit code 1
```

when i start building the project in the emulator in android studio this error shows

i m using the latest version of firebase_core.
and 

i added firebase to my project

project/android/app

```
dependencies {
implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
implementation platform('com.google.firebase:firebase-bom:28.2.1')
implementation "com.google.firebase:firebase-analytics"
}

apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services'
```
project/android
```

dependencies {
    classpath 'com.android.tools.build:gradle:3.5.0'
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    classpath 'com.google.gms:google-services:4.3.8'

}
```
and the google services file.

I tried also to change firebase sdk version  but it didn't work

also i tried to remose this line 

`implementation platform('com.google.firebase:firebase-bom:28.2.1')
`

but still the probem shows

**Comment by markusaksli-nc** [comment] 2021-07-27 12:55
There is no need to open a new issue.
Closing as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6703

**Closed by markusaksli-nc** 2021-07-27 12:55 UTC
Labels: Needs Attention, in triage, type: bug
