### ISSUE TITLE
[Cloud Functions] Callable functions don't work when useFunctionsEmulator() is used.

### ISSUE THREAD

**Issue by ChangYuJonathanWu** [FirebaseExtended/flutterfire#2910] opened 2020-07-07 06:41 UTC
**Describe the bug**
When configured to use the emulator through useFunctionsEmulator(), callable functions fail with: `PlatformException(functionsError, Cloud function failed with exception., {code: INTERNAL, details: null, message: INTERNAL})` 

Other functions work fine.

**To Reproduce**
1. Write callable Cloud Function and verify it can be called when deployed. E.g. 
`exports.someFunction= functions.https.onCall((data, context) => {
  return {success: true};
})`
2. Setup functions emulator with default settings. (e.g. at localhost:5001)
4. Setup Flutter application with Cloud Functions to use emulator:
`      CloudFunctions.instance.useFunctionsEmulator(
          origin: http://10.0.2.2:5001);`
5. Call the Callable function:
```
HttpsCallable someFunction= CloudFunctions.instance.getHttpsCallable(functionName: 'someFunction') ; 
HttpsCallableResult result = await someFunction.call();
```
6. Catch exception:
`PlatformException(functionsError, Cloud function failed with exception., {code: INTERNAL, details: null, message: INTERNAL})`

**Expected behavior**
Callable functions should work when the emulator is used.

**Additional context**
Exception only shows up client-side and not in emulator logs. Full stack trace from calling a callable when a button is pressed:
```
E/flutter (22856): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: PlatformException(functionsError, Cloud function failed with exception., {code: INTERNAL, details: null, message: INTERNAL})
E/flutter (22856): #0      StandardMethodCodec.decodeEnvelope
E/flutter (22856): #1      MethodChannel._invokeMethod
E22856): <asynchronous suspension>
E/flutter (22856): #2      MethodChannel.invokeMethod
E/flutter (22856): #3      MethodChannelCloudFunctions.callCloudFunction
E/flutter (22856): #4      HttpsCallable.call
E/flutter (22856): #5      HomePage.build.<anonymous closure>.<anonymous closure>
E/flutter (22856): #6      _InkResponseState._handleTap
E/flutter (22856): #7      _InkResponseState.build.<anonymous closure>
E/flutter (22856): #8      GestureRecognizer.invokeCallback
E/flutter (22856): #9      TapGestureRecognizer.handleTapUp
E/flutter (22856): #10     BaseTapGestureRecognizer._checkUp
E/flutter (22856): #11     BaseTapGestureRecognizer.handlePrimaryPointer
E/flutter (22856): #12     PrimaryPointerGestureRecognizer.handleEvent
E/flutter (22856): #13     PointerRouter._dispatch
E/flutter (22856): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure>
E/flutter (22856): #15     _LinkedHashMapMixin.forEach  (dart:collection-patch/compact_hash.dart:379:8)
E/flutter (22856): #16     PointerRouter._dispatchEventToRoutes
E/flutter (22856): #17     PointerRouter.route
E/flutter (22856): #18     GestureBinding.handleEvent
E/flutter (22856): #19     GestureBinding.dispatchEvent
E/flutter (22856): #20     GestureBinding._handlePointerEvent
E/flutter (22856): #21     GestureBinding._flushPointerEventQueue
E/flutter (22856): #22     GestureBinding._handlePointerDataPacket
E/flutter (22856): #23     _rootRunUnary  (dart:async/zone.dart:1196:13)
E/flutter (22856): #24     _CustomZone.runUnary  (dart:async/zone.dart:1085:19)
E/flutter (22856): #25     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:987:7)
E/flutter (22856): #26     _invoke1  (dart:ui/hooks.dart:275:10)
E/flutter (22856): #27     _dispatchPointerDataPacket  (dart:ui/hooks.dart:184:5)
```

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.5, on Microsoft Windows [Version 10.0.19041.329], locale en-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.6)
[√] VS Code (version 1.46.1)
[√] Connected device (3 available)

• No issues found!
```

**Comment by TahaTesser** [comment] 2020-07-07 14:16
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2792

**Closed by TahaTesser** 2020-07-07 14:16 UTC
