### ISSUE TITLE
🐛 App not working properly

### ISSUE THREAD

**Issue by itsdani121** [FirebaseExtended/flutterfire#6867] opened 2021-08-23 07:22 UTC
## Bug report

Hi i am making school management app which i use lots of pacakges but when i run the app it looks fine but when i first time click on app button or any widget then its not working until again i click on it i dont know what issue is but this is happen. i attached the code and video what issue i get.kindly look into this matter.

https://issuetracker.google.com/issues/197292075

flutter doctor is 
      
        Doctor summary (to see all details, run flutter doctor -v):
        [√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
        [√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
        [√] Chrome - develop for the web
        [√] Android Studio (version 4.1.0)
        [√] Connected device (3 available)

       • No issues found!

**Comment by markusaksli-nc** [comment] 2021-08-23 10:31
Hi @itsdani121 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
What platform does the issue occur on and are you able to provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by itsdani121** [comment] 2021-08-23 13:04
Ita android phone

**Comment by markusaksli-nc** [comment] 2021-08-24 05:32
Based on your I can't see how this could be related to firebase when it is an issue with the interaction and lifecycle of material design widgets?

What you were describing in issuetracker seems to be related to https://github.com/FirebaseExtended/flutterfire/issues/4316 which is a known issue.

Unless what you described turns out to be somehow related to the FlutterFire plugins you are using I'm closing this in favor of your issuetracker issue for now.

**Closed by markusaksli-nc** 2021-08-24 05:32 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by itsdani121** [comment] 2021-08-24 06:52
flutter doctor -v
[√] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version
10.0.19041.508], locale en-US)
    • Flutter version 2.2.3 at C:\src\flutter_windows_2.0.6-stable\flutter
    • Framework revision f4abaa0735 (8 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[√] Android toolchain - develop for Android devices (Android SDK version
31.0.0)
    • Android SDK at C:\Users\WasiSoft\AppData\Local\Android\sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7249189)

[√] Connected device (3 available)
    • JSN L22 (mobile) • GBT4C18913026549 • android-arm64  • Android 10
(API 29)
    • Chrome (web)     • chrome           • web-javascript • Google Chrome
92.0.4515.159
    • Edge (web)       • edge             • web-javascript • Microsoft Edge
92.0.902.78

• No issues found!

i attached link of code which is github repo
