### ISSUE TITLE
[Dynamic Links] Update requirements for ios

### ISSUE THREAD

**Issue by LucasTejero** [FirebaseExtended/flutterfire#2413] opened 2020-04-22 06:47 UTC
You have to add the FirebaseDynamicLinksCustomDomains in the info.plist

https://firebase.google.com/docs/dynamic-links/custom-domains

and there is no reference in the readme to implement the package.
i lost a lot of time until i discover this.

**Comment by TahaTesser** [comment] 2020-04-22 10:51
Duplicate of [#1738](https://github.com/FirebaseExtended/flutterfire/issues/1738)

**Closed by TahaTesser** 2020-04-22 10:51 UTC
