### ISSUE TITLE
Firebase analytics not working on flutter web

### ISSUE THREAD

**Issue by sarry173** [FirebaseExtended/flutterfire#3017] opened 2020-07-24 07:09 UTC
```
TypeError: Cannot read property 'analytics' of undefined
    at Object.analytics$ [as analytics] (http://localhost:50937/packages/firebase/src/top_level.dart.lib.js:110:102)
    at new firebase_analytics_web.FirebaseAnalyticsWeb.new (http://localhost:50937/packages/firebase_analytics_web/firebase_analytics_web.dart.lib.js:56:64)
    at Function.registerWith (http://localhost:50937/packages/firebase_analytics_web/firebase_analytics_web.dart.lib.js:19:82)
    at Object.registerPlugins (http://localhost:50937/packages/approvalneo/generated_plugin_registrant.dart.lib.js:11:49)
    at main$ (http://localhost:50937/web_entrypoint.dart.lib.js:15:35)
    at main$.next (<anonymous>)
    at runBody (http://localhost:50937/dart_sdk.js:37195:34)
    at Object._async [as async] (http://localhost:50937/dart_sdk.js:37226:7)
    at main$ (http://localhost:50937/web_entrypoint.dart.lib.js:14:18)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:50937/dwds/src/injected/client.js:8451:15)
    at http://localhost:50937/dwds/src/injected/client.js:22495:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:50937/dwds/src/injected/client.js:3744:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:50937/dwds/src/injected/client.js:10956:12)
    at Object._asyncStartSync (http://localhost:50937/dwds/src/injected/client.js:3708:20)
    at main__closure1.$call$body$main__closure (http://localhost:50937/dwds/src/injected/client.js:22507:16)
    at main__closure1.call$1 (http://localhost:50937/dwds/src/injected/client.js:22439:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:50937/dwds/src/injected/client.js:4066:16)
at _CustomZone.runUnary$2$2 (http://localhost:50937/dwds/src/injected/client.js:12275:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:50937/dwds/src/injected/client.js:12203:14)
    at _ControllerSubscription._sendData$1 (http://localhost:50937/dwds/src/injected/client.js:11753:19)
    at _DelayedData.perform$1 (http://localhost:50937/dwds/src/injected/client.js:11907:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:50937/dwds/src/injected/client.js:11956:14)
    at Object._microtaskLoop (http://localhost:50937/dwds/src/injected/client.js:3909:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:50937/dwds/src/injected/client.js:3915:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:50937/dwds/src/injected/client.js:10828:9)
    at invokeClosure (http://localhost:50937/dwds/src/injected/client.js:1172:26)
```

**Comment by darshankawar** [comment] 2020-07-29 09:53
Hi @sarry173,
I see there's a similar open issue describing your case, [2352](https://github.com/FirebaseExtended/flutterfire/issues/2352).
Please follow-up there for updates.
Closing this as duplicate. If you disagree, write in comments and I'll reopen.
Thanks.

**Closed by darshankawar** 2020-07-29 09:53 UTC

**Comment by NightOwlCoder** [comment] 2020-08-01 17:45
@darshankawar I'm having the exact same problem.
My flutter app is iOS/Droid and I was asked to validate the `web` possibility of it.

The solution pointed to by @TahaTesser on SO looks like to be a web only one?
``` dart
import 'dart:js' as js;
...
Widget build(BuildContext context) {
    return MaterialApp(
      navigatorObservers: [AnalyticsRouteObserver(analytics: js.context.hasProperty('firebase')?analytics():null)],
...
}
```

Can someone help us here?

BTW, I'm more than happy to open yet another bug if required.
.NightOwl

**Comment by darshankawar** [comment] 2020-08-03 05:54
@NightOwlCoder please open a new issue and mention all required details.
Thanks.

**Comment by rahulraj64** [comment] 2020-08-03 08:09
Hi @sarry173 
Initially I had this issue with the latest pre releases. 
```
firebase_core: "^0.5.0-dev.2"
firebase_analytics: "^6.0.0-dev.1"
```
Then, I repaired the cache using `flutter pub cache repair` and rebuild, which helped to solve this issue

**Comment by rahulraj64** [comment] 2020-08-03 11:41
I am also having the same issue with the latest pre releases. Followed the documentation at (https://firebase.flutter.dev/docs/analytics/overview/) 
But unable to use the new analytics plugin for flutter web. App crashes with the following error:
**TypeError: Cannot read property 'analytics' of undefined**
Using:
```
firebase_core: "^0.5.0-dev.2"
firebase_analytics: "^6.0.0-dev.1"
```
```
<script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-app.js"></script>
<script src="https://www.gstatic.com/firebasejs/7.14.4/firebase-analytics.js"></script>
<script>
 // Your web app's Firebase configuration
 var firebaseConfig = {...};
 // Initialize Firebase
 firebase.initializeApp(firebaseConfig);
</script>
```
CC @Salakar

**Comment by darshankawar** [comment] 2020-08-03 13:48
Could everyone who still has this problem please file a new issue with the exact description of what happens, logs and the output of `flutter doctor -v`.
All system setups can be slightly different, so it's always better to open new issues and reference related issues.

**Comment by rahulraj64** [comment] 2020-08-04 06:42
Note: Its working when I checked it today. Unable to reproduce. I will report another issue if this happens agains. Seems like some other config/cache problem.
