### ISSUE TITLE
[firebase_admob plugin] _interstitialAd?.dispose() throws PlatformException every time

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#635] opened 2019-10-13 18:48 UTC
I am using `firebase_admob` plugin(0.6.1) to display banner and interstitial ads.

When `_interstitialAd?.dispose()` is call, PlatformException occurs every time.

My code is the same as the example of firebase_admob plugin.
```
  @override
  void dispose() {

    _interstitialAd?.dispose();  --> exception occurs every time

    super.dispose();
  }
```

Flutter : 0.8.2
Dart : 2.1.0-dev.3.1.flutter-760a9690c2
firebase_admob plugin : 0.6.1
```
[VERBOSE-2:shell.cc(181)] Dart Error: Unhandled exception:
PlatformException(no_ad_for_id, dispose failed, no ad exists for id=861467796, null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
<asynchronous suspension>
#2      _invokeBooleanMethod (package:firebase_admob/firebase_admob.dart:509:61)
<asynchronous suspension>
#3      MobileAd.dispose (package:firebase_admob/firebase_admob.dart:229:12)
#4      _ExerciseWidgetState.dispose (file:///Users/upinel9/work/bitbucket/upinel9_treasure_house/dart/flutter/kest/lib/exercise_widget.dart:60:22)
#5      StatefulElement.unmount (package:flutter/src/widgets/framework.dart:3833:12)
#6      _InactiveElements._unmount (package:flutter/src/widgets/framework.dart:1697:13)
#7      _InactiveElements._unmount.<anonymous closure> (package:flutter/src/widgets/framework.dart:1695:7)
#8      SingleChildRenderObjectElement<…>
```

**Comment by kroikie** [comment] 2019-10-13 18:48
@noma15

The issue at https://github.com/flutter/flutter/issues/22488 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by nemoryoliver** [comment] 2019-10-21 07:15
I wish this issue will be fixed soon! Still getting this error....

**Comment by iapicca** [comment] 2019-10-24 12:07
Hi @noma15
If you are still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by nemoryoliver** [comment] 2019-10-24 12:14
@iapicca here's my flutter doctor -v below.

```
[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.15 19A583, locale en-PH)
    • Flutter version 1.9.1+hotfix.5 at /Users/nemoryoliver/Development/flutter
    • Framework revision 1aedbb1835 (7 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/nemoryoliver/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.0, Build version 11A420a
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

[✓] Connected device (1 available)
    • BBD100 2 • 1164448822 • android-arm64 • Android 8.1.0 (API 27)

• No issues found!
```

Also, I temporarily made a workaround by wrapping a try-catch on most of the methods. It's also not easy to reproduce because it's not so often. but I'll try to replicate again and post more logs for here.

**Comment by sukhcha-in** [comment] 2019-10-29 12:28
Tried `myInterstitial.isLoaded()` having same issue.
```
PlatformException (PlatformException(no_ad_for_id, isAdLoaded failed, no add exists for id=985569725, null))
```

**Comment by DevarshRanpara** [comment] 2019-11-07 09:24
I am facing same issue in my iOS platform.

**Comment by drexel-ue** [comment] 2020-04-08 00:25
is anyone noticing this error is happening at the same time, as well?

```
flutter: Error caught by Crashlytics plugin <recordError>:
flutter: 'package:firebase_admob/firebase_admob.dart': Failed assertion: line 241 pos 12: '_allAds[id] != null': is not true.
flutter: 
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:38:5)
#2      MobileAd.dispose (package:firebase_admob/firebase_admob.dart:241:12)
#3      AdBloc._disposeAds (package:trivia_black/blocs/ad_bloc.dart:114:39)
#4      AdBloc._init.<anonymous closure> (package:trivia_black/blocs/ad_bloc.dart:52:32)
#5      _rootRunUnary (dart:async/zone.dart:1155:38)
#6      _CustomZone.runUnary (dart:async/zone.dart:1048:19)
#7      _CustomZone.runUnaryGuarded (dart:async/zone.dart:950:7)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _DelayedData.perform (dart:async/stream_impl.dart:594:14)
#10     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:710:11)
#11     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:670:7)
#12     _rootRun (dart:async/zone.dart:1143:38)

#13     _CustomZone.run (dart:async/zone.dart:1040:19)

**Comment by umaqs** [comment] 2020-04-14 01:03
@drexel-ue 
I am facing the same error on `bannerAd.dispose()`

**Comment by devibrahimkarahan** [comment] 2020-05-19 20:51
Same issue on isLoaded method, any update on this ?

**Comment by ndhbr** [comment] 2020-06-12 17:44
I have the same problem with isLoaded.

**Comment by russellwheatley** [comment] 2021-03-19 12:36
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.

**Closed by russellwheatley** 2021-03-19 12:36 UTC
Labels: bitcoin, impact: customer, plugin: admob, type: bug
