### ISSUE TITLE
🐛 [firebase_auth] Auth status updates not emitted in 1.1.2

### ISSUE THREAD

**Issue by ntrampe** [FirebaseExtended/flutterfire#5979] opened 2021-04-30 04:48 UTC
## Bug report

In firebase_auth 1.1.2 only, FirebaseAuth.instance.authStateChanges() is not emitting updated user objects on iOS devices.

### Steps to reproduce

1. Depend on firebase_auth 1.1.2
2. Listen to FirebaseAuth.instance.authStateChanges()
3. Run your Flutter project on an iOS simulator or device
4. Notice that auth updates are not emitted when authenticating by any credentials

### Expected behavior

Auth updates should be emitted

---

## Additional context

I have tested version 1.1.1 on all devices, as well as 1.1.2 on Android emulators and devices, and the expected behavior is observed in all cases

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.4, on macOS 11.1 20C69 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (4 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.4
nunci 1.4.0+22

dependencies:
- auto_size_text 3.0.0-nullsafety.0 [flutter]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 1.0.5 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.2
- devicelocale 0.4.1 [flutter flutter_web_plugins]
- easy_localization 3.0.0 [flutter shared_preferences intl args path easy_logger flutter_localizations]
- equatable 2.0.0 [collection meta]
- firebase_analytics 7.1.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.1.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.1.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- fl_chart 0.30.0 [flutter equatable pedantic]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.0 [flutter bloc provider]
- flutter_facebook_auth 3.3.3+1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_inapp_purchase 5.0.1 [http meta flutter platform]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_markdown 0.6.1 [flutter markdown meta path]
- flutter_picker 2.0.1 [flutter]
- flutter_sound 8.1.1 [path_provider logger recase uuid provider flutter_spinkit path synchronized flutter flutter_sound_platform_interface flutter_sound_web]
- flutter_staggered_animations 1.0.0 [flutter]
- font_awesome_flutter 9.0.0 [flutter]
- formz 0.4.0
- geolocator 7.0.3 [flutter geolocator_platform_interface geolocator_web]
- get_it 6.1.1 [async collection]
- google_fonts 2.0.0 [flutter http path_provider crypto]
- google_maps_flutter 2.0.3 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_mobile_ads 0.12.1+1 [meta flutter]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- image_picker 0.7.4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl 0.17.0 [clock path]
- package_info 2.0.0 [flutter]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 6.1.3 [flutter meta permission_handler_platform_interface]
- popover 0.2.2 [flutter]
- sign_in_with_apple 3.0.0 [flutter meta]
- simple_animations 3.1.1 [flutter supercharged pedantic]
- smooth_page_indicator 0.3.0-nullsafety.0 [flutter]
- speech_to_text 4.1.1-nullsafety [flutter speech_to_text_platform_interface json_annotation clock pedantic flutter_web_plugins meta js]
- url_launcher 6.0.3 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- args 2.1.0
- async 2.5.0 [collection]
- bloc 7.0.0 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.7 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.3 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.0.5 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- easy_logger 0.0.2 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.2.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.6 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_auth_platform_interface 2.4.2 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.4.2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_sound_platform_interface 8.1.1 [flutter meta plugin_platform_interface]
- flutter_sound_web 8.1.1 [flutter_sound_platform_interface flutter flutter_web_plugins meta js]
- flutter_spinkit 5.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- geolocator_platform_interface 2.0.2 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.3 [flutter flutter_web_plugins geolocator_platform_interface]
- google_maps_flutter_platform_interface 2.0.4 [flutter meta plugin_platform_interface stream_transform collection]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.13.2 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.1.0 [flutter meta http plugin_platform_interface]
- js 0.6.3
- json_annotation 4.0.1
- logger 1.0.0
- markdown 4.0.0 [args charcode meta]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- permission_handler_platform_interface 3.3.0 [flutter meta plugin_platform_interface]
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- provider 5.0.0 [collection flutter nested]
- quiver 3.0.1 [matcher]
- recase 4.0.0
- rxdart 0.26.0
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- speech_to_text_platform_interface 2.0.0-nullsafety [flutter meta plugin_platform_interface]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- supercharged 2.0.0 [supercharged_dart flutter]
- supercharged_dart 2.0.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-04-30 08:46
Hi @ntrampe 
There is already an open issue for changes not persisting through hot restart or app restart https://github.com/FirebaseExtended/flutterfire/issues/5952
You are saying that you receive no events at all?
Thank you

**Comment by ntrampe** [comment] 2021-04-30 09:02
Hi @markusaksli-nc 

Yes, I am saying that I am receiving no events at all. After I sign in with any credentials (google, facebook, phone, anonymous, etc.), or sign out, a new user status is not emitted. When I kill and relaunch the application (not hot reload or restart), an auth status is also not emitted, even if I am signed in.

I did a bit more digging and it looks like this issue might be partially related with firebase_core 1.1.0 updating the Firebase iOS SDK. I downgraded firebase_core to 1.0.4 and things are working normally. It might be because that also transitively downgrades firebase_auth.

I'm not sure if that changes anything. Apologies, I am not too familiar with these packages and how they work together.

**Comment by markusaksli-nc** [comment] 2021-04-30 09:30
Does the `userChanges` stream or `currentUser` provide the correct values for you?
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

**Comment by i-Senku** [comment] 2021-04-30 10:08
> Does the `userChanges` stream or `currentUser` provide the correct values for you?
> Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?

i have some issue. on ios emulator authStateChanges not working. it worked fine in the previous version

**Comment by oodavid** [comment] 2021-04-30 10:53
Same here:

* Android Emulator is fine
* iOS Simulator fails to emit events

Have downgraded to `firebase_auth: 1.1.1` to fix the issue

My code is a bit mixed up with other logic, but this should reproduce it:

```
import 'package:firebase_auth/firebase_auth.dart';

// ...
  static final FirebaseAuth _auth = FirebaseAuth.instance;
_auth.authStateChanges().listen((User? authUser) {
      if (authUser == null) {
        print('no user');
      } else {
        print('has user ${authUser.displayName}');
      }
    });
```

**Comment by Ehesp** [comment] 2021-04-30 11:43
It'd be helpful to not pollute issues with comments which don't detail if the cause is the same.

> @ntrampe  When I kill and relaunch the application (not hot reload or restart), an auth status is also not emitted, even if I am signed in.

This is odd. I've managed to get this working fine across all 3 platforms so trying to replicate now.

> Same here: Android Emulator is fine, iOS Simulator fails to emit events

What events? The initial ones or on actions (sign out/in)?

**Comment by oodavid** [comment] 2021-04-30 12:21
@Ehesp 
> What events? The initial ones or on actions (sign out/in)?

As per the code: `_auth.authStateChanges().listen`

**Comment by psrcek** [comment] 2021-04-30 13:27
I'm seeing the same issue on an iPhone 12 Pro Max with iOS 14.4. No event whatsoever is emitted in the authStateChanges stream besides the initial null.

I'm able to reproduce it with the below files, just add your `GoogleService-Info.plist` and replace your default `com.example.whatever` to whatever is in your firebase config. The line `User Name is signed in!` never gets printed for me.

Podfile:
```Podfile
platform :ios, '11.0'
...
```

pubspec.yaml:
```yaml
name: firebase_authstate
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.1.0
  firebase_auth: 1.1.2
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
```

main.dart:
```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(FirebaseAuthStateBugApp());
}

class FirebaseAuthStateBugApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: FirebaseAuthStateBugHome(),
        appBar: AppBar(
          title: Text('Firebase auth state bug'),
        ),
      ),
    );
  }
}

class FirebaseAuthStateBugHome extends StatefulWidget {
  @override
  _FirebaseAuthStateBugHomeState createState() => _FirebaseAuthStateBugHomeState();
}

class _FirebaseAuthStateBugHomeState extends State<FirebaseAuthStateBugHome> {
  FirebaseAuth get _auth => FirebaseAuth.instance;

  bool _initialized = false;
  dynamic? _error;

  User? user;

  TextEditingController _emailController = TextEditingController();
  TextEditingController _passwordController = TextEditingController();

  void initializeFlutterFire() async {
    try {
      await Firebase.initializeApp();
      setState(() {
        _initialized = true;
      });
    } catch (e) {
      setState(() {
        _error = e;
      });
    }

    print("Listening to authStateChanges");

    _auth.authStateChanges().listen((user) {
      if (user == null) {
        print('User is currently signed out!');
      } else {
        print('User ${user.displayName} is signed in!');
      }

      setState(() {
        this.user = user;
      });
    });
  }

  @override
  void initState() {
    initializeFlutterFire();
    super.initState();
  }

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();

    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    if (_error != null) {
      Text('Error: $_error');
    }

    if (!_initialized) {
      return CircularProgressIndicator();
    }

    if (this.user != null) {
      return Center(
        child: Text('Logged in:\n${user!.displayName}\n${user!.email}'),
      );
    }

    return Column(
      children: [
        TextField(
          controller: _emailController,
          autocorrect: false,
          decoration: InputDecoration(labelText: 'Email'),
        ),
        TextField(
          controller: _passwordController,
          obscureText: true,
          autocorrect: false,
          decoration: InputDecoration(labelText: 'Password'),
        ),
        ElevatedButton(
          onPressed: _login,
          child: Text('Log in'),
        ),
      ],
    );
  }

  Future<void> _login() async {
    try {
      print("Logging in: ${_emailController.text} ${_passwordController.text}");

      final result = await _auth.signInWithEmailAndPassword(
        email: _emailController.text,
        password: _passwordController.text,
      );

      print("Login result: $result");
    } catch (e, trace) {
      print("Login error: $e\n$trace");
    }
  }
}
```

Logs of execution:
```log
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
 lib/main.dart
Xcode build done.                                           52.0s
Connecting to VM Service at ws://127.0.0.1:49425/GdpsD-6xx8U=/ws
flutter: Listening to authStateChanges
flutter: User is currently signed out!
flutter: Logging in: [redacted] [redacted]
flutter: Login result: UserCredential(additionalUserInfo: AdditionalUserInfo(isNewUser: false, profile: {}, providerId: password, username: null), credential: null, user: User(displayName: [redacted], email: [redacted], emailVerified: true, isAnonymous: false, metadata: UserMetadata(creationTime: 2020-08-06 00:03:05.126, lastSignInTime: 2021-04-30 06:21:32.756), phoneNumber: null, photoURL: null, providerData, [UserInfo(displayName: [redacted], email: [redacted], phoneNumber: null, photoURL: null, providerId: password, uid: [redacted])], refreshToken: , tenantId: null, uid: [redacted]))
```

**Comment by Ehesp** [comment] 2021-04-30 14:25
Closing this, we think it's a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/5952 after investigating (same underlying cause).

**Closed by Ehesp** 2021-04-30 14:25 UTC
Labels: blocked: customer-response, in triage, type: bug
