### ISSUE TITLE
[firebase_messaging] Flutter 1.12.13+hotfix.5 Unresolved supertypes FlutterFirebaseMessagingService

### ISSUE THREAD

**Issue by 01FC** [FirebaseExtended/flutterfire#1646] opened 2019-12-14 22:49 UTC
After the latest Flutter stable update **Flutter 1.12.13+hotfix.5** and trying to update the plugin to firebase_messaging: ^6.0.9 and the gradle configurations (3.5.3 and google services 4.3.2) there is an error that brakes the gradle assembly.

```
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService, unresolved supertypes: com.google.firebase.messaging.FirebaseMessagingService
```
It was working fine in the previous flutter stable version 1.9.4+hotfix.6 and the previous plugin version and gradle configurations.

**Comment by iapicca** [comment] 2019-12-19 15:18
Hi @01FC 
can you please provide your updated  `flutter doctor -v`
and your `flutter run --verbose`?
Also, to better address the issue, would be helpful
if you could post  a minimal code sample
or the steps to reproduce the problem.
Thank you

**Comment by medyas** [comment] 2019-12-23 13:41
@iapicca I am getting the same issue. I just created a new project and added firebase_messaging and build fails because of this.
```
Launching lib\main.dart on AOSP on IA Emulator in debug mode...
Running Gradle task 'assembleDebug'...
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService, unresolved supertypes: com.google.firebase.messaging.FirebaseMessagingService


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugKotlin'.
> Compilation error. See log for more details
```
Flutter Doctor:
```
[√] Flutter (Channel stable, v1.12.13+hotfix.5, on Microsoft Windows [Version 10.0.17763.864], locale en-US)
    • Flutter version 1.12.13+hotfix.5 at C:\flutter
    • Framework revision 27321ebbad (12 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0
```
Flutter run --verbose
```
[+1409 ms] > Task :app:compileDebugKotlin FAILED
[   +7 ms] e: Supertypes of the following classes cannot be resolved. Please make sure you have the required
dependencies in the classpath:
[  +14 ms]     class io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService, unresolved supertypes:
com.google.firebase.messaging.FirebaseMessagingService
[  +29 ms] FAILURE: Build failed with an exception.
[   +1 ms] * What went wrong:
[   +6 ms] Execution failed for task ':app:compileDebugKotlin'.
[   +1 ms] > Compilation error. See log for more details
[   +2 ms] * Try:
[   +7 ms] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log
output. Run with --scan to get full insights.
[   +5 ms] * Get more help at https://help.gradle.org
[   +1 ms] BUILD FAILED in 9s
[   +2 ms] 148 actionable tasks: 7 executed, 141 up-to-date
[ +358 ms] Running Gradle task 'assembleDebug'... (completed in 10.5s)
[  +11 ms] "flutter run" took 11,822ms.
Gradle task assembleDebug failed with exit code 1

#0      throwToolExit (package:flutter_tools/src/base/common.dart:28:3)
#1      buildGradleApp (package:flutter_tools/src/android/gradle.dart:387:7)
#2      _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#3      _rootRunUnary (dart:async/zone.dart:1134:38)
#4      _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#5      _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#6      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#7      Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#8      Future._completeWithValue (dart:async/future_impl.dart:524:5)
#9      _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:32:15)
#10     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:290:13)
#11     _DefaultProcessUtils.stream (package:flutter_tools/src/base/process.dart)
#12     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:73:64)
#13     _rootRunUnary (dart:async/zone.dart:1134:38)
#14     _CustomZone.runUnary (dart:async/zone.dart:1031:19)
#15     _FutureListener.handleValue (dart:async/future_impl.dart:139:18)
#16     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:680:45)
#17     Future._propagateToListeners (dart:async/future_impl.dart:709:32)
#18     Future._completeWithValue (dart:async/future_impl.dart:524:5)
#19     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:554:7)
#20     _rootRun (dart:async/zone.dart:1126:13)
#21     _CustomZone.run (dart:async/zone.dart:1023:19)
#22     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
#23     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:965:23)
#24     _microtaskLoop (dart:async/schedule_microtask.dart:43:21)
#25     _startMicrotaskLoop (dart:async/schedule_microtask.dart:52:5)
#26     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#27     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:175:5)

```

**Comment by piecubed** [comment] 2020-06-28 18:50
Has this been fixed yet?  I'm having this issue too

**Comment by Salakar** [comment] 2020-11-05 09:47
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.

**Closed by Salakar** 2020-11-05 09:47 UTC
Labels: impact: crowd, platform: android, plugin: messaging, severe: regression, type: bug
