### ISSUE TITLE
🐛 [google_sign_in] Google Sign-in not working after deploying to Google Play while it works perfectly fine on development 

### ISSUE THREAD

**Issue by julesdmercado** [FirebaseExtended/flutterfire#7435] opened 2021-11-26 16:56 UTC
## Bug report

**Describe the bug**
After the .aab is uploaded to Google Play and downloaded right after, Google Sign-in suddenly just stops working, while works completely fine during development. Working fine means nothing is wrong with Firebase integration, appbundleId is the same and I can signin with any email I want during development.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Mac OS X 10.14.6 18G9323 darwin-x64, locale en-PH)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode 10.3.0 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.62.3)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```

Dart SDK 2.13.4
Flutter SDK 2.2.3
criiit 1.0.2+4

dependencies:
- change_app_package_name 1.0.0
- cloud_firestore 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cloud_functions 3.1.1 [cloud_functions_platform_interface cloud_functions_web firebase_core firebase_core_platform_interface flutter]
- country_codes 2.0.1 [flutter]
- cupertino_icons 1.0.3
- dio 4.0.0 [http_parser path]
- firebase_auth 1.1.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 2.0.7 [firebase_core flutter]
- firebase_messaging 10.0.4 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 8.0.6 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 8.1.1+1 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_polyline_points 1.0.0 [flutter http]
- flutter_riverpod 0.13.1+1 [collection flutter meta riverpod state_notifier]
- flutter_secure_storage 4.2.0 [meta flutter]
- flutter_staggered_grid_view 0.4.0 [flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- geocoder 0.2.1 [meta flutter]
- geoflutterfire 3.0.0-nullsafety.2 [flutter cloud_firestore rxdart]
- geolocator 7.4.0 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web]
- google_maps_flutter 2.0.5 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_mobile_ads 0.13.5 [meta flutter]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_cropper 1.4.0 [flutter]
- image_picker 0.7.4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl 0.17.0 [clock path]
- json_annotation 4.0.1
- json_to_model 2.3.1 [args logging path]
- location 4.2.3 [flutter location_platform_interface location_web meta]
- markdown 4.0.0 [args charcode meta]
- material_design_icons_flutter 5.0.5955-rc.1 [flutter]
- miniplayer 1.0.0+2 [flutter]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 8.1.4+2 [flutter meta permission_handler_platform_interface]
- provider 5.0.0 [collection flutter nested]
- rename 1.3.1 [args logger]
- rxdart 0.26.0
- share_plus 2.1.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- simple_moment 1.1.1 [intl]
- sms_autofill 2.0.0 [pin_input_text_field flutter]
- timeago 3.0.2
- url_launcher 6.0.6 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.1.1 [meta video_player_platform_interface video_player_web flutter flutter_test]
- video_thumbnail 0.3.3 [flutter]

dev dependencies:
- build_runner 2.0.4 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- json_serializable 4.1.3 [analyzer build build_config collection json_annotation meta path source_gen]

transitive dependencies:
- _fe_analyzer_shared 22.0.0 [meta]
- analyzer 1.7.1 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.2.0
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.2 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.3 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.6 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.7 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- cloud_functions_platform_interface 5.0.14 [firebase_core flutter meta plugin_platform_interface]
- cloud_functions_web 4.1.1 [cloud_functions_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.1 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.1 [meta path]
- firebase_auth_platform_interface 4.2.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.1.0 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.2.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.3 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.3 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.0.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.0.6 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_local_notifications_platform_interface 4.0.1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.1 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- freezed_annotation 0.14.1 [collection json_annotation meta]
- frontend_server_client 2.1.0 [async path]
- geolocator_android 1.0.0 [flutter geolocator_platform_interface]
- geolocator_apple 1.0.0 [flutter geolocator_platform_interface]
- geolocator_platform_interface 2.3.2 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.6 [flutter flutter_web_plugins geolocator_platform_interface]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_maps_flutter_platform_interface 2.0.4 [flutter meta plugin_platform_interface stream_transform collection]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 2.0.0
- http 0.13.3 [async http_parser meta path pedantic]
- http_multi_server 3.0.1 [async]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.1.0 [flutter meta http plugin_platform_interface]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- linkify 4.0.0
- location_platform_interface 2.2.0 [flutter meta plugin_platform_interface]
- location_web 3.1.0 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logger 1.1.0
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- package_config 2.0.0 [path]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- permission_handler_platform_interface 3.6.1 [flutter meta plugin_platform_interface]
- petitparser 4.1.0 [meta]
- pin_input_text_field 4.0.0 [flutter]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1 [matcher]
- riverpod 0.13.1 [collection freezed_annotation meta state_notifier]
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.4 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.0 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timezone 0.7.0 [path]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.0 [flutter flutter_web_plugins meta video_player_platform_interface]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by YuriiVasylyshyn** [comment] 2021-11-29 11:14
Hello @julesdmercado , I've faced the same issue, were you able to fix it?

**Comment by julesdmercado** [comment] 2021-11-29 11:28
@YuriiVasylyshyn currently still looking for a fix. Have you tried to update package? Because I am about to. I also tried to promote my app on OAuth screen to "In Production" and currently in review by Google. My credentials also is not restricted anymore. All that and I still don't know what is happening.

**Comment by YuriiVasylyshyn** [comment] 2021-11-29 11:33
@julesdmercado I've tried to update every firebase connected package in my app, also I've noticed that I had not SHA1 key connected in firebase console, I'm using anonymous sign in by the way, but when i connected this key, nothing happened, still have this issue.

**Comment by julesdmercado** [comment] 2021-11-29 11:44
@YuriiVasylyshyn have you tried contacting Firebase support? They refused me as they said it is not a Firebase issue while Google just referred me somewhere else

**Comment by YuriiVasylyshyn** [comment] 2021-11-29 11:46
@julesdmercado No I haven’t. Will contact and send here the result.

**Comment by darshankawar** [comment] 2021-11-29 11:55
@julesdmercado 
Can you confirm if the issue is limited only to google_sign_in ? If so, the plugin and it's issues are tracked in flutter/flutter repo and not here, because the plugin is maintained by flutter team itself. If you could confirm the same behavior without using any firebase integration steps, then we can move this issue in dedicated repo.

**Comment by julesdmercado** [comment] 2021-11-29 12:05
> If you could confirm the same behavior without using any firebase integration steps

I'm sorry, I might not be able to know how to do that since the app mainly uses Firebase upon login.

**Comment by darshankawar** [comment] 2021-11-29 12:47
@julesdmercado 
Can you provide an error log ? `not working` is very vague and we won't know exactly where the issue could be and hence an error or exception log would be helpful.

**Comment by julesdmercado** [comment] 2021-11-29 12:55
@darshankawar can you suggest how something how to do that? As I am scratching my head since it is perfectly fine while in development and it only happens after deploying to Google Play. Any suggestion is greatly appreciated. Would it also help if I show you logs while on development?

**Comment by YuriiVasylyshyn** [comment] 2021-11-29 13:02
@julesdmercado You can made a trick I've discovered to show market app log. First of all run release version `flutter run --release` on your device/emulator and the just remove app but do not stop flutter run work. After that you can download app from market and try to run it. Console should show logs of play market app.

**Comment by julesdmercado** [comment] 2021-11-29 13:52
> @julesdmercado You can perform a trick I've discovered to show market app log. First of all run release version `flutter run --release` on your device/emulator and then just remove app but do not stop flutter run work. After that you can download app from market and try to run it. Console should show logs of play market app.

okay cool trick. Let me try.

**Comment by julesdmercado** [comment] 2021-11-30 06:04
flutter run --release the result is behaving the same way. Google sign in will not work.

This is all it shows on terminal 

`Flutter run key commands.
h Repeat this help message.
c Clear the screen
q Quit (terminate the application on the device).
D/FlutterLocationService(20681): Creating service.
D/FlutterLocationService(20681): Binding to location service.
E/flutter (20681): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.b: 10: , null, null)
E/flutter (20681): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:597)
E/flutter (20681): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:158)
E/flutter (20681): <asynchronous suspension>
E/flutter (20681): #2      MethodChannel.invokeMapMethod (package:flutter/src/services/platform_channel.dart:358)
E/flutter (20681): <asynchronous suspension>
E/flutter (20681): #3      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:233)
E/flutter (20681): <asynchronous suspension>
E/flutter (20681): #4      GoogleSignIn.signIn.isCanceled (package:google_sign_in/google_sign_in.dart:361)
E/flutter (20681): <asynchronous suspension>
E/flutter (20681): `

**Comment by darshankawar** [comment] 2021-11-30 11:59
Thanks for the logs which makes it clear to me that this isn't firebase related, but specific to `google_sign_in` plugin:

`Unhandled Exception: PlatformException(sign_in_failed, com.google.android.gms.common.api.b: 10: , null, null)`

Please refer to below similar issues
https://github.com/flutter/flutter/issues/75224
https://github.com/flutter/flutter/issues/33393

Both of them have comments / solutions mentioned that you may try and see if they help.

Closing out from here.

**Closed by darshankawar** 2021-11-30 11:59 UTC
Labels: type: bug, Needs Attention, in triage
