### ISSUE TITLE
[📚] Different error codes for Firebase Auth are not available

### ISSUE THREAD

**Issue by Tom3652** [FirebaseExtended/flutterfire#6970] opened 2021-09-08 18:46 UTC
The following [documentation](https://firebase.flutter.dev/docs/auth/error-handling) suggest to check out the [Reference API](https://pub.dev/documentation/firebase_auth/latest/) to get the informations about the (many) error codes available.

However i went down until the ```code``` property of the ```FirebaseAuthException``` and there are no list of the possible error code / messages.

Here is the [error code page](https://pub.dev/documentation/firebase_core_platform_interface/latest/firebase_core_platform_interface/FirebaseException/code.html) that should display a list such as follow for instance : 

```
switch (error.code) {
        case "invalid-email":
          // Description of the code, how to "get" it
          break;
        case "wrong-password":
          break;
        case "user-not-found":
          break;
        case "user-disabled":
          break;
        case "account-exists-with-different-credential":
}
```

Thanks !

**Comment by markusaksli-nc** [comment] 2021-09-09 09:09
Hi @Tom3652 
This looks like a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6326
Thank you

**Closed by markusaksli-nc** 2021-09-09 09:09 UTC
Labels: type: documentation, good first issue, in triage
