### ISSUE TITLE
[cloud_firestore] Transaction: INTERNAL ASSERTION FAILED

### ISSUE THREAD

**Issue by Nuytemans-Dieter** [FirebaseExtended/flutterfire#2587] opened 2020-05-19 20:44 UTC
**Describe the bug**
Our app has been having some issues with Transactions causing the app to crash. The transaction was supposed to update fields in an existing document. It even happens when no concurrency is taking place. The issue does not happen every time, sometimes it works fine and sometimes it doesn't. We are yet to find any correlation between possible causes and the error.

**To Reproduce**
We are unsure what causes this error, it is quite severe but does not seem to point at our code directly. Both emulator as actual devices have the problem. Our transaction looks like the snippet below, but is in reality very lengthy so I shortened it for now.

````
static Future< bool > updateGroup(GroupData groupData) async {
    await Firestore.instance.runTransaction((Transaction transaction) async {
        GroupData freshData;
        DocumentReference docRef = Firestore.instance.collection("groups").document( code );
        DocumentSnapshot snap = await transaction.get( docRef );
      
        if (snap.exists)
          freshData = new GroupData.fromDocumentSnapshot( snap );
        else
          freshData = groupData;

        // Lots of lines were removed that make changes to the document

        await transaction.set(docRef, data);
    });
    return true;
}
````

**Expected behavior**
We expected the document to be updated consistently with the new data.

**Flutter doctor**
````
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.1, on Microsoft Windows [Version 10.0.18362.836], locale nl-BE)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Android Studio (version 3.5)
[!] IntelliJ IDEA Community Edition (version 2019.2)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.
````

**Stacktrace**
```
E/AndroidRuntime( 7246): FATAL EXCEPTION: AsyncTask #5
E/AndroidRuntime( 7246): Process: be.dezijwegel.blackbox, PID: 7246
E/AndroidRuntime( 7246): java.lang.RuntimeException: An error occurred while executing doInBackground()
E/AndroidRuntime( 7246):        at android.os.AsyncTask$3.done(AsyncTask.java:354)
E/AndroidRuntime( 7246):        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
E/AndroidRuntime( 7246):        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
E/AndroidRuntime( 7246):        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
E/AndroidRuntime( 7246):        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
E/AndroidRuntime( 7246):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/AndroidRuntime( 7246):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/AndroidRuntime( 7246):        at java.lang.Thread.run(Thread.java:764)
E/AndroidRuntime( 7246): Caused by: java.lang.AssertionError: INTERNAL ASSERTION FAILED: A transaction object cannot be used after its update callback has been invoked.
E/AndroidRuntime( 7246):        at com.google.firebase.firestore.util.Assert.fail(com.google.firebase:firebase-firestore@@21.3.0:46)
E/AndroidRuntime( 7246):        at com.google.firebase.firestore.util.Assert.hardAssert(com.google.firebase:firebase-firestore@@21.3.0:31)
E/AndroidRuntime( 7246):        at com.google.firebase.firestore.core.Transaction.ensureCommitNotCalled(com.google.firebase:firebase-firestore@@21.3.0:246)
E/AndroidRuntime( 7246):        at com.google.firebase.firestore.core.Transaction.lookup(com.google.firebase:firebase-firestore@@21.3.0:81)
E/AndroidRuntime( 7246):        at com.google.firebase.firestore.Transaction.getAsync(com.google.firebase:firebase-firestore@@21.3.0:191)
E/AndroidRuntime( 7246):        at com.google.firebase.firestore.Transaction.get(com.google.firebase:firebase-firestore@@21.3.0:228)
E/AndroidRuntime( 7246):        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:613)
E/AndroidRuntime( 7246):        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$5.doInBackground(CloudFirestorePlugin.java:608)
E/AndroidRuntime( 7246):        at android.os.AsyncTask$2.call(AsyncTask.java:333)
E/AndroidRuntime( 7246):        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
E/AndroidRuntime( 7246):        ... 4 more
D/OSTracker( 7246): OS Event: crash
I/Process ( 7246): Sending signal. PID: 7246 SIG: 9
Lost connection to device.
```

**Comment by TahaTesser** [comment] 2020-05-20 12:30
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1969

**Closed by TahaTesser** 2020-05-20 12:30 UTC
