### ISSUE TITLE
[firebase_auth] App crash in ios13.1 release build

### ISSUE THREAD

**Issue by SathishGovindaraju** [FirebaseExtended/flutterfire#246] opened 2019-10-02 08:10 UTC
Hi
My flutter app crashes with the attached error stack on ios 13.1. The same app is completely stable in android and pre 13.1 iOS versions

The crash seems to be related to firebase Auth

I would really appreciate any help on fixing it as it is my first flutter app and this issue is blocking its release in the App store.

<details>

  <summary>screenshots</summary>

![Screenshot_20191002-090221__01](https://user-images.githubusercontent.com/10033810/66028122-56beaa80-e4f4-11e9-8144-1c9c1292a7ff.jpg)
![Screenshot_20191002-090248__01](https://user-images.githubusercontent.com/10033810/66028123-56beaa80-e4f4-11e9-8de5-b311fafee71d.jpg)

</details>

**Comment by caseyryan** [comment] 2019-10-02 13:31
It's not acompletely stable on Android. The same happens on Android 5, 9 and maybe every other version. I can surely say about the 5th and 9th version because I've tested on them.
Here's my bug report as well https://github.com/FirebaseExtended/flutterfire/issues/249

**Comment by SathishGovindaraju** [comment] 2019-10-09 14:50
For me it works fine in simulator! Unable to find a solution for this issue. Stopping us from releasing the app to app store

**Comment by caseyryan** [comment] 2019-10-09 14:58
> For me it works fine in simulator! Unable to find a solution for this issue. Stopping us from releasing the app to app store
Try realtime QR scanning. Launch a camera for scan 3 - 5 times. It will crash. I tested in in many emlators and real devices. It crashes on all of them

**Comment by iapicca** [comment] 2019-10-21 13:17
Hi @SathishGovindaraju 
could you please provide your `flutter doctor -v`
and your `flutter run --verbose`.
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Please refrain 
from posting pictures if not necessary.
Thank you

**Comment by iapicca** [comment] 2019-11-20 13:34
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-20 13:34 UTC
Labels: bug, waiting for customer response
