### ISSUE TITLE
[firebase_ml_vision] Custom model plugin

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#788] opened 2019-10-13 19:05 UTC
@bparrishMines Thank you for the official MLKit Vision plugin located here, 
https://github.com/flutter/plugins/tree/master/packages/firebase_ml_vision

This is a request for Custom MLIntepreter plugin, supported by MLKit
https://firebase.google.com/docs/reference/android/com/google/firebase/ml/custom/package-summary

**Comment by kroikie** [comment] 2019-10-13 19:05
@startupgurukul

The issue at https://github.com/flutter/flutter/issues/18660 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by nominator** [comment] 2020-01-15 13:09
Is there any news on when can we expect an ml-kit plugin for custom models? I am currently using an alternative plugin 'mlkit', it works fine on Android but on iOS it is not working at all.

**Comment by bhack** [comment] 2020-01-29 15:00
Is this the same of https://github.com/FirebaseExtended/flutterfire/issues/1675?

**Comment by prakharb10** [comment] 2020-07-14 16:41
Is this a duplicate of #401 ?

**Comment by bparrishMines** [comment] 2020-07-17 03:49
Our team is currently working on other priorities, so we don't have anyone that can work on this in the near future.

**Comment by prakharb10** [comment] 2020-08-13 09:04
I think we can close this issue now @bparrishMines

**Comment by elvisun** [comment] 2020-08-13 20:01
custom model is now supported in a separate plugin thanks to @PolinaGo !!
https://pub.dev/packages/firebase_ml_custom

**Closed** 2020-08-14 18:14 UTC
Labels: plugin: ml_vision, type: enhancement, type: missing-feature
