### ISSUE TITLE
🐛 [cloud_firestore] DocumentReference has internally wrong Settings when received from snapshots()

### ISSUE THREAD

**Issue by jutarhon** [FirebaseExtended/flutterfire#3935] opened 2020-10-22 16:18 UTC
## Bug report

**Describe the bug**
When you have **custom** settings set and you start immediately listening snapshots (no other calls which might set inner method_channel instances) and then receive document with DocumentReference, and try to get it, it will cause internal exception

```
E/FLTFirestoreMsgCodec(17216): java.lang.IllegalStateException: FirebaseFirestore has already been started and its settings can no longer be changed. You can only call setFirestoreSettings() before calling any other methods on a FirebaseFirestore object.
E/FLTFirestoreMsgCodec(17216): 	at com.google.firebase.firestore.FirebaseFirestore.setFirestoreSettings(com.google.firebase:firebase-firestore@@21.4.3:191)
E/FLTFirestoreMsgCodec(17216): 	at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readFirestoreInstance(FlutterFirebaseFirestoreMessageCodec.java:244)
```

This is because, when you receive (in firestore_message_codec.dart) new DocumentReference ->
```
case _kDocumentReference:
        final String appName = readValue(buffer);
        final String path = readValue(buffer);
        final FirebaseApp app = Firebase.app(appName);
        final FirebaseFirestorePlatform firestore =
            FirebaseFirestorePlatform.instanceFor(app: app);
        return firestore.doc(path);
```
In there that FirebaseFirestorePlatform.instanceFor(app: app); will create completely new instance (of MethodChannelFirebaseFirestore) ... which has ->
`Settings _settings = Settings();
`

So when calling `get` for this `DocumentReference` (although it has right  settings) those empty settings are sent to Android side, and finally causes that exception.

### Steps to reproduce

1. Set custom settings
```
_firestore = FirebaseFirestore.instance;
_firestore.settings = Settings( persistenceEnabled: false, cacheSizeBytes: 1024 * 1024 );

```
2. Start listening snapshots
```
Stream<QuerySnapshot> stream = someCollection.snapshots();
stream.listen((event) {
  event.docChanges.forEach( (change) async {
      Map data = change.doc.data();
      await data[ 'something_that_is_ref'].get();  // <--- this causes internal exception
  }
}
```

**Comment by markusaksli-nc** [comment] 2020-10-23 08:25
Reproducible on the latest flutter master `1.24.0-4.0.pre.33` with `cloud_firestore: ^0.14.1+3`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-4.0.pre.33, on Microsoft Windows [Version 10.0.19041.572], locale en-US)
    • Flutter version 1.24.0-4.0.pre.33 at C:\Development\flutter_master
    • Framework revision 351ccf7eaf (2 hours ago), 2020-10-22 23:28:51 -0700
    • Engine revision defa8be2b1
    • Dart version 2.11.0 (build 2.11.0-242.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.6.5)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.6.30320.27
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6858069
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.4818.26
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • sdk gphone x86 arm (mobile) • emulator-5554 • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows       • windows-x64    • Microsoft Windows [Version 10.0.19041.572]
    • Web Server (web)            • web-server    • web-javascript • Flutter Tools
    • Chrome (web)                • chrome        • web-javascript • Google Chrome 86.0.4240.75
    • Edge (web)                  • edge          • web-javascript • Microsoft Edge 86.0.622.38

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  FirebaseFirestore _firestore = FirebaseFirestore.instance;
  _firestore.settings = Settings(persistenceEnabled: false, cacheSizeBytes: 1024 * 1024);
  Stream<QuerySnapshot> stream = _firestore.collection('ref_collection').snapshots();
  stream.listen((event) {
    event.docChanges.forEach((change) async {
      Map data = change.doc.data();
      await data['ref'].get(); // <--- this causes internal exception
    });
  });
  runApp(MaterialApp(home: Container()));
}
```
</details>
<details>
 <summary>Logs</summary>

```
[   +4 ms] V/NativeCrypto(15854): Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
[        ] W/evercode.triag(15854): Accessing hidden method Ljava/security/spec/ECParameterSpec;->getCurveName()Ljava/lang/String; (greylist, reflection, allowed)
[  +12 ms] I/ProviderInstaller(15854): Installed default security provider GmsCore_OpenSSL
[ +102 ms] W/evercode.triag(15854): Accessing hidden field Ljava/net/Socket;->impl:Ljava/net/SocketImpl; (greylist, reflection, allowed)
[        ] W/evercode.triag(15854): Accessing hidden method Ldalvik/system/CloseGuard;->get()Ldalvik/system/CloseGuard; (greylist,core-platform-api, linking, allowed)
[   +1 ms] W/evercode.triag(15854): Accessing hidden method Ldalvik/system/CloseGuard;->open(Ljava/lang/String;)V (greylist,core-platform-api, linking, allowed)
[        ] W/evercode.triag(15854): Accessing hidden field Ljava/io/FileDescriptor;->descriptor:I (greylist, JNI, allowed)
[  +34 ms] W/evercode.triag(15854): Accessing hidden method Ljava/security/spec/ECParameterSpec;->setCurveName(Ljava/lang/String;)V (greylist, reflection, allowed)
[  +12 ms] W/evercode.triag(15854): Accessing hidden method Ldalvik/system/BlockGuard;->getThreadPolicy()Ldalvik/system/BlockGuard$Policy; (greylist,core-platform-api, linking, allowed)
[        ] W/evercode.triag(15854): Accessing hidden method Ldalvik/system/BlockGuard$Policy;->onNetwork()V (greylist, linking, allowed)
[ +442 ms] E/DartMessenger(15854): Uncaught exception in binary message listener
[        ] E/DartMessenger(15854): java.lang.IllegalStateException: FirebaseFirestore has already been started and its settings can no longer be changed. You can only call setFirestoreSettings() before calling any other methods on a FirebaseFirestore object.
[        ] E/DartMessenger(15854):      at com.google.firebase.firestore.FirebaseFirestore.setFirestoreSettings(com.google.firebase:firebase-firestore@@21.4.3:191)
[        ] E/DartMessenger(15854):      at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readFirestoreInstance(FlutterFirebaseFirestoreMessageCodec.java:241)
[        ] E/DartMessenger(15854):      at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readValueOfType(FlutterFirebaseFirestoreMessageCodec.java:205)
[        ] E/DartMessenger(15854):      at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
[        ] E/DartMessenger(15854):      at io.flutter.plugin.common.StandardMessageCodec.readValueOfType(StandardMessageCodec.java:410)
[        ] E/DartMessenger(15854):      at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestoreMessageCodec.readValueOfType(FlutterFirebaseFirestoreMessageCodec.java:224)
[   +1 ms] E/DartMessenger(15854):      at io.flutter.plugin.common.StandardMessageCodec.readValue(StandardMessageCodec.java:317)
[   +1 ms] E/DartMessenger(15854):      at io.flutter.plugin.common.StandardMethodCodec.decodeMethodCall(StandardMethodCodec.java:48)
[   +1 ms] E/DartMessenger(15854):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
[        ] E/DartMessenger(15854):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
[        ] E/DartMessenger(15854):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:693)
[        ] E/DartMessenger(15854):      at android.os.MessageQueue.nativePollOnce(Native Method)
[        ] E/DartMessenger(15854):      at android.os.MessageQueue.next(MessageQueue.java:335)
[        ] E/DartMessenger(15854):      at android.os.Looper.loop(Looper.java:183)
[        ] E/DartMessenger(15854):      at android.app.ActivityThread.main(ActivityThread.java:7656)
[        ] E/DartMessenger(15854):      at java.lang.reflect.Method.invoke(Native Method)
[        ] E/DartMessenger(15854):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
[        ] E/DartMessenger(15854):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
[        ] E/flutter (15854): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method DocumentReference#get on channel plugins.flutter.io/firebase_firestore)
[        ] E/flutter (15854): #0      convertPlatformException (package:cloud_firestore_platform_interface/src/method_channel/utils/exception.dart:13:5)
[        ] E/flutter (15854): #1      MethodChannelDocumentReference.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:80:13)
[        ] E/flutter (15854): <asynchronous suspension>
[        ] E/flutter (15854): #2      DocumentReference.get (package:cloud_firestore/src/document_reference.dart:63:20)
[        ] E/flutter (15854): <asynchronous suspension>
[        ] E/flutter (15854): #3      main.<anonymous closure>.<anonymous closure> (package:triage/main.dart:15:7)
[        ] E/flutter (15854): <asynchronous suspension>
[        ] E/flutter (15854): 
```
</details>

**Comment by nipunasudha** [comment] 2021-01-12 22:54
I use custom settings only when I use the Firebase Emulators. This error occurs on the emulator too. This is a critical error for everybody who use custom settings for any purpose.

**Comment by nipunasudha** [comment] 2021-01-22 09:28
Please, this needs more attention!

**Comment by muzzah** [comment] 2021-01-22 23:09
I am also seeing this error. Any update on when this will be fixed?

Using
```
  cloud_firestore: ^0.16.0
  firebase_core: ^0.7.0
```

**Comment by muzzah** [comment] 2021-01-23 20:52
This is happening very frequently to me and its rather annoying, is there an update on when this will be fixed?

**Comment by markusaksli-nc** [comment] 2021-01-25 12:20
Please thumbs up the original issue comment to bring more attention to the issue instead of commenting that you have the same issue unless you have anything unmentioned to contribute.

**Comment by muzzah** [comment] 2021-01-31 00:05
@markusaksli-nc  Dont get me wrong but as a paying customer of firebase, who currently has to constantly reload the app multiple times while developing, it gets a bit annoying that we have to wait for somewhat a semi-decent development experience with flutter and firebase. If this is not going to be fixed for a while, at least let us know so we know what to expect. Otherwise hiding comments is not very helpful since apparently  firestore is meant to be at a stable version when it seems not to be the case. All I am asking is if there is a fix in the pipeline or not.

**Comment by nipunasudha** [comment] 2021-01-31 00:53
Effort put into moderating the issue threads would be more useful if used for moderating these untested chaotic releases. Sorry

**Comment by muzzah** [comment] 2021-02-07 23:33
Is there any update @markusaksli-nc ? Or should we just release versions of our apps with serious bugs such as these?

**Closed** 2021-02-18 16:45 UTC
Labels: impact: crowd, plugin: cloud_firestore, type: bug
