### ISSUE TITLE
[firebase_admob] inline banner

### ISSUE THREAD

**Issue by glennmichaelmejias** [FirebaseExtended/flutterfire#296] opened 2019-10-11 07:42 UTC
a banner ads that can be put on listview or can be a child with any widgets.

**Comment by jesusmartinoza** [comment] 2019-10-17 08:18
Currently is not possible with this package, maybe you can try with this one https://github.com/kmcgill88/admob_flutter/

**Comment by blasten** [comment] 2020-05-15 22:55
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1175

**Closed by blasten** 2020-05-15 22:55 UTC
Labels: bitcoin, plugin: admob, type: enhancement, type: missing-feature
