### ISSUE TITLE
[cloud_firestore] - Metadata property `isFromCache` returns false, when a hot restart is done 

### ISSUE THREAD

**Issue by kanily-tech** [FirebaseExtended/flutterfire#3035] opened 2020-07-27 14:40 UTC
In the flutter cloud firestore plugin, if persistent cache is on, the metadata property `isFromCache` should always return true if a document is loaded from cache. 

### What is actually happening

I am listening to a query for real time updates in my app as such
```
messagesRef = Firestore.instance.collection("test");
sub = messagesRef.orderBy("date").snapshots().listen((event) {
    event.documentChanges.forEach((DocumentChange change) {
      print("Document ${change.document.documentID} ${change.type}, metadata - isFromCache:${change.document.metadata.isFromCache}, hasPendingWrites:${change.document.metadata.hasPendingWrites}");

      if (change.type == DocumentChangeType.added) {
          /// do something
      }

    });
});
```

- `isFromCache` is `true` when the app is started first (assuming there are some documents in the "test" collection already, and they were loaded into the cache)
- `isFromCache` is `false` when the app is hot restarted

I am seeing this behaviour in cloud_firestore v0.13.7

**Comment by TahaTesser** [comment] 2020-07-27 15:17
```
Restarted application in 1,878ms.
D/ViewRootImpl@6188378[MainActivity](23898): ViewPostIme pointer 0
D/ViewRootImpl@6188378[MainActivity](23898): ViewPostIme pointer 1
I/flutter (23898): Document pasDyjH6DzBIswh2JYj4 DocumentChangeType.added, metadata - isFromCache:false, hasPendingWrites:false
Application finished.
```

<details> 
<summary>Code Sample</summary> 

```
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      floatingActionButton: FloatingActionButton(
          child: Icon(Icons.network_check),
          onPressed: () async {
            final messagesRef = Firestore.instance.collection("books");
            final sub =
                messagesRef.orderBy("title").snapshots().listen((event) {
              event.documentChanges.forEach((DocumentChange change) {
                print(
                    "Document ${change.document.documentID} ${change.type}, metadata - isFromCache:${change.document.metadata.isFromCache}, hasPendingWrites:${change.document.metadata.hasPendingWrites}");

                if (change.type == DocumentChangeType.added) {
                  /// do something
                }
              });
            });
          }),
    );
  }
}

``` 

</details> 

<details> 
<summary>flutter doctor -v</summary> 

```
[✓] Flutter (Channel dev, 1.21.0-1.0.pre, on Mac OS X 10.15.6 19G73, locale
    en-GB)
    • Flutter version 1.21.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision f25bd9c55c (13 days ago), 2020-07-14 20:26:01 -0400
    • Engine revision 99c2b3a245
    • Dart version 2.9.0 (build 2.9.0-21.0.dev 20bf2fcf56)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.6)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.6, Build version 11E708
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2

[✓] Connected device (4 available)
    • SM M305F (mobile) • 32003c30dc19668f • android-arm64  • Android 10 (API
      29)
    • macOS (desktop)   • macos            • darwin-x64     • Mac OS X 10.15.6
      19G73
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome
      84.0.4147.89

• No issues found!

```

</details>

**Comment by kanily-tech** [comment] 2020-07-27 15:45
Sample code to reproduce
```
import 'dart:async';

import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  Firestore.instance.settings(persistenceEnabled: true);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
        visualDensity: VisualDensity.adaptivePlatformDensity,
      ),
      home: FirestorePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class FirestorePage extends StatefulWidget {
  FirestorePage({Key key, this.title}) : super(key: key);

  final String title;

  @override
  _FirestorePageState createState() => _FirestorePageState();
}

class _FirestorePageState extends State<FirestorePage> {
  List<Message> messages = [];

  CollectionReference messagesRef;
  StreamSubscription<QuerySnapshot> sub;

  @override
  void initState() {
    super.initState();
    messagesRef = Firestore.instance.collection("messages");
    sub = messagesRef.orderBy("date").snapshots().listen((event) {

      event.documents.forEach((doc) {
        print("Event Snapshot doc ${doc.documentID}. isFromCache = ${doc.metadata.isFromCache}");
      });

      event.documentChanges.forEach((DocumentChange change) {
        print("Document ${change.document.documentID} ${change.type}, metadata - isFromCache:${change.document.metadata.isFromCache}, hasPendingWrites:${change.document.metadata.hasPendingWrites}");

        if (change.type == DocumentChangeType.added) {
          Message message = Message.from(change.document);
          setState(() {
            messages.add(message);
          });
        }

      });
    });
  }

  @override
  void dispose() {
    sub.cancel();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            Expanded(
              child: ListView.builder(itemBuilder: (BuildContext bc, int count) {
                if (count >= messages.length) {
                  return null;
                }
                return MessageWidget(messages[count]);
              }),
            ),
            FlatButton(
              onPressed: () async {
                addMessage("Test message");
              },
              child: Text("Add message"),
            ),
          ],
        ),
      ),
    );
  }

  void addMessage(String text) {
    messagesRef.add({
      "date": FieldValue.serverTimestamp(),
      "by": "test",
      "text": text,
    });
  }
}

class Message {
  final String id;
  final String by;
  final String text;
  Timestamp date;

  Message({
    @required this.id,
    @required this.by,
    @required this.text,
    @required this.date,
  });

  updateDate(Timestamp date) {
    this.date = date;
  }

  static Message from(DocumentSnapshot document) {
    return Message(
      id: document.documentID,
      by: document.data["by"],
      date: document.data["date"],
      text: document.data["text"],
    );
  }
}

class MessageWidget extends StatelessWidget {
  final Message message;

  MessageWidget(this.message);

  @override
  Widget build(BuildContext context) {
    return Padding(
      key: Key(message.id),
      padding: const EdgeInsets.all(8.0),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          Text(message.by, style: TextStyle(fontSize: 10)),
          Text(message.text),
          if (message.date != null)
            Text(
              message.date.toString(),
              textAlign: TextAlign.right,
              style: TextStyle(fontSize: 8),
            ),
        ],
      ),
    );
  }
}
```


Flutter Doctor
```
flutter doctor -v
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-IN)
    • Flutter version 1.17.5 at /Users/XXX/Library/flutter
    • Framework revision 8af6b2f038 (4 weeks ago), 2020-06-30 12:53:55 -0700
    • Engine revision ee76268252
    • Dart version 2.8.4


[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/XXX/Library/Android/sdk
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/XXX/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 37.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] IntelliJ IDEA Community Edition (version 2019.1.3)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8580

[✓] VS Code (version 1.35.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.2.0

[✓] Connected device (2 available)
    • xxx     • yyy                                 • android-arm • Android 6.0.1 (API 23)
    • xxx • yyy • ios         • iOS 13.5.1
```

**Comment by kroikie** [comment] 2020-07-28 15:55
@kanily-tech thanks for raising this. Could you try to repro this with the dev version of Firestore?
https://pub.dev/packages/cloud_firestore/versions/0.14.0-dev.1

**Comment by animeshjain** [comment] 2020-08-02 06:31
On v0.14.0-dev.1, the issue is fixed

**Comment by kanily-tech** [comment] 2020-08-02 06:33
On version 0.14.0-dev.1, the issue is fixed

**Comment by TahaTesser** [comment] 2020-08-04 12:31
Hi @kanily-tech 
given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you

**Closed by TahaTesser** 2020-08-04 12:31 UTC
Labels: Needs Attention, plugin: cloud_firestore, type: bug
