### ISSUE TITLE
[<firebase_asmob-0.9.3+2>] <Deprecated>

### ISSUE THREAD

**Issue by Motero69** [FirebaseExtended/flutterfire#2575] opened 2020-05-17 18:03 UTC
**Describe the bug**
I ran: flutter build appbundle
and in the process show me this:

C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_admob-0.9.3+2\android\src\main\java\io\flutter\plugins\firebaseadmob\AdRequestBuilderFactory.java uses or overrides a deprecated API

flutter Doctor:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel beta, v1.17.0, on Microsoft Windows [VersiÃ³n 10.0.18362.836], locale es-MX)
 
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[√] Chrome - develop for the web
[√] Android Studio (version 3.6)
[√] VS Code (version 1.45.0)
[√] Connected device (3 available)

• No issues found!

**Comment by TahaTesser** [comment] 2020-05-19 14:16
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/438

**Closed by TahaTesser** 2020-05-19 14:16 UTC
