### ISSUE TITLE
🐛 Firebase Auth too many refresh token request

### ISSUE THREAD

**Issue by cartwa** [FirebaseExtended/flutterfire#3574] opened 2020-09-17 15:09 UTC
Hi, 
Using firebase auth for the web we detected that too many requests for refreshing token will be executed in Chrome for some devices using Windows 10. but there is no issue on other platforms, and the request keep executing until quota exceeded.

How to fix it?

![Capture](https://user-images.githubusercontent.com/71450505/93489258-f6489900-f90f-11ea-9300-c4c52024f3db.PNG)

<details>
          <summary>flutter doctor -v</summary>

[✓] Flutter (Channel master, 1.22.0-10.0.pre.137, on Mac OS X 10.15.6 19G73, locale en-US)
    • Flutter version 1.22.0-10.0.pre.137 at /Applications/flutter
    • Framework revision 37e2013774 (6 days ago), 2020-09-11 04:05:02 -0400
    • Engine revision bdaac368f8
    • Dart version 2.10.0 (build 2.10.0-115.0.dev)

 
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/cartwatech/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ! Some Android licenses not accepted.  To resolve this, run: flutter doctor
      --android-licenses

[✓] Xcode - develop for iOS and macOS (Xcode 11.7)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.7, Build version 11E801a
    • CocoaPods version 1.10.0.beta.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.48.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.13.2

[✓] Connected device (3 available)
    • macOS (desktop)  • macos      • darwin-x64     • Mac OS X 10.15.6 19G73
    • Web Server (web) • web-server • web-javascript • Flutter Tools
    • Chrome (web)     • chrome     • web-javascript • Google Chrome 85.0.4183.102

! Doctor found issues in 1 category.

</details>

**Comment by TahaTesser** [comment] 2020-09-18 11:09
Hi @cartwa 
Can you please provide your `pubspec.yaml` and a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)
Thank you

**Comment by rebaz94** [comment] 2020-09-18 18:51
@TahaTesser 
Sorry for late response.
here is `pubspec.yaml`
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_storage: ^4.0.0
  cloud_firestore: ^0.14.0+2
  firebase_messaging: ^6.0.12
```
I don't know if thats help because when we test it, it work on chrome on `Windows` but on another computer with same chrome version in `Windwos` not work!(sometime work, but after refreshing page logged out)

[Here the code](https://github.com/rebaz94/auth-issue) and [app](https://test-repo-rebaz.firebaseapp.com/#/).
its same code I used for sign in using email and password. 

If thats not helping, I can provide you the real app which has the issue

Thanks

**Comment by TahaTesser** [comment] 2020-09-21 10:43
Hi @cartwa 
This doesn't reproduce your app or code repository on `Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)`

![image](https://user-images.githubusercontent.com/48603081/93758044-5a779f80-fc25-11ea-9a17-2f8c659c5cba.png)

**Comment by cartwa** [comment] 2020-09-21 11:59
I tested on this Windows now but it also has the same problem
```
Google Chrome is up to date
Version 85.0.4183.102 (Official Build) (64-bit)
```

![20200921_145133](https://user-images.githubusercontent.com/71450505/93763938-f0f29380-fc1a-11ea-8c92-4f8e45c3c4ec.jpg)

**Comment by deve-sh** [comment] 2020-10-06 10:41
This issue is usually caused by the **device clock being out of sync**, causing an endless loop of Firebase Auth trying to issue a new token using the existing refresh token, realizing that the time for the issued token is up, and then repeating the process.

**Comment by podolskyi** [comment] 2021-01-04 14:15
@TahaTesser @rebaz94 @cartwa

I have the same issues in my test Windows machine, and I noticed it's related to incorrect time on the system. The time on the machine is in future in a few hours.

**Comment by russellwheatley** [comment] 2022-01-21 13:37
Hey @podolskyi, thanks for the update. Is the fix set the time correctly?

**Comment by Salakar** [comment] 2022-01-28 10:30
This happens with the underlying Firebase SDKs if your host time is incorrect - not something FlutterFire has control over so I'm going to close this issue, thanks!

**Closed by Salakar** 2022-01-28 10:30 UTC
Labels: type: bug, plugin: auth
