### ISSUE TITLE
Clicking on one Push Notification on iOS opens multiple ones (FCM)

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#411] opened 2019-10-13 18:21 UTC
## Steps to Reproduce
Receive multiple push notifications. 
User taps to open one notification.
onResume triggers for all notifications received and redirects to a specific page for each one. 
Once the user tries to return (back button) from a notification page, instead of going to home page, it goes to the other notification page. 
The user has to click on the back button for each notification page to return to the home page. 

Is this the expected behavior? I thought that onResume should be triggered only for the notification that the user tapped and not for each notification received. Or is the way I am implementing this wrong?

## Logs
```
[✓] Flutter (Channel stable, v1.0.0, on Mac OS X 10.13.6 17G3025, locale pt-BR)
    • Flutter version 1.0.0 at /Users/isadora_maria/Downloads/flutter
    • Framework revision 5391447fae (3 months ago), 2018-11-29 19:41:26 -0800
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/isadora_maria/Library/Android/sdk
    • Android NDK at /Users/isadora_maria/Library/Android/sdk/ndk-bundle
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 29.0.1
    • Dart plugin version 173.4700
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b01)

[✓] Connected device (1 available)
    • Isadora • 7388be6c205ef382341a23c03c4a62834feb61ea • ios • iOS 12.1

• No issues found!
```

**Comment by kroikie** [comment] 2019-10-13 18:21
@IsaNascimento

The issue at https://github.com/flutter/flutter/issues/28580 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by kleinpetr** [comment] 2019-10-22 09:30
I have the same problem..

**Comment by iapicca** [comment] 2019-10-22 11:32
Hi @IsaNascimento
(and hello to @kmusham and @kleinpetr as well)
if you arer still experiencing this issue with the latest version of Flutter and [firebase_messaging](https://pub.dev/packages/firebase_messaging)?
please provide your `flutter doctor -v`?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

[1060](https://github.com/FirebaseExtended/flutterfire/issues/1060)

**Comment by kleinpetr** [comment] 2019-10-22 20:01
@iapicca Hey, Yes I am using the newest stable Flutter and No I don't using latest firebase_messaging plugin, because the backgroundMessage callback is absolutely bad and I dont understand why it is changed. In verison 5.1.4 is background message working fine as well.. here https://stackoverflow.com/questions/58394139/flutter-firebase-messaging-onbackgroundmessage-hell

**Comment by kleinpetr** [comment] 2019-10-22 21:11
@iapicca Is there some chance to fix it with using version 5.1.4. Thanks

**Comment by iapicca** [comment] 2019-11-20 14:24
Hi @kleinpetr 
I apologize for the delay,
is your experience with `backgroundMessage ` improved with `firebase_messaging: ^5.1.8`?
thank you

**Comment by iapicca** [comment] 2019-12-13 14:19
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-12-13 14:19 UTC
Labels: bug, severe: regression, waiting for customer response
