### ISSUE TITLE
Installing Flutter Firebase

### ISSUE THREAD

**Issue by arvobrendon** [FirebaseExtended/flutterfire#7022] opened 2021-09-20 02:19 UTC
## Bug report

**Describe the bug**
Fatal error: module
    'cloud_firestore' not found
    @import cloud_firestore;

1. https://pub.dev/packages/cloud_firestore

**Comment by markusaksli-nc** [comment] 2021-09-20 07:43
Hi @arvobrendon 
Have you added the dependency to your `pubspec.yaml`?
Usually you would import
```dart
import 'package:cloud_firestore/cloud_firestore.dart';
```

Thank you

**Comment by arvobrendon** [comment] 2021-09-20 08:23
thank you for your response 
i added them in main 

and i installed them by using terminal not any hope

**Comment by markusaksli-nc** [comment] 2021-09-20 09:01
So is the issue cleared or no?

**Comment by arvobrendon** [comment] 2021-09-20 09:07
not yet

**Comment by markusaksli-nc** [comment] 2021-09-21 05:45
Sorry your comment was a bit hard to understand. 

So are you sure the dependency is in your `pubspec.yaml` and you have run `flutter pub get`.

What is your output for `flutter pub deps -- --style=compact`?

**Comment by arvobrendon** [comment] 2021-09-21 16:24
I have a new error this time 
import 'package:firebase_core/firebase_core.dart';

and its error

**Comment by Ahmadre** [comment] 2021-09-21 17:06
@markusaksli-nc I have the same error since Flutter 2.5.0 while creating a new project with exact same config for my firebase apps :( I am working since years mit firestore in Flutter.

this is my output:
```sh
❯ flutter pub deps -- --style=compact
Dart SDK 2.14.2
Flutter SDK 2.5.1
museum 1.0.0+1

dependencies:
- cloud_firestore 2.5.3 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.3
- firebase_core 1.6.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_beacon 0.5.1 [flutter]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_tts 3.2.2 [flutter flutter_web_plugins]
- hive 2.0.4 [meta crypto]
- i18next 0.5.1 [flutter path]
- path_provider 2.0.5 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- provider 6.0.0 [collection flutter nested]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- integration_test 0.0.0 [flutter flutter_driver flutter_test path vm_service archive async boolean_selector characters charcode clock collection crypto fake_async file matcher meta source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math webdriver]

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.4.2 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_driver 0.0.0 [file flutter flutter_test fuchsia_remote_debug_protocol path meta vm_service webdriver archive async boolean_selector characters charcode clock collection crypto matcher platform process source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- fuchsia_remote_debug_protocol 0.0.0 [process vm_service file meta path platform]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- nested 1.0.0 [flutter]
- path 1.8.0
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- platform 3.0.0
- plugin_platform_interface 2.0.1 [meta]
- process 4.2.3 [file path platform]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- sync_http 0.3.0
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- vm_service 7.1.1
- webdriver 3.0.0 [archive matcher path stack_trace sync_http]
- win32 2.2.9 [ffi]
- xdg_directories 0.2.0 [meta path process]
```

**Comment by markusaksli-nc** [comment] 2021-09-22 10:46
Could you provide your `flutter run -v` logs?

**Comment by Ahmadre** [comment] 2021-09-22 12:36
> Could you try running these commands in your `ios` directory?
> 
> ```bash
> 
> rm -rf build
> 
> rm -rf Pods
> 
> rm -rf Podfile.lock
> 
> rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
> 
> pod cache clean --all
> 
> flutter clean
> 
> flutter pub get
> 
> pod repo update
> 
> pod install
> 
> ```
> 
> 
> 
> You can also try https://github.com/FirebaseExtended/flutterfire/issues/7034#issuecomment-924804711

I found this answer from you here in other issues, but didn't solve the issue.

The errir lies here in the newest Flutter version in Beta / Master Channels.

You've to delete your ios folder, switch to stable channel and recreate the ios folder.

It's not FlutterFire's issue here.

**Comment by kdupont-asfotec** [comment] 2021-09-22 12:40
> > Could you try running these commands in your `ios` directory?
> > ```shell
> > rm -rf build
> > 
> > rm -rf Pods
> > 
> > rm -rf Podfile.lock
> > 
> > rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
> > 
> > pod cache clean --all
> > 
> > flutter clean
> > 
> > flutter pub get
> > 
> > pod repo update
> > 
> > pod install
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can also try [#7034 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/7034#issuecomment-924804711)
> 
> I found this answer from you here in other issues, but didn't solve the issue.
> 
> The error lies here in the newest Flutter version in Beta / Master Channels.
> 
> You've to delete your ios folder, switch to stable channel and recreate the ios folder.
> 
> It's not FlutterFire's issue here.

I have the same problem too. I have already gone through all the forums to sort this out and nothing is working.
Is this really the solution to the problem?
How to create the new ios folder?

**Comment by Ahmadre** [comment] 2021-09-22 17:58
> > > Could you try running these commands in your `ios` directory?
> 
> > > ```shell
> 
> > > rm -rf build
> 
> > > 
> 
> > > rm -rf Pods
> 
> > > 
> 
> > > rm -rf Podfile.lock
> 
> > > 
> 
> > > rm -rf ~/.pub-cache/hosted/pub.dartlang.org/
> 
> > > 
> 
> > > pod cache clean --all
> 
> > > 
> 
> > > flutter clean
> 
> > > 
> 
> > > flutter pub get
> 
> > > 
> 
> > > pod repo update
> 
> > > 
> 
> > > pod install
> 
> > > ```
> 
> > > 
> 
> > > 
> 
> > >     
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >       
> 
> > >     
> 
> > > 
> 
> > >     
> 
> > >   
> 
> > > You can also try [#7034 (comment)](https://github.com/FirebaseExtended/flutterfire/issues/7034#issuecomment-924804711)
> 
> > 
> 
> > I found this answer from you here in other issues, but didn't solve the issue.
> 
> > 
> 
> > The error lies here in the newest Flutter version in Beta / Master Channels.
> 
> > 
> 
> > You've to delete your ios folder, switch to stable channel and recreate the ios folder.
> 
> > 
> 
> > It's not FlutterFire's issue here.
> 
> 
> 
> I have the same problem too. I have already gone through all the forums to sort this out and nothing is working.
> 
> Is this really the solution to the problem?
> 
> How to create the new ios folder?

just do: "flutter create ." but be aware: You've already set your org and project-name, so do that also with --project-name and --org

**Comment by markusaksli-nc** [comment] 2021-09-23 06:37
If this is just a project config issue I'm going to close it as not actionable for us

**Comment by kdupont-asfotec** [comment] 2021-09-23 08:46
Nothing works.
- I just removed the ios folder, then re-create it.
Always the same error.

- I recreated my project with my org and project-name.
Again the error.

- I just created a new empty flutter project adding only Firebase.
Again the same error.

I am on mac M1.

**Comment by markusaksli-nc** [comment] 2021-09-23 08:51
> And I add that if I do "flutter run", the application launches perfectly with firebase.
The error only appears when I build on XCode

Just read this. The issue was being caused by the fact that just building in Xcode does not run `pod install` to add the firebase native dependencies. Xcode will then throw an error for any code that uses them. If you wish to specifically build from xcode for some reason then you need to run `flutter pub get` and `pod install` first

**Closed by markusaksli-nc** 2021-09-23 08:51 UTC
Labels: type: bug, blocked: customer-response, resolution: solution-provided

**Comment by kdupont-asfotec** [comment] 2021-09-23 08:57
Thank you for your reply.
However it does not work either.
I have to go through Xcode because I have to publish the application as soon as possible. Is there another solution for push the application on the AppStore without going through Xcode?

**Comment by markusaksli-nc** [comment] 2021-09-23 09:06
What do you mean? For publishing you should not be using Xcode or `flutter run` as these will generate a debug build. You should run `flutter build ipa` to generate an archived release build and just `open build/ios/archive/Runner.xcarchive` to distribute it

**Comment by kdupont-asfotec** [comment] 2021-09-23 09:08
Yes sorry, I normally used xcode to publish my apps on the AppStore.
I tried with the ipa command.
I find another error which may be the source of my problem.
```
None of the architectures in ARCHS (arm64) are valid. Consider setting ARCHS to
     $ (ARCHS_STANDARD) or updating it to include at least one value from VALID_ARCHS (arm64, arm64e, armv7,
     armv7s) which is not in EXCLUDED_ARCHS (arm64). (in target 'Runner' from project 'Runner')
```

**Comment by kdupont-asfotec** [comment] 2021-09-23 09:19
It's ok on my side now. I managed to publish.
Thanks for the explanations of xcode which does not run "pod install".

I understood 👍🙏
