### ISSUE TITLE
🐛 [firebase_auth] Incompatible with latest flutter_localizations master channel.

### ISSUE THREAD

**Issue by ekasetiawans** [FirebaseExtended/flutterfire#4342] opened 2020-12-07 01:38 UTC
Reported by @Macacoazul01 on flutter repo. flutter/flutter#71801

I've tried to use flutter localizations package on my app to change the showdatepicker widget language, but when i add it to my pub there is a conflict with firebase auth:
```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.3
```
```
[assets_apps] flutter pub get
Running "flutter pub get" in assets_apps...                     
Because firebase_auth >=0.18.4 depends on firebase_auth_web ^0.3.2+2 which depends on intl ^0.16.1, firebase_auth >=0.18.4 requires intl ^0.16.1.

And because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, firebase_auth >=0.18.4 is incompatible with flutter_localizations from sdk.

So, because assets_apps depends on both flutter_localizations any from sdk and firebase_auth ^0.18.4, version solving failed.
pub get failed (1; So, because assets_apps depends on both flutter_localizations any from sdk and firebase_auth ^0.18.4, version solving failed.)
exit code 1
```
My flutter doctor:
```
[√] Flutter (Channel master, 1.25.0-5.0.pre.57, on Microsoft Windows [versÃ£o 10.0.19042.662], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.51.1)
[√] Connected device (2 available)

• No issues found!
```
Is there any way of changing the lang of the datepicker to pt-br that doesn't use the flutter_localizations?

**Comment by markusaksli-nc** [comment] 2020-12-07 12:49
Reproducible on the latest master `1.25.0-5.0.pre.91`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.25.0-5.0.pre.91, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.25.0-5.0.pre.91 at C:\Development\flutter_master
    • Framework revision 7dade22f25 (20 hours ago), 2020-12-06 21:34:04 +0530
    • Engine revision 6491c7518f
    • Dart version 2.12.0 (build 2.12.0-120.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.5981.155
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (5 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```
</details>

**Comment by Macacoazul01** [comment] 2020-12-07 13:54
They've told me to reopen the issue here on flutterfire, but seems it's already made by the team.
Like @markusaksli-nc said, the error happens in the latest master too.

**Comment by rtr-dnd** [comment] 2020-12-07 14:26
Does anyone know a working version pair of firebase_auth and flutter_localizations?
I'm currently having this issue and don't know which version I should roll back to.

**Comment by visit1985** [comment] 2020-12-08 09:19
beta (1.24.0-10.2.pre) works with latest firebase_auth.

**Comment by rtr-dnd** [comment] 2020-12-08 11:33
I just downgraded Flutter to v1.22.4 and everything started to work again!

**Comment by Macacoazul01** [comment] 2020-12-15 17:38
The problem still exists on the latest firebase_auth package (0.18.4+1)

```
because firebase_auth >=0.18.4+1 depends on firebase_auth_web ^0.3.2+3 which depends on intl ^0.16.1, firebase_auth >=0.18.4+1 requires intl ^0.16.1.

And because every version of flutter_localizations from sdk depends on intl 0.17.0-nullsafety.2, firebase_auth >=0.18.4+1 is incompatible with flutter_localizations from sdk.

So, because assets_apps depends on both flutter_localizations any from sdk and firebase_auth ^0.18.4+1, version solving failed.
pub get failed (1; So, because assets_apps depends on both flutter_localizations any from sdk and firebase_auth ^0.18.4+1, version solving failed.)
exit code 1
```

**Comment by Macacoazul01** [comment] 2020-12-15 17:44
updated flutter doctor

Doctor summary (to see all details, run flutter doctor -v):
[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.52.0)
[√] Connected device (2 available)

• No issues found!

**Comment by reiji012** [comment] 2020-12-17 17:47
I solved it with this.

```bash
 flutter downgrade 1.24.0-10.2.pre 
```

**Comment by yusufnadar** [comment] 2020-12-19 13:37
> ```shell
> flutter downgrade 1.24.0-10.2.pre
> ```

How did you do that? ı have an error like that "There is no previously recorded version for channel "dev"." Can you help me?

**Comment by reiji012** [comment] 2020-12-19 17:00
@yusufnadar 

I'm using beta channel.

try this

>$ flutter channel beta

and 
> $ flutter downgrade 1.24.0-10.2.pre

**Comment by arnaudelub** [comment] 2020-12-21 11:19
Same here, downgrading  1.24.0-10.2.pre seems to be the only solution right now as firebase_auth depends on firebase_auth_web which depends on intl: ^0.16.1

**Comment by Macacoazul01** [comment] 2020-12-21 14:18
Downgrading is an option, but isn't the ideal. The localizations package is fundamental for developing apps focused on markets that don't have English as their native language, also firebase as an easy way of letting your app be developed. Both of them are developed by the google team and heavily encouraged to be used, so it's a little controversial that they aren't compatible.

**Comment by devj3ns** [comment] 2020-12-21 16:31
I am having the same issue. I also downgraded to version 1.24.0-10.2.pre

**Comment by visit1985** [comment] 2020-12-21 23:55
For now you can simply add the following to your `pubspec.yaml` if you need to stay on `dev` channel and do not really use `firebase_auth_web` in a web app:

```
dependency_overrides:
  intl: ^0.17.0-nullsafety.2
````

**Comment by Macacoazul01** [comment] 2020-12-22 02:03
I'm currently developing a web site using flutter, so removing auth web isn't an option.

**Comment by devj3ns** [comment] 2020-12-22 10:11
> For now you can simply add the following to your `pubspec.yaml` if you need to stay on `dev` channel and do not really use `firebase_auth_web` in a web app:
> 
> ```
> dependency_overrides:
>   intl: ^0.17.0-nullsafety.2
> ```

This worked for me. Thanks a lot!

@Macacoazul01 Just add these two lines to your pubspec.yaml file. You do not need to remove firebase_auth.

**Comment by Macacoazul01** [comment] 2020-12-22 22:18
Haven't tried all of my firebase functions with this dependency override, but at least the pub get now works (and the site debug).

I'm gonna test a little more to see if this fully works for me, but thanks @visit1985 and @devj3ns for your help.

**Comment by yusufnadar** [comment] 2020-12-23 16:48
> intl: ^0.17.0-nullsafety.2

Dude when ı do that ı have an error, could you help me? Where did you put this dependency?

**Comment by bringbackthedog** [comment] 2020-12-23 19:41
Same issue. The combination works on `stable` channel only. Really frustrating since I'm trying to develop for web too, and web doesn't seem to work on `stable`

**Comment by Macacoazul01** [comment] 2020-12-24 15:39
@yusufnadar my pubspec:
```

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  google_sign_in: ^4.5.6
  firebase_analytics: ^6.2.0
  google_tag_manager: ^0.0.3
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
```

**Comment by ganeshchenniah** [comment] 2021-01-20 17:51
any update on this ?

**Comment by Macacoazul01** [comment] 2021-01-20 22:52
@ganeshchenniah i don't think so. The firebase team didn't close this issue or updated the package to solve it, so the "solution" now is to include the dependency override.

**Comment by Macacoazul01** [comment] 2021-01-20 22:55
they are currently migrating all of the packages to nullsafety, so it will be solved

**Comment by ganeshchenniah** [comment] 2021-01-21 17:16
Even after including dev_dependencies:
  intl: 0.17.0-nullsafety.2 i m still getting error . 

I have firebase_auth , flutter_localizations libraries

**Comment by ganeshchenniah** [comment] 2021-01-21 17:17
depends on dependency_overrides from unknown source "intl", version solving failed.

**Comment by seidlmatus** [comment] 2021-02-09 09:17
Hi folks, any update on this ? @Macacoazul01  is it ok using your solution ? because I got warring "Warning: You are using these overridden dependencies:
! intl 0.17.0-nullsafety.2"

**Comment by Macacoazul01** [comment] 2021-02-09 13:16
@seidlmatus using the override dependency solves the problem (but you will have to live with this warning). I think that changing to the null safety version of firebase_auth package also solves it, but if you use any other firebase package that wasn't migrated to null safety yet (like firebase database), the dependency problem will happen again.

**Comment by Macacoazul01** [comment] 2021-02-11 22:41
@markusaksli-nc i think this issue can be closed as it was solved on the null safety version of firebase_auth

**Comment by markusaksli-nc** [comment] 2021-02-12 10:03
Thanks for reminding me. Although the null safety versions aren't fully complete yet I think this can already be closed as solved since the nullsafety version of auth is already compatible with the latest intl.

**Closed by markusaksli-nc** 2021-02-12 10:03 UTC
Labels: plugin: auth, type: bug
