### ISSUE TITLE
🐛 [firebase_ml_vision] Failed to load 'firebase_ml_vision' podspec

### ISSUE THREAD

**Issue by binaris-no** [FirebaseExtended/flutterfire#4627] opened 2021-01-11 21:58 UTC
**pod update** fails with:
```
...
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] Failed to load 'firebase_ml_vision' podspec:
[!] Invalid `firebase_ml_vision.podspec` file: [!] Unsupported version requirements. [nil] is not valid..

 #  from /Users/foo/app/ios/.symlinks/plugins/firebase_ml_vision/ios/firebase_ml_vision.podspec:37
 #  -------------------------------------------
 #    s.dependency 'firebase_core'
 >    s.dependency 'Firebase/MLVision', firebase_sdk_version
 #    s.ios.deployment_target = '10.0'
 #  -------------------------------------------
```

---
firebase_ml_vision 0.10.0

[✓] Flutter (Channel beta, 1.25.0-8.2.pre, on macOS 11.1 20C69 darwin-x64, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)

**Comment by arhamcode** [comment] 2021-01-12 07:44
same error here!

**Comment by juzo** [comment] 2021-01-12 08:33
Try adding

```
# Override Firebase SDK Version
$FirebaseSDKVersion = '6.33.0'
```

to the top of your `Podfile`.

Also you might need to include 

`firebase_core: ^0.4.5`

into your `pubspec.yaml`

**Comment by binaris-no** [comment] 2021-01-12 08:49
Thanks @juzo, I'll try it out later today.
Is that an official guidance or just a temporary manual workaround?

**Comment by juzo** [comment] 2021-01-12 08:52
The latter.
This was my urgent fix for one of my app that has an MLVision package...

**Comment by markusaksli-nc** [comment] 2021-01-12 13:50
Hi @binaris-no 
The root cause here is likely the same as https://github.com/FirebaseExtended/flutterfire/issues/4625 so I'm going to close this as a duplicate. Please feel free to comment any additional info or workarounds there.
Thank you

**Closed by markusaksli-nc** 2021-01-12 13:50 UTC
Labels: Needs Attention, type: bug
