### ISSUE TITLE
uses or overrides a deprecated API

### ISSUE THREAD

**Issue by hasanm08** [FirebaseExtended/flutterfire#7095] opened 2021-09-29 08:36 UTC
## Bug report

**Describe the bug**
```
\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_core-1.6.0\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
```

### Steps to reproduce

build apk using flutter 2.5.1

**Comment by hasanm08** [comment] 2021-09-29 08:42
other libraries also have this problem
```
Note: ...\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-8.3.2\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: ...\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_analytics-8.3.2\android\src\main\java\io\flutter\plugins\firebaseanalytics\FirebaseAnalyticsPlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note:...\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\firebase_crashlytics-2.2.1\android\src\main\java\io\flutter\plugins\firebase\crashlytics\FlutterFirebaseCrashlyticsPlugin.java uses or overrides a deprecated API.
```

**Comment by markusaksli-nc** [comment] 2021-09-29 08:47
Hi @hasanm08 
This is a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/3876
Closing it as such.
Thank you

**Closed by markusaksli-nc** 2021-09-29 08:47 UTC
Labels: type: bug, Needs Attention, in triage
