### ISSUE TITLE
Firebase Message can't receive notification background from firebase console IOS 13

### ISSUE THREAD

**Issue by siwakornmook** [FirebaseExtended/flutterfire#1812] opened 2020-01-14 08:40 UTC
When I send notification background from firebase console Xcode show error 

Can't end BackgroundTask: no background task exists with identifier 11 (0xb), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug. 

How to solve ? .

**Now Android foreground and background message work 
IOS foreground work and background not work**

flutter doctor -v

`[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-TH)
    • Flutter version 1.12.13+hotfix.5 at /Users/siwakorn/flutter
    • Framework revision 27321ebbad (5 weeks ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/siwakorn/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • ANDROID_HOME = /Users/siwakorn/Library/Android/sdk
    • ANDROID_SDK_ROOT = /Users/siwakorn/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.41.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • USER’s iPhone • c5c49e24e7122e94c4373ee3ee07be282caf1243 • ios • iOS 13.3

• No issues found!
`

**Comment by pdivita** [comment] 2020-01-14 09:20
Possible duplicate of #1041 and #1799

**Comment by iapicca** [comment] 2020-01-21 08:01
Hi @siwakornmook 
I see there's an open [issue ](https://github.com/FirebaseExtended/flutterfire/issues/1590)addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Comment by dazednconfusing** [comment] 2020-01-26 23:48
@iapicca The issue you linked here as well only applies to android

**Comment by shingsoso** [comment] 2020-02-18 11:22
I have the exact problem with you . Do anyone know what’s going on ...

**Comment by iapicca** [comment] 2020-02-20 12:17
Hi @siwakornmook 
as @pdivita pointed out there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1041) addressing the case you described.
Please follow up on that issue,
I'm closing the current one as duplicate.
If you disagree please write in the comments
and I will reopen it.
Thank you

**Closed by iapicca** 2020-02-20 12:17 UTC
Labels: bug
