### ISSUE TITLE
🐛 [firebase_messaging] FCMService: Invalid notification content

### ISSUE THREAD

**Issue by benyamin218118** [FirebaseExtended/flutterfire#4915] opened 2021-02-02 12:08 UTC
## Bug report

i am getting this error about FCM after importing wakelock library in my flutter project:

D/FCMService: FCM received
D/FCMService: Invalid notification content
but if i remove the wakelock plugin from my dependencies list , it works well as it was working before!
what's wrong?
### Steps to reproduce

1. only add the wakelock library into a your project dependencies when you have firebase_messaging too
2. run and send a notification to there
3. then you can see the logs

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.19041.630], locale en-US)
``` 
</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
- autocomplete_textfield 1.7.3 [flutter]
- awesome_notifications 0.0.5+4 [flutter platform intl]
- cached_network_image 2.5.0 [flutter flutter_cache_manager octo_image]
- cupertino_icons 1.0.0
- dio 3.0.10 [http_parser path]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_audio_manager 0.2.3 [flutter]
- flutter_incall 1.0.0 [flutter]
- flutter_launcher_icons 0.8.0 [image args yaml]
- flutter_ringtone_player 2.0.0 [flutter]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- flutter_typeahead 1.9.1 [flutter flutter_keyboard_visibility]
- flutter_webrtc 0.2.8 [flutter]
- fluttertoast 7.1.6 [flutter flutter_web_plugins]
- image_picker 0.6.7+17 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- numberpicker 1.3.0 [flutter infinite_listview]
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- persian_datetime_picker 1.0.7 [flutter shamsi_date]
- retrofit 1.3.4+1 [meta dio]
- sentry_flutter 4.0.1 [flutter flutter_web_plugins sentry package_info]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- smooth_page_indicator 0.2.0 [flutter]
- socket_io_client 0.9.12 [logging socket_io_common]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- tinode 0.0.1 [flutter]
- tus_client 0.0.4 [flutter http path]

dev dependencies:
- build_runner 1.10.11 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- retrofit_generator 1.4.1 [dio source_gen built_collection code_builder tuple retrofit analyzer dart_style build]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.1 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.6.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.5 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.1 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.5 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- dart_style 1.3.10 [analyzer args path source_span]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_keyboard_visibility 4.0.2 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 1.0.1 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- infinite_listview 1.0.1+1 [flutter]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.1.1
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- package_info 0.4.3+2 [flutter]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.7 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.5 [matcher meta]
- rxdart 0.25.0
- sentry 4.0.3 [http meta stack_trace uuid]
- shamsi_date 0.8.1 [flutter]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- socket_io_common 0.9.2 [logging]
- source_gen 0.9.10+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+3 [json_annotation]
- tuple 1.0.3 [quiver]
- typed_data 1.3.0-nullsafety.3 [collection]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]


```

</details>

---

**Comment by Ehesp** [comment] 2021-02-02 12:11
Would it not make more sense to raise this against the Wakelock library? We're not doing any side effects in this library so looks as though the issue isn't with us.

**Comment by benyamin218118** [comment] 2021-02-02 12:25
i have asked them and i have read their library code.
it does not seem like that

**Comment by markusaksli-nc** [comment] 2021-02-03 11:22
@benyamin218118 Did they give a reason for why this is coming from flutterfire? If you opened an issue in the maintainers repository could you provide a link to it?

**Comment by benyamin218118** [comment] 2021-02-04 06:18
they didn't sayd any thing about it is coming from flutter fire.
https://github.com/creativecreatorormaybenot/wakelock/issues/91
i just sayed maybe it is related to flutterfire , because there is a log like this : 
D/FCMService: FCM received
D/FCMService: Invalid notification content
what this mean?

**Comment by markusaksli-nc** [comment] 2021-02-04 09:07
There have been two other issues about this before but in both cases, it seemed to be resolved by just using the latest version of `firebase_messaging` instead of `7.0.3`.

Could you try upgrading to `firebase_messaging: ^8.0.0-dev.14` or `firebase_messaging: ^9.0.0-1.0.nullsafety.0`?

**Comment by benyamin218118** [comment] 2021-02-06 06:02
At that time I needed to turn on the Lock screen on new notification Received, i solved that problem , i dont want to use wakelock package any more , but i will upgrade the version and let you guys know if it is fixed.
tnx for answering;

**Comment by markusaksli-nc** [comment] 2021-02-08 10:18
Since wakelock was the original cause I'm going to optimistically close this as solved for now, let me know if the issue persists.

**Closed by markusaksli-nc** 2021-02-08 10:18 UTC
Labels: Needs Attention, impact: deprecated-version, type: bug
