### ISSUE TITLE
🐛 [firebase_auth] Sign in with Google only works on iOS but not on Android

### ISSUE THREAD

**Issue by blck-shp** [FirebaseExtended/flutterfire#5932] opened 2021-04-26 07:30 UTC
## Bug report

**Describe the bug**

I have a Flutter project that uses Sign in with Google plugin for making the users log in using their accounts (both Android and iOS). The issue is whenever the plugin generates a token from an Android device and it's being validated to our backend, it would return token client-id mismatch. I'm using this (https://www.googleapis.com/oauth2/v1/tokeninfo?id_token=) url to verify the validity of the tokens and one thing that I have noticed on an Android generated token is that the values of **issued_to** and **audience** are different. As I checked on the credentials of the Firebase project, the OAuth client id being used on **audience** was from Web Application (I'm only developing for Android and iOS devices). With that, whenever the token generated from an Android device is being sent to our backend (using this: https://github.com/google/google-id-token), it would return a token client-id mismatch. Both tokens generated were verified tokens. 

I have already followed the steps on the configuration of this plugin from adding the google-services.json and GoogleService-Info.plist files on the Flutter project to filling up the necessary configurations on Firebase console. I have tried recreating the Firebase project like three times just to make sure but I'd still get the same error.

## Additional context

**iOS token:** 

```
{
  "issued_to": "60204403274-jvgooi7...",
  "audience": "60204403274-jvgooi7...",
  "user_id": "1003...",
  "expires_in": 3583,
  "email": "dean...",
  "email_verified": true,
  "issuer": "https://accounts.google.com",
  "issued_at": 1619....,
  "nonce": "IF4Y3..."
}
```

**Android:** 

```
{
  "issued_to": "60204403274-uqoa6ss...",
  "audience": "60204403274-7uh25jv2...",
  "user_id": "10036...",
  "expires_in": 1592,
  "email": "dean...",
  "email_verified": true,
  "issuer": "https://accounts.google.com",
  "issued_at": 1619...
}

```
![attachment](https://user-images.githubusercontent.com/65164446/116045064-3a6cfa80-a6a4-11eb-862d-96c653cce6e9.png)

**Comment by markusaksli-nc** [comment] 2021-04-27 15:41
Hi @blck-shp 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Could you create a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) or steps to demonstrate the difference?
Thank you

**Comment by blck-shp** [comment] 2021-04-28 02:35
Hi @markusaksli-nc 

```
flutter doctor -v 

[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale
    en-US)
    • Flutter version 2.0.3 at /Users/kk38/Downloads/flutter
    • Framework revision 4d7946a68d (6 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/kk38/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • 6566D6D8-44CA-41DC-B247-0B4FB6799BF7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)      • chrome                               • web-javascript
      • Google Chrome 90.0.4430.93
```

```
flutter pub deps -- --style=compact

Dart SDK 2.12.2
Flutter SDK 2.0.3
facesbyplaces 1.0.0+1

dependencies:
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- auth_buttons 1.0.0 [flutter]
- better_player 0.0.63 [flutter cupertino_icons wakelock pedantic meta flutter_widget_from_html_core visibility_detector path_provider collection]
- cached_network_image 3.0.0-nullsafety [flutter flutter_cache_manager octo_image]
- carousel_slider 4.0.0-nullsafety.0 [flutter]
- clipboard 0.1.3 [flutter]
- date_time_format 2.0.1
- date_time_picker 2.0.0 [flutter intl]
- dio 4.0.0 [http_parser path]
- firebase_auth 1.0.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter_barcode_scanner 2.0.0-nullsafety.0 [flutter flutter_plugin_android_lifecycle]
- flutter_bloc 7.0.0 [flutter bloc provider]
- flutter_branch_sdk 3.0.0 [flutter flutter_web_plugins plugin_platform_interface js]
- flutter_inappwebview 5.3.0 [flutter]
- flutter_login_facebook 1.0.1 [flutter list_ext]
- flutter_spinkit 5.0.0 [flutter]
- flutter_staggered_grid_view 0.4.0-nullsafety.3 [flutter]
- flutter_svg 0.21.0+1 [flutter meta path_drawing vector_math xml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- fluttericon 2.0.0 [flutter]
- font_awesome_flutter 9.0.0 [flutter]
- geocoding 2.0.0 [flutter geocoding_platform_interface]
- geolocator 7.0.1 [flutter geolocator_platform_interface geolocator_web]
- giffy_dialog 1.8.0 [flutter flare_flutter]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- image_picker 0.7.3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- images_picker 1.0.0 [flutter]
- intl_phone_number_input 0.7.0+1 [flutter meta libphonenumber_plugin equatable collection]
- keyboard_attachable 2.0.0 [flutter flutter_keyboard_visibility]
- loader_overlay 2.0.0 [flutter]
- location 4.1.1 [flutter location_platform_interface location_web meta]
- material_design_icons_flutter 5.0.5955-rc.1 [flutter]
- mime 1.0.0
- modal_bottom_sheet 2.0.0 [flutter]
- pinput 1.2.0 [flutter]
- qr_flutter 4.0.0 [flutter qr]
- responsive_framework 0.1.0 [flutter collection]
- share 2.0.1 [meta mime flutter]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.0.0 [flutter meta]
- stripe_payment 1.0.11 [flutter]
- timeago 3.0.2
- we_slide 2.0.1 [flutter]

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.5.0 [collection]
- bloc 7.0.0 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.0 [collection typed_data]
- csslib 0.17.0 [source_span]
- cupertino_icons 1.0.2
- equatable 2.0.0 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flare_dart 2.3.4
- flare_flutter 2.0.6 [flutter flare_dart meta]
- flutter_blurhash 0.5.4-nullsafety.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.0-nullsafety.2 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_keyboard_visibility 5.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_plugin_android_lifecycle 2.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flutter_widget_from_html_core 0.6.0-rc.2021031201 [flutter html]
- geocoding_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- geolocator_platform_interface 2.0.0 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.2 [flutter flutter_web_plugins geolocator_platform_interface]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.15.0 [csslib source_span]
- http 0.13.1 [http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.3
- libphonenumber 2.0.0 [flutter meta]
- libphonenumber_platform_interface 0.3.1 [flutter plugin_platform_interface]
- libphonenumber_plugin 0.2.3 [flutter flutter_web_plugins libphonenumber_platform_interface libphonenumber_web libphonenumber]
- libphonenumber_web 0.2.0+1 [flutter flutter_web_plugins js libphonenumber_platform_interface]
- list_ext 1.0.2 [quiver collection]
- location_platform_interface 2.1.0 [flutter meta plugin_platform_interface]
- location_web 3.0.0 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0-nullsafety.1 [flutter flutter_blurhash]
- path 1.8.0
- path_drawing 0.5.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0 [vector_math meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.0 [file path platform]
- provider 5.0.0 [collection flutter nested]
- qr 2.0.0 [meta]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- uuid 3.0.2 [crypto]
- vector_math 2.1.0
- visibility_detector 0.2.0-nullsafety.1 [flutter]
- wakelock 0.4.0 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web]
- wakelock_macos 0.1.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.0 [flutter meta]
- wakelock_web 0.2.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]
```


---


**Steps:**

Once the user has done signing in, the Google Sign In plugin generates a token. This token will then be sent to our backend for verification. 

To verify that these tokens are valid, I’m using this link (https://www.googleapis.com/oauth2/v1/tokeninfo?id_token=) and so far both of the tokens generated from iOS and Android devices were valid, as shown on _**Additional context**_ above. However, whenever the token from an Android device is being verified on the backend, it would return: 

`{status: Cannot validate: Token client-id mismatch}`

Using the link above, the values on **issued_to** and **audience** on Android are different unlike from iOS.
On an iOS generated token, it’s using the OAuth client id of iOS for both **issued_to** and **audience** but for Android, the **issued_to** is using the client id of Android but the **audience** is using the client id Web Application. 

iOS:

```
{
  "issued_to": "60204403274-jvgooi7...",
  "audience": "60204403274-jvgooi7...",
  "user_id": “100368...",
  "expires_in": 3505,
  "email": “deanv...",
  "email_verified": true,
  "issuer": "https://accounts.google.com",
  "issued_at": 16195...,
  "nonce": “zd5xn33..."
}
```

Android:

```
{
  "issued_to": "60204403274-uqoa6ss...",
  "audience": "60204403274-7uh25jv2...",
  "user_id": "100368800442506365560",
  "expires_in": 3562,
  "email": "deanver.freolo@kodakollectiv.com",
  "email_verified": true,
  "issuer": "https://accounts.google.com",
  "issued_at": 1619575906
}

```


**Firebase credentials:**

![oauth](https://user-images.githubusercontent.com/65164446/116337544-dca7f200-a80c-11eb-905c-92962acfb38c.png)

**Comment by blck-shp** [comment] 2021-04-28 02:41
Hi @markusaksli-nc 

```
flutter doctor -v 

[✓] Flutter (Channel stable, 2.0.3, on Mac OS X 10.15.6 19G73 darwin-x64, locale
    en-US)
    • Flutter version 2.0.3 at /Users/kk38/Downloads/flutter
    • Framework revision 4d7946a68d (6 weeks ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Users/kk38/Library/Android/sdk
    • Platform android-30, build-tools 30.0.1
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 54.1.1
    • Dart plugin version 201.9335
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (2 available)
    • iPhone 8 (mobile) • 6566D6D8-44CA-41DC-B247-0B4FB6799BF7 • ios
      • com.apple.CoreSimulator.SimRuntime.iOS-14-4 (simulator)
    • Chrome (web)      • chrome                               • web-javascript
      • Google Chrome 90.0.4430.93
```

```
flutter pub deps -- --style=compact

Dart SDK 2.12.2
Flutter SDK 2.0.3
facesbyplaces 1.0.0+1

dependencies:
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- auth_buttons 1.0.0 [flutter]
- better_player 0.0.63 [flutter cupertino_icons wakelock pedantic meta flutter_widget_from_html_core visibility_detector path_provider collection]
- cached_network_image 3.0.0-nullsafety [flutter flutter_cache_manager octo_image]
- carousel_slider 4.0.0-nullsafety.0 [flutter]
- clipboard 0.1.3 [flutter]
- date_time_format 2.0.1
- date_time_picker 2.0.0 [flutter intl]
- dio 4.0.0 [http_parser path]
- firebase_auth 1.0.3 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.0.3 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.1.1 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter_barcode_scanner 2.0.0-nullsafety.0 [flutter flutter_plugin_android_lifecycle]
- flutter_bloc 7.0.0 [flutter bloc provider]
- flutter_branch_sdk 3.0.0 [flutter flutter_web_plugins plugin_platform_interface js]
- flutter_inappwebview 5.3.0 [flutter]
- flutter_login_facebook 1.0.1 [flutter list_ext]
- flutter_spinkit 5.0.0 [flutter]
- flutter_staggered_grid_view 0.4.0-nullsafety.3 [flutter]
- flutter_svg 0.21.0+1 [flutter meta path_drawing vector_math xml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- fluttericon 2.0.0 [flutter]
- font_awesome_flutter 9.0.0 [flutter]
- geocoding 2.0.0 [flutter geocoding_platform_interface]
- geolocator 7.0.1 [flutter geolocator_platform_interface geolocator_web]
- giffy_dialog 1.8.0 [flutter flare_flutter]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- image_picker 0.7.3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- images_picker 1.0.0 [flutter]
- intl_phone_number_input 0.7.0+1 [flutter meta libphonenumber_plugin equatable collection]
- keyboard_attachable 2.0.0 [flutter flutter_keyboard_visibility]
- loader_overlay 2.0.0 [flutter]
- location 4.1.1 [flutter location_platform_interface location_web meta]
- material_design_icons_flutter 5.0.5955-rc.1 [flutter]
- mime 1.0.0
- modal_bottom_sheet 2.0.0 [flutter]
- pinput 1.2.0 [flutter]
- qr_flutter 4.0.0 [flutter qr]
- responsive_framework 0.1.0 [flutter collection]
- share 2.0.1 [meta mime flutter]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.0.0 [flutter meta]
- stripe_payment 1.0.11 [flutter]
- timeago 3.0.2
- we_slide 2.0.1 [flutter]

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.5.0 [collection]
- bloc 7.0.0 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.0 [collection typed_data]
- csslib 0.17.0 [source_span]
- cupertino_icons 1.0.2
- equatable 2.0.0 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.5 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.1.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.4 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flare_dart 2.3.4
- flare_flutter 2.0.6 [flutter flare_dart meta]
- flutter_blurhash 0.5.4-nullsafety.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.0-nullsafety.2 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_keyboard_visibility 5.0.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_plugin_android_lifecycle 2.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- flutter_widget_from_html_core 0.6.0-rc.2021031201 [flutter html]
- geocoding_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- geolocator_platform_interface 2.0.0 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.2 [flutter flutter_web_plugins geolocator_platform_interface]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.15.0 [csslib source_span]
- http 0.13.1 [http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.3
- libphonenumber 2.0.0 [flutter meta]
- libphonenumber_platform_interface 0.3.1 [flutter plugin_platform_interface]
- libphonenumber_plugin 0.2.3 [flutter flutter_web_plugins libphonenumber_platform_interface libphonenumber_web libphonenumber]
- libphonenumber_web 0.2.0+1 [flutter flutter_web_plugins js libphonenumber_platform_interface]
- list_ext 1.0.2 [quiver collection]
- location_platform_interface 2.1.0 [flutter meta plugin_platform_interface]
- location_web 3.0.0 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0-nullsafety.1 [flutter flutter_blurhash]
- path 1.8.0
- path_drawing 0.5.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0 [vector_math meta]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.0 [file path platform]
- provider 5.0.0 [collection flutter nested]
- qr 2.0.0 [meta]
- quiver 3.0.1 [matcher]
- rxdart 0.26.0
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- uuid 3.0.2 [crypto]
- vector_math 2.1.0
- visibility_detector 0.2.0-nullsafety.1 [flutter]
- wakelock 0.4.0 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web]
- wakelock_macos 0.1.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.0 [flutter meta]
- wakelock_web 0.2.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]
```


---


**Steps:**

Once the user has done signing in, the Google Sign In plugin generates a token. This token will then be sent to our backend for verification. 

To verify that these tokens are valid, I’m using this link (https://www.googleapis.com/oauth2/v1/tokeninfo?id_token=) and so far both of the tokens generated from iOS and Android devices were valid, as shown on _**Additional context**_ above. However, whenever the token from an Android device is being verified on the backend, it would return: 

`{status: Cannot validate: Token client-id mismatch}`

Using the link above, the values on **issued_to** and **audience** on Android are different unlike from iOS.
On an iOS generated token, it’s using the OAuth client id of iOS for both **issued_to** and **audience** but for Android, the **issued_to** is using the client id of Android but the **audience** is using the client id Web Application. 

iOS:

```
{
  "issued_to": "60204403274-jvgooi7...",
  "audience": "60204403274-jvgooi7...",
  "user_id": “100368...",
  "expires_in": 3505,
  "email": “deanv...",
  "email_verified": true,
  "issuer": "https://accounts.google.com",
  "issued_at": 16195...,
  "nonce": “zd5xn33..."
}
```

Android:

```
{
  "issued_to": "60204403274-uqoa6ss...",
  "audience": "60204403274-7uh25jv2...",
  "user_id": "100368800442506365560",
  "expires_in": 3562,
  "email": "dean...",
  "email_verified": true,
  "issuer": "https://accounts.google.com",
  "issued_at": 1619575906
}

```


**Firebase credentials:**

![oauth](https://user-images.githubusercontent.com/65164446/116338294-188f8700-a80e-11eb-978b-989b0967b5cd.png)

**Comment by markusaksli-nc** [comment] 2021-04-28 14:54
As mentioned could you provide some actual code and concrete steps to reproduce the issue?

From the description this mismatch is the only issue? The sign in flow for google sign in for firebase auth still works aside from this manual validation?

**Comment by blck-shp** [comment] 2021-04-29 02:36
```
class RegularGoogleAuthentication {
  static Future<FirebaseApp> initializeFirebase({required BuildContext context}) async {
    FirebaseApp firebaseApp = await Firebase.initializeApp();
    User? user = FirebaseAuth.instance.currentUser;

    if (user != null) {
      bool result = await apiRegularSignInWithGoogle(
        firstName: user.displayName!, 
        lastName: '', 
        email: user.email!, 
        username: user.email!,
        googleId: await user.getIdToken(),
        image: user.photoURL!,
      ); // API used to send the token

      if(result == true){
        Navigator.pushReplacementNamed(context, '/home/regular');
      }
    }

    return firebaseApp;
  }

  static Future<User?> signInWithGoogle({required BuildContext context}) async {
    FirebaseAuth auth = FirebaseAuth.instance;
    User? user;
    final GoogleSignIn googleSignIn = GoogleSignIn();
    final GoogleSignInAccount? googleSignInAccount = await googleSignIn.signIn();

    if (googleSignInAccount != null) {
      final GoogleSignInAuthentication googleSignInAuthentication = await googleSignInAccount.authentication;

      bool result = await apiRegularSignInWithGoogle(
        firstName: googleSignInAccount.displayName!, 
        lastName: '', 
        email: googleSignInAccount.email, 
        username: googleSignInAccount.email,
        googleId: '${googleSignInAuthentication.idToken}',
        image: googleSignInAccount.photoUrl!,
      ); // API used to send the token

      final AuthCredential credential = GoogleAuthProvider.credential(
        accessToken: googleSignInAuthentication.accessToken,
        idToken: googleSignInAuthentication.idToken,
      );

      try {
        final UserCredential userCredential = await auth.signInWithCredential(credential);
        user = userCredential.user;

      } on FirebaseAuthException catch (e) {
        // ...
      } catch (e) {
        // ...
      }
    }

    return user;
  }
}
```

After going through the sign in process, on these functions; `initializeFirebase()` or `signInWithGoogle()`, it generates a token and sends it to the API `apiRegularSignInWithGoogle()`. For ios, it's going to be a valid request but not for android.


> From the description this mismatch is the only issue? The sign in flow for google sign in for firebase auth still works aside from this manual validation?

As for the code above, the sign in flow for google sign in for firebase auth works for both android and ios. It's just that whenever the token generated from an android device is being sent and verified by the backend, using this validator (https://github.com/google/google-id-token), it would return the error `{status: Cannot validate: Token client-id mismatch}`

**Comment by markusaksli-nc** [comment] 2021-04-29 09:39
In that case, the issue isn't really with any of the firebase plugins so I'm closing the issue here.

Since this is caused by the token provided by `google_sign_in` you can open this in https://github.com/flutter/flutter/issues

**Closed by markusaksli-nc** 2021-04-29 09:39 UTC
Labels: Needs Attention, in triage, type: bug
