### ISSUE TITLE
[firebase_storage] ref.writeToFile returns a future and doesn't report progress

### ISSUE THREAD

**Issue by iscriptology** [FirebaseExtended/flutterfire#2584] opened 2020-05-19 14:30 UTC
**Is your feature request related to a problem? Please describe.**
On native, we have a way to track progress of a download, but flutterfire doesn't expost the progress stream.

**Describe the solution you'd like**
As described in the flutter fire source code: `/// TODO: Move into own file and build out progress functionality`

**Additional context**

**Comment by TahaTesser** [comment] 2020-05-19 14:40
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/420

**Closed by TahaTesser** 2020-05-19 14:40 UTC

**Comment by awazgyawali** [comment] 2020-07-02 17:53
https://github.com/FirebaseExtended/flutterfire/pull/2884
