### ISSUE TITLE
🐛 [firebase_analytics] Firebase analytics ^7.1.0 is not compatible with http: ^0.13.0 and other plugins which also depend on http: ^0.13.0

### ISSUE THREAD

**Issue by hdavidmb** [FirebaseExtended/flutterfire#5243] opened 2021-03-06 04:16 UTC
## Bug report

I recently upgraded flutter and it made me update several plugins on my app, including all firebase suite. But after updating `firebase_analytics` to version `^7.1.0` `flutter pub get` fails with this error: 

```
Because no versions of googleapis_auth match >1.0.0 <2.0.0 and googleapis_auth 1.0.0 depends on http ^0.13.0, googleapis_auth ^1.0.0 requires http ^0.13.0.
And because firebase >=5.0.3 <9.0.0 depends on http >=0.11.3 <0.13.0, googleapis_auth ^1.0.0 is incompatible with firebase >=5.0.3 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, googleapis_auth ^1.0.0 is incompatible with firebase_analytics >=7.1.0.
```

I tried removing `googleapis_auth` plugin but then `firebase_storage` plugin also depends on `http:^0.13.0` and `flutter pub get` fails again.

### Steps to reproduce

1. Create new flutter app
2. On pubspec.yaml insert `firebase_analytics: ^7.1.0` to depend on it.
3. Also insert `http: ^0.13.0` or any other plugin that depends on it.
4. Run `flutter pub get`

### Expected behavior

`flutter pub get` running successfully and being able to run the app.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2 20D64 darwin-x64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65
```

</details>

---

**Comment by palancana** [comment] 2021-03-06 06:35
Duplicate of #5200

**Comment by vinoopks** [comment] 2021-03-07 06:52
Facing the same issue.  Hope this gets rectified soon

**Comment by markusaksli-nc** [comment] 2021-03-08 08:39
Hi @hdavidmb 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/5202.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by markusaksli-nc** 2021-03-08 08:39 UTC
Labels: Needs Attention, type: bug

**Comment by hdavidmb** [comment] 2021-03-09 13:13
You are right @markusaksli-nc . Thanks for the info.
