### ISSUE TITLE
🐛 Dart command not found flutterfire cli on Debian 10

### ISSUE THREAD

**Issue by HemilTheRebel** [FirebaseExtended/flutterfire#7879] opened 2022-01-15 17:30 UTC
## Bug report

**Describe the bug**
Installed flutter fire cli on debian 10 buster and ran flutterfire configure. Got dart: command not found

### Steps to reproduce

1. Create a new project
2. Add to pubspec.yaml
 ```yaml
firebase_core: ^1.10.0
firebase_messaging: ^11.2.5
``` 
3. Run:
```sh
# Install the CLI if not already done so
dart pub global activate flutterfire_cli

# Run the `configure` command, select a Firebase project and platforms
flutterfire configure
```

### Actual Output
![image](https://user-images.githubusercontent.com/29833486/149631415-5730f27c-82af-4ee7-b3b4-1164c3bd0128.png)

### Expected behavior
The CLI should find dart and generate the required files

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.5.3, on Debian GNU/Linux 10 (buster) 4.19.0-18-amd64, locale en_IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2021.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.14.4
Flutter SDK 2.5.3
state_mve 1.0.0+1

dependencies:
- cupertino_icons 1.0.0
- firebase_core 1.11.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 11.2.5 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.8.1 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.3.1
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.1.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.2.6 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- path 1.8.0
- plugin_platform_interface 2.1.2 [meta]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
```

</details>

---

I went through `/home/hemil/.pub-cache/bin/flutterfire` which is where pub stored the flutterfire command. The shebang was:
```sh
#!/usr/bin/env sh
```

Changing it to:
```sh
#!/usr/bin/bash
```

worked.

Note: It worked on my MacOS 12.0.1 without any modifications. This maybe totally due to some configuration of my system but I hope its existence as an issue helps someone in the future.

**Comment by maheshmnj** [comment] 2022-01-17 13:51
Hi @HemilTheRebel, Thanks for filing the issue. It seems like the fluttefire tool is not able to find the dart tool located at `/flutter/bin/dart`., Could you please check if you dart file located at `/flutter/bin/dart`?

if so, please try running `dart` in your terminal and check if you get any error or output from the dart tool.

**Comment by HemilTheRebel** [comment] 2022-01-18 03:09
My dart installation comes from flutter. Running `dart --version` outputs:
```
Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "linux_x64"
```

Running `flutter --version` outputs:
```
Flutter 2.5.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 18116933e7 (3 months ago) • 2021-10-15 10:46:35 -0700
Engine • revision d3ea636dc5
Tools • Dart 2.14.4
```

My dart tool works fine. The problem seems to be that because the shebang uses env, it seems to ignore my .bashrc where I have set the path to include flutter's bin

**Comment by maheshmnj** [comment] 2022-01-19 06:26
Thanks for the info, I am unable to reproduce the issue, Leaving this issue open for further investigation.

**Comment by darshankawar** [comment] 2022-01-19 10:59
Since you are getting the error `dart command not found` after running `flutterfire configure`, 
according to the CLI documentation, any issues using the tool need to be reported in dedicated repo: https://firebase.flutter.dev/docs/cli/#reporting-an-issue, so please open this issue here https://github.com/invertase/flutterfire_cli/issues
Closing from here.

**Closed by darshankawar** 2022-01-19 10:59 UTC
Labels: type: bug, flutterfire_cli
