### ISSUE TITLE
[Firebase Cloud Messaging for Flutter] heads-up notification on Android

### ISSUE THREAD

**Issue by angelocapone** [FirebaseExtended/flutterfire#2566] opened 2020-05-16 09:54 UTC
**Describe the bug**
May I kindly know whether the package supports heads-up notification when receiving notification in background on Android?
I’m trying all possible options to make it without luck

**Comment by TahaTesser** [comment] 2020-05-19 13:10
This needs documentation
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2093

**Closed by TahaTesser** 2020-05-19 13:10 UTC
