### ISSUE TITLE
🐛 [firebase_auth] Unable to connect to auth emulator from iOS simulator

### ISSUE THREAD

**Issue by Pitazzo** [FirebaseExtended/flutterfire#6877] opened 2021-08-24 19:55 UTC
## Bug report

I'm an unable to use the Firebase Auth Emulator from an iOS app running on the iOS simulator. When any `firebase_auth`-related operation is executed, following exception is thrown: `[firebase_auth/network-request-failed] Network error (such as timeout, interrupted connection or unreachable host) has occurred.`
### Steps to reproduce
1. Launch Firebase Emulator in your local machine
2. Enable the usage of the Auth Emulator in the iOS app:
```
await FirebaseAuth.instance.useAuthEmulator(
  '127.0.0.1',
  9099,
);
```
3. Perform any auth-related op, such as `await _firebaseAuth.verifyPhoneNumber(...)`

### Expected behavior

No exception should be thrown and the emulator should work.

## Additional context

- Already enabled incoming and outgoing connections in Xcode
- Already added following local networking permissions to `Info.plist`:
```
<dict>
  <key>NSAllowsArbitraryLoads</key>
  <true/>
  <key>NSAllowsLocalNetworking</key>
  <true/>
</dict>
```
- Already tried `localhost`, `127.0.0.1`, `192.168.0.1`...
- Firebase Emulator UI is accesible via Safari at `localhost:4000` in the simulated device
---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.4 20F71 darwin-arm, locale es-ES)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)

• No issues found!```
```
</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.4
Flutter SDK 2.2.3
controlcenter 1.0.0+1

dependencies:
- async_redux 12.0.0 [logging path path_provider file weak_map fast_immutable_collections collection meta flutter]
- carousel_slider 4.0.0 [flutter]
- cupertino_icons 1.0.3
- faker 2.0.0 [crypto]
- firebase_analytics 8.2.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_app_check 0.0.1+3 [firebase_app_check_platform_interface firebase_app_check_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.1.1 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_performance 0.7.0+7 [firebase_core flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- get_it 7.2.0 [async collection]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- logger 1.0.0
- mask_text_input_formatter 2.0.0 [flutter]
- phone_number 0.11.0+2 [flutter meta]
- pin_code_fields 7.3.0 [flutter]

dev dependencies:
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- fast_immutable_collections 5.1.1 [collection meta]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_app_check_platform_interface 0.0.1+3 [firebase_core flutter meta plugin_platform_interface]
- firebase_app_check_web 0.0.1+3 [firebase_app_check_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.0.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.0 [collection firebase_core flutter meta plugin_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http 0.13.3 [async http_parser meta path pedantic]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- lints 1.0.1
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.1
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.1 [meta]
- process 4.2.1 [file path platform]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- weak_map 2.0.2
- win32 2.2.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.2 [collection meta petitparser]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-08-25 12:28
Hi @Pitazzo 
Are you able to connect to any of the emulators from iOS simulator?
Have you made sure the simulator and firebase emulator are on the same network?
Thank you

**Comment by Pitazzo** [comment] 2021-08-30 18:55
Hey @markusaksli-nc
Thanks for your quick reply. Answering your questions:

> Are you able to connect to any of the emulators from iOS simulator?

Yes, I'm able to use Realtime Database emulator without any trouble using as address `127.0.0.1`

> Have you made sure the simulator and firebase emulator are on the same network?

Absolutely, I can confirm that as Realtime Database simulator works fine and is provided by the same instance as the Auth emulator. Moreover, I can access to the Emulator UI from the emulated device browser.

I would like to add that I have been messing around with a physical **Android** device and I'm experimenting a similar issue: connection with other emulator such as a Realtime Database emulator works fine, but when I try to authenticate with SMS Auth against the Emulator, I get following error:
```
E/FirebaseAuth(13940): [SmsRetrieverHelper] SMS verification code request failed: unknown status code: 17499 Invalid authority field:[http:
E/flutter (13940): [ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter (13940): #0      MethodChannelFirebaseAuth.verifyPhoneNumber.<anonymous closure>
```
The error message is different, but the ` 17499 Invalid authority field:[http:` makes me suspect it could be somehow related (also networking stuff) and thus this issue could be broader and related with the emulator as a whole. Let me know if I should open a new issue or edit this one.

**Comment by markusaksli-nc** [comment] 2021-08-31 10:24
So just to be clear you have tried other auth methods than `verifyPhoneNumber` or other phone-related methods? Could you also `npm i -g firebase-tools` to the latest version just in case and comment the version.

**Comment by Pitazzo** [comment] 2021-09-10 11:38
Hey @markusaksli-nc, sorry for the delay in my response. 

> So just to be clear you have tried other auth methods than `verifyPhoneNumber` or other phone-related methods? If this is just related to phone auth using the emulator then I don't think it requires a separate issue.

Other auth related methods such as `authStateChanges()` lead to the same issue.

> Could you also `npm i -g firebase-tools` to the latest version just in case and comment the version.

I'm using a [dockerized version of `firebase-tools`](https://hub.docker.com/r/andreysenov/firebase-tools), but I managed to force an update and check that following is the installed version:
```
{
  "dependencies": {
    "firebase-tools": "9.18.0"
  }
}
```

**Comment by markusaksli-nc** [comment] 2021-09-13 12:19
Well in this case I am not seeing the same issue and without being able to reproduce it seems like it shouldn't be coming from the plugin code. Because the issue isn't actionable for us I'm going to close it here but I recommend you send these logs and the strange `unknown status code: 17499` to https://firebase.google.com/support

If it they say it could be coming from somewhere in our plugin code then I can reopen.

**Closed by markusaksli-nc** 2021-09-13 12:19 UTC
Labels: type: bug, Needs Attention, in triage
