### ISSUE TITLE
[cloud_firestore] Lacking documentation on transaction handlers and return types

### ISSUE THREAD

**Issue by khainke** [FirebaseExtended/flutterfire#1899] opened 2020-01-29 15:40 UTC
Regarding: cloud_firestore, Firestore.instance.runTransaction
See: 
https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/Firestore/runTransaction.html

Currently, it is not clear, what the transactionHandler is supposed to return or how to access results from a transaction from the callback of runTransaction. Nor is it clear, how to recognize a failed transaction. Please improve the documentation on that part, as it is somewhat important to be able, to correctly handle bundled requests for the firebase database.

**Comment by kirstywilliams** [comment] 2020-04-20 17:23
Closing as a duplicate of [#1642](https://github.com/FirebaseExtended/flutterfire/issues/1642). Please follow that issue for updates.

**Closed by kirstywilliams** 2020-04-20 17:23 UTC
Labels: type: documentation
