### ISSUE TITLE
🐛 [Firebase Core] Unable to set FirebaseOptions at runtime

### ISSUE THREAD

**Issue by sima-11** [FirebaseExtended/flutterfire#6651] opened 2021-07-19 06:55 UTC
## Bug report

**Describe the bug**
I have `GoogleService-info.plist` and `google-service.json` embedded properly in the project (works as expected).
Then I was also trying to use `Firebase.initializeApp(options:)` to set a different set of configurations manually during app launch via `initState()` of the root `StatefulWidget`, in order to enable the app with multiple environments. But the configurations being picked up were always what was written in the physical google service files.

### Steps to reproduce

1. Add `GoogleService-info.plist` and `google-service.json` to the iOS and Android project as per described in the documentation.
2. In the root `StatefulWidget`, do
```
final app = await Firebase.initializeApp(options: {OPTIONS});
FirebaseAuth.instanceFor(app: app);
```
3. Go through standard username and password sign up process

### Expected behavior

User is registered under the corresponding environment

---

## Additional Questions

I think this might be expected behaviour. But if that is the case, when and where should `initializeApp(options:)` be used? Besides, based on what the physical file contains, it seems more of less a replicate of `FirebaseOptions`. Not sure why having this physical file is mandatory?

---

## Worth Mentioning

I posted the [same bug](https://github.com/FirebaseExtended/flutterfire/issues/6490) 21 days ago, but got closed and then ignored even though I followed up and mentioned the thread I was suggested to look at doesn't work.

As our work depends on flutterfire, I had to post a new ticket here.

Hopefully somebody with a more sense of responsibility will care to have a look this time.

**Comment by markusaksli-nc** [comment] 2021-07-19 08:29
Hi @sima-11 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Are you using the auth instance from the secondary app in all of the method calls?
Thank you

**Comment by sima-11** [comment] 2021-07-21 22:19
Hi @markusaksli-nc 

Thank you for your reply.

Please find results below.

### `flutter doctor -v`:
```
[✓] Flutter (Channel stable, 2.2.3, on macOS 11.2.3 20D91 darwin-x64, locale en-GB)
    • Flutter version 2.2.3 at /Users/sima/Documents/flutter
    • Framework revision f4abaa0735 (3 weeks ago), 2021-07-01 12:46:11 -0700
    • Engine revision 241c87ad80
    • Dart version 2.13.4

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/sima/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.58.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.24.0

[✓] Connected device (2 available)
    • iPhone 11 (mobile) • 1896B13E-778B-44EC-8F31-FFFEF1EAC981 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)       • chrome                               • web-javascript • Google Chrome 91.0.4472.164
    ! Error: *** Si’s iPhone 11 *** is not connected. Xcode will continue when *** Si’s iPhone 11 *** is connected. (code -13)

! Doctor found issues in 1 category.
```
### `flutter pub deps -- --style=compact`:
```
Dart SDK 2.13.4
Flutter SDK 2.2.3
kniddo 1.0.0+1

dependencies:
- cloud_firestore 2.2.1 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.2
- equatable 2.0.3 [collection meta]
- firebase_auth 1.3.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_dynamic_links 2.0.6 [firebase_core flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_sfsymbols 2.0.0 [flutter]
- flutter_slidable 0.6.0 [flutter]
- intl 0.17.0 [clock path]
- provider 5.0.0 [collection flutter nested]
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- url_launcher 6.0.9 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.4 [crypto]

dev dependencies:
- flutter_lints 1.0.3 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.1 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 5.1.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.1.1 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- crypto 3.0.1 [collection typed_data]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_auth_platform_interface 4.2.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.3.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- lints 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- win32 2.2.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- ```

**Comment by sima-11** [comment] 2021-07-21 22:21
@markusaksli-nc And to your question `Are you using the auth instance from the secondary app in all of the method calls?` - Yes.

**Comment by markusaksli-nc** [comment] 2021-07-22 10:31
So your issue is more that you are not able to create a new firebase app at runtime? Well as you guessed this is expected behavior, as documented for `initializeApp`:

> Initializes a new FirebaseApp instance by name and options and returns the created app. This method should be called before any usage of FlutterFire plugins.

So you will not be able to create new instances off of this app if it isn't initialized **first** (technically at runtime, but just before you use the other plugins). You should be able to create all of the different apps you need at startup and just reference them later.

Because this is intended, I'm going to close the issue since there isn't really anything to fix. However if you want an answer as to why the plugins work like this, I personally don't have an answer. You can ask in Discussions though.

Thank you

**Closed by markusaksli-nc** 2021-07-22 10:31 UTC
Labels: Needs Attention, in triage, type: bug
