### ISSUE TITLE
[cloud_firestore] Batch and serverTimestamp error

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#558] opened 2019-10-13 18:39 UTC
I'm trying to insert multiple documents by using the `batch`, but when I try to use the `serverTimestamp`, I get the below error.

Tested with `cloud_firestore` version `0.8.2`.

The code:

```dart
final data = <String, dynamic>{
    "processed": false,
    "createdOn": FieldValue.serverTimestamp()
};

batch.setData(firestore.collection("theCollection").document(), data);
```

The error:

```
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): Failed to handle method call
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): java.lang.RuntimeException: No properties to serialize found on class com.google.firebase.firestore.FieldValue$zzd
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo$zza.<init>(com.google.firebase:firebase-firestore@@17.1.1:659)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo.zza(com.google.firebase:firebase-firestore@@17.1.1:347)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo.zzb(com.google.firebase:firebase-firestore@@17.1.1:168)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo.zzb(com.google.firebase:firebase-firestore@@17.1.1:138)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.obfuscated.zzgo.zza(com.google.firebase:firebase-firestore@@17.1.1:1101)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.FirebaseFirestoreSettings$1.zzb(com.google.firebase:firebase-firestore@@17.1.1:1208)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.google.firebase.firestore.WriteBatch.set(com.google.firebase:firebase-firestore@@17.1.1:109)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin.onMethodCall(CloudFirestorePlugin.java:420)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:200)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at io.flutter.view.FlutterNativeView.handlePlatformMessage(FlutterNativeView.java:163)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at android.os.MessageQueue.next(MessageQueue.java:326)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at android.os.Looper.loop(Looper.java:160)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#plugins.flutter.io/cloud_firestore(28314): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

When I was using the regular insert by using the below code, everything went fine.

```dart
firestore
        .collection("theCollection")
        .document()
        .setData(data);
```

This seems to be the same as: https://stackoverflow.com/questions/52404620/flutter-firestore-batch-write-with-server-timestamp

**Comment by kroikie** [comment] 2019-10-13 18:39
@renannprado

The issue at https://github.com/flutter/flutter/issues/24992 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment] 2019-10-22 14:39
Hi @renannprado
given this [message](https://github.com/flutter/flutter/issues/24992#issuecomment-499429283) I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Closed by iapicca** 2019-10-22 14:39 UTC

**Comment by Minituff** [comment] 2019-10-28 21:18
@iapicca I am facing the same issue on the newest Firestore version. I created a new issue (Here: https://github.com/FirebaseExtended/flutterfire/issues/1322) before I found this thread. This seems to be the exact problem I am facing. I can close my previous thread if you would like and we can continue the discussion here.
Thank you.

**Comment by yvzoncu** [comment] 2019-10-28 21:21
:))) exactly the same problem
while i was trying to create new document or collection and set data in it i am getting the error

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Minituff** [comment] 2019-10-28 21:24
@yvzoncu Glad I'm not the only one. Do you have this problem when the app is online too? I am only having this issue offline, when the app is online it works properly.

**Comment by yvzoncu** [comment] 2019-10-28 21:25
while trying to setData only

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by yvzoncu** [comment] 2019-10-28 21:55
intresting I figured it out.
it was null walue in my case.
one of the fields I am trying to set was coming null.
i have fixed it and working now.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Minituff** [comment] 2019-10-28 22:06
@yvzoncu Could you please post the working and non-working code? I would like to take a look at your setData() and see if I could reproduce it on my end.

Thanks.

**Comment by yvzoncu** [comment] 2019-10-28 22:15
CollectionReference addCardPath = Firestore.instance
        .collection('resources')
        .document(gitUserUID)
        .collection('usercards');

    DocumentReference categoriesPath = Firestore.instance
        .collection('users')
        .document(gitUserUID)
        .collection('cards')
        .document('categori');

    addCardPath.add(card).then((v) => categoriesPath.setData({
          categori: FieldValue.arrayUnion([v.documentID]) =======> categori was coming
        }, merge: true).then((c) {
          print('object');
          cardCreateController = false;
          topicCtrl.clear();
          defCtrl.clear();
          categoriCtrl.clear();

          setState(() {});

          alert.showCustomDialog(context, 'Card created.', true).then((val) {
            alert.sendOKStream.listen((ok) {
              if (ok) {
                Navigator.pop(context);
              }
            });
          }, onError: (e) {
            alert.showCustomDialog(context, 'Error.', true).then((val) {
              alert.sendOKStream.listen((ok) {
                if (ok) {
                  Navigator.pop(context);
                }
              });
            });
          });
        }, onError: (e) {
          cardCreateController = false;
          alert.showCustomDialog(context, 'Error1.', true).then((val) {
            alert.sendOKStream.listen((ok) {
              if (ok) {
                Navigator.pop(context);
              }
            });
          });
        }));

i dont have the non working code but this is working now.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Minituff** [comment] 2019-10-28 22:56
@yvzoncu Thank you for the response.
I am not quite sure if we are experiencing the same issue here. Were you using a batched write before and then switched to 2 separate writes to overcome this issue?

**Comment by yvzoncu** [comment] 2019-10-28 23:03
no batch only two write with result of first

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by Minituff** [comment] 2019-10-28 23:07
Okay. Unfortunately, I don't think your solution will work for me. I am only having the issue when completing a **batched** write. I was able to separate my writes (which is not ideal for my app) and everything worked just fine. It seems to be caused by a FieldValue inside of an offline batched write.

**Comment by yvzoncu** [comment] 2019-10-28 23:09
good luck

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by JaiMistry** [comment] 2019-10-28 23:11
Hey, @iapicca I am also on the latest version of Cloud Firestore **cloud_firestore: ^0.12.9+5** and am facing the exact same issue.
