### ISSUE TITLE
🐛 [Firebase Messaging] Data only message delayed when in doze mode and Android >= O

### ISSUE THREAD

**Issue by cturn-dev** [FirebaseExtended/flutterfire#6388] opened 2021-06-14 16:28 UTC
## Bug report

When I send a high priority FCM data only message to the device, my background message handler is not given the message while the device is in doze (idle) state. As soon as the device comes out of doze the background handler is called.
Tested on multiples devices with Android >= O, in debug and release mode with flutter 2.2.1 and firebase messaging 10.0.2.

See #4718 

In the file firebase/messaging/FlutterFirebaseMessagingBackgroundService.java, the class FlutterFirebaseMessagingBackgroundService extends JobIntentService.

The   [JobIntentService documentation](https://developer.android.com/reference/androidx/core/app/JobIntentService) says:
" When running as a Job, it will be subject to standard JobScheduler policies for a Job with a JobInfo.Builder.setOverrideDeadline(long) of 0: the job will not run while the device is dozing, it may get delayed more than a service if the device is under strong memory pressure with lots of demand to run jobs."

Could this be the problem?

**Comment by markusaksli-nc** [comment] 2021-06-15 08:32
Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4718

Please comment this information there.

**Closed by markusaksli-nc** 2021-06-15 08:32 UTC
Labels: Needs Attention, in triage, type: bug
