### ISSUE TITLE
[remote_config] Web support

### ISSUE THREAD

**Issue by Viacheslav-Romanov** [FirebaseExtended/flutterfire#2809] opened 2020-06-21 04:02 UTC
Add web support to flutter remote config package. Thanks!

**Comment by yelkamel** [comment] 2020-06-22 11:32
yes please :)

**Comment by TahaTesser** [comment] 2020-06-22 12:03
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2115

**Closed by TahaTesser** 2020-06-22 12:03 UTC
