### ISSUE TITLE
support for windows desktop firebase

### ISSUE THREAD

**Issue by WashingtonlGarcia** [FirebaseExtended/flutterfire#5325] opened 2021-03-12 12:06 UTC
When support is provided for the windows\linux platform of the firebase service?

**Comment by nilsreichardt** [comment] 2021-03-14 13:07
Related to #3243

**Comment by markusaksli-nc** [comment] 2021-03-15 15:27
Closing this as a duplicate of #3243

**Closed by markusaksli-nc** 2021-03-15 15:27 UTC
