### ISSUE TITLE
[Admob] Ad failed to load : 1 :

### ISSUE THREAD

**Issue by maheshkumar2150** [FirebaseExtended/flutterfire#2621] opened 2020-05-24 11:39 UTC
This request is sent from a test device.

```bash
I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:21400
 I/DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 21400
W/flutter: onRewardedVideoAdFailedToLoad: 1
I/Ads: Ad failed to load : 1
```

```dart
@override
  void initState() {
    super.initState();
   FirebaseAdMob.instance.initialize(appId: FirebaseAdMob.testAppId);

   targetingInfo = MobileAdTargetingInfo(
    testDevices: testDevices != null ? <String>['My Device Id'] : null,
    keywords: <String>['Book', 'Game'],
    nonPersonalizedAds: true,
  );

    RewardedVideoAd.instance.listener =
        (RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
      if (event == RewardedVideoAdEvent.rewarded) {
        
      } else if (event == RewardedVideoAdEvent.loaded) {
        RewardedVideoAd.instance.show();
        
      }
    };
}
```

```dart
onPressed() {
RewardedVideoAd.instance.load(adUnitId: "My Ad Unit Id", targetingInfo: targetingInfo);
}
```

**Comment by iapicca** [comment] 2020-05-25 14:27
Hi @maheshkumar2150 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by cg021** [comment] 2020-06-09 18:55
Hi @maheshkumar2150 It looks like the ad unit id that you're using is incorrect. 
`Error Code 1 : ERROR_CODE_INVALID_REQUEST
The ad request was invalid; for instance, the ad unit ID was incorrect.`

`This commonly suggests that the Ad Request implementation is not as per the SDK’s requirements - Resources like the  sample codes and sample apps provided in the developer documentation can help in implementing the functions correctly.`

Please see [AdMob Help](https://support.google.com/admob/thread/3494603?hl=en) for a complete listing of error codes.

**Comment by cyanglaz** [comment] 2020-07-15 19:03
Same as https://github.com/FirebaseExtended/flutterfire/issues/2830

**Comment by cg021** [comment] 2020-07-15 19:31
@maheshkumar2150 Have you tried changing the `adUnitId` from `My Ad Unit Id` to a valid id? I think this is causing your issue.

**Comment by iapicca** [comment] 2020-07-20 07:22
Hi @maheshkumar2150 
as @cyanglaz pointed out  there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/2830) addressing the case you described.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-07-20 07:22 UTC
Labels: bitcoin, plugin: admob
