### ISSUE TITLE
🐛 firebase_auth fatal error: 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found

### ISSUE THREAD

**Issue by gsiewe** [FirebaseExtended/flutterfire#4792] opened 2021-01-23 20:19 UTC
## Bug report

**Describe the bug**
After adding *firebase_auth: ^0.20.0+1* to my flutter project i'm not able to build/run on ios anymore. I can still run on android though. 
Here the compile error i get when trying to run on ios

```
/Users/gsiewe/workspace/private/Ndolo/chat-yamo-android/ios/Pods/FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m:22:9: fatal error: 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found
    #import <GoogleUtilities/GULAppEnvironmentUtil.h>
```
### Steps to reproduce

1. add firebase_auth: "^0.20.0+1" to pubspec.yaml
2. execute pub get
4. run project on ios

### Expected behavior

I would expect the app to run on ios without any compile error

---

## Additional context

here the error i get when running the project on ios

```
/Users/gsiewe/workspace/private/Ndolo/chat-yamo-android/ios/Pods/FirebaseCoreDiagnostics/Firebase/CoreDiagnostics/FIRCDLibrary/FIRCoreDiagnostics.m:22:9: fatal error: 'GoogleUtilities/GULAppEnvironmentUtil.h' file not found
    #import <GoogleUtilities/GULAppEnvironmentUtil.h>
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.5 19F101 darwin-x64, locale de-DE)
    • Flutter version 1.22.5 at /Users/gsiewe/workspace/private/flutter
    • Framework revision 7891006299 (6 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/gsiewe/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (1 available)
    • iPhone 12 Pro Max (mobile) • 56B67681-CBCA-4927-BAC6-7DD550E80343 • ios • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.5
chatetyamo 0.0.0

dependencies:
- apple_sign_in 0.1.0 [flutter]
- backdrop 0.4.6 [flutter]
- currency_pickers 1.0.6 [flutter]
- event_bus 1.1.1
- expandable_text 1.1.0 [flutter]
- firebase_auth 0.20.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_messaging 6.0.16 [meta platform flutter]
- firebase_performance 0.3.1+7 [flutter]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_cache_manager 1.4.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_custom_tabs 0.6.0 [flutter url_launcher]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_native_splash 0.1.9 [yaml image color]
- flutter_screenutil 3.1.1 [flutter]
- flutter_slidable 0.5.7 [flutter]
- flutter_webview_plugin 0.3.11 [flutter]
- fluttertoast 7.1.1 [flutter flutter_web_plugins]
- geolocator 5.3.2+2 [flutter meta equatable google_api_availability location_permissions vector_math]
- highlighter_coachmark 0.0.3 [flutter]
- http 0.12.2 [http_parser path pedantic]
- image_crop 0.3.3 [flutter]
- image_picker 0.6.7+14 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- in_app_purchase 0.3.3+1 [async collection flutter json_annotation meta]
- intl 0.16.1 [path]
- intro_slider 2.3.3 [flutter]
- material_design_icons_flutter 4.0.5655 [flutter]
- package_info 0.4.3 [flutter]
- photo_view 0.10.2 [flutter]
- quiver 2.1.3 [matcher meta]
- rate_my_app 0.4.0 [shared_preferences smooth_star_rating flutter]
- rflutter_alert 1.1.0 [flutter]
- rxdart 0.24.1
- share 0.6.5+2 [meta mime flutter]
- shared_preferences 0.5.12 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- super_tooltip 0.9.0 [flutter]
- timer_builder 1.3.0 [flutter]
- url_launcher 5.7.2 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- zoomable_image 1.3.1 [flutter]

dev dependencies:
- flutter_launcher_icons 0.7.4 [image args yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- color 2.1.1
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.4 [collection convert typed_data]
- equatable 1.1.1 [collection meta]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+6 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- google_api_availability 2.0.4 [flutter]
- http_parser 3.1.3 [charcode collection source_span string_scanner typed_data]
- image 2.1.12 [archive xml]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- js 0.6.2
- json_annotation 3.0.1
- location_permissions 3.0.0+1 [flutter meta]
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- path 1.8.0-nullsafety.1
- path_provider 1.6.1 [flutter platform meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.8.0+1
- petitparser 2.4.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.2 [meta]
- process 3.0.13 [file intl meta path platform]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- smooth_star_rating 1.0.3 [flutter]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.1.7+2 [flutter synchronized path]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.1.0+1
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- uuid 2.0.4 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.3 [ffi]
- xdg_directories 0.1.0 [path process flutter]
- xml 3.6.1 [collection convert meta petitparser]
- yaml 2.2.0 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-01-25 11:47
Hi @gsiewe 
Could you try `flutter clean and then in `ios` directory:
```console
rm -rf ~/Library/Developer/Xcode/DerivedData/
rm -rf ~/Library/Caches/CocoaPods/
pod deintegrate
pod update
```
and then `flutter pub get`.
You can also do `flutter pub cache repair`.
Thank you

**Comment by gsiewe** [comment] 2021-01-25 19:12
Hi @markusaksli-nc,

when i execute the command in the order you gave here is the output

```
flutter clean
cd ios
rm -rf ~/Library/Developer/Xcode/DerivedData/
rm -rf ~/Library/Caches/CocoaPods/
pod deintegrate
pod update

[!] Invalid `Podfile` file: /Users/gsiewe/workspace/private/Ndolo/chat-yamo-android/ios/Flutter/Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first.

 #  from /Users/gsiewe/workspace/private/Ndolo/chat-yamo-android/ios/Podfile:16
 #  -------------------------------------------
 #    unless File.exist?(generated_xcode_build_settings_path)
 >      raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
 #    end
 #  -------------------------------------------
```

Then i changed the order of the commands like this

```
flutter clean
cd ios
rm -rf ~/Library/Developer/Xcode/DerivedData/
rm -rf ~/Library/Caches/CocoaPods/
pod deintegrate
flutter pub get
pod update
```
But when running the app on ios it still doesn't compile

**Comment by markusaksli-nc** [comment] 2021-01-26 09:11
I'm not seeing this on the latest master `1.26.0-13.0.pre.179` with `firebase_auth: ^0.20.0+1`.
<details>
 <summary>flutter doctor -v</summary>

```console
[✓] Flutter (Channel master, 1.26.0-13.0.pre.179, on macOS 11.1 20C69 darwin-arm, locale en-GB)
    • Flutter version 1.26.0-13.0.pre.179 at /Users/nevercode/development/flutter_master
    • Framework revision fc9addb88b (42 minutes ago), 2021-01-26 03:24:03 -0500
    • Engine revision f47ab4434d
    • Dart version 2.12.0 (build 2.12.0-257.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7042882/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.3
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 11.1 20C69 darwin-arm
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 88.0.4324.96

• No issues found!
```
</details>

Did you try `flutter pub cache repair`?

**Comment by gsiewe** [comment] 2021-01-26 09:14
I'm on stable channel, not on master. You can take a look at my flutter doctor -v output

```
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.5 19F101 darwin-x64, locale de-DE)
    • Flutter version 1.22.5 at /Users/gsiewe/workspace/private/flutter
    • Framework revision 7891006299 (7 weeks ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4


[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/gsiewe/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 48.1.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] IntelliJ IDEA Ultimate Edition (version 2020.1.2)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[✓] Connected device (2 available)
    • sdk gphone x86 (mobile)    • emulator-5554                        • android-x86 • Android 11 (API 30) (emulator)
    • iPhone 12 Pro Max (mobile) • 56B67681-CBCA-4927-BAC6-7DD550E80343 • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)

! Doctor found issues in 1 category.
```

**Comment by markusaksli-nc** [comment] 2021-01-26 09:23
Could you update your CocoaPods using `sudo gem update cocoapods`?

**Comment by jpv123** [comment] 2021-02-04 21:18
I'm having the same problem here. I simply can't run on iOS. Any update on this topic?

**Comment by gsiewe** [comment] 2021-02-05 08:57
@markusaksli-nc ,
i run all required command, but still have the issue. i just can't run it on iOS.

**Comment by markusaksli-nc** [comment] 2021-02-05 09:12
@gsiewe If you just `flutter create` a new project and only add the `firebase_auth` dependency does it do this as well? It seems like it could be caused by one of your other packages using an outdated version of `GoogleUtilities` forcing it on `firebase_auth` as well (`geolocator` maybe?)

**Comment by nuelsoft** [comment] 2021-02-14 05:09
@markusaksli-nc 
For me, using just firebase_auth causes this same error when attempting to build for ios. Is this going to be fixed anytime soon?

**Comment by alibubere9** [comment] 2021-02-15 00:20
I seem to be able to have some hint of the error after juggling for around four hours.

I'm currently working on two projects with my older project pointing at `firebase_auth:0.16.1` but the newer project uses the latest public release `0.20.1+1` As far as I've researched around, this seems to cause this issue as per my understanding
.

**Comment by srsudar** [comment] 2021-02-15 06:51
I saw this problem at the same time I saw the problem in #4931 . My solution is, following other people's advice, is [here](https://github.com/FirebaseExtended/flutterfire/issues/4931#issuecomment-778965420).

**Comment by alibubere9** [comment] 2021-02-15 11:07
> I seem to be able to have some hint of the error after juggling for around four hours.
> 
> I'm currently working on two projects with my older project pointing at `firebase_auth:0.16.1` but the newer project uses the latest public release `0.20.1+1` As far as I've researched around, this seems to cause this issue as per my understanding.
> 
> EDIT:
> And that turns out to be absolutely baseless.

So now I'm up and fresh and can explain what really is the issue.

To begin with the Firebase plugins have updated and have a dependancy on `firebase_core`. But for some unknown reason the latest stable version of `firebase_core: 0.7.0` (in my case) doesn't support the latest `firebase_messaging` version `7.0.3`. 

When you update `firebase_messaging` to `7.0.3`. 
This error is thrown:
`[classified_app] flutter pub get
Running "flutter pub get" in classified_app...                  
Because firebase_messaging >=7.0.3 <8.0.0-dev.7 depends on firebase_core ^0.5.0+1 and classified_app depends on firebase_core ^0.7.0, firebase_messaging >=7.0.3 <8.0.0-dev.7 is forbidden.

So, because classified_app depends on firebase_messaging ^7.0.3, version solving failed.
pub get failed (1; So, because classified_app depends on firebase_messaging ^7.0.3, version solving failed.)
exit code 1`

So I have to use `firebase_messaging : 6.0.16` which  is an independant package and doesn't require `firebase_core` in the `yaml` as mentioned in the changelog of `7.0.0`

'Depend on firebase_core and migrate plugin to use firebase_core native SDK versioning features;
Firebase iOS SDK versions are now locked to use the same version defined in firebase_core.
Firebase Android SDK versions are now using the Firebase Bill of Materials (BoM) to specify individual SDK versions. BoM version is also sourced from firebase_core.
Allow iOS to be imported as a module.`

So my theory as I've not dived into the core packages, says that since the `firebase_messaging:6.0.16` doesn't have a pubspec dependancy it might be asking for the older version of the FirebaseCore pod subsequently GoogleServiceUtilites and there's a conflict of mulriple plugins having same configs.


Still I don't know how to solve this but I seem to have a found a reason for the multiple pods issue for the same pluugin.

**Comment by markusaksli-nc** [comment] 2021-02-15 12:42
@alibubere9 Your `firebase_messaging` workaround is entirely unnecessary though since you can just use the latest non-nullsafety version `firebase_messaging: ^8.0.0-dev.14`.

This should be mentioned in the documentation but due to some fixes regarding the null safety versions it got mistakingly automatically replaced with the old `7.0.3` version. There is already an open issue to track this https://github.com/FirebaseExtended/flutterfire/issues/4955

Technically this version is still prerelease but it is much more stable and reliable than `7.0.3` already and it got rid of all of the native code workarounds needed before.

**Comment by markusaksli-nc** [comment] 2021-02-15 12:53
Actually seeing that this same independent package is used by @gsiewe this could be the root cause of the issue here. Still waiting for a response.

**Comment by alibubere9** [comment] 2021-02-15 13:14
> @alibubere9 Your `firebase_messaging` workaround is entirely unnecessary though since you can just use the latest non-nullsafety version `firebase_messaging: ^8.0.0-dev.14`.
> 
> This should be mentioned in the documentation but due to some fixes regarding the null safety versions it got mistakingly automatically replaced with the old `7.0.3` version. There is already an open issue to track this https://github.com/FirebaseExtended/flutterfire/issues/4955
> 
> Technically this version is still prerelease but it is much more stable and reliable than `7.0.3` already and it got rid of all of the native code workarounds needed before.

You're absolutely correct with this but the issue then is pod `install` fails with couldn't find the package, I did try it last night when I was juggling around for a solution, I'll have a go on android tonight with this, if it works then maybe I'll need to look in the pods.

**Comment by alibubere9** [comment] 2021-02-15 14:09
> Actually seeing that this same independent package is used by @gsiewe this could be the root cause of the issue here. Still waiting for a response.

I don't really know what weed was pod smoking last night. 

I updated `firebase_messaging` to `8.0.0.-dev.14` and see:

```alibubere@Alis-Mac classified % flutter clean && flutter pub get && cd ios && pod install
Cleaning Xcode workspace...                                         5.7s
Deleting build...                                                  111ms
Deleting .dart_tool...                                               3ms
Deleting Generated.xcconfig...                                       1ms
Deleting flutter_export_environment.sh...                            1ms
Deleting App.framework...                                            4ms
Deleting Flutter.podspec...                                          1ms
Deleting .flutter-plugins-dependencies...                            2ms
Deleting .flutter-plugins...                                         0ms
Running "flutter pub get" in classified...                          1.1s
Analyzing dependencies
firebase_auth: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
firebase_core: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
firebase_messaging: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
firebase_storage: Using Firebase SDK version '7.3.0' defined in 'firebase_core'
Downloading dependencies
Installing Firebase (7.3.0)
Installing FirebaseAuth (7.3.0)
Installing FirebaseCore (7.3.0)
Installing FirebaseCoreDiagnostics (7.6.0)
Installing FirebaseInstallations (7.6.0)
Installing FirebaseInstanceID (7.6.0)
Installing FirebaseMessaging (7.3.0)
Installing FirebaseStorage (7.3.0)
Installing Flutter (1.0.0)
Installing GTMSessionFetcher (1.5.0)
Installing GoogleDataTransport (8.2.0)
Installing GoogleUtilities (7.2.2)
Installing PromisesObjC (1.2.12)
Installing app_settings (3.0.0+1)
Installing firebase_auth (0.20.0-1)
Installing firebase_core (0.7.0)
Installing firebase_messaging (8.0.0-dev.14)
Installing firebase_storage (7.0.0)
Installing flutter_inappwebview (0.0.1)
Installing geolocator (6.2.0)
Installing image_picker (0.0.1)
Installing nanopb (2.30907.0)
Installing package_info (0.0.1)
Installing path_provider (0.0.1)
Installing share (0.0.1)
Installing shared_preferences (0.0.1)
Installing url_launcher (0.0.1)
Installing vibration (1.7.3)
Installing webview_flutter (0.0.1)
Generating Pods project
Integrating client project
Pod installation complete! There are 16 dependencies from the Podfile and 29 total pods installed.

[!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Release.xcconfig`).
```

**Comment by gsiewe** [comment] 2021-02-15 22:21
Indeed, using 8.0.0.-dev.14 also solved the issue for me.
Thanks @markusaksli-nc

**Comment by markusaksli-nc** [comment] 2021-02-16 07:29
Thanks, closing this as solved

**Closed by markusaksli-nc** 2021-02-16 07:29 UTC
Labels: Needs Attention, type: bug
