### ISSUE TITLE
Firestore PlatformException(Error performing get, Failed to get document because the client is offline., null

### ISSUE THREAD

**Issue by William-cpu** [FirebaseExtended/flutterfire#2898] opened 2020-07-05 18:29 UTC
**Describe the bug**
I'm getting the below PlatformException in a FutureBuilder when using an app.release.apk on an Android phone. 
I noticed that if I have the app open and I just close the phone, after opening it and visiting an item from a ListView generates the error, sometimes following visits to other items causes the exception, sometimes not.

**To Reproduce**
1. Open app
2. Go to a list view
4. Close the phone
5. Open phone after 5 - 10 min
6. Click on any list view item
7. Exception happens

**Expected behavior**
I expect the call to Firestore to return data for a specific document.

**Additional context**

Below is the code I use to make the request

item-db.dart
```
  Future<DocumentSnapshot> getItem(itemID) {
    try {
      DocumentReference ref = _db.collection("content").document(itemID);
      return ref.get();
    } catch (error) {
      print(error);
    }
    return null;
  }
```

item.dart
```
Future<DocumentSnapshot> _itemFuture;

@override
  void initState() {
    super.initState();
    _itemFuture = _itemDB.getItem(widget.item.documentID);
}

    FutureBuilder<DocumentSnapshot>(
        future: _itemFuture, // a previously-obtained Future<String> or null
        builder:
            (BuildContext context, AsyncSnapshot<DocumentSnapshot> snapshot) {
          List<Widget> children;
          if (snapshot.hasData) {
            children = <Widget>[Expanded(child: _itemBody(snapshot.data))];
          } else if (snapshot.hasError) {
            children = <Widget>[
              Icon(
                Icons.error_outline,
                color: Colors.red,
                size: 60,
              ),
              Padding(
                padding: const EdgeInsets.only(top: 16),
                child: Text('Error: ${snapshot.error}'),
              )
            ];
          } else {
            children = <Widget>[
              SizedBox(
                child: CircularProgressIndicator(),
                width: 60,
                height: 60,
              ),
              const Padding(
                padding: EdgeInsets.only(top: 16),
                child: Text('Awaiting result...'),
              )
            ];
          }
          return Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              crossAxisAlignment: CrossAxisAlignment.center,
              children: children,
            ),
          );
        },
      );
```

pubspec.yaml
```
cloud_firestore: ^0.13.7
firebase_auth: ^0.16.1
```

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale en-RO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[!] Android Studio (version 3.5)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.46.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-07-06 12:59
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2498

**Closed by TahaTesser** 2020-07-06 12:59 UTC

**Comment by William-cpu** [comment] 2020-07-06 14:25
@TahaTesser I see that the other issue doesn't have a solution. Is this a known issue? We are finished with development and this is holding back everything.

**Comment by TahaTesser** [comment] 2020-07-07 08:23
@William-cpu 
This is the duplicate, original issue/known issue is still open hence not fixed yet 
Please thumbs up mentioned issue to raise priority

**Comment by William-cpu** [comment] 2020-07-08 12:00
Yes. It is open. My mistake. Thank you.
