### ISSUE TITLE
🐛 [firebase_messaging] No notification is shown in iOS right after installation. It works again when app is restarted once.

### ISSUE THREAD

**Issue by sc00n** [FirebaseExtended/flutterfire#4152] opened 2020-11-19 09:20 UTC
Previously my app worked just fine (for over a year). The app I have in the app store also still works fine.

Since I updated to the newest flutter and firebase_messaging package I however have some problems on iOS (Android works fine). I now have 

`firebase_messaging: ^7.0.3`

When I install the app and close it I don't get any notifications. When I then open the app again I get an onMessage call (so the message was received by the phone, but the notification was not shown as a notification while the app was closed), but it looks different as what I normal get:

`{from: 756240466417, data: {“message“:369}, collapse_key: io.m-Path.kuleuven, click_action: FLUTTER_NOTIFICATION_CLICK, notification: {sound2: default, title: Notification from Siggy [code0]:, tag: whatever, e: 1, sound: default, body: Time for a couple of questions?, icon: myIcon}}`

After that, everything works normal. I get notifications when the app is closed, and the onMessage calls I get when the app is open look like what I always had:

`{gcm.message_id: 1605774095223064, data: {“message“:369}, google.c.sender.id: 756240466417, google.c.a.e: 1, click_action: FLUTTER_NOTIFICATION_CLICK, aps: {alert: {title: Notification from Siggy [code0]:, body: Time for a couple of questions?}, sound: default}}`

Flutter doctor -v

```

[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-BE)
    • Flutter version 1.22.4 at /Users/app/flutter
    • Framework revision 1aafb3a8b9 (6 days ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/merijnmestdagh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
 
[✓] Connected device (1 available)            
    • Merijn’s iPhone (mobile) • 00008020-0009601E1199002E • ios • iOS 13.4.1
```

**Comment by markusaksli-nc** [comment] 2020-11-20 13:31
Hi @sc00n 
The app needs to be initialized at least once to register the FCM token and to request notification permissions. It should be expected that it cannot send notifications before it has been opened for the first time.
If the issue is that notifications do not work before the app has been opened, does this answer your concerns?
Thank you.

**Comment by sc00n** [comment] 2020-11-20 14:03
Hey @markusaksli-nc

Thank you for your help. What I meant is that I first install the app, then open the app, then close the app. In this case the notifications don't work. After that I open and close the app again and then the notifications work.

When I do the following: first install the app, then open the app and then send a firebase message I get the message.  So this means that also the first time firebase was actually initialized (I think). But to get messages when the app is closed I need to open en close the app twice. 

I now upgraded to **8.0.0-dev.8**. Here I have the problem when I use flutter install. When I use flutter run I don't have the problem. Using the example code from  8.0.0-dev.8 I don't seem to have the problem (also not with flutter install). It is all kind of weird as everything seems to almost work :). I am now gradually changing the example app to my app to see when the problem is introduced.

**Comment by markusaksli-nc** [comment] 2020-11-20 14:13
Ah I see, thanks for clearing the confusion. 

The new stable will likely solve this once it lands in that case. Since the problem still occurred in `8.0.0-dev.8` it would be great if you could isolate what causes it. There is already an issue for tracking troubles with getting iOS notifications https://github.com/FirebaseExtended/flutterfire/issues/4097. It would be great to get that information there if this isn't just a simple mistake in your code.

Closing this since issues purely about the old version will get outdated anyway as soon as the new version lands properly.

**Closed by markusaksli-nc** 2020-11-20 14:13 UTC
Labels: Needs Attention, type: bug

**Comment by sc00n** [comment] 2020-11-21 18:58
After hours of debugging and similar problems in 8.0.0-dev.8 I finally got it back to work by using `firebase_messaging: ^7.0.3` and including` firebase_core: 0.5.0+1`. Anything higher (for firebase_core) gives problems in my app.
