### ISSUE TITLE
Documentation not working

### ISSUE THREAD

**Issue by douglasnoronha** [FirebaseExtended/flutterfire#2449] opened 2020-04-28 01:23 UTC
**Describe the bug**
The documentation for firebase_messaging is extremely flawed, it has no correct explanation for handling messages in the background.
I've done research here looking for a solution and it doesn't exist, what I find most are reports that don't really work.
Does the onBackgroundMessage function work yes or no?
If it works what are the correct procedures that must be followed to configure, the documentation is not correct.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Microsoft Windows [versão 6.1.7601]
Copyright (c) 2009 Microsoft Corporation. Todos os direitos reservados.

C:\Users\Douglas>flutter doctor -v
[ÔêÜ] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [vers├â┬
o
    6.1.7601], locale pt-BR)
    ÔÇó Flutter version 1.12.13+hotfix.9 at C:\flutter
    ÔÇó Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    ÔÇó Engine revision af51afceb8
    ÔÇó Dart version 2.7.2

[ÔêÜ] Android toolchain - develop for Android devices (Android SDK version 29.0
2)
    ÔÇó Android SDK at C:\Users\Douglas\AppData\Local\Android\sdk
    ÔÇó Android NDK location not configured (optional; useful for native profil
ng
      support)
    ÔÇó Platform android-29, build-tools 29.0.2
    ÔÇó Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    ÔÇó Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)
    ÔÇó All Android licenses accepted.

[ÔêÜ] Android Studio (version 3.6)
    ÔÇó Android Studio at C:\Program Files\Android\Android Studio
    ÔÇó Flutter plugin version 45.1.1
    ÔÇó Dart plugin version 192.7761
    ÔÇó Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b04)

[!] IntelliJ IDEA Community Edition (version 2019.2)
    ÔÇó IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition
      2019.2
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    ÔÇó For information about installing plugins, see
      https://flutter.dev/intellij-setup/#installing-the-plugins

[ÔêÜ] VS Code (version 1.44.2)
    ÔÇó VS Code at C:\Users\Douglas\AppData\Local\Programs\Microsoft VS Code
    ÔÇó Flutter extension version 3.5.1

[ÔêÜ] Connected device (1 available)
    ÔÇó SM J500M ÔÇó 0d7354e5 ÔÇó android-arm ÔÇó Android 6.0.1 (API 23)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-04-28 12:10
Hi @douglasnoronha 
Looks lie there is an already open for  documentation 
Closing as duplicate of [#2387](https://github.com/FirebaseExtended/flutterfire/issues/2387)

**Closed** 2020-04-28 12:11 UTC
