### ISSUE TITLE
[admob] the Google Mobile Ads SDK was initialized incorrectly.

### ISSUE THREAD

**Issue by khangahs** [FirebaseExtended/flutterfire#1805] opened 2020-01-12 07:25 UTC
```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="appmobile.app_mobile">
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="Ambience - Relaxing Sounds"
        android:icon="@mipmap/ambience">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true"/>
            <meta-data
                android:name="com.google.android.gms.ads.APPLICATION_ID"
                android:value="ca-app-pub-123456789456123~123456789"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>
```

```bash
2020-01-11 23:20:42.252 22162-22162/? E/Zygote: isWhitelistProcess - Process is Whitelisted
2020-01-11 23:20:42.253 22162-22162/? E/Zygote: accessInfo : 1
2020-01-11 23:20:42.259 22162-22162/? I/_ambience_soun: Late-enabling -Xcheck:jni
2020-01-11 23:20:42.444 22162-22162/? I/_ambience_soun: report jit thread pid = 22186
2020-01-11 23:20:43.044 22162-22162/com.kaiserambiencesound.kaiser_ambience_sound D/AndroidRuntime: Shutting down VM
2020-01-11 23:20:43.056 22162-22162/com.kaiserambiencesound.kaiser_ambience_sound E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.kaiserambiencesound.kaiser_ambience_sound, PID: 22162
    java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here:                                       *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to add a valid App ID inside the AndroidManifest.                          *
    * Google Ad Manager publishers should follow instructions here:              *
    * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
    ******************************************************************************
    
    
        at android.app.ActivityThread.installProvider(ActivityThread.java:6808)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6350)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6265)
        at android.app.ActivityThread.access$1200(ActivityThread.java:240)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1806)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7124)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
     Caused by: java.lang.IllegalStateException: 
    
    ******************************************************************************
    * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
    * should follow the instructions here:                                       *
    * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
    * to add a valid App ID inside the AndroidManifest.                          *
    * Google Ad Manager publishers should follow instructions here:              *
    * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
    ******************************************************************************
    
    
        at com.google.android.gms.internal.ads.zzxb.attachInfo(com.google.android.gms:play-services-ads-lite@@18.1.1:27)
        at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@18.1.1:3)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6803)
        	... 10 more
```

**Comment by iapicca** [comment] 2020-01-21 07:48
Hi @khangahs  
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
Thank you

**Comment by korchix** [comment] 2020-03-22 14:29
for android you have to add this as well:

```
<manifest>
    <application>
        <meta-data
            android:name="com.google.android.gms.ads.AD_MANAGER_APP"
            android:value="true"/>
    </application>
</manifest>
```

https://developers.google.com/ad-manager/mobile-ads-sdk/android/quick-start#update_your_androidmanifestxml

**Comment by BrunoLCunha** [comment] 2020-04-04 20:44
I am having this problem as well using Unity 2020 and GoogleMobileAds-v5.0.1

**Comment by blasten** [comment] 2020-05-15 03:41
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2516.

Please follow the documentation https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob

**Closed by blasten** 2020-05-15 03:41 UTC
Labels: blocked: customer-response, impact: customer, platform: android, plugin: admob, type: bug
