### ISSUE TITLE
Abmob Adaptive Banners

### ISSUE THREAD

**Issue by edscodeblenders** [FirebaseExtended/flutterfire#2370] opened 2020-04-15 15:36 UTC
We received an email from Google that we could increase our banner revenue up to 20% by using "adaptative banners". Do you have any plan to add support for them in Flutter?

**Comment by blasten** [comment] 2020-05-15 22:30
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2003

**Closed by blasten** 2020-05-15 22:30 UTC
Labels: bitcoin, plugin: admob, type: enhancement
