### ISSUE TITLE
🐛 [cloud_firestore] CollectionReference.add() promise not resolving when working offline

### ISSUE THREAD

**Issue by IAmJulianAcosta** [FirebaseExtended/flutterfire#4273] opened 2020-11-30 17:45 UTC
## Bug report

**Describe the bug**

When using `await CollectionReference.add()`, the promise never resolves, but the item is created.

### Steps to reproduce

```
CollectionReference collection = FirebaseFirestore.instance.collection('path');
data = {
  foo: FirebaseFirestore.instance.collection('/foo').doc('1');
}
DocumentReference reference = await collection.add(data);
DocumentSnapshot snapshot = await reference.get();

//I do something with the snapshot
```

### Expected behavior
The promise resolves, and the execution of the method continues

## Additional context
I have an app that requires to be used offline, and I'm using cloud firestore to store data, and it will sync end of day when it has internet access.

The app loads some data from firebase when is online, then it goes offline and data is added while is still offline. 

--- 

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-CO)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] Connected device (2 available)

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.4

dependencies:
- camera 0.5.8+5 [flutter]
- cloud_firestore 0.14.3 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cron 0.2.3
- event_bus 1.1.1
- ffi 0.1.3
- firebase_auth 0.18.3 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.2 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_ml_vision 0.9.9 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_android 0.8.0 [flutter meta typed_data]
- flutter_launcher_icons 0.8.1 [image args yaml path]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- image 2.1.14 [archive xml]
- intl 0.16.1 [path]
- package_info 0.4.3+2 [flutter]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- qr_flutter 3.2.0 [flutter qr]
- shared_preferences 0.5.12 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- slugify 1.0.0
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- validators 2.0.1 [vin_decoder]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- asn1lib 0.6.5
- async 2.5.0-nullsafety.1 [collection]
- basic_utils 2.6.2 [http logging json_annotation pointycastle asn1lib convert crypto]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.0 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 2.1.3 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.2
- json_annotation 3.0.1
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- path 1.8.0-nullsafety.1
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.0
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.0.4 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.2 [meta]
- pointycastle 1.0.2
- process 3.0.13 [file intl meta path platform]
- qr 1.3.0 [meta]
- quiver 2.1.3 [matcher meta]
- random_string 2.1.0
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0-nullsafety.3
- vin_decoder 0.1.2 [meta basic_utils http random_string]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.0 [path process flutter]
- xml 4.2.0 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by IAmJulianAcosta** [comment] 2020-11-30 23:38
I realized that maybe this not a bug, but is by design, as the reference can only come after is created in the server, but if it is the case, is there a way to access the newly created record?

**Comment by markusaksli-nc** [comment] 2020-12-01 11:23
Not seeing this behavior on the latest master `1.24.0-8.0.pre.375` with `cloud_firestore: ^0.14.3+1`.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.375, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.375 at C:\Development\flutter_master
    • Framework revision a7f5fd5360 (22 hours ago), 2020-11-30 13:14:13 +0100
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.2)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\202.8194.7
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (6 available)
    • SM G950F (mobile)           • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • sdk gphone x86 arm (mobile) • emulator-5554      • android-x86    • Android 11 (API 30) (emulator)
    • Windows (desktop)           • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)            • web-server         • web-javascript • Flutter Tools
    • Chrome (web)                • chrome             • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)                  • edge               • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```
</details>
<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      body: Center(
        child: Adder(),
      ),
    );
  }
}

class Adder extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return RaisedButton(
      child: const Text("Add and await"),
      onPressed: () async {
        CollectionReference collection = FirebaseFirestore.instance.collection('test');
        var data = {
          "foo": FirebaseFirestore.instance.collection('test').doc('testDoc'),
        };
        DocumentReference reference = await collection.add(data);
        DocumentSnapshot snapshot = await reference.get();
        print(snapshot.data());
      },
    );
  }
}
```
</details>

The future resolves and the print is reached. Does this sample not work for you?

**Comment by IAmJulianAcosta** [comment] 2020-12-01 15:40
Hi @markusaksli-nc, I tried your example, with an LG US998 as a device. Enabled airplane mode (maybe you didn't do this step) on it and ran your code, this is the outcome:

```
W/ManagedChannelImpl(18737): [{0}] Failed to resolve name. status={1}
I/ViewRootImpl(18737): ViewRoot's Touch Event : ACTION_DOWN
I/zygote64(18737): Do partial code cache collection, code=60KB, data=50KB
I/zygote64(18737): After code cache collection, code=60KB, data=50KB
I/zygote64(18737): Increasing code cache capacity to 256KB
I/ViewRootImpl(18737): ViewRoot's Touch Event : ACTION_UP
W/Firestore(18737): (22.0.0) [WriteStream]: (b21e44) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(18737): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:436)
W/Firestore(18737): 	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:272)
W/Firestore(18737): 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:228)
W/Firestore(18737): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
W/Firestore(18737): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
W/Firestore(18737): 	at java.lang.Thread.run(Thread.java:764)
W/Firestore(18737): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(18737): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
W/Firestore(18737): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
W/Firestore(18737): 	at java.net.InetAddress.getAllByName(InetAddress.java:787)
W/Firestore(18737): 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:646)
W/Firestore(18737): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:404)
W/Firestore(18737): 	... 5 more
W/Firestore(18737): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(18737): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore(18737): 	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:58)
W/Firestore(18737): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:122)
W/Firestore(18737): 	... 9 more
W/Firestore(18737): }.
W/ManagedChannelImpl(18737): [{0}] Failed to resolve name. status={1}
```

Using Flutter `1.24.0-8.0.pre.375`, with `cloud_firestore: ^0.14.3+1` too. If I remove the `await` [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/lib/src/collection_reference.dart#L45), the promise will resolve

Placed a debugger and the code is stuck here:

**Comment by IAmJulianAcosta** [comment] 2020-12-01 18:59
I'm having this issue too #3521, probably related

**Comment by markusaksli-nc** [comment] 2020-12-02 07:58
On a physical device with airplane mode enabled the promise does seem to not resolve at all.
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 1.24.0-8.0.pre.406, on Microsoft Windows [Version 10.0.19041.630], locale et-EE)
    • Flutter version 1.24.0-8.0.pre.406 at C:\Development\flutter_master
    • Framework revision 60bdcf55fe (3 hours ago), 2020-12-01 21:24:21 -0800
    • Engine revision 20caf54969
    • Dart version 2.12.0 (build 2.12.0-76.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (5 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.630]
    • Web Server (web)  • web-server         • web-javascript • Flutter Tools
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 87.0.4280.66
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 87.0.664.47

• No issues found!
```
</details>

**Comment by IAmJulianAcosta** [comment] 2020-12-02 23:07
I investigated a little bit more to check why is this happening, and tracked it down to [this method](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore_platform_interface/lib/src/method_channel/method_channel_document_reference.dart#L28-L45), here is where the promise doesn't resolve, so I think that it is something going on in [Android](https://github.com/firebase/firebase-android-sdk/blob/00e6a8d5e19ba962702268c67ea8e4a5b006ea1e/firebase-firestore/src/main/java/com/google/firebase/firestore/DocumentReference.java#L160-L171) (or [here](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java#L433)) that prevents the promise to resolve.

**Comment by Salakar** [comment] 2020-12-06 23:49
@kroikie is this a potential Firebase Android SDK issue? When offline the Android SDK errors with a dns failure resolution instead of 'working offline'

**Comment by kroikie** [comment] 2020-12-17 18:32
@Salakar There may be an issue with the DMS failure resolution.

However the `add` not returning is expected since the device is offline and writes only complete on the server. One option if possible would be to not await the write. The document should still be available from cache the SDK will sync the added documents once the device gets back online.

**Comment by IAmJulianAcosta** [comment] 2020-12-19 00:45
@kroikie is there a workaround for this case?

```
CollectionReference collection = FirebaseFirestore.instance.collection('path');
data = {
  foo: FirebaseFirestore.instance.collection('/foo').doc('1');
}
DocumentReference reference = await collection.add(data);
DocumentSnapshot snapshot = await reference.get();
```

If I remove `await` from `add()`, I won't have a reference to get the snapshot, as the promise returned by `add()` returns that reference. Is there a way I can get the locally created record without that reference?

**Comment by kroikie** [comment] 2021-01-15 16:52
@IAmJulianAcosta In this case would it be possible for you to use `await firestore.document('/foo/1').get();`

**Comment by russellwheatley** [comment] 2021-04-21 14:42
I'm going to close this issue as it appears `add()` not resolving is expected behaviour when the device is offline.

**Comment by IAmJulianAcosta** [comment] 2021-04-21 16:12
@russellwheatley I don't agree with closing this. I think that is not realistic for an offline application to wait for a long process (could take hours to write to online database), it should resolve the promise right away and then write to the database later when the client is back online

**Comment by Salakar** [comment] 2021-04-21 20:44
> @russellwheatley I don't agree with closing this. I think that is not realistic for an offline application to wait for a long process (could take hours to write to online database), it should resolve the promise right away and then write to the database later when the client is back online

This is best taken up with the official Firebase Android or iOS SDKs as all we do is wrap these SDKs - so if you don't agree with this behavior I'd report it there as there's nothing FlutterFire could do here, sorry

**Closed by Salakar** 2021-04-21 20:44 UTC
Labels: plugin: cloud_firestore, type: bug
