### ISSUE TITLE
🐛 [firebase_auth] 0.18.1+2 Cannot get Apple Sign in to work

### ISSUE THREAD

**Issue by LiveRock** [FirebaseExtended/flutterfire#3846] opened 2020-10-12 08:08 UTC
I follow the updated docs up to

return await FireBaseAuth.signInWithCredential(oauthCredential);

where it complained that 'signInWithCredential' is nor defined.

What am I doing wrong here?

**Comment by markusaksli-nc** [comment] 2020-10-12 12:45
Hi @LiveRock 
Can you please provide your `flutter doctor -v` and `flutter run -v` logs? It would also be helpful if you provided a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
Thank you

**Comment by LiveRock** [comment] 2020-10-14 04:55
`return await auth.signInWithCredential(oauthCredential);`

IDE flagged the above error because **signInWithCredential** is not found.
auth is Firebase_Auth object

flutter doctor -v
[✓] Flutter (Channel stable, 1.20.2, on Mac OS X 10.15.7 19H2, locale en-SG)
    • Flutter version 1.20.2 at /Users/peterlum/dev/flutter
    • Framework revision bbfbf1770c (9 weeks ago), 2020-08-13 08:33:09 -0700
    • Engine revision 9d5b21729f
    • Dart version 2.9.1

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
    • Android SDK at /Applications/AndroidDev/sdk
    • Platform android-30, build-tools 30.0.1
    • ANDROID_HOME = /Applications/AndroidDev/sdk
    • ANDROID_SDK_ROOT = /Applications/AndroidDev/sdk
    • Java binary at: /Applications/Android Studio 3.3.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.1

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio 3.3.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[!] Android Studio (version 2.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin version 12.1 - the recommended minimum version is 16.0.0
    • Dart plugin version 162.2924
    • Java version OpenJDK Runtime Environment (build 1.8.0_112-release-b06)

[✓] VS Code (version 1.50.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.15.0

[!] Connected device
    ! No devices available

! Doctor found issues in 2 categories.

**Comment by markusaksli-nc** [comment] 2020-10-14 06:38
I'm not seeing this with just
```dart
import 'package:firebase_auth/firebase_auth.dart';

void main() => FirebaseAuth.instance
    .signInWithCredential(AuthCredential(signInMethod: '', providerId: ''));
```
If it's just an analysis error you could try `File -> Invalidate Caches / Restart -> Invalidate and Restart` (Android Studio). If it's purely dart analysis (shows up in `flutter analyze`) you could try `pub cache repair`.

In any case I'm going to close this for now since it isn't an issue with the package itself. Let me know if this doesn't work.

**Closed by markusaksli-nc** 2020-10-14 06:38 UTC
Labels: Needs Attention, type: bug
