### ISSUE TITLE
[Cloud_Firestore] <CloudFirestorePlugin.java uses unchecked or unsafe operations.>

### ISSUE THREAD

**Issue by salaheddinelhamraoui** [FirebaseExtended/flutterfire#2545] opened 2020-05-13 06:09 UTC
I'm trying to integrate cloud firestore to an android app but all I get is this error every single time

```
Note: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\cloud_firestore-0.13.5\android\src\main\java\io\flutter\plugins\firebase\cloudfirestore\CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by TahaTesser** [comment] 2020-05-13 12:17
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1401

**Closed by TahaTesser** 2020-05-13 12:17 UTC
