### ISSUE TITLE
🐛 [Firebase_auth] Firebase Auth User signs out after manual page reload 

### ISSUE THREAD

**Issue by hemanthkb97** [FirebaseExtended/flutterfire#5072] opened 2021-02-18 06:50 UTC
```
Launching lib\main.dart on Chrome in debug mode...
 lib\main.dart
Debug service listening on ws://127.0.0.1:3579/1-Lv2nF5VyE=/ws
Running with unsound null safety
For more information see https://dart.dev/null-safety/unsound-null-safety
Connecting to VM Service at ws://127.0.0.1:3579/1-Lv2nF5VyE=/ws
ikmhemanthkumar@gmail.com
ikmhemanthkumar@gmail.com
TypeError: Cannot read property 'email' of null
    at Dashboard._DashBoardState.new._getuserandothersdetails (http://localhost:3529/packages/safehandsfordoc/navpages/homenavpages/Dashboard.dart.lib.js:2701:30)
    at _getuserandothersdetails.next (<anonymous>)
    at runBody (http://localhost:3529/dart_sdk.js:39177:34)
    at Object._async [as async] (http://localhost:3529/dart_sdk.js:39208:7)
    at Dashboard._DashBoardState.new.[_getuserandothersdetails] (http://localhost:3529/packages/safehandsfordoc/navpages/homenavpages/Dashboard.dart.lib.js:2699:20)
    at http://localhost:3529/packages/safehandsfordoc/navpages/homenavpages/Dashboard.dart.lib.js:2669:39
    at binding$5.WidgetsFlutterBinding.new.[_invokeFrameCallback] (http://localhost:3529/packages/flutter/src/scheduler/binding.dart.lib.js:776:9)
    at binding$5.WidgetsFlutterBinding.new.handleDrawFrame (http://localhost:3529/packages/flutter/src/scheduler/binding.dart.lib.js:749:37)
    at http://localhost:3529/packages/flutter/src/scheduler/binding.dart.lib.js:653:14
    at internalCallback (http://localhost:3529/dart_sdk.js:25238:11)
```

**Describe the bug**
When i reload a page in browser i get this error, i even tried to use firebase_auth_web didt help

### Steps to reproduce

1. Login
2. Reload  page after u login
4. See error or incorrect behavior

### Flutter doctor

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel dev, 1.27.0-1.0.pre, on Microsoft Windows [Version 10.0.19042.804], locale en-IN)
• Flutter version 1.27.0-1.0.pre at D:\flutter
• Framework revision 68c96f1 (9 days ago), 2021-02-08 16:14:15 -0800
• Engine revision b049556
• Dart version 2.13.0 (build 2.13.0-0.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
• Android SDK at C:\Users\Hemanth\AppData\Local\Android\sdk
• Platform android-30, build-tools 30.0.2
• Java binary at: D:\Andriod studio\jre\bin\java
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
• All Android licenses accepted.

[√] Chrome - develop for the web
• Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
• Android Studio at D:\Andriod studio
• Flutter plugin can be installed from:
https://plugins.jetbrains.com/plugin/9212-flutter
• Dart plugin can be installed from:
https://plugins.jetbrains.com/plugin/6351-dart
• Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.53.2)
• VS Code at C:\Users\Hemanth\AppData\Local\Programs\Microsoft VS Code
• Flutter extension version 3.19.0

[√] Connected device (2 available)
• Chrome (web) • chrome • web-javascript • Google Chrome 86.0.4240.198
• Edge (web) • edge • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.0-0.0.dev   
Flutter SDK 1.27.0-1.0.pre
safehandsfordoc 1.0.0+1

dependencies:
- cloud_firestore 0.16.0 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cupertino_icons 1.0.2
- dio 3.0.10 [http_parser path]
- dropdown_search 0.4.8 [flutter geolocator]
- firebase_auth 0.20.0+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_auth_web 0.3.2+6 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_storage 7.0.0 [flutter firebase_core firebase_core_platform_interface firebase_storage_web firebase_storage_platform_interface quiver]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_layout_grid 0.11.3 [collection flutter meta quiver]
- google_fonts 1.1.2 [flutter http path_provider crypto]
- google_maps_webservice 0.0.19 [http meta]
- horizontal_data_table 2.2.0 [flutter provider]
- http 0.12.2 [http_parser path pedantic]
- intl 0.16.1 [path]
- liquid_progress_indicator 0.3.2 [flutter]
- mobile_sidebar 2.0.1 [flutter auto_size_text]
- ntp 1.0.8 [universal_io]
- overlay_support 1.0.5 [flutter async]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows] 
- strings 0.1.4 [characters unicode]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- auto_size_text 2.1.0 [flutter]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 3.0.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+1 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- equatable 1.2.5 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 3.0.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_storage_platform_interface 1.0.4 [flutter meta collection firebase_core plugin_platform_interface]
- firebase_storage_web 0.1.1+3 [async crypto firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- geolocator 5.3.2+2 [flutter meta equatable google_api_availability location_permissions vector_math]
- google_api_availability 2.0.4 [flutter]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- lists 0.1.6
- location_permissions 3.0.0+1 [flutter meta]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 0.0.4 [flutter]
- path 1.8.0
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- provider 4.3.3 [collection flutter nested]
- quiver 2.1.5 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- unicode 0.2.4 [lists]
- universal_io 1.0.2 [crypto meta zone_local]
- vector_math 2.1.0
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- zone_local 0.1.2
```

</details>

---
####Login Page Code
<details><summary>Click To Expand</summary>

```dart
import 'package:flutter/foundation.dart';
import 'package:overlay_support/overlay_support.dart';
import 'package:flutter/material.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/services.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:firebase_auth/firebase_auth.dart';

class LoginPage extends StatefulWidget {
  LoginPage({Key key, this.title}) : super(key: key);

  final String title;
  @override
  _LoginPageState createState() => _LoginPageState();
}

class _LoginPageState extends State<LoginPage> {
  bool loading = false;
  bool enable = true;
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  String email = "", password = "";
  bool _obscureText = true;
  void togelpass() {
    setState(() {
      _obscureText = !_obscureText;
      print(_obscureText);
    });
  }

  Widget _backButton() {
    --
    --
    --
  }

  Widget _divider() {
    --
    --
    --
  }

  Widget _createAccountLabel() {
    return InkWell(
     --
    --
    --
  }

  @override
  Widget build(BuildContext context) {
    var height = MediaQuery.of(context).size.height;
    --
    --
    --
  }

  void _onFormSubmitted() async {
    FirebaseAuth _auth = FirebaseAuth.instance;
    try {
      final UserCredential userCredential =
          await _auth.signInWithEmailAndPassword(
        email: email,
        password: password,
      );
      final User user = userCredential.user;
      if (user != null) {
        if (user.emailVerified) {
          Navigator.pushNamedAndRemoveUntil(context, '/home', (route) => false,
              arguments: user);
        } else {
          setState(() {
            enable = true;
            loading = false;
          });
          showDialog(
            context: context,
            builder: (context) {
              return AlertDialog(
                title: Text("Please Verify E-mail"),
                content: Text("Re-send E-mail Verification?"),
                actions: [
                  TextButton(
                      onPressed: () {
                        Navigator.of(context).pop();
                      },
                      child: Text("Cancel")),
                  TextButton(
                      onPressed: () {
                        user.sendEmailVerification().whenComplete(() =>
                            showSimpleNotification(
                                Text("Email Verification sent"),
                                background: Colors.red,
                                autoDismiss: true,
                                duration: Duration(seconds: 2),
                                position: NotificationPosition.top));
                      },
                      child: Text("Send"))
                ],
              );
            },
          );
        }
      }
    } catch (exception) {
      setState(() {
        enable = true;
        loading = false;
      });
      if (exception.code == "invalid-email") {
        showSimpleNotification(Text("Invalid Email"),
            background: Colors.red,
            autoDismiss: true,
            duration: Duration(seconds: 2),
            position: NotificationPosition.top);
      } else if (exception.code == "user-not-found") {
        showSimpleNotification(Text("User Not Found"),
            background: Colors.red,
            autoDismiss: true,
            duration: Duration(seconds: 2),
            position: NotificationPosition.top);
      } else if (exception.code == "wrong-password") {
        showSimpleNotification(Text("Wrong Password"),
            background: Colors.red,
            autoDismiss: true,
            duration: Duration(seconds: 2),
            position: NotificationPosition.top);
      }
    }
  }
}
</details>

###after login code
<details><summary>Click To Expand</summary>

@override
  void initState() {
    if (mounted)
      setState(() {
        _timeString = _formatDateTime(DateTime.now());
      });
    _getindex();
    _timer = Timer.periodic(
        Duration(seconds: 1),
        (Timer t) => {
              _getTime(),
            });
    WidgetsBinding.instance.addPostFrameCallback((_) {
      _getuserandothersdetails();
    });

    super.initState();
  }

void _getuserandothersdetails() async {
    user = FirebaseAuth.instance.currentUser;
    print(user.email);
    if (user == null) {
      user = await FirebaseAuth.instance.authStateChanges().first;
      inspect(user);
      if (user == null)
        Navigator.pushNamedAndRemoveUntil(
            context, '/welcome', (route) => false);
      else
        print(user.uid);
    }
}
```
</details>

**Comment by markusaksli-nc** [comment] 2021-02-18 09:50
Hi @hemanthkb97 
Could you try this with the official example? I'm not seeing this behavior using the official example with 
```yaml
  firebase_auth: ^0.20.0+1
  firebase_core: ^0.7.0
  google_sign_in: ^4.5.9
  firebase_dynamic_links: ^0.7.0+1
  flutter_signin_button: ^1.1.0
```
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 1.27.0-5.0.pre.48, on Microsoft Windows [Version 10.0.19041.804], locale et-EE)
    • Flutter version 1.27.0-5.0.pre.48 at C:\Development\flutter_master
    • Framework revision 86d6d17a4f (66 minutes ago), 2021-02-18 14:11:03 +0530
    • Engine revision 6993cb229b
    • Dart version 2.13.0 (build 2.13.0-30.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2020.3)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\203.7148.57
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.19041.804]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 88.0.4324.150
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 88.0.705.68

• No issues found!
```
</details>

Thank you

**Comment by hemanthkb97** [comment] 2021-02-18 10:17
@markusaksli-nc 
okay i created new project without any 3rd party plugins and still same problem when i refresh web page current user is null

### code
<details><summary>Click To Expand</summary>
import 'package:firebase_auth/firebase_auth.dart'; import 'package:firebase_core/firebase_core.dart'; import 'package:flutter/material.dart';
FirebaseAuth _auth = FirebaseAuth.instance;
Future main() async {
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();
runApp(MyApp());
}

class MyApp extends StatelessWidget {
@override
Widget build(BuildContext context) {
return MaterialApp(
title: 'Flutter Demo',
theme: ThemeData(
// This is the theme of your application.
//
// Try running your application with "flutter run". You'll see the
// application has a blue toolbar. Then, without quitting the app, try
// changing the primarySwatch below to Colors.green and then invoke
// "hot reload" (press "r" in the console where you ran "flutter run",
// or simply save your changes to "hot reload" in a Flutter IDE).
// Notice that the counter didn't reset back to zero; the application
// is not restarted.
primarySwatch: Colors.blue,
),
home: MyHomePage(title: 'Flutter Demo Home Page'),
);
}
}

class MyHomePage extends StatefulWidget {
MyHomePage({Key key, this.title}) : super(key: key);

final String title;

@override
_MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State {
String email, pass;

@override
void initState() {
checkuser();
super.initState();
}

@override
Widget build(BuildContext context) {
return Scaffold(
body: Container(
width: 500,
height: 300,
child: Column(
children: [
TextField(
onChanged: (value) {
email = value;
},
),
TextField(
onChanged: (value) {
pass = value;
},
onSubmitted: (value) {
singin(email, pass);
},
)
],
),
),
);
}

void singin(email, pass) {
_auth.signInWithEmailAndPassword(email: email, password: pass);
if (_auth.currentUser != null) {
print(_auth.currentUser.email);
}
}

void checkuser() {
if (_auth.currentUser != null) {
print(_auth.currentUser.email);
} else {
print("no user");
}
}
}

</details>

### pubspec

`name: safehands_doctors
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^0.7.0
  firebase_auth: ^0.20.0+1
  cloud_firestore: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
`

**Comment by markusaksli-nc** [comment] 2021-02-18 10:42
The currentUser is only null at first, if you check it after `initState` (such as with a button) it will not be null.

This is a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4326

**Closed by markusaksli-nc** 2021-02-18 10:42 UTC
Labels: Needs Attention, type: bug

**Comment by hemanthkb97** [comment] 2021-02-18 10:57
@markusaksli-nc 
can you please tell me what is the correct way to get current user I'm newbie, if not initstate then how should i check

**Comment by markusaksli-nc** [comment] 2021-02-18 11:04
This is an issue on web but It seems to work fine with the official example using https://github.com/FirebaseExtended/flutterfire/pull/4635

You can look at that for an example of how to use the `userChanges` stream to have a stream constantly update your user reference. This solutions seems to be a bit more robust than just using `currentUser` until this gets fixed for web.

Here is an example of how to use it in the minimal case you had before

<details>
 <summary>main.dart</summary>

```dart
import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';
import 'package:flutter_signin_button/flutter_signin_button.dart';

final FirebaseAuth _auth = FirebaseAuth.instance;
String linkEmail;

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(AuthExampleApp());
}

class AuthExampleApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        title: 'Firebase Example App',
        theme: ThemeData.dark(),
        home: SignInPage());
  }
}

class SignInPage extends StatefulWidget {
  final String title = 'Sign In & Out';

  @override
  State<StatefulWidget> createState() => _SignInPageState();
}

class _SignInPageState extends State<SignInPage> {
  User user;

  @override
  void initState() {
    _auth.userChanges().listen((event) => setState(() => user = event));
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
        actions: <Widget>[
          Builder(builder: (BuildContext context) {
            return FlatButton(
              child: const Text('Sign out'),
              textColor: Theme.of(context).buttonColor,
              onPressed: () async {
                final User user = await _auth.currentUser;
                if (user == null) {
                  Scaffold.of(context).showSnackBar(const SnackBar(
                    content: Text('No one has signed in.'),
                  ));
                  return;
                }
                _signOut();
                final String uid = user.uid;
                Scaffold.of(context).showSnackBar(SnackBar(
                  content: Text(uid + ' has successfully signed out.'),
                ));
              },
            );
          })
        ],
      ),
      body: Builder(builder: (BuildContext context) {
        return ListView(
          padding: EdgeInsets.all(8),
          scrollDirection: Axis.vertical,
          children: <Widget>[
            _UserInfoCard(user),
            _EmailPasswordForm(),
          ],
        );
      }),
    );
  }

  // Example code for sign out.
  void _signOut() async {
    await _auth.signOut();
  }
}

class _UserInfoCard extends StatefulWidget {
  final User user;

  const _UserInfoCard(this.user);

  @override
  _UserInfoCardState createState() => _UserInfoCardState();
}

class _UserInfoCardState extends State<_UserInfoCard> {
  @override
  Widget build(BuildContext context) {
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Container(
              child: const Text(
                "User info",
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
              padding: EdgeInsets.only(bottom: 8.0),
              alignment: Alignment.center,
            ),
            if (widget.user != null)
              if (widget.user.photoURL != null)
                Container(
                  child: Image.network(widget.user.photoURL),
                  alignment: Alignment.center,
                  margin: EdgeInsets.only(bottom: 8.0),
                )
              else
                Align(
                  alignment: Alignment.center,
                  child: Container(
                    child: Text(
                      "No image",
                      textAlign: TextAlign.center,
                    ),
                    padding: EdgeInsets.all(8.0),
                    margin: EdgeInsets.only(bottom: 8.0),
                    color: Colors.black,
                  ),
                ),
            Text(widget.user == null
                ? 'Not signed in'
                : '${widget.user.isAnonymous ? 'User is anonymous\n\n' : ''}'
                'Email: ${widget.user.email} (verified: ${widget.user.emailVerified})\n\n'
                'Phone number: ${widget.user.phoneNumber}\n\n'
                'Name: ${widget.user.displayName}\n\n\n'
                'ID: ${widget.user.uid}\n\n'
                'Tenant ID: ${widget.user.tenantId}\n\n'
                'Refresh token: ${widget.user.refreshToken}\n\n\n'
                'Created: ${widget.user.metadata.creationTime.toString()}\n\n'
                'Last login: ${widget.user.metadata.lastSignInTime}\n\n'),
            if (widget.user != null)
              Column(
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  Text(
                    widget.user.providerData.isEmpty
                        ? 'No providers'
                        : 'Providers:',
                    style: TextStyle(fontWeight: FontWeight.bold),
                    textAlign: TextAlign.center,
                  ),
                  for (var provider in widget.user.providerData)
                    Dismissible(
                      key: Key(provider.uid),
                      child: Card(
                        color: Colors.grey[700],
                        child: ListTile(
                          leading: provider.photoURL == null
                              ? IconButton(
                              icon: const Icon(Icons.remove),
                              onPressed: () =>
                                  widget.user.unlink(provider.providerId))
                              : Image.network(provider.photoURL),
                          title: Text(provider.providerId),
                          subtitle: Text(
                              "${provider.uid == null ? "" : "ID: ${provider.uid}\n"}"
                                  "${provider.email == null ? "" : "Email: ${provider.email}\n"}"
                                  "${provider.phoneNumber == null ? "" : "Phone number: ${provider.phoneNumber}\n"}"
                                  "${provider.displayName == null ? "" : "Name: ${provider.displayName}\n"}"),
                        ),
                      ),
                      onDismissed: (action) =>
                          widget.user.unlink(provider.providerId),
                    ),
                ],
              ),
            Visibility(
              visible: widget.user != null,
              child: Container(
                margin: EdgeInsets.only(top: 8.0),
                alignment: Alignment.center,
                child: Row(
                  mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                  children: [
                    IconButton(
                      onPressed: () => widget.user.reload(),
                      icon: const Icon(Icons.refresh),
                    ),
                    IconButton(
                      onPressed: () => showDialog(
                        context: context,
                        builder: (context) => UpdateUserDialog(widget.user),
                      ),
                      icon: const Icon(Icons.text_snippet),
                    ),
                    IconButton(
                      onPressed: () => widget.user.delete(),
                      icon: const Icon(Icons.delete_forever),
                    ),
                  ],
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class UpdateUserDialog extends StatefulWidget {
  final User user;

  const UpdateUserDialog(this.user);

  @override
  _UpdateUserDialogState createState() => _UpdateUserDialogState();
}

class _UpdateUserDialogState extends State<UpdateUserDialog> {
  TextEditingController _nameController;
  TextEditingController _urlController;

  @override
  void initState() {
    _nameController = TextEditingController(text: widget.user.displayName);
    _urlController = TextEditingController(text: widget.user.photoURL);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return AlertDialog(
      title: const Text("Update profile"),
      content: SingleChildScrollView(
        child: ListBody(
          children: [
            TextFormField(
              controller: _nameController,
              autocorrect: false,
              decoration: const InputDecoration(labelText: 'displayName'),
            ),
            TextFormField(
              controller: _urlController,
              decoration: const InputDecoration(labelText: 'photoURL'),
              autovalidateMode: AutovalidateMode.onUserInteraction,
              autocorrect: false,
              validator: (String value) {
                if (value.isNotEmpty) {
                  var uri = Uri.parse(value);
                  if (uri.isAbsolute) {
                    //You can get the data with dart:io or http and check it here
                    return null;
                  }
                  return "Faulty URL!";
                }
                return null;
              },
            ),
          ],
        ),
      ),
      actions: [
        TextButton(
          onPressed: () {
            widget.user.updateProfile(
                displayName: _nameController.text,
                photoURL: _urlController.text);
            Navigator.of(context).pop();
          },
          child: const Text("Update"),
        )
      ],
    );
  }

  @override
  void dispose() {
    _nameController.dispose();
    _urlController.dispose();
    super.dispose();
  }
}

class _EmailPasswordForm extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => _EmailPasswordFormState();
}

class _EmailPasswordFormState extends State<_EmailPasswordForm> {
  final GlobalKey<FormState> _formKey = GlobalKey<FormState>();
  final TextEditingController _emailController = TextEditingController();
  final TextEditingController _passwordController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    return Form(
        key: _formKey,
        child: Card(
          child: Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Container(
                  child: const Text(
                    'Sign in with email and password',
                    style: TextStyle(fontWeight: FontWeight.bold),
                  ),
                  alignment: Alignment.center,
                ),
                TextFormField(
                  controller: _emailController,
                  decoration: const InputDecoration(labelText: 'Email'),
                  validator: (String value) {
                    if (value.isEmpty) return 'Please enter some text';
                    return null;
                  },
                ),
                TextFormField(
                  controller: _passwordController,
                  decoration: const InputDecoration(labelText: 'Password'),
                  validator: (String value) {
                    if (value.isEmpty) return 'Please enter some text';
                    return null;
                  },
                  obscureText: true,
                ),
                Container(
                  padding: const EdgeInsets.only(top: 16.0),
                  alignment: Alignment.center,
                  child: SignInButton(
                    Buttons.Email,
                    text: "Sign In",
                    onPressed: () async {
                      if (_formKey.currentState.validate()) {
                        _signInWithEmailAndPassword();
                      }
                    },
                  ),
                ),
              ],
            ),
          ),
        ));
  }

  @override
  void dispose() {
    _emailController.dispose();
    _passwordController.dispose();
    super.dispose();
  }

  // Example code of how to sign in with email and password.
  void _signInWithEmailAndPassword() async {
    try {
      final User user = (await _auth.signInWithEmailAndPassword(
        email: _emailController.text,
        password: _passwordController.text,
      ))
          .user;

      Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("${user.email} signed in"),
      ));
    } catch (e) {
      Scaffold.of(context).showSnackBar(SnackBar(
        content: Text("Failed to sign in with Email & Password"),
      ));
    }
  }
}
```
</details>

**Comment by hemanthkb97** [comment] 2021-02-18 11:26
> This is an issue on web but It seems to work fine with the official example using #4635
> 
> You can look at that for an example of how to use the `userChanges` stream to have a stream constantly update your user reference. This solutions seems to be a bit more robust than just using `currentUser` until this gets fixed for web.
> 
> Here is an example of how to use it in the minimal case you had before
> 
> main.dart

Thank you so much :) 🥇 got it
