### ISSUE TITLE
[CLOUD_FIRESTORE_WEB] dart.global.firebase.firestore is not a function

### ISSUE THREAD

**Issue by Ahmadre** [FirebaseExtended/flutterfire#2805] opened 2020-06-20 18:21 UTC
**Describe the bug**
Can't open Flutter web app, because cloud_firestore_web is not working.

**To Reproduce**
1. Create a plain flutter web project.
2. Enable web
3. Add: cloud_firestore to your pubspec.yaml
4. Execute/Use Firestore and fetch a sample collection
5. Flutter web won't even show up.

**Note:** Of course I already initialized firebase like shown on Firebase Console.

**Expected behavior**
Flutter Web App is started properly.

**Actual context**
```bash
TypeError: dart.global.firebase.firestore is not a function
    at Object.firestore$ [as firestore] (http://localhost:57131/packages/firebase/src/top_level.dart.lib.js:94:55)
    at new cloud_firestore_web.FirestoreWeb.new (http://localhost:57131/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:802:37)
    at Function.registerWith (http://localhost:57131/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:747:71)
    at Object.registerPlugins (http://localhost:57131/packages/garage/generated_plugin_registrant.dart.lib.js:13:38)
    at main$ (http://localhost:57131/web_entrypoint.dart.lib.js:15:35)
    at main$.next (<anonymous>)
    at runBody (http://localhost:57131/dart_sdk.js:37195:34)
    at Object._async [as async] (http://localhost:57131/dart_sdk.js:37226:7)
    at main$ (http://localhost:57131/web_entrypoint.dart.lib.js:14:18)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:57131/dwds/src/injected/client.js:8451:15)
    at http://localhost:57131/dwds/src/injected/client.js:22495:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:57131/dwds/src/injected/client.js:3744:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:57131/dwds/src/injected/client.js:10956:12)
    at Object._asyncStartSync (http://localhost:57131/dwds/src/injected/client.js:3708:20)
    at main__closure1.$call$body$main__closure (http://localhost:57131/dwds/src/injected/client.js:22507:16)
    at main__closure1.call$1 (http://localhost:57131/dwds/src/injected/client.js:22439:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:57131/dwds/src/injected/client.js:4066:16)
    at _CustomZone.runUnary$2$2 (http://localhost:57131/dwds/src/injected/client.js:12275:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:57131/dwds/src/injected/client.js:12203:14)
    at _ControllerSubscription._sendData$1 (http://localhost:57131/dwds/src/injected/client.js:11753:19)
    at _DelayedData.perform$1 (http://localhost:57131/dwds/src/injected/client.js:11907:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:57131/dwds/src/injected/client.js:11956:14)
    at Object._microtaskLoop (http://localhost:57131/dwds/src/injected/client.js:3909:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:57131/dwds/src/injected/client.js:3915:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:57131/dwds/src/injected/client.js:10828:9)
    at invokeClosure (http://localhost:57131/dwds/src/injected/client.js:1172:26)
```

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.18362.900], locale de-DE)
    • Flutter version 1.19.0-4.1.pre at C:\Users\rebar\Documents\flutter
    • Framework revision f994b76974 (11 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\rebar\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[!] Android Studio (version 4.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.46.1)
    • VS Code at C:\Users\rebar\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (3 available)
    • Pixel 2 XL • 801KPXV1385746 • android-arm64  • Android 10 (API 29)
    • Web Server • web-server     • web-javascript • Flutter Tools
    • Chrome     • chrome         • web-javascript • Google Chrome 83.0.4103.106

! Doctor found issues in 1 category.
```

**Comment by Ahmadre** [comment] 2020-06-21 18:22
cc @ditman

**Comment by TahaTesser** [comment] 2020-06-22 12:13
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2682

**Closed by TahaTesser** 2020-06-22 12:13 UTC
