### ISSUE TITLE
firebase_auth Missing implementation of "fetchSignInMethodsForEmail" on Flutter web

### ISSUE THREAD

**Issue by fearlessambassador** [FirebaseExtended/flutterfire#2641] opened 2020-05-26 20:11 UTC
**Describe the bug**
When calling
```
List<String> signInMethods =  await FirebaseAuth.instance.fetchSignInMethodsForEmail(email: googleSignInAccount.email);
```
An UnImplemented exception is raised:
```
Uncaught UnimplementedError: fetchSignInMethodsForEmail
    at Object.f (https://dev.taxhelper.dk/main.dart.js:2110:3)
    at EE.I9 (https://dev.taxhelper.dk/main.dart.js:32602:28)
    at https://dev.taxhelper.dk/main.dart.js:58784:19
    at ajT.a (https://dev.taxhelper.dk/main.dart.js:3510:71)
    at ajT.$2 (https://dev.taxhelper.dk/main.dart.js:27142:23)
    at aj2.$1 (https://dev.taxhelper.dk/main.dart.js:27134:30)
    at Od.zU (https://dev.taxhelper.dk/main.dart.js:28202:40)
    at Od.jJ (https://dev.taxhelper.dk/main.dart.js:28204:30)
    at a8K.$0 (https://dev.taxhelper.dk/main.dart.js:27555:13)
    at Object.rr (https://dev.taxhelper.dk/main.dart.js:3628:42)
```

**To Reproduce**
Below is a complete example of the class and the method throwing the exception.
```
import 'package:firebase_auth/firebase_auth.dart';
import 'package:google_sign_in/google_sign_in.dart';
import 'package:taxice_web/analytics/trackingUtils.dart';
import 'package:taxice_web/data/userUtils.dart';

class SignInService {
  final FirebaseAuth _firebaseAuth;
  final GoogleSignIn _googleSignIn;

  SignInService({FirebaseAuth firebaseAuth, GoogleSignIn googleSignIn, dynamic context})
    :   _firebaseAuth = firebaseAuth ?? FirebaseAuth.instance,
        _googleSignIn = googleSignIn ?? GoogleSignIn();

  Future<FirebaseUser> signInWithGoogle() async {
    final GoogleSignInAccount googleSignInAccount = await _googleSignIn.signIn();
    List<String> signInMethods =  await _firebaseAuth.fetchSignInMethodsForEmail(email: googleSignInAccount.email);
    if (signInMethods.length > 0) {
      final GoogleSignInAuthentication googleSignInAuthentication = await googleSignInAccount.authentication;
      final AuthCredential credential = GoogleAuthProvider.getCredential(
        idToken: googleSignInAuthentication.idToken,
        accessToken: googleSignInAuthentication.accessToken
      );
      final AuthResult result = await _firebaseAuth.signInWithCredential(credential);
      logEvent("google_sign_in");
      return result.user;
    } else {
      return null;
    }
  }
}
```

**Expected behavior**
According to the documentation it should return a List of available Sign In methods for a given email. Since other Firebase methods available outside the Flutter framework is unavailable I thought it was strange that it threw a UnImplemented Exception.

**Additional context**
In the method above I'm trying to determine if the user signing in with Google Sign In has previously signed up with the same email address or not.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.2 19C57, locale en-US)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✗] Xcode - develop for iOS and macOS
    ✗ Xcode installation is incomplete; a full installation is necessary for iOS development.
      Download at: https://developer.apple.com/xcode/download/
      Or install Xcode via the App Store.
      Once installed, run:
        sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer
        sudo xcodebuild -runFirstLaunch
    ✗ CocoaPods installed but not working.
        You appear to have CocoaPods installed but it is not working.
        This can happen if the version of Ruby that CocoaPods was installed with is different from the one being used to invoke it.
        This can usually be fixed by re-installing CocoaPods. For more info, see https://github.com/flutter/flutter/issues/14293.
      To re-install CocoaPods, run:
        sudo gem install cocoapods
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.45.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

**Comment by TahaTesser** [comment] 2020-05-27 14:37
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1682

**Comment by TahaTesser** [comment] 2020-05-27 14:48
<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (2 weeks ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.8052
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.2

[✓] Connected device (5 available)
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5
    • macOS         • macOS                     • darwin-x64     • Mac OS X
      10.15.4 19E287
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details>

**Comment by Ehesp** [comment] 2020-08-20 11:00
Support has landed for this in the latest release.

**Closed by Ehesp** 2020-08-20 11:00 UTC
Labels: platform: web, plugin: auth, type: bug
