### ISSUE TITLE
extreme long build time when adding cloud_firestore to pubspec.yaml

### ISSUE THREAD

**Issue by Dubwoof** [FirebaseExtended/flutterfire#1557] opened 2019-12-04 23:28 UTC
having issues with extreme long build time when adding cloud_firestore to pubspec.yaml.

what am i doing wrong?

**Comment by collinjackson** [comment] 2019-12-05 19:28
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/349

**Closed by collinjackson** 2019-12-05 19:28 UTC
