### ISSUE TITLE
Are localized messages available?

### ISSUE THREAD

**Issue by vinnytwice** [FirebaseExtended/flutterfire#2759] opened 2020-06-15 08:51 UTC
I have firebase_messaging working fine with `title` and `body` parameters, but as I have mixed languages communications I need to localize the messages in the receiver language. So I put the translations in a json file, and changed my sending methods to use `'title_loc_key'`, `'title_loc_args'`, `'body_loc_key'` and `'body_loc_args'`. Now received messages is still delivered to system tray but only shows app name. 

In the method I use to send a message, the commented out parameters for `notification:` will send a message in the sender language which works as expected, but where do I catch the `loc` parameters when receiving the message to assign translations? 

```
void sendBookingReceived(Booking booking) async {
    print('sendBookingReceived() started');
    var customerName = booking.customerName;
//    var bookingDate = DateTime.fromMillisecondsSinceEpoch(booking.bookingDate);
    var bookingStart = booking.bookingStart;
    var customerFCMToken = booking.customerFCMToken;

    await post('https://fcm.googleapis.com/fcm/send',
        headers: <String, String>{
          'Content-Type': 'application/json',
          'Authorization': 'key=$firebaseServerKey'
        },
        body: jsonEncode({
          'notification': <String, dynamic>{
            'title_loc_key': 'BOOKING_RECEIVED_PUSH_SUBTITLE',
            'title_loc_args': [booking.shopName],
            'body_loc_key': 'BOOKING_RECEIVED_PUSH_BODY',
            'body_loc_args': [
              customerName,
              '',
              bookingStart
            ], //, bookingDate, bookingStart]),
            'sound': 'true',
            'mutable_content': 'true',
            'content_available': 'true'
//            'title': sprintf(
//                AppLocalizations.instance
//                    .text('BOOKING_RECEIVED_PUSH_SUBTITLE'),
//                [booking.shopName]),
//            'body': sprintf(
//                AppLocalizations.instance.text('BOOKING_RECEIVED_PUSH_BODY'), [
//              customerName,
//              '',
//              bookingStart
//            ]), //, bookingDate, bookingStart]),
//            'sound': 'true'
          },
          'priority': 'high',
          'data': <String, dynamic>{
            'click_action': 'FLUTTER_NOTIFICATION_CLICK',
            'id': '1',
            'status': 'done'
          },
          'to': customerFCMToken
        })).whenComplete(() {
      print('sendBookingReceived(): message sent');
    }).catchError((e) {
      print('sendBookingReceived() error: $e');
    });
  }
```

**Comment by TahaTesser** [comment] 2020-06-15 13:50
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2436

**Closed by TahaTesser** 2020-06-15 13:50 UTC
