### ISSUE TITLE
[<FIREBASE_ADMOB>] Google Mobile Ads SDK was initialized incorrectly

### ISSUE THREAD

**Issue by nimai05** [FirebaseExtended/flutterfire#3329] opened 2020-08-24 21:25 UTC
**Describe the bug**
My app was working perfectly until the latest Flutter upgrade. Since then, firebase_admob said it depended on a previous version of firebase_core. I set admob to any version in the pubspec.yaml so it would run. However, it throws the aforementioned error. The app crashes immediately after displaying the splash screen.

**To Reproduce**

1. pubspec.yaml:

name: sorted
description: A new Flutter application.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  characters: ^1.0.0

  intl: ^0.16.1

  flutter_swiper : ^1.1.6

  firebase_core: ^0.5.0

  firebase_analytics: ^5.0.16

  firebase_auth: ^0.18.0+1

  cloud_firestore: ^0.14.0+2
  
  google_sign_in: ^4.5.1

  rxdart: ^0.24.1

  device_id: ^0.2.0

  firebase_admob: any

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  fonts:
    - family: Pacifico
      fonts:
        - asset: lib/assets/fonts/Pacifico-Regular.ttf
 
  uses-material-design: true

2. App-level build.gradle:

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'com.google.gms.google-services'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

android {
    compileSdkVersion 28

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
    }

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
       
        applicationId "com.<INSERT ID HERE>"
        minSdkVersion 23
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
    }

    buildTypes {
        release {
            signingConfig signingConfigs.debug
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'com.google.android.gms:play-services-ads:19.3.0'
}

apply plugin: 'com.google.gms.google-services'

3. AndroidManifest.XML:

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.nimainitai.sorted">
 
    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="sorted"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize">
            
            <meta-data
              android:name="io.flutter.embedding.android.NormalTheme"
              android:resource="@style/NormalTheme"
              />

    <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-<Insert app ID here>"/>

           

            <meta-data
              android:name="io.flutter.embedding.android.SplashScreenDrawable"
              android:resource="@drawable/launch_background"
              />

            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>

        </activity>
    
        <meta-data
            android:name="flutterEmbedding"
            android:value="2" />

    </application>
</manifest>

4. main.dart:

import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:sorted/screens/loginMain.dart'; 

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  runApp(LoginMain());
}

5. Run the app and see error.

**Expected behavior**
The login screen should open as it did earlier.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[√] Flutter (Channel stable, 1.20.2, on Microsoft Windows [Version 10.0.18363.1016], locale en-IN)
 
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.1)
[√] Android Studio (version 4.0)
[√] VS Code (version 1.48.1)
[√] Connected device (1 available)

• No issues found!
![Bug report](https://user-images.githubusercontent.com/31560361/91097749-e37ad580-e67d-11ea-94ec-195e2057e3ef.jpeg)

```

**Comment by Salakar** [comment] 2020-08-24 22:51
Duplicate of #3209.

**Closed by Salakar** 2020-08-24 22:51 UTC
