### ISSUE TITLE
Dart initialization not working when using FirebaseAuth and FirebaseMessaging together on real device.

### ISSUE THREAD

**Issue by sstakoff** [FirebaseExtended/flutterfire#8170] opened 2022-02-23 19:18 UTC
Some additional info. The error only occurs when running on a real device. Here is some context from my experience:

<details><summary>Console Log messages</summary>

2022-02-23 11:59:46.861192-0500 Runner[70126:84723762] Metal API Validation Enabled
2022-02-23 11:59:47.063866-0500 Runner[70126:84723999] 8.11.0 - [Firebase/Core][I-COR000012] Could not locate configuration file: 'GoogleService-Info.plist'.
2022-02-23 11:59:47.214326-0500 Runner[70126:84723762] <Warning>: Please set a value for FacebookAutoLogAppEventsEnabled. Set the flag to TRUE if you want to collect app install, app launch and in-app purchase events automatically. To request user consent before collecting data, set the flag value to FALSE, then change to TRUE once user consent is received. Learn more: https://developers.facebook.com/docs/app-events/getting-started-app-events-ios#disable-auto-events.
2022-02-23 11:59:47.214379-0500 Runner[70126:84723762] <Warning>: You haven't set a value for FacebookAdvertiserIDCollectionEnabled. Set the flag to TRUE if you want to collect Advertiser ID for better advertising and analytics results.
2022-02-23 11:59:47.217694-0500 Runner[70126:84724032] flutter: Observatory listening on http://127.0.0.1:54307/Aiipqazh3ak=/
2022-02-23 11:59:47.230417-0500 Runner[70126:84723762] FBSDKLog: Missing [FBSDKAppEvents appID] for [FBSDKAppEvents publishInstall:]
2022-02-23 11:59:47.448249-0500 Runner[70126:84723762] [VERBOSE-2:FlutterObservatoryPublisher.mm(101)] Failed to register observatory port with mDNS with error -65555.
2022-02-23 11:59:47.448295-0500 Runner[70126:84723762] [VERBOSE-2:FlutterObservatoryPublisher.mm(103)] On iOS 14+, local network broadcast in apps need to be declared in the app's Info.plist. Debug and profile Flutter apps and modules host VM services on the local network to support debugging features such as hot reload and DevTools. To make your Flutter app or module attachable and debuggable, add a '_dartobservatory._tcp' value to the 'NSBonjourServices' key in your Info.plist for the Debug/Profile configurations. For more information, see https://flutter.dev/docs/development/add-to-app/ios/project-setup#local-network-privacy-permissions
2022-02-23 11:59:47.448404-0500 Runner[70126:84723762] FBSDKLog: Missing [FBSDKAppEvents appEventsState.appID] for [FBSDKAppEvents flushOnMainQueue:]
2022-02-23 11:59:47.448431-0500 Runner[70126:84723762] FBSDKLog: Missing [FBSDKAppEvents appEventsState.appID] for [FBSDKAppEvents flushOnMainQueue:]
2022-02-23 11:59:47.456331-0500 Runner[70126:84723762] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The default FirebaseApp instance must be configured before the default Authinstance can be initialized. One way to ensure this is to call `FirebaseApp.configure()` in the App Delegate's `application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI).'
*** First throw call stack:
(0x1a436e708 0x1b8e787a8 0x1a42637a0 0x101025b84 0x1000d7d90 0x1050f8c98 0x1a6d85028 0x1074500b4 0x107451de0 0x1074620a8 0x1a42e8340 0x1a42e2218 0x1a42e1308 0x1bb964734 0x1a6d5f75c 0x1a6d64fcc 0x100008638 0x1a3f9dcf8)
libc++abi: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'The default FirebaseApp instance must be configured before the default Authinstance can be initialized. One way to ensure this is to call `FirebaseApp.configure()` in the App Delegate's `application(_:didFinishLaunchingWithOptions:)` (or the `@main` struct's initializer in SwiftUI).'
terminating with uncaught exception of type NSException
(lldb) </details>

<details><summary>flutter doctor -v</summary>
[✓] Flutter (Channel stable, 2.10.2, on macOS 11.6.1 20G224 darwin-x64, locale en)
    • Flutter version 2.10.2 at /Users/sstakoff/dev/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 097d3313d8 (5 days ago), 2022-02-18 19:33:08 -0600
    • Engine revision a83ed0e5e3
    • Dart version 2.16.1
    • DevTools version 2.9.2

[✓] Android toolchain - develop for Android devices (Android SDK version 32.0.0)
    • Android SDK at /Users/sstakoff/Library/Android/sdk
    • Platform android-32, build-tools 32.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7590822)

[✓] VS Code (version 1.63.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (2 available)
    • iPhone 13 (mobile)    • 452E84A5-5DC5-449B-B5C9-FB7B21008BB6 • ios            • com.apple.CoreSimulator.SimRuntime.iOS-15-2 (simulator)
    • Chrome (web)          • chrome                               • web-javascript • Google Chrome 98.0.4758.102

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
</details>

<details><summary>Dependencies from pubspec.yaml</summary>
  cupertino_icons: ^1.0.2

  firebase: ^9.0.2
  firebase_core: ^1.12.0
  firebase_database: ^9.0.6
  firebase_auth: ^3.3.7
  syncfusion_flutter_core: ^19.4.42
  syncfusion_flutter_calendar: ^19.4.43
  cloud_functions: ^3.2.7
  modal_progress_hud_nsn: ^0.1.0-nullsafety-1
  syncfusion_flutter_datepicker: ^19.4.43
  swipe_image_gallery: ^0.0.5
  cached_network_image: ^3.2.0
  url_launcher: ^6.0.18
  filter_list: ^1.0.1
  firebase_messaging: ^11.2.6
  flutterfire_ui: ^0.3.4
  shared_preferences: ^2.0.13
  icon_badge: ^1.0.0
  flutter_app_badger: ^1.3.0
  provider: ^6.0.2
  firebase_analytics: ^9.1.0

</details>

_Originally posted by @sstakoff in https://github.com/FirebaseExtended/flutterfire/issues/8119#issuecomment-1049015768_

**Comment by sstakoff** [comment] 2022-02-23 19:30
I was looking through some of the framework code and came across these 2 interesting comments:

```
/// The default app instance cannot be initialized here and should be created
/// using the platform Firebase integration.
  static Future<FirebaseApp> initializeApp({
```

This is odd since I call this code in main() as follows:
```
await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
```
which I believe is in fact attempting to initialize the default app?????

I also noticed this in the FirebaseMessaging code:

```
  //  Messaging does not yet support multiple Firebase Apps. Default app only.
  /// Returns an instance using a specified [FirebaseApp].
  factory FirebaseMessaging._instanceFor({required FirebaseApp app}) {
    return _firebaseMessagingInstances.putIfAbsent(app.name, () {
      return FirebaseMessaging._(app: app);
    });
```

which makes reference to the fact that Messaging is currently ONLY supported using the default app. So is it possible that in my call to initializeApp, I am NOT actually initializing the default app - causing an issue with messaging? And then messaging uses the info in GoogleService-Info.plist as the default app config that it need???? Just a theory :)

**Comment by anthonyhunter** [comment] 2022-02-24 22:29
@sstakoff see #7983 for potential workaround

**Comment by sstakoff** [comment] 2022-02-24 22:35
> @sstakoff see #7983 for potential workaround

Thank you! I will def try this out... Much appreciated

**Comment by darshankawar** [comment] 2022-02-28 11:56
Closing this as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/7983

**Closed by darshankawar** 2022-02-28 11:56 UTC
Labels: in triage
