### ISSUE TITLE
🐛 [firebase_messaging] Background message handler stops working when app is in background / terminated AND device is locked.

### ISSUE THREAD

**Issue by tanvish99** [FirebaseExtended/flutterfire#4369] opened 2020-12-10 10:36 UTC
## Bug report

The background message handler works as expected when the app is in the background or killed provided the screen is unlocked. As soon as the screen is locked(app in background or killed) the background message handler works fine for almost 3 - 5 min but then it stops working. As soon as the screen is unlocked it starts working again. This is seen in the example of firebase messaging and also in my app. I tested it on Android 9 and Android 10 on LG G8X and Moto g8 plus. Due to this, we cannot use the background message handler in production.

### Steps to reproduce

1. Raise local notifications in the background message handler
2. Try with app killed or in the background with the screen locked

### Expected behavior

The background message handler should work even when the screen is locked.
---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary></summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.4, on Linux, locale en_IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Android Studio (version 4.0)
[✓] Android Studio (version 3.6)
[!] VS Code (version 1.50.0)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[✓] Connected device (1 available)

! Doctor found issues in 1 category```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.4

- cloud_firestore 0.14.3+1 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- firebase_auth 0.18.3+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.2+1 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_messaging 8.0.0-dev.9 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface]
```

</details>

---

**Comment by tanvish99** [comment] 2020-12-11 12:54
No, in my case the background message handler works when the app is killed and is in background, only when it is locked after 4 to 5 min it stops.

**Comment by danielgchap** [comment] 2020-12-14 06:32
Implemented as the pub readme instructed (despite the example folder being DRASTICALLY different.. I'm sure disparity is to be expected during these crazy times in the world.)

iOS works. Testing on devices.
Android just.... stopped.

(When it was working, all I did was update the pods but the renaming, sorry, that you are doing here are Firebase on your pubs is very poor). There seems to be little concern for backward compatibility sometimes?

Any updates on the Android side of things?
Please don't ask for Flutter Doctor. That doesn't do anything and just stalls. Thank you.

**Comment by darshankawar** [comment] 2020-12-14 12:38
With `firebase_messaging` plugin [example](https://pub.dev/packages/firebase_messaging/example), I was able to replicate it on Android 8.1.0 device using latest stable, with app in background and screen locked.

<details>
<summary>flutter doctor -v</summary>

```

[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.4 19E2269 darwin-x64,
    locale en-IN)
    • Flutter version 1.22.5 at /Users/dhs/documents/Fluttersdk/flutter
    • Framework revision 7891006299 (3 days ago), 2020-12-10 11:54:40 -0800
    • Engine revision ae90085a84
    • Dart version 2.10.4

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at /Users/dhs/Library/Android/sdk
    • Platform android-30, build-tools 30.0.0
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.0.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.0.1, Build version 12A7300
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.51.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.16.0

[✓] Connected device (2 available)
    • SM A260G (mobile)                   • 5200763ebcfa861f
      • android-arm • Android 8.1.0 (API 27)
    • iPhone SE (2nd generation) (mobile) • 6C85835D-FBFD-4AB3-8DE8-B4FAD35E5367
      • ios         • com.apple.CoreSimulator.SimRuntime.iOS-14-0 (simulator)

• No issues found!


```

</details>

**Comment by tanvish99** [comment] 2020-12-23 11:47
any updates on this issue?

**Comment by damato3** [comment] 2021-01-10 18:44
We are facing the same issue, testing on Samsung A31 Android 10 and Huawei P30 Android 10.
The background handler stop working after some minutes when the app is locked.

**Comment by lauriolasw** [comment] 2021-01-17 21:59
Hello, any updates on this issue?

**Comment by tanvish99** [comment] 2021-01-23 08:14
Any updates on this issue?

**Comment by danielgchap** [comment] 2021-01-25 16:37
Hi all! Sorry I haven't been more helpful in this. I have been working 3 jobs pretty much.

I will say this... take a REALLY REALLY close look at your firebase_messaging code that's coming from cloud to client.
Android and iOS are VERY VERY finicky and handle the messages differently. 

It is VERY important to assess the payloads that you are firing. Obviously I can't share production code but here's an idea of what I ended up doing because of such discrepancies between Android and iOS handling these messages.

From my 'functions' folder in Visual Studio..

`const payload = {
            notification: {
                title: titleString,
                body: bodyString,
            },
            android: {
                data: {
                    id: groupId,
                    type: 'membershiprequest',
                    title: titleString,
                    body: bodyString,
                    groupId: groupId,
                    "click_action": "FLUTTER_NOTIFICATION_CLICK",
                    "priority": "high",
                },
            },
            data: {
                id: groupId,
                type: 'membershiprequest',
                title: titleString,
                body: bodyString,
                groupId: groupId,
            },
            topic: topicString,
        };`

SEE HOW ANDROID NEEDS A SEGMENTED PORTION OF THE PAYLOAD?

This was the make or break in my situation.
Hope it helps @tanvish99 @lauriolasw

**Comment by sezaru** [comment] 2021-04-19 03:50
Any updates on this? I upgraded my app from firebase_messaging 7.x to 9.x and now I'm getting this same issue.

It is kinda disheartening that a critical bug like this one is still not solved after more than 5 months and without much feedback from the developers.

Please, prioritize this, it is simply a deal breaker for apps focused on notification delivery like mine...

**Comment by drikanius** [comment] 2021-04-19 13:20
Same issue here.

Every time I update this lib a new problem appears. Worst of all, they are always invisible bugs =[.

**Comment by danielgchap** [comment] 2021-04-19 13:23
> Same issue here.
> 
> Every time I update this lib a new problem appears. Worst of all, they are always invisible bugs =[.

@drikanius sadly, same for me. Often Firebase gets updated and will frag your flutter project and multiple dependencies. Additionally, if it happens at the same time Flutter upgrades.. phew.. you're in for a frustrating day. Sorry bro.

**Comment by danielgchap** [comment] 2021-04-19 13:24
> Any updates on this? I upgraded my app from firebase_messaging 7.x to 9.x and now I'm getting this same issue.
> 
> It is kinda disheartening that a critical bug like this one is still not solved after more than 5 months and without much feedback from the developers.
> 
> Please, prioritize this, it is simply a deal breaker for apps focused on notification delivery like mine...

Hey bro, my fix ended up being the notification payload that i mentioned in my comment above. Not sure if that helps. I wish I could be of more help but, ever since doing that in my project, it works.

**Comment by sezaru** [comment] 2021-04-19 13:38
> Hey bro, my fix ended up being the notification payload that I mentioned in my comment above. Not sure if that helps. I wish I could be of more help but, ever since doing that in my project, it works.

Hey @danielgchap thanks for the suggestion, just to make sure I got it right.

You fixed this issue by adding the `android` field to your payload?

If I'm not mistaken, the payload with the android fields is for the old version of FCM messages, and the newer one doesn't need it. So are you using the older API to send your notifications and that fixes this bug?

**Comment by danielgchap** [comment] 2021-04-19 13:41
> > Hey bro, my fix ended up being the notification payload that I mentioned in my comment above. Not sure if that helps. I wish I could be of more help but, ever since doing that in my project, it works.
> 
> Hey @danielgchap thanks for the suggestion, just to make sure I got it right.
> 
> You fixed this issue by adding the `android` field to your payload?
> 
> If I'm not mistaken, the payload with the android fields is for the old version of FCM messages, and the newer one doesn't need it. So are you using the older API to send your notifications and that fixes this bug?

@sezaru good chance that's true. I haven't touched that module in a bit. 
Here's my firebase portion in .yaml file if helps...

`  firebase_core: "^0.5.3"
  # Newly reworked plugins covered by this migration guide:
  firebase_auth: "^0.18.4"
  cloud_firestore: "^0.14.4"
  cloud_functions: "^0.7.2"
  firebase_storage: "^5.2.0"
  firebase_messaging: ^7.0.3  # Updated to work with new core only plugins (no new changes):
  firebase_admob: "^0.10.3"
  firebase_analytics: "^6.3.0"
  firebase_dynamic_links: "^0.6.3"`

**Comment by sezaru** [comment] 2021-04-19 22:28
Yeah, I just confirmed here that downgrading to version 7.0.3 "fixes" the problem.

So this bug is only in version 9.x.

**Comment by sezaru** [comment] 2021-05-23 14:20
So, I saw that there is a new version of the library, version 10.0.0, does this bug still exists in that version? Looking at the changelog I couldn't find anything related to this.

**Comment by sunnykinger** [comment] 2021-05-24 05:51
Guys, please update if the issue has been fixed in 10.0.0

**Comment by danielgchap** [comment] 2021-05-24 16:49
> Guys, please update if the issue has been fixed in 10.0.0

@sunnykinger hey homie. Messaging is working for me. I'm not really using the old school background handler as I am currently using the onMessageOpened app (or whatever it's called). However when I DID use the background handler (within the last week or so).. it worked fine. Thanks boss!

**Comment by sezaru** [comment] 2021-05-26 14:50
I was testing the new version and it is not fixed... More than 6 months with this bug and no fix or even a simple feedback about it here...

It makes me wonder if this will ever be fixed or will be ignored forever...

**Comment by sezaru** [comment] 2021-05-30 04:14
Another update, since I was not sure if this was really a bug or maybe just something new with the new firebase sdk, I created a native kotlin project with FCM just to see if I can reproduce the same issue there.

Well, I cannot, so this is really a bug in this library.

Very sad that the developers simply ignore this critical bug and keeps creating new broken versions as if everything is ok...

**Comment by russellwheatley** [comment] 2021-12-23 10:11
Hey @tanvish99, I think this problem was solved [here](https://github.com/FirebaseExtended/flutterfire/pull/6730). I'll reopen if this is not the case.

**Closed by russellwheatley** 2021-12-23 10:11 UTC
Labels: type: bug, plugin: messaging
