### ISSUE TITLE
Flutter Web's "SDK setup and configuration" cant use AUTOMATIC? can only use CDN??

### ISSUE THREAD

**Issue by YohanWadia** [FirebaseExtended/flutterfire#6232] opened 2021-05-24 20:15 UTC
Hi,
In all my Web apps with JS and hosting on firebase I am able to use the AUTOMATIC option. How ever it fails with Flutter WEB.

**The below code doesnt work.**
  ```
<script src="/__/firebase/8.6.1/firebase-app.js"></script>
  <script src="/__/firebase/8.6.1/firebase-firestore.js"></script>
  <script src="/__/firebase/init.js"></script>
```
 
![a](https://user-images.githubusercontent.com/39173295/119401948-dfe7ae00-bce4-11eb-8811-fca11c46273a.JPG)

**BUT, if I use the CDN option it works**

  ```
<script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-app.js"></script>
  <script src="https://www.gstatic.com/firebasejs/8.6.1/firebase-firestore.js"></script>
  <script>
  // Your web app's Firebase configuration
  // For Firebase JS SDK v7.20.0 and later, measurementId is optional
  var firebaseConfig = {
    apiKey: "xxxxxxxxxxxxxxxxxxxxxxxx",
    authDomain: "xxxxxxxxxxxxxx.firebaseapp.com",
    databaseURL: "https://xxxxxxxxxxxx.firebaseio.com",
    projectId: "xxxxxxxxxxx",
    storageBucket: "xxxxxxxxxxxx.appspot.com",
    messagingSenderId: "54677346543658787965",
    appId: "6:464536482:web:dfhg5467ytjhfd",
    measurementId: "z-ghdhy6"
  };
  // Initialize Firebase
  firebase.initializeApp(firebaseConfig);
  firebase.analytics();
</script>
```

Is this an expected behavior? or am I missing something via which I could still run it via the AUTOMATIC option?

**Comment by darshankawar** [comment] 2021-05-25 06:46
@YohanWadia 
This is an expected behavior, because Flutter web currently only allows to CDN to configure Firebase SDK. Check this documentation for reference. https://firebase.flutter.dev/docs/installation/web/#add-firebase-sdks

There's also a note that mentions:

`We are actively investigating ways to initialize Firebase without directly using the CDN and will update the documentation once this becomes available.`


Closing this based on the info provided above, that hopefully should answer your question.

**Closed by darshankawar** 2021-05-25 06:46 UTC
Labels: in triage

**Comment by YohanWadia** [comment] 2021-05-25 09:30
@darshankawar, thank you for the reply.
BUT JUST SO THAT YOU KNOW... I have gone through the documentation thoroughly for over a week! No where in the documentation of the link given in your reply above, was this mentioned, up till last night. It seems they updated it over night after I drew attention to this point! ;-)
