### ISSUE TITLE
🐛 [Firebase_auth] Not persisting user on authStateChanges stream after 1.1.2

### ISSUE THREAD

**Issue by hdavidmb** [FirebaseExtended/flutterfire#5952] opened 2021-04-28 02:13 UTC
My app was working fine with firebase_auth 1.1.0 version. I recently updated to 1.1.2 and now the `authStateChanges` stream returns null when the app is restarted with a logged in user.

Because of this the app shows the login page and when I try to login with the same user the `authStateChanges` doesn't get called. If i login with a different user, it works fine and perform the login. But, again, when I restart the app `authStateChanges` returns null and the app shows the login page.

### Steps to reproduce

1. Update firebase_auth to 1.1.2 version
2. Sign in with a user (as it was working fine with 1.1.0 version). -> In this case `authStateChanges` gets called and the sign in. works fine.
3. Restart the app (hot restart or kill the app and start it again) -> In this case `authStateChanges` returns null.

### Expected behavior

After the app restart `authStateChanges` should return the already logged in user credentials.

---
### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-x64, locale es-419)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
dependencies:
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- cupertino_icons 1.0.2
- dartz 0.10.0-nullsafety.1
- firebase_auth 1.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flash 1.5.1 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_facebook_auth 3.3.3+1 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_riverpod 0.14.0+2 [collection flutter meta riverpod state_notifier]
- font_awesome_flutter 9.0.0 [flutter]
- freezed_annotation 0.14.1 [collection json_annotation meta]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.0.0 [flutter hive path_provider path]
- intl 0.17.0 [clock path]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.0.0 [flutter meta]

dev dependencies:
- build_runner 2.0.1 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime package_config path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 0.14.1+3 [analyzer build build_config meta source_gen freezed_annotation]
- hive_generator 1.1.0 [build source_gen hive analyzer source_helper]
- lint 1.5.3

transitive dependencies:
- _fe_analyzer_shared 21.0.0 [meta]
- analyzer 1.5.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.0.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.1 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform]
- build_runner_core 7.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.4 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.7 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.0 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.2.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.0.1 [clock collection file flutter http image path path_provider pedantic rxdart sqflite uuid]
- flutter_facebook_auth_platform_interface 2.4.2 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.4.2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 2.0.0
- http 0.13.1 [http_parser meta path pedantic]
- http_multi_server 3.0.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- path 1.8.0
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.1.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.1 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1 [matcher]
- riverpod 0.14.0+1 [collection freezed_annotation meta state_notifier]
- rxdart 0.26.0
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_helper 1.1.0 [analyzer collection source_gen]
- source_span 1.8.0 [charcode collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- state_notifier 0.7.0 [meta]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- win32 2.0.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by IvanDeluxe** [comment] 2021-04-28 07:43
I can confirm that @ 1.1.0 it works correctly & on 1.1.2 after a reload, it always returns null.

```
StreamProvider<User?>.value(
    initialData: null,
    value: FirebaseAuth.instance.userChanges(),
)
...
final user = context.watch<User?>();
print(user); // null
print(FirebaseAuth.instance.currentUser); // User(...)
return (user != null) ? HomeScreen() : LoginScreen();
```

```
[√] Flutter (Channel stable, 2.0.5, on Microsoft Windows [Version 10.0.19042.928], locale hr-HR)
    • Flutter version 2.0.5 at C:\flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\ivan7\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code (version 1.55.2)
    • VS Code at C:\Users\ivan7\AppData\Local\Programs\Microsoft VS Code
    • Flutter extension version 3.21.0

[√] Connected device (2 available)
    • Chrome (web) • chrome • web-javascript • Google Chrome 90.0.4430.93
    • Edge (web)   • edge   • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!
```

This is Web @ Chrome btw.

Thanks! :)

**Comment by markusaksli-nc** [comment] 2021-04-28 14:06
Seeing this issue as well on the latest `firebase_auth: ^1.1.2` (however `userChanges()` still works).

<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 2.3.0-1.0.pre.145, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
    • Flutter version 2.3.0-1.0.pre.145 at /Users/nevercode/development/flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision f1ad5cd9ee (4 hours ago), 2021-04-28 06:14:02 -0400
    • Engine revision adf2e24993
    • Dart version 2.14.0 (build 2.14.0-48.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (3 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.5
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 11.2.3 20D91
      darwin-arm
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome
      90.0.4430.93

• No issues found!
```
</details>

**Comment by Aanu1995** [comment] 2021-04-28 17:50
Am also experiencing the same issue

**Comment by jonmountjoy** [comment] 2021-04-29 12:34
Relatedly (I'm experiencing the same thing as above), when I log-in, the `firebaseAuth.authStateChanges()` isn't firing. Reverting to 1.0.3 seemed to fix it.

**Comment by Ehesp** [comment] 2021-04-29 14:07
Would someone be able to post a small code snippet of this issue?

I've just been playing around however I don't see the same results as OP, but that might be because of how I'm listening to the stream causing hot reload behaving differently.  

If I run the following in the example app:

```dart
Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp();
  await FirebaseAuth.instance.useEmulator('http://localhost:9099');
  runApp(AuthExampleApp());

  FirebaseAuth.instance.authStateChanges().listen((event) {
    print('got user event $event');
  });
}
```

The events come through fine (initial load). However if I then hot restart I don't see any events at all. The difference to OP here is that it's reported the stream returns `null` (vs no event at all).

With the above code, it works fine on Android/iOS - so seems hot reload is applying different results on web.

This being said, I still don't think I've replicated OPs issue.

**Comment by markusaksli-nc** [comment] 2021-04-29 14:29
@Ehesp 
https://github.com/FirebaseExtended/flutterfire/blob/dc8f49fc60eef1ebddf40e41b72749a421daf915/packages/firebase_auth/firebase_auth/example/lib/signin_page.dart#L31
replaced with
```dart
    _auth.authStateChanges().listen((event) {
      print("stream event: $event");
      setState(() => user = event);
    });
```
results in just `flutter: stream event: null` after a hot restart but with `userChanges` fires
```
flutter: stream event: null
flutter: stream event: User(displayName: null, email...
```

**Comment by budo385** [comment] 2021-04-29 17:52
This behaviour in my case happened after upgrading from 7.3.0 to 7.11 ios Firebase sdk...
_auth.authStateChanges() simply doesn't do the job anymore.

**Comment by red42** [comment] 2021-04-29 19:06
In addition to downgrading to `firebase_auth: 1.1.0`, I also had to downgrade `firebase_auth_platform_interface` to `4.1.1`, otherwise I would get errors registering auth state listeners.

**Comment by hdavidmb** [comment] 2021-04-29 19:32
> In addition to downgrading to `firebase_auth: 1.1.0`, I also had to downgrade `firebase_auth_platform_interface` to `4.1.1`, otherwise I would get errors registering auth state listeners (`Auth#registerAuthStateListener`).

Yeah!! Me too.



> Seeing this issue as well on the latest `firebase_auth: ^1.1.2` (however `userChanges()` still works). This is also observable if you hot restart.

Ok, I'll try `userChanges()`

**Comment by budo385** [comment] 2021-04-29 20:02
> Seeing this issue as well on the latest `firebase_auth: ^1.1.2` (however `userChanges()` still works). This is also observable if you hot restart.
> 
> flutter doctor -v

userChanges() is working but it has different behaviour than authStateChanges() - so it does wonders :) in my app. Downgrade was the only option for me

**Comment by YonyElm** [comment] 2021-04-29 21:17
I agree with @budo385, and implemented a similar solution (version downgrade)
Here is a small breakdown from my investigation

1. Latest working versions for me are:
`firebase_core: 1.0.4`
`firebase_auth: 1.1.1`
which results in SDK 7.3.0

2. Not working versions - login/logout functionality are buggy and do not update correctly
`firebase_core: 1.1.0`
`firebase_auth: ^1.0.0`
which results in SDK 7.11.0

3. Not working versions - login/logout do work, but `authStateChanges` returns null as described in other comments
`firebase_core: 1.1.0`
`firebase_auth: 1.1.2`
which results in SDK 7.11.0

**Comment by emreakcadag** [comment] 2021-04-30 07:50
same issue for me. session drops after closing IOS application so needs to be logged in again. Android works fine.

**Comment by rrousselGit** [comment] 2021-04-30 09:02
Please everyone, could you provide a way to reproduce the issue?

As said earlier, we aren't sure that we understand the problem. The only thing we reproduced is a hot-restart issue that happens exclusively on web, which is a minor issue

**Comment by davidcv5** [comment] 2021-04-30 09:26
This started happening to me with:
```yaml
firebase_auth: 1.1.2
firebase_auth_platform_interface: 4.2.0
```
On my startup logic I do something like this
```dart
final _auth = FirebaseAuth.instance;
if (_auth.currentUser == null) {
  // is always getting here on hot restart, wasn't before.
  await _auth.signInAnonymously();
}
...
// this gets called twice, first with null
_auth.authStateChanges().listen((user) {
  if(user == null) {
    print("user is null, sorry");
  }
  else {
    print ("now we have a user, kind of late");
    doSomethingUseful(user);
  }
});
```
This s an oversimplification, just to show the point.
Downgrading solves the issue.
```yaml
firebase_auth: 1.1.1

dependency_overrides:
  firebase_auth_platform_interface: 4.1.1
```

**Comment by Ehesp** [comment] 2021-04-30 11:47
Trying to dig into this one, the last major change which occurred was this PR https://github.com/FirebaseExtended/flutterfire/pull/5766/files - which solved a web issue, however might have caused this problem (although I don't see how right now).

**Comment by rrousselGit** [comment] 2021-04-30 11:51
So it's only a hot-restart issue?

**Comment by red42** [comment] 2021-04-30 12:09
> So it's only a hot-restart issue?

No, this happens on cold starts as well.
```dart
_auth.authStateChanges().listen((user) {
  print(user);
});
```
always gives me `null` user.

**Comment by jonmountjoy** [comment] 2021-04-30 12:17
I must admit I'm a little stymied by this.

I created a simple app https://github.com/jonmountjoy/debugerror in order to reproduce the problem.

The intention was to show the absence of the problem in 1.0.3, and how it arises in 1.1.0.

But my app doesn't even persist authentication in 1.0.3 (this is extracted from a much larger app, so perhaps there's a bug, but I can't see it).

From the README you'll see I had to do a "hot reload" at one point - without it the state change is not picked up.  After that one "hot reload" it seems to work.  However, if I do a "hot restart" the logged-in state is not persisted.

This is on the latest Xcode, and I wonder if Xcode 12.5 is a confounding factor here as I thought the above would have worked, and did work, before.

**Comment by peaklev** [comment] 2021-04-30 12:17
Just a thought... I recently updated my iOS simulator to 14.5 in tandem with updating to firebase_auth 1.1.2. Could it have something to do with Apple's latest OS?

**Comment by Ehesp** [comment] 2021-04-30 12:43
OK everyone I think we need to realign the issue. There's currently people saying "I have the same issue", but it turns out it's not the same issue and the comments don't specify versions/platforms so it becomes far too confusing.

Here any my findings so far (from master code using example app):

- Web 
 - On fresh load: Everything is working as expected. Events are firing as they should be, any persisted logged in user is emitted straight away too.
 - On hot reload: No more events are provided. This seems to be a Dart SDK difference between Android/iOS. [This is the change which caused this to happen.](https://github.com/FirebaseExtended/flutterfire/pull/5766/files#diff-00f9e031b958abd4b2c815c21265513e02c6367677588d93ac9117b59d920f3f).

- Android: Everything working as expected.
- iOS: Trying, XCode causing issues.

**Comment by davidcv5** [comment] 2021-04-30 14:26
Here are some tests I just tried:

* Android: works as expected with firebase_auth: 1.1.2

* iOS - **iPhone 12 Simulator, OS version 14.5**

Is the same for both cold and hot restart.

Somehwere in `main.dart` or your initialization logic:

```dart
FirebaseAuth.instance.authStateChanges().listen((user) {
  print('whoami: ${user?.uid}');
});

if (FirebaseAuth.instance.currentUser == null) {
  print('no user: calling signIn');
  FirebaseAuth.instance.signInAnonymously();
}

return;
```

#### firebase_auth: ^1.1.2:
```yaml
firebase_auth: ^1.1.2 #(this installs firebase_auth_platform_inteface: 4.2.0)
```

**Output:**

```sh
no user: calling signIn
whoami: null
# Because `signInAnonymously()` returns the same user as before, the state change listener is not triggered again.
```
#### firebase_auth: 1.1.1, firebase_auth_platform_interface: 4.1.1:

```yaml
firebase_auth: 1.1.1

dependency_overrides:
  firebase_auth_platform_interface: 4.1.1
```

**Output:**

```sh
whoami: myexpecteduserid
```

**Closed** 2021-04-30 14:41 UTC
Labels: impact: crowd, plugin: auth, type: bug

**Comment by cadaniel** [comment] 2021-04-30 14:56
> I'm having the same error - moved from 1.0.0 to 1.1.2 - downgrading again.
> Will try to create a reproducible. But did not understand why people are closing all the issues related to this.
> If this is not the correct thread, is there a correct one open? Or even better, is this solved?

This issue was closed because a PR fixing it got merged.

**Comment by diver2** [comment] 2021-04-30 15:28
just tested pointing to master, works great. BIG THANKS

**Comment by jonmountjoy** [comment] 2021-04-30 16:04
@Ehesp thanks for this update!  Note that my sample app https://github.com/FirebaseExtended/flutterfire/issues/5952#issuecomment-830053828 still doesn't work on iOS 12.5, but does work on Android - so I suspect that there's still an issue (albeit a different one).

**Comment by Ehesp** [comment] 2021-04-30 16:11
Still pending a release at the moment.

**Comment by Jethro87** [comment] 2021-04-30 20:29
> Still pending a release at the moment.

Can we expect a release today? I was planning on releasing a new iOS version of my app today. If a release is expected soon, I'll hold back my release. Otherwise, I'll downgrade Firebase auth. Thanks.

**Comment by Jethro87** [comment] 2021-05-01 00:57
@diver2 Thanks! I'll give that a try.

**Comment by ConstantNel** [comment] 2021-05-01 06:23
@Jethro87 @diver2 The above fix doesn't seem to work when using Firebase SDK 7.11.0. I believe the problem is the the IOS SDK.

**Comment by jonmountjoy** [comment] 2021-05-01 08:00
@ConstantNel The above fix does work in my demo app listed above (on 12.5).  

The only problem now is that a a Hot Restart crashes the app completely.  

Presumably that's because it's on the master branch and some work is outstanding before it's released.

**Comment by diver2** [comment] 2021-05-01 11:32
You could just get v1.1.2 and merge the commit of @rrousselGit - https://github.com/FirebaseExtended/flutterfire/pull/5987 on a repository of yours. Should work as well.

**Comment by Jethro87** [comment] 2021-05-01 14:27
My app is also crashing on hot reload.
