### ISSUE TITLE
🐛 [firebase_auth] Firebase Phone Auth SMS verification Code not received

### ISSUE THREAD

**Issue by ZahidTekbas** [FirebaseExtended/flutterfire#6869] opened 2021-08-23 14:21 UTC
## Bug report

**Describe the bug**
My app is using Phone Verification and I use Firebase Auth services in order to complete that process. My app is live more than 4 months and phone verification was working completely good until today. The client side is not receiving any SMS verification code and does not log any error or does not catch any exception. This is my implementation code in Flutter:

### Steps to reproduce

1. enter your phone number
2. call phoneVerify function after user press done
3. no code received and also no error appears in logs

### Expected behavior

Code should be successfully received to user's phone.

### Sample project

I can provide sample code:

<details><summary>Click To Expand Code</summary>

```
 Future<void> _phoneVerify() async {
    print("phone number $_phoneNumber");
    try {
      await _auth.verifyPhoneNumber(
        phoneNumber: _phoneNumber,
        verificationCompleted: (PhoneAuthCredential credential) async {
        },
        verificationFailed: (FirebaseAuthException e) {
          print(e.toString());
          EasyLoading.showError(e.toString());
        },
        codeSent: (String verificationId, int resendToken) async {
          // Create a PhoneAuthCredential with the code
          _phoneVerificationPopUp(
              verificationID: verificationId, resendToken: resendToken);
        },
        codeAutoRetrievalTimeout: (String verificationId) {},
        timeout: Duration(seconds: 120),
      );
    } catch (e) {
      EasyLoading.dismiss();
      setState(() {
        _smsCode = '';
      });
      _controller.clear();
      Navigator.pop(context);
      if (e.code == 'invalid-verification-code') {
        EasyLoading.showError('Invalid Verification Code');
      } else {
        EasyLoading.showError(e.code);
      }
    }
  }
```

</details>

---

## Additional context

That verification process was working fine until today. The phone numbers are located in Turkey, starts with +90.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.2.2, on macOS 11.5.2 20G95 darwin-x64, locale en-GB)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.59.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.3
Flutter SDK 2.2.2
terapistin_app 1.0.18+62

dependencies:
- add_2_calendar 2.1.0 [flutter]
- agora_rtc_engine 4.0.2 [flutter flutter_web_plugins json_annotation]
- alphabet_scroll_view 0.3.1 [flutter collection]
- angles 2.1.0 [meta]
- animated_bottom_navigation_bar 0.3.2 [flutter]
- animations 2.0.0 [flutter]
- auto_size_text_pk 3.0.0 [flutter]
- cached_network_image 3.0.0 [flutter flutter_cache_manager octo_image]
- cloud_firestore 1.0.7 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- crypto 3.0.1 [collection typed_data]
- cupertino_icons 1.0.3
- device_info 2.0.2 [flutter device_info_platform_interface]
- dropdown_below 0.0.9 [flutter]
- favorite_button 0.0.4 [flutter]
- file_picker 3.0.3 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 8.2.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_auth 1.4.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.4.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_database 7.1.2 [firebase_core flutter]
- firebase_in_app_messaging 0.5.0+5 [firebase_core flutter meta]
- firebase_messaging 10.0.3 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_storage 8.1.3 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- flashy_tab_bar 0.0.3 [flutter]
- flip_card 0.5.0 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_calendar_carousel 2.0.1 [intl flutter]
- flutter_chips_input 1.10.0 [flutter]
- flutter_countdown_timer 4.1.0 [flutter]
- flutter_cupertino_date_picker_fork 1.0.3 [flutter]
- flutter_easyloading 3.0.0 [flutter flutter_spinkit]
- flutter_html 0.11.1 [html flutter]
- flutter_icons 1.1.0 [flutter]
- flutter_local_notifications 8.1.1 [flutter flutter_local_notifications_platform_interface platform timezone]
- flutter_quill 1.6.0 [flutter collection flutter_colorpicker flutter_keyboard_visibility image_picker photo_view quiver string_validator tuple url_launcher pedantic characters]
- flutter_rating_bar 4.0.0 [flutter]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- flutter_spinkit 5.0.0 [flutter]
- flutter_svg 0.20.0-nullsafety.3 [flutter meta path_drawing vector_math xml]
- font_awesome_flutter 9.1.0 [flutter]
- getwidget 2.0.3 [flutter]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- google_sign_in 5.0.4 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- http 0.13.3 [async http_parser meta path pedantic]
- image_picker 0.7.5+4 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- intl_phone_field 2.0.0 [flutter]
- kommunicate_flutter 1.1.9 [flutter]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- pdf 3.4.2 [archive barcode crypto image meta path_parsing vector_math xml]
- permission_handler 6.1.3 [flutter meta permission_handler_platform_interface]
- pin_code_text_field 1.8.0 [flutter]
- provider 4.3.3 [collection flutter nested]
- readmore 2.1.0 [flutter]
- shared_preferences 2.0.6 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 3.0.0 [flutter meta]
- textfield_search 0.8.0 [flutter]
- timezone 0.7.0 [path]
- twilio_flutter 0.0.9 [flutter http meta]
- url_launcher 6.0.8 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- video_player 2.1.6 [flutter flutter_test meta video_player_platform_interface video_player_web]
- wakelock 0.5.2 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- webview_flutter 2.0.9 [flutter]
- youtube_player_flutter 8.0.0 [flutter flutter_inappwebview]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 3.1.2 [crypto path]
- async 2.6.1 [meta collection]
- barcode 2.1.0 [meta qr]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.3 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.7 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- collection 1.15.0
- csslib 0.16.2 [source_span]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth_platform_interface 4.3.1 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.3.1 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.2 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_storage_platform_interface 2.1.2 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 1.1.2 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_colorpicker 0.4.0 [flutter]
- flutter_inappwebview 5.3.2 [flutter]
- flutter_keyboard_visibility 5.0.2 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_local_notifications_platform_interface 4.0.1 [flutter plugin_platform_interface]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.14.0+4 [csslib source_span]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.2 [archive meta xml]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.1.0 [flutter meta http plugin_platform_interface]
- intl 0.17.0 [clock path]
- js 0.6.3
- json_annotation 4.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.6.0 [flutter meta plugin_platform_interface]
- petitparser 4.1.0 [meta]
- photo_view 0.11.1 [flutter]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.2.1 [file path platform]
- qr 2.1.0 [meta]
- quiver 3.0.1 [matcher]
- rxdart 0.27.1
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- string_validator 0.3.0
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.3 [flutter plugin_platform_interface]
- url_launcher_web 2.0.1 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.0 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.0
- video_player_platform_interface 4.1.0 [flutter meta flutter_test]
- video_player_web 2.0.1 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock_macos 0.1.0+1 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.1+1 [flutter meta]
- wakelock_web 0.2.0+1 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.1.0 [flutter wakelock_platform_interface win32]
- win32 2.2.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.1.2 [collection meta petitparser]

```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-08-24 05:43
Hi @ZahidTekbas 
This sounds like a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4916
It sounds like this happened spontaneously instead of due to a version change? Could you try looking through the discussion on the mentioned issue and seeing if anything helps? You can comment any unmentioned relevant information on it as well.
Closing this as a duplicate.
Thank you

**Closed by markusaksli-nc** 2021-08-24 05:43 UTC
Labels: type: bug, Needs Attention, in triage
