### ISSUE TITLE
settings.gradle conflict using firebase_auth: ^0.16.1

### ISSUE THREAD

**Issue by mukundoesflutter** [FirebaseExtended/flutterfire#2870] opened 2020-06-30 17:04 UTC
Error list:
Running Gradle task 'assembleDebug'...
Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :firebase_auth_web not found. Please update settings.gradle.

Flutter doctor result:
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, v1.17.4, on Microsoft Windows [Version 10.0.19041.329], locale en-GB)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 4.0)
[√] Connected device (2 available)

• No issues found!

Fixes attempted:
1. Tried changing `minSdkVersion `from 16 to 21.
2. In the app level _build.gradle_ added `multiDexEnabled true` to `defaultConfig` and added dependency for `androidx.multidex:multidex:2.0.1`.
3. Updated _settings.gradle_ to -->

```
include ':app'

def flutterProjectRoot = rootProject.projectDir.parentFile.toPath()

def plugins = new Properties()
def pluginsFile = new File(flutterProjectRoot.toFile(), '.flutter-plugins')
if (pluginsFile.exists()) {
pluginsFile.withReader('UTF-8') { reader -> plugins.load(reader) }
}

plugins.each { name, path ->
def pluginDirectory = flutterProjectRoot.resolve(path).resolve('android').toFile()
include ":$name"
project(":$name").projectDir = pluginDirectory
}
```
4. Included `firebase_core: ^0.4.5` in _pubspec.yaml_ and did `pub get`

The errors still remain the same.
Experts, please advise.

**Comment by ezone-dev** [comment] 2020-07-01 08:17
I have the same issue exactly. Thought it was worth noting the Flutter code works fine on iOS.

Steps to reproduce: Install stable release of  Flutter 1.17.4, Go through steps of codelab at [https://codelabs.developers.google.com/codelabs/flutter-firebase/ ] adding firebase to the default app.

Expected Result: App runs identically on iOS and Android
Actual Result: App runs on iOS, App fails to run on Android with error 
`Plugin project :firebase_core_web not found. Please update settings.gradle.
Plugin project :firebase_auth_web not found. Please update settings.gradle.`

**Comment by TahaTesser** [comment] 2020-07-01 08:27
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2796

**Closed by TahaTesser** 2020-07-01 08:27 UTC

**Comment by ezone-dev** [comment] 2020-07-03 00:08
I thought about this and thought it was environmental and was able to get my app working by resolving inconsistencies in my android applicationID and package settings, (I had renamed it) and using the settings in #2796 - all working on 1.17.5 now. sorry for the noise.
