### ISSUE TITLE
[firebase_crashlytics] Example Project is not working

### ISSUE THREAD

**Issue by leochiu-work** [FirebaseExtended/flutterfire#2207] opened 2020-03-19 12:24 UTC
**Describe the bug**
Crashlytics cannot catch the Exception at all.

**To Reproduce**
1. Download and run the Firebase Crashlytics Example Project in iOS
2. Press 'Crash' button
4. Crashed, but Crashlytics cannot catch the exception

**Expected behavior**
"Flutter error caught by Crashlytics plugin" is shown in Debug Console

**Comment by iapicca** [comment] 2020-03-20 09:40
Hi @leochiu-work 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`
and your `pubspec.yaml` 
Thank you

**Comment by ajackson2907** [comment] 2020-03-26 21:08
It seems the command line argument -FIRAnalyticsDebugEnabled is not included when using flutter run

Can flutter include command-line arguments?

**Comment by workerbee22** [comment] 2020-04-11 06:59
It hasn't worked as documented for about 6 months or longer.

**Comment by Ehesp** [comment] 2020-04-23 07:45
Closing as duplicate of the older https://github.com/FirebaseExtended/flutterfire/issues/1951

**Closed by Ehesp** 2020-04-23 07:45 UTC
Labels: blocked: customer-response, platform: ios, plugin: crashlytics, type: bug
