### ISSUE TITLE
[Crashlytics] Remove Fabric dependency

### ISSUE THREAD

**Issue by zmeggyesi** [FirebaseExtended/flutterfire#2881] opened 2020-07-02 06:32 UTC
Firebase Crashlytics seems to be still using the deprecated Fabric SDK. This is no longer supported, and will stop working altogether on 2020-11-15.

Podspecs should be updated to no longer include Fabric, and code changes are necessary due to an updated API in Crashlytics.

Source: https://firebase.google.com/docs/crashlytics/upgrade-sdk

**Comment by tillchen** [comment] 2020-07-02 21:01
Agreed! The documentation should also update for the setup.

**Comment by sanekyy** [comment] 2020-07-03 13:39
Waiting for update.

**Comment by emostar** [comment] 2020-07-03 17:53
Duplicate of #2038

**Comment by TahaTesser** [comment] 2020-07-06 11:57
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2038

**Closed by TahaTesser** 2020-07-06 11:57 UTC
