### ISSUE TITLE
🐛 [firebase_messaging] The onMessageOpenedApp method doesn't get triggered after click the notification in example.

### ISSUE THREAD

**Issue by windows7lake** [FirebaseExtended/flutterfire#5399] opened 2021-03-19 06:15 UTC
## Bug report

Running the example in (flutterfire->firebase_messaging), the onMessageOpenedApp method was never get triggered.

### Steps to reproduce

1. Running the example in (flutterfire->firebase_messaging)
2. Click 'send message' button
3. After the notification appear, click it.

### Expected behavior

The onMessageOpenedApp method can be get triggered.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.133, on macOS 11.2.3 20D91 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Xcode - develop for iOS and macOS
    ! CocoaPods 1.9.3 out of date (1.10.0 is recommended).
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To upgrade see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
firebase_messaging % flutter pub deps -- --style=compact
Dart SDK 2.13.0-143.0.dev
Flutter SDK 2.1.0-13.0.pre.133
firebase_messaging 9.0.0

dependencies:
- firebase_core 1.0.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 2.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- meta 1.3.0

dev dependencies:
- async 2.5.0 [collection]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mockito 5.0.2 [analyzer build code_builder collection dart_style matcher meta path source_gen test_api]
- plugin_platform_interface 2.0.0 [meta]
- test 1.16.5 [analyzer async boolean_selector coverage http_multi_server io js node_preamble package_config path pedantic pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]

transitive dependencies:
- _fe_analyzer_shared 18.0.0 [meta]
- analyzer 1.2.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.0.0
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.0 [analyzer async convert crypto glob logging meta path]
- built_collection 5.0.0
- built_value 8.0.3 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- coverage 1.0.1 [args logging package_config path source_maps stack_trace vm_service]
- crypto 3.0.0 [collection typed_data]
- dart_style 1.3.14 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- file 6.1.0 [meta path]
- firebase_core_web 1.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.0 [async collection file path pedantic string_scanner]
- http_multi_server 3.0.0 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- logging 1.0.0
- matcher 0.12.10 [stack_trace]
- mime 1.0.0
- node_preamble 1.4.13
- package_config 2.0.0 [path]
- path 1.8.0
- pedantic 1.11.0
- pool 1.5.0 [async stack_trace]
- pub_semver 2.0.0 [collection]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.0.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 0.9.10+4 [analyzer async build dart_style glob meta path pedantic source_span]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.3.15 [analyzer async args boolean_selector collection coverage glob io meta package_config path pedantic pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- vm_service 6.1.0+1
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.0.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.0.0 [logging]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by windows7lake** [comment] 2021-03-19 10:15
After checking the code in [firebase_mesagging], I found that when click the notification, ”Messaging#onMessageOpenedApp“ seem to never being invoked.

## FlutterFirebaseMessagingPlugin.java:
```
  @Override
  public boolean onNewIntent(Intent intent) {
    if (intent == null || intent.getExtras() == null) {
      return false;
    }

    // Remote Message ID can be either one of the following...
    String messageId = intent.getExtras().getString("google.message_id");
    if (messageId == null) messageId = intent.getExtras().getString("message_id");
    if (messageId == null) {
      **********************************
      ** messageId wiil always be null**
      **********************************
      return false;
    }

    RemoteMessage remoteMessage = FlutterFirebaseMessagingReceiver.notifications.get(messageId);

    // If we can't find a copy of the remote message in memory then check from our persisted store.
    if (remoteMessage == null) {
      remoteMessage = FlutterFirebaseMessagingStore.getInstance().getFirebaseMessage(messageId);
      // Note we don't remove it here as the user may still call getInitialMessage.
    }

    if (remoteMessage == null) {
      return false;
    }

    // Store this message for later use by getInitialMessage.
    initialMessage = remoteMessage;

    FlutterFirebaseMessagingReceiver.notifications.remove(messageId);
    channel.invokeMethod(
        "Messaging#onMessageOpenedApp",
        FlutterFirebaseMessagingUtils.remoteMessageToMap(remoteMessage));
    mainActivity.setIntent(intent);
    return true;
  }
```
The `message_id` will always be null.

## FlutterLocalNotificationsPlugin.java:
```
  private static Notification createNotification(Context context, NotificationDetails notificationDetails) {
        setupNotificationChannel(context, NotificationChannelDetails.fromNotificationDetails(notificationDetails));
        Intent intent = getLaunchIntent(context);
        intent.setAction(SELECT_NOTIFICATION);
        intent.putExtra(PAYLOAD, notificationDetails.payload);
        ******************************************************************
        ** no message_id or google.message_id was setted here ********
        ******************************************************************
        PendingIntent pendingIntent = PendingIntent.getActivity(context, notificationDetails.id, intent, PendingIntent.FLAG_UPDATE_CURRENT);
        DefaultStyleInformation defaultStyleInformation = (DefaultStyleInformation) notificationDetails.styleInformation;
        NotificationCompat.Builder builder = new NotificationCompat.Builder(context, notificationDetails.channelId)
                .setContentTitle(defaultStyleInformation.htmlFormatTitle ? fromHtml(notificationDetails.title) : notificationDetails.title)
                .setContentText(defaultStyleInformation.htmlFormatBody ? fromHtml(notificationDetails.body) : notificationDetails.body)
                .setTicker(notificationDetails.ticker)
                .setAutoCancel(BooleanUtils.getValue(notificationDetails.autoCancel))
                .setContentIntent(pendingIntent)
                .setPriority(notificationDetails.priority)
                .setOngoing(BooleanUtils.getValue(notificationDetails.ongoing))
                .setOnlyAlertOnce(BooleanUtils.getValue(notificationDetails.onlyAlertOnce));
      .........
  }
```
It seems that when we create notification and `message_id` isn't setted by us.

**Comment by 604587986** [comment] 2021-03-19 10:24
@windows7lake

**Comment by markusaksli-nc** [comment] 2021-03-19 12:20
Hi @windows7lake 
As mentioned in the documentation

> A Stream event will be sent if the app has opened from a background state (not terminated)

The message that appears in the example app if you tap the FAB is received in the `onMessage` and then shown as a heads-up notification by `flutter_local_notifications`. You would not expect the tapped message to open to trigger the `onMessageOpenedApp` since it didn't open the app.

If you want access to a callback when the heads-up notification is pressed please look into the documentation for `flutter_local_notifications`.

If you send a message to the app from an API call or from Firebase Console and press the notification when the app is backgrounded the `onMessageOpenedApp` stream fires as expected.

Closing this since the package is working as intended.
Thank you

**Closed by markusaksli-nc** 2021-03-19 12:20 UTC
Labels: Needs Attention, type: bug
