### ISSUE TITLE
[firebase_admob] RewardedVideoAd.load() only triggers RewardedVideoAdEvent.loaded on first load, not triggered on successive loads

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1178] opened 2019-10-13 19:49 UTC
**Issue**

The firebase_admob package has an option to display RewardedVideoAd's, but only one video will load and each successive call to load() fails to trigger a RewardedVideoAdEvent.loaded, so only one ad can be shown per session.

**Steps to Reproduce:**

1. Create an empty project
2. Add this to your AndroidManifest.xml (below is the testAppID):
```xml
<meta-data
  android:name="com.google.android.gms.ads.APPLICATION_ID"
  android:value="ca-app-pub-3940256099942544~3347511713"/>
```
3. Add firebase_admob to your pubspec.yaml:
```
firebase_admob: 0.9.0+1
```
4. Replace main.dart with the below code.
5. Fill in your App Id from the Google Admob Dashboard
6. Run

**main.dart**:

```Dart
import 'package:firebase_admob/firebase_admob.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

void main() {
  FirebaseAdMob.instance.initialize(appId: FirebaseAdMob.testAppId);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: RewardedVideoAdTest(),
    );
  }
}

class RewardedVideoAdTest extends StatefulWidget {
  @override
  RewardedVideoAdTestState createState() => RewardedVideoAdTestState();
}

class RewardedVideoAdTestState extends State<RewardedVideoAdTest> {

  bool rewardedVideoAdLoaded = false;

  @override
  void initState() {
    super.initState();

    // Add a listener for RewardedVideoAd's
    RewardedVideoAd.instance.listener =
      (RewardedVideoAdEvent event, {String rewardType, int rewardAmount}) {
        if (event == RewardedVideoAdEvent.rewarded) {
          print("RewardedVideoAd.listener - Rewarded");
        } else if ( event == RewardedVideoAdEvent.loaded ) {
          print("RewardedVideoAd.listener - Loaded");
          setState(() {
            rewardedVideoAdLoaded = true;
          });
        } else if ( event == RewardedVideoAdEvent.opened ) {
          print("RewardedVideoAd.listener - Opened");
          loadRewardedVideoAd();
        } else if ( event == RewardedVideoAdEvent.failedToLoad ) {
          print("RewardedVideoAd.listener - FailedToLoad");
        } else if ( event == RewardedVideoAdEvent.started ) {
          print("RewardedVideoAd.listener - Started");
        } else if ( event == RewardedVideoAdEvent.completed ) {
          print("RewardedVideoAd.listener - Completed");
        } else if ( event == RewardedVideoAdEvent.leftApplication ) {
          print("RewardedVideoAd.listener - Left Application");
        } else if ( event == RewardedVideoAdEvent.closed ) {
          print("RewardedVideoAd.listener - Closed");
        }
      };

    // Load our first RewardedVideoAd
    loadRewardedVideoAd();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Rewarded Ad Video Test")
      ),

      body: Center(
        child: RaisedButton(
          child: Text("Show Rewarded Video Ad"),
          onPressed: rewardedVideoAdLoaded ? showRewardedVideoAd : null
        ),
      )
    );
  }
  
  void loadRewardedVideoAd() {
    print("RewardedVideoAd.load() - Called");
    RewardedVideoAd.instance.load(
      adUnitId: RewardedVideoAd.testAdUnitId,
      targetingInfo: MobileAdTargetingInfo(
        nonPersonalizedAds: true,
      )
    ).catchError((error) {
      print("RewardedVideoAd.load() - Error");
    }).then((onVal) {
      print("RewardedVideoAd.load() - Returned ${onVal}");
      return onVal;
    }).whenComplete(() {
      print("RewardedVideoAd.load() - Complete");
    });
  }

  void showRewardedVideoAd() {
    setState(() {
      rewardedVideoAdLoaded = false;
    });
    RewardedVideoAd.instance.show();
  }

}

```

**Observations**

You'll notice that at first the "Show Rewarded Video Ad" button is temporarily disabled, that is because on startup we are still loading the first video ad. Once the ad loads the button will be enabled, you can click it to see the test video ad.

After clicking the ad you will see an attempt to load the next video ad that is triggered by our listener. This second load() attempt will never finish.

The output you'll see to console will be something like:

```
RewardedVideoAd.load() - Called
RewardedVideoAd.load() - Returned true  <--- First load() triggers an event...
RewardedVideoAd.load() - Complete
RewardedVideoAd.listener - Loaded  <--- ... right here. We now can show ad
RewardedVideoAd.listener - Opened  <--- We open an ad
RewardedVideoAd.load() - Called 
RewardedVideoAd.load() - Returned true <--- Second load() works, never triggers event  
RewardedVideoAd.load() - Complete
RewardedVideoAd.listener - Started
RewardedVideoAd.listener - Completed
RewardedVideoAd.listener - Rewarded
RewardedVideoAd.listener - Closed
```

In the case above we waited for the video to load and watched it while attempted to load the next, which is why we see the "rewarded" line. The next video never loads.

**flutter doctor**

Here are my flutter doctor results:

```
[✓] Flutter (Channel dev, v1.7.4, on Mac OS X 10.14.5 18F203, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
[✓] iOS tools - develop for iOS devices
[✓] Android Studio (version 3.4)
[✓] Connected device (1 available)
```

Here are the verbose flutter doctor results:

```
[✓] Flutter (Channel dev, v1.7.4, on Mac OS X 10.14.5 18F203, locale en-US)
    • Flutter version 1.7.4 at /Users/mas7967/Library/Flutter/flutter
    • Framework revision dfecafa4ab (4 days ago), 2019-06-14 09:46:23 -0700
    • Engine revision 2589785b5c
    • Dart version 2.4.0

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/mas7967/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 10.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.2.1, Build version 10E1001
    • CocoaPods version 1.6.1

[✓] iOS tools - develop for iOS devices
    • ios-deploy 1.9.4

[✓] Android Studio (version 3.4)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 36.1.1
    • Dart plugin version 183.6270
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1343-b01)

[✓] Connected device (1 available)
    • Pixel 2 XL • 711KPFX0768491 • android-arm64 • Android 9 (API 28)

• No issues found!
```

**Comment by kroikie** [comment] 2019-10-13 19:49
@mas7967

The issue at https://github.com/flutter/flutter/issues/34670 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment] 2019-10-21 18:50
Hello @mas7967 !

Did you manage to solve the issue? Does the problem still persist in the latest stable version?

**Comment by iapicca** [comment] 2019-10-24 12:34
https://github.com/FirebaseExtended/flutterfire/issues/1300

**Comment by mas7967** [comment] 2019-10-24 15:45
Sorry for the delay in response, I did figure this issue out.

The problem is with this part of my code:

`
} else if ( event == RewardedVideoAdEvent.opened ) {
  print("RewardedVideoAd.listener - Opened");
  loadRewardedVideoAd();
}
`

The issue is I was trying to load a second reward video ad when the user opens a loaded ad. My thought process was that I would load a second ad in the background so that when the user finishes watching the first ad, another ad would be in a loaded state and ready to be opened. This apparently isn't allowed. You need to wait until the current reward video hits the completed status, and only then can you begin loading another reward video.

It was unclear to me that this was how it worked, it's not mentioned in the documentation, and the only way I tracked down the problem was going through the native implementation which seems to be forcing this behavior.

See the [FirebaseAdMobPlugin.java](https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_admob/android/src/main/java/io/flutter/plugins/firebaseadmob/FirebaseAdMobPlugin.java) file of the Android implementation for reference. 

Lines 128:
`
private void callLoadRewardedVideoAd(MethodCall call, Result result) {
    if (rewardedWrapper.getStatus() != RewardedVideoAdWrapper.Status.CREATED
        && rewardedWrapper.getStatus() != RewardedVideoAdWrapper.Status.FAILED) {
      result.success(Boolean.TRUE); // The ad was already loading or loaded.
      return;
    }
    ...
}
`

While viewing a reward video, the RewardedVideoAdWrapper.Status is still LOADED, and so the method returned true, even though it didn't load a new reward video. So in my log statements:

`
RewardedVideoAd.load() - Called
RewardedVideoAd.load() - Returned true  <--- First load() triggers an event...
RewardedVideoAd.load() - Complete
RewardedVideoAd.listener - Loaded  <--- ... right here. We now can show ad
RewardedVideoAd.listener - Opened  <--- We open an ad
RewardedVideoAd.load() - Called 
RewardedVideoAd.load() - Returned true <--- Second load() works, never triggers event  
RewardedVideoAd.load() - Complete
RewardedVideoAd.listener - Started
RewardedVideoAd.listener - Completed
RewardedVideoAd.listener - Rewarded
RewardedVideoAd.listener - Closed
`

The second time we call RewardedVideoAd.load() and it returned true, it didn't actually load another video. It had interpreted the reward video currently being viewed by the user as LOADED and didn't bother loading a second one.

I do think this should be addressed in some way in the package, some options are:

* Do nothing but at a minimum mention this as a "Limitation" in the package documentation.

* Ad another status to the RewardVideoAdWrapper.Status enum. The current enum is:

`
  enum Status {
    CREATED,
    LOADING,
    FAILED,
    LOADED
  }
`

The Status does not differentiate between a video that is LOADED, and one that is being viewed by the user. I'm unsure if there is a technical limitation here, but if another status could be added, such as VIEWING, then the previously mentioned method callLoadRewardedVideoAd could load another reward video. Or, in the case that two reward videos cannot be loaded at once, it could at least throw a meaningful error.

* Throw a meaningful error / response when a user tries to load a video with an already loaded video. Right now the callLoadRewardedVideoAd returns:

`
result.success(Boolean.TRUE);
`

which is very misleading since it wasn't successful at all, instead it should return something like:

`
result.error("ad_not_loaded", "load failed, cannot load two reward videos at one time", null);
`

I'm not sure if this was a technical limitation or a choice by the author, but there is something misleading here that I think should be addressed, since at a higher level anyone using this package would get misleading returns without any explicit documentation saying that what they are trying to do is not allowed.

Thanks!

**Comment by geekydiamond** [comment] 2019-11-20 17:02
I hit exactly this problem. I was loading an advert, then when switching user account I was attempting to load it again (this time with different tracking settings). 
However, the second call to load never triggered the listener because (after much investigation) I realised the advert was already loaded and the listener didn't trigger on the second load.

I would suggest that the listener should still trigger the 'loaded' event even if the advert is already loaded.

Anyway, I hadn't noticed the boolean being returned from the load method, so I'll see if that solves my problem :)

**Comment by iapicca** [comment] 2020-01-28 07:59
Hi @mas7967 
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of firebase_admob?
thank you

**Comment by Ehesp** [comment] 2020-04-20 11:46
Going to leave this one open for the time being. Not 100% sure whether this should be documentation or additional code to support this.

**Comment by tapizquent** [comment] 2020-07-15 18:50
I am experiencing a similar issue, but what happens is that if I, load the video first but don't show it, if I exit and come back to this, the `loaded` event does not fire again. I have to get out of the app and come back for it to actually load and the listener to alert that the ad was loaded. 

I am assuming this is because the video is already loaded and doing a new `instance.load()` won't load another one and hence not alert the listener of it.

I have yet to find another way to check whether the video was previously loaded and can be shown right away without listener alerting of the Loaded event.

This does not happen and it behaves properly if I show the video. But if the video is never shown, then it won't load again.

**Comment by tapizquent** [comment] 2020-07-15 19:09
> I hit exactly this problem. I was loading an advert, then when switching user account I was attempting to load it again (this time with different tracking settings).
> However, the second call to load never triggered the listener because (after much investigation) I realised the advert was already loaded and the listener didn't trigger on the second load.
> 
> I would suggest that the listener should still trigger the 'loaded' event even if the advert is already loaded.
> 
> Anyway, I hadn't noticed the boolean being returned from the load method, so I'll see if that solves my problem :)

Agree! It should fire the Loaded event if it's already loaded and there is a call to `instance.load()`

**Comment by ostrowp1** [comment] 2020-07-21 20:38
Having same problem here. I'm loading a reward video ad on a particular page and if someone leaves that page after the ad gets loaded then enters again he will end up waiting for the listener event that will never show :/

**Comment by armandojimenez** [comment] 2021-02-19 23:51
Having the same problem, anyway we can check if the video already loaded?

**Comment by russellwheatley** [comment] 2021-03-19 12:27
The `firebase_admob` plugin will be deprecated in April 2021 in favor of [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter).
Google Mobile Ads SDK for Flutter is a new Flutter plugin that supports more Ads formats than `firebase_admob` does. Google Mobile Ads SDK for Flutter currently supports loading and displaying banner, interstitial (full-screen), native ads, and rewarded video ads across AdMob and AdManager. It also supports displaying banner and native ads as `Widgets` as opposed to being overlayed over all app content.
We're now recommending projects currently using `firebase_admob` migrate to Google Mobile Ads SDK for Flutter following the [instructions outlined here](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_admob#migrating-to-google-mobile-ads-sdk-for-flutter).
Issues with migrating or with using the new package should now be raised over on the [Google Mobile Ads SDK for Flutter](https://github.com/googleads/googleads-mobile-flutter) repository.

**Closed by russellwheatley** 2021-03-19 12:27 UTC
Labels: plugin: admob, type: documentation
