### ISSUE TITLE
Firebase Crashlytics - New dependencies

### ISSUE THREAD

**Issue by ahmaducg** [FirebaseExtended/flutterfire#2591] opened 2020-05-20 06:40 UTC
The Firebase Crashlytics library still uses Fabric as the reporting API.
Since Firebase Crashlytics are now fully from Firebase, can you please update the library to use Firebase instead of Fabric?

**Comment by TahaTesser** [comment] 2020-05-20 12:35
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2038

**Closed by TahaTesser** 2020-05-20 12:35 UTC
