### ISSUE TITLE
[firebase_auth] Anonymous currentUser() returns null

### ISSUE THREAD

**Issue by matejhocevar** [FirebaseExtended/flutterfire#2187] opened 2020-03-17 09:07 UTC
**Describe the bug**
We have developed and tested a Flutter app. Everything works as expected. We deployed an app to stores and gain some users.

After a few months, we got complaints from our users that they lost all their data when they opened the app.

I believe that the data is not lost, only their anonymous account changed to the new anonymous account.

What users, with lost data, have in common:
- iOS devices (not sure if relevant),
- didn't use the app for at least a few days.

**To Reproduce**
Our user authentication flow:

1. App starts,
2. All services are initialized in `main()` method,
3. AuthService initialize `final _auth = FirebaseAuth.instance;` and calls `loginUser()`,
4. `loginUser()` method executes:

```dart
void loginUser() async {
  FirebaseUser user = await _auth.currentUser();

  if (user == null) {
    AuthResult result = await _auth.signInAnonymously();
    user = result.user;
  }

  IdTokenResult userToken = await user.getIdToken();
  print('USER');
  print('    UID: ${user.uid}');
  print('    Token: ${userToken.token}');
  print('    Expires: ${userToken.expirationTime}');
}
```

We are using versions:

- `flutter: v1.12.13+hotfix.7`
- `firebase_core: ^0.4.0+8`
- `firebase_auth: ^0.14.0+5`
- `get_it: ^1.1.0`

We didn't experience any problems with registered users.

**Expected behavior**
We expect that an anonymous account will stay cached on the mobile device for many months, even if a user doesn't use the app. Also if the app updates via App store the anonymous account should stay the same.

**Additional context**
Questions:

- In what cases would `this._auth.currentUser()` return `null`?
- Is there an expiry date for the anonymous account?
- Is there a way to reproduce this issue?
- Did someone experience the same issue?
- What are we doing wrong in our auth flow?
- How can this be avoided for anonymous users?

**Comment by awaik** [comment] 2020-04-13 04:05
Hello,
I also make anonymous authorization and this issue important for me. For now, I have not this issue in my app. Because of this, question: "Do you keep in the cache the user id"? 

In the case of Anonymous authorization, if we lost user id in the app == we lost all the user data. Data left in Firebase storage, but we can't identify user with this data.

**Comment by jaredford** [comment] 2020-05-30 21:55
I have the same issue. When my app is killed (I do not sign out the user), the user seems to get signed out anyway. This results in a new anonymous user being created. The issue is occurring for me in TestFlight, but not locally

**Comment by Ehesp** [comment] 2020-08-25 14:51
Hi All - this should now be fixed on the latest version of auth. Closing - please let me know if you continue to have issues.

**Closed by Ehesp** 2020-08-25 14:51 UTC
Labels: blocked: customer-response, good first issue, impact: customer, plugin: auth, resolution: needs-repro, type: bug, type: question
