### ISSUE TITLE
🐛 [cloud_firestore] ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by Dylan-Sharp** [FirebaseExtended/flutterfire#4901] opened 2021-02-01 21:47 UTC
## Bug report

Firebase Firestore has been causing the following ArrayIndexOutOfBoundsException 's as seen reported by Crashalytics.  The following crashes are below:

```
Fatal Exception: java.lang.RuntimeException: Unable to destroy activity {com.company.project/com.company.project.MainActivity}: java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5176)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5205)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

```
Caused by java.lang.ArrayIndexOutOfBoundsException: length=11; index=11
       at android.util.SparseArray.gc(SparseArray.java:217)
       at android.util.SparseArray.size(SparseArray.java:270)
       at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.d(FlutterFirebaseFirestorePlugin.java:3)
       at io.flutter.plugins.firebase.firestore.FlutterFirebaseFirestorePlugin.onDetachedFromEngine(FlutterFirebaseFirestorePlugin.java)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.b(FlutterEnginePluginRegistry.java:118)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.a(FlutterEnginePluginRegistry.java:16)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.removeAll(FlutterEnginePluginRegistry.java:11)
       at io.flutter.embedding.engine.FlutterEnginePluginRegistry.destroy(FlutterEnginePluginRegistry.java:10)
       at io.flutter.embedding.engine.FlutterEngine.a(FlutterEngine.java:9)
       at io.flutter.embedding.android.FlutterActivityAndFragmentDelegate.onDetach(FlutterActivityAndFragmentDelegate.java:90)
       at io.flutter.embedding.android.FlutterActivity.onDestroy(FlutterActivity.java:10)
       at android.app.Activity.performDestroy(Activity.java:8063)
       at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1363)
       at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5161)
       at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5205)
       at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2183)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:241)
       at android.app.ActivityThread.main(ActivityThread.java:7617)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
```

### Steps to reproduce

Unknown at this time

### Expected behavior

Unknown at this time

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.0, on Microsoft Windows [Version 10.0.18363.1316], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (not installed)
[!] VS Code (version 1.52.1)
    X Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
[√] Connected device (1 available)

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
- animations 1.1.2 [flutter]
- bloc 6.1.0 [meta]
- clock 1.1.0-nullsafety.1
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- copy_with_extension 1.4.0
- cupertino_icons 0.1.3
- dash_chat 1.1.15 [flutter flutter_parsed_text uuid intl transparent_image]
- equatable 1.2.5 [collection meta]
- firebase_analytics 6.0.2 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.1+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- firebase_performance 0.4.3 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_barcode_scanner 1.0.1 [flutter flutter_plugin_android_lifecycle]
- flutter_bloc 6.0.6 [flutter bloc provider]
- flutter_local_notifications 3.0.1+6 [flutter platform flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_spinkit 4.1.2+1 [flutter]
- google_fonts 1.1.1 [flutter http path_provider crypto pedantic]
- implicitly_animated_reorderable_list 0.2.5 [flutter async meta]
- intl 0.16.1 [path]
- intl_translation 0.17.10+1 [analyzer args dart_style intl path petitparser]
- json_annotation 3.1.1
- package_info 0.4.3+2 [flutter]
- pedantic 1.10.0-nullsafety.2
- percent_indicator 2.1.8 [flutter]
- provider 4.3.2+2 [flutter nested collection]
- pub_semver 1.4.4 [collection]
- rxdart 0.24.1
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sliver_tools 0.1.9 [flutter]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- vibration 1.7.3 [flutter vibration_web]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-02-02 08:57
There was quite an old similar issue about but it doesn't seem like it should be relevant https://github.com/FirebaseExtended/flutterfire/issues/1287

For now you could try upgrading to the latest version of the plugin.

**Comment by Salakar** [comment] 2021-03-25 13:40
I'm pretty sure this has since been fixed - I've been unable to reproduce so I'm going to go ahead and close this in favour of trying the latest versions out.

**Closed by Salakar** 2021-03-25 13:40 UTC
Labels: plugin: cloud_firestore, type: crash
