### ISSUE TITLE
[firebase_admob] firebase_admob plugin is not compatible with the new firebase_core plugin

### ISSUE THREAD

**Issue by talent-apps** [FirebaseExtended/flutterfire#3340] opened 2020-08-25 07:48 UTC
As per [Migration Guide](https://firebase.flutter.dev/docs/migration/), all firebase plugins have a new version that uses the new [firebase_core](https://pub.dev/packages/firebase_core) plugin **except** firebase_admob.
This prevents apps that use firebase_admob from upgrading all of the firebase plugins to their latest version.

**Comment by SwissCheese5** [comment] 2020-08-25 09:19
Just hit this issue as well.

**Comment by daShrike** [comment] 2020-08-26 00:22
Duplicate of #https://github.com/FirebaseExtended/flutterfire/issues/3209

**Comment by darshankawar** [comment] 2020-08-26 10:43
Hi @talent-apps,
There's similar open issue describing your case, [3209](https://github.com/FirebaseExtended/flutterfire/issues/3209).
Please follow-up there for updates and any questions.
Also, follow [this](https://github.com/FirebaseExtended/flutterfire/issues/3209#issuecomment-675247334) workaround for time-being.
Closing this as duplicate.

**Closed by darshankawar** 2020-08-26 10:43 UTC
