### ISSUE TITLE
[cloud_firestore] The plugin cloud_firestore could not be built due to the issue above.

### ISSUE THREAD

**Issue by rignaneseleo** [FirebaseExtended/flutterfire#1896] opened 2020-01-29 12:21 UTC
I've got this strange bug: if I use 
```yaml
cloud_firestore: ^0.13.0+1
flutter_downloader: ^1.4.0
```
then the project compiles and runs with this error: 

```bash
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

If I remove flutter_downloader (because I'm actually not using it) then I get:

```bash
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Android resource linking failed
  /Users/leo/Dev/Projects/MyGrandKids/my_grand_kids/build/app/intermediates/merged_manifests/debug/AndroidManifest.xml:72: AAPT: error: resource xml/provider_paths (aka boydpearce.my_grand_kids:xml/provider_paths) not found.

  error: failed processing manifest.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 28s
The built failed likely due to AndroidX incompatibilities in a plugin. The tool is about to try using Jetfier to solve the incompatibility.
Building plugin cloud_firestore...
Running Gradle task 'assembleAarRelease'...
Finished with error: The plugin cloud_firestore could not be built due to the issue above.
```

My flutter doctor:
```console
[✓] Flutter (Channel dev, v1.14.3, on Mac OS X 10.15.2 19C57, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.41.1)
[✓] Connected device (2 available)

• No issues found!
```
 
My complete list of plugins:
```yaml
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  #vcontrol-start
  mime_type: ^0.2.4

  #firestore
  firebase_storage: ^3.1.1
  firebase_core: ^0.4.3+2
  firebase_analytics: ^5.0.9
  firebase_messaging: ^6.0.9
  firebase_crashlytics: 0.1.2+4

  cloud_firestore: ^0.13.0+1
  flutter_downloader: ^1.4.0 #<----- I don't need this


  #download
  dio: ^3.0.8

  validators: 2.0.0+1

  encrypt: ^4.0.0
  random_string: ^2.0.1
  flutter_image_compress: ^0.6.5+1
  flutter_typeahead: ^1.7.0
  cached_network_image: 2.0.0-rc
  sqflite: ^1.1.7+3
  http: ^0.12.0+2
  path_provider: 1.5.0
  fluttertoast: ^3.1.3
  flutter_mailer: ^0.4.1+2
  shared_preferences: ^0.5.4+8
  flutter_launcher_icons: ^0.7.4
  file_picker: 1.4.3+2
  auto_size_text: ^2.1.0
  package_info: ^0.4.0+12
  share_extend: 1.1.0
  indexed_list_view: ^1.0.8
  page_indicator: ^0.3.0
  photo:
    path: ./my_flutter_photo
  photo_view: ^0.9.0
  synchronized: ^2.1.1
  contacts_service: ^0.3.10
  permission_handler: ^4.0.0
  flutter_fab_dialer: ^0.1.1
  #chewie is a video player
  chewie: 0.9.8+1
  font_awesome_flutter: 8.5.0
  flutter_cupertino_date_picker: ^1.0.12
  downloads_path_provider:
    git:
      url: git://github.com/jld3103/downloads_path_provider.git
  #vcontrol-end
```

**Comment by rafaelbanhos** [comment] 2020-01-31 17:35
The same here.

**Comment by pigant** [comment] 2020-02-05 17:03
i got the same problem. The message is not acurrate.
i fixed the problem by replacing all the build.gradle with "compileSdkVersion 27" to "compileSdkVersion 28" in the .pub-cache folder
i used this command for finding in mac for findind those files 

`find $HOME/App/flutter/.pub-cache -name build.gradle -type f -exec grep -l "compileSdkVersion 27" {} \; | grep -v 'example'`

**Comment by adbr-dev** [comment] 2020-02-24 08:04
same problem...:(

**Comment by mikron123** [comment] 2020-03-04 11:28
Same

**Comment by rafaelbanhos** [comment] 2020-03-04 11:33
I solved this problem here. Just change gradle version in build.gradle

I put this version: `classpath 'com.android.tools.build:gradle:3.4.2'`

**Comment by SpencerRiddering** [comment] 2020-03-14 03:26
I agree the message is misleading. I was able to resolve the issue by updating my gradle version at
<project>/android/build.gradle to  

    classpath 'com.android.tools.build:gradle:3.3.0'

It's not clear what right version should be though. This problem emerged for me when I added a new package to my pubspec.yaml. I first looked for a build.gradle in that new package, but it didn't have one. Then I looked at the changes made to pubspec.lock and found that some transitive dependency packages were added to my project. I then looked at each of the transitive dependency projects for a build.gradle and found one that had a newer gradle version. Mine was 3.2.1 and the this one was 3.3.0

**Comment by rignaneseleo** [comment] 2020-04-21 14:19
any news?

**Comment by himanshuMaheshwari2311** [comment] 2020-04-21 17:57
changing the classpath to either 3.3.1 or 3.4.2 is not working for me

**Comment by himanshuMaheshwari2311** [comment] 2020-04-23 18:03
```
firebase_core: ^0.4.0+9
firebase_analytics: ^5.0.2
cloud_firestore: ^0.12.9+5
``` 
upgrading to these versions helped me fix the issue

**Comment by talhashahab786** [comment] 2020-04-23 21:47
in my case setting launch_background.xml color was used as hashtag. So reverted back the code. can be a problem in android manifest too inside /app/src

**Comment by allanchao** [comment] 2020-04-29 20:56
In my case, I received this  error, but up above in the log had this:

```

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':flutter_twitter:verifyReleaseResources'.
```

Removing that package resolved the problem

**Comment by Omar-ramadan1** [comment] 2020-05-02 22:01
i'm about to lose my mind about 3 day in the same error any news pls !!

**Comment by ChickenAhn** [comment] 2020-05-12 00:47
> i'm about to lose my mind about 3 day in the same error any news pls !!

I'm trying to figure out what is the root cause while building my flutter app.

try this command and it will tell you what happen here.
```
flutter -v build appbundle
// or
flutter -v build appbundle --flavor 'your_flavor_name' // if you're using flavor for your flutter.
```

FYI, my setting is like this.
```
// android/build.gradle
...
classpath 'com.google.gms:google-services:4.3.3'
...
```

```
// android/app/build.gradle
...
minSdkVersion 21
...
```

I hope it help you.

**Comment by 4toshowjohn** [comment] 2020-06-04 02:13
alguien resolvió el error?

**Comment by rignaneseleo** [comment] 2020-06-04 14:12
@4toshowjohn todavia no! Yo tengo flutter_downloader siempre en mi pubspec.

**Comment by ArbabShujaat** [comment] 2020-06-18 13:16
> In my case setting launch_background.xml color was used as hashtag. So reverted back the code. can be a problem in android manifest too inside /app/src.
> 
> Simply remove a piece of tag code in your XMLs and it will get all fixed up without a hurdle.
> The error is a result of some messed up XML files (corrupted, unreadable, not compilable)
> 
> Thank me later. I do the same each time (y)

Thank you very much this sloved my problem

**Comment by rnagar3434** [comment] 2020-07-03 17:31
same here I am also getting the same error

**Comment by Salakar** [comment] 2020-07-07 22:03
Hey, as part of our on-going work for #2582, we've reworked Firebase Firestore (#2913) which should resolve some previous build issues - this has now been merged into master. We'll look at publishing some prereleases in the next few days which it would be good if you could try. Thank you

**Closed by Salakar** 2020-07-07 22:03 UTC
Labels: impact: customer, plugin: cloud_firestore, type: bug
