### ISSUE TITLE
[firebase_messaging] Background messages not delivered in versions newer than 6.0.3

### ISSUE THREAD

**Issue by LinusU** [FirebaseExtended/flutterfire#1763] opened 2020-01-04 17:03 UTC
**Describe the bug**
When upgrading from version 6.0.3 of firebase_messaging our `onBackgroundMessage` handler is no longer called. Instead the following error is printed to the Android log:

```text
I/flutter (20210): Unable to handle incoming background message.
I/flutter (20210): NoSuchMethodError: The method 'call' was called on null.
I/flutter (20210): Receiver: null
I/flutter (20210): Tried calling: call(_LinkedHashMap len:1)
```

**This occurs even if my handler is just a simple `print` statement**, thus the `null.call(...)` doesn't happen in my handler.

Here is where the error is logged from:

https://github.com/FirebaseExtended/flutterfire/blob/547674c8b550a0b14ff442a3bd6a2663c6dc7680/packages/firebase_messaging/lib/firebase_messaging.dart#L37-L43

**To Reproduce**
1. Add `firebase_messaging` version `6.0.3`
2. Add a background handler that prints something to the log
3. See that the message is received
4. Upgrade to the latest `firebase_messaging` version
5. See that the message is no longer received 

**Expected behavior**
The message should be received with both versions.

**Additional context**
n/a

**Comment by iapicca** [comment] 2020-01-08 11:01
Hi @LinusU 
can you please provide your  your `flutter doctor -v`,
your `pubspec.yaml` 
and your `flutter run --verbose`?
Thank you

**Comment by mklim** [comment] 2020-01-08 19:14
From a discussion in our team chat: this is likely caused by a bug in how we added Android v2 embedding support. See also flutter/flutter#47406, which is showing similar symptoms when running in the background because of a change in the v2 embedding.

/cc @bparrishMines

**Comment by bayuramadeza** [comment] 2020-03-20 07:08
Hi @mklim any update for this issue? cause i can't see notification in background untill now.
@LinusU do you have a solution? i need your help for this issue

**Comment by arputharajraja** [comment] 2020-05-29 06:42
I am also faced this issue after upgrade .. Please register the plugin like below in Application class for android. Now it's working for me 

import io.flutter.app.FlutterApplication
import io.flutter.plugin.common.PluginRegistry
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback
import io.flutter.plugins.GeneratedPluginRegistrant
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService



class Application : FlutterApplication(), PluginRegistrantCallback {
    override fun onCreate() {
        super.onCreate()
        FlutterFirebaseMessagingService.setPluginRegistrant(this)
    }

    override fun registerWith(registry: PluginRegistry) {
       // GeneratedPluginRegistrant.registerWith(registry);
        io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
        io.flutter.plugins.pathprovider.PathProviderPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.pathprovider.PathProviderPlugin"));
        com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin.registerWith(registry?.registrarFor("com.dexterous.flutterlocalnotifications.FlutterLocalNotificationsPlugin"));       // registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin");
        fr.g123k.flutterappbadger.FlutterAppBadgerPlugin.registerWith(registry?.registrarFor("fr.g123k.flutterappbadger.FlutterAppBadgerPlugin"));
    }
}

**Comment by arputharajraja** [comment] 2020-05-29 06:45
Need add below lines 
io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry?.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
instead of 
GeneratedPluginRegistrant.registerWith(registry);

**Comment by Moizsohail** [comment] 2020-06-30 12:05
Any solutions?

**Comment by Moizsohail** [comment] 2020-06-30 12:07
Also can you please expound on the background handler? How are you logging a backgrounded application?

**Comment by gregertw** [comment] 2020-07-20 06:14
Note that the comments in this thread shows two different things, one is a user error, the other is a bug:

1. The [documentation](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging#sending-messages) documents that you need to include click_action=FLUTTER_NOTIFICATION_CLICK in the message, also elsewhere (not able to find it now), it is documented that only data messages can be sent to backgrounded applications. If you thus use curl as described to send a message, but REMOVES the notification part of the message (i.e. `DATA='{"data": {"click_action": "FLUTTER_NOTIFICATION_CLICK", "id": "1", "status": "done"}, "to": "<token>"}'`), you will be able to send a message that is received, however...
2. Issue 2 is a bug (a similar issues with alarms is referred above) where the the LinkedMap of callbacks is not initialised. This issue title refers to >6.0.3 as the breaking point, however, I see the same error message with firebase_messaging=6.0.2

**Comment by Salakar** [comment] 2020-11-05 10:17
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone.

**Closed by Salakar** 2020-11-05 10:17 UTC
Labels: impact: crowd, plugin: messaging, severe: regression, type: bug
