### ISSUE TITLE
🐛 [Crashlytics] Failed to retrieve settings from [URL]

### ISSUE THREAD

**Issue by marcobraghim** [FirebaseExtended/flutterfire#3786] opened 2020-10-06 14:15 UTC
## Bug report

**Describe the bug**
I just can not start report bugs to crashlytics

### Steps to reproduce

1. Create an Android app on Firebase
2. Follow this steps to setup Firebase https://firebase.flutter.dev/docs/installation/android
3. Follow this steps to setup Crashlytics https://firebase.flutter.dev/docs/crashlytics/overview
4. Run App with this line to force a crash FirebaseCrashlytics.instance.crash();
5. Run App again without this line above to report crash to Crashlytics

### Expected behavior

Crashlytics should get this error and start to track errors dispatched on the App, but I got the error below instead:

```
E/FirebaseCrashlytics( 7833): Failed to retrieve settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:579174145361:android:4434dbe91d2132538a4770/settings
```

---

## Additional context

```
flutter run -d emulator-5554
Using hardware rendering with device sdk gphone x86. If you notice graphics artifacts, consider
enabling software rendering with "--enable-software-rendering".
Launching lib/main.dart on sdk gphone x86 in debug mode...
Running Gradle task 'assembleDebug'...                                  
Running Gradle task 'assembleDebug'... Done                        36,3s
✓ Built build/app/outputs/flutter-apk/app-debug.apk.
Installing build/app/outputs/flutter-apk/app.apk...                 4,9s
Waiting for sdk gphone x86 to report its views...                   14ms
D/AndroidRuntime( 7833): Shutting down VM                               
E/AndroidRuntime( 7833): FATAL EXCEPTION: main                          
E/AndroidRuntime( 7833): Process: com.gotchosen.gotchosenmi, PID: 7833  
E/AndroidRuntime( 7833): io.flutter.plugins.firebase.crashlytics.FirebaseCrashlyticsTestCrash: This is a test crash caused by calling .crash() in Dart.
E/AndroidRuntime( 7833):        at io.flutter.plugins.firebase.crashlytics.FlutterFirebaseCrashlyticsPlugin.lambda$crash$1(FlutterFirebaseCrashlyticsPlugin.java:81)
E/AndroidRuntime( 7833):        at io.flutter.plugins.firebase.crashlytics.-$$Lambda$FlutterFirebaseCrashlyticsPlugin$H0t0BleSpjDMVvqpx8Hy-ZKGwP8.run(Unknown Source:0)
E/AndroidRuntime( 7833):        at android.os.Handler.handleCallback(Handler.java:907)
E/AndroidRuntime( 7833):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 7833):        at android.os.Looper.loop(Looper.java:216)
E/AndroidRuntime( 7833):        at android.app.ActivityThread.main(ActivityThread.java:7464)
E/AndroidRuntime( 7833):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 7833):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:549)
E/AndroidRuntime( 7833):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:955)
E/FirebaseCrashlytics( 7833): Failed to retrieve settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:579174145361:android:4434dbe91d2132538a4770/settings
Syncing files to device sdk gphone x86...                               
I/Process ( 7833): Sending signal. PID: 7833 SIG: 9             
Syncing files to device sdk gphone x86...                                                            Lost connection to device.                                      
Syncing files to device sdk gphone x86...                                                            Could not update files on device: HttpException: Connection closed before full header was received,
uri = http://127.0.0.1:41299/nWRDMmudj1E=/
Syncing files to device sdk gphone x86... 
```

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor -v
[✓] Flutter (Channel stable, 1.22.0, on Linux, locale pt_BR.UTF-8)
    • Flutter version 1.22.0 at /home/nedstark/Documentos/software/flutter
    • Framework revision d408d302e2 (7 days ago), 2020-09-29 11:49:17 -0700
    • Engine revision 5babba6c4d
    • Dart version 2.10.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /home/nedstark/Android/Sdk
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /home/nedstark/Documentos/software/android-studio/jre/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Android Studio (version 4.0)
    • Android Studio at /home/nedstark/Documentos/software/android-studio
    • Flutter plugin version 48.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.49.3)
    • VS Code at /usr/share/code
    • Flutter extension version 3.15.0

[✓] Connected device (1 available)
    • sdk gphone x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.0
Flutter SDK 1.22.0
gotchosenmi 1.0.0+1

dependencies:
- connectivity 0.4.9+3 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- cupertino_icons 1.0.0
- dio 3.0.10 [http_parser path]
- easy_localization 2.3.3 [flutter intl shared_preferences args path flutter_localizations]
- email_validator 1.0.5
- file_picker 2.0.6 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_core 0.5.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- flare_flutter 2.0.6 [flutter flare_dart meta]
- flushbar 1.10.4 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_better_camera 0.6.1 [flutter]
- flutter_datetime_picker 1.4.0 [flutter]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_ffmpeg 0.3.0 [flutter]
- flutter_mobx 1.1.0+2 [mobx flutter]
- flutter_modular 2.0.1 [flutter]
- flutter_secure_storage 3.3.4 [meta flutter]
- flutter_share 1.0.2+1 [flutter]
- flutter_staggered_grid_view 0.3.2 [flutter]
- google_fonts 1.1.0 [flutter http path_provider crypto pedantic]
- gradient_progress 0.1.0 [flutter]
- image_cropper 1.3.1 [flutter]
- image_gallery_saver 1.5.0 [flutter]
- image_picker 0.6.7+11 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- mobx 1.2.1+2 [meta]
- path_provider 1.6.18 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- preload_page_view 0.1.4 [flutter]
- shared_preferences 0.5.12 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- video_player 0.10.12+5 [meta video_player_platform_interface video_player_web flutter]

dev dependencies:
- build_runner 1.10.1 [analyzer args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mobx_codegen 1.1.0+2 [analyzer build build_resolvers meta mobx path source_gen]
- mockito 4.1.1 [collection matcher meta test_api]

transitive dependencies:
- _fe_analyzer_shared 6.0.0 [meta]
- analyzer 0.39.14 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob html meta package_config path pub_semver source_span watcher yaml]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.3.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.3.11 [analyzer build crypto graphs logging path package_config pub_semver]
- build_runner_core 6.0.1 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.1.4 [path]
- clock 1.1.0-nullsafety.1
- code_builder 3.4.1 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- connectivity_for_web 0.3.1+2 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+5 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.6 [analyzer args path source_span]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.0 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flare_dart 2.3.4
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- html 0.14.0+4 [csslib source_span]
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.1.0
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.0
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.3 [matcher meta]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.0 [path process flutter]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by vmadupu9** [comment] 2020-10-07 06:08
I faced the same issue . Crashlytics did not get enabled due to this issue. After some searching for answers i have added `Firebase Crashlytics 17.2.2`  sdk in `android/app/build.gradle`. This step is not mention in https://firebase.flutter.dev/docs/crashlytics/overview but i have found it in one of the official document . After adding this line my crashyltics console got enabled. @marcobraghim  can you check this and confirm. 


![CleanShot 2020-10-07 at 11 33 04@2x](https://user-images.githubusercontent.com/67674262/95293470-1923f880-0891-11eb-9384-c68d0cdad591.png)

**Comment by vmadupu9** [comment] 2020-10-07 06:17
I just had a look into the official firebase documentation . The comment which i mentioned above is part of [Crashlytics Initialisation](https://firebase.google.com/docs/crashlytics/get-started?platform=android&authuser=3#initialize-crashlytics) without using BoM.

**Comment by Salakar** [comment] 2020-10-07 11:12
Duplicate of #3669

**Closed by Salakar** 2020-10-07 11:12 UTC
Labels: Needs Attention, type: bug

**Comment by marcobraghim** [comment] 2020-10-07 13:46
> I faced the same issue . Crashlytics did not get enabled due to this issue. After some searching for answers i have added `Firebase Crashlytics 17.2.2` sdk in `android/app/build.gradle`. This step is not mention in https://firebase.flutter.dev/docs/crashlytics/overview but i have found it in one of the official document . After adding this line my crashyltics console got enabled. @marcobraghim can you check this and confirm.
> 
> `implementation 'com.google.firebase:firebase-crashlytics:17.2.2'`
> 
> ![CleanShot 2020-10-07 at 11 33 04@2x](https://user-images.githubusercontent.com/67674262/95293470-1923f880-0891-11eb-9384-c68d0cdad591.png)

Yeah!! It works! Thank you very much!
