### ISSUE TITLE
Face detector in ios  14.0 not working

### ISSUE THREAD

**Issue by ronitP12** [FirebaseExtended/flutterfire#5902] opened 2021-04-23 12:22 UTC
The method  "**_faceDetector.processImage(visionImage)**"  
 i am calling for face detection in ios but,
this method is not returning any response or output. but the android side this is working.

**Comment by Salakar** [comment] 2021-04-23 12:30
Duplicate of #5899

**Closed by Salakar** 2021-04-23 12:30 UTC
Labels: Needs Attention, type: bug
