### ISSUE TITLE
Cloud Firestore Flutter java.lang.NullPointException

### ISSUE THREAD

**Issue by Aashishm178** [FirebaseExtended/flutterfire#2390] opened 2020-04-17 17:24 UTC
When I try to setData to a nested collection in cloud firestore , this error comes and forces my app to shut down but it happens only one particular collection and none other collection.

```
D/AndroidRuntime( 9744): Shutting down VM
E/AndroidRuntime( 9744): FATAL EXCEPTION: main
E/AndroidRuntime( 9744): Process: com.example.chatbot, PID: 9744
E/AndroidRuntime( 9744): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 9744): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:451)
E/AndroidRuntime( 9744): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:433)
E/AndroidRuntime( 9744): 	at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.0:1025)
E/AndroidRuntime( 9744): 	at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
E/AndroidRuntime( 9744): 	at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.0:42)
E/AndroidRuntime( 9744): 	at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
E/AndroidRuntime( 9744): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime( 9744): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime( 9744): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime( 9744): 	at android.app.ActivityThread.main(ActivityThread.java:7682)
E/AndroidRuntime( 9744): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 9744): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
E/AndroidRuntime( 9744): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/Process ( 9744): Sending signal. PID: 9744 SIG: 9
Lost connection to device.
```

**Comment by Ehesp** [comment] 2020-04-18 08:07
Hi @Aashishm178 please could you show some code usage.

**Comment by Aashishm178** [comment] 2020-04-18 08:17
This is happening when i am clicking the button 
Here is the function of the button click 
Its purpose is to setData on the specified document in cloud firestore but it is crashing my app but the data is been set to  firestore , I checked it through my firebase console , the changes which were intended were happening but my app keeps on crashing again again.
It is inside a stream builder which has a listview.builder child

try {
                                                              await _firestore
                                                                  .collection(
                                                                      'users')
                                                                  .document(snapshot
                                                                          .data
                                                                          .documents[index]
                                                                      [
                                                                      'UserId'])
                                                                  .collection(
                                                                      'FriendRequest')
                                                                  .document()
                                                                  .setData({
                                                                'UserId': widget
                                                                    .firebaseUser
                                                                    .uid,
                                                                'UserEmail': widget
                                                                    .firebaseUser
                                                                    .email,
                                                                'time': DateTime
                                                                        .now()
                                                                    .toIso8601String(),
                                                              });
                                                              Navigator.of(
                                                                      context)
                                                                  .pop();
                                                              scaffoldKey
                                                                  .currentState
                                                                  .hideCurrentSnackBar();
                                                              SnackBar snack = SnackBar(
                                                                  action: SnackBarAction(
                                                                      textColor:
                                                                          Colors
                                                                              .purpleAccent,
                                                                      label:
                                                                          'OK',
                                                                      onPressed:
                                                                          () {}),
                                                                  elevation:
                                                                      6.0,
                                                                  behavior:
                                                                      SnackBarBehavior
                                                                          .floating,
                                                                  duration:
                                                                      Duration(
                                                                          seconds:
                                                                              4),
                                                                  content: Text(
                                                                      'REQUEST SENT SUCCESSFULLY'));
                                                              scaffoldKey
                                                                  .currentState
                                                                  .showSnackBar(
                                                                      snack);
                                                              searchController
                                                                  .clear();
                                                            } catch (error) {
                                                              print(error);
                                                            }

**Comment by ZatacaSystems** [comment] 2020-04-23 15:00
for me it happens when I press a button aswell:

`InkResponse(
                    onTap: () {
                      if (_tecMessage.text.isNotEmpty) {
                        _blocChat.add(
                          Event(
                            ChatEventType.sendMessageButtonPressed,
                            data: _tecMessage.text.trim(),
                          ),
                        );
                        _tecMessage.clear();
                      }
                    },
                    child: Container(
                      margin: EdgeInsets.all(5.0),
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        color: Theme.of(context).primaryColor,
                      ),
                      padding: EdgeInsets.all(12.0),
                      child: SvgPicture.asset(
                        'lib/main/images/ic_chat_send_white.svg',
                      ),
                    ),
                  ),`

pressing the button executes this code on the bloc:

`case ChatEventType.sendMessageButtonPressed:
        try {
          await messagesCollectionReference.add(<String, dynamic>{
            'message': event.data,
            'date': FieldValue.serverTimestamp(),
            'fk_from': _userType == 1 ? _patientId : _doctorId,
          });
        } catch (e, s) {
          print('${this.runtimeType} -> $e | $s');
        }
        yield event;
        break;`

It's strange cause it crashes 1 time, then I reopen the app and then it does not crashes, and then I close again an reopen again and it crashes again. That goes on and on

**Comment by ZatacaSystems** [comment] 2020-04-23 15:38
When I try to send a message the app crashes. It's strange cause it works nice the 1st time the app is launched, then I reopen the app and then it crashes, and then I close again an reopen again and it works again, and that goes on and on:

```
D/AndroidRuntime(25841): Shutting down VM
E/AndroidRuntime(25841): FATAL EXCEPTION: main
E/AndroidRuntime(25841): Process: com.example.social_doctor_app, PID: 25841
E/AndroidRuntime(25841): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(25841):        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:451)
E/AndroidRuntime(25841):        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:433)
E/AndroidRuntime(25841):        at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.0:1025)
E/AndroidRuntime(25841):        at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
E/AndroidRuntime(25841):        at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.0:42)
E/AndroidRuntime(25841):        at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
E/AndroidRuntime(25841):        at android.os.Handler.handleCallback(Handler.java:873)
E/AndroidRuntime(25841):        at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(25841):        at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(25841):        at android.app.ActivityThread.main(ActivityThread.java:6865)
E/AndroidRuntime(25841):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(25841):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
E/AndroidRuntime(25841):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
my code:

```dart
InkResponse(
                    onTap: () {
                      if (_tecMessage.text.isNotEmpty) {
                        _blocChat.add(
                          Event(
                            ChatEventType.sendMessageButtonPressed,
                            data: _tecMessage.text.trim(),
                          ),
                        );
                        _tecMessage.clear();
                      }
                    },
                    child: Container(
                      margin: EdgeInsets.all(5.0),
                      decoration: BoxDecoration(
                        shape: BoxShape.circle,
                        color: Theme.of(context).primaryColor,
                      ),
                      padding: EdgeInsets.all(12.0),
                      child: SvgPicture.asset(
                        'lib/main/images/ic_chat_send_white.svg',
                      ),
                    ),
                  ),
```

pressing the button executes this code on the bloc:

```dart
case ChatEventType.sendMessageButtonPressed:
        try {
          await _firestore.collection(_tableName).add(<String, dynamic>{
            'message': event.data,
            'date': FieldValue.serverTimestamp(),
            'fk_from': _userType == 1 ? _patientId : _doctorId,
          });
        } catch (e, s) {
          print('${this.runtimeType} -> $e | $s');
        }
        yield event;
        break;
```

Flutter doctor -v:
```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale es-ES)
    • Flutter version 1.12.13+hotfix.8 at /Users/jose/developement/flutter
    • Framework revision 0b8abb4724 (2 months ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jose/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4, Build version 11E146
    • CocoaPods version 1.9.1

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 44.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.44.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.1

[✓] Connected device (1 available)
    • 5024D EEA • V7LB18BBMMC01BI • android-arm64 • Android 9 (API 28)

• No issues found!
```

I have tried with flutter run and with flutter run --release

`cloud_firestore: ^0.13.5`

**Comment by Aashishm178** [comment] 2020-04-23 15:41
> When I try to send a message the app crashes. It's strange cause it works nice the 1st time the app is launched, then I reopen the app and then it crashes, and then I close again an reopen again and it works again, and that goes on and on:
> 
> ```
> D/AndroidRuntime(25841): Shutting down VM
> E/AndroidRuntime(25841): FATAL EXCEPTION: main
> E/AndroidRuntime(25841): Process: com.example.social_doctor_app, PID: 25841
> E/AndroidRuntime(25841): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
> E/AndroidRuntime(25841):        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:451)
> E/AndroidRuntime(25841):        at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:433)
> E/AndroidRuntime(25841):        at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.0:1025)
> E/AndroidRuntime(25841):        at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
> E/AndroidRuntime(25841):        at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.0:42)
> E/AndroidRuntime(25841):        at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
> E/AndroidRuntime(25841):        at android.os.Handler.handleCallback(Handler.java:873)
> E/AndroidRuntime(25841):        at android.os.Handler.dispatchMessage(Handler.java:99)
> E/AndroidRuntime(25841):        at android.os.Looper.loop(Looper.java:193)
> E/AndroidRuntime(25841):        at android.app.ActivityThread.main(ActivityThread.java:6865)
> E/AndroidRuntime(25841):        at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(25841):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:504)
> E/AndroidRuntime(25841):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> ```
> my code:
> 
> ```dart
> InkResponse(
>                     onTap: () {
>                       if (_tecMessage.text.isNotEmpty) {
>                         _blocChat.add(
>                           Event(
>                             ChatEventType.sendMessageButtonPressed,
>                             data: _tecMessage.text.trim(),
>                           ),
>                         );
>                         _tecMessage.clear();
>                       }
>                     },
>                     child: Container(
>                       margin: EdgeInsets.all(5.0),
>                       decoration: BoxDecoration(
>                         shape: BoxShape.circle,
>                         color: Theme.of(context).primaryColor,
>                       ),
>                       padding: EdgeInsets.all(12.0),
>                       child: SvgPicture.asset(
>                         'lib/main/images/ic_chat_send_white.svg',
>                       ),
>                     ),
>                   ),
> ```
> 
> pressing the button executes this code on the bloc:
> 
> ```dart
> case ChatEventType.sendMessageButtonPressed:
>         try {
>           await _firestore.collection(_tableName).add(<String, dynamic>{
>             'message': event.data,
>             'date': FieldValue.serverTimestamp(),
>             'fk_from': _userType == 1 ? _patientId : _doctorId,
>           });
>         } catch (e, s) {
>           print('${this.runtimeType} -> $e | $s');
>         }
>         yield event;
>         break;
> ```
> 
> Flutter doctor -v:
> ```
> [✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.2 19C57, locale es-ES)
>     • Flutter version 1.12.13+hotfix.8 at /Users/jose/developement/flutter
>     • Framework revision 0b8abb4724 (2 months ago), 2020-02-11 11:44:36 -0800
>     • Engine revision e1e6ced81d
>     • Dart version 2.7.0
> 
>  
> [✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
>     • Android SDK at /Users/jose/Library/Android/sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.2
>     • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
>     • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 11.4)
>     • Xcode at /Applications/Xcode.app/Contents/Developer
>     • Xcode 11.4, Build version 11E146
>     • CocoaPods version 1.9.1
> 
> [✓] Android Studio (version 3.5)
>     • Android Studio at /Applications/Android Studio.app/Contents
>     • Flutter plugin version 44.0.1
>     • Dart plugin version 191.8593
>     • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
> 
> [✓] VS Code (version 1.44.2)
>     • VS Code at /Applications/Visual Studio Code.app/Contents
>     • Flutter extension version 3.9.1
> 
> [✓] Connected device (1 available)
>     • 5024D EEA • V7LB18BBMMC01BI • android-arm64 • Android 9 (API 28)
> 
> • No issues found!
> ```
> 
> I have tried with flutter run and with flutter run --release
> 
> `cloud_firestore: ^0.13.5`

I have the same exact issue with cloud_firestore plugin 
Sometimes it works and sometimes it crashes the app

**Comment by ZatacaSystems** [comment] 2020-04-23 18:54
**UPDATE**
I can confirm that this is not happening with version 0.13.1

**Comment by orestesgaolin** [comment] 2020-04-24 14:57
This error occurs also on cloud_firestore 0.13.5. The stack trace is a bit different, but the reason seems to be similar. I don't have reproducible steps unfrotunately.

Using with current beta Flutter v1.17.0-33.2.pre

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void e.b.b.a.j.a(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.a(CloudFirestorePlugin.java:106)
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.a(CloudFirestorePlugin.java:2)
       at com.google.firebase.firestore.DocumentReference.a(DocumentReference.java:87)
       at com.google.firebase.firestore.DocumentReference$$Lambda$3.a(DocumentReference.java:6)
       at com.google.firebase.firestore.core.AsyncEventListener.a(AsyncEventListener.java:6)
       at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(AsyncEventListener.java:6)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6854)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:860)
```

**Comment by orestesgaolin** [comment] 2020-04-27 12:42
I believe that this issue shouldn't have `blocked: customer-response` label anymore

**Comment by hudsoncadan** [comment] 2020-05-02 14:41
I face this error in the following scenario:
- When I run the app for the first time it works perfectly.
- If I press the back button on Android, run the app for the second time then I try to update some document in Firestore, the app crashes.

I'm working with a StreamBuilder and cloud_firestore: ^0.13.5

```
Shutting down VM
E/AndroidRuntime(32722): FATAL EXCEPTION: main
E/AndroidRuntime(32722): Process: br.com.test, PID: 32722
E/AndroidRuntime(32722): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(32722): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:451)
E/AndroidRuntime(32722): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:433)
E/AndroidRuntime(32722): 	at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.0:1025)
E/AndroidRuntime(32722): 	at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
E/AndroidRuntime(32722): 	at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.0:42)
E/AndroidRuntime(32722): 	at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
E/AndroidRuntime(32722): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(32722): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(32722): 	at android.os.Looper.loop(Looper.java:235)
E/AndroidRuntime(32722): 	at android.app.ActivityThread.main(ActivityThread.java:7441)
E/AndroidRuntime(32722): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(32722): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(32722): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

flutter doctor -v

```
[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [versÃ£o 10.0.18363.592], locale pt-BR)
    • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
    • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:\Users\hudso\AppData\Local\Android\sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] Connected device (2 available)
    • XT1033     • [I REMOVED IT] • android-arm   • Android 5.1 (API 22)
    • ASUS Z01RD • [I REMOVED IT] • android-arm64 • Android 10 (API 29)

• No issues found!
```

**Comment by ZatacaSystems** [comment] 2020-05-02 14:53
> I face this error in the following scenario:
> 
> * When I run the app for the first time it works perfectly.
> * If I press the back button on Android, run the app for the second time then I try to update some document in Firestore, the app crashes.
> 
> I'm working with a StreamBuilder and cloud_firestore: ^0.13.5
> 
> ```
> Shutting down VM
> E/AndroidRuntime(32722): FATAL EXCEPTION: main
> E/AndroidRuntime(32722): Process: br.com.test, PID: 32722
> E/AndroidRuntime(32722): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
> E/AndroidRuntime(32722): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:451)
> E/AndroidRuntime(32722): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:433)
> E/AndroidRuntime(32722): 	at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.0:1025)
> E/AndroidRuntime(32722): 	at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
> E/AndroidRuntime(32722): 	at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.0:42)
> E/AndroidRuntime(32722): 	at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
> E/AndroidRuntime(32722): 	at android.os.Handler.handleCallback(Handler.java:883)
> E/AndroidRuntime(32722): 	at android.os.Handler.dispatchMessage(Handler.java:100)
> E/AndroidRuntime(32722): 	at android.os.Looper.loop(Looper.java:235)
> E/AndroidRuntime(32722): 	at android.app.ActivityThread.main(ActivityThread.java:7441)
> E/AndroidRuntime(32722): 	at java.lang.reflect.Method.invoke(Native Method)
> E/AndroidRuntime(32722): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
> E/AndroidRuntime(32722): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
> ```
> 
> flutter doctor -v
> 
> ```
> [√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [versÃ£o 10.0.18363.592], locale pt-BR)
>     • Flutter version 1.12.13+hotfix.9 at C:\src\flutter
>     • Framework revision f139b11009 (5 weeks ago), 2020-03-30 13:57:30 -0700
>     • Engine revision af51afceb8
>     • Dart version 2.7.2
> 
> [√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
>     • Android SDK at C:\Users\hudso\AppData\Local\Android\sdk
>     • Android NDK location not configured (optional; useful for native profiling support)
>     • Platform android-29, build-tools 29.0.3
>     • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
>     • All Android licenses accepted.
> 
> [√] Android Studio (version 3.6)
>     • Android Studio at C:\Program Files\Android\Android Studio
>     • Flutter plugin version 45.1.1
>     • Dart plugin version 192.7761
>     • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
> 
> [√] Connected device (2 available)
>     • XT1033     • [I REMOVED IT] • android-arm   • Android 5.1 (API 22)
>     • ASUS Z01RD • [I REMOVED IT] • android-arm64 • Android 10 (API 29)
> 
> • No issues found!
> ```

https://github.com/FirebaseExtended/flutterfire/issues/2390#issuecomment-618591127

**Comment by hudsoncadan** [comment] 2020-05-05 01:55
@ZatacaSystems thank you for your comment. 
Unfortunately If I downgrade to 0.13.1 version, I will get back to others issues.
Now I'm using 0.13.4 version. It's working for now.

**Comment by kepuza** [comment] 2020-05-05 18:55
i have same problem  cloud_firestore: ^0.13.5 version

**Comment by orestesgaolin** [comment] 2020-05-07 13:05
> @ZatacaSystems thank you for your comment.
> Unfortunately If I downgrade to 0.13.1 version, I will get back to others issues.
> Now I'm using 0.13.4 version. It's working for now.
Can you confirm that 0.13.4 doesn't have this issue?

**Comment by kepuza** [comment] 2020-05-07 17:14
> > @ZatacaSystems thank you for your comment.
> > Unfortunately If I downgrade to 0.13.1 version, I will get back to others issues.
> > Now I'm using 0.13.4 version. It's working for now.
> 
> Can you confirm that 0.13.4 doesn't have this issue?

I came back to that version got the same problem

**Comment by funeasysoft** [comment] 2020-05-08 16:47
I had same problem cloud_firestore: ^0.13.5.
I solved the problem this way.

```
class MainApp extends StatefulWidget {
  @override
  _MainAppState createState() => _MainAppState();
}

class _MainAppState extends State<MainApp>  {
  var _listener;
   @override
  void initState() {
    super.initState();

    _listener = _userRef.document("data").snapshots().listen((snapshot) {
      // some code
    });
  }
  
  Future removeListener() async {
    if (_listener != null) {
      await _listener.cancel();
      print("user _listener cancel");
  }

  @override
  Widget build(BuildContext context) {
    return WillPopScope(
        onWillPop: () {
          removeListener().then((value) {
            print("cancel done");
            SystemNavigator.pop();
          });
        },
        child: // some view
  }
}
```

I think, we need to cancel the listener, before push the back button.

**Comment by niypoo** [comment] 2020-05-11 02:38
ّI have similar issue  and I using  0.13.5 
the scenario that happened with me  is

in production mode and it's happened once time and don't happened if I try same action I have did , so when try add item in firebase it's crashing and if return try same item in same condition maybe didn't crashed but I have cashed these issues.
 

```
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent (CloudFirestorePlugin.java:451)
io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent (CloudFirestorePlugin.java:433)
com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2 (com.google.firebase:firebase-firestore@@21.3.0:1025)
com.google.firebase.firestore.Query$$Lambda$3.onEvent (Unknown Source:6)
com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0 (com.google.firebase:firebase-firestore@@21.3.0:42)
com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run (Unknown Source:6)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
com.google.android.gms.internal.tasks.zzb.dispatchMessage (com.google.android.gms:play-services-tasks@@17.0.2:6)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7156)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:975)
```

**Comment by lemonxah** [comment] 2020-05-19 07:35
same error here is my stack trace,

```Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'void d.a.b.a.i.a(java.lang.String, java.lang.Object)' on a null object reference
io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.a (CloudFirestorePlugin.java:33)
io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.a (CloudFirestorePlugin.java:2)
com.google.firebase.firestore.Query.a (Query.java:27)
com.google.firebase.firestore.Query$$Lambda$3.a (Query.java:6)
com.google.firebase.firestore.core.AsyncEventListener.a (AsyncEventListener.java:6)
com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run (AsyncEventListener.java:6)
android.os.Handler.handleCallback (Handler.java:883)
android.os.Handler.dispatchMessage (Handler.java:100)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7857)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)```

**Comment by lemonxah** [comment] 2020-05-19 07:36
i have gone down to 0.13.1 and will test to make sure that i dont get that error, unfortunately this is a new app so i dont know when this was introduced since i started with 0.13.5. It works 95% of the time and then out of the blue the app dies, you start it back up and everything works again even the thing that made it crash. also FYI this happens on a delete, add, update and even on the remote phone that has Streambuilders for the data that is being changed. Sometimes just deleting a list item on my phone crashes my wife's phone.

*update*
I have not had a crash yet after downgrading the library. Will keep updated

**Comment by lemonxah** [comment] 2020-05-25 15:53
0.13.4 is also fine for my usrcase also no crashes thusfar

**Comment by orestesgaolin** [comment] 2020-05-25 18:01
I also downgraded cloud_firestore to 0.13.4+2 few days ago and no issues so far

**Comment by Ehesp** [comment] 2020-05-26 18:17
Does anyone have a Map of data which contains whatever is causing the pointer exception?

**Comment by carloxavier** [comment] 2020-05-31 15:30
this is also happening to our app, here's the [gist of the stacktrace](https://gist.github.com/carloxavier/82ac4e168f5aeb4e7c634fb100a57270).
we are using the `cloud_firestore: 0.13.6`.

**steps to reproduce**:  We have a `setDocument` transaction being run whenever a button is clicked. When the app starts clean, executing the transaction is not crashing the app, but it only crashes whenever we exit the app by back-button and then we come back to the app and execute this transaction. 

In concrete, this crashes when we call `Transaction::set(...)`, and interestingly the transaction does complete successfully each and every time this crashes.
_(similar steps described by https://github.com/FirebaseExtended/flutterfire/issues/2390#issuecomment-622963868)_

**Comment by carloxavier** [comment] 2020-05-31 15:40
It does solve the crash in our case when we downgrade to `cloud_firestore: 0.13.4+2`, but there's still a message printed that may give hints on what's actually going on:
```
W/FlutterJNI(24945): Tried to send a platform message to Flutter, but FlutterJNI was detached from native C++. Could not send. Channel: plugins.flutter.io/cloud_firestore. Response ID: 0
```

**Comment by andcea** [comment] 2020-06-01 11:30
Using the steps mentioned by @carloxavier above I managed to reproduce the issue 100% of the time. All you have to do is exit the app using the back button on Android, and on resume trigger a firestore write. In my case, I have a toggle button on the home screen that does a firestore update.

Downgrading to `cloud_firestore: 0.13.4+2` did not help for me for some reason.

It's quite scary that this bug has been opened for more than a month and there's been little official support.

My crash-rate is around 5% because of this bug according to Crashlytics and I'm getting customer complaints and bad reviews.

Please treat this with urgency. I'm happy to help if you need anything else from me.

**Comment by carloxavier** [comment] 2020-06-01 11:38
hey I just found that the crash has actually been solved a few days ago on a fork but it hasn't been merged: https://github.com/lidongze91/flutterfire/commit/a2f5abf7d2a6cbb78d0f2f51665c98e49bb378af

we just need to be a bit patient

**Comment by andcea** [comment] 2020-06-01 12:02
@carloxavier thanks for that.
I can confirm that fix is working. I've used that package directly by
```
  cloud_firestore:
    git:
      url: git://github.com/lidongze91/flutterfire.git
      path: packages/cloud_firestore/cloud_firestore
      ref: bb5683a
```

**Comment by johnvinosh** [comment] 2020-06-19 07:12
This bug is annoying me a lot. Lot of crash issues reported because of this error. I downgraded the Firestore version 0.13.4 but still the issue persists. Any idea when this will be merged to the Master branch ?

**Closed** 2020-06-19 16:07 UTC
Labels: blocked: customer-response, plugin: cloud_firestore, type: bug
