### ISSUE TITLE
🐛 [firebase_admob] iOS init App Tracking Transparency

### ISSUE THREAD

**Issue by ElaineSchwner** [FirebaseExtended/flutterfire#4308] opened 2020-12-03 11:01 UTC
I sent an App to Apple review and followed the documentation.

An I got this message from Apple ResolutionCenter:

Specifically, we were unable to locate or trigger the App Tracking Transparency modal alert in your app.
Please provide us with steps to locate the AppTrackingTransperancy in the app.

In the lib there is no way to trigger the modal.

Thank you

**Comment by markusaksli-nc** [comment] 2020-12-03 13:06
Hi @ElaineSchwner 
I see that you have already opened an issue regarding this case.
Closing this one as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4271.
Thank you

**Closed by markusaksli-nc** 2020-12-03 13:06 UTC
Labels: Needs Attention, type: bug
