### ISSUE TITLE
[firebase_dynamic_links] auth links dont pass to app on iOS

### ISSUE THREAD

**Issue by Bazilikum** [FirebaseExtended/flutterfire#1571] opened 2019-12-06 13:47 UTC
**Describe the bug**
When using authentication by email link, the link will work and call the "OnLink" delegate only on Android. On iOS will open the app but wont call the delegate.

**To Reproduce**
1. Send a request for email link login from an open app on iOS device (not simulator)
2. Switch to email and activate link on the device
3. iOS will switch back to the app but the "OnLink" delegate wont be called.

**Expected behavior**
"OnLink" is called and link is parsed.

**Additional context**
Followed all the instruction on https://pub.dev/packages/firebase_dynamic_links

flutter doctor -v output:
```bash
[✓] Flutter (Channel stable, v1.9.1+hotfix.6, on Mac OS X 10.15.1 19B2106, locale en-DE)
    • Flutter version 1.9.1+hotfix.6 at /Users/.../flutter
    • Framework revision 68587a0916 (3 months ago), 2019-09-13 19:46:58 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/.../Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Users/.../Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Users/.../Library/Application
      Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/191.5977832/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] Connected device (1 available)
    • ... • fa23d... • ios • iOS 13.1.3

• No issues found!

```

**Comment by Bazilikum** [comment] 2019-12-07 17:54
Might be related to [https://github.com/firebase/firebase-ios-sdk/issues/3918](https://github.com/firebase/firebase-ios-sdk/issues/3918)
The call to scene delegate instead of app delegate not being implemented in Flutter?

**Comment by cgrain** [comment] 2020-02-27 16:16
I also encounter this issue, and I was wondering if anybody already has a work-around or a fix for this.

**Comment by dpedrinha** [comment] 2020-03-03 02:45
I'm having a similar problem. Most my iOS users can login but some just can't no matter what. The email activation link sends the user to the App Store instead of opening the app. I can't reproduce the problem since everything works fine on the simulator and on my device. I'm trying to figure out the iOS version of those who can't, but there's definitely an issue there. Problem is I don't know how to report it since I can't reproduce it and most users don't have any problem.

**Comment by theochampion** [comment] 2020-04-03 14:43
Have you got any updates on this? I'm having the same issue on the latest version

**Comment by LucasTejero** [comment] 2020-04-22 03:19
Im having the same issue,i see every video and read a lot but i can not understand what is happening.

**Comment by athornz** [comment] 2020-04-22 03:26
Do you have multiple dynamic link domain prefixes registered? I think the iOS Dynamic Links SDK has issues with custom domain prefixes. 

Use the branch of firebase_auth from [this PR](https://github.com/FirebaseExtended/flutterfire/pull/147) that adds the `dynamicLinkDomain` property and generate your auth link with the `page.link` prefix.

That fixed it for me.

**Comment by ToniTornado** [comment] 2020-04-25 14:24
Hi, I have the same issue and posted it in detail on Stackoverflow: https://stackoverflow.com/questions/61393682/firebase-authentication-link-not-working-missing-trailing-slash

@athornz Thank you for the suggestion. The PR is required if you want to change the domain used to generate the dynamic link. I hoped I could define that domain with a trailing slash to solve my problem, but the dynamicLinkDomain parameter accepts only a naked domain (no protocol and no path). That made me wonder what will happen when I have two different path suffixes but I haven't tried that.

When the dynamicLinkDomain param is left out, it will use the first URL prefix it finds. So if you do not rely on multiple prefixes you can just delete all the others and use the pub.dev version without PR.

**Comment by Salakar** [comment] 2020-08-25 17:26
These properties are now directly supported on firebase_auth in ActionCodeSettings.

Please could you update to the new version as this feature is now supported. If you have any problems with this feature or the updated plugins please raise a new GitHub issue.

For help migrating to the new plugins please see the new migration guide: https://firebase.flutter.dev/docs/migration

**Closed by Salakar** 2020-08-25 17:26 UTC
Labels: impact: customer, plugin: dynamic_links, type: bug
