### ISSUE TITLE
🐛 [firebase_crashlytics] - Flutter/Android Obfuscated Trace

### ISSUE THREAD

**Issue by adriancsbna** [FirebaseExtended/flutterfire#5815] opened 2021-04-18 15:28 UTC
Hello.

I have an App made in Flutter for Android published. It uses Crashlytics so we can detect errors.
The problem is that we obfuscate the code, both in dart as indicated in this link https://flutter.dev/docs/deployment/obfuscate as well as by R8 (by default in flutter, configured with a Proguard file).

The problem is that being obfuscated, when I get the reports to Crashlytics, they arrive with the StackTrace obfuscated and I can not know how to see it without obfuscating. Attached is an image of how it appears.

![Captura de pantalla 2021-04-08 a las 18 58 14](https://user-images.githubusercontent.com/26508254/114066791-644cb180-989c-11eb-9038-6fb7299b357f.png)

I have asked for Firebase support and they have told me the following:

> Upon checking your screenshot, the way how the stack traces appear non-readable is indeed strange. Currently, as much as we would like to debug this from our side, Flutter is considered one of the external frameworks that's not yet covered by Firebase support. Even though Flutter basically still belongs to Google and we recommend this library for developers looking to bind Firebase to their suitable frameworks, it is not yet considered an official Firebase SDK. Issues that occur while integrating it are being handled by the Flutter team as they have the resources to further check why crashes coming from your app appear that way.
> 
> With this, you may try to bring up this issue in the official GitHub tracker for FlutterFire here (handled by Flutter team) so that this issue can be deeply examined. And if you wish to try our official Android SDK during part of the testing, you may also try to run our quickstart app for Crashlytics which has the latest Firebase Crashlytics SDK version and see if it reproduces the same issue (if it's reproducible using the official Android SDK, we can try to troubleshoot it here as well).

Would anyone know how to read the obfuscated trace?

**Comment by markusaksli-nc** [comment] 2021-04-19 08:43
Hi @adriancsbna 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by untp** [comment] 2021-04-19 15:39
Hi @adriancsbna
This is a duplicate of #2644, and this issue is solved by #4407. It is recently merged. You have to wait a few days for this fix to published in pub.dev. If you want to use it now, you can override your Crashlytics dependency with:
```
firebase_crashlytics:
  git:
    url: https://github.com/FirebaseExtended/flutterfire.git
    path: packages/firebase_crashlytics/firebase_crashlytics
```

Deobfuscation can be done like [this](https://github.com/FirebaseExtended/flutterfire/issues/2644#issuecomment-746217634).

**Comment by adriancsbna** [comment] 2021-04-19 18:29
Hi @untp 

I have done the test and it works correctly.
I have also been able to defuse correctly.

Thank you very much
Best regards

**Comment by Salakar** [comment] 2021-04-19 19:35
Closing as #4407 has been merged and is being published shortly.

**Closed by Salakar** 2021-04-19 19:35 UTC
Labels: Needs Attention, type: bug
