### ISSUE TITLE
🐛 firebase_analytics: Missing google_app_id

### ISSUE THREAD

**Issue by thomasklaush** [FirebaseExtended/flutterfire#8041] opened 2022-02-08 12:31 UTC
## Bug report

Missing google_app_id. Firebase Analytics disabled. See [https://goo.gl/NAOOOI]()

### Steps to reproduce

```
buildscript {
    ext.kotlin_version = '1.6.10' 
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.1.1'  
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath 'com.google.gms:google-services:4.3.10'
    }
}
```
```
distributionUrl=https\://services.gradle.org/distributions/gradle-7.3.3-all.zip

```
API 31

### Expected behavior

Working analytics,

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.10.0, on Microsoft Windows [Version 10.0.22000.469], locale de-AT)
[√] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2019 16.11.9)
[√] Android Studio (version 2021.1)
[√] VS Code (version 1.64.0)
[√] Connected device (4 available)
[√] HTTP Host Availability
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.16.0
Flutter SDK 2.10.0
kubikos 1.0.4+17

dependencies:
- amplify_auth_cognito 0.3.2 [flutter amplify_auth_plugin_interface amplify_core collection plugin_platform_interface]
- amplify_datastore 0.3.2 [flutter amplify_datastore_plugin_interface amplify_core plugin_platform_interface meta collection async]
- amplify_flutter 0.3.2 [amplify_analytics_plugin_interface amplify_api_plugin_interface amplify_auth_plugin_interface amplify_core amplify_datastore_plugin_interface amplify_storage_plugin_interface collection flutter json_annotation meta plugin_platform_interface]
- amplify_storage_s3 0.3.2 [flutter amplify_storage_plugin_interface plugin_platform_interface amplify_core]
- bloc 8.0.2 [meta]
- bloc_test 9.0.2 [bloc diff_match_patch meta mocktail test]
- cached_network_image 3.2.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cbor 4.1.0 [typed_data convert meta]
- convert 3.0.1 [typed_data]
- cupertino_icons 1.0.4
- dartz 0.10.1
- data_connection_checker 0.3.4
- equatable 2.0.3 [collection meta]
- firebase_analytics 9.1.0 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_core 1.12.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.5.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- fl_chart 0.41.0 [flutter equatable]
- flutter 0.0.0 [characters collection material_color_utilities meta typed_data vector_math sky_engine]
- flutter_bloc 8.0.1 [flutter bloc provider]
- flutter_nfc_kit 3.2.0 [flutter json_annotation ndef]
- flutter_reactive_ble 5.0.2 [collection flutter functional_data meta reactive_ble_mobile reactive_ble_platform_interface]
- flutter_svg 1.0.3 [flutter meta path_drawing vector_math xml]
- font_awesome_flutter 9.2.0 [flutter]
- formz 0.4.1
- freezed_annotation 1.1.0 [collection json_annotation meta]
- get_it 7.2.0 [async collection]
- google_fonts 2.3.1 [flutter http path_provider crypto]
- http 0.13.4 [async http_parser meta path]
- injectable 1.5.3 [get_it]
- intl 0.17.0 [clock path]
- json_annotation 4.4.0 [meta]
- logger 1.1.0
- mocktail 0.2.0 [collection matcher test]
- move_to_background 1.0.2 [flutter]
- path 1.8.0
- path_provider 2.0.8 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 8.3.0 [flutter meta permission_handler_platform_interface]
- radar_chart 2.1.0 [flutter]
- rxdart 0.27.3
- shared_preferences 2.0.13 [flutter shared_preferences_android shared_preferences_ios shared_preferences_linux shared_preferences_macos shared_preferences_platform_interface shared_preferences_web shared_preferences_windows]
- stats 2.0.0 [json_annotation]
- svg_path_parser 1.1.1 [string_scanner flutter]
- video_player 2.2.18 [flutter video_player_android video_player_avfoundation video_player_platform_interface video_player_web html]
- wakelock 0.6.1+1 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]

dev dependencies:
- build_runner 2.1.7 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher material_color_utilities meta source_span stream_channel string_scanner term_glyph typed_data]
- freezed 1.1.0 [analyzer build build_config collection meta source_gen freezed_annotation]
- injectable_generator 1.5.2 [build source_gen path glob analyzer code_builder dart_style injectable collection]
- json_serializable 6.1.4 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- lint 1.8.2

transitive dependencies:
- _fe_analyzer_shared 31.0.0 [meta]
- amplify_analytics_plugin_interface 0.3.2 [amplify_core flutter meta]
- amplify_api_plugin_interface 0.3.2 [amplify_core collection flutter json_annotation meta]
- amplify_auth_plugin_interface 0.3.2 [flutter meta amplify_core]
- amplify_core 0.3.2 [flutter meta plugin_platform_interface uuid]
- amplify_datastore_plugin_interface 0.3.2 [flutter meta collection date_time_format uuid amplify_core]
- amplify_storage_plugin_interface 0.3.2 [flutter meta amplify_core]
- analyzer 2.8.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.11 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.2.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.6 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.4 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- coverage 1.0.3 [args logging package_config path source_maps stack_trace vm_service]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.1 [source_span]
- dart_style 2.2.1 [analyzer args path pub_semver source_span]
- date_time_format 2.0.1
- diff_match_patch 0.4.1
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.0.5 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+6 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_core_platform_interface 4.2.4 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.4 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.13 [collection firebase_core flutter meta plugin_platform_interface]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.3.0 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_web_plugins 0.0.0 [flutter js characters collection material_color_utilities meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- functional_data 1.0.0 [meta collection]
- glob 2.0.2 [async collection file path string_scanner]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.1.1 [archive meta xml]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- lints 1.0.1
- logging 1.0.2
- matcher 0.12.11 [stack_trace]
- material_color_utilities 0.1.3
- meta 1.7.0
- mime 1.0.1
- ndef 0.3.1 [uuid]
- nested 1.0.0 [flutter]
- node_preamble 2.0.1
- octo_image 1.0.1 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider_android 2.0.11 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.5 [ffi flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.5 [flutter path_provider_platform_interface]
- path_provider_platform_interface 2.0.3 [flutter platform plugin_platform_interface]
- path_provider_windows 2.0.5 [ffi flutter path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.1.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- protobuf 2.0.1 [fixnum collection]
- provider 6.0.2 [collection flutter nested]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.2.0 [checked_yaml collection json_annotation pub_semver yaml]
- reactive_ble_mobile 5.0.2 [flutter protobuf reactive_ble_platform_interface]
- reactive_ble_platform_interface 5.0.2 [collection flutter functional_data meta plugin_platform_interface]
- shared_preferences_android 2.0.10 [flutter shared_preferences_platform_interface]
- shared_preferences_ios 2.0.9 [flutter shared_preferences_platform_interface]
- shared_preferences_linux 2.0.4 [file flutter path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.2 [flutter shared_preferences_platform_interface]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.3 [flutter flutter_web_plugins shared_preferences_platform_interface]
- shared_preferences_windows 2.0.4 [file flutter path path_provider_platform_interface path_provider_windows shared_preferences_platform_interface]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_packages_handler 3.0.0 [path shelf shelf_static]
- shelf_static 1.1.0 [convert http_parser mime path shelf]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.2.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.1 [analyzer collection source_gen]
- source_map_stack_trace 2.1.0 [path stack_trace source_maps]
- source_maps 0.10.10 [source_span]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.2 [flutter sqflite_common path]
- sqflite_common 2.2.0 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test 1.19.5 [analyzer async boolean_selector collection coverage http_multi_server io js node_preamble package_config path pool shelf shelf_packages_handler shelf_static shelf_web_socket source_span stack_trace stream_channel typed_data web_socket_channel webkit_inspection_protocol yaml test_api test_core]
- test_api 0.4.8 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- test_core 0.4.9 [analyzer async args boolean_selector collection coverage frontend_server_client glob io meta package_config path pool source_map_stack_trace source_maps source_span stack_trace stream_channel vm_service yaml matcher test_api]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- uuid 3.0.5 [crypto]
- vector_math 2.1.1
- video_player_android 2.2.17 [flutter video_player_platform_interface]
- video_player_avfoundation 2.2.18 [flutter video_player_platform_interface]
- video_player_platform_interface 5.0.1 [flutter plugin_platform_interface]
- video_player_web 2.0.6 [flutter flutter_web_plugins pedantic video_player_platform_interface]
- vm_service 7.5.0
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webkit_inspection_protocol 1.0.0 [logging]
- win32 2.3.11 [ffi]
- xdg_directories 0.2.0+1 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment] 2022-02-09 11:06
@thomasklaush 
Assuming you used dart-only intialization in your app, according to the documentation, the dart-only initialization is not supported by all plugins on all platforms. See this table for your reference which shows `firebase_analytics` plugin isn't yet supported on Android platform for dart-only initialization, and you might need to use manual installation for time being.
https://firebase.flutter.dev/docs/cli/#usage

Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/7639

**Closed by darshankawar** 2022-02-09 11:06 UTC
Labels: type: bug, Needs Attention, in triage
