### ISSUE TITLE
[firebase_auth] Anonymous user has isAnonymous = false

### ISSUE THREAD

**Issue by ingluife** [FirebaseExtended/flutterfire#2989] opened 2020-07-20 23:20 UTC
**Describe the bug**
I have a flow in a  flutter mobile application with an Anonymous user. When the user enters the application, it's created an anonymous user to identify him, then the user can link his account data with some providers like Google, Facebook or Twitter, through the method `linkWithCredential`. Sometimes when it creates an anonymous user, the **isAnonymous** attribute is **FALSE** instead of **TRUE**.

**To Reproduce**
1. Create an Anonymous user with `signInAnonymously()` method
2. Link that anonymous account to a Google account with the `linkWithCredential()` method.
4. Log out with singOut for that account linked. Immediately creates another Anonymous user with `signInAnonymously()` method.
5. See **isAnonymous** attribute is FALSE from the latest Anonymous user created.

**Expected behavior**
I expect the **isAnonymous** attribute ALWAYS be TRUE if the User is Anonymous.

**Additional context**
The version used here is:
- firebase_auth: ^0.15.5+3
I tried to use the `reload()` method for the user, but the result was the same.
I have checked the user in the project's firebase console, according to his uid attribute assigned, I saw that user is Anonymous.

This is the Anonymous user in the Firebase console: 
![image](https://user-images.githubusercontent.com/17582750/87994895-75625200-cac4-11ea-8038-d421b4d889b2.png)

This is a PrintScreen of the code to show the user attributes:
![Screen Shot 2020-07-20 at 20 11 13](https://user-images.githubusercontent.com/17582750/87995177-2e289100-cac5-11ea-9aea-c95b59ea2274.png)
![Screen Shot 2020-07-20 at 20 11 50](https://user-images.githubusercontent.com/17582750/87995215-44365180-cac5-11ea-84b3-6c58ea9628ae.png)

**Flutter doctor**

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.8, on Mac OS X 10.15.5 19F101)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.47.0)
[✓] Connected device (1 available)

• No issues found!

```

**Comment by TahaTesser** [comment] 2020-07-21 10:52
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/288

**Closed by TahaTesser** 2020-07-21 10:52 UTC
