### ISSUE TITLE
🐛 [firebase_core] FlutterFirebaseCorePlugin.java still appears

### ISSUE THREAD

**Issue by josegpulido** [FirebaseExtended/flutterfire#5318] opened 2021-03-12 07:14 UTC
## Bug report

**Describe the bug**
Duplicate of #1401. Update all dependencies (including my Dart SDK) but the error still shows. I also added multidex support, but nothing.

### Steps to reproduce

1. $ flutter run on my project directory.
2. Builds the app on my physic device, but shows the error below:
```
Note: /Users/Jose_Pulido/flutter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_core-0.7.0/android/src/main/java/io/flutter/plugins/firebase/core/FlutterFirebaseCorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/Jose_Pulido/flutter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_auth-0.20.1/android/src/main/java/io/flutter/plugins/firebase/auth/FlutterFirebaseAuthPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/Jose_Pulido/flutter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.16.0+1/android/src/main/java/io/flutter/plugins/firebase/firestore/FlutterFirebaseFirestorePlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
Note: /Users/Jose_Pulido/flutter-sdk/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.16.0+1/android/src/main/java/io/flutter/plugins/firebase/firestore/streamhandler/TransactionStreamHandler.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.     
```

### Expected behavior

---

## Additional context

I'm specifically interested in support minSdkVersion 16 devices. I've tried the following commands:
```
$ flutter pub upgrade

$ flutter pub get

$ flutter clean

$ flutter run
```
But seems like not resolving the error.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on Mac OS X 10.14.6 18G6032 darwin-x64, locale es-MX)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[!] Xcode - develop for iOS and macOS
    ! Xcode 11.2.1 out of date (12.0.1 is recommended).
      Download the latest version or update via the Mac App Store.
[✗] Chrome - develop for the web (Cannot find Chrome executable at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome)
    ! Cannot find Chrome. Try setting CHROME_EXECUTABLE to a Chrome executable.
[✓] Android Studio (version 3.2)
[✓] VS Code (version 1.54.2)
[✓] Connected device (1 available)

! Doctor found issues in 2 categories.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.0
Flutter SDK 2.0.1
remote 1.0.0+1

dependencies:
- auto_size_text 2.1.0 [flutter]
- cloud_firestore 0.16.0+1 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- firebase_auth 0.20.1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- cloud_firestore_platform_interface 3.0.2 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.3.0+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 3.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+3 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- win32 1.7.4+1 [ffi]
- xdg_directories 0.1.2 [meta path process]
```

</details>

---

### pubspec.yml

<details><summary>Click To Expand</summary>

```
name: remote
description: Control de tu sistema domótico

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text:
  shared_preferences:
  firebase_core: "^0.7.0"
  firebase_auth: "^0.20.0+1"
  cloud_firestore: "^0.16.0+1"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
    - family: Nunito Sans
      fonts:
        - asset: fonts/NunitoSans-Regular.ttf
          weight: 500
```

</details>

**Comment by markusaksli-nc** [comment] 2021-03-12 08:42
Hi @josegpulido 
I see there's an open issue addressing the case you described https://github.com/FirebaseExtended/flutterfire/issues/3876.
Please follow up on that issue, I'm closing the current one as a duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

PS These are just warnings, if you are having some kind of issue they are not the cause.

**Closed by markusaksli-nc** 2021-03-12 08:42 UTC
Labels: Needs Attention, type: bug

**Comment by josegpulido** [comment] 2021-03-12 11:38
Thanks you a lot, I'm following the issue now. I will try to test on low sdk version devices and then decide if keep this issue open or not.
