### ISSUE TITLE
too@TahaTesser

### ISSUE THREAD

**Issue by wlong800** [FirebaseExtended/flutterfire#3616] opened 2020-09-22 08:19 UTC
@TahaTesser 

```
FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':firebase_remote_config:uploadArchives'.
> Could not publish configuration 'archives'
   > Could not write to file '/Users/ayushpgupta/.pub-cache/hosted/pub.dartlang.org/firebase_remote_config-0.4.0/android/build/poms/pom-default.xml'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* Where:
Script '/Users/ayushpgupta/development/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 897

* What went wrong:
Execution failed for task ':flutter:compileFlutterBuildRelease'.
> Process 'command '/Users/ayushpgupta/development/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 56s


Gradle task assembleAarRelease failed with exit code 0.

```

I am getting this error on running `flutter build aar`. Is this issue related with this current issue?

_Originally posted by @apgapg in https://github.com/FirebaseExtended/flutterfire/issues/2398#issuecomment-680887961_

**Comment by TahaTesser** [comment] 2020-09-22 09:25
Hi @wlong800 
It could be related, I added more labels to better describe the issue
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2398

**Closed by TahaTesser** 2020-09-22 09:25 UTC
