### ISSUE TITLE
FlutterFirebaseCorePlugin  uses or overrides a deprecated API

### ISSUE THREAD

**Issue by yadav-aniket** [FirebaseExtended/flutterfire#6321] opened 2021-06-05 17:05 UTC
Note: C:\FlutterSDK\flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-1.2.1\android\src\main\java\io\flutter\plugins\firebase\core\FlutterFirebaseCorePlugin.java uses or overrides a deprecated API

At the time of build i see this note

**Comment by mirkopoloni** [comment] 2021-06-06 17:53
Hey @yadav-aniket there are already a few issues regarding this problem. The main issue should be this one: https://github.com/FirebaseExtended/flutterfire/issues/3876
I think a quick fix could be to update the `minSdkVersion` of your project to at least version 23. Obviously this is not the solution if your app needs to be installed on older android version.

**Comment by yadav-aniket** [comment] 2021-06-07 04:36
hey @mirkopoloni  my minSdkVersion  is 24.

**Comment by mirkopoloni** [comment] 2021-06-07 07:16
@yadav-aniket is the app building correctly? Could you try to `flutter clean` and then to build the app again? Is the warning still there?

**Comment by yadav-aniket** [comment] 2021-06-07 08:04
@mirkopoloni  even  after flutter clean  warning is still there

**Comment by mirkopoloni** [comment] 2021-06-07 08:46
Can you please post the result of `flutter doctor`? And which firebase versions are you using? Also, the build is working, right?

**Comment by yadav-aniket** [comment] 2021-06-07 08:55
flutter doctor 

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale en-IN)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 4.1.0)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

• No issues found!


  firebase_messaging: ^10.0.1
  firebase_core: ^1.2.1

@mirkopoloni  build is working

**Comment by mirkopoloni** [comment] 2021-06-07 11:24
Thanks for the infos @yadav-aniket.
Can you create a repository so that I can test your code locally?
Does your app compile with null-safety?
Could you please try something:
```
flutter clean
flutter build apk --no-sound-null-safety
```
Is the warning still there?

**Comment by yadav-aniket** [comment] 2021-06-07 12:38
@mirkopoloni  I have created a repository 
  [FlutterFCMDemo](https://github.com/yadav-aniket/FlutterFCMDemo)

And I tried your command but still showing warning

**Comment by mirkopoloni** [comment] 2021-06-07 13:11
Thanks, I will have a look later in a few hours as soon as I am back home and let you know 👍

**Comment by mirkopoloni** [comment] 2021-06-07 20:44
@yadav-aniket thanks again for the repo. Unfortunately I can't get rid of the warning too... it is the same problem as described here https://github.com/FirebaseExtended/flutterfire/issues/3876
Your best bet is to wait until that issue is solved. Sorry that I couldn't help you with your problem.

**Comment by yadav-aniket** [comment] 2021-06-08 04:02
@mirkopoloni  thanks for giving time and no problem, I will wait for issue get resolved in plugin

**Comment by markusaksli-nc** [comment] 2021-06-08 08:27
Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/3876

**Closed by markusaksli-nc** 2021-06-08 08:27 UTC
Labels: in triage
