### ISSUE TITLE
TRACKER

### ISSUE THREAD

**Issue by fargievanel** [FirebaseExtended/flutterfire#7943] opened 2022-01-25 13:09 UTC
i cant run  the  app  on  the  iphone  . having  some  issues  with  the  licenses  . is  there  any  problem with  them  ?

**Comment by darshankawar** [comment] 2022-01-26 10:47
@fargievanel 
Not sure if what exactly the issue is and if it's related to flutterfire plugin. Closing.
If you are facing any issue using any flutterfire plugin, use new issue template and fill out requested details.

**Closed by darshankawar** 2022-01-26 10:47 UTC
Labels: in triage
