### ISSUE TITLE
🐛[firebase_core] iOS could not build module 'firebase_core' on Flutter 2.8, FirebaseCore 1.10.5

### ISSUE THREAD

**Issue by palvajk** [FirebaseExtended/flutterfire#7540] opened 2021-12-10 10:46 UTC
## Bug report

**Describe the bug**
After upgrading to Flutter 2.8 xCode build failing.

GeneratedPluginRegistrant.m:12:9: fatal error: module 'firebase_core' not found
    @import firebase_core;
     ~~~~~~~^~~~~~~~~~~~~
    1 error generated.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.0, on macOS 12.0.1 21A559 darwin-arm,
    locale hu-HU)
[✓] Android toolchain - develop for Android devices (Android SDK version
    31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.0)
[✓] Connected device (2 available)

• No issues found!

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

get: ^4.1.4
  intl: ^0.17.0
  easy_localization: ^3.0.0
  http: ^0.13.3
  uuid: ^3.0.4
  intl_phone_field: ^2.1.0
  flutter_local_notifications: ^9.0.2
  flutter_rating_bar: ^4.0.0
  flutter_spinkit: ^5.1.0
  geolocator: ^8.0.0
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.9
  share_plus: ^3.0.4
  flutter_advanced_segment: ^2.0.1+2
  font_awesome_flutter: ^9.1.0
  expandable: ^5.0.1
  flutter_switch: ^0.3.2

  image_picker: ^0.8.4+4
  image_crop: ^0.4.0
  flutter_native_image: ^0.0.6
  qr_code_scanner: ^0.6.1

  firebase_core: ^1.10.5
  firebase_messaging: ^11.2.3

  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.1.0

</details>

---

**Comment by darshankawar** [comment] 2021-12-10 12:21
@palvajk 
I tried the official plugin example on latest stable and it compiled and built properly without any issues.

```
Running "flutter pub get" in firebase_core_example...
Launching lib/main.dart on iPhone 12 Pro Max in debug mode...
Running pod install...
Running Xcode build...
Xcode build done.                                           26.5s
Debug service listening on ws://127.0.0.1:53952/ybMtCv-hZkI=/ws
Syncing files to device iPhone 12 Pro Max...
```

![Screenshot 2021-12-10 at 5 40 02 PM](https://user-images.githubusercontent.com/67046386/145573352-8ff300b1-b52e-414f-a320-f5b27490f0bd.png)

Can you try [this](https://stackoverflow.com/a/69943297) solution and see if it works for you ?

**Comment by palvajk** [comment] 2021-12-10 12:51
@darshankawar 
I tried you linked solution but it didn't help, but i created a new project with firebase_core and it worked fine. I don't understand why my older project doesn't work. I perform all cache clean, deleted the Pods library, reinstalled pods and still the same error.

**Comment by a-v-ebrahimi** [comment] 2021-12-11 05:02
On what platform are you trying to run? I have problems compiling and running my Flutter app on MacOS.

**Comment by palvajk** [comment] 2021-12-11 09:07
@a-v-ebrahimi I use macOS too.

**Comment by masewo** [comment] 2021-12-11 12:46
Having the same problem. @palvajk Are you also using a Mac with M1?

**Comment by palvajk** [comment] 2021-12-11 13:04
@masewo 
I use M1 Mac as well. But if i create a new project and add firebase_core, its build fine.

**Comment by masewo** [comment] 2021-12-11 13:07
@palvajk Same here. I looked for overlaps in our pubspecs. Try adding google_sign_in to the new project. Then it starts not being able to build anymore.

**Comment by palvajk** [comment] 2021-12-11 17:32
@masewo 
I will try to add google_sign_in to the new project. My error is not the same like the other issue, but we will see. I stay the 2.5.3 until the issue resolve

**Comment by dw2kim** [comment] 2021-12-11 20:01
Same here:

`/ios/Runner/GeneratedPluginRegistrant.m:12:9: Module 'connectivity_plus' not found`

![Screen Shot 2021-12-11 at 3 00 57 PM](https://user-images.githubusercontent.com/8919703/145689980-0bfd4f6c-6bca-49e1-a774-f0acd55a5214.png)
.

**Comment by palvajk** [comment] 2021-12-13 10:51
UPDATE
#https://github.com/flutter/flutter/issues/94914#issuecomment-992239759
This comment helped me! The error was gone, but I need to remove sign_in_with_google temporarily.

**Comment by darshankawar** [comment] 2021-12-13 12:25
@palvajk 
Based on the thread above, it seems the issue is related to `google_sign_in` plugin and not with `firebase_core`, so I suggest you to file related plugin issue in `flutter/flutter repo`. Since your issue is resolved based on above comment, I"ll close it. If you disagree, write in comments and I'll reopen.

**Closed by darshankawar** 2021-12-13 12:25 UTC
Labels: type: bug, Needs Attention, in triage
