### ISSUE TITLE
🐛 [firebase_auth] signInAnonymously return anonymous user, but userChanges emits empty signed in user

### ISSUE THREAD

**Issue by SashaFarkas** [FirebaseExtended/flutterfire#5802] opened 2021-04-16 15:13 UTC
## Bug report

**THIS HAPPENS ONLY ON ANDROID, iOS works as expected**

When logged in, perform signInAnonymously (it will return user.isAnonymous == true)
But instance.userChanges will emit empty signed in User (user.isAnonymous == false)

### Steps to reproduce

1. Sign in with phone (don't know if it matters)
2. SignInAnonymously (which should perform sign out first)
3. See signed in user in userChanges()

### Expected behavior

userChanges should emit anonymous user.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

[✓] Flutter (Channel stable, 2.0.4, on Mac OS X 10.15.7 19H2 darwin-x64, locale en-RU)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.1)

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>
firebase_core: ^1.0.2
  firebase_auth: ^1.0.1
  cloud_firestore: ^1.0.3
  firebase_storage: ^8.0.1

</details>

---

**Comment by markusaksli-nc** [comment] 2021-04-19 07:58
This seems to be a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/3667 except now the restart isn't required. I think rolling these into the same issue is reasonable since both require essentially the same steps.

**Closed by markusaksli-nc** 2021-04-19 07:58 UTC
Labels: Needs Attention, type: bug
