### ISSUE TITLE
[crashlytics] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=, content_type=application/json; charset=utf-8}

### ISSUE THREAD

**Issue by mehtahardikr** [FirebaseExtended/flutterfire#3725] opened 2020-10-01 09:10 UTC
getting issue on ios : 

`Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=, content_type=application/json; charset=utf-8}`

Please help me resolve this. using flavor based app.

**Comment by orestesgaolin** [comment] 2020-10-01 09:36
seems like duplicate of #3669

**Comment by mehtahardikr** [comment] 2020-10-01 09:39
@orestesgaolin : that for android, i had issue with ios

**Comment by darshankawar** [comment] 2020-10-01 12:02
@mehtahardikr Please provide `flutter doctor -v`.
Will need to confirm, but the error could be coming from ios-sdk itself. See [this](https://github.com/firebase/firebase-ios-sdk/issues/5641) for reference.

**Comment by mehtahardikr** [comment] 2020-10-01 12:13
Here i have debug logs also.

```
6.26.0 - [Firebase/Core][I-COR000001] Configuring the default app.
 [Firebase/Crashlytics] Version 4.1.1
 6.26.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics] Running on iOS Simulator (iPhone), 12.1.0 (17G65)
6.26.0 - [Firebase/Crashlytics][I-CLS000000] [Crashlytics:Settings] No settings were cached
6.26.0 - [Firebase/Crashlytics][I-CLS000000] Automatic data collection is enabled.
6.26.0 - [Firebase/Installations][I-FIS002000] -[FIRInstallationsIDController createGetInstallationItemPromise], appName: __FIRAPP_DEFAULT
 6.26.0 - [Firebase/Crashlytics][I-CLS000000] Unsent reports will be uploaded at startup
 6.26.0 - [Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=, content_type=application/json; charset=utf-8}
```
and flutter doctor -v

```
[✓] Flutter (Channel stable, 1.20.4, on Mac OS X 10.13.6 17G65, locale en-IN)
    • Flutter version 1.20.4 at /Users/UserA/flutter
    • Framework revision fba99f6cf9 (2 weeks ago), 2020-09-14 15:32:52 -0700
    • Engine revision d1bc06f032
    • Dart version 2.9.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/UserA/Library/Android/sdk
    • Platform android-30, build-tools 29.0.3
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[!] Xcode - develop for iOS and macOS (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    ✗ Flutter requires a minimum Xcode version of 11.0.0.
      Download the latest version or update via the Mac App Store.
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 50.0.1
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] Connected device (1 available)
    • SM T385 (mobile) • e2294ff5 • android-arm • Android 8.1.0 (API 27)

! Doctor found issues in 1 category.
```
Let me know if anything missing.

**Comment by mehtahardikr** [comment] 2020-10-07 03:55
@TahaTesser : is there any updates ?

**Comment by kaciula** [comment] 2020-10-13 14:29
@TahaTesser You've added the wrong tag to this issue. It should be platform: ios.

**Comment by TahaTesser** [comment] 2020-10-14 12:16
@kaciula 
Thanks!

**Comment by dilipmishra907** [comment] 2020-10-23 05:04
I am facing same issue in iOS .what i am doing wrong.
[Firebase/Crashlytics][I-CLS000000] Failed to download settings Error Domain=FIRCLSNetworkError Code=-5 "(null)" UserInfo={status_code=403, type=2, request_id=, content_type=application/json; charset=utf-8}

Thanks

**Comment by russellwheatley** [comment] 2021-05-06 14:05
A couple of major crashlytics versions have been released since this issue. Please install the latest and follow the updated documentation closely [here](https://firebase.flutter.dev/docs/crashlytics/usage). Will reopen if you're still getting the same error.

**Closed by russellwheatley** 2021-05-06 14:05 UTC
Labels: platform: ios, plugin: crashlytics, type: bug
