### ISSUE TITLE
firebase_auth 0.16.1 mysterious crash happens when exit from the app and then get back to it.

### ISSUE THREAD

**Issue by asoftraiden** [FirebaseExtended/flutterfire#2886] opened 2020-07-02 19:14 UTC
This applies to version 0.16.1, the current version as of this writing.
1 - Mysterious crash happens when exit from the app and then get back to it.
2 - Happens also during calling FirebaseAuth.instance.signOut() and various other signIn methods.
3 - The problem disappears completely when downgrading to version firebase_auth: 0.15.5+3 and I dont knouw about other versions. so fix the 0.16.1 and later versions please.

```
@override
  void initState(){
    authService.onAuthStatusChanged().listen((event) {
      print('forex editor onAuthStatusChanged() with event =$event');
      if(event!=null && mounted) {
        setState(() {
          loggedIn = true;
        });
      } else if (event==null && mounted){
        setState(() {
          loggedIn = false;
        });
      }
    });
   super.initState();
  }
```
then simply a different widget appears based on logged in or not in the build method.

error crash text:

```
I/flutter (12650): forex editor onAuthStatusChanged() with event =FirebaseUser(Instance of 'PlatformUser')
D/FirebaseAuth(12650): Notifying id token listeners about user ( HgiJFxeeIyZRCHMV6dMsDjO5bf62 ).
I/PGA     (12650): PgaSocketInit: opened /dev/bstpgaipc: fd = 47
I/PGA     (12650): Attempting to create new SOCKET connection pid = 12650, tid = 13444
I/PGA     (12650): PgaSocketInitClientPgaIpc: data mapped to 0xaffaa000
I/PGA     (12650): New SOCKET connection: com.asoft.rayancontroller (pid 12650, tid 13444)
I/PGA     (12650): PgaSocketInit: opened /dev/bstpgaipc: fd = 59
I/PGA     (12650): Attempting to create new SOCKET connection pid = 12650, tid = 13443
I/PGA     (12650): PgaSocketInitClientPgaIpc: data mapped to 0xafec0000
I/PGA     (12650): New SOCKET connection: com.asoft.rayancontroller (pid 12650, tid 13443)
I/flutter (12650): build() MyHomePageState: loggedIn=false => LoginScreen
I/flutter (12650): MyHomePageState onAuthStatusChanged with event = FirebaseUser(Instance of 'PlatformUser')
I/flutter (12650): finished registering firestore listen callback in the ForexEditorState constructor
I/flutter (12650): document().snapshot().listen() callback in Constructor (document change detected)  ------------------------------------!
I/flutter (12650): setting state variables: ->>>>>>>>>>>>>>>>>>>>>>>>>>>>
I/flutter (12650): mounted = true >>>>> setting textEdit controllers
I/flutter (12650): forex editor onAuthStatusChanged() with event =FirebaseUser(Instance of 'PlatformUser')
D/AndroidRuntime(12650): Shutting down VM
D/AndroidRuntime(12650): procName from cmdline: com.asoft.rayancontroller
E/AndroidRuntime(12650): in writeCrashedAppName, pkgName :com.asoft.rayancontroller
D/AndroidRuntime(12650): file written successfully with content: com.asoft.rayancontroller StringBuffer : ;com.asoft.rayancontroller
E/AndroidRuntime(12650): FATAL EXCEPTION: main
E/AndroidRuntime(12650): Process: com.asoft.rayancontroller, PID: 12650
E/AndroidRuntime(12650): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(12650): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent(CloudFirestorePlugin.java:429)
E/AndroidRuntime(12650): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent(CloudFirestorePlugin.java:402)
E/AndroidRuntime(12650): 	at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.0:504)
E/AndroidRuntime(12650): 	at com.google.firebase.firestore.DocumentReference$$Lambda$3.onEvent(com.google.firebase:firebase-firestore@@21.3.0)
E/AndroidRuntime(12650): 	at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.0:42)
E/AndroidRuntime(12650): 	at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(com.google.firebase:firebase-firestore@@21.3.0)
E/AndroidRuntime(12650): 	at android.os.Handler.handleCallback(Handler.java:751)
E/AndroidRuntime(12650): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(12650): 	at android.os.Looper.loop(Looper.java:154)
E/AndroidRuntime(12650): 	at android.app.ActivityThread.main(ActivityThread.java:6138)
E/AndroidRuntime(12650): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(12650): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:893)
E/AndroidRuntime(12650): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
I/Process (12650): Sending signal. PID: 12650 SIG: 9
Lost connection to device.

```

**Comment by TahaTesser** [comment] 2020-07-03 10:56
Hi @asoftraiden 
Using the package version on official [example](https://pub.dev/packages/firebase_messaging#-example-tab-)
i cannot reproduce any of the issues you mentioned

<details> 
<summary>stable flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.20.0-2.0.pre, on Mac OS X 10.15.5 19F101, locale
    en-GB)
    • Flutter version 1.20.0-2.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 15a28159bc (10 days ago), 2020-06-23 04:52:58 -0700
    • Engine revision 91a63d6a44
    • Dart version 2.9.0 (build 2.9.0-19.0.dev 7e72c9ae7e)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/sdk
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/sdk
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.46.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.1

 
[✓] Connected device (5 available)            
    • SM M305F      • 32003c30dc19668f          • android-arm64  • Android 10
      (API 29)
    • Taha’s iPhone • 00008020-001059882212002E • ios            • iOS 13.5.1
    • macOS desktop • macos                     • darwin-x64     • Mac OS X
      10.15.5 19F101
    • Web Server    • web-server                • web-javascript • Flutter Tools
    • Chrome        • chrome                    • web-javascript • Google Chrome
      83.0.4103.116

• No issues found!
``` 

</details> 

Please try official example 
Thank you

**Comment by asoftraiden** [comment] 2020-07-03 15:35
Well it is very subtle error in the 0.16.1 version but I present in both the emulator and the real physical device. It appears that an event inside the auth library could not find the callback because it somehow became null internally only sometimes.

**Comment by yoongti** [comment] 2020-07-04 09:48
We are facing the same issue as well. The app mysteriously crashes when we try to do a log out.

Platform: Android 8.0
Version: 0.16.1

**How to simulate**
1. Login through OTP
2. Close the app (Use physical back button to close app, don't kill the app and launch app)
3. Open the app and do a log out
4. App immediately crashes

**Side Note**
1. We tried 0.15.5+3 and there is no issue. It seems the crash happens since the Android v2 embedding migration.
2. Logging out without closing the app will not crash the app, but will crash the app the next time a login is attempted after closing the app. (Login -> Logout -> Close App(Back until app is closed) -> Login -> Crash)
3. Killing the app then logout won't crash the app.

**Conclusion**
The only way to simulate it is
1. Login/Logout the app
2. Use physical Back Button until the app is closed (Not killing the app using Overview button)
3. Open the app up again, login/logout
4. Crash

> D/FirebaseAuth( 3461): Notifying id token listeners about a sign-out event.
D/FirebaseAuth( 3461): Notifying auth state listeners about a sign-out event.
D/AndroidRuntime( 3461): Shutting down VM
E/AndroidRuntime( 3461): FATAL EXCEPTION: main
E/AndroidRuntime( 3461): Process: com.krave.kravemobileconsumer, PID: 3461
E/AndroidRuntime( 3461): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime( 3461):        at io.flutter.plugins.firebaseauth.FirebaseAuthPlugin$3.onAuthStateChanged(FirebaseAuthPlugin.java:710)
E/AndroidRuntime( 3461):        at com.google.firebase.auth.zzp.run(com.google.firebase:firebase-auth@@19.2.0:3)
E/AndroidRuntime( 3461):        at android.os.Handler.handleCallback(Handler.java:808)
E/AndroidRuntime( 3461):        at android.os.Handler.dispatchMessage(Handler.java:101)
E/AndroidRuntime( 3461):        at com.google.android.gms.internal.firebase_auth.zzj.dispatchMessage(com.google.firebase:firebase-auth@@19.2.0:6)
E/AndroidRuntime( 3461):        at android.os.Looper.loop(Looper.java:166)
E/AndroidRuntime( 3461):        at android.app.ActivityThread.main(ActivityThread.java:7529)
E/AndroidRuntime( 3461):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 3461):        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
E/AndroidRuntime( 3461):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by athlona64** [comment] 2020-07-07 02:23
same issue in latest firebase auth

**Comment by exptk3** [comment] 2020-07-13 10:27
* same issue occured. (package : firebase_auth)
version 0.15.5+3 : normal
version 0.16.0 : app crash
version 0.16.1 : app crash

* error log
D/AndroidRuntime(27359): Shutting down VM
E/AndroidRuntime(27359): FATAL EXCEPTION: main

* reproduce
 - app log out --> app start --> app crash
 - app kill (force close) --> app start --> normal
 - app log out --> app kill (force close) --> app start --> normal

This error occurs when the app is restarted while the app is running in the background launcher of Android Device. This is a very important issue because it is the general way users use the app.

**Comment by greghesp** [comment] 2020-07-13 13:41
@asoftraiden 

I've tested this and I am unable to replicate on the rework that is currently being worked on.

The roadmap can be [found here](https://github.com/FirebaseExtended/flutterfire/issues/2582).  Please keep an eye on the roadmap for the next release, and let us know if you are still able to replicate this yourself

<img src="https://user-images.githubusercontent.com/768908/87311093-b7b0ef80-c516-11ea-99ff-01e96a46956d.gif" width="50%">

**Comment by Ehesp** [comment] 2020-07-13 13:43
Closing - please let us know if you continue to have issues after using the reworked plugin.

**Closed by Ehesp** 2020-07-13 13:43 UTC
Labels: plugin: auth, type: bug
