### ISSUE TITLE
Plugin project :firebase_core_web not found. Please update settings.gradle. Plugin project :cloud_firestore_web not found. Please update settings.gradle.

### ISSUE THREAD

**Issue by 12amansharma** [FirebaseExtended/flutterfire#2727] opened 2020-06-08 12:36 UTC
in dependencies
cloud_firestore: ^0.13.6
permission_handler:` ^5.0.0+hotfix.9
firebase_core: ^0.4.5

**Comment by TahaTesser** [comment] 2020-06-08 14:48
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2599

**Closed by TahaTesser** 2020-06-08 14:48 UTC

**Comment by akashdusky** [comment] 2020-06-21 04:33
did u figure out ?

**Comment by hkmr** [comment] 2020-07-11 05:33
Hi @12amansharma, Did you find the solution ?

**Comment by 12amansharma** [comment] 2020-07-11 06:17
Yes I did just go to #2599 and follow instructions there.
