### ISSUE TITLE
🐛 [cloud_firestore] Unhandled Exception: type 'DocumentSnapshot' is not a subtype of type 'QueryDocumentSnapshot' of 'element'

### ISSUE THREAD

**Issue by dsourav** [FirebaseExtended/flutterfire#3849] opened 2020-10-12 20:21 UTC
## Bug report

**Bug description**
I am trying to listen to changes in the newly added item to stream. But after adding item, it's showing error. But I was able to use that piece of code for the earlier version. I am using **cloud_firestore: ^0.14.0+2**.

**Here's is the code:**

```
**Firestore service class**

class FirestoreService {
  final CollectionReference _usersCollectionReference =
      FirebaseFirestore.instance.collection('users');
  final CollectionReference _photoGalleryCollectionReference =
      FirebaseFirestore.instance.collection('photoGallery');
   Future<List<DocumentSnapshot>> fetchInitialList() async {
    return (await _photoGalleryCollectionReference
            .orderBy("timestamp",descending: true)
            .limit(10)
            .get())
        .docs;
  }

  Future<List<DocumentSnapshot>> fetchNextList(
      List<DocumentSnapshot> documentList) async {
    return (await _photoGalleryCollectionReference
            .orderBy("timestamp",descending: true)
            .startAfterDocument(documentList[documentList.length - 1])
            .limit(10)
            .get())
        .docs;
  }
 Stream<QuerySnapshot> photoGalleryListStream(){
    return _photoGalleryCollectionReference
    .orderBy("timestamp",descending: true).snapshots();
  }

}

**pagination service class**

class GalleryEditPagination {
 final _firestoreService = FirestoreService();
  List<DocumentSnapshot> documentList=[];

  BehaviorSubject<List<DocumentSnapshot>> itemController =
      BehaviorSubject<List<DocumentSnapshot>>();

  Stream<List<DocumentSnapshot>> get itemStream => itemController.stream;

  listentChangeofData() {
    _firestoreService
        .photoGalleryListStream()
        .listen((event) => onChangeData(event.docChanges));
  }

  void onChangeData(
    List<DocumentChange> documentChanges,
  ) {
    var isChange = false;
    documentChanges.forEach((productChange) {
      if (productChange.type == DocumentChangeType.removed) {
        documentList.removeWhere((product) {
          return productChange.doc.id == product.id;
        });
        isChange = true;
      } 
 **//this section is creating issue**
    else if (productChange.type == DocumentChangeType.added) {  
        documentList.insert(productChange.newIndex, productChange.doc);

        isChange = true;
      } else {
        if (productChange.type == DocumentChangeType.modified) {
          int indexWhere = documentList.indexWhere((product) {
            return productChange.doc.id == product.id;
          });

          if (indexWhere >= 0) {
            documentList[indexWhere] = productChange.doc;
          }
          isChange = true;
        }
      }
    });

    if (isChange) {
      if (documentList != null) itemController.sink.add(documentList);
    }
  }
}


**Base ViewModel class**

class BaseViewModel extends ChangeNotifier {

 bool _isLoadingVisible=false;

  bool get isLoadingVisible => _isLoadingVisible;

  set isLoadingVisible(bool isLoadingVisible) {
    _isLoadingVisible = isLoadingVisible;
    notifyListeners();
  }
   
}

**Data model class**

class PhotoGalleryDataModel {
  String imageUrl;
  var timestamp;
  DocumentReference documentReference;
  String id;
  PhotoGalleryDataModel({this.imageUrl});
  PhotoGalleryDataModel.fromDocumentSnapshot(DocumentSnapshot snapshot) {
    var data = snapshot.data();
    id=snapshot.id;
    documentReference = snapshot.reference;
    imageUrl = data['imageUrl'] ?? "";
    timestamp = data['timestamp'] ?? DateTime.now();
  }

  tojson() {
    return {'imageUrl': imageUrl, 'timestamp': FieldValue.serverTimestamp()};
  }
}

**Gallery View model class**

class GetProfileGalleryViewModel extends BaseViewModel {

  final _galleryEditPagination=GalleryEditPagination();
  ScrollController _controller = ScrollController();

  ScrollController get controller => _controller;

  List<PhotoGalleryDataModel> _photoGalleryList;

  List<PhotoGalleryDataModel> get photoGalleryList => _photoGalleryList;
 
  onModelready(){
   _galleryEditPagination.fetchFirstList();
   _controller.addListener(_scrollListener);
   listenToStream();
 _galleryEditPagination.listentChangeofData();
 }
 listenToStream(){
   _galleryEditPagination.itemStream.listen((event) { 
     _photoGalleryList=event.map((e) => PhotoGalleryDataModel.fromDocumentSnapshot(e) ).toList();
     notifyListeners();
   });
 }
void _scrollListener() {
  if (controller.offset >= controller.position.maxScrollExtent &&
        !controller.position.outOfRange) {
      _galleryEditPagination.fetchNextMovies();
    }
}
}


**UI class**

class EditProfileView extends StatelessWidget {

  @override
  Widget build(BuildContext context) {
    return ViewModelBuilder.reactive(
        viewModelBuilder: () => GetProfileGalleryViewModel(),
        disposeViewModel: false,
        onModelReady: (GetProfileGalleryViewModel galleryModel) =>
            galleryModel.onModelready(),
        builder: (context, GetProfileGalleryViewModel galleryModel, child) =>Scaffold(
      backgroundColor: Colors.black,
      body: SafeArea(
          child: Container(
        margin: EdgeInsets.only(left: 20.0, right: 20.0, top: 20.0),
        child: ListView(
         controller: galleryModel.controller,
          children: [
       
            photoGridView(context,galleryModel),
           
          ],
        ),
      )),
    ));
  }

  photoGridView(context,GetProfileGalleryViewModel galleryModel) {
    return  Column(
              children: [
                galleryModel.isLoadingVisible
                    ? Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        children: [
                          Padding(
                            padding: const EdgeInsets.all(8.0),
                            child: ProgressIndicatorWidget(
                              radius: 15.0,
                            ),
                          )
                        ],
                      )
                    : Padding(
                        padding: const EdgeInsets.all(8.0),
                        child: Container(),
                      ),
                Container(
                  margin: EdgeInsets.symmetric(horizontal: 35.0),
                  child: galleryModel.photoGalleryList == null
                      ?Container():galleryModel.photoGalleryList.length<1 ? Container(
                          decoration: BoxDecoration(
                              border: Border.all(color: AppColor.whiteColor)),
                          child: Padding(
                            padding: const EdgeInsets.all(15.0),
                            child: Column(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                IconButton(
                                  icon: Icon(
                                    Icons.add_a_photo,
                                    color: AppColor.whiteColor,
                                  ),
                                  onPressed: () => showPhotoGalleryDialog(
                                      context,
                                      galleryModel,
                                     // galleryModel.photoGalleryList.length,
                                      null,
                                      null),
                                ),
                                Text("ADD PHOTO TO GALLERY ",
                                    style: CustomFonts.googleBodyFont(
                                        color: Colors.white, fontSize: 13)),
                              ],
                            ),
                          ),
                        )
                      : GridView.builder(
                         shrinkWrap: true,
                         physics: NeverScrollableScrollPhysics(),
                     
                          gridDelegate:
                              SliverGridDelegateWithFixedCrossAxisCount(
                            crossAxisCount: 2,
                            childAspectRatio: 0.7,
                          ),
                          itemCount: galleryModel.photoGalleryList.length,
                          itemBuilder: (context, index) =>
                              Padding(
                                padding: const EdgeInsets.all(4.0),
                                child: InkWell(
                                  child: CachedNetworkImageWidget(
                                    imageUrl: galleryModel
                                        .photoGalleryList[index].imageUrl,
                                  ),
                                  onTap: () => showPhotoGalleryDialog(
                                      context,
                                      galleryModel,
                                      galleryModel.photoGalleryList[index].id,
                                      galleryModel
                                          .photoGalleryList[index].imageUrl,
                                          totalDoclength: galleryModel.photoGalleryList.length
                                           ),
                                ),
                              )),
                ),
              ],
            );
  }
}
```

</details>

---
Here is the output of the error:

<details><summary>Click To Expand</summary>

```
E/flutter (31873): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: type 'DocumentSnapshot' is not a subtype of type 'QueryDocumentSnapshot' of 'element'
E/flutter (31873): #0      List.insert (dart:core-patch/growable_array.dart)
E/flutter (31873): #1      GalleryEditPagination.onChangeData.<anonymous closure> 
package:oui_dating/…/firestorePaginationServices/galleryEditPagination.dart:91
E/flutter (31873): #2      List.forEach  (dart:core-patch/growable_array.dart:313:8))
E/flutter (31873): #3      GalleryEditPagination.onChangeData 
package:oui_dating/…/firestorePaginationServices/galleryEditPagination.dart:77
E/flutter (31873): #4      GalleryEditPagination.listentChangeofData.<anonymous closure> 
package:oui_dating/…/firestorePaginationServices/galleryEditPagination.dart:70
E/flutter (31873): #5      _rootRunUnary  (dart:async/zone.dart:1198:47))
E/flutter (31873): #6      _CustomZone.runUnary  (dart:async/zone.dart:1100:19))
E/flutter (31873): #7      _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7))
E/flutter (31873): #8      _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11))
E/flutter (31873): #9      _BufferingStreamSubscription._add  (dart:async/stream_impl.dart:285:7))
E/flutter (31873): #10     _ForwardingStreamSubscription._add  (dart:async/stream_pipe.dart:127:11))
E/flutter (31873): #11     _MapStream._handleData  (dart:async/stream_pipe.dart:224:10))
E/flutter (31873): #12     _ForwardingStreamSubscription._handleData  (dart:async/stream_pipe.dart:157:13))
E/flutter (31873): #13     _rootRunUnary  (dart:async/zone.dart:1198:47))
E/flutter (31873): #14     _CustomZone.runUnary  (dart:async/zone.dart:1100:19))
E/flutter (31873): #15     _CustomZone.runUnaryGuarded  (dart:async/zone.dart:1005:7))
E/flutter (31873): #16     _BufferingStreamSubscription._sendData  (dart:async/stream_impl.dart:357:11))
E/flutter (31873): #17     _DelayedData.perform  (dart:async/stream_impl.dart:611:14))

```

</details>

---

**Comment by markusaksli-nc** [comment] 2020-10-13 13:15
Hi @dsourav 
Could you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
There were a lot of changes from `0.14.0` such as

> QuerySnapshot:
    DEPRECATED: documents has been deprecated in favor of docs.
    DEPRECATED: documentChanges has been deprecated in favor of docChanges.
    NEW: docs now returns a List<QueryDocumentSnapshot> vs List<DocumentSnapshot>. This doesn't break existing functionality.

See the [changelog](https://pub.dev/packages/cloud_firestore/changelog#0140) for a full list.
Thank you

**Comment by dsourav** [comment] 2020-10-13 15:59
> Hi @dsourav
> Could you please provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
> There were a lot of changes from `0.14.0` such as
> 
> > QuerySnapshot:
> > DEPRECATED: documents has been deprecated in favor of docs.
> > DEPRECATED: documentChanges has been deprecated in favor of docChanges.
> > NEW: docs now returns a List vs List. This doesn't break existing functionality.
> 
> See the [changelog](https://pub.dev/packages/cloud_firestore/changelog#0140) for a full list.
> Thank you

I have added the minimal complete reproducible code for you. Please check and let me know.

**Comment by markusaksli-nc** [comment] 2020-10-14 06:03
As mentioned in the QuerySnapshot changelog 

> NEW: docs now returns a List< QueryDocumentSnapshot > vs List< DocumentSnapshot>.

The problem is actually due to your `fetchInitialList()` method signature containing `List<DocumentSnapshot>`.

Closing since this is working as intended.

**Closed by markusaksli-nc** 2020-10-14 06:03 UTC
Labels: Needs Attention, type: bug
