### ISSUE TITLE
Android Firebase GeneratedMessageLite.java line 1319 (com.google.protobuf.GeneratedMessageLite.a)

### ISSUE THREAD

**Issue by gustavobrian** [FirebaseExtended/flutterfire#1521] opened 2019-11-30 21:04 UTC
```
com.google.firebase.firestore.util.AsyncQueue.a (AsyncQueue.java:379)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$5.run (AsyncQueue.java:2)
android.os.Handler.handleCallback (Handler.java:873)
android.os.Handler.dispatchMessage (Handler.java:99)
android.os.Looper.loop (Looper.java:214)
android.app.ActivityThread.main (ActivityThread.java:7050)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)

com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1319)
com.google.firestore.v1.Target$DocumentsTarget.a (Target.java:530)
com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1355)
com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser.parsePartialFrom (GeneratedMessageLite.java:1340)
com.google.protobuf.GeneratedMessageLite$DefaultInstanceBasedParser.parsePartialFrom (GeneratedMessageLite.java:1328)
com.google.protobuf.CodedInputStream.a (CodedInputStream.java:497)
com.google.firebase.firestore.proto.Target.a (Target.java:1115)
com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1355)
com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1432)
com.google.protobuf.GeneratedMessageLite.a (GeneratedMessageLite.java:1449)
com.google.firebase.firestore.proto.Target.a (Target.java:538)
com.google.firebase.firestore.local.SQLiteQueryCache.a (SQLiteQueryCache.java:238)
com.google.firebase.firestore.local.SQLiteQueryCache.a (SQLiteQueryCache.java:221)
com.google.firebase.firestore.local.SQLiteQueryCache$$Lambda$4.accept (SQLiteQueryCache.java:8)
com.google.firebase.firestore.local.SQLitePersistence$Query.a (SQLitePersistence.java:431)
com.google.firebase.firestore.local.SQLiteQueryCache.a (SQLiteQueryCache.java:218)
com.google.firebase.firestore.local.LocalStore.a (LocalStore.java:513)
com.google.firebase.firestore.core.SyncEngine.a (SyncEngine.java:178)
com.google.firebase.firestore.core.EventManager.a (EventManager.java:91)
com.google.firebase.firestore.core.FirestoreClient.b (FirestoreClient.java:152)
com.google.firebase.firestore.core.FirestoreClient$$Lambda$6.run (FirestoreClient.java:4)
com.google.firebase.firestore.util.AsyncQueue.a (AsyncQueue.java:311)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$4.call (AsyncQueue.java:2)
com.google.firebase.firestore.util.AsyncQueue.a (AsyncQueue.java:287)
com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run (AsyncQueue.java:4)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:459)
java.util.concurrent.FutureTask.run (FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:641)
com.google.firebase.firestore.util.AsyncQueue$DelayedStartFactory.run (AsyncQueue.java:205)
java.lang.Thread.run (Thread.java:764)
```

**Comment by iapicca** [comment] 2019-12-04 13:25
Hi @gustavobrian 
could you please provide your updated  `flutter doctor -v`
and describe the issue in details?
Also, to better address the issue, would be helpful
if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by jffiorillo** [comment] 2020-01-01 20:49
```
pubspec.yaml
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.1.0
  dart_countries_states: ^0.0.8
  streets:
    path: <path_to_project_streets>
  jaguar_serializer: ^2.2.12
  firebase_core: ^0.4.3+1
  firebase_analytics: ^5.0.9
  firebase_auth: ^0.15.2
  firebase_dynamic_links: ^0.5.0+9
  cloud_firestore: ^0.13.0+1
  firebase_storage: ^3.1.1
  cache_image: ^0.0.3
  enum_to_string: ^1.0.8
  google_sign_in: ^4.1.1
  flutter_i18n: ^0.8.2
  flutter_typeahead: ^1.7.0
  flutter_cache_manager: 1.1.3
  cupertino_icons: ^0.1.2
  image: ^2.1.4
  transparent_image: 1.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.3
  build_runner: ^1.7.2
  jaguar_serializer_cli: ^2.2.8
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher/icon.png"
```

```
root build.gradle
buildscript {
  repositories {
    google()
    jcenter()
  }

  dependencies {
    classpath 'com.android.tools.build:gradle:3.2.1'
    classpath 'com.google.gms:google-services:4.3.2' // Google Services plugin
  }
}

allprojects {
  repositories {
    google()
    jcenter()
  }
}

rootProject.buildDir = '../build'
subprojects {
  project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
  project.evaluationDependsOn(':app')
}

task clean(type: Delete) {
  delete rootProject.buildDir
}

```

```
app build.gradle

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localPropertiesFile.withReader('UTF-8') { reader ->
        localProperties.load(reader)
    }
}

def flutterRoot = localProperties.getProperty('flutter.sdk')
if (flutterRoot == null) {
    throw new GradleException("Flutter SDK not found. Define location with flutter.sdk in the local.properties file.")
}

def flutterVersionCode = localProperties.getProperty('flutter.versionCode')
if (flutterVersionCode == null) {
    flutterVersionCode = '1'
}

def flutterVersionName = localProperties.getProperty('flutter.versionName')
if (flutterVersionName == null) {
    flutterVersionName = '1.0'
}

apply plugin: 'com.android.application'
apply from: "$flutterRoot/packages/flutter_tools/gradle/flutter.gradle"

def keystoreProperties = new Properties()
def keystorePropertiesFile = rootProject.file('key.properties')
if (keystorePropertiesFile.exists()) {
    keystoreProperties.load(new FileInputStream(keystorePropertiesFile))
}

android {
    compileSdkVersion 28

    lintOptions {
        disable 'InvalidPackage'
    }

    defaultConfig {
        // TODO: Specify your own unique Application ID (https://developer.android.com/studio/build/application-id.html).
        applicationId <app_id>
        minSdkVersion 21
        targetSdkVersion 28
        versionCode flutterVersionCode.toInteger()
        versionName flutterVersionName
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            keyAlias keystoreProperties['keyAlias']
            keyPassword keystoreProperties['keyPassword']
            storeFile file(keystoreProperties['storeFile'])
            storePassword keystoreProperties['storePassword']
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled true
            useProguard true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

flutter {
    source '../..'
}

dependencies {
    implementation 'com.google.firebase:firebase-auth:19.2.0'
    implementation 'com.google.android.gms:play-services-auth:17.0.0'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.1.0'
}
apply plugin: 'com.google.gms.google-services'  // Google Play services Gradle plugin
```

```
flutter doctor -v                                                                                                           21:24:01
[✓] Flutter (Channel beta, v1.12.13+hotfix.6, on Mac OS X 10.15.2 19C57, locale en-ES)
    • Flutter version 1.12.13+hotfix.6 at <dir>
    • Framework revision 18cd7a3601 (3 weeks ago), 2019-12-11 06:35:39 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0-rc1)
    • Android SDK at <sdk_dir>
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3, Build version 11C29
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 41.1.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[!] Android Studio
    • Android Studio at /Applications/Android Studio 4.0 Preview.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b4-5784211)

[✓] IntelliJ IDEA Ultimate Edition (version 2019.3.1)
    • IntelliJ at /Applications/IntelliJ IDEA.app
    • Flutter plugin version 42.1.4
    • Dart plugin version 193.5731

[✓] VS Code (version 1.40.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.6.0

[!] Connected device
    ! No devices available
```

When creating a release (`flutter build appbundle`) and executing a query to firestore I get the following error:

```
Process: io.foodie.foodie, PID: 24983
java.lang.RuntimeException: Internal error in Cloud Firestore (21.3.0).
	at com.google.firebase.firestore.util.AsyncQueue.a(AsyncQueue.java:529)
	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$3.run(AsyncQueue.java)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5538)
	at java.lang.reflect.Method.invoke(Method.java)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Caused by: java.lang.AbstractMethodError: abstract method "b.b.g.w$d b.b.g.w$d.b(int)"
	at com.google.protobuf.GeneratedMessageLite.a(GeneratedMessageLite.java:1319)
	at com.google.firestore.v1.Target$DocumentsTarget.ensureDocumentsIsMutable(Target.java:145)
	at com.google.firestore.v1.Target$DocumentsTarget.addDocuments(Target.java:181)
	at com.google.firestore.v1.Target$DocumentsTarget.a(Target.java:78)
	at com.google.firestore.v1.Target$DocumentsTarget$Builder.addDocuments(Target.java:428)
	at com.google.firebase.firestore.remote.RemoteSerializer.a(RemoteSerializer.java:697)
	at com.google.firebase.firestore.local.LocalSerializer.a(LocalSerializer.java:215)
	at com.google.firebase.firestore.local.SQLiteQueryCache.c(SQLiteQueryCache.java:103)
	at com.google.firebase.firestore.local.SQLiteQueryCache.a(SQLiteQueryCache.java:142)
	at com.google.firebase.firestore.local.LocalStore.a(LocalStore.java:547)
	at com.google.firebase.firestore.local.LocalStore$$Lambda$8.run(LocalStore.java)
	at com.google.firebase.firestore.local.SQLitePersistence.a(SQLitePersistence.java:189)
	at com.google.firebase.firestore.local.LocalStore.a(LocalStore.java:537)
	at com.google.firebase.firestore.core.SyncEngine.a(SyncEngine.java:183)
	at com.google.firebase.firestore.core.EventManager.a(EventManager.java:104)
	at com.google.firebase.firestore.core.FirestoreClient.b(FirestoreClient.java:169)
	at com.google.firebase.firestore.core.FirestoreClient$$Lambda$6.run(FirestoreClient.java)
	at com.google.firebase.firestore.util.AsyncQueue.a(AsyncQueue.java:431)
	at com.google.firebase.firestore.util.AsyncQueue$$Lambda$2.call(AsyncQueue.java)
	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor.a(AsyncQueue.java:317)
	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$$Lambda$2.run(AsyncQueue.java)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:224)
	at java.lang.Thread.run(Thread.java:831)
```

This error doesn't happen when running the app from the IDE.

**Comment by jffiorillo** [comment] 2020-01-01 20:51
I'm not sure if is this same issue https://github.com/flutter/flutter/issues/44700

**Comment by jffiorillo** [comment] 2020-01-02 09:59
The issue was solved setting `minifyEnabled false` and `shrinkResources false`. More details in https://github.com/FirebaseExtended/flutterfire/issues/1412#issuecomment-570161645.

**Comment by iapicca** [comment] 2020-02-07 13:50
Hi @gustavobrian 
does @jffiorillo solution works for you?
Thank you

**Comment by kirstywilliams** [comment] 2020-04-21 10:37
This seems to be solved by https://github.com/FirebaseExtended/flutterfire/issues/1521#issuecomment-570162108 . Since no update from OP closing this for now.

**Closed by kirstywilliams** 2020-04-21 10:37 UTC
Labels: blocked: customer-response, type: bug
