### ISSUE TITLE
[firebase_dynamic_links] plugin is not working in ios when app is in Back ground.

### ISSUE THREAD

**Issue by dhanrajvermaRepo** [FirebaseExtended/flutterfire#33] opened 2019-08-26 14:45 UTC
I have downloaded the example app from [https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_dynamic_links/example](url).
This example is running fine on android but on ios it is doing nothing when app is in background.
In fact onLink method was never called when ios app is in background.
HELP me please.

**Comment by jherencia** [comment] 2019-08-27 09:50
I'm going to try to check this this week.

**Comment by jherencia** [comment] 2019-10-03 02:13
I've pushed a PR with the fix.

**Comment by quetool** [comment] 2019-10-03 19:44
> I've pushed a PR with the fix, can you try? You just need to point to the PR version?
> 
> ```
>   firebase_dynamic_links:
>     git:
>       url: https://github.com/mrmilu/flutterfire.git
>       path: packages/firebase_dynamic_links
>       ref: firebase_dynamic_links-0.5.0+4
> ```

I don't know what @dhanrajvermaRepo means with "when app is in background" because, in order to open a Dynamic link from somewhere else, your app needs to be in background for sure, so...
Anyway, it is not working at all on iOS. App is being called and opened just fine, but the listener is not being called...
And not, @jherencia, your fix is not working, at leas not for me...
So I opened another issue https://github.com/FirebaseExtended/flutterfire/issues/262

**Comment by jherencia** [comment] 2019-10-04 11:53
@quetool
As you pointed in the other issue (#262) you are using a custom domain, and when you configured correctly the Info.plist file, everything worked.

Does that mean that the my PR worked for you?

**Comment by quetool** [comment] 2019-10-04 12:35
@jherencia sorry, I didn't notice you were talking about default domains... I didn't try again your PR after I solved my issue like I said in in https://github.com/FirebaseExtended/flutterfire/issues/262
So, we need to wait for @dhanrajvermaRepo to answer that...

**Comment by jherencia** [comment] 2019-10-04 12:39
@quetool

So you were using the latest official version (0.5.0+3) not the PR when it worked, right?

**Comment by quetool** [comment] 2019-10-04 13:56
That's right

**Comment by HofmannZ** [comment] 2019-10-05 11:59
Managed to get it working, though it's still subscribing to `onLink` multiple times because I can't unmount it.

Also note that
```dart
Navigator.pushNamed(context, deepLink.path);
```
needs to be a child of `MaterialApp` to work.

**Comment by dhanrajvermaRepo** [comment] 2019-10-05 12:04
> I've pushed a PR with the fix, can you try? You just need to point to the PR version?
> 
> ```
>   firebase_dynamic_links:
>     git:
>       url: https://github.com/mrmilu/flutterfire.git
>       path: packages/firebase_dynamic_links
>       ref: firebase_dynamic_links-0.5.0+4
> ```

I'll test my App on 8 October and let you know whether it is working or not.
Thank you

**Comment by dhanrajvermaRepo** [comment] 2019-10-07 09:50
> I've pushed a PR with the fix, can you try? You just need to point to the PR version?
> 
> ```
>   firebase_dynamic_links:
>     git:
>       url: https://github.com/mrmilu/flutterfire.git
>       path: packages/firebase_dynamic_links
>       ref: firebase_dynamic_links-0.5.0+4
> ```

Hi, I have tested my app with this PR. It is working when app is in background. When app is in killed state it navigates to appropriate screen but returns to my root widget within a micro/millisecond. It is so fast that it seems it directly opens my root widget (root screen ie login screen). I have is used toast to debug this issue as in killed state i can not debug it.

**Comment by jherencia** [comment] 2019-10-08 00:41
Can you post some example code to reproduce this?

**Comment by dhanrajvermaRepo** [comment] 2019-10-09 13:08
> Can you post some example code to reproduce this?

I am sorry. 
PR is working fine in both android and iOS. There was a bug in my code.

**Comment by jherencia** [comment] 2019-10-09 13:32
Great to hear, thank you!

**Comment by quetool** [comment] 2019-10-09 18:22
@jherencia I can confirm your PR fix the problem on iOS when app is in "killed state"

**Comment by dhanrajvermaRepo** [comment] 2019-10-10 08:57
> Great to hear, thank you!

why onError callback of onLink method is not called when we do not come by link in iOS?
getInitialLink always returns null in iOS.

**Comment by dhanrajvermaRepo** [comment] 2019-10-10 10:45
@jherencia Can I release my App with this PR?

**Comment by jherencia** [comment] 2019-10-10 10:52
Well, I cannot guarantee anything about this, it's a PR which has to pass a review and a process which can end up in the repo or not.

I wouldn't trust my repo because I will change things on it without notice.

It's your call to clone it and freeze the version so you can rely on your own repo or wait or whatever you think is the best for your project.

**Comment by Ehesp** [comment] 2020-04-21 14:47
Closing - looks like the problem is now fixed. Please create a new issue if the problem still persists as this one has generated a lot of noise from users posting stack traces without formatting.

**Closed by Ehesp** 2020-04-21 14:47 UTC
Labels: type: bug, type: documentation
