### ISSUE TITLE
🐛 [firebase_dynamic_links] getInitialLink() always returns null when terminated app launched on iOS

### ISSUE THREAD

**Issue by EddieWilkie91** [FirebaseExtended/flutterfire#7129] opened 2021-10-04 15:54 UTC
## Bug report

**Describe the bug**
When the application is launched from a dynamic link on iOS the getInitialLink() method always returns null. Shortly after, the onLink callback is executed. 

### Steps to reproduce

1. Set up & configure app following instructions: https://pub.dev/packages/firebase_dynamic_links
2. Launch iOS app from dynamic link.
3. Notice that the getInitialLink() returns null but onLink is called shortly after.

### Expected behavior

getInitialLink() returns deeplink when app is launched from a terminated state on iOS. 

## Additional context

Adding a one second delay before calling getInitialLink() fixes the issue. 

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-10-05 11:57
Hi @EddieWilkie91 
This sounds like a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6913 so closing it as such.
Let me know if you disagree.
Thank you

**Closed by markusaksli-nc** 2021-10-05 11:57 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by EddieWilkie91** [comment] 2021-10-05 13:42
> Hi @EddieWilkie91 This sounds like a duplicate of #6913 so closing it as such. Let me know if you disagree. Thank you

Yeah, that's no probs. I thought it would be slightly different because my onLink method for iOS gets called after I recieve null from getInitialLink(). But happy to leave it and continue watching the other issue. Cheers.
