### ISSUE TITLE
🐛 [cloud_firestore] symbol(s) not found for architecture armv7

### ISSUE THREAD

**Issue by miguelpruivo** [FirebaseExtended/flutterfire#5411] opened 2021-03-19 21:29 UTC
## Bug report

**Describe the bug**
I can't archive or build release (iOS) with latest version (`1.0.1`) it gives an error that symbols cannot be found for armv7.

### Steps to reproduce

1. Just build iOS for release using latest versions.

### Expected behavior

Build should be done properly.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 2.0.3, on macOS 11.2.2 20D80 darwin-x64, locale
    pt-PT)
    • Flutter version 2.0.3 at /Users/miguelruivo/devtools/flutter
    • Framework revision 4d7946a68d (21 hours ago), 2021-03-18 17:24:33 -0700
    • Engine revision 3459eb2436
    • Dart version 2.12.2

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.12.2
Flutter SDK 2.0.3
firepanel 1.0.0+9

dependencies:
- cloud_firestore 1.0.1 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- configurable_expansion_tile 1.0.0 [flutter]
- cupertino_icons 0.1.3
- dio 3.0.10 [http_parser path]
- file_picker 3.0.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_auth 1.0.1 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_oauth 1.0.1 [flutter firebase_auth firebase_core firebase_auth_oauth_platform_interface firebase_auth_oauth_web]
- firebase_crashlytics 1.0.0 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_colorpicker 0.3.5 [flutter]
- flutter_cupertino_localizations 1.0.1 [flutter flutter_localizations]
- flutter_google_places 0.2.8 [flutter google_api_headers google_maps_webservice http rxdart]
- flutter_html 2.0.0-nullsafety.0 [html csslib css_colors flutter_layout_grid video_player chewie webview_flutter chewie_audio flutter_svg flutter]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_markdown 0.5.2 [flutter markdown meta path]
- flutter_mobx 1.1.0+2 [mobx flutter]
- flutter_neumorphic 3.1.0 [flutter]
- flutter_slidable 0.5.7 [flutter]
- flutter_svg 0.21.0-nullsafety.0 [flutter meta path_drawing vector_math xml]
- font_awesome_flutter 8.12.0 [flutter]
- google_maps_flutter 2.0.1 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_sign_in 5.0.1 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- image_picker 0.7.3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]
- in_app_review 2.0.1 [flutter in_app_review_platform_interface]
- intl 0.17.0 [clock path]
- json_serializable 3.5.1 [analyzer build build_config json_annotation meta path source_gen]
- logger 0.9.4
- mobx 1.2.1+4 [meta]
- open_file 3.1.0 [flutter ffi]
- package_info 0.4.3+4 [flutter]
- pretty_json 1.1.0
- provider 4.3.3 [collection flutter nested]
- shared_preferences 2.0.5 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 1.1.2 [flutter]
- simple_animations 1.3.12 [flutter]
- url_launcher 6.0.2 [flutter url_launcher_platform_interface url_launcher_linux url_launcher_macos url_launcher_windows url_launcher_web]

dev dependencies:
- build_runner 1.11.5 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mobx_codegen 1.1.2 [analyzer build build_resolvers meta mobx path source_gen]

dependency overrides:
- cupertino_icons 0.1.3
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker 0.7.3 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface image_picker_for_web]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.2 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 1.6.0
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 1.6.2 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.6 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.10 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.3 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.10 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 5.0.0
- built_value 8.0.3 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- chewie 1.0.0 [cupertino_icons flutter video_player wakelock]
- chewie_audio 1.2.0 [cupertino_icons flutter video_player]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 4.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 1.0.1 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 3.7.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.0 [collection typed_data]
- css_colors 1.1.0 [flutter]
- csslib 0.17.0 [source_span]
- dart_style 1.3.12 [analyzer args path pub_semver source_span]
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.1 [http http_parser js]
- firebase_auth_oauth_platform_interface 1.0.0 [flutter firebase_auth firebase_core]
- firebase_auth_oauth_web 1.0.0 [flutter flutter_web_plugins firebase firebase_auth firebase_core firebase_auth_oauth_platform_interface js]
- firebase_auth_platform_interface 4.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.0.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core 1.0.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 2.0.0 [collection firebase_core flutter meta plugin_platform_interface]
- fixnum 1.0.0
- flutter_layout_grid 1.0.0-nullsafety.6 [flutter collection meta quiver]
- flutter_plugin_android_lifecycle 2.0.0 [flutter]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- glob 2.0.0 [async collection file path pedantic string_scanner]
- google_api_headers 0.1.1+2 [flutter package_info]
- google_maps_flutter_platform_interface 2.0.2 [flutter meta plugin_platform_interface stream_transform collection]
- google_maps_webservice 0.0.19 [http meta]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- html 0.15.0 [csslib source_span]
- http 0.13.1 [http_parser meta path pedantic]
- http_multi_server 2.2.0 [async]
- image_picker_for_web 2.0.0 [image_picker_platform_interface meta flutter flutter_web_plugins]
- image_picker_platform_interface 2.0.1 [flutter meta http plugin_platform_interface]
- in_app_review_platform_interface 2.0.2 [flutter url_launcher plugin_platform_interface platform]
- io 0.3.5 [meta path string_scanner]
- js 0.6.3
- json_annotation 3.1.1
- logging 1.0.0
- markdown 3.0.0 [args charcode meta]
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- package_config 1.9.3 [path charcode]
- path 1.8.0
- path_drawing 0.5.0-nullsafety.0 [vector_math meta path_parsing flutter]
- path_parsing 0.2.0-nullsafety.0 [vector_math meta]
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- petitparser 4.0.2 [meta]
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.1.0 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 0.1.8 [checked_yaml json_annotation pub_semver yaml]
- quiver 3.0.0 [matcher]
- rxdart 0.25.0
- shared_preferences_linux 2.0.0 [flutter file meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 2.0.0 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 2.0.0 [flutter]
- shared_preferences_web 2.0.0 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 2.0.0 [shared_preferences_platform_interface flutter file meta path path_provider_platform_interface path_provider_windows]
- shelf 1.1.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.4+1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 0.9.10+3 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0 [collection]
- url_launcher_linux 2.0.0 [flutter]
- url_launcher_macos 2.0.0 [flutter]
- url_launcher_platform_interface 2.0.2 [flutter plugin_platform_interface]
- url_launcher_web 2.0.0 [url_launcher_platform_interface meta flutter flutter_web_plugins]
- url_launcher_windows 2.0.0 [flutter]
- vector_math 2.1.0
- video_player 2.0.2 [meta video_player_platform_interface video_player_web flutter flutter_test]
- video_player_platform_interface 4.0.0 [flutter meta flutter_test]
- video_player_web 2.0.0 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock 0.4.0 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web]
- wakelock_macos 0.1.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.2.0 [flutter meta]
- wakelock_web 0.2.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- webview_flutter 2.0.2 [flutter]
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.0.2 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by hokenn99** [comment] 2021-03-21 14:24
Me too facing same problem .. have you found any solutions ?

**Comment by miguelpruivo** [comment] 2021-03-22 10:39
@hokenn99 not yet, and you?

**Comment by hokenn99** [comment] 2021-03-22 10:57
@miguelpruivo yes .. just change the ios target version to 12.0 .. then run `flutter clean` then `flutter pub get` then build .. if it doesnt work then cd the ios file and run `pod cache clean --all` then `pod install` and build ... thats worked for me yesterday

**Comment by miguelpruivo** [comment] 2021-03-22 12:23
@hokenn99 just removed `armv7` from build architectures and it worked as well (with lower iOS version support). It should be fine, since every iOS device should be using `arm64` since iOS 8 I believe.

**Comment by markusaksli-nc** [comment] 2021-03-22 12:40
Closing this as solved

**Closed by markusaksli-nc** 2021-03-22 12:40 UTC
Labels: Needs Attention, type: bug

**Comment by miguelpruivo** [comment] 2021-03-22 15:22
@markusaksli-nc it's not solved. We just found a "workaround". I believe that it is not suppose to crash if you want to build for `armv7` architectures.

**Comment by markusaksli-nc** [comment] 2021-03-22 15:55
It could be that something in my dev environment is blocking me from actually running into this but it doesn't seem to be a reproducible issue aside from a few rare cases and can be solved by not including the `armv7` arch (which will exclude some really old devices) or just setting a higher target version and clearing cache. As I've never been able to reproduce this and the symbols actually seem to exist I'm just not sure what can be fixed since this seems to just be a rare linker issue?

**Comment by hokenn99** [comment] 2021-03-25 19:22
> @hokenn99 just removed `armv7` from build architectures and it worked as well (with lower iOS version support). It should be fine, since every iOS device should be using `arm64` since iOS 8 I believe.

i'm changing the architecture for both project and target but it keeps failing .. is there any specific steps i have to do ?
