### ISSUE TITLE
🐛 [firebase_auth] getter currentUser always returns null

### ISSUE THREAD

**Issue by cadaniel** [FirebaseExtended/flutterfire#5964] opened 2021-04-28 18:49 UTC
## Bug report

When I call `FirebaseAuth.instance.currentUser` it's always null. Subscribing to the stream `FirebaseAuth.instance.authStateChanges()` will emit a non-null user. Note: I've only tested on iOS. 

### Steps to reproduce

This photo below is the result from the code below. Clearly the user from currentUser is null while from authStateChanges is not. 

![8E8ADBF2-38D7-4EA1-A60F-6FD240CBCE25_1_105_c](https://user-images.githubusercontent.com/5515671/116456506-98721d00-a81f-11eb-9bb0-b7965909822c.jpeg)

Pubspec.yaml holds 

    dependencies:
      firebase_core: ^1.1.0
      firebase_auth: ^1.1.2
      flutter:
        sdk: flutter 

<details><summary>Sample code Click To Expand</summary>

```
    import 'package:firebase_auth/firebase_auth.dart';
    import 'package:firebase_core/firebase_core.dart';
    import 'package:flutter/material.dart';
    
    void main() {
      runApp(MyApp());
    }
    
    class MyApp extends StatelessWidget {
      // This widget is the root of your application.
      @override
      Widget build(BuildContext context) {
        return MaterialApp(
          title: 'Flutter Demo',
          theme: ThemeData(
            // This is the theme of your application.
            //
            // Try running your application with "flutter run". You'll see the
            // application has a blue toolbar. Then, without quitting the app, try
            // changing the primarySwatch below to Colors.green and then invoke
            // "hot reload" (press "r" in the console where you ran "flutter run",
            // or simply save your changes to "hot reload" in a Flutter IDE).
            // Notice that the counter didn't reset back to zero; the application
            // is not restarted.
            primarySwatch: Colors.blue,
          ),
          home: MyHomePage(),
        );
      }
    }
    
    class MyHomePage extends StatefulWidget {
      MyHomePage({Key? key}) : super(key: key);
    
      // This widget is the home page of your application. It is stateful, meaning
      // that it has a State object (defined below) that contains fields that affect
      // how it looks.
    
      // This class is the configuration for the state. It holds the values (in this
      // case the title) provided by the parent (in this case the App widget) and
      // used by the build method of the State. Fields in a Widget subclass are
      // always marked "final".
    
      @override
      _MyHomePageState createState() => _MyHomePageState();
    }
    
    class _MyHomePageState extends State<MyHomePage> {
      User? _user;
      Stream<User?>? _userStream;
      TextEditingController _emailController = TextEditingController();
      TextEditingController _passwordController = TextEditingController();
    
      @override
      void initState() {
        super.initState();
        init();
      }
    
      void init() async {
        await Firebase.initializeApp();
        setState(() {
          _user = FirebaseAuth.instance.currentUser;
          _userStream = FirebaseAuth.instance.authStateChanges();
        });
      }
    
      void _login() async {
        FirebaseAuth.instance.signInWithEmailAndPassword(
            email: _emailController.text, password: _passwordController.text);
      }
    
      void _register() async {
        FirebaseAuth.instance.createUserWithEmailAndPassword(
            email: _emailController.text, password: _passwordController.text);
      }
    
      @override
      Widget build(BuildContext context) {
        return Scaffold(
          body: SafeArea(
            child: Column(
              children: [
                Text("User: $_user"),
                if (_userStream != null)
                  StreamBuilder(
                    stream: _userStream,
                    builder: (BuildContext context, AsyncSnapshot<User?> stream) {
                      if (stream.hasData) {
                        return Text("User is ${stream.data?.toString() ?? "null"}");
                      }
                      return Text("Initializing...");
                    },
                  ),
                Text("Email"),
                TextFormField(
                  controller: _emailController,
                ),
                Text("Password"),
                TextFormField(
                  controller: _passwordController,
                ),
                Row(
                  children: [
                    TextButton(onPressed: _login, child: Text("Login")),
                    TextButton(onPressed: _register, child: Text("Register")),
                  ],
                )
              ],
            ),
          ),
        );
      }
    }

```

</details>

### Expected behavior

Both return the same user

---

## Additional context

I'm not sure what triggered this. I had to upgrade my build server to use XCode 12, and this came with that change. That's not to say that it caused it, it could be just a coincidence.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
casey@Caseys-Mac-mini firebase_test % flutter doctor -v
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.1 20C69 darwin-arm, locale en-CA)
    • Flutter version 2.0.5 at /Users/casey/flutter
    • Framework revision adc687823a (12 days ago), 2021-04-16 09:40:20 -0700
    • Engine revision b09f014e96
    • Dart version 2.12.3

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/casey/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/casey/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.7199119/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (4 available)
    • SM G960W (mobile)          • 3338385647453098                     • android-arm64  • Android 10 (API 29)
    • Casey’s iPhone (mobile)    • 00008030-001A20E83C78802E            • ios            • iOS 14.4.2
    • iPhone 12 Pro Max (mobile) • 9F2B654C-42A3-4578-BE0E-D780E396F04A • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-5 (simulator)
    • Chrome (web)               • chrome                               • web-javascript • Google Chrome 90.0.4430.85

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
casey@Caseys-Mac-mini firebase_test % flutter pub deps -- --style=compact
Dart SDK 2.12.3
Flutter SDK 2.0.5
firebase_test 1.0.0+1

dependencies:
- cupertino_icons 1.0.2
- firebase_auth 1.1.2 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 4.2.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- sky_engine 0.0.99
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0

```

</details>

---

**Comment by MaximeDelhorme** [comment] 2021-04-28 21:18
Same error here!

**Comment by cadaniel** [comment] 2021-04-28 21:41
So in my app that i'm actually developing, both the stream and user are null. I can make this app overwrite the app by using the same bundle-id and googleinfo-plsit. 

This sample app is able to pull the user and see it, but my actual app cannot.

**Comment by leidig54** [comment] 2021-04-29 06:36
I am receiving null with authStateChanges(). 

UserChanges() is working normally.

Android and iOS.

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.55.2)
[✓] Connected device (4 available)
```

```
  firebase_auth: ^1.0.1
  firebase_core: ^1.0.1
```

I think the change to the 7.11.0 sdk had something to do with it on the iOS side. Works normally on 7.3.0.

**Comment by sajunt4** [comment] 2021-04-29 09:30
Same issue here. As @leidig54 said, by listening to UserChanges instead of authStateChanges you can still listen to auth changes.

I haven't had this issue before, until yesterday I've updated to 7.11.0. So yes, probably the issue comes from here.

**Comment by markusaksli-nc** [comment] 2021-04-29 13:12
Hi @cadaniel 
The sample you provided doesn't really work since you are just copying over `currentUser` in `initState` so signing in won't update the value. In general the value of `currentUser` is updated at the same time as the stream so they should have the same value. 
```dart
@override
  void initState() {
    FirebaseAuth.instance.userChanges().listen((event) {
      print(FirebaseAuth.instance.currentUser);
      print(event);
    });
  }
```
Since `currentUser` is initialized to null you will not catch when the cached user is fired in the stream if you just save the value to a variable at initialization.
Since the issue isn't actually reproducible I'm going to close the issue.
Thank you

**Closed by markusaksli-nc** 2021-04-29 13:12 UTC
Labels: Needs Attention, in triage, type: bug

**Comment by cadaniel** [comment] 2021-04-29 14:34
> Hi @cadaniel 
> 
> The sample you provided doesn't really work since you are just copying over `currentUser` in `initState` so signing in won't update the value. In general the value of `currentUser` is updated at the same time as the stream so they should have the same value. 
> 
> ```dart
> 
> @override
> 
>   void initState() {
> 
>     FirebaseAuth.instance.userChanges().listen((event) {
> 
>       print(FirebaseAuth.instance.currentUser);
> 
>       print(event);
> 
>     });
> 
>   }
> 
> ```
> 
> Since `currentUser` is initialized to null you will not catch when the cached user is fired in the stream if you just save the value to a variable at initialization.
> 
> Since the issue isn't actually reproducible I'm going to close the issue.
> 
> Thank you

@markusaksli-nc 

The problem is actually when you reopen the app it shows this. 

When you login, close the app, and reopen you see the screen. 

Sorry that wasn't super clear in my report.

**Comment by cadaniel** [comment] 2021-04-29 14:44
@markusaksli-nc 

Here's a video showing the bug in more detail


https://user-images.githubusercontent.com/5515671/116569856-058cbd80-a8c7-11eb-99ac-2424b8dacd85.mov

**Comment by magnocasmor** [comment] 2021-04-29 14:54
Unfortunelly, how @markusaksli-nc says, `FirebaseAuth.instance.currentUser` always is initialized null. So, you need listen `FirebaseAuth.instance.userChanges()` to catch user state.

And the getter `FirebaseAuth.instance.currentUser` says:

You should not use this getter to determine the users current state, instead use [authStateChanges], [idTokenChanges] or [userChanges] to subscribe to updates.

**Comment by cadaniel** [comment] 2021-04-29 14:56
@magnocasmor 

So after the app reboots I'm fetching the current user. If it returns null then, when would it ever return not null after the app restarts?

**Comment by cadaniel** [comment] 2021-04-29 15:02
To highlight what I mean, I downgraded dependencies to 

    dependencies:
      firebase_core: 1.0.3
      firebase_auth: 1.0.2

And this video shows it working. When I call the getter after the app restarts, it shows the user twice. 

https://user-images.githubusercontent.com/5515671/116572886-92d11180-a8c9-11eb-8550-b998144e1605.mov

**Comment by Tom3652** [comment] 2021-04-29 15:10
I have read that the value of the currentUser is retrieved asynchronously (from persistence yes but async anyway) so it's better to use the stream (even if it's 99% of the time fast enough to not get a null currentUser without stream).

However, I am having this problem on authStateChanges() AND UserChanges() returning a null user after the app is rebuilt and the user previously signed in. 
Only on IOS (14+) and only with ```firebase_auth : 1.1.2``` plugin.
I have downgraded to ```firebase_auth: 1.1.1``` and it works perfectly with the exact same code and many rebuild situations with both versions to be sure that there is an issue and not with the cache or something else.

```
[✓] Flutter (Channel stable, 2.0.5, on macOS 11.3 20E232 darwin-x64, locale
    fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (2 available)

• No issues found!
```

Tested on iPhone XS Max, iPhone 7+ and 12 Pro max.
Works fine on Android (9 and 10 tested) with ```firebase_auth: 1.1.2```

**Comment by cadaniel** [comment] 2021-04-29 15:12
@Tom3652 

I'm having the same trouble in my real app as well. They're both null. 

The original picture was me overwritting my main app with this test app, and reading the results. On iOS you can do this by giving it the same bundle id. Odly this was able to read it. But my real app still shows null for both stream and getter.

**Comment by MedvedevAI** [comment] 2021-04-29 15:46
same trouble
@markusaksli-nc why issue is closed ?

**Comment by leidig54** [comment] 2021-04-29 16:02
I think the initial issue described here is a little confusing. Despite this, there has definitely been a breaking change introduced in a recent update, bug or otherwise, that leads to authStateChanges() returning null where it previously did not. I think some more clarification would be good before closing the issue.

**Comment by markusaksli-nc** [comment] 2021-04-29 17:31
As mentioned reading the value of currentUser at init isn't really reliable as it is updated by the same events that update the streams. It's possible that the changed value you are getting is because of the same issue that has caused authStateChanges to break but that is already a separate open issue https://github.com/FirebaseExtended/flutterfire/issues/5952

**Comment by cadaniel** [comment] 2021-04-29 17:57
It might be. But I still demonstrate that behaviour changed between the two versions. I'll make a note that the next version change to see if it works better. 

There should still be documentation that describes when you can call the getter and get the proper value.

**Comment by Aanu1995** [comment] 2021-04-29 23:25
I agree with @cadaniel The getter user works perfectly well in Android and return null in IOS.... From my own perspective the issue is whether getter user returns immediately or not because the same codebase returns user when the getter current user is called but return null in IOS. Previous versions also work and it is obvious that the bug is in the recent versions released

**Comment by darwin-morocho** [comment] 2021-05-01 23:50
I have the same problem on iOS currentUser returns null after hot restar or when the app was opened again, while the app is running currentUser works well.

**Comment by magnocasmor** [comment] 2021-05-04 13:07
Why is this issue closed?

**Comment by markusaksli-nc** [comment] 2021-05-04 13:46
The original issue description was confusing and https://github.com/FirebaseExtended/flutterfire/issues/6019 is a better fit for this.

**Comment by darwin-morocho** [comment] 2021-05-04 13:52
@magnocasmor on iOS the first time that you call to currentUser this is null so you could listen the stream and skip the first event

```dart
 User? _currentUser;
 Completer<void> _completer = Completer();

initState(){
 firebaseAuth.userChanges().skip(1).listen((user) {
      _currentUser = user;
      if (!_completer.isCompleted) {
        _completer.complete();
      }
    });
}


 Future<String?> get accessToken async {
    try {
      await _completer.future;
      return await _currentUser?.getIdToken(true);
    } catch (_) {
      return null;
    }
  }

```

**Comment by magnocasmor** [comment] 2021-05-04 14:15
> @magnocasmor on iOS the first time that you call to currentUser this is null so you could listen the stream and skip the first event
> 
> ```dart
>  User? _currentUser;
>  Completer<void> _completer = Completer();
> 
> initState(){
>  firebaseAuth.userChanges().skip(1).listen((user) {
>       _currentUser = user;
>       if (!_completer.isCompleted) {
>         _completer.complete();
>       }
>     });
> }
> 
> 
>  Future<String?> get accessToken async {
>     try {
>       await _completer.future;
>       return await _currentUser?.getIdToken(true);
>     } catch (_) {
>       return null;
>     }
>   }
> ```

But this is a bug. Different approaches for different platforms
