### ISSUE TITLE
🐛  [Firebase Messaging] type 'Null' is not a subtype of type 'bool'

### ISSUE THREAD

**Issue by HedgeHao** [FirebaseExtended/flutterfire#5390] opened 2021-03-18 13:26 UTC
## Bug report

**Describe the bug**
I'm using firebase_analytics 7.1.1. Testing on Android 10 emulator. While receiving notification in background getting this error `type 'Null' is not a subtype of type 'bool'`

### Steps to reproduce
```dart
Future<void> firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  await Firebase.initializeApp();
  print("Handling a background message: ${message.messageId}");
}

void main() {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseMessaging.onBackgroundMessage(firebaseMessagingBackgroundHandler);
  runApp(MyApp());
}
```
Message content
```json
{
    "to": "....",
    "data": {
        "title": "mytitle",
        "body": "mybody",
        "url": "myurl"
    },
    "click_action": "FLUTTER_NOTIFICATION_CLICK"
}
```

And the log
```
D/FLTFireMsgReceiver( 5889): broadcast received for message
I/flutter ( 5889): FlutterFire Messaging: An error occurred in your background messaging handler:
I/flutter ( 5889): type 'Null' is not a subtype of type 'bool'
```

### Expected behavior

Receive message without error

---

### Flutter doctor

```
[✓] Flutter (Channel master, 2.1.0-13.0.pre.104, on Linux, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.54.1)
[✓] Connected device (3 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.13.0-137.0.dev
Flutter SDK 2.1.0-13.0.pre.104
orderbar_app 1.0.0+1

dependencies:
- cupertino_icons 1.0.2
- firebase_analytics 7.1.1 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_core 1.0.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_messaging 9.0.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_inappwebview 5.1.0+4 [flutter]
- http 0.13.0 [http_parser meta path pedantic]
- path_provider 2.0.1 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0 [collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- ffi 1.0.0
- file 6.1.0 [meta path]
- firebase 9.0.0 [http http_parser js]
- firebase_analytics_platform_interface 1.1.0 [flutter meta]
- firebase_analytics_web 0.2.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_core_platform_interface 4.0.0 [flutter meta plugin_platform_interface]
- firebase_core_web 1.0.1 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 2.0.0 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 1.0.1 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- path_provider_linux 2.0.0 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 2.0.0 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.0 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.11.0
- platform 3.0.0
- plugin_platform_interface 2.0.0 [meta]
- process 4.1.0 [file path platform]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
- win32 2.0.4 [ffi]
- xdg_directories 0.2.0 [meta path process]
```

</details>

---

**Comment by Gabanelli** [comment] 2021-03-18 13:57
I'm having the same issue, when I debug i have this error when the `RemoteMessage.fromMap ` is called, because `contentAvailable` comes as null, on a field that accepts just bool.

https://github.com/FirebaseExtended/flutterfire/blob/991dd4e01e61bb02bb27de9ef64d20e7ffdb414a/packages/firebase_messaging/firebase_messaging_platform_interface/lib/src/remote_message.dart#L31

**Comment by spacejunky** [comment] 2021-03-18 16:33
Issue #4949, PR #5336

**Comment by markusaksli-nc** [comment] 2021-03-19 11:23
Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4949

**Closed by markusaksli-nc** 2021-03-19 11:23 UTC
Labels: Needs Attention, type: bug
