### ISSUE TITLE
🐛 [remote_config] web throws exception when calling instanceFor

### ISSUE THREAD

**Issue by ezet** [FirebaseExtended/flutterfire#7331] opened 2021-11-09 19:04 UTC
## Bug report

Compiling flutter for web, it throws an error whenever I call any methods on `RemoteConfig.instance`.
It works fine on Android and iOS. I have added the script tags in index.html, and tried a full clean build.

The error is `Expected a value of type 'int', but got one of type 'Null'`

### Steps to reproduce

1. Compile for web
2. Call RemoteConfig.instance.fetchAndActivate() (or any other method)
3. Error appears in log, remote config does not work

### Expected behavior

I expected Remote Config to work on web.

## Additional context

I have checked all documentation and initialization code, everything seems to be in order. It doesn't matter which method I call,  I've tried `fetc()`, `setDefaults()`, `fetchAndActivate()` and others. It seems to be an issue with the delegate call.

<details><summary>Stacktrace</summary>

```
Expected a value of type 'int', but got one of type 'Null'
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 251:49       throw_
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 84:3         castError
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 452:10   cast
C:/b/s/w/ir/cache/builder/src/out/host_debug/dart-sdk/lib/_internal/js_dev_runtime/patch/core_patch.dart 203:12                 as
packages/firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart 63:26          setInitialValues
packages/firebase_remote_config_platform_interface/src/platform_interface/platform_interface_firebase_remote_config.dart 31:30  instanceFor
packages/firebase_remote_config/src/remote_config.dart 24:55                                                                    get [_delegate]
packages/firebase_remote_config/src/remote_config.dart 138:22                                                                   setDefaults
```

</details>

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19042.1288], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] VS Code, 64-bit edition (version 1.22.1)
[√] Connected device (3 available)

• No issues found!

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
$ flutter pub deps -- --style=compact
Dart SDK 2.14.4
Flutter SDK 2.5.3
hoopit 1.0.0+1

dependencies:
- adaptive_dialog 1.2.0 [animations collection flutter meta]
- authentication 1.0.0 [equatable firebase_auth firebase_core flutter google_sign_in]
- badges 2.0.1 [flutter]
- bloc 7.2.1 [meta]
- built_collection 5.1.1
- carousel_slider 4.0.0 [flutter]
- chips_choice 2.0.1 [flutter]
- country_code_picker 2.0.2 [flutter modal_bottom_sheet collection universal_platform]
- cupertino_icons 1.0.3
- dropdown_search 2.0.0 [flutter]
- equatable 2.0.3 [collection meta]
- file_picker 4.2.0 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface ffi path]
- firebase_analytics 8.3.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_core 1.8.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_crashlytics 2.2.4 [firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface flutter stack_trace]
- firebase_messaging 10.0.9 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.7.1+2 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 0.11.0+2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.3.1 [flutter bloc provider]
- flutter_datetime_picker 1.5.1 [flutter]
- flutter_easyloading 3.0.3 [flutter flutter_spinkit]
- flutter_flavor 3.0.3 [flutter xml yaml]
- flutter_hooks 0.18.0 [flutter]
- flutter_linkify 5.0.2 [flutter linkify]
- flutter_local_notifications 9.0.2 [clock flutter flutter_local_notifications_linux flutter_local_notifications_platform_interface timezone]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- fluttertoast 8.0.8 [flutter flutter_web_plugins]
- font_awesome_flutter 9.2.0 [flutter]
- get_it 7.2.0 [async collection]
- google_fonts 2.1.0 [flutter http path_provider crypto]
- grouped_list 4.1.0 [flutter]
- hoopit_api 1.0.0 [dio dio_http_cache flutter http http_parser json_annotation]
- im_stepper 0.1.3 [flutter]
- image_picker 0.8.4+4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- intercom_flutter 5.1.0+1 [flutter flutter_web_plugins intercom_flutter_platform_interface intercom_flutter_web]
- intl 0.17.0 [clock path]
- maps_launcher 2.0.1 [flutter flutter_web_plugins url_launcher]
- material_floating_search_bar 0.3.6 [flutter meta]
- mime 1.0.1
- modal_bottom_sheet 2.0.0 [flutter]
- network_bloc 1.0.0 [dio equatable flutter flutter_bloc infinite_scroll_pagination]
- open_file 3.2.1 [flutter ffi]
- package_info_plus 1.3.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- reactive_date_time_picker 0.1.6 [flutter intl reactive_forms]
- reactive_forms 10.6.4 [flutter intl]
- responsive_builder 0.4.1 [flutter]
- responsive_framework 0.1.5 [flutter collection]
- rxdart 0.27.2
- sentry_flutter 6.1.0 [flutter flutter_web_plugins sentry package_info_plus]
- shimmer 2.0.0 [flutter]
- stream_chat_flutter 3.2.0 [cached_network_image characters chewie collection diacritic dio ezanimation file_picker flutter flutter_markdown flutter_portal flutter_slidable flutter_svg http_parser image_gallery_saver image_picker
jiffy lottie meta path_provider photo_manager photo_view rxdart share_plus shimmer stream_chat_flutter_core substring_highlight synchronized url_launcher video_compress video_player video_thumbnail visibility_detector]
- stream_chat_persistence 3.0.0 [flutter logging meta moor mutex path path_provider sqlite3_flutter_libs stream_chat]
- stripe_sdk 5.0.0-nullsafety.1 [flutter http url_launcher mask_text_input_formatter flutter_slidable simple_animations supercharged awesome_card credit_card_validator collection webview_flutter universal_html]
- supercharged 2.1.1 [supercharged_dart flutter]
- syncfusion_flutter_calendar 19.3.48 [flutter timezone syncfusion_flutter_core syncfusion_flutter_datepicker intl]
- syncfusion_flutter_core 19.3.48 [vector_math flutter]
- url_launcher 6.0.12 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.5 [crypto]

dev dependencies:
- build_runner 2.1.4 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime pack
age_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_lints 1.0.4 [lints]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- image_res 0.3.0 [flutter yaml path watcher]
- sentry_dart_plugin 1.0.0-beta.1 [yaml injector ansicolor package_config system_info]

dependency overrides:
- chewie 1.2.2 [cupertino_icons flutter provider video_player wakelock]
- provider 6.0.1 [collection flutter nested]
- timezone 0.8.0 [path]
- video_thumbnail 0.4.3 [flutter]

transitive dependencies:
- _fe_analyzer_shared 22.0.0 [meta]
- analyzer 1.7.2 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- animations 2.0.2 [flutter]
- ansicolor 2.0.1
- archive 3.1.6 [crypto path]
- args 2.3.0
- asn1lib 1.0.2
- async 2.8.1 [collection meta]
- awesome_card 1.1.5 [flutter]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_value 8.1.2 [built_collection collection fixnum meta]
- cached_network_image 3.1.0 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.1.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- connectivity_plus 2.0.2 [flutter meta connectivity_plus_platform_interface connectivity_plus_linux connectivity_plus_macos connectivity_plus_web connectivity_plus_windows]
- connectivity_plus_linux 1.1.0 [flutter connectivity_plus_platform_interface dbus meta nm]
- connectivity_plus_macos 1.2.1 [connectivity_plus_platform_interface flutter]
- connectivity_plus_platform_interface 1.1.0 [flutter meta plugin_platform_interface]
- connectivity_plus_web 1.1.0+1 [connectivity_plus_platform_interface flutter_web_plugins flutter]
- connectivity_plus_windows 1.2.0 [connectivity_plus_platform_interface flutter]
- convert 3.0.1 [typed_data]
- credit_card_type_detector 2.0.0
- credit_card_validator 2.0.0 [credit_card_type_detector]
- cross_file 0.3.1+5 [flutter meta]
- crypto 3.0.1 [collection typed_data]
- crypto_keys 0.3.0 [pointycastle meta collection quiver]
- csslib 0.17.1 [source_span]
- dart_style 2.1.1 [analyzer args path pub_semver source_span]
- dbus 0.5.6 [args ffi meta pedantic xml]
- diacritic 0.1.3
- dio 4.0.1 [http_parser path]
- dio_http_cache 0.3.0 [crypto dio flutter json_serializable json_annotation path quiver sqflite]
- drift 1.0.1 [async convert collection meta stream_channel sqlite3]
- ezanimation 0.5.0 [flutter]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- file_utils 1.0.1 [globbing path]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_auth 3.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_auth_platform_interface 6.1.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.1.3 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_crashlytics_platform_interface 3.1.4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_platform_interface 3.0.7 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.0.7 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.0.1+5 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.0.1+1 [firebase firebase_performance_platform_interface flutter flutter_web_plugins]
- firebase_remote_config_platform_interface 0.3.0+7 [firebase_core flutter meta plugin_platform_interface]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_local_notifications_linux 0.3.0 [flutter flutter_local_notifications_platform_interface dbus path xdg_directories]
- flutter_local_notifications_platform_interface 5.0.0 [flutter plugin_platform_interface]
- flutter_markdown 0.6.8 [flutter markdown meta path]
- flutter_plugin_android_lifecycle 2.0.4 [flutter]
- flutter_portal 0.4.0 [flutter]
- flutter_slidable 0.6.0 [flutter]
- flutter_spinkit 5.1.0 [flutter]
- flutter_svg 0.23.0+1 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- freezed_annotation 0.15.0 [collection json_annotation meta]
- frontend_server_client 2.1.2 [async path]
- glob 2.0.2 [async collection file path string_scanner]
- globbing 1.0.0 [path]
- google_sign_in 5.2.1 [flutter google_sign_in_platform_interface google_sign_in_web meta]
- google_sign_in_platform_interface 2.1.0 [flutter meta quiver]
- google_sign_in_web 0.10.0+3 [flutter flutter_web_plugins google_sign_in_platform_interface js meta]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_gallery_saver 1.7.1 [flutter]
- image_picker_for_web 2.1.4 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- infinite_scroll_pagination 3.1.0 [flutter sliver_tools]
- injector 2.0.0
- intercom_flutter_platform_interface 1.0.0 [flutter plugin_platform_interface]
- intercom_flutter_web 0.0.3 [flutter flutter_web_plugins intercom_flutter_platform_interface uuid]
- io 1.0.3 [meta path string_scanner]
- jiffy 4.1.0 [intl]
- jose 0.3.2 [crypto_keys meta typed_data x509 http http_parser asn1lib collection]
- js 0.6.3
- json_annotation 4.1.0 [meta]
- json_serializable 4.1.4 [analyzer build build_config collection json_annotation meta path source_gen]
- linkify 4.1.0
- lints 1.0.1
- logging 1.0.2
- lottie 1.2.1 [archive characters flutter path vector_math]
- markdown 4.0.0 [args charcode meta]
- mask_text_input_formatter 2.0.0 [flutter]
- matcher 0.12.10 [stack_trace]
- meta 1.7.0
- moor 4.6.1 [async convert collection drift meta stream_channel sqlite3]
- mutex 3.0.0
- nested 1.0.0 [flutter]
- nm 0.3.0 [dbus]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path 1.8.0
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider 2.0.5 [flutter path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- path_provider_linux 2.1.0 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- photo_manager 1.3.9+1 [flutter]
- photo_view 0.13.0 [flutter]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- pointycastle 3.3.4 [collection convert js]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.1.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1+1 [matcher]
- rate_limiter 0.1.1
- sentry 6.1.0 [http meta stack_trace uuid]
- share_plus 3.0.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- simple_animations 3.2.0 [flutter supercharged flutter_lints]
- sky_engine 0.0.99
- sliver_tools 0.2.5 [flutter]
- source_gen 1.0.3 [analyzer async build dart_style glob meta path pedantic source_span yaml]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1+1 [synchronized path meta]
- sqlite3 1.3.1 [collection ffi meta]
- sqlite3_flutter_libs 0.5.1 [flutter]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_chat 3.2.0 [async collection dio equatable freezed_annotation http_parser jose json_annotation logging meta mime rate_limiter rxdart uuid web_socket_channel]
- stream_chat_flutter_core 3.2.0 [collection connectivity_plus flutter meta rxdart stream_chat]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- substring_highlight 1.0.33 [flutter]
- supercharged_dart 2.1.1
- syncfusion_flutter_datepicker 19.3.48 [flutter intl syncfusion_flutter_core]
- synchronized 3.0.0
- system_info 1.0.1 [file_utils path]
- term_glyph 1.2.0
- test_api 0.4.2 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- universal_html 2.0.8 [async csslib charcode collection html meta source_span typed_data universal_io]
- universal_io 2.0.4 [collection crypto meta typed_data]
- universal_platform 1.0.0+1
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- vector_math 2.1.0
- video_compress 3.1.0 [flutter]
- video_player 2.2.5 [flutter meta video_player_platform_interface video_player_web html]
- video_player_platform_interface 4.2.0 [flutter flutter_test meta]
- video_player_web 2.0.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- visibility_detector 0.2.2 [flutter]
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- webview_flutter 2.1.2 [flutter webview_flutter_platform_interface webview_flutter_android webview_flutter_wkwebview]
- webview_flutter_android 2.0.15 [flutter webview_flutter_platform_interface]
- webview_flutter_platform_interface 1.2.0 [flutter plugin_platform_interface]
- webview_flutter_wkwebview 2.0.14 [flutter webview_flutter_platform_interface]
- win32 2.2.10 [ffi]
- x509 0.2.2 [asn1lib quiver crypto_keys]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

```

</details>

---

**Comment by maheshmnj** [comment] 2021-11-10 14:15
Hi @ezet, Thanks for filing the issue. [Firebase Remote Config](https://pub.dev/packages/firebase_remote_config) is not supported on the web. Closing as this isn't an issue with flutter fire if you disagree feel free to write in the comments and I will reopen it.

Thanks

**Comment by maheshmnj** [comment] 2021-11-11 05:39
Sorry for closing the issue, Reopening as remote config is supported on the web probably there's an issue on the pub as it doesn't mention the web platform.

**Comment by maheshmnj** [comment] 2021-11-11 11:00
I was able to reproduce the issue by running the [official example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_remote_config/firebase_remote_config/example)


<details>
<summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel stable, 2.5.3, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.5.3 at /Users/mahesh/Documents/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 18116933e7 (4 weeks ago), 2021-10-15 10:46:35 -0700
    • Engine revision d3ea636dc5
    • Dart version 2.14.4

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/mahesh/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/mahesh/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.1, Build version 13A1030d
    • CocoaPods version 1.10.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] IntelliJ IDEA Community Edition (version 2021.2.1)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 60.1.4
    • Dart plugin version 212.5080.8

[✓] VS Code (version 1.61.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.28.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.0.1 21A559 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 95.0.4638.69

• No issues found!
```
</details>

<details>
<summary>logs</summary>

```
Launching lib/main.dart on Chrome in debug mode...
This app is linked to the debug service: ws://127.0.0.1:49822/9wtL6SvK6gg%3D/ws
Debug service listening on ws://127.0.0.1:49822/9wtL6SvK6gg=/ws
💪 Running with sound null safety 💪
Connecting to VM Service at ws://127.0.0.1:49822/9wtL6SvK6gg=/ws
Error: Expected a value of type 'int', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:49783/dart_sdk.js:5061:11)
    at Object.castError (http://localhost:49783/dart_sdk.js:5020:15)
    at Object.cast [as as] (http://localhost:49783/dart_sdk.js:5345:17)
    at Function.as (http://localhost:49783/dart_sdk.js:19068:19)
at method_channel_firebase_remote_config.MethodChannelFirebaseRemoteConfig.new.setInitialValues (http://localhost:49783/packages/firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart.lib.js:260:67)
at Function.instanceFor (http://localhost:49783/packages/firebase_remote_config_platform_interface/src/method_channel/method_channel_firebase_remote_config.dart.lib.js:90:118)
at firebase_remote_config.RemoteConfig.__.get [_delegate] (http://localhost:49783/packages/firebase_remote_config/firebase_remote_config.dart.lib.js:63:104)
at firebase_remote_config.RemoteConfig.__.setConfigSettings (http://localhost:49783/packages/firebase_remote_config/firebase_remote_config.dart.lib.js:125:18)
at setupRemoteConfig (http://localhost:49783/packages/firebase_storage_sample/main.dart.lib.js:376:26)
    at setupRemoteConfig.next (<anonymous>)
    at http://localhost:49783/dart_sdk.js:38640:33
    at _RootZone.runUnary (http://localhost:49783/dart_sdk.js:38511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:49783/dart_sdk.js:33713:29)
    at handleValueCallback (http://localhost:49783/dart_sdk.js:34265:49)
    at Function._propagateToListeners (http://localhost:49783/dart_sdk.js:34303:17)
    at _Future.new.[_completeWithValue] (http://localhost:49783/dart_sdk.js:34151:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49783/dart_sdk.js:34172:35)
    at Object._microtaskLoop (http://localhost:49783/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:49783/dart_sdk.js:38784:13)
    at http://localhost:49783/dart_sdk.js:34519:9
```

</details>

**Comment by ezet** [comment] 2021-11-11 20:22
I saw that it was supposed to work too, that's why I created the issue. But after your initial response, I found that it is completed, but currently only in beta on pub.dev. I assume the beta works, but I haven't tested it yet. So I think you can close the issue after all.

**Comment by maheshmnj** [comment] 2021-11-12 10:08
Thanks for the update I can confirm using the [prerelease version: 1.0.0-dev.2](https://pub.dev/packages/firebase_remote_config/versions/1.0.0-dev.2)  the issue is resolved. 

Closing as already fixed in the newer version.

**Closed by maheshmnj** 2021-11-12 10:08 UTC
Labels: type: bug, plugin: remote_config, platform: web
