### ISSUE TITLE
[firebase_database] Order by key/ Order by child is not working properly 

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1070] opened 2019-10-13 19:36 UTC
## Steps to Reproduce

I am using Firebase Realtime Database for one of my flutter application. I've fetch many user data as a list and build a listview. The problem is that when i apply 'Order by key' or 'order by child' , the list stays same as before (random order).

## Here is the code

    DatabaseReference reference = FirebaseDatabase.instance.reference();
    allData.length == 0
        ? reference
            .child('teachers')
            .orderByKey()
            //.orderByChild('index')
            .once()
            .then((DataSnapshot snap) {
            var keys = snap.value.keys;

            var data = snap.value;
            allData.clear();

            for (var key in keys) {
              TeachersData d = TeachersData(
                  data[key]['bio link'],
                  data[key]['email'],
                  data[key]['name'],
                  data[key]['phone'],
                  data[key]['profile link'],
                  
                  data[key]['title']);
              allData.add(d);
              
            }

## Here the screenshot of my database

<img width="643" alt="Screenshot 2019-07-22 at 12 30 15 PM" src="https://user-images.githubusercontent.com/34546369/61611026-87749f00-ac7c-11e9-8483-0e5e2dd626fd.png">

**Comment by kroikie** [comment] 2019-10-13 19:36
@rakib205

The issue at https://github.com/flutter/flutter/issues/36661 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by diegogarciar** [comment] 2020-03-17 15:58
any progress?

**Comment by DawidSwan** [comment] 2020-03-18 12:24
Any updates please?

**Comment by dotdoom** [comment] 2020-03-29 06:47
Looks like a duplicate of #753.

**Comment by Salakar** [comment] 2020-04-20 11:33
This appears to be a duplicate of #753 - I'm going to go ahead and close this issue so we can track on #753.

**Closed by Salakar** 2020-04-20 11:33 UTC
Labels: plugin: database, resolution: duplicate, type: bug
