### ISSUE TITLE
🐛 [cloud_firestore] withConverter behaviour changes when defining a reference as field or inside a function

### ISSUE THREAD

**Issue by Silver-Fullbuster** [FirebaseExtended/flutterfire#6884] opened 2021-08-25 14:02 UTC
## Bug report

When using `withConverter`, the `toFirestore` parameters gets inferred to `Object?` when being defined inside a function, but correctly gets inferred as the converted data type when defined as a class field member

### Sample Code of withConverter in both situations

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:worldola/common/model/advert.dart';

class FirestoreTest {
  final advertRefField = FirebaseFirestore.instance
      .collection("Common")
      .withConverter(
      fromFirestore: (snapshot, _) => Advert.fromJson(snapshot.data()!),
      toFirestore: (advert, _) => advert.toJson());  // CORRECT: advert is inferred as type Advert

  void testFunction() {
    final advertRefInFunction = FirebaseFirestore.instance
        .collection("Common")
        .withConverter(
        fromFirestore: (snapshot, _) => Advert.fromJson(snapshot.data()!),
        toFirestore: (advert, _) => advert.toJson());  // ERROR HERE: advert is inferred as Object?
  }
}
```

### Expected behavior

The toFirestore parameter is inferred as the type returned in fromFirestore no matter where or how it is defined.

## Additional context

![image](https://user-images.githubusercontent.com/22327220/130804849-08e8e891-1127-4a1b-ad61-96ac0545c17e.png)

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.2.3, on Microsoft Windows [Version 10.0.19043.1110], locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Android Studio
[✓] Connected device (2 available)

• No issues found!
```

</details>

---

**Comment by rrousselGit** [comment] 2021-09-01 10:18
This looks like an analyzer issue.

Dart packages have no control over how type inference works. I'd suggest raising an issue on github.com/dart-lang/sdk

**Comment by Silver-Fullbuster** [comment] 2021-09-01 10:21
I'd appreciate if someone from the firebase teams creates the issue since they are better equipped in answering any questions they may have

**Comment by russellwheatley** [comment] 2021-09-01 10:30
@Silver-Fullbuster Your initial comment should be good enough as a reproduction. There isn't much more to it than a buggy analysis. You're welcome to post a link to the issue here for visibility if you create one, but I'm going to close this as it isn't actionable.

**Closed by russellwheatley** 2021-09-01 10:30 UTC
Labels: type: bug, plugin: cloud_firestore
