### ISSUE TITLE
🐛 [firebase_dynamic_links] When I click the link while the application is open in the background, it does not work correctly

### ISSUE THREAD

**Issue by barangungor** [FirebaseExtended/flutterfire#4716] opened 2021-01-18 14:10 UTC
## Bug report

**Describe the bug**
When I click the link while the application is closed, it does the process correctly, but when I click the link while the application is open in the background, I get this output:
E / FA (26205): Name is reserved. Type, name: event, dynamic_link_app_open
E / FA (26205): Invalid event name. Event will not be logged (FE): dynamic_link_app_open

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[√] Flutter (Channel beta, 1.25.0-8.2.pre, on Microsoft Windows [Version 10.0.19042.746], locale tr-TR)
    • Flutter version 1.25.0-8.2.pre at C:\src\flutter
    • Framework revision b0a2299859 (13 days ago), 2021-01-05 12:34:13 -0800
    • Engine revision 92ae191c17
    • Dart version 2.12.0 (build 2.12.0-133.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\bbara\AppData\Local\Android\Sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_SDK_ROOT = C:\Users\bbara\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (1 available)
    • Android SDK built for x86 (mobile) • emulator-5554 • android-x86 • Android 10 (API 29) (emulator)

! Doctor found issues in 1 category.
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-01-19 13:38
Hi @barangungor 
Could you please provide your `flutter pub deps -- --style=compact`?
Thank you

**Comment by barangungor** [comment] 2021-01-19 13:40
Dart SDK 2.12.0-133.2.beta
Flutter SDK 1.25.0-8.2.pre
MyProject 1.0.1+2

dependencies:
- animations 1.1.2 [flutter]
- auto_size_text 2.1.0 [flutter]
- awesome_dialog 1.3.0 [flutter simple_animations flare_flutter]
- badges 1.1.6 [flutter]
- cached_network_image 2.5.0 [flutter flutter_cache_manager octo_image]
- carousel_slider 2.3.1 [flutter]
- connectivity 2.0.2 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- custom_switch 0.0.1 [flutter]
- email_validator 1.0.6
- expandable 4.1.4 [flutter]
- firebase_dynamic_links 0.7.0+1 [flutter firebase_core]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_easyrefresh 2.1.8 [flutter]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_html 1.1.1 [html csslib css_colors video_player chewie webview_flutter chewie_audio flutter_svg flutter]
- flutter_inappwebview 4.0.0+4 [flutter uuid mime]
- flutter_masked_text 0.8.0 [flutter]
- flutter_rating_bar 3.2.0+1 [flutter]
- flutter_spinkit 4.1.2+1 [flutter]
- flutter_switch 0.1.5 [flutter]
- fluttertoast 7.1.6 [flutter flutter_web_plugins]
- font_awesome_flutter 8.11.0 [flutter]
- gender_selector 1.0.6 [flutter]
- google_sign_in 4.5.6 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- http 0.12.2 [http_parser path pedantic]
- jwt_decoder 1.0.3 [flutter]
- keyboard_avoider 0.1.2 [flutter]
- percent_indicator 2.1.9 [flutter]
- photo_view 0.10.3 [flutter]
- progressive_image 1.0.1 [flutter]
- provider 4.3.2+3 [collection flutter nested]
- rounded_loading_button 1.0.17 [flutter rxdart]
- scroll_app_bar 1.0.2 [flutter scroll_bars_common]
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 1.1.2 [flutter]
- validators 2.0.1 [vin_decoder]
- web_socket_channel 1.1.0 [async crypto stream_channel]

dev dependencies:
- flutter_launcher_icons 0.7.5 [image args yaml]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- asn1lib 0.6.5
- async 2.4.2 [collection]
- basic_utils 2.6.3 [http logging json_annotation pointycastle asn1lib convert crypto]
- characters 1.1.0-nullsafety.5
- charcode 1.1.3
- chewie 0.12.0 [video_player cupertino_icons wakelock flutter]
- chewie_audio 1.1.1 [video_player cupertino_icons flutter]
- clock 1.0.1 [meta]
- collection 1.15.0-nullsafety.5
- connectivity_for_web 0.3.1+4 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+7 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- css_colors 1.1.0 [flutter]
- csslib 0.16.2 [source_span]
- cupertino_icons 1.0.2
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flare_dart 2.3.4
- flare_flutter 2.0.6 [flutter flare_dart meta]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.0 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_svg 0.19.2+1 [flutter meta path_drawing vector_math xml]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- html 0.14.0+4 [csslib source_span]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- import_js_library 1.0.2 [flutter html flutter_web_plugins js]
- intl 0.16.1 [path]
- js 0.6.3-nullsafety.3
- json_annotation 3.0.1
- logging 0.11.4
- matcher 0.12.9 [stack_trace]
- meta 1.3.0-nullsafety.6
- mime 0.9.7
- nested 0.0.4 [flutter]
- octo_image 0.3.0 [flutter flutter_blurhash]
- path 1.7.0
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows] 
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 1.0.2
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- random_string 2.1.0
- rxdart 0.24.1
- sa_v1_migration 1.1.2 [flutter]
- scroll_bars_common 2.0.0 [flutter]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- simple_animations 2.4.2 [flutter supercharged sa_v1_migration pedantic]
- sky_engine 0.0.99
- source_span 1.7.0 [charcode collection meta path term_glyph]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.9.6 [path]
- stream_channel 2.0.0 [async]
- string_scanner 1.0.5 [charcode meta source_span]
- supercharged 1.12.0 [supercharged_dart flutter]
- supercharged_dart 1.4.0
- synchronized 2.2.0+2
- term_glyph 1.1.0
- typed_data 1.3.0-nullsafety.5 [collection]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.5
- video_player 1.0.1 [meta video_player_platform_interface video_player_web flutter]
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- vin_decoder 0.1.3 [meta basic_utils http random_string]
- wakelock 0.2.1+1 [flutter meta wakelock_platform_interface wakelock_web]
- wakelock_platform_interface 0.1.0+1 [flutter meta]
- wakelock_web 0.1.0+3 [flutter flutter_web_plugins import_js_library js wakelock_platform_interface]
- webview_flutter 1.0.7 [flutter]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]

**Comment by markusaksli-nc** [comment] 2021-01-19 14:10
Based on https://github.com/FirebaseExtended/flutterfire/issues/4452 it looks like `flutter clean` and a fresh install might fix this.

Is the callback not executed at all?

**Comment by barangungor** [comment] 2021-01-19 14:31
Tried but still get this errors 😢 
```
E/FA      (19605): Name is reserved. Type, name: event, dynamic_link_app_open
E/FA      (19605): Invalid event name. Event will not be logged (FE): dynamic_link_app_open
```

**Comment by markusaksli-nc** [comment] 2021-01-20 10:08
This code is dependent on the app lifecycle but that is not necessary. Here you are registering a callback for `onLink` every time the lifecycle state is resumed. I'm not sure why the print isn't being called but this isn't how you are meant to use the dynamic links package. 

You only need to register the callback once. You should also check if the app has been opened from a terminated state with a link using `getInitialLink`.

From the official example:

```dart
  @override
  void initState() {
    super.initState();
    initDynamicLinks();
  }

  void initDynamicLinks() async {
    FirebaseDynamicLinks.instance.onLink(
        onSuccess: (PendingDynamicLinkData dynamicLink) async {
          final Uri deepLink = dynamicLink?.link;

          if (deepLink != null) {
            //handleLinkData(deepLink);
          }
        }, onError: (OnLinkErrorException e) async {
      print('onLinkError');
      print(e.message);
    });

    final PendingDynamicLinkData data = await FirebaseDynamicLinks.instance.getInitialLink();
    final Uri deepLink = data?.link;

    if (deepLink != null) {
      //handleLinkData(deepLink);
    }
  }
```

Does this solve the issue for you?

**Comment by barangungor** [comment] 2021-01-20 10:48
Tried but same situation. I texted to firebase support yesterday and they replied me. Reply is:

I've tried replicating the issue on my end, and I was also able to reproduce the same error. This looks to be a bug on our end, and I've escalated this to our engineers for deeper investigation. However, I can't share any timelines yet on when the fix will be available. We'll be sure to address things though once we've identified the root cause of the issue. For further updates, please keep an eye out on our release notes, or check the Analytics reports from time to time.

 

Thanks for bringing this to our attention, and apologies for the inconvenience this may have caused you.

**Comment by ygotthilf** [comment] 2021-01-21 11:05
Hello,

Same issue here.

I rollbacked from the  `firebase_auth: 0.20.0+1 firebase_dynamic_links: 0.7.0+1`  to `firebase_auth: 0.18.4+1 firebase_dynamic_links: 0.6.3`.

As far I know, the link handler (`FirebaseDynamicLinks.instance.onLink`) returns the link without the query params, so the link cannot be validated by `FirebaseAuth.instance.isSignInWithEmailLink`.

**Comment by barangungor** [comment] 2021-01-21 11:19
It can be ok but i should use the parameters. Thanks anyway..

**Comment by mypower119** [comment] 2021-01-25 02:14
> Tried but same situation. I texted to firebase support yesterday and they replied me. Reply is:
> 
> I've tried replicating the issue on my end, and I was also able to reproduce the same error. This looks to be a bug on our end, and I've escalated this to our engineers for deeper investigation. However, I can't share any timelines yet on when the fix will be available. We'll be sure to address things though once we've identified the root cause of the issue. For further updates, please keep an eye out on our release notes, or check the Analytics reports from time to time.
> 
> Thanks for bringing this to our attention, and apologies for the inconvenience this may have caused you.

I think it is possible to conflict with the firebase library in the final versions (  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_crashlytics: ^0.4.0
  cloud_firestore: ^0.16.0
  firebase_storage: ^7.0.0
  firebase_messaging: ^8.0.0-dev.14
  firebase_dynamic_links: ^0.7.0+1)

**Comment by andreyeurope** [comment] 2021-02-08 16:42
I'm experiencing the same error.
The app handles the links correctly if it is closed, otherwise if the app is running in the background, the dynamic link just opens it.

**Comment by andreyeurope** [comment] 2021-02-17 20:30
Some updates from my side which might, hopefully, help with the issue.

I have played around with the issue, and have a few observations.
Looks like I am able to open dynamic links, but there's a catch. I can only do it one time per "app opened event".
If I (successfully) open one dynamic link for the first time since the app was opened, and then I try opening another or the same dynamic link, the second or the preceding time, the dynamic link won't do anything.

The problem is that now I can see it happening on Android too.
I've put some `print`s here and there, and the `onLink` listener isn't even triggered after the first time.

There could multiple sources where this came from, but I might copy the library directly into my app and put some breakpoints to see if I can see the firebase sdk communicating with the firebase dynamic lib.
Maybe the issue is not coming from the flutter lib, but from the Firebase SDK or even Android.

**Comment by diver2** [comment] 2021-03-08 22:39
I have the same error - dynamic links come with data == null if I have app open in background.
if app is closed, dynamic links work great

**Comment by russellwheatley** [comment] 2022-01-21 15:26
Hey @barangungor, that error is coming from Firebase Analytics (`E F/A`) I believe which will be coming from the underlying Firebase SDK. I'm going to close this as there is nothing we can do about it, and if you've already made Firebase Support aware, then I'll assume it has been addressed at this point, a year later. Will reopen if the issue persists. Thanks.

**Closed by russellwheatley** 2022-01-21 15:26 UTC
Labels: type: bug, plugin: dynamic_links

**Comment by stact** [comment] 2022-01-24 18:47
Got same issue but resolved with adding this following key on Info.plist

```xml
<key>FirebaseDynamicLinksCustomDomains</key>
<array>
  <string>https://example.com/link</string>
  <string>https://example.com/promos</string>
</array>
```

Source: https://firebase.google.com/docs/dynamic-links/custom-domains

Hope it helps.

**Comment by ffaridi1** [comment] 2022-02-09 15:25
> Got same issue but resolved with adding this following key on Info.plist
> 
> ```
> <key>FirebaseDynamicLinksCustomDomains</key>
> <array>
>   <string>https://example.com/link</string>
>   <string>https://example.com/promos</string>
> </array>
> ```
> 
> Source: https://firebase.google.com/docs/dynamic-links/custom-domains
> 
> Hope it helps.

Did you add the exact same (example) URL ?

**Comment by stact** [comment] 2022-02-09 17:05
No you need to replace with yours. Check the domain configured into your Firebase Dynamic links (default one or your custom domain)

**Comment by ffaridi1** [comment] 2022-02-09 17:47
How will that help Android?

**Comment by stact** [comment] 2022-02-09 17:56
Android doesn't need this configuration. I've no issue on Android. Follow the doc https://firebase.flutter.dev/docs/dynamic-links/overview/
