### ISSUE TITLE
OnBackgroundHandler is not working when app is terminated 

### ISSUE THREAD

**Issue by rajatjain7869** [FirebaseExtended/flutterfire#2139] opened 2020-03-08 08:28 UTC
in OnBackgroundHandler callback not recevied when app is start then notification came please try to solve this issue

**Comment by TahaTesser** [comment] 2020-03-09 14:12
Duplicate of [#1590](https://github.com/FirebaseExtended/flutterfire/issues/1590)

**Closed by TahaTesser** 2020-03-09 14:12 UTC
