### ISSUE TITLE
Error: MissingPluginException(No implementation found for method setCurrentScreen on channel plugins.flutter.io/firebase_analytics)

### ISSUE THREAD

**Issue by mark-zs** [FirebaseExtended/flutterfire#2675] opened 2020-05-31 11:04 UTC
main.dart:
``` FirebaseAnalytics firebaseAnalytics = FirebaseAnalytics();
 FirebaseAnalyticsObserver firebaseObserver = FirebaseAnalyticsObserver(analytics: firebaseAnalytics);

void main() {
  runApp(MaterialApp(
    navigatorObservers: [firebaseObserver],
```

Whenever I do `Navigator.pushNamed`...

`Error: MissingPluginException(No implementation found for method setCurrentScreen on channel plugins.flutter.io/firebase_analytics)`

I have tried `flutter clean` 'flutter build web` etc.

Thanks!

**Comment by TahaTesser** [comment] 2020-06-02 13:15
Hi @mark-zs 
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you"

**Comment by mark-zs** [comment] 2020-06-02 14:02
OK thanks so here's the story.  Seems the problem is caused because I have `url_launcher:` in my pubspec.yaml.  When I remove that I don't see the error.  So  my code sample is 

**url_launcher:**
```dependencies:
  flutter:
    sdk: flutter
  url_launcher:
  firebase_analytics: ^5.0.14```

**main.dart**
```
import 'package:firebase_analytics/firebase_analytics.dart';
import 'package:firebase_analytics/observer.dart';
import 'package:flutter/material.dart';
import 'dart:html';

FirebaseAnalytics firebaseAnalytics = FirebaseAnalytics();
FirebaseAnalyticsObserver firebaseObserver =
    FirebaseAnalyticsObserver(analytics: firebaseAnalytics);

void main() {
  runApp(NMaterialApp());
}

class NMaterialApp extends MaterialApp {
  NMaterialApp()
      : super(
          navigatorObservers: [firebaseObserver],
          initialRoute: '/',
          routes: {
            '/': (context) => Text('home'),
            '/test': (context) => Text('test'),
          },
        );
}
```

**Comment by TahaTesser** [comment] 2020-06-03 09:36
Hi @mark-zs 
From what I can see, the issue is related to a 3rd party plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/AndriousSolutions/auth/issues).
Closing, as this isn't an issue with Flutterfire itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use 3rd party plugins, and I will reopen it.
Thank you

**Comment by mark-zs** [comment] 2020-06-03 10:06
Thanks @TahaTesser .  Well I don't really agree.  If you want people to use flutterfire/firebase_analyticFreightos it has to be compatible with other common flutter libraries.

I can't say for sure if flutterfire is responsible but given that the problem occurs with two other common libraries, not one, and given that the exception comes from flutterifre code I do think flutterfire should fix this please.

**Comment by abhinavsingh** [comment] 2020-07-17 21:02
Got the same when trying to run `macOS` desktop application.  Unsure if I should open another issue issue for `macOS` platform.

# MissingPluginException for setCurrentScreen

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method setCurrentScreen on channel plugins.flutter.io/firebase_analytics)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      MethodChannelFirebaseAnalytics.setCurrentScreen (package:firebase_analytics_platform_interface/method_channel_firebase_analytics.dart:46:21)
#3      FirebaseAnalytics.setCurrentScreen (package:firebase_analytics/firebase_analytics.dart:90:29)
#4      FirebaseAnalyticsObserver._sendScreenView (package:firebase_analytics/observer.dart:80:17)
#5      FirebaseAnalyticsObserver.didPush (package:firebase_analytics/observer.dart:97:7)
#6      _NavigatorPushObservation.notify (package:flutter/src/widgets/navigator.dart:2661:14)
#7      List.forEach (dart:core-patch/growable_array.dart:302:8)
#8      NavigatorState._flushObserverNotifications (package:flutter/src/widgets/navigator.dart:3273:27)
#9      NavigatorState._flushHistoryUpdates (package:flutter/src/widgets/navigator.dart:3240:5)
#10     NavigatorState.initState (package:flutter/src/widgets/navigator.dart:2765:5)
#11     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4684:58)
#12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#16     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#17     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#18     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#19     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#23     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#24     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#26     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#27     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#28     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#29     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#30     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#35     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#36     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#40     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#44     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#45     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#47     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#48     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#49     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#52     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#53     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#54     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#55     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#56     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#57     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#58     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#59     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#61     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#72     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#76     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#81     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#82     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#83     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#85     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#86     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#87     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#89     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#90     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#93     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#94     Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#96     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#97     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#98     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#102    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#103    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#105    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#106    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#107    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#109    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#110    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#111    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#112    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#113    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#114    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#116    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#117    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#118    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#119    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#120    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#121    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#122    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#123    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#124    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#125    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#126    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#127    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#128    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#129    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#130    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#131    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#132    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#133    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#134    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#135    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#136    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#137    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#138    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#139    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#140    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#141    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#142    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#143    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#144    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#145    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#146    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#147    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#148    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#149    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#150    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#151    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#152    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#153    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#154    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#155    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#156    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#157    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#158    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#159    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#160    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#161    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#162    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5874:14)
#163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#164    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#166    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#167    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#168    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#169    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#170    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#171    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#172    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#173    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#174    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#175    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#176    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#177    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#178    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#179    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#180    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#181    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#182    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#183    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#184    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#185    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#186    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#187    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#188    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#189    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#190    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#191    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#192    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#193    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#194    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#195    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#196    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#197    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#198    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#199    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#200    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#201    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#202    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#203    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#204    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#205    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#206    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#207    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#208    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4719:11)
#209    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#210    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#211    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4710:11)
#212    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#213    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#214    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#215    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4571:16)
#216    Element.rebuild (package:flutter/src/widgets/framework.dart:4262:5)
#217    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4525:5)
#218    ComponentElement.mount (package:flutter/src/widgets/framework.dart:4520:5)
#219    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3490:14)
#220    Element.updateChild (package:flutter/src/widgets/framework.dart:3258:18)
#221    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1174:16)
#222    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1145:5)
#223    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1087:17)
#224    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2620:19)
#225    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1086:13)
#226    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:927:7)
#227    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:908:7)
#228    _rootRun (dart:async/zone.dart:1182:47)
#229    _CustomZone.run (dart:async/zone.dart:1093:19)
#230    _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#231    _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#232    _rootRun (dart:async/zone.dart:1190:13)
#233    _CustomZone.run (dart:async/zone.dart:1093:19)
#234    _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1021:23)
#235    Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#236    _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)
#237    _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)
#238    _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
```

# MissingPluginException for logEvent

```
[ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method logEvent on channel plugins.flutter.io/firebase_analytics)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
#2      MethodChannelFirebaseAnalytics.logEvent (package:firebase_analytics_platform_interface/method_channel_firebase_analytics.dart:22:21)
#3      FirebaseAnalytics.logEvent (package:firebase_analytics/firebase_analytics.dart:44:29)
#4      _CallState._makeCall (package:myapp/call/call.dart:122:21)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:992:19)
#6      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1098:38)
#7      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
#8      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
#9      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
#10     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
#11     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
#14     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
#15     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
#16     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
#17     _rootRunUnary (dart:async/zone.dart:1206:13)
#18     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
#20     _invoke1 (dart:ui/hooks.dart:267:10)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
```

# Environment Info

I am using `firebase_analytics: ^5.0.16`.

`flutter doctor -v` output:

```
[✓] Flutter (Channel dev, 1.20.0-7.1.pre, on Mac OS X 10.15.5 19F101, locale en-US)
    • Flutter version 1.20.0-7.1.pre at /Users/abhinavsingh/Dev/flutter
    • Framework revision 7736f3bc90 (7 days ago), 2020-07-10 16:33:05 -0700
    • Engine revision d48085141c
    • Dart version 2.9.0 (build 2.9.0-21.2.beta)

[!] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/abhinavsingh/Library/Android/sdk
    • Platform android-29, build-tools 29.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)
    ✗ Android license status unknown.
      Try re-installing or updating your Android SDK Manager.
      See https://developer.android.com/studio/#downloads or visit https://flutter.dev/docs/get-started/install/macos#android-setup for detailed instructions.

[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.5, Build version 11E608c
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 47.1.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.47.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.12.2
```

**Comment by Fideas** [comment] 2020-09-03 09:46
I'm experiencing the same issue and I don't have any of the aforementioned dependencies. I have to add that the error only happens on iOS devices, whereas on Android it works as expected.

**Comment by tolotrasamuel** [comment] 2020-09-22 13:44
Me I have url launcher but after I did flutter clean then stop a re run flutter run it worked

**Comment by wangxingxing123654** [comment] 2020-11-29 07:45
have the same problem

**Comment by agreensh** [comment] 2020-12-01 14:40
Same problem here (iOS, Channel dev, 1.24.0-10.2.pre, Xcode 12.2)

**Comment by RaphaelRevivor** [comment] 2021-01-22 20:38
Same issue here. Running with Flutter (Channel dev, 1.26.0-12.0.pre, on macOS 11.2 20D53 darwin-arm, locale en-SE).

**Comment by muhlba91** [comment] 2021-02-01 13:53
Same issue here on iOS and macOS. Flutter dev channel but not aforementioned dependencies.

**Comment by DavidLemayian** [comment] 2021-03-09 23:05
Try include Analytics Observer **after** [Initializing Firebase](https://firebase.flutter.dev/docs/overview#initializing-flutterfire)?

**Comment by russellwheatley** [comment] 2021-04-23 15:25
Hey @mark-zs, have you tried the latest stable version & the `firebase_analytics`? Both have had major version updates since this issue was raised.

**Comment by russellwheatley** [comment] 2021-07-02 14:03
I'm going to close this issue down due to lack of response. If there is still an issue, I will reopen.

**Closed by russellwheatley** 2021-07-02 14:03 UTC
Labels: plugin: analytics, type: bug
