### ISSUE TITLE
[firebase_firestore] Nested read always returns null for "snapshot.data()"?

### ISSUE THREAD

**Issue by sabetAI** [FirebaseExtended/flutterfire#4703] opened 2021-01-17 06:34 UTC
If I perform a nested read that is deeper than 2 levels ie FirebaseFirestore.instance.doc(a/b/c).get(), the snapshot.data.data() field always returns null (when snap.hasData). For efficiency reasons, I'd like to perform partial reads (ie field c of document b), is this possible or can I only retrieve the whole document as a snapshot?

**Comment by markusaksli-nc** [comment] 2021-01-19 12:26
Hi @sabetAI 
I'm not seeing the data field being null in nested reads for example
```dart
var test = await FirebaseFirestore.instance.doc('a/b/c/test').get().catchError((e) => print(e));
print(test.data());
```
As for partial reads, all of the methods in the implementation are listed in the [documentation](https://pub.dev/documentation/cloud_firestore/latest/cloud_firestore/DocumentReference-class.html). In both the Flutter implementation here and the upstream SDK you cannot read individual fields. Realtime Database is more suited for that.

Does this answer your question?
Thank you

**Comment by sabetAI** [comment] 2021-01-19 23:10
Thanks for the answering my question! If the value in the json is just a string and not another map, then it would be considered a field, correct?

**Comment by markusaksli-nc** [comment] 2021-01-22 12:09
Yes, that would be the case. Since this is working as intended I'm going to close the issue as solved.

**Closed by markusaksli-nc** 2021-01-22 12:09 UTC
Labels: plugin: cloud_firestore, type: bug
