### ISSUE TITLE
🐛 [firebase_auth] Phone auth verification throws exception with null error code

### ISSUE THREAD

**Issue by edgarfroes** [FirebaseExtended/flutterfire#4924] opened 2021-02-02 19:39 UTC
## Bug report

When I try to send the OTP with `FirebaseAuth.instance.verifyPhoneNumber()`, I get triggered the `verificationFailed` callback with the `FirebaseAuthException` exception type. Inside the exception object, the property `code` is coming with a null value.

### Steps to **(hypothetically)** reproduce the behavior:

1. When initing Firebase on your main.dart, set this configuration:

```
FirebaseAuth.instance.setSettings(
    appVerificationDisabledForTesting: true,
);
```

2. Spam the same phone number a few times until the error occurs. The error only occurs with few phone numbers, so you can test the error with this phone number and maybe reproduce it: `+5561992469052`

---

## Additional context

I came across #3821, it has similar behavior. I've [commented on it](https://github.com/FirebaseExtended/flutterfire/issues/3821#issuecomment-764948316) with what I think would be an explanation to the problem, and I quote:

> If your phone is not set as Test Phone in the Firebase Console, and you submit some (I don't know how many) OTP requests, it starts to recognize as spam, and your number gets blocked. The exception, indeed, comes null. I've been through this issue and lost a few hours just because the error message wasn't clear (or, in this case, wasn't available).
> 
> I think I'm "fixing" this by saving the users' phone for a further OTP request, and sign-in him with Anonymous authentication, I just can't afford for my user flow to get interrupted because Firebase won't let me proceed.
> 
> Also, I'm getting the same null exception on random users requesting the OTP for the first time. Because of this, I'm losing their conversion because the flow gets interrupted.

Also, with `appVerificationDisabledForTesting ` set to false, I couldn't reproduce the error locally, but the error still occurs in production. I caught and logged the error in my production app (installed from the Play Store), and managed to log the exception to an external tool. I've confirmed in my log that the error's `code` is null.

### Expected behavior

Log a message explaining the error, with the `code` field being not null.

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale pt-BR)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
 
[✓] Connected device (1 available)            
    ! Error: iPhone de Jéssica is not connected. Xcode will continue when iPhone de Jéssica is connected. (code -13)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
blu 1.0.5+6

dependencies:
- age 0.0.1 [flutter meta]
- algolia 0.1.7 [meta http uuid]
- auto_size_text 2.1.0 [flutter]
- carousel_slider 2.3.1 [flutter]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- darq 0.4.0+1
- data_connection_checker 0.3.4
- easy_mask 1.1.5 [flutter]
- firebase_analytics 6.3.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.4 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_dotenv 2.1.0 [flutter meta]
- flutter_keyboard_visibility 4.0.2 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_modular 2.0.1 [flutter]
- flutter_statusbarcolor 0.2.3 [flutter]
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]
- font_awesome_flutter 8.11.0 [flutter]
- geocoding 1.0.5 [flutter geocoding_platform_interface url_launcher]
- geolocator 6.1.13 [flutter geolocator_platform_interface]
- get 3.23.1 [flutter]
- google_geocoding 0.1.4 [flutter http]
- google_maps_webservice 0.0.18 [http meta]
- hexcolor 1.0.6 [flutter flutter_web_plugins]
- http 0.12.2 [http_parser path pedantic]
- keyboard_avoider 0.1.2 [flutter]
- maps_toolkit 1.1.0+2
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- poly 1.0.7+2 [csv collection]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- skeleton_text 1.0.0 [flutter]
- timer_count_down 1.0.4+1 [flutter]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- uuid 2.2.2 [crypto convert]
- via_cep 1.0.6 [http xml2json]
- visibility_detector 0.1.5 [flutter]
- whatsapp_unilink 1.0.0+1

dev dependencies:
- build_runner 1.10.7 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- change_app_package_name 0.1.2
- flutter_launcher_icons 0.8.1 [image args yaml path]
- flutter_native_splash 0.1.9 [yaml image color]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

dependency overrides:
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]
- font_awesome_flutter 8.11.0 [flutter]
- xml 4.5.1 [collection convert meta petitparser]

transitive dependencies:
- _fe_analyzer_shared 14.0.0 [meta]
- analyzer 0.41.1 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.5.2 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.4 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.4.4 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.1.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- code_builder 3.5.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- color 2.1.1
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- csv 4.1.0
- dart_style 1.3.10 [analyzer args path source_span]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.4 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flutter_keyboard_visibility_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 1.0.1 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- geocoding_platform_interface 1.0.1+1 [flutter meta plugin_platform_interface]
- geolocator_platform_interface 1.0.8 [flutter meta plugin_platform_interface vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.1.1
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.5 [matcher meta]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0-nullsafety.3
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml2json 3.0.3 [xml]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-02-03 12:07
Hi @edgarfroes 
Could you see if the behavior persists on the latest `firebase_auth: ^0.20.0+1`?
Thank you

**Comment by edgarfroes** [comment] 2021-02-03 16:43
> Hi @edgarfroes
> Could you see if the behavior persists on the latest `firebase_auth: ^0.20.0+1`?
> Thank you

I tried upgrading but I couldn't because of #4650 and #4885

**Comment by edgarfroes** [comment] 2021-02-04 03:17
@markusaksli-nc The same error still occurs on `firebase_messaging: "^8.0.0-dev.14"`.

**Comment by markusaksli-nc** [comment] 2021-02-04 09:18
I wasn't able to reproduce this myself but in any case it seems like this can still be considered a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/3821

Could you comment 

> I get triggered the verificationFailed callback with the FirebaseAuthException exception type. Inside the exception object, the property code is coming with a null value.

this bit and the fact that it is still happening on `firebase_auth: ^0.20.0+1` on the original issue?
Closing this for now.

**Closed by markusaksli-nc** 2021-02-04 09:18 UTC
Labels: Needs Attention, type: bug
