### ISSUE TITLE
[Crashlytics] Usage documentation should be updated to not use maven.fabric.io

### ISSUE THREAD

**Issue by naim5am** [FirebaseExtended/flutterfire#2290] opened 2020-04-02 22:02 UTC
https://pub.dev/packages/firebase_crashlytics

crashlytics package documentation recommends importing  maven.fabric.io repository. A rabbit hole I didn't need to go down since flutter v1.12.13.
https://firebase.google.com/docs/crashlytics/upgrade-sdk?platform=android recommends 

in root-level build.gradle 
```
    // Remove Fabric's Maven repository.
    maven { url 'https://maven.fabric.io/public' }

    // Add Google's Maven repository (if it's not there already).
    google()
  }

  dependencies {
    // ..

    classpath 'com.google.gms:google-services:4.3.3'

    // Remove the Fabric Gradle plugin.
    classpath 'io.fabric.tools:gradle:1.31.2'

    // Add the Firebase Crashlytics Gradle plugin.
    classpath 'com.google.firebase:firebase-crashlytics-gradle:2.0.0-beta03'
```

and app-level build.gradle

```
apply plugin: 'com.android.application'

// Remove the Fabric plugin.
apply plugin: 'io.fabric'

// Add the Firebase Crashlytics plugin.
apply plugin: 'com.google.firebase.crashlytics'
```

**Comment by TahaTesser** [comment] 2020-04-03 09:49
duplicate of [#2038](https://github.com/FirebaseExtended/flutterfire/issues/2038)

**Closed by TahaTesser** 2020-04-03 09:49 UTC
Labels: bug
