### ISSUE TITLE
Flutter Firestore code contains errors and fails to compile

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1238] opened 2019-10-13 19:56 UTC
When trying to run an app with the latest version of this plugin, the Flutter compiler reports the following error:

`C:\Flutter\.pub-cache\hosted\pub.dartlang.org\firebase_core-0.3.1+1\android\src\main\java\io\flutter\plugins\firebase\core\FirebaseCorePlugin.java uses unchecked or unsafe operations.`

The Android emulator fails to run the app and reports a force close crash.

**Comment by kroikie** [comment] 2019-10-13 19:56
@brian-dunn

The issue at https://github.com/flutter/flutter/issues/30230 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment] 2019-10-17 14:25
@brian-dunn please report how it works for you with cloud_firestore 0.12.9+5?

**Comment by BondarenkoStas** [comment] 2019-10-17 14:28
Duplicate of #1244

**Closed by BondarenkoStas** 2019-10-17 14:28 UTC
