### ISSUE TITLE
🐛 [firebase_auth] 🐛 Can't call cloud function while logged in as anonymous user

### ISSUE THREAD

**Issue by luiscarch11** [FirebaseExtended/flutterfire#5213] opened 2021-03-04 12:34 UTC
## Bug report

I'm trying to call a cloud function while signed in anonymously but it returns [firebase_functions/unauthenticated] Unauthenticated. I'm pretty sure the execution doesn't reach de cloud function's code since I'm logging something at it but that code line is never executed. Instead, the cloud function rejects the user.

### Steps to reproduce

I don't know how to provide details so you're able to reproduce by yourselves using my cloud functions, but I guess that just by using the same versions as me and calling your own cloud functions while signed in anonymously it should reproduce

```dart
await auth.signInAnonymously();
final userId = auth.currentUser.uid;
final data = {
     'id': userId,
     'childbirthDate': babyBirthDate.millisecondsSinceEpoch,
   };
try {
     final cloudFunction =
         FirebaseFunctions.instanceFor(region: 'europe-west1')
             .httpsCallable(functionName);
     final result = await cloudFunction.call(data);

     return right(result);
   } on FirebaseFunctionsException catch (e) {
     print(e); //I get [firebase_functions/unauthenticated] Unauthenticated
     return left(error);
   }
```

### Expected behavior

I expect the cloud function's code to be executed. Instead, the call is rejected

---

## Additional context

I'm pretty sure I'm properly logged in since auth.currentUser.uid returns a valid value(that can be checked at Firebase console)

The weirdest is that when I call the very same cloud function without the previous signInAnonymously step, it does execute the cloud function code and returns an Exception that's correct for the mentioned context:
[firebase_functions/unauthenticated] Login first

Could this be because of any error in the headers that the cloud functions SDK are sending to the cloud function?

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.22.6, on Microsoft Windows [Version 10.0.18363.1379], locale es-US)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[√] Android Studio (version 3.5)
[√] VS Code (version 1.53.2)
[√] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
dependencies:
- auto_route 0.6.9 [flutter meta]
- auto_route_generator 0.6.10 [build source_gen analyzer path build_runner auto_route]
- cloud_functions 0.9.0 [meta flutter firebase_core firebase_core_platform_interface cloud_functions_platform_interface cloud_functions_web]
- cupertino_icons 1.0.0
- dartz 0.9.2
- division 0.8.8 [flutter]
- fancy_shimmer_image 1.2.0 [flutter cached_network_image shimmer]
- firebase_auth 0.20.1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- flash 1.3.2 [flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.1.1 [flutter bloc provider]
- flutter_date_pickers 0.1.10 [flutter intl flutter_localizations]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_screenutil 4.0.2+8 [flutter]
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]
- freezed 0.12.7 [analyzer build build_config meta source_gen freezed_annotation]
- freezed_annotation 0.12.0 [collection json_annotation meta]
- get_it 5.0.6 [async meta]
- injectable 1.0.7 [get_it]
- injectable_generator 1.0.7 [build source_gen path glob analyzer injectable collection]
- intl 0.16.1 [path]
- json_serializable 3.5.1 [analyzer build build_config json_annotation meta path source_gen]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- shimmer 1.1.2 [flutter]
- uuid 2.2.2 [crypto convert]
- youtube_player_flutter 7.0.0+7 [flutter flutter_inappwebview]

dev dependencies:
- build_runner 1.11.0 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector 
characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]- lint 1.3.0

transitive dependencies:
- _fe_analyzer_shared 12.0.0 [meta]
- analyzer 0.40.6 [_fe_analyzer_shared args cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- bloc 6.1.1 [meta]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.6.1 [analyzer async convert crypto glob logging meta path]
- build_config 0.4.5 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.6 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.5.2 [analyzer build crypto graphs logging meta path package_config pool pub_semver]     
- build_runner_core 6.1.6 [async build build_config build_resolvers collection convert crypto glob graphs logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- cached_network_image 2.5.0 [flutter flutter_cache_manager octo_image]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.4 [json_annotation source_span yaml]
- cli_util 0.2.0 [path]
- clock 1.1.0-nullsafety.1
- cloud_functions_platform_interface 4.0.1 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 3.1.3 [firebase_core firebase_core_web cloud_functions_platform_interface flutter flutter_web_plugins http_parser meta js]
- code_builder 3.6.0 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- dart_style 1.3.10 [analyzer args path source_span]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_auth_platform_interface 3.1.0 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 2.1.1 [flutter path_provider uuid http path sqflite pedantic clock file rxdart image]
- flutter_inappwebview 4.0.0+4 [flutter uuid mime]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- graphs 0.2.0
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.1.1
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.2.1 [js]
- node_io 1.2.0 [file node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- provider 4.3.3 [collection flutter nested]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.7 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.5 [matcher meta]
- rxdart 0.25.0
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]   
- shared_preferences_windows 0.0.2+2 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.10+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.2+3 [flutter sqflite_common path]
- sqflite_common 1.0.3+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+3 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- vector_math 2.1.0-nullsafety.3
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.2.0 [async crypto stream_channel]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-03-04 15:35
Hi @luiscarch11 
I'm not seeing this using
```yaml
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  cloud_functions: ^1.0.0
```
Could you see if the issue persists on the latest version?
Thank you

**Comment by luiscarch11** [comment] 2021-03-04 16:04
> Hi @luiscarch11
> I'm not seeing this using
> 
> ```yaml
>   firebase_auth: ^1.0.0
>   firebase_core: ^1.0.0
>   cloud_functions: ^1.0.0
> ```
> 
> flutter doctor -v
> Could you see if the issue persists on the latest version?
> Thank you
I'm using these versions

I wish I didn't have to upgrade to the latest Dart and Flutter versions. Is this mandatory to keep this issue moving forward?


cloud_functions: ^0.9.0
firebase_auth: ^0.20.0+1
firebase_core: ^0.7.0

**Comment by markusaksli-nc** [comment] 2021-03-04 16:14
Well I was not able to reproduce the issue on the latest versions and the versions you are using are deprecated by now. You will have to upgrade to the new stable to get all of the features in Flutter 2.0 anyway. The same goes for the FlutterFire plugins.

If you don't want to upgrade that is fine but then there really is no way to proceed with the issue since we can't reproduce it. Even if it did get fixed somehow the only way you would be able to receive that fix is by upgrading to a newer version anyway.

**Comment by luiscarch11** [comment] 2021-03-04 16:31
> Well I was not able to reproduce the issue on the latest versions and the versions you are using are deprecated by now. You will have to upgrade to the new stable to get all of the features in Flutter 2.0 anyway. The same goes for the FlutterFire plugins.
> 
> If you don't want to upgrade that is fine but then there really is no way to proceed with the issue since we can't reproduce it. Even if it did get fixed somehow the only way you would be able to receive that fix is by upgrading to a newer version anyway.

You're right. I'm upgrading Flutter. I'll be getting in touch either if the problem was solved or if it's not

**Comment by markusaksli-nc** [comment] 2021-03-04 16:38
Closing this, for now, let me know if the issue persists and I'll reopen

**Closed by markusaksli-nc** 2021-03-04 16:38 UTC
Labels: Needs Attention, impact: deprecated-version, type: bug
