### ISSUE TITLE
🐛 [firebase_core] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core) in Redmi Note 4

### ISSUE THREAD

**Issue by ffriande** [FirebaseExtended/flutterfire#4373] opened 2020-12-10 12:27 UTC
## Bug report

**Describe the bug**
My App has been tested in a long set of devices and emulators, but when I run it on Xiaomi Redmi Note 4, the following exception is thrown 

<details><summary>error log</summary>

```

E/flutter ( 1916): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)
E/flutter ( 1916): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter ( 1916): <asynchronous suspension>
E/flutter ( 1916): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter ( 1916): #2      MethodChannel.invokeListMethod (package:flutter/src/services/platform_channel.dart:345:41)
E/flutter ( 1916): #3      MethodChannelFirebase._initializeCore (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:30:36)
E/flutter ( 1916): #4      MethodChannelFirebase.initializeApp (package:firebase_core_platform_interface/src/method_channel/method_channel_firebase.dart:75:13)
E/flutter ( 1916): #5      Firebase.initializeApp (package:firebase_core/src/firebase.dart:43:25)
E/flutter ( 1916): #6      startSingletons (package:MyAppName/main.dart:41:18)
E/flutter ( 1916): #7      main (package:MyAppName/main.dart:15:9)
E/flutter ( 1916): #8      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:231:25)
E/flutter ( 1916): #9      _rootRun (dart:async/zone.dart:1190:13)
E/flutter ( 1916): #10     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter ( 1916): #11     _runZoned (dart:async/zone.dart:1630:10)
E/flutter ( 1916): #12     runZonedGuarded (dart:async/zone.dart:1618:12)
E/flutter ( 1916): #13     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:223:5)
E/flutter ( 1916): #14     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:19)
E/flutter ( 1916): #15     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
E/flutter ( 1916): 
```

</details>

This error happens in both debug and release runs, but only for this device... In all the others initializeApp runs smoothly

### Steps to reproduce

```
WidgetsFlutterBinding.ensureInitialized();
await Firebase.initializeApp();
```
in Xiaomi Redmi Note 4 is causing the error

### Expected behavior

initializeApp() should succeed, like it does in the other devices.

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.4, on macOS 11.0.1 20B29 darwin-x64, locale
    en-PT)
    • Flutter version 1.22.4 at /Users/friande/Desktop/dev/flutter
    • Framework revision 1aafb3a8b9 (4 weeks ago), 2020-11-13 09:59:28 -0800
    • Engine revision 2c956a31c0
    • Dart version 2.10.4

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/friande/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)


 
[✓] Xcode - develop for iOS and macOS (Xcode 12.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.2, Build version 12B45b
    • CocoaPods version 1.9.3

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin not installed; this adds Flutter specific functionality.
    • Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (1 available)
    • Redmi Note 4 (mobile) • JJKFOF4HGUOBOZWS • android-arm64 • Android 6.0
      (API 23)

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.4
camera 0.5.8+99

dependencies:
- animated_overflow 1.0.2 [flutter simple_animations]
- animations 1.1.2 [flutter]
- audioplayers 0.16.2 [uuid path_provider flutter flutter_web_plugins]
- auto_size_text 2.1.0 [flutter]
- chewie 0.9.10 [open_iconic_flutter video_player wakelock flutter]
- clipboard 0.1.2+8 [flutter]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- connectivity 0.4.9+5 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- device_preview 0.4.8 [font_awesome_flutter http freezed_annotation json_annotation flutter flutter_localizations meta shared_preferences shared_preferences_macos]
- disk_space 0.0.3 [flutter]
- firebase_analytics 6.3.0 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.4 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_dynamic_links 0.6.3 [flutter firebase_core]
- firebase_storage 4.0.1 [flutter firebase_core]
- fl_chart 0.12.0 [flutter path_drawing equatable]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_ffmpeg 0.3.0 [flutter]
- flutter_holo_date_picker 0.2.3 [flutter]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_rating_bar 3.2.0+1 [flutter]
- flutter_spinkit 4.1.2+1 [flutter]
- flutter_svg 0.18.1 [path_drawing xml vector_math meta flutter]
- flutter_tts 1.3.0 [flutter flutter_web_plugins]
- font_awesome_flutter 8.10.1 [flutter]
- google_sign_in 4.5.6 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.7+14 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- intl 0.16.1 [path]
- package_info 0.4.3+2 [flutter]
- path_provider 1.6.24 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- percent_indicator 2.1.8 [flutter]
- permission_handler 5.0.1+1 [flutter meta permission_handler_platform_interface]
- preload_page_view 0.1.4 [flutter]
- provider 4.3.2+3 [collection flutter nested]
- sensors 0.4.2+6 [flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 2.5.4 [meta flutter]
- sliver_tools 0.1.9 [flutter]
- video_player 0.10.12+5 [meta video_player_platform_interface video_player_web flutter]
- volume_control 0.1.3 [flutter]
- wakelock 0.1.4+2 [flutter]
- webview_flutter 0.3.24 [flutter]

dev dependencies:
- flutter_driver 0.0.0 [file json_rpc_2 meta path web_socket_channel vm_service_client webdriver flutter flutter_test fuchsia_remote_debug_protocol archive args async boolean_selector characters charcode clock collection convert crypto fake_async matcher platform process pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- pedantic 1.9.2 [meta]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- collection 1.15.0-nullsafety.3
- connectivity_for_web 0.3.1+4 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.1.0+7 [flutter]
- connectivity_platform_interface 1.0.6 [flutter meta plugin_platform_interface]
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- equatable 1.2.5 [collection meta]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 6.0.0-nullsafety.2 [meta path]
- firebase 7.3.3 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.4 [flutter meta collection firebase_core plugin_platform_interface]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- freezed_annotation 0.11.0+1 [collection json_annotation meta]
- fuchsia_remote_debug_protocol 0.0.0 [json_rpc_2 process web_socket_channel flutter_test flutter_driver archive args async boolean_selector charcode clock collection convert crypto fake_async file matcher meta path platform pub_semver source_span stack_trace stream_channel string_scanner sync_http term_glyph test_api typed_data vector_math vm_service_client webdriver]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- js 0.6.2
- json_annotation 3.1.1
- json_rpc_2 2.2.2 [stack_trace stream_channel]
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- nested 0.0.4 [flutter]
- open_iconic_flutter 0.3.0 [flutter]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+6 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- permission_handler_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- petitparser 3.1.0 [meta]
- platform 3.0.0-nullsafety.2
- plugin_platform_interface 1.0.3 [meta]
- process 4.0.0-nullsafety.2 [file path platform]
- pub_semver 1.4.4 [collection]
- quiver 2.1.5 [matcher meta]
- sa_v1_migration 1.1.2 [flutter]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+3 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- simple_animations 2.4.2 [flutter supercharged sa_v1_migration pedantic]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- supercharged 1.12.0 [supercharged_dart flutter]
- supercharged_dart 1.4.0
- sync_http 0.2.0
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- video_player_platform_interface 2.2.0 [flutter meta]
- video_player_web 0.1.4+1 [flutter flutter_web_plugins meta video_player_platform_interface]
- vm_service_client 0.2.6+2 [async collection json_rpc_2 pub_semver source_span stack_trace stream_channel web_socket_channel]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- webdriver 2.1.2 [archive matcher path stack_trace sync_http]
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
```

</details>

---

**Comment by darshankawar** [comment] 2020-12-11 10:01
Similar or possibly duplicate of  https://github.com/FirebaseExtended/flutterfire/issues/4019

Related : https://github.com/FirebaseExtended/flutterfire/issues/3311

**Comment by ffriande** [comment] 2020-12-14 03:14
> @ffriande
> Can you try the official `firebase_core` plugin [example](https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_core/firebase_core/example) on the same device and see if you get the same error or not ?

The example app runs smoothly and does not produce that error. I still haven't figured out what seems to be missing... Any ideas?

**Comment by darshankawar** [comment] 2020-12-14 09:46
@ffriande 
I'd suggest you to follow-up in https://github.com/FirebaseExtended/flutterfire/issues/4019, because once that issue is fixed, your issue hopefully will be resolved too. Closing this as duplicate.
If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2020-12-14 09:46 UTC
Labels: Needs Attention

**Comment by ffriande** [comment] 2020-12-14 13:27
> @ffriande
> I'd suggest you to follow-up in #4019, because once that issue is fixed, your issue hopefully will be resolved too. Closing this as duplicate.
> If you disagree, write in comments and I'll reopen it.

I will follow up those issues you linked, although I don't think it is a similar case, therefore I disagree with closing this issue...
Unlike #4019, my app does work in a very wide variety of devices. For some reason it throws this error in Xiaomi Redmi Note 4
