### ISSUE TITLE
Cloud_Firestore in where function "whereIn" not working.

### ISSUE THREAD

**Issue by MandoraVikash** [FirebaseExtended/flutterfire#2630] opened 2020-05-25 15:55 UTC
I want to fetch those users that have value in array (string) field. But in whereIn not get any records.

**Comment by TahaTesser** [comment] 2020-05-27 12:22
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2225

**Closed by TahaTesser** 2020-05-27 12:22 UTC
