### ISSUE TITLE
🐛 Windows Support

### ISSUE THREAD

**Issue by richard457** [FirebaseExtended/flutterfire#6378] opened 2021-06-13 09:13 UTC
Need to know if there is a plan in supporting plugins on windows as I can tell, only macOS is focused I have no idea is the case or if windows is rejected.

**Comment by markusaksli-nc** [comment] 2021-06-14 12:11
Closing as a duplicate of https://github.com/FirebaseExtended/flutterfire/discussions/5795

**Closed by markusaksli-nc** 2021-06-14 12:11 UTC
Labels: Needs Attention, in triage, type: bug
