### ISSUE TITLE
🐛 [FIREBASE_MESSAGING] iOS not receiving notification.

### ISSUE THREAD

**Issue by shinewanna** [FirebaseExtended/flutterfire#6079] opened 2021-05-08 06:35 UTC
## Bug report

**Describe the bug**
Notification not receiving on iOS. android receive notification. only in iOS

### Steps to reproduce
You can git pull and add your Firebase Server Token and Google-Service-Info.plist in my example project. Github example project link [here](https://github.com/shinewanna/github-page-test).

I already add all configuration of iOS firebase messaging like switch on the Push Notification and Background Mode in Xcode and add Google-Service-Info.plist in Runner and added APNs Authentication Key in Firebase Project Setting> Cloud Messaging. I think that's all of iOS firebase messaging notificaion. And when i run i can see firebase fcm token in debug console and send fcm from firebase, app not receiving notification.

Flutter: 2.0.5
firebase_messaging: ^9.1.1

**Comment by shinewanna** [comment] 2021-05-11 06:05
Hay are u there, I'm still having this issue, no one respond my issue yet.

**Comment by markusaksli-nc** [comment] 2021-05-11 13:08
Hi @shinewanna 
Have you tried sending a notification directly to the FCM token?
Have you made sure to carefully follow all of the steps in https://firebase.flutter.dev/docs/messaging/apple-integration?
Thank you

**Comment by shinewanna** [comment] 2021-05-11 13:15
Yes sir, both FCM and api called are not work. Yes, I did all of the things from apple integration but not luck to me.

**Comment by shinewanna** [comment] 2021-05-11 15:14
Permissions are requested.
And I'm having this warning when i run from xcode.
But i already added Apns in firebase.
![Screen Shot 2021-05-11 at 9 41 13 PM](https://user-images.githubusercontent.com/39454969/117840280-07308b00-b2a2-11eb-9d05-a2e16c0a09a6.png)

<summary>
<detail>log</detail>
2021-05-11 21:37:51.958462+0630 Runner[46105:413156] 7.11.0 - [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '385855819233'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.
</summary>

**Comment by markusaksli-nc** [comment] 2021-05-12 10:29
Have you made sure the package identifier is the same as in the apple configuration?

**Comment by shinewanna** [comment] 2021-05-12 13:03
Yes bro, it's work fine before firebase_messaging update. After update it's not working anymore. 

I configure with update apple integration docs. But it's not work. So i created new example project and try to show notification in iOS that's also not working.

**Comment by CostierLucas** [comment] 2021-05-13 08:20
Same issue here since last update

**Comment by tstarasinic** [comment] 2021-05-13 09:31
Same issue after updating firebase_core and firebase_messaging. Is there any fix for this ?

**Comment by markusaksli-nc** [comment] 2021-05-14 11:25
Could you provide the exact message payload you are sending, the send response, and any relevant logs from either `flutter run -v` or the device logs when the message should be received?

**Comment by shinewanna** [comment] 2021-05-15 05:00
It's not working with anything, even with FCM token and send test message from Firebase console. And it's not showing any logs after sent.

But showing one warning when i run with Xcode

Logs
[Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID ''. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.

**Comment by CostierLucas** [comment] 2021-05-16 12:58
Any news ?

**Comment by shinewanna** [comment] 2021-05-17 04:51
Not yet

**Comment by markusaksli-nc** [comment] 2021-05-17 10:05
Again, same question as before. Could you send directly to the fcm token through the API and log the response from the API. It should look something like:
```
projects/triage-79c7c/messages/1621245764946429
```
or
```
Error sending message: FirebaseMessagingError: The registration token is not a valid FCM registration token
    at FirebaseMessagingError.FirebaseError [as constructor] (C:\Users\marku\Desktop\Projects\firebase_messaging_send\node_modules\firebase-admin\lib\utils\error.js:44:28)
    at FirebaseMessagingError.PrefixedFirebaseError [as constructor] (C:\Users\marku\Desktop\Projects\firebase_messaging_send\node_modules\firebase-admin\lib\utils\error.js:90:28)
    at new FirebaseMessagingError (C:\Users\marku\Desktop\Projects\firebase_messaging_send\node_modules\firebase-admin\lib\utils\error.js:256:16)
    at Function.FirebaseMessagingError.fromServerError (C:\Users\marku\Desktop\Projects\firebase_messaging_send\node_modules\firebase-admin\lib\utils\error.js:289:16)
    at Object.createFirebaseError (C:\Users\marku\Desktop\Projects\firebase_messaging_send\node_modules\firebase-admin\lib\messaging\messaging-errors-internal.js:35:47)
    at C:\Users\marku\Desktop\Projects\firebase_messaging_send\node_modules\firebase-admin\lib\messaging\messaging-api-request-internal.js:79:51
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async sendWithAdmin (C:\Users\marku\Desktop\Projects\firebase_messaging_send\index.js:112:20) {
  errorInfo: {
    code: 'messaging/invalid-argument',
    message: 'The registration token is not a valid FCM registration token'
  },
  codePrefix: 'messaging'
}
```
and provide the exact payload of the message you are sending, the device, and the iOS version. Without some logs to point to what exactly is going wrong or an exact reproducible case we can't really fix anything. I still haven't been able to reproduce this on any devices.

**Comment by shinewanna** [comment] 2021-05-20 06:03
Ok, api response are like success below
![Screen Shot 2021-05-20 at 12 27 29 PM](https://user-images.githubusercontent.com/39454969/118926944-16c96700-b967-11eb-8d37-5f61671d0754.png)

No error occur when sending notification, just not receiving notification on device.

I already mention that but i mention again,

[Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID ''. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.

this log is showing when the device is start to run in iOS.

**Comment by luvishq** [comment] 2021-05-24 06:17
Any update on this ? This is a blocker for me, we are not receiving notification on iOS ? Also if anyone has a workaround to fix it ?

**Comment by shinewanna** [comment] 2021-05-24 07:53
Yes bro, my project is just stuck with this issue. Not solved yet😪😪.

**Comment by russellwheatley** [comment] 2021-05-24 08:39
@shinewanna, are you sure you've enabled push notifications?

> It's not working with anything, even with FCM token and send test message from Firebase console. And it's not showing any logs after sent.
> 
> But showing one warning while the device start run the application with xcode.
> 
> Logs
> [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID ''. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set.

this warning message often occurs when you haven't set push notifications in xcode. Please confirm it is set? [Relevant documentation](https://firebase.flutter.dev/docs/messaging/apple-integration#enable-push-notifications)

**Comment by shinewanna** [comment] 2021-05-24 08:42
All are said to on the notification in xcode. But i already turned on the notification on xcode and the iOS notification is receiving before update.

**Comment by russellwheatley** [comment] 2021-05-24 09:00
Hmmm, presumably you're [requesting permission](https://firebase.flutter.dev/docs/messaging/permissions#requesting-permissions)? 

Have you tried the latest version by the way? `10.0.0`?

**Comment by shinewanna** [comment] 2021-05-24 11:14
Yes, i request permission and the device also ask for notification permission.

**Comment by russellwheatley** [comment] 2021-05-24 12:49
could you let me know if v10 works for you? Thanks.

**Comment by shinewanna** [comment] 2021-05-26 03:05
also not work with v10.

**Comment by darshankawar** [comment] 2021-05-26 06:50
Keeping this issue open for further insights and investigation from team.

**Comment by mericgerceker** [comment] 2021-05-27 11:42
I have same problem

**Comment by tmtit** [comment] 2021-05-31 07:26
I am facing the same issue, please fix

**Comment by tmtit** [comment] 2021-05-31 08:14
Did you run on the real device? i tried and it worked perfectly

**Comment by mericgerceker** [comment] 2021-05-31 09:54
> Did you run on the real device? i tried and it worked perfectly

I tested it with the real device. :( Do you have a sample project? Also are you sending the notification via postman?

**Comment by ebrarbilgili** [comment] 2021-06-07 20:46
i also have this issue. the problem that i wonder is that my applications i published before flutter null safety and firebase_messaging null safety is still working!!! and i want to publish new version of that apps but firebase messaging on ios is not working on background or on terminated. i really wonder this issue why why why?

**Comment by shinewanna** [comment] 2021-06-16 06:13
Is anyone fixed this issue?
I opened the issued very long days ago, still iOS not receiving notification.

**Comment by junaidlodhi22** [comment] 2021-06-18 16:40
Having the same problem... I am using **version 10.0.2**
I am receiving notifications in debug mode. but not in release mode via firebase app distribution

**Comment by junaidlodhi22** [comment] 2021-06-18 17:51
And now it has stopped working in debug mode also giving the error 

>  APNS device token not set before retrieving FCM Token for Sender ID

**Comment by shinewanna** [comment] 2021-06-25 04:42
Hello, it's really a bug for my current project, i need to fixed it. Client is requesting many times to fixed this issue.
Hello, any contributer or worked developer help me to create a simple iOS notification from TeamViewer, i'll share my screen.

**Comment by yahyanasser** [comment] 2021-06-26 14:14
I am facing the same issue, please fix

**Comment by junaidlodhi22** [comment] 2021-06-28 07:49
I got it working.
First of all method swizzling is always disabled if you are using Phone auth from firebase. right now it does not matter if you set it to false or do not add entry **FirebaseAppDelegateProxyEnabled**.
so if you are using Phone auth along with notifications you have to add method swizzling code.

    override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
            let firebaseAuth = Auth.auth()
        
            firebaseAuth.setAPNSToken(deviceToken, type: AuthAPNSTokenType.unknown)
        }
    
        override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
            let firebaseAuth = Auth.auth()
            if (firebaseAuth.canHandleNotification(userInfo)){
                completionHandler(.noData)
                print(userInfo)
                return
            }
        }

**Comment by shinewanna** [comment] 2021-06-28 10:21
> I got it working.
> First of all method swizzling is always disabled if you are using Phone auth from firebase. right now it does not matter if you set it to false or do not add entry **FirebaseAppDelegateProxyEnabled**.
> so if you are using Phone auth along with notifications you have to add method swizzling code.
> 
> ```
> override func application(_ application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: Data) {
>         let firebaseAuth = Auth.auth()
>     
>         firebaseAuth.setAPNSToken(deviceToken, type: AuthAPNSTokenType.unknown)
>     }
> 
>     override func application(_ application: UIApplication, didReceiveRemoteNotification userInfo: [AnyHashable : Any], fetchCompletionHandler completionHandler: @escaping (UIBackgroundFetchResult) -> Void) {
>         let firebaseAuth = Auth.auth()
>         if (firebaseAuth.canHandleNotification(userInfo)){
>             completionHandler(.noData)
>             print(userInfo)
>             return
>         }
>     }
> ```

I'm not using firebase phone auth, but facebook and google login are used.
```dart
	<key>FirebaseAppDelegateProxyEnabled</key>
	<false/>
```
i disabled the FirebaseAppDelegateProxyEnabled.
So, is i need to add ur code snippet in my app?
I'm not use phone auth, but iOS notification is not work for me.

**Comment by junaidlodhi22** [comment] 2021-06-28 10:39
without phone auth... it should work. remove this entry from **info.plist.** I don't think it is required if you are using phone auth
try to check ios notifications settings

**Comment by shinewanna** [comment] 2021-06-28 11:20
Humm, not work for me.
this warning is not disappear for me.

[Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '102218486927'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set

if u don't mind, can u check my example project with remote desktop?

**Comment by junaidlodhi22** [comment] 2021-06-28 12:02
Sure

**Comment by shinewanna** [comment] 2021-06-28 12:14
https://www.facebook.com/profile.php?id=100013868348978

That's my facebook id, u can add request or give me ur id, i'll send request. 

(+95 9693543788) This my Telegram account. U can hi whatever u like.

**Comment by shinewanna** [comment] 2021-07-04 13:24
Hay, Finally i found the solution. 

Check your APNs certificate from Firebase, Cloud Messaging,iOS

In my case, my debug certificate key has been expired. 

Or try to remove your certficate from Firebase and regenerate the certificate and readd it in Firebase, Cloud Messaging, iOS config

If other are fixed with my solution, i'll closed my issue.

**Comment by markusaksli-nc** [comment] 2021-07-05 11:23
Since this turned out to be a setup issue that we could not reproduce in any way with a fresh setup I'm going to close the issue. If anyone is still facing this issue you can attempt the same solution or just try completing the setup from scratch. 

Unless we get some very specific steps to also face this issue with a fresh and correct setup on iOS this isn't really an issue we can "fix" in any way, as it will likely also be caused by user config.

**Closed by markusaksli-nc** 2021-07-05 11:23 UTC
Labels: platform: ios, plugin: messaging, type: bug
