### ISSUE TITLE
Firebase Return differently when comes to map 

### ISSUE THREAD

**Issue by shuvojit007** [FirebaseExtended/flutterfire#220] opened 2019-09-26 06:29 UTC
Firstly ,
My data   :
```
data : 
    10:150
    20:250

return data:{10: 150, 20: 250},
```

Secondly,
when data stored likes  :
```
data : 
    1:150
    2:250

return data:[null, 150,  250],
``

**Comment by Ehesp** [comment] 2020-04-21 14:37
Closing due to lack of detail and staleness. Please provide some more details about what plugin this is along with a reproduction case.

**Closed by Ehesp** 2020-04-21 14:37 UTC
Labels: type: bug
