### ISSUE TITLE
cloudfirestore/CloudFirestorePlugin.java 

### ISSUE THREAD

**Issue by taracell** [FirebaseExtended/flutterfire#2610] opened 2020-05-22 14:56 UTC
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when when attempting to load my application and I get the red text that states the following:  

Note: /Users/user/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.5/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
warning: [options] source value 1.5 is obsolete and will be removed in a future release
warning: [options] target value 1.5 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
3 warnings

**Comment by ram231** [comment] 2020-05-23 04:02
How did you solved this today?

I'm using Flutter 1.18.0-11.pre SDK

**Comment by iapicca** [comment] 2020-05-25 14:10
Hi @ram231 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose`,
your `pubspec.yaml` 
and a reproducible minimal code sample.
Thank you

**Comment by ram231** [comment] 2020-05-25 14:13
@iapicca , Here is the result in the separate issue here #2611 
I closed it due to duplicate issues.

**Comment by iapicca** [comment] 2020-05-26 12:18
Hi @taracell 
I see there's an open [issue](https://github.com/FirebaseExtended/flutterfire/issues/1914
) addressing the case you described.
Please follow up on that issue, I'm closing the current one as duplicate.
If you disagree, please write in the comments and I will reopen it.
Thank you

**Closed by iapicca** 2020-05-26 12:18 UTC
Labels: blocked: customer-response

**Comment by shinya-tkhs** [comment] 2020-07-30 10:07
I have the same error on Flutter 1.20.0-7.3.pre

```
Note: /Users/user/flutter/.pub-cache/hosted/pub.dartlang.org/cloud_firestore-0.13.7/android/src/main/java/io/flutter/plugins/firebase/cloudfirestore/CloudFirestorePlugin.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

I ran the commands below but no luck.
```
flutter pub cache repair
flutter clean
```
