### ISSUE TITLE
[firebase_remote_config] Support the v2 Android embedder plugins API

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#304] opened 2019-10-13 16:33 UTC

**Comment by kroikie** [comment] 2019-10-13 16:33
@amirh
    
    The issue at https://github.com/flutter/flutter/issues/41876 has been closed and moved here. Future collaboration
    on this issue will be done here.

**Comment by creativecreatorormaybenot** [comment] 2019-10-13 16:52
@kroikie This is still a duplicate of #72.

**Comment by kroikie** [comment] 2019-10-13 20:43
@creativecreatorormaybenot thanks we will note that during triage.

**Comment by kirstywilliams** [comment] 2020-04-27 10:15
Closing. Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/72

**Closed by kirstywilliams** 2020-04-27 10:15 UTC
Labels: type: enhancement
