### ISSUE TITLE
[firebase_crashlytics] FirebaseCrash is not linked

### ISSUE THREAD

**Issue by vivchar** [FirebaseExtended/flutterfire#2420] opened 2020-04-23 09:40 UTC
**Describe the bug**
I configure firebase_crashlytics by this guide https://pub.dev/packages/firebase_crashlytics

**To Reproduce**
1. integrate `firebase_crashlytics 0.1.3+3`
2. launch android app
4. see LogCat
Result: you will see error `FirebaseCrash is not linked. Skipping initialization`

**Expected behavior**
Crashlytics should work, and you should see non-fatal exceptions in firebase console.

**Additional context**

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[✓] Flutter (Channel stable, v1.12.13+hotfix.9, on Mac OS X 10.14.5 18F132, locale en-RU)
    • Flutter version 1.12.13+hotfix.9 at /Users/vvv/Library/flutter
    • Framework revision f139b11009 (3 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/vvv/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 42.1.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.43.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.9.0

[✓] Connected device (1 available)
    • Redmi 4X • b2af1cc17d04 • android-arm64 • Android 7.1.2 (API 25)

• No issues found!
```

**Simple logs**

```
2020-04-23 16:32:10.790 28840-28840/com.filmillion.application D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
2020-04-23 16:32:10.791 28840-28840/com.filmillion.application D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
2020-04-23 16:32:10.792 28840-28840/com.filmillion.application I/FirebaseInitProvider: FirebaseApp initialization successful
2020-04-23 16:32:10.854 28840-28863/com.filmillion.application I/FA: App measurement is starting up, version: 16250
2020-04-23 16:32:10.854 28840-28863/com.filmillion.application I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
2020-04-23 16:32:10.854 28840-28863/com.filmillion.application I/FA: To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.filmillion.application
2020-04-23 16:32:10.872 28840-28840/com.filmillion.application I/CrashlyticsCore: Initializing Crashlytics 2.6.8.32
2020-04-23 16:32:10.883 28840-28866/com.filmillion.application D/NetworkSecurityConfig: No Network Security Config specified, using platform default
2020-04-23 16:32:10.912 28840-28840/com.filmillion.application I/CrashlyticsInitProvider: CrashlyticsInitProvider initialization successful
```

**Comment by TahaTesser** [comment] 2020-04-23 15:25
duplicate of [#2422](https://github.com/FirebaseExtended/flutterfire/issues/2422)

**Closed by TahaTesser** 2020-04-23 15:25 UTC
