### ISSUE TITLE
[Firebase_messaging] : version 8.0.0-dev.7 unable to hit message handler functions. 

### ISSUE THREAD

**Issue by cgonzalezandrades** [FirebaseExtended/flutterfire#4054] opened 2020-11-07 05:22 UTC
Im unable to hit the message handle functions when sending a notification from Firebase cloud messaging console.

 
1. Send message from firebase console.
2. put print statements in message handler functions like onBackgroundMessage, onMessageOpenedApp and onMessage.listen

I was able to send notifications with the new version deployment (8.0.0-dev.7) in IOS . I can see the notification in IOS physical device but when I click the notification I dont see the print logs Im setting in the message handler functions. 

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print('message from background handler');
  print("Handling a background message: ${message.messageId}");
}`

@override
  void didChangeDependencies() async {
    if (!_isInit) {
      // FirebaseMessaging.onBackgroundMessage(
      //     _firebaseMessagingBackgroundHandler);
      // FirebaseMessaging messaging = FirebaseMessaging.instance;
      FirebaseMessaging.instance.getToken().then((value) {
        print(value);
      });

      FirebaseMessaging.onMessageOpenedApp.listen((event) {
        print('hey');
        print(event);
      });

      FirebaseMessaging.onBackgroundMessage(
          _firebaseMessagingBackgroundHandler);

      FirebaseMessaging.onMessage.listen((RemoteMessage message) {
  
        print('Got a message whilst in the foreground!');
        print('Message data: ${message.data}');

        if (message.notification != null) {
          print(
              'Message also contained a notification: ${message.notification}');
        }
      });

    }

    _isInit = true;
    super.didChangeDependencies();
  }
```

**Comment by Neil2847** [comment] 2020-11-09 06:13
I have the above problems too with iOS real devices.

**Comment by Salakar** [comment] 2020-11-09 13:13
Where have you defined the `_firebaseMessagingBackgroundHandler` - can you show me the content of the whole dart file where you've defined it. You need to define it outside any classes as a top-level/global function.

**Comment by muccy** [comment] 2020-11-09 13:44
I can confirm that `onMessage` function is not triggered when app is foregrounded on iOS. On Android device I receive `onMessage` correctly

**Comment by itmediacreations** [comment] 2020-11-09 15:19
As onMessage is not Triggered as onMessageOpenedApp.

**Comment by Salakar** [comment] 2020-11-09 15:49
It's not really clear here what is not working, 

Which one is not working, `onMessage`, `onMessageOpenedApp` or `onBackgroundMessage`? 

Can you confirm you are also testing this with a real device, this will **not** work on an iOS simulator.

Can you also confirm APNs has been setup correctly in your project, iOS/macOS will not work at all without APNs - it must be configured.

**Comment by muccy** [comment] 2020-11-09 16:39
Hi Salakar,
`onMessage` status according to my tests:

* it doesn't work on iOS Simulator
* it doesn't work on iOS device
* it does work on Android
* push notifications are configured properly

As a workaround, which is probably a better solution than the original, I've used `FirebaseMessaging.instance.setForegroundNotificationPresentationOptions`

**Comment by Salakar** [comment] 2020-11-09 16:46
> Hi Salakar,
> `onMessage` status according to my tests:
> 
> * it doesn't work on iOS Simulator
> * it doesn't work on iOS device
> * it does work on Android
> * push notifications are configured properly
> 
> As a workaround, which is probably a better solution than the original, I've used `FirebaseMessaging.instance.setForegroundNotificationPresentationOptions`

> * it doesn't work on iOS Simulator

Correct - FCM will only ever work on a real device.

> it doesn't work on iOS device

Could you explain specifically what doesn't work with `onMessage`? You don't get the event in Dart or it doesn't show notifications in the foreground.

**Comment by muccy** [comment] 2020-11-09 17:29
I don't receive the Dart event.
I followed the guide, I'm sending the messages through Firebase Console. I'm really sure the implementation works because notifications are received by the device when app is backgrounded. What is more, I read a log printed (I assume) from the Flutter Fire plugin on VS Code console containing the message I've just sent.

**Comment by Salakar** [comment] 2020-11-09 17:38
> @muccy What is more, I read a log printed (I assume) from the Flutter Fire plugin on VS Code console containing the message I've just sent.

Ah interesting, can you show me this log. Also can you show me how you've setup the `onMessage` code in your Dart code?

**Comment by muccy** [comment] 2020-11-09 17:40
Not now because I'm quite busy, sorry. But I'll do it for sure as soon as I can.
Thank you very much

**Comment by Salakar** [comment] 2020-11-09 17:41
> Not now because I'm quite busy, sorry. But I'll do it for sure as soon as I can.

Ok, thanks. Could you also let me know the version of iOS your device is running when you can also.

**Comment by cgonzalezandrades** [comment] 2020-11-09 21:49
@Salakar My apologies for the late response.

Im using a reald device ( IOS 14.1) I have firebase console setup and Im able to send messages with firebase console and cloud functions. However, when my app in background, messages are not hitting **onBackgroundMessage**  

`Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print('message');
  print("Handling a background message: ${message.messageId}");
}` 

_Outside my class_
`_firebaseMessagingBackgroundHandler`

Working for me
* onMessage.  
* onMessageOpenedApp. 

Not working 
* onBackgroundMessage. 
 
`flutter_local_notifications: ^3.0.1+2`
`firebase_messaging: ^8.0.0-dev.7`

let me know if you need more information...

**Comment by itmediacreations** [comment] 2020-11-10 07:07
Sorry for lack of information. In my case:

Im testing on real devices:

Android => Huawei P30 Pro, Android 10.
iOS => IPhone X, iOS 14.2

I was using previous version 7.0.3 in production, everything works well. After migrating to 8.0.0-dev.7 something goes wrong on iOS side. As I'am sending notification from Firebase I can see in my logs, that all that data is corect but functions which I pass to onMessage and onMessageOpenedApp wont be triggered.

I'll mention again that everything works on Android side. The problem only occurs when testing on iOS.
Notification will display only in case when application is in background but after click on notification application will come to foreground and onMessageOpenedApp isnt trigerred, as I said ealier i can see print data from my firebase console but onMessage functions or onMesssageOpenedApp won't be triggered.

Log print from console

`2020-11-10 07:59:57.399924+0100 Media Creations[1059:481366] flutter: {messageId: 1604991596928874, data: {fcm_options: {image: https://media-creations.pl/assets_mobile/campaigns/DD_49.jpg}, image_url: https://media-creations.pl/assets_mobile/campaigns/DD_49.jpg, url: null, only_image: true}, sentTime: 1604991596, mutableContent: true, notification: {title: Tytuł, apple: {}, body: Opis}}`

Class with Notification 
```
import 'package:Media_Creations/models/db_data.dart' show NotificationData;
import 'package:Media_Creations/models/strings_data.dart';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';

import './widgets/notification_full.dart';
import './widgets/notification_only_image.dart';

class PushNotificationManager {
  static final PushNotificationManager _instance = PushNotificationManager._();

  final FirebaseMessaging _firebaseMessaging = FirebaseMessaging.instance;

  PushNotificationManager._();

  factory PushNotificationManager() => _instance;

  bool _initialized = false;

  Future<dynamic> _buildDialog(Widget child, BuildContext context) async =>
      showDialog(
        context: context,
        useRootNavigator: true,
        useSafeArea: true,
        builder: (ctx) => child,
        barrierDismissible: true,
      );

  void _fetchMessage(RemoteMessage message, BuildContext context) async {
    if (message == null || message.notification == null) return;
    final Map<String, String> _data = message.data;
    if (_data.containsKey(NotificationData.keyOnlyImage))
      _buildDialog(
          NotificationOnlyImage(
            imageUrl: _data[NotificationData.keyImageUrl],
            innerUrl: _data[NotificationData.keyUrl],
          ),
          context);
    if (_data.containsKey(NotificationData.keyFullNotification))
      _buildDialog(
          NotificationFull(
            imageUrl: _data[NotificationData.keyImageUrl],
            url: _data[NotificationData.keyUrl],
            title: _data[NotificationData.keyTitle],
            description: _data[NotificationData.keyDescription],
            btnCloseText: _data[NotificationData.keyBtnCancel],
            btnOpenText: _data[NotificationData.keyBtnOk],
          ),
          context);
  }

  Future<void> init(BuildContext context) async {
    if (!_initialized) {
      await _firebaseMessaging.requestPermission();
      _firebaseMessaging
          .getInitialMessage()
          .then((message) => _fetchMessage(message, context));
      FirebaseMessaging.onMessage
          .listen((message) => _fetchMessage(message, context));
      FirebaseMessaging.onMessageOpenedApp
          .listen((message) => _fetchMessage(message, context));

      String token = await _firebaseMessaging.getToken();
      print("${Strings.firebaseToken}$token");

      _initialized = true;
    }
  }
}
```

**Comment by Salakar** [comment] 2020-11-10 15:56
I think I'd probably need to screenshare with someone as I still don't full understand where it's going wrong and I'd like to see the full environment/project setup. With FCM there's so many moving parts it's hard to get the complete picture down in a GitHub issue without going back and forth on replies forever 😅  

Or if someone is able to add me to their project on git I can also look there (confidentially of course).

**Comment by Den-Ree** [comment] 2020-11-11 12:36
I'm using 8.0.0-dev.8 and it doesn't work on iOS, but on 7.0.3 everything was okay.

**Comment by Den-Ree** [comment] 2020-11-12 14:25
@Salakar I'm okay to schedule a zoom call and go through the project.

**Comment by Salakar** [comment] 2020-11-12 16:26
@Den-Ree dropped you an email

**Comment by Den-Ree** [comment] 2020-11-12 17:14
@Salakar replied, I'm planning to do testing on iOS 14.2.

**Comment by Den-Ree** [comment] 2020-11-16 12:05
@Salakar no luck, I don't receive any notifications on iOS 14.2, tested on a real device.

**Comment by HugoHeneault** [comment] 2021-01-15 10:53
Hey guys! Some time passed since last update, did you manage to get your notification through your app? 

Thanks 🙏

**Comment by kuromukira** [comment] 2021-01-28 02:35
```FirebaseMessaging.onMessage``` in my end does not work. Although I see a printed log of the notification I sent via FCM legacy HTTP.

**Comment by itmediacreations** [comment] 2021-01-28 09:16
> `FirebaseMessaging.onMessage` in my end does not work. Although I see a printed log of the notification I sent via FCM legacy HTTP and notification banner is shown.
> 
> This is on an iOS Device (14.4) - firebase_messaging 8.dev14

Which FB SDK version do you use?

**Comment by maares** [comment] 2021-02-13 05:45
Hi just using the packages for the first time, after several hours, searching on this git issues, found that I was mistakenly sending the payload, thanks to #4300  :

> Does the background callback work if you send a notification through FCM?
> 
> Such as
> 
> ```json
> {
>   "notification":{
>     "title": "This is the title",
>     "body": "This is the body",
>   },
>   "content_available": true,
>   "priority": "high",
>   "data": {
>     "id": 15,
>     "type": "comment"
>   },
>   "to": "FCM token"
> }
> ```



From:
```
[
        "notification" => [
          "title" => $title,
          "body" => $message,
          "click_action" => "FLUTTER_NOTIFICATION_CLICK",
],
```

To: 

```
"notification" => [
          "title" => $title,
          "body" => $message,
          // "click_action" => "FLUTTER_NOTIFICATION_CLICK",
        ],
        "priority": "high",

```

This was preventing handlers to get notify, and after changing them, complete example from repo started working!

Hope this helps any newcomer !

**Comment by santiotin** [comment] 2021-03-09 15:19
I have the same issue using firebase_messaging: 9.0.0. When sending a notification I see through logs that is received (firebase messaging logs show: broadcast received for message). But the functions onMessage(foreground) or onMessageOpenedApp(background) are never executed. Someone knows why?

**Comment by ituitis-gulbahara17** [comment] 2021-03-15 15:53
I have the similar issue when upgrading iOS app.

I was using **firebase_messaging: ^6.0.12** and i upgraded to **firebase_messaging: ^9.0.0**. In version 6.0.12 there is no foreground alert feature. I built foreground alert show with firebase local notification. Then I upgraded to 9.0.0 and added:

>  await FirebaseMessaging.instance
        .setForegroundNotificationPresentationOptions(
      alert: false,
      badge: false,
      sound: false,
    );

There is no problem when I first installed or built to iOS device. But when I upgraded older version to last test version of my app in TestFlight **setForegroundNotificationPresentationOptions** is not working. Alert is showing twice. First firebase messaging default alert, second alert from my functions with firebase local notification. Any solution for this case?

**Comment by lucasalmeida-egsys** [comment] 2021-03-24 17:17
> I have the same issue using firebase_messaging: 9.0.0. When sending a notification I see through logs that is received (firebase messaging logs show: broadcast received for message). But the functions onMessage(foreground) or onMessageOpenedApp(background) are never executed. Someone knows why?

Same issue here.

**Comment by santiotin** [comment] 2021-03-24 17:22
@lucasalmeida-egsys I resolved my issue navigating to RemoteMessage.fromMap() and changing contentAvailable: map['contentAvailable'], to contentAvailable: map['contentAvailable']??false and mutableContent: map['mutableContent'], to mutableContent: map['mutableContent']??false

**Comment by lucasalmeida-egsys** [comment] 2021-03-24 17:29
> @lucasalmeida-egsys I resolved my issue navigating to RemoteMessage.fromMap() and changing contentAvailable: map['contentAvailable'], to contentAvailable: map['contentAvailable']??false and mutableContent: map['mutableContent'], to mutableContent: map['mutableContent']??false

These changes have already been made here but still not working...

**Comment by lucasalmeida-egsys** [comment] 2021-03-24 18:50
> @lucasalmeida-egsys I resolved my issue navigating to RemoteMessage.fromMap() and changing contentAvailable: map['contentAvailable'], to contentAvailable: map['contentAvailable']??false and mutableContent: map['mutableContent'], to mutableContent: map['mutableContent']??false

solved, thanks.

**Comment by juanektbb** [comment] 2021-04-08 13:40
In my case, we can get background notifications on IOS real devices. But it does not invoke **_firebaseMessagingBackgroundHandler** which I use to do some tasks when the app receive a background notification.
(Android devices work perfect)

```
Future<void> _firebaseMessagingBackgroundHandler(RemoteMessage message) async {
  print("Background Notification");
}

mixin PushNotification<T extends StatefulWidget> on State<T>, DioField {
  static final _messaging = FirebaseMessaging.instance;

  @override
  initState() {
    super.initState();
    registerUpPushNotification();
    _listenToPushNotifications();
  }

  registerUpPushNotification() {
    //REGISTER REQUIRED FOR IOS
    if (Platform.isIOS) {
      _messaging.requestPermission();
    }

    _messaging.getToken().then((value) {
      if (value == null) return;
      print('token $value');
    });
  }

  _listenToPushNotifications() {
    FirebaseMessaging.onBackgroundMessage(_firebaseMessagingBackgroundHandler);

    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      print("onMessage");
    });

    FirebaseMessaging.onMessageOpenedApp.listen((RemoteMessage message) {
      print('onMessageOpenedApp');
    });
  }
}
```

firebase_messaging 8.0.0-dev.12

**Comment by mario202k** [comment] 2021-04-27 22:47
"7.3.0 - [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '708349719378'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set."
Nobody have this when running on Xcode? Is it related to "onIosSettingsRegistered" that is deprecated?

**Comment by mario202k** [comment] 2021-04-28 13:53
> "7.3.0 - [Firebase/Messaging][I-FCM002022] APNS device token not set before retrieving FCM Token for Sender ID '708349719378'. Notifications to this FCM Token will not be delivered over APNS.Be sure to re-retrieve the FCM token once the APNS device token is set."
> Nobody have this when running on Xcode? Is it related to "onIosSettingsRegistered" that is deprecated?

Sorry a was forgetting await. Everything works on both side.

**Comment by russellwheatley** [comment] 2021-12-22 12:21
Hi guys, I'm going to close this issue for now as we're on `firebase_messaging` version `11.2.4` now. Please create a new issue if you feel there is a problem with the latest version. Thank you.

**Closed by russellwheatley** 2021-12-22 12:21 UTC
Labels: type: bug, plugin: messaging, platform: ios
