### ISSUE TITLE
[Firestore] Crash (NPE) when updating a document

### ISSUE THREAD

**Issue by wujek-srujek** [FirebaseExtended/flutterfire#2666] opened 2020-05-29 20:34 UTC
**Describe the bug**
The app crashed when I updated a Firestore document. Below the stack trace from Crashlytics:

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:451)
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:433)
       at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.0:1025)
       at com.google.firebase.firestore.Query$$Lambda$3.onEvent(:6)
       at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.0:42)
       at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(:6)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:7356)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

**Flutter doctor**

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.1, on Mac OS X 10.15.5 19F96, locale en-DE)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.45.1)
[✓] Connected device (1 available)
```

**Comment by TahaTesser** [comment] 2020-06-02 13:05
Hi @wujek-srujek 
Is this a published app? Can you reproduce using example code?
Can you please provide your `flutter doctor -v`, your `flutter run --verbose` and a minimal complete reproducible code sample.
Thank you

**Comment by wujek-srujek** [comment] 2020-06-02 20:32
Hi.
1. This is not a published app, this is something I wrote for my household and use very often, but is not public.
2. I can't provide a relevant `flutter doctor -v` any more as I have since upgraded to 1.17.2, the crash was on 1.17.1. Unless you are Ok with that.
3. I can't give you a sample, I couldn't reproduce the crash if I wanted to, it was completely random while I was using the app as I always do. It's the first crash after about a month of pretty much daily usage on 2-3 phones (Android and iOS).

What I know is that at the moment of the crash network was very spotty and very bad, and I think the app might have been coming from the background, but not sure.

I know it's not very useful, I was hoping the crash stack trace can help you somehow. The version of `cloud_firestore` is `0.13.5` if it's of any value.

**Comment by TahaTesser** [comment] 2020-06-03 09:07
Hi @wujek-srujek 
Just tried official [example](https://pub.dev/packages/cloud_firestore#-example-tab-) using `cloud_firestore: ^0.13.5` and  also latest `cloud_firestore: ^0.13.6` and i had no issue

Since you can't provide reproducible and no longer experiencing this issue, i feel safe to close the issue

given your last message I feel safe to close this issue, if you disagree please write in the comments and I will reopen it. 
Thank you"

**Closed** 2020-06-03 09:07 UTC
Labels: blocked: customer-response
