### ISSUE TITLE
🐛 [firebase_storage]  Object not found exception

### ISSUE THREAD

**Issue by JamiuJimoh** [FirebaseExtended/flutterfire#7718] opened 2021-12-27 19:59 UTC
Update on issue [#4908](https://github.com/FirebaseExtended/flutterfire/issues/4908). It says that the issue is fixed but the bug still persists.

**Comment by darshankawar** [comment] 2021-12-28 12:25
@JamiuJimoh 
Although you linked the issue and was fixed long time back, we would need your `flutter doctor -v`, a [complete minimal reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) that shows the exception.

**Comment by JamiuJimoh** [comment] 2021-12-29 14:51
##  **Bug report**
I'm storing files on firebase using the firebase_storage package. I get the URLs and store and store them in Firestore. Now, when the user taps a  button to delete the URLs from Firestore, before deleting URLs, I'm trying to delete the corresponding files from Firestore storage using those URLs.

### Steps to reproduce the error
- Upload a file to firebase storage.
- Get the dowloadUrl and store it in Firestore.
- Delete the file from firebase_storage using `FirebaseStorage.instance.refFromURL(url).delete();` whilst deleting the URL from Firestore.
- This is where the storage exception is thrown.

### Expected behaviour
It should delete the file and the URL from both the storage and Firestore respectively, **''without crashes"**. Emphasis on the "without crashes"" because it does delete the file and the URL but it crashes and gives the storage exception.

<hr></hr>

### Additional context
**_Crash logs_**
```
E/StorageException(24578): StorageException has occurred.
E/StorageException(24578): Object does not exist at location.
E/StorageException(24578):  Code: -13010 HttpResult: 404
E/StorageException(24578): {  "error": {    "code": 404,    "message": "Not Found."  }}
E/StorageException(24578): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found."  }}
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:445)
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:462)
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:453)
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:289)
E/StorageException(24578): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:76)
E/StorageException(24578): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:68)
E/StorageException(24578): 	at com.google.firebase.storage.DeleteStorageTask.run(DeleteStorageTask.java:59)
E/StorageException(24578): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException(24578): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException(24578): 	at java.lang.Thread.run(Thread.java:923)
E/flutter (24578): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_storage/object-not-found] No object exists at the desired reference.
```

## Flutter doctor
<details>
<summary>Click to expand!</summary>

```
[✓] Flutter (Channel stable, 2.8.1, on Microsoft Windows [Version 10.0.22468.1000], locale en-NG)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Chrome - develop for the web
[✓] Visual Studio - develop for Windows (Visual Studio Community 2019 16.11.1)
[✓] Android Studio (version 4.1)
[✓] Android Studio (version 4.2)
[✓] VS Code (version 1.63.2)
[✓] Connected device (3 available)
```
</details>

## Flutter dependencies
<details>
<summary>Click to expand!</summary>

```
dependencies:
  cloud_firestore: ^2.3.0
  cupertino_icons: ^1.0.2
  file_picker: ^4.3.0
  firebase_auth: ^2.0.0
  firebase_core: ^1.3.0
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.4
  image_picker: ^0.8.3+3
  intl: ^0.17.0
  provider: ^5.0.0
  rxdart: ^0.27.1
  syncfusion_flutter_pdfviewer: ^19.4.38-beta
  uuid: ^3.0.5

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
```
</details>

**Comment by darshankawar** [comment] 2021-12-30 08:08
@JamiuJimoh 
Thanks for the details. While downloading the url, can you try to use whole path in reference something like `storage.ref('Directory/$filename').getDownloadURL();` and see if it helps ?

**Comment by JamiuJimoh** [comment] 2021-12-30 14:29
Thanks for the swift reply. This is how I'm getting the URL
```dart
Future<String> setFile({
  required String path,
  required String fileID,
  required File file,
}) async {
  final documentReference = FirebaseStorage.instance
      .ref()
      .child(path)
      .child(fileID)
      .child(file.path);

  await documentReference.putFile(file);
  return documentReference.getDownloadURL();
}
```

**Comment by darshankawar** [comment] 2021-12-31 08:02
@JamiuJimoh 
Check [this](https://github.com/FirebaseExtended/flutterfire/issues/5431#issuecomment-810032538) solution and see if it helps.

**Comment by JamiuJimoh** [comment] 2021-12-31 13:39
### **I found out what's triggering the error.**
I have two collections in Firestore. One called Materials and the other called PDFs. A Material stores informations like the materialID, datePosted, e.t.c. In the app, when the user creates a material, they can choose one or multiple PDF files and the files selected will all have the same material ID.  <p>In the PDFs collection, a PDF stores information like the pdfID, **materialID**, and the url gotten from the storage. </p>
So I display the PDFs using the `.where()` method, where the PDF.materialID isEqual to the given materialID.
When the user decides to delete a material, 

1. I delete all PDF files corresponding to the material from the storage first,
2. then I delete the PDF data from the PDFs collections
3. lastly, I delete the material from the materials collection.

The problem isn't from 2 and 3. The problem is from number 1. This is how I'm deleting the PDF files from the storage.

```dart
/// Reading through the PDFs collection where the materialID isEqual to the
/// PDF.materialID.
pdfsStream(materialID).listen((pdfs) async {
  // getting each 'pdf' in the returned list from the PDFs collection satisfying the above clause.
  for (var pdf in pdfs) {
    //1. deleting pdf from the storage.
    await deletePDFStorage(pdf.url);
    //2. deleting pdf from firestore.
    await deletePDFFirestore(pdf.pdfID);
  }
}
//3. Finally deleting the material from Materials collection.
await deleteMaterial(materialID);

/// THE FUNCTIONS


Future<void> deletePDFFirestore( String pdfID) async {
// no problem here
  await FirebaseFirestore.instance.doc('/PDFs/$pdfID').delete();
}

Future<void>  deletePDFStorage( String url) async {
  final ref = FirebaseStorage.instance.refFromURL(url);
//  problem here
  await ref.delete();
}
```

**This where it get's interesting**
Suppose I choose to select and save just one PDF file for a Material, I can delete the material and It works as expected.
But when I decide to select multiple PDF files for a material, I can save it, no problem. The error only occurs when I try to delete. I debugged and found out why.
## Apparently, the `deletePDFStorage` which calls `ref.delete()` gets called multiple times for the same PDF file. So, for a file that has already been deleted, it tries to delete it again but it can't find it. Hence, this error:

<details>
  <summary>Click to expand</summary>

```
E/StorageException(24578): StorageException has occurred.
E/StorageException(24578): Object does not exist at location.
E/StorageException(24578):  Code: -13010 HttpResult: 404
E/StorageException(24578): {  "error": {    "code": 404,    "message": "Not Found."  }}
E/StorageException(24578): java.io.IOException: {  "error": {    "code": 404,    "message": "Not Found."  }}
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.parseResponse(NetworkRequest.java:445)
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.parseErrorResponse(NetworkRequest.java:462)
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.processResponseStream(NetworkRequest.java:453)
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:272)
E/StorageException(24578): 	at com.google.firebase.storage.network.NetworkRequest.performRequest(NetworkRequest.java:289)
E/StorageException(24578): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:76)
E/StorageException(24578): 	at com.google.firebase.storage.internal.ExponentialBackoffSender.sendWithExponentialBackoff(ExponentialBackoffSender.java:68)
E/StorageException(24578): 	at com.google.firebase.storage.DeleteStorageTask.run(DeleteStorageTask.java:59)
E/StorageException(24578): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
E/StorageException(24578): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
E/StorageException(24578): 	at java.lang.Thread.run(Thread.java:923)
E/flutter (24578): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: [firebase_storage/object-not-found] No object exists at the desired reference.
```
</details>

I haven't figured how to solve the issue yet. I'd appereciate any solutions. Thank you.

**Comment by darshankawar** [comment] 2022-01-04 08:06
@JamiuJimoh 
Thanks for digging in and identifying the root cause. I think this is related to the code implementation as it's deleting properly but getting called again, so there need to be a check in your code to confirm if the document is deleted and if so don't run the method again.
With this, I think you can ask for the solution for such case on support platforms like StackOverflow.
Closing from here. If you disagree, write in comments and I'll reopen it.

**Closed by darshankawar** 2022-01-04 08:06 UTC
Labels: type: bug, Needs Attention, in triage
