### ISSUE TITLE
[Firestore] Cannot read property 'app' of undefined

### ISSUE THREAD

**Issue by thecoffeehog** [FirebaseExtended/flutterfire#2680] opened 2020-06-01 11:27 UTC
Getting this error while running the app on Flutter Web (Chrome) while iOS runs successfully.

**Error Log**

```
Launching lib/main.dart on Chrome in debug mode...
Syncing files to device Chrome...
Debug service listening on ws://127.0.0.1:65439/F45UR92WpHA=
Debug service listening on ws://127.0.0.1:65439/F45UR92WpHA=
TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (http://localhost:65394/packages/firebase/src/top_level.dart.lib.js:72:56)
    at new cloud_firestore_web.FirestoreWeb.new (http://localhost:65394/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:793:57)
    at Function.registerWith (http://localhost:65394/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:738:71)
    at Object.registerPlugins (http://localhost:65394/packages/dashboard/generated_plugin_registrant.dart.lib.js:15:38)
    at main$ (http://localhost:65394/web_entrypoint.dart.lib.js:15:35)
    at main$.next (<anonymous>)
    at runBody (http://localhost:65394/dart_sdk.js:35674:34)
    at Object._async [as async] (http://localhost:65394/dart_sdk.js:35702:7)
    at main$ (http://localhost:65394/web_entrypoint.dart.lib.js:14:18)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:65394/dwds/src/injected/client.js:8343:15)
    at http://localhost:65394/dwds/src/injected/client.js:22335:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:65394/dwds/src/injected/client.js:3636:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:65394/dwds/src/injected/client.js:10848:12)
    at Object._asyncStartSync (http://localhost:65394/dwds/src/injected/client.js:3600:20)
    at main__closure1.$call$body$main__closure (http://localhost:65394/dwds/src/injected/client.js:22347:16)
    at main__closure1.call$1 (http://localhost:65394/dwds/src/injected/client.js:22279:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:65394/dwds/src/injected/client.js:3958:16)
    at _CustomZone.runUnary$2$2 (http://localhost:65394/dwds/src/injected/client.js:12164:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:65394/dwds/src/injected/client.js:12092:14)
    at _ControllerSubscription._sendData$1 (http://localhost:65394/dwds/src/injected/client.js:11642:19)
    at _DelayedData.perform$1 (http://localhost:65394/dwds/src/injected/client.js:11796:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:65394/dwds/src/injected/client.js:11845:14)
    at Object._microtaskLoop (http://localhost:65394/dwds/src/injected/client.js:3801:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:65394/dwds/src/injected/client.js:3807:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:65394/dwds/src/injected/client.js:10720:9)
    at invokeClosure (http://localhost:65394/dwds/src/injected/client.js:1172:26)
    at MutationObserver.<anonymous> (http://localhost:65394/dwds/src/injected/client.js:1191:18)TypeError: Cannot read property 'app' of undefined
    at Object.app$ [as app] (http://localhost:65394/packages/firebase/src/top_level.dart.lib.js:72:56)
    at new cloud_firestore_web.FirestoreWeb.new (http://localhost:65394/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:793:57)
    at Function.registerWith (http://localhost:65394/packages/cloud_firestore_web/src/write_batch_web.dart.lib.js:738:71)
    at Object.registerPlugins (http://localhost:65394/packages/dashboard/generated_plugin_registrant.dart.lib.js:15:38)
    at main$ (http://localhost:65394/web_entrypoint.dart.lib.js:15:35)
    at main$.next (<anonymous>)
    at runBody (http://localhost:65394/dart_sdk.js:35674:34)
    at Object._async [as async] (http://localhost:65394/dart_sdk.js:35702:7)
    at main$ (http://localhost:65394/web_entrypoint.dart.lib.js:14:18)
    at <anonymous>:1:8
    at Object.runMain (http://localhost:65394/dwds/src/injected/client.js:8343:15)
    at http://localhost:65394/dwds/src/injected/client.js:22335:19
    at _wrapJsFunctionForAsync_closure.$protected (http://localhost:65394/dwds/src/injected/client.js:3636:15)
    at _wrapJsFunctionForAsync_closure.call$2 (http://localhost:65394/dwds/src/injected/client.js:10848:12)
    at Object._asyncStartSync (http://localhost:65394/dwds/src/injected/client.js:3600:20)
    at main__closure1.$call$body$main__closure (http://localhost:65394/dwds/src/injected/client.js:22347:16)
    at main__closure1.call$1 (http://localhost:65394/dwds/src/injected/client.js:22279:19)
    at StaticClosure._rootRunUnary [as call$2$5] (http://localhost:65394/dwds/src/injected/client.js:3958:16)
    at _CustomZone.runUnary$2$2 (http://localhost:65394/dwds/src/injected/client.js:12164:39)
    at _CustomZone.runUnaryGuarded$1$2 (http://localhost:65394/dwds/src/injected/client.js:12092:14)
    at _ControllerSubscription._sendData$1 (http://localhost:65394/dwds/src/injected/client.js:11642:19)
    at _DelayedData.perform$1 (http://localhost:65394/dwds/src/injected/client.js:11796:59)
    at _PendingEvents_schedule_closure.call$0 (http://localhost:65394/dwds/src/injected/client.js:11845:14)
    at Object._microtaskLoop (http://localhost:65394/dwds/src/injected/client.js:3801:21)
    at StaticClosure._startMicrotaskLoop (http://localhost:65394/dwds/src/injected/client.js:3807:11)
    at _AsyncRun__initializeScheduleImmediate_internalCallback.call$1 (http://localhost:65394/dwds/src/injected/client.js:10720:9)
    at invokeClosure (http://localhost:65394/dwds/src/injected/client.js:1172:26)
    at MutationObserver.<anonymous> (http://localhost:65394/dwds/src/injected/client.js:1191:18)
```

**Versions of plugins**

```
  cloud_firestore: ^0.13.6
  firebase_core: ^0.4.5
  firebase_analytics: ^5.0.14
  firebase_auth: ^0.16.1
```
**Flutter Doctor Output**

```
[✓] Flutter (Channel beta, 1.18.0-11.1.pre, on Mac OS X 10.15.5 19F96, locale en-IN)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.45.1)
[✓] Connected device (3 available)

• No issues found!

```

**Comment by TahaTesser** [comment] 2020-06-02 13:58
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1688

**Closed by TahaTesser** 2020-06-02 13:58 UTC
