### ISSUE TITLE
[cloud_firestore] Firestore Streams cause crash on app relaunch

### ISSUE THREAD

**Issue by Adeering** [FirebaseExtended/flutterfire#2529] opened 2020-05-10 19:03 UTC
**Describe the bug**
When listening to a stream with the StreamBuilder for cloud_firestore everything works fine on the initial launch, but if I use the android back button to exit the app and go back into the app, then do anything that modifies data associated with that stream the app will crash.  Here is my stream code:

```
@override
  Widget build(BuildContext context) {
    return StreamBuilder<List<Message>>(
      stream: widget.firestore
          .collection('chats')
          .document(widget.chatId)
          .collection('messages')
          .orderBy('timestamp', descending: true)
          .limit(20)
          .snapshots()
          .map((list) =>
              list.documents.map((doc) => Message.fromFirestore(doc)).toList()),
      builder: (context, snapshot) {
        if (!snapshot.hasData) {
          return LoadingPage();
        }
        List<Message> messageStream = snapshot.data;
        return Expanded(
          child: ListView.builder(
            reverse: true,
            padding: EdgeInsets.symmetric(horizontal: 10.0, vertical: 20.0),
            controller: listScrollController,
            itemCount: messageStream.length,
            itemBuilder: (context, index) {
              return Text(messageStream[index].message);
            },
          ),
        );
      },
    );
  }
```
And this is my code to send a message:
```
sendMessage({
    String sender,
    String receiver,
    String message,
    bool isPlayer,
    String dmName,
    String playerName,
    String dmImage,
    String playerImage,
  }) async {
    String sender1 = sender.compareTo(receiver) < 0 ? sender : receiver;
    String sender2 = sender.compareTo(receiver) > 0 ? sender : receiver;
    String chatName = '${sender1}_$sender2';
    await _firestore.collection(CHAT_COLLECTION).document(chatName).setData({
      'dm': isPlayer ? receiver : sender,
      'dm_image': dmImage,
      'dm_name': dmName,
      'player': isPlayer ? sender : receiver,
      'player_image': playerImage,
      'player_name': playerName,
      'dm_hidden': false,
      'player_hidden': false,
      'timestamp': FieldValue.serverTimestamp(),
      'dm_seen': isPlayer ? false : true,
      'player_seen': isPlayer ? true : false,
      'last_message': {
        'message': message,
        'sender_name': isPlayer ? playerName : dmName,
        'sender_id': sender,
        'receiver_id': receiver,
      },
    }, merge: true);
    await _firestore
        .collection(CHAT_COLLECTION)
        .document(chatName)
        .collection(MESSAGES_COLLECTION)
        .add({
      'sender_id': sender,
      'receiver_id': receiver,
      'sender_name': isPlayer ? playerName : dmName,
      'message': message,
      'timestamp': FieldValue.serverTimestamp(),
    });
  }
```
And this is the error I get:
```
E/AndroidRuntime(24029): java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
E/AndroidRuntime(24029): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:451)
E/AndroidRuntime(24029): 	at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$EventObserver.onEvent(CloudFirestorePlugin.java:433)
E/AndroidRuntime(24029): 	at com.google.firebase.firestore.Query.lambda$addSnapshotListenerInternal$2(com.google.firebase:firebase-firestore@@21.3.0:1025)
E/AndroidRuntime(24029): 	at com.google.firebase.firestore.Query$$Lambda$3.onEvent(Unknown Source:6)
E/AndroidRuntime(24029): 	at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(com.google.firebase:firebase-firestore@@21.3.0:42)
E/AndroidRuntime(24029): 	at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(Unknown Source:6)
E/AndroidRuntime(24029): 	at android.os.Handler.handleCallback(Handler.java:883)
E/AndroidRuntime(24029): 	at android.os.Handler.dispatchMessage(Handler.java:100)
E/AndroidRuntime(24029): 	at com.google.android.gms.internal.tasks.zzb.dispatchMessage(com.google.android.gms:play-services-tasks@@17.0.2:6)
E/AndroidRuntime(24029): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(24029): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/AndroidRuntime(24029): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24029): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/AndroidRuntime(24029): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```
**To Reproduce**
1. Launch App and go to the chat screen (stream initiated)
2. Back out of app with back button on Android (dont have iphone to test on iOS)
3. Reopen app and go to chat screen again (stream re-initiated)
4. Send a message and the app crashes with the above error

**Expected behavior**
Not crash and update the message stream

**Additional context**
In my code im updating both a document and a sub collection.  The chats document  gets updated, but the message doesnt get added.  I have also done steps 1-2 in the reproduce, but instead of sending a message through the app, i have manually added a new message in the firestore dashboard online and it still crashes.  It is something to do with the cloud_firestore querysnapshot update handler.

**Comment by agreensh** [comment] 2020-05-12 15:22
Same crash using firebase messaging when a message arrives and the app is BACKGROUNDED.

`  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  firebase_storage: ^3.1.5
  firebase_messaging: ^6.0.15`

**Comment by TahaTesser** [comment] 2020-05-13 12:37
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2517

**Closed by TahaTesser** 2020-05-13 12:37 UTC
