### ISSUE TITLE
🐛 [Firebase_Performance] iOS crashes on start after updating to 0.8.0

### ISSUE THREAD

**Issue by thassio-vinicius** [FirebaseExtended/flutterfire#7611] opened 2021-12-15 15:43 UTC
## Bug report

After updating to the latest 0.8.0 version, the app simply crashes right after it finishes compiling, with the following error message: 

```
-[NSNull longValue]: unrecognized selector sent to instance 0x1dc3b8558
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull longValue]: unrecognized selector sent to instance 0x1dc3b8558'
*** First throw call stack:
(0x1814e904c 0x199b5df54 0x1815c6014 0x18147e474 0x18147d5b0 0x104c10754 0x104c104a8 0x104c101c0 0x10b72164c 0x10b20eac4 0x10b214708 0x10b5f93c0 0x10b505510 0x10b50bfc0 0x1814fe268 0x181482c40 0x18147d43c 0x18145bc58 0x18146f3b8 0x19cdff38c 0x183e0f6a8 0x183b8e7f4 0x104b53bb4 0x104f99a24)
libc++abi: terminating with uncaught exception of type NSException
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGABRT
    frame #0: 0x00000001b848e964 libsystem_kernel.dylib`__pthread_kill + 8
libsystem_kernel.dylib`__pthread_kill:
->  0x1b848e964 <+8>:  b.lo   0x1b848e984               ; <+40>
    0x1b848e968 <+12>: pacibsp 
    0x1b848e96c <+16>: stp    x29, x30, [sp, #-0x10]!
    0x1b848e970 <+20>: mov    x29, sp
Target 0: (Runner) stopped.
Lost connection to device.
```

This only happens on iOS and starting from version 0.8.0. I can confirm that Android is working fine and downgrading to 0.7.1 fixes it for iOS. Also, versions 0.8.0+1 and 0.8.0+2 don't work either.

### Steps to reproduce

Simply update from 0.7.1 to 0.8.0 and try compiling to iOS

## Additional context

The only custom tracking implementation I'm using from the plugin is `FirebasePerformance.instance.newHttpMetric`

---

### Flutter doctor

<details><summary>Click To Expand</summary>

```
thassio@Thassios-MacBook-Pro gruups_app % flutter doctor -v
[✓] Flutter (Channel dev, 2.6.0-11.0.pre, on macOS 12.0.1 21A559 darwin-arm, locale en-GB)
    • Flutter version 2.6.0-11.0.pre at /Users/thassio/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4b330ddbed (3 months ago), 2021-09-16 17:29:58 -0700
    • Engine revision 5b81c6d615
    • Dart version 2.15.0 (build 2.15.0-116.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/thassio/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • ANDROID_HOME = /Users/thassio/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2020.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.10+0-b96-7281165)

[✓] VS Code (version 1.63.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[✓] Connected device (3 available)
    • Pixel 4a (mobile)          • 192.168.0.43:5555         • android-arm64  • Android 12 (API 31)
    • iPhone de Thassio (mobile) • 00008101-001602C81A12001E • ios            • iOS 15.1.1 19B81
    • Chrome (web)               • chrome                    • web-javascript • Google Chrome 96.0.4664.110
    ! Error: iPhone de Thassio is busy: Making the device ready for development. Xcode will continue when iPhone de Thassio is finished. (code -10)

• No issues found!
```

</details>

---

### Flutter dependencies

<details><summary>Click To Expand</summary>

```
thassio@Thassios-MacBook-Pro gruups_app % flutter pub deps -- --style=compact
Dart SDK 2.15.0-116.0.dev
Flutter SDK 2.6.0-11.0.pre
gruups_app 1.5.6+293

dependencies:
- adonis_websok 1.0.2 [meta websok]
- agora_rtc_engine 4.0.7 [flutter flutter_web_plugins json_annotation]
- app_settings 4.1.1 [flutter]
- audioplayers 0.20.1 [uuid path_provider http flutter flutter_web_plugins]
- auto_size_text 3.0.0 [flutter]
- cached_network_image 3.1.0+1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- camera 0.9.4+4 [camera_platform_interface camera_web flutter pedantic quiver flutter_plugin_android_lifecycle]
- collection 1.15.0
- connectivity 3.0.6 [flutter meta connectivity_platform_interface connectivity_macos connectivity_for_web]
- country_code_picker 2.0.2 [flutter modal_bottom_sheet collection universal_platform]
- cupertino_icons 1.0.4
- device_info 2.0.3 [flutter device_info_platform_interface]
- dio 4.0.3 [http_parser path]
- emoji_picker 0.1.0 [flutter shared_preferences]
- expandable 5.0.1 [flutter]
- firebase_analytics 8.3.4 [firebase_analytics_platform_interface firebase_analytics_web firebase_core flutter meta]
- firebase_core 1.10.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_dynamic_links 3.0.1 [firebase_core flutter]
- firebase_messaging 11.1.0 [firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web flutter meta]
- firebase_performance 0.7.1+5 [firebase_core firebase_core_platform_interface firebase_performance_platform_interface firebase_performance_web flutter]
- firebase_remote_config 0.11.0+2 [firebase_core firebase_core_platform_interface firebase_remote_config_platform_interface flutter]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_cupertino_localizations 1.0.1 [flutter flutter_localizations]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_markdown 0.6.8 [flutter markdown meta path]
- flutter_mobx 2.0.2 [flutter mobx]
- flutter_statusbarcolor_ns 0.4.0 [flutter]
- flutter_svg 0.23.0+1 [flutter meta path_drawing vector_math xml]
- font_awesome_flutter 8.8.1 [flutter]
- get_it 7.2.0 [async collection]
- giphy_picker 2.0.0 [flutter http]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- i18n_extension 4.1.3 [sprintf args analyzer gettext_parser equatable intl flutter]
- image_picker 0.8.4+4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- jiffy 4.1.0 [intl]
- json_annotation 4.3.0 [meta]
- mobx 2.0.5 [meta]
- notification_permissions 0.6.1 [flutter]
- package_info 2.0.2 [flutter]
- path_provider 2.0.7 [flutter path_provider_android path_provider_ios path_provider_linux path_provider_macos path_provider_platform_interface path_provider_windows]
- permission_handler 8.3.0 [flutter meta permission_handler_platform_interface]
- photo_view 0.13.0 [flutter]
- retrofit 2.2.0 [dio meta]
- scroll_to_index 2.1.0 [flutter]
- sentry 6.1.2 [http meta stack_trace uuid]
- share 2.0.4 [meta mime flutter]
- smooth_page_indicator 1.0.0+2 [flutter]
- store_redirect 2.0.0 [flutter]
- swipedetector 1.2.0 [flutter]
- transformer_page_view 0.1.6 [flutter]
- url_launcher 6.0.13 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]
- uuid 3.0.5 [crypto]
- video_player 2.2.6 [flutter meta video_player_platform_interface video_player_web html]
- wakelock 0.5.6 [flutter meta wakelock_macos wakelock_platform_interface wakelock_web wakelock_windows]
- worker_manager 4.2.4 [async collection]
- youtube_player_flutter 8.0.0 [flutter flutter_inappwebview]

dev dependencies:
- build_runner 2.1.5 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- effective_dart 1.3.2
- hive_generator 1.1.1 [build source_gen hive analyzer source_helper]
- json_serializable 6.0.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- mobx_codegen 2.0.4 [analyzer build build_resolvers meta mobx path source_gen]
- retrofit_generator 2.2.0 [dio source_gen built_collection code_builder tuple retrofit analyzer dart_style build]

dependency overrides:
- intl 0.17.0 [clock path]
- path 1.8.0

transitive dependencies:
- _fe_analyzer_shared 30.0.0 [meta]
- analyzer 2.7.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.1 [built_collection built_value http_multi_server logging path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.1
- built_value 8.1.3 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- camera_platform_interface 2.1.1 [cross_file flutter meta plugin_platform_interface stream_transform]
- camera_web 0.2.1+1 [camera_platform_interface flutter flutter_web_plugins stream_transform]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.5 [meta path]
- clock 1.1.0
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- connectivity_for_web 0.4.0+1 [connectivity_platform_interface flutter_web_plugins flutter]
- connectivity_macos 0.2.1+2 [flutter connectivity_platform_interface]
- connectivity_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- convert 3.0.1 [typed_data]
- cross_file 0.3.2 [flutter js meta]
- crypto 3.0.1 [collection typed_data]
- csslib 0.17.1 [source_span]
- dart_style 2.2.0 [analyzer args path pub_semver source_span]
- device_info_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- equatable 2.0.3 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase 9.0.2 [http http_parser js]
- firebase_analytics_platform_interface 2.0.1 [flutter meta]
- firebase_analytics_web 0.3.0+1 [firebase firebase_analytics_platform_interface flutter flutter_web_plugins meta]
- firebase_core_platform_interface 4.2.2 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.2 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_messaging_platform_interface 3.0.9 [firebase_core flutter meta plugin_platform_interface]
- firebase_messaging_web 2.1.0 [firebase_core firebase_core_web firebase_messaging_platform_interface flutter flutter_web_plugins js meta]
- firebase_performance_platform_interface 0.0.1+8 [firebase_core flutter plugin_platform_interface]
- firebase_performance_web 0.0.3+1 [firebase firebase_core firebase_core_web firebase_performance_platform_interface flutter flutter_web_plugins]
- firebase_remote_config_platform_interface 0.3.0+7 [firebase_core flutter meta plugin_platform_interface]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.3 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_inappwebview 5.3.2 [flutter]
- flutter_plugin_android_lifecycle 2.0.4 [flutter]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.2 [async path]
- gettext_parser 0.2.0
- glob 2.0.2 [async collection file path string_scanner]
- graphs 2.1.0 [collection]
- html 0.15.0 [csslib source_span]
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image_picker_for_web 2.1.4 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- logging 1.0.2
- markdown 4.0.0 [args charcode meta]
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- mime 1.0.1
- modal_bottom_sheet 2.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.2 [path]
- path_drawing 0.5.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- path_provider_android 2.0.7 [flutter path_provider_platform_interface]
- path_provider_ios 2.0.7 [flutter path_provider_platform_interface]
- path_provider_linux 2.1.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.3 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.4 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- permission_handler_platform_interface 3.7.0 [flutter meta plugin_platform_interface]
- petitparser 4.4.0 [meta]
- platform 3.0.2
- plugin_platform_interface 2.0.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.4 [file path platform]
- pub_semver 2.1.0 [collection meta]
- pubspec_parse 1.1.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1+1 [matcher]
- rxdart 0.27.2
- shared_preferences 0.5.7+3 [meta flutter shared_preferences_platform_interface shared_preferences_macos shared_preferences_web]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.1.1 [analyzer async build dart_style glob meta path source_span yaml]
- source_helper 1.3.0 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- sprintf 6.0.0
- sqflite 2.0.0+4 [flutter sqflite_common path]
- sqflite_common 2.0.1+1 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- tuple 2.0.0 [quiver]
- typed_data 1.3.0 [collection]
- universal_platform 1.0.0+1
- url_launcher_linux 2.0.2 [flutter]
- url_launcher_macos 2.0.2 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- vector_math 2.1.0
- video_player_platform_interface 4.2.0 [flutter flutter_test meta]
- video_player_web 2.0.4 [flutter flutter_web_plugins meta video_player_platform_interface]
- wakelock_macos 0.4.0 [flutter flutter_web_plugins wakelock_platform_interface]
- wakelock_platform_interface 0.3.0 [flutter meta]
- wakelock_web 0.4.0 [flutter flutter_web_plugins js wakelock_platform_interface]
- wakelock_windows 0.2.0 [flutter wakelock_platform_interface win32]
- watcher 1.0.1 [async path]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- websok 2.1.1 [meta web_socket_channel]
- win32 2.3.0 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by igorkurek** [comment] 2021-12-15 18:32
Most probably duplicate of https://github.com/FirebaseExtended/flutterfire/issues/7417

**Comment by darshankawar** [comment] 2021-12-16 10:02
@thassio-vinicius 
There's similar open issue describing your case, https://github.com/FirebaseExtended/flutterfire/issues/7523
Please follow-up in it for further updates.
Closing this as a duplicate.

**Closed by darshankawar** 2021-12-16 10:02 UTC
Labels: type: bug, Needs Attention, in triage
