### ISSUE TITLE
Exception when moving camera with Google Maps plugin

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#445] opened 2019-10-13 18:25 UTC
My application is creating a map and waiting for the `onMapCreated` callback before trying to move the camera e.g.

```dart
void onMapCreated(GoogleMapController controller) {
    controller.moveCamera(
      CameraUpdate.newLatLngBounds(
        LatLngBounds(
          southwest: LatLng(...),
          northeast: LatLng(...),
        ),
        mapPadding,
      ),
    );
  }
```

The majority of the time this works. However, maybe 1 times in 5, this fails with the following error message:
```
E/MethodChannel#plugins.flutter.io/google_maps_12: Failed to handle method call
    com.google.maps.api.android.lib6.common.apiexception.c: Error using newLatLngBounds(LatLngBounds, int): Map size can't be 0. Most likely, layout has not yet occured for the map view.  Either wait until layout has occurred or use newLatLngBounds(LatLngBounds, int, int, int) which allows you to specify the map's dimensions.
        at com.google.maps.api.android.lib6.common.n.b(:com.google.android.gms.dynamite_mapsdynamite@15090029@15.0.90 (020306-231259764):6)
...
```
```
[✓] Flutter (Channel beta, v1.1.8, on Mac OS X 10.14.3 18D42, locale en-GB)
    • Flutter version 1.1.8 at /Users/foobar/flutter
    • Framework revision 985ccb6d14 (5 weeks ago), 2019-01-08 13:45:55 -0800
    • Engine revision 7112b72cc2
    • Dart version 2.1.1 (build 2.1.1-dev.0.1 ec86471ccc)

[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/foobar/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 1.9.4
    • CocoaPods version 1.5.3

[✓] Android Studio (version 3.3)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 32.0.1
    • Dart plugin version 182.5124
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1248-b01)

[✓] VS Code (version 1.30.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 2.21.1

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

**Comment by kroikie** [comment] 2019-10-13 18:25
@irevans

The issue at https://github.com/flutter/flutter/issues/27936 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment] 2019-10-22 11:52
Hi @irevans
(and hello also to @lumogox  , @adrianmoneta and @d3xt3r2909 as well)
If are you still experiencing this issue 
with the latest version of Flutter and FlutterFire plugin
can you please provide your `flutter doctor -v`
and your and your `flutter run --verbose`/`flutter build --verbose` ?
Also, to better address the issue, would be helpful
if you could post a self contained app on github
or the steps to reproduce it.
Thank you

**Comment by iapicca** [comment] 2019-11-20 14:35
Without additional information, we are unfortunately not sure how to resolve this issue. We are therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the bug if you have any more information for us; we will reopen it right away!  
Thanks for your contribution.

Could everyone who still has this problem please file a new issue with the exact descriptions what happens, logs and the output of 'flutter doctor -v'  please.
All system setups can be slightly different so its always better to open new issues and reference related issues.

**Closed by iapicca** 2019-11-20 14:35 UTC
Labels: waiting for customer response

**Comment by hebaothman** [comment] 2019-11-30 17:52
By using `controller.animateCamera(CameraUpdate.newLatLngZoom(LatLng(lat, long), _zoom));`
instead of `controller.animateCamera(CameraUpdate.newCameraPosition());` i solved this issue for ios 13

**Comment by AAverin** [comment] 2020-02-27 17:14
Just following examples with Completer() on flutter_google_map pub page, I get this exception quite often.
All I do is animate map in `onMapCreated()`

```
class MapCmpnt extends HookWidget {
  Completer<GoogleMapController> _controller = Completer();

  @override
  Widget build(BuildContext context) {
    return StoreConnector(
      converter: (redux.Store<AppState> store) => _VM.fromStore(store),
      builder: (context, _VM vm) {
        if (!vm.ready) return Text('Loading...');
        return GoogleMap(
          mapType: MapType.hybrid,
          mapToolbarEnabled: true,
          markers: vm.getMarkers(),
          initialCameraPosition:
              CameraPosition(target: vm.allPhotosBounds().northeast, zoom: 10),
          onMapCreated: (GoogleMapController controller) {
            if (!_controller.isCompleted)
              _controller.complete(controller);
            if (_controller.isCompleted)
              controller.animateCamera(CameraUpdate.newLatLngBounds(vm.allPhotosBounds(), 0));
          },
        );
      },
    );
  }
}
```

**Comment by AAverin** [comment] 2020-02-27 17:16
On Android native this would mean that either map is not ready or GlobalLayout didn't yet kick in because you need to wait for both to start working with the map

**Comment by eyewritecode** [comment] 2020-08-06 10:03
If you end up here with this same error, here's how i fixed it. Note that the issue comes from trying to draw markers, polylines, etc... on the map before it has "fully loaded"

```dart
GoogleMap(
  onMapCreated: (mapCon) {
    WidgetsBinding.instance.addPostFrameCallback((_) {
         // your code that moves the camera
     });
  }
)
```
