### ISSUE TITLE
🐛 [firebase_analytics] dependency issues

### ISSUE THREAD

**Issue by erf** [FirebaseExtended/flutterfire#5271] opened 2021-03-08 23:03 UTC
## Bug report

**Describe the bug**

I get an dependency error with google_fonts 2.0.0 and firebase_analytics 7.1.0.

Because no versions of google_fonts match >2.0.0 <3.0.0 and google_fonts 2.0.0 depends on http ^0.13.0, google_fonts ^2.0.0 requires http ^0.13.0.
And because firebase >=5.0.3 <9.0.0 depends on http >=0.11.3 <0.13.0, google_fonts ^2.0.0 is incompatible with firebase >=5.0.3 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, google_fonts ^2.0.0 is incompatible with firebase_analytics >=7.1.0.
So, because xxx depends on both firebase_analytics ^7.1.0 and google_fonts ^2.0.0, version solving failed.
Running "flutter pub get" in xxx...
pub get failed (1; So, because xxx depends on both firebase_analytics ^7.1.0 and google_fonts ^2.0.0,
version solving failed.)

Is there a way to solve this, or could you improve the dependencies?

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, 2.1.0-10.0.pre, on macOS 11.2.1 20D74 darwin-arm, locale en-NO)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS
[✓] Android Studio (version 4.1)
[✓] IntelliJ IDEA Community Edition (version 2020.3.2)
[✓] Connected device (1 available)
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  firebase_core: ^1.0.0
  firebase_crashlytics: ^1.0.0
  firebase_analytics: ^7.1.0
  firebase_auth: ^1.0.0
  firebase_messaging: ^9.0.0
  cloud_firestore: ^1.0.0
  shared_preferences: ^2.0.3
  rxdart: ^0.26.0
  package_info: ^2.0.0
  google_fonts: ^2.0.0
  geolocator: ^7.0.1
  path_provider: ^2.0.1
  intl: ^0.17.0
  charts_flutter: ^0.9.0
  csv_localizations: ^1.0.0
  google_maps_flutter: ^2.0.1
  flutter_local_notifications: ^5.0.0-nullsafety.1
  flutter_native_timezone: ^1.0.10
  sign_in_with_apple: ^3.0.0
  google_sign_in: ^5.0.0
  app_review:
    git:
      url: git@github.com:erf/app_review.git
      ref: package_info
  purchases_flutter: ^3.0.0
  flutter_icons: ^1.1.0
  flutter_markdown: ^0.6.0
  toml_localizations: ^1.0.0
  flutter_riverpod: ^0.13.1
  flutter_mailer: ^1.0.1
  share: ^2.0.0
  json_annotation: ^4.0.0

dependency_overrides:
  intl: ^0.17.0
  #firebase: ^9.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0
  build_runner: ^1.11.5
  json_serializable: ^4.0.2

```

</details>

---

**Comment by erf** [comment] 2021-03-08 23:11
When i removed `google_fonts` i got a new dependency issue with `app_review`:

```
Because every version of app_review from git depends on http ^0.13.0-nullsafety.0 and firebase >=5.0.3 <9.0.0 depends on http >=0.11.3 <0.13.0, app_review from git is incompatible with firebase >=5.0.3 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, app_review from git is incompatible with firebase_analytics >=7.1.0.
So, because xxx depends on both firebase_analytics ^7.1.0 and app_review from git, version solving failed.
Running "flutter pub get" in xxx...
pub get failed (1; So, because xxx depends on both firebase_analytics ^7.1.0 and app_review from git,
version solving failed.)
```

**Comment by erf** [comment] 2021-03-08 23:12
And when i removed `app_review` i got an issue with `firebase_auth` ?? what is going on here..??

```
Because no versions of firebase_auth match >1.0.0 <2.0.0 and firebase_auth 1.0.0 depends on firebase_auth_web ^1.0.0, firebase_auth ^1.0.0 requires firebase_auth_web ^1.0.0.
And because no versions of firebase_auth_web match >1.0.0 <2.0.0, firebase_auth ^1.0.0 requires firebase_auth_web 1.0.0.
And because firebase_auth_web 1.0.0 depends on http_parser ^4.0.0 and firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0, firebase_auth ^1.0.0 is incompatible with firebase >=7.0.0 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, firebase_auth ^1.0.0 is incompatible with firebase_analytics >=7.1.0.
So, because cashplan depends on both firebase_analytics ^7.1.0 and firebase_auth ^1.0.0, version solving failed.
Running "flutter pub get" in cashplan...
pub get failed (1; So, because cashplan depends on both firebase_analytics ^7.1.0 and firebase_auth ^1.0.0,
version solving failed.)
```

**Comment by erf** [comment] 2021-03-08 23:13
When i removed `app_review` i got a new dependency issue with `firebase_auth`.. what is going on here??

```
Because no versions of firebase_auth match >1.0.0 <2.0.0 and firebase_auth 1.0.0 depends on firebase_auth_web ^1.0.0, firebase_auth ^1.0.0 requires firebase_auth_web ^1.0.0.
And because no versions of firebase_auth_web match >1.0.0 <2.0.0, firebase_auth ^1.0.0 requires firebase_auth_web 1.0.0.
And because firebase_auth_web 1.0.0 depends on http_parser ^4.0.0 and firebase >=7.0.0 <9.0.0 depends on http_parser ^3.0.0, firebase_auth ^1.0.0 is incompatible with firebase >=7.0.0 <9.0.0.
And because firebase_analytics >=7.1.0 depends on firebase_analytics_web ^0.2.0 which depends on firebase ^7.3.0, firebase_auth ^1.0.0 is incompatible with firebase_analytics >=7.1.0.
So, because xxx depends on both firebase_analytics ^7.1.0 and firebase_auth ^1.0.0, version solving failed.
Running "flutter pub get" in xxx...
pub get failed (1; So, because xxx depends on both firebase_analytics ^7.1.0 and firebase_auth ^1.0.0,
version solving failed.)
```

**Comment by erf** [comment] 2021-03-09 00:56
@sofferjacob  I tried to remove `google_fonts`, but as i mention in the other comments, there was other dependencies issues then. I also tried to override the dependency for http 0.13.0 as you mention, but that caused more problems. So i ended up disabling `firebase_analytics` for now as all the other dependencies worked fine then, and i'd like to have the latest packages.

**Comment by sofferjacob** [comment] 2021-03-09 01:32
@erf if dependency overriding is not working, it's a matter of waiting for an update to firebase_analytics or downgrading other packages in order to use analytics. Besides fixing it yourself and creating a pull request/using the forked repo instead of using the plugin from pub, there's not much else that can be done.

**Comment by erf** [comment] 2021-03-09 01:38
Yep. Will wait for the flutter team to solve this.

**Comment by markusaksli-nc** [comment] 2021-03-09 10:11
Hi @erf 
There is already an open issue to track the dependency problems with `firebase_analytics` https://github.com/FirebaseExtended/flutterfire/issues/5202.
Since this is caused by the same underlying `http` dependency in `firebase_analytics_web ^0.2.0` I'm going to close this as a duplicate.
Could you please follow up on the mentioned issue?
Thank you

**Closed by markusaksli-nc** 2021-03-09 10:11 UTC
Labels: Needs Attention, type: bug
