### ISSUE TITLE
[firebase_auth] User.uid has a value of user's email instead of UID suddenly

### ISSUE THREAD

**Issue by bakua** [FirebaseExtended/flutterfire#5385] opened 2021-03-18 06:48 UTC
Hello, we have an application with tens of thousands of MAU. We've got a support incident from user that the app broke up and upon looking into data closer, we have discovered that calling `FirebaseAuth.instance.currentUser.uid` returns his email instead of UID seen on Fireabse Auth web admin. This is bad in many ways, especially as it makes UID inconsistent in time. When looking on his data history, this user was getting proper UID until yesterday, then on a new app session launch and user refresh, it broke up.

Also, a global search across all our data found that there are more users this happened to.

**Comment by markusaksli-nc** [comment] 2021-03-18 09:52
Hi @bakua 
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Have you been able to reproduce this yourself? If so could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Thank you

**Comment by bakua** [comment] 2021-03-18 10:06
```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-arm, locale en-GB)
    • Flutter version 1.22.6 at /Users/jakubtakac/workspace/sdk/flutter
    • Framework revision 9b2d32b605 (8 weeks ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/jakubtakac/Library/Android/sdk
    • Platform android-30, build-tools 29.0.2
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.9.3

[!] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[!] Connected device
    ! No devices available
```

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
timesheet 30.0.3+0

dependencies:
- amplitude_flutter 2.2.2 [flutter]
- app_review 2.0.1 [http intl package_info url_launcher flutter]
- badges 1.1.3 [flutter]
- built_value 7.1.0 [built_collection collection fixnum quiver]
- cached_network_image 2.3.2+1 [flutter flutter_cache_manager octo_image]
- crypto 2.1.5 [collection convert typed_data]
- dio 3.0.10 [http_parser path]
- easy_debounce 1.0.2 [flutter]
- excel 1.1.5 [archive xml]
- firebase_analytics 6.0.2 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.1+2 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.0+1 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_crashlytics 0.2.1+1 [flutter stack_trace firebase_core firebase_core_platform_interface firebase_crashlytics_platform_interface]
- firebase_database 4.1.1 [flutter firebase_core]
- firebase_messaging 7.0.3 [meta flutter firebase_core]
- firebase_remote_config 0.4.0+2 [flutter firebase_core]
- fl_chart 0.11.1 [flutter path_drawing equatable]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 6.0.6 [flutter bloc provider]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- get_it 5.0.1 [async meta]
- google_api_availability 2.0.4 [flutter]
- google_sign_in 4.5.4 [google_sign_in_platform_interface flutter meta google_sign_in_web]
- hive 1.4.4+1 [meta crypto]
- hive_flutter 0.3.1 [flutter hive path_provider path]
- in_app_update 1.1.14 [flutter]
- intro_views_flutter 2.8.2 [flutter]
- jiffy 3.0.1 [intl]
- logger 0.9.4
- modal_bottom_sheet 0.2.2 [flutter]
- moor 3.3.1 [meta convert collection synchronized pedantic sqlite3]
- package_info 0.4.3 [flutter]
- parallax_image 0.3.1+1 [flutter]
- path_provider 1.6.18 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- provider 4.3.2+2 [flutter nested collection]
- purchases_flutter 1.4.3 [flutter]
- rxdart 0.24.1
- scrollable_positioned_list 0.1.8 [flutter meta]
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sign_in_with_apple 2.5.2 [meta flutter]
- sliding_up_panel 1.0.2 [flutter]
- sqlite3_flutter_libs 0.2.0
- time 1.3.0
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- uuid 2.2.2 [crypto convert]

dev dependencies:
- build_runner 1.10.3 [args async build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style glob graphs http_multi_server io js logging meta mime path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- built_value_generator 7.1.0 [analyzer build build_config built_collection built_value source_gen quiver]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- mockito 4.1.3 [analyzer build code_builder collection dart_style matcher meta source_gen test_api]
- moor_generator 3.3.1 [collection recase meta path json_annotation stream_transform args logging cli_util moor sqlparser analyzer analyzer_plugin source_span build build_resolvers build_config source_gen]
- pedantic 1.9.2 [meta]

dependency overrides:
- analyzer 0.40.4 [_fe_analyzer_shared args charcode cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- petitparser 3.0.0 [meta]
- xml 4.1.0 [collection convert meta petitparser]

transitive dependencies:
- _fe_analyzer_shared 11.0.0 [meta]
- analyzer_plugin 0.3.0 [analyzer charcode dart_style html meta path pub_semver]
- archive 2.0.13 [crypto args path]
- args 1.6.0
- async 2.5.0-nullsafety.1 [collection]
- bloc 6.0.3 [meta]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- build 1.5.0 [analyzer async convert crypto logging meta path glob]
- build_config 0.4.2 [checked_yaml json_annotation meta path pubspec_parse yaml]
- build_daemon 2.1.4 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 1.4.1 [analyzer build crypto graphs logging meta path package_config pool pub_semver]
- build_runner_core 6.0.3 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher yaml]
- built_collection 4.3.2 [collection quiver]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- checked_yaml 1.0.2 [json_annotation source_span yaml]
- cli_util 0.1.4 [path]
- clock 1.1.0-nullsafety.1
- code_builder 3.4.1 [built_collection built_value collection matcher meta]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- csslib 0.16.2 [source_span]
- dart_style 1.3.7 [analyzer args path source_span]
- equatable 1.2.5 [collection meta]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.1 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.1+1 [flutter flutter_web_plugins firebase meta http_parser intl firebase_core firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.0.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.0 [firebase firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_crashlytics_platform_interface 1.1.1 [flutter meta collection firebase_core plugin_platform_interface]
- fixnum 0.10.11
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 1.4.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- glob 1.2.0 [async collection node_io path pedantic string_scanner]
- google_sign_in_platform_interface 1.1.2 [flutter meta quiver]
- google_sign_in_web 0.9.2 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 0.2.0
- html 0.14.0+3 [csslib source_span]
- http 0.12.2 [http_parser path pedantic]
- http_multi_server 2.2.0 [async]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- intl 0.16.1 [path]
- io 0.3.4 [charcode meta path string_scanner]
- js 0.6.2
- json_annotation 3.1.0
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- node_interop 1.1.1 [js]
- node_io 1.1.1 [node_interop path]
- octo_image 0.3.0 [flutter flutter_blurhash]
- package_config 1.9.3 [path charcode]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pool 1.4.0 [async stack_trace]
- process 3.0.13 [file intl meta path platform]
- pub_semver 1.4.4 [collection]
- pubspec_parse 0.1.5 [checked_yaml json_annotation pub_semver yaml]
- quiver 2.1.3 [matcher meta]
- recase 3.0.0
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- shelf 0.7.9 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 0.2.3 [shelf web_socket_channel stream_channel]
- sky_engine 0.0.99
- source_gen 0.9.7+1 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite 1.3.1+1 [flutter sqflite_common path]
- sqflite_common 1.0.2+1 [synchronized path meta]
- sqlite3 0.1.6 [collection ffi meta]
- sqlparser 0.10.1 [meta collection source_span charcode]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 0.1.1+2 [json_annotation]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- vector_math 2.1.0-nullsafety.3
- watcher 0.9.7+15 [async path pedantic]
- web_socket_channel 1.1.0 [async crypto stream_channel]
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

**Comment by bakua** [comment] 2021-03-18 10:07
I'd like to point out that Firebase returns bad uid any number of times we ask. However, after the user signs out and back in the uid is back to normal.

**Comment by markusaksli-nc** [comment] 2021-03-18 10:20
Have you been able to create a minimal reproducible case for this?

Could you try switching to the latest stable release `firebase_auth: ^1.0.1`?

There have been some quite extensive changes since the version you are using.

**Comment by bakua** [comment] 2021-03-18 10:55
I am not able to reproduce on my own but I don't think it is related to the flutter plugin. Our app was initialy Android native only and was migrated to Flutter a year ago. I was able to find a user that has his email as his id since 2019 Android native times. Meaning the issue is probably related to Android code or Firebase backend.

I will update the app dependencies into the upcomming release. Thanks.

**Comment by markusaksli-nc** [comment] 2021-03-18 11:12
Well in that case I'm going to close the issue since there isn't anything for us to really fix here. This repository only wraps the upstream native Firebase SDKs so they could be used with Flutter. This is probably better suited to Firebase Support.

**Closed by markusaksli-nc** 2021-03-18 11:12 UTC
Labels: Needs Attention, impact: deprecated-version, type: bug
