### ISSUE TITLE
[Firestore.instance.settings(timestampsInSnapshotsEnabled: true)]=> Here "timestampsInSnapshotsEnabled" is working or not available

### ISSUE THREAD

**Issue by SaiVaraPrasad-3** [FirebaseExtended/flutterfire#2258] opened 2020-03-29 14:45 UTC
**Is your feature request related to a problem? Please describe.**
I am using the version cloud_firestore-0.13.4+2 , for the project and i want add the Firestore settings for that i was adding it to Main.dart in **void main() async{Firestore.instance.settings(timestampsInSnapshotsEnabled: true)} ** but it not accepted here, any solution...?

**Describe the solution you'd like**
Please provide solution, I was struck from morning... :{

**Additional context**
![bug](https://user-images.githubusercontent.com/59758830/77852015-f2a64600-71f9-11ea-83c9-4fdf266bd6ed.JPG)

**Comment by iapicca** [comment] 2020-04-03 13:11
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2259

**Closed by iapicca** 2020-04-03 13:11 UTC
Labels: enhancement
