### ISSUE TITLE
Firebase_Auth Example for Google Signin target Macos give MissingPluginException

### ISSUE THREAD

**Issue by rlfolden** [FirebaseExtended/flutterfire#6130] opened 2021-05-12 19:03 UTC
## Bug report

The example at: https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_auth/firebase_auth/example/lib
gives the following error when using the Google Login option:

**flutter: MissingPluginException(No implementation found for method init on channel plugins.flutter.io/google_sign_in)**

### Steps to reproduce

1. Create a project in Android Studio and create a Macos project using:
    flutter create --platforms=windows,macos,linux .
2. Create credentials using Firebase console, as described, and install plist in xcode
3. Build and run for macOS
4. Select Google Login

### Expected behavior

I expect the example to work.

### Sample project

I'm attaching the dart and  pubspec.yaml files
---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
doctor --verbose
[✓] Flutter (Channel master, 2.3.0-2.0.pre.147, on macOS 11.2.3 20D91 darwin-x64, locale en-US)
    • Flutter version 2.3.0-2.0.pre.147 at /Users/rudyfoldenMBP/Developer/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 7d46d43635 (2 hours ago), 2021-05-12 18:59:02 +0200
    • Engine revision f3847febb2
    • Dart version 2.14.0 (build 2.14.0-108.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/rudyfoldenMBP/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5, Build version 12E262
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.54.3)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.20.0

[✓] Connected device (1 available)
    • macOS (desktop) • macos • darwin-x64 • macOS 11.2.3 20D91 darwin-x64

• No issues found!
Process finished with exit code 0
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Changing current working directory to: /Users/rudyfoldenMBP/AndroidStudioProjects/firebase_authtest
Dart SDK 2.14.0-108.0.dev
Flutter SDK 2.3.0-2.0.pre.147
firebase_authtest 1.0.0+1

dependencies:
- cupertino_icons 1.0.3
- firebase_auth 1.1.4 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.1.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_signin_button 1.1.0 [flutter font_awesome_flutter]
- google_sign_in 5.0.2 [google_sign_in_platform_interface google_sign_in_web flutter meta]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.6.0 [meta collection]
- boolean_selector 2.1.0 [source_span string_scanner]
- characters 1.1.0
- charcode 1.2.0
- clock 1.1.0
- collection 1.15.0
- fake_async 1.2.0 [clock collection]
- firebase_auth_platform_interface 4.2.2 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.1.2 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.0.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 8.12.0 [flutter]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- js 0.6.3
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- path 1.8.0
- plugin_platform_interface 2.0.0 [meta]
- quiver 3.0.1 [matcher]
- sky_engine 0.0.99
- source_span 1.8.1 [collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.3.0 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0 [collection]
- vector_math 2.1.0
bash-3.2$ 

```

</details>

---

[Archive.zip](https://github.com/FirebaseExtended/flutterfire/files/6468525/Archive.zip)

**Comment by markusaksli-nc** [comment] 2021-05-13 15:50
Hi @rlfolden 
This is caused by google sign-in not being supported on MacOS
https://github.com/flutter/flutter/issues/46157
Closing due to there being an open issue to track this (and this isn't the repository for it).
Thank you

**Closed by markusaksli-nc** 2021-05-13 15:50 UTC
Labels: Needs Attention, in triage, type: bug
