### ISSUE TITLE
[<FIREBASE_DYNAMIC_LINKS>] Flutter web app does not work firebase_dynamic_links package

### ISSUE THREAD

**Issue by dirugec** [FirebaseExtended/flutterfire#2661] opened 2020-05-28 20:29 UTC
I compiled my flutter project for the web and hosted the application on a server, everything works fine but the flutter_dynamic_links package doesn't work for me, it doesn't capture the deep link

**Comment by TahaTesser** [comment] 2020-05-29 09:24
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2660

**Closed by TahaTesser** 2020-05-29 09:24 UTC
