### ISSUE TITLE
an error occurred while executing doInBackground

### ISSUE THREAD

**Issue by niypoo** [FirebaseExtended/flutterfire#2397] opened 2020-04-19 14:29 UTC
I'm using firestore with flutter and accidentally I try set and my app has crashed, I check the error I found that

```

    > E/AndroidRuntime(14541): java.lang.RuntimeException: An error occurred
    > while executing doInBackground() E/AndroidRuntime(14541): 	at
    > android.os.AsyncTask$4.done(AsyncTask.java:399)
    > E/AndroidRuntime(14541): 	at
    > java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
    > E/AndroidRuntime(14541): 	at
    > java.util.concurrent.FutureTask.setException(FutureTask.java:252)
    > E/AndroidRuntime(14541): 	at
    > java.util.concurrent.FutureTask.run(FutureTask.java:271)
    > E/AndroidRuntime(14541): 	at
    > android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
    > E/AndroidRuntime(14541): 	at
    > java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    > E/AndroidRuntime(14541): 	at
    > java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    > E/AndroidRuntime(14541): 	at java.lang.Thread.run(Thread.java:919)
    > E/AndroidRuntime(14541): Caused by: java.lang.AssertionError: INTERNAL
    > ASSERTION FAILED: A transaction object cannot be used after its update
    > callback has been invoked.

    > E/AndroidRuntime(14541): 	at
    > com.google.firebase.firestore.util.Assert.fail(com.google.firebase:firebase-firestore@@21.3.0:46)
    > E/AndroidRuntime(14541): 	at
    > com.google.firebase.firestore.util.Assert.hardAssert(com.google.firebase:firebase-firestore@@21.3.0:31)
    > E/AndroidRuntime(14541): 	at
    > com.google.firebase.firestore.core.Transaction.ensureCommitNotCalled(com.google.firebase:firebase-firestore@@21.3.0:246)
    > E/AndroidRuntime(14541): 	at
    > com.google.firebase.firestore.core.Transaction.write(com.google.firebase:firebase-firestore@@21.3.0:241)
    > E/AndroidRuntime(14541): 	at
    > com.google.firebase.firestore.core.Transaction.set(com.google.firebase:firebase-firestore@@21.3.0:105)
    > E/AndroidRuntime(14541): 	at
    > com.google.firebase.firestore.Transaction.set(com.google.firebase:firebase-firestore@@21.3.0:91)
    > E/AndroidRuntime(14541): 	at
    > com.google.firebase.firestore.Transaction.set(com.google.firebase:firebase-firestore@@21.3.0:67)
    > E/AndroidRuntime(14541): 	at
    > io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$7.doInBackground(CloudFirestorePlugin.java:688)
    > E/AndroidRuntime(14541): 	at
    > io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$7.doInBackground(CloudFirestorePlugin.java:682)
    > E/AndroidRuntime(14541): 	at
    > android.os.AsyncTask$3.call(AsyncTask.java:378)
    > E/AndroidRuntime(14541): 	at
    > java.util.concurrent.FutureTask.run(FutureTask.java:266)
    > E/AndroidRuntime(14541): 	... 4 more
```

I found When I tried executing `transAction.set` the internet service not working , the service is on but connection field , while that the error occurred,

my code is

```


       await FireStoreHelper.firestore.runTransaction(
            (transAction) async {
    
          await transAction.set(
               ItemsHelper(item.id).ItemsRef.document(),
               {
                  'title':'title',
                  'price': 11.20
               }
       )
       
```

**Comment by TahaTesser** [comment] 2020-04-21 11:49
Hi @niypoo 
can you please provide your `flutter doctor -v` and `flutter run --verbose`? 
Also, to better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem
Thank you

**Comment by larssn** [comment] 2020-05-16 12:35
@TahaTesser 

We haven't used transactions in cloud_firestore since we started using Flutter early last year, our initial tests showed they didn't work at all.

Today we retested our initial tests, and found that it's pretty much worse, as now it hard crashes with the above error; see https://github.com/FirebaseExtended/flutterfire/issues/54#issuecomment-629637871

Is cloud_firestore entirely community managed? I sadly haven't had time to dig into the code to try and figure out why it (apparently) is so hard to make transactions work.

**Comment by TahaTesser** [comment] 2020-05-22 11:13
Hi @niypoo 
Without additional information, we are unfortunately not sure how to resolve this issue. We are
therefore reluctantly going to close this bug for now. Please don't hesitate to comment on the
bug if you have any more information for us; we will reopen it right away!
Thanks for your contribution

**Closed by TahaTesser** 2020-05-22 11:13 UTC
Labels: blocked: customer-response
