### ISSUE TITLE
[firebase_ml_vision] Add support for custom models from ML Kit for Firebase

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#401] opened 2019-10-13 18:20 UTC
https://firebase.google.com/docs/ml-kit/use-custom-models

**Comment by kroikie** [comment] 2019-10-13 18:20
@bparrishMines

The issue at https://github.com/flutter/flutter/issues/28859 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by iapicca** [comment] 2019-10-22 10:27
Hi 
Since the date of the original post
many plugins have been made available,
including [firebase_ml_vision](https://pub.dev/packages/firebase_ml_vision)
therefore I feel safe to close this issue,
if you disagree please write in the comments
and I will reopen it. 
Thank you

**Comment by bparrishMines** [comment] 2019-10-25 19:00
@iapicca  `firebase_ml_vision` has been created, but it still does not have support for custom models. I'm going to go ahead and reopen.

**Comment by sebastianovide** [comment] 2020-02-14 08:38
in the meantime that an official support is released, did anybody find any stable plugin for this ?

**Comment by prakharb10** [comment] 2020-07-14 16:37
Any updates on this?

**Comment by bparrishMines** [comment] 2020-07-17 03:46
Closing since this looks to be a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/788

**Closed by bparrishMines** 2020-07-17 03:46 UTC
Labels: plugin: ml_vision, type: enhancement, type: missing-feature
