### ISSUE TITLE
🐛 Migration guide currently has both nullsafety and non-nullsafety package versions that are incompatible

### ISSUE THREAD

**Issue by zenkog** [FirebaseExtended/flutterfire#4907] opened 2021-02-02 07:40 UTC
## Bug report

**Describe the bug**
Dependencies issue / version solving failed when running `flutter pub get`, although I have followed the documentation from https://firebase.flutter.dev/docs/migration/

The error message was:
```
Running "flutter pub get" in test_app...                        

Because firebase_database >=6.0.0 depends on firebase_core ^0.7.0 and test_app depends on firebase_core ^0.8.0-nullsafety.1, firebase_database >=6.0.0 is forbidden.
So, because test_app depends on firebase_database ^6.0.0, version solving failed.
pub get failed (1; So, because test_app depends on firebase_database ^6.0.0, version solving failed.)
Process finished with exit code 1
```

### Steps to reproduce

1. Create a new flutter app
2. Add this in `pubspec.yaml`:
```
  firebase_core: ^0.8.0-nullsafety.1
  firebase_auth: ^0.21.0-nullsafety.0
  cloud_firestore: ^0.16.0
  cloud_functions: ^0.9.1-nullsafety.1
  firebase_storage: ^7.0.0
  firebase_admob: ^0.11.0+1
  firebase_analytics: ^7.0.1
  firebase_database: ^6.0.0
```
(* I'm following the versions listed in https://firebase.flutter.dev/docs/migration/ )
Note: These are all the latest versions. And if I change firebase_core to version 0.7.0 as the error said, I will get another dependency error. 

3. run `flutter pub get`

### Expected behavior
No error.

### Flutter doctor

Run `flutter doctor -v` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-US)
    • Flutter version 1.22.6 at /Users/ZK/development/flutter
    • Framework revision 9b2d32b605 (10 days ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5
    • Pub download mirror https://pub.flutter-io.cn
    • Flutter download mirror https://storage.flutter-io.cn

 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Volumes/ZK-R/Applications/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Volumes/ZK-R/Applications/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.4)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.4, Build version 12D4e
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9317
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.52.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.18.1

[✓] Connected device (1 available)
    • ZK iPho (mobile) • b3ebbe93864b12bcf25da9ac75d28 • ios • iOS 14.4

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>
Since we couldn't run `flutter pub get` thus we get an error code here.

```
The pubspec.yaml file has changed since the pubspec.lock file was generated, please run "pub get" again.
pub finished with exit code 65
```

</details>

---

**Comment by xmany** [comment] 2021-02-02 07:42
Same with `firebase_messaging`

```
Because firebase_messaging 7.0.3 depends on firebase_core ^0.5.0+1 and no versions of firebase_messaging match >7.0.3 <8.0.0, firebase_messaging ^7.0.3 requires firebase_core ^0.5.0+1.

So, because icoffee depends on both firebase_core ^0.7.0 and firebase_messaging ^7.0.3, version solving failed.
pub get failed (1; So, because icoffee depends on both firebase_core ^0.7.0 and firebase_messaging ^7.0.3, version solving failed.)
```

**Comment by markusaksli-nc** [comment] 2021-02-02 09:09
Hi @zenkog 
Not all of the plugins currently have a nullsafety version. You cannot mix and match the nullsafety and non-nullsafety firebase plugins. You can just use the latest versions for each that aren't nullsafety (for example auth would be `firebase_auth: ^0.20.0+1`).

Leaving this open to track the inconsistency until all of the plugins have a nullsafety version.

FYI @xmany you are getting a failure for a completely different reason. You are trying to use the latest firebase core with the outdated messaging version. The latest versions of the firebase plugins are not compatible with older versions because of an update to the iOS minimum target version constraint.

You need to either use the latest `firebase_messaging: ^8.0.0-dev.14` or downgrade all of your other firebase packages.

**Comment by hsnbsst** [comment] 2021-02-02 09:46
the same problem continues with me

```
  firebase_core: ^0.8.0-nullsafety.1
  firebase_auth: ^0.21.0-nullsafety.0
  firebase_crashlytics: ^0.5.0-1.0.nullsafety.1
  firebase_messaging: ^8.0.0-dev.14
  firebase_database: ^6.0.0
  firebase_analytics: ^7.0.1
```

```
Because firebase_analytics >=7.0.1 depends on firebase_core ^0.7.0 and mafya depends on firebase_core ^0.8.0-nullsafety.1, firebase_analytics >=7.0.1 is forbidden.

So, because mafya depends on firebase_analytics ^7.0.1, version solving failed.
pub get failed (1; So, because mafya depends on firebase_analytics ^7.0.1, version solving failed.)
exit code 1

```

**Comment by Ehesp** [comment] 2021-02-02 11:43
Got a PR up for this one. We dynamically inject the versions from pub so have had to manually break out null safe versions from the non-null ones.

**Comment by Ehesp** [comment] 2021-02-02 11:58
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4885

**Closed by Ehesp** 2021-02-02 11:58 UTC
Labels: plugin: core, type: bug

**Comment by YJaff** [comment] 2021-02-02 14:25
Definitely better, but the migration guide does not correspond to these older versions, which can be a bit disturbing... But nothing dramatic here. Any idea on a potential release date for null-safe cloud_messaging?

**Comment by jlubeck** [comment] 2021-02-18 21:14
Any reason why this (or #4885 for that matter) is closed when @markusaksli-nc mentioned 

> Leaving this open to track the inconsistency until all of the plugins have a nullsafety version.

**Comment by markusaksli-nc** [comment] 2021-02-19 08:54
The latest non-nullsafety versions of the plugins are in the migration guide again and null-safety now has its own separate section. This should clear any confusion (aside from https://github.com/FirebaseExtended/flutterfire/issues/4955 which was created as a result of this change).
