### ISSUE TITLE
[firebase_messaging] undesired auto cleaning notifications when entering foreground (iOS)

### ISSUE THREAD

**Issue by JasperShih** [FirebaseExtended/flutterfire#114] opened 2019-09-09 10:44 UTC
**Describe the bug**
Hi, I found a undesired auto cleaning notifications scenario when application entering foreground. It is at line 159 in
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/firebase_messaging/ios/Classes/FirebaseMessagingPlugin.m
``` objc
- (void)applicationDidBecomeActive:(UIApplication *)application {
  _resumingFromBackground = NO;
  // Clears push notifications from the notification center, with the
  // side effect of resetting the badge count. We need to clear notifications
  // because otherwise the user could tap notifications in the notification
  // center while the app is in the foreground, and we wouldn't be able to
  // distinguish that case from the case where a message came in and the
  // user dismissed the notification center without tapping anything.
  // TODO(goderbauer): Revisit this behavior once we provide an API for managing
  // the badge number, or if we add support for running Dart in the background.
  // Setting badgeNumber to 0 is a no-op (= notifications will not be cleared)
  // if it is already 0,
  // therefore the next line is setting it to 1 first before clearing it again
  // to remove all
  // notifications.
  application.applicationIconBadgeNumber = 1;
  application.applicationIconBadgeNumber = 0;
}
```

**To Reproduce**
1. get >=2 remote notifications on iPhone
2. enter foreground
3. all notifications & badges be unexpectedly removed 

**Expected behavior**
Just remove the notification we clicked. Thanks!

**Comment by izabekz** [comment] 2019-09-22 13:17
same problem, I don't want notifications to disappear after launching app, even when launching app  without clicking the notification makes it disappear and I lose info from notification

**Comment by kroikie** [comment] 2019-10-30 19:08
@JasperShih and @izabekz thanks for pointing this out. As you have noted this is currently WAI for the plugin, I'm going to re-label this as a feature request and we will update the behaviour.

**Comment by izabekz** [comment] 2019-11-12 09:00
@kroikie thanks, what does WAI mean? And another question, when the update will be available? This is very crucial for us.

**Comment by jigarfumakiya** [comment] 2019-11-29 09:24
when this update will be available? this is important for us.

**Comment by kroikie** [comment] 2019-12-03 21:05
@jigarfumakiya I agree that the current implementation of automatically clearing the notifications is something that does not work for all cases. I'm investigating the best way to provide the option to clear notifications by the developer.

**Comment by jigarfumakiya** [comment] 2019-12-06 04:41
thank you so much @kroikie but still, there is any date when this will be solved.

**Comment by jlhour** [comment] 2019-12-19 10:12
Thanks for the great work, but sorry to be insistent: why is this the expected/default behaviour?

**Comment by MaikuB** [comment] 2020-02-08 03:16
@kroikie the code causes another problem by clearing out notifications that might not have originated from firebase as well (see https://github.com/MaikuB/flutter_local_notifications/issues/134). An app may display a local notification and reference the `firebase_messaging` plugin. If they pull down the notification centre, the notification is automatically removed. This occurs even if an app only references the `firebase_messaging` plugin in the pubspec but doesn't use any of the APIs in the Flutter side. 

Perhaps this behaviour could be something is opted in as. The comments in the code also mention removal of the code if there's an API to manage the badge number. There's a plugin on pub for it https://pub.dev/packages/flutter_app_badger. The logic there could potentially be replaced my leavi g it to applications to check the [state of the app](https://api.flutter.dev/flutter/dart-ui/AppLifecycleState-class.html) and using the badge plugin to change the number

**Comment by nicholasrq** [comment] 2020-05-17 22:10
any updates on this issue? it becomes really annoying when you're trying to control the badge from the server and the app is continuously resetting the counter

**Comment by dprophete** [comment] 2020-05-27 08:01
Would love to know if there is an update here.

I am facing the exact same use case @MaikuB is referencing. 

The idea being that when I want notifications received when the app is in the foreground to behave like when the app is in the background. So as soon as firebase received a foreground notification, I am sending it back with `flutter_local_notifications`. 

So the combination of both `flutter_local_notifications` and `firebase_messaging` is causing the notification to disappear automatically from the system tray without me doing anything.

Like this:
![disappearing-notification](https://user-images.githubusercontent.com/518393/82993447-d871c400-a000-11ea-9c76-bacb95d77d12.gif)

@jlhour

**Comment by dprophete** [comment] 2020-05-27 09:10
@jlhour @kroikie  : or is there a way to let foreground notifications behave like background notification with using only `firebase_messaging` ?

Basically, I don't want to have to do any special treatment in my app for foreground notification. I want a regular notification to show up at the top and then be put in the system tray like any other notification and then let my user manage when/if he wants to deal with them.

For now the only solution I found for this was to use `flutter_local_notifications` (catch the foreground notificaton from firebase and dispatch it right away with flutter_local_notifications), but maybe there is an easier way?

**Comment by mhnowak** [comment] 2020-05-29 08:44
> @jlhour @kroikie : or is there a way to let foreground notifications behave like background notification with using only `firebase_messaging` ?
> 
> Basically, I don't want to have to do any special treatment in my app for foreground notification. I want a regular notification to show up at the top and then be put in the system tray like any other notification and then let my user manage when/if he wants to deal with them.
> 
> For now the only solution I found for this was to use `flutter_local_notifications` (catch the foreground notificaton from firebase and dispatch it right away with flutter_local_notifications), but maybe there is an easier way?

Hey - I've been working on something like this yesterday. `flutter_local_notifications` won't work, because this package is designed not to work in the foreground on iOS (You can find more info about it in package's readme). 

You can add this line to your `AppDelegate.swift` after you make the UNUserNotificationCenter delegate reference your app delegate by adding this:
```swift
        if #available(iOS 10.0, *) {
          UNUserNotificationCenter.current().delegate = self
        }
```
```swift
    override func userNotificationCenter(_ center: UNUserNotificationCenter, willPresent notification: UNNotification, withCompletionHandler completionHandler: @escaping (UNNotificationPresentationOptions) -> Void) {
        completionHandler([.alert, .badge, .sound])
    }
```

Reference: https://stackoverflow.com/a/37844312

**Comment by MaikuB** [comment] 2020-05-29 08:53
> because this package is designed not to work in the foreground on iOS (You can find more info about it in package's readme).

@mhnowak which package are you referring to here? If you're referring to `flutter_local_notifications` then it does work in the foreground. The note in the readme is that iOS requires extra steps (this is how the native APIs work) and the plugin exposes properties that map to the presentation options. There is already code in the plugin to do what you've described. 

Another thing to note that @dprophete has gotten `flutter_local_notifications`  to work together with `firebase_messaging` . Unfortunately there's an issue in `firebase_messaging` where pulling down the notifications tray and returning to the app clears all of the notifications because of the code around changing the application's badge number

**Comment by mhnowak** [comment] 2020-05-29 08:59
> > because this package is designed not to work in the foreground on iOS (You can find more info about it in package's readme).
> 
> 
> 
> @mhnowak which package are you referring to here? If you're referring to `flutter_local_notifications` then it does work in the foreground. The note in the readme is that iOS requires extra steps (this is how the native APIs work) and the plugin exposes properties that map to the presentation options. There is already code in the plugin to do what you've described. 
> 
> 
> 
> Another thing to note that @dprophete has gotten `flutter_local_notifications`  to work together with `firebase_messaging` . Unfortunately there's an issue in `firebase_messaging` where pulling down the notifications tray and returning to the app clears all of the notifications because of the code around changing the application's badge number

Ahh ok. You might be right I didn’t read deeply enough there.

**Comment by MaikuB** [comment] 2020-05-29 09:05
No worries. I probably should've added that I maintain `flutter_local_notifications` and referred @dprophete to this issue after he reported the problem on the `flutter_local_notifications`'s repository  :)

**Comment by Yirmerah** [comment] 2020-07-03 19:13
Any updates ?

**Comment by samuelgfenton** [comment] 2020-07-11 12:18
Hey Guys, any updates on this, it is a frustrating behaviour.

**Comment by MobileMon** [comment] 2020-08-10 16:09
This needs to be fixed but if you need a quick fix just search for and comment out these 2 lines:

 //application.applicationIconBadgeNumber = 1;
//  application.applicationIconBadgeNumber = 0;

Then make sure to do it every time if you upgrade the package

**Comment by MaikuB** [comment] 2020-08-18 12:53
@FirebaseExtended/invertase any chance this could be prioritised? Some solutions have been discussed here, including the removal of code that is causing this to happen

**Comment by Salakar** [comment] 2020-08-18 13:27
Messaging is being started in the next couple of weeks and we are aware of this issue. We've also started adding docs for messaging, e.g. https://firebase.flutter.dev/docs/messaging/ios-integration

**Comment by MaikuB** [comment] 2020-08-18 13:29
Thanks @Salakar, did see that page today :)

**Comment by Salakar** [comment] 2020-08-18 13:36
Looks like this was actually fixed recently:

https://github.com/FirebaseExtended/flutterfire/pull/227

**Comment by MaikuB** [comment] 2020-08-18 13:41
Missed that as the changelog entry sounded like it was for a different issue as it mentions app launch. If it is fixed then shouldn't the change be classified as a breaking change? Previously it was mentioned that this was working as intended

**Comment by Salakar** [comment] 2020-08-18 13:50
Not one we looked at ourselves but I think you're right probably should have been a breaking change.

We're most likely going to remove this entirely in the rework anyway and expose badge APIs to Dart like we did here: https://notifee.app/react-native/docs/ios/badges (JavaScript of course, but API applies).

**Comment by MaikuB** [comment] 2020-08-18 13:58
Given there's already this package https://pub.dev/packages/flutter_app_badger, I wonder if it's perhaps better to promote existing work done by others in community

**Comment by Salakar** [comment] 2020-08-18 14:01
That is also definitely an option of course, nothing set in stone yet :) That one looks pretty well maintained

I'm going to go ahead and close this issue now at least as there has been a fix published.

**Closed by Salakar** 2020-08-18 14:01 UTC
Labels: impact: critical, plugin: messaging, type: enhancement

**Comment by evripidesk** [comment] 2020-09-15 06:38
I have project with firebase messaging 7.0.0 and when I received notification with badge when I opened the app without click on notification , the notification automatically removed from notifications tray
