### ISSUE TITLE
[firebase_admob] ^0.9.0+7 Android/iOS app crashes on clean installation

### ISSUE THREAD

**Issue by soncco** [FirebaseExtended/flutterfire#1282] opened 2019-10-19 14:16 UTC
**Describe the bug**
With a clean installation with flutter create command, app crashes without error.

**To Reproduce**
1. flutter create
2. Configure app following [the steps of page](https://pub.dev/packages/firebase_admob)
3. Running app
4. App crashes without error on Android
5. iOS app crashes with the following message:
```
    Launching lib/main.dart on iPhone 11 Pro Max in debug mode...
    Xcode build done.                                           61,0s
        path: satisfied (Path is satisfied), interface: en1
    Configuring the default Firebase app...
    *** First throw call stack:
    (
        0   CoreFoundation                      0x00007fff23baa1ee __exceptionPreprocess + 350
        1   libobjc.A.dylib                     0x00007fff50864b20 objc_exception_throw + 48
        2   CoreFoundation                      0x00007fff23baa02c +[NSException raise:format:] + 188
        3   Runner                              0x000000010c7792fa +[FIRApp configure] + 138
        4   Runner                              0x000000010c953872 -[FLTFirebaseAdMobPlugin init] + 258
        5   Runner                              0x000000010c9535e6 +[FLTFirebaseAdMobPlugin registerWithRegistrar:] + 70
        6   Runner                              0x000000010c774ba0 +[GeneratedPluginRegistrant registerWithRegistry:] + 112
        7   Runner                           <…>
    Lost connection to device.
```

**Expected behavior**
App running

**Additional context**

[✓] Flutter (Channel stable, v1.9.1+hotfix.5, on Mac OS X 10.14.6 18G95, locale es-PE)
    • Flutter version 1.9.1+hotfix.5 at /Users/brau/flutter
    • Framework revision 1aedbb1835 (2 days ago), 2019-10-17 08:37:27 -0700
    • Engine revision b863200c37
    • Dart version 2.5.0

 
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
    • Android SDK at /Users/brau/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • ANDROID_HOME = /Users/brau/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.1, Build version 11A1027
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 40.2.2
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.39.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.5.1

**Comment by JonasJW** [comment] 2019-10-19 20:07
I have the same issue and I read about other users with the same issue. Latest version that doesn't have the problem is `0.5.5` for me.

Problem is, with this version I can't build the apk, I get this error:

````
FAILURE: Build failed with an exception.                                                                           
                                                                                                                  
* What went wrong:                                                                                                 
Execution failed for task ':firebase_admob:verifyReleaseResources'.                                                
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  Output:  /Users/jonas/Projects/ProjectFit/mobile/project_fit_flutter/build/firebase_admob/intermediates/res/merged/release/values/values.xml:208: error: resource android:attr/fontVariationSettings not found.
  /Users/jonas/Projects/ProjectFit/mobile/project_fit_flutter/build/firebase_admob/intermediates/res/merged/release/values/values.xml:209: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by andersoncarlosfs** [comment] 2019-10-20 05:15
I got the same errors for both libraries (tested separately as well).

cloud_firestore: ^0.12.9+5
firebase_auth: ^0.14.0+5

The same behaviours for the same steps to reproduce.

**Comment by zingwin** [comment] 2019-10-24 02:27
I got the same errors firebase_admob: 0.9.0

**Comment by iapicca** [comment] 2019-10-25 10:22
https://github.com/FirebaseExtended/flutterfire/issues/17

**Comment by shenwilly** [comment] 2019-11-02 05:04
Using the value provided on the instruction page causes crash, try this:

        <meta-data
            android:name="com.google.android.gms.ads.APPLICATION_ID"
            android:value="ca-app-pub-0000000000000000~0000000000"/>

**Comment by duvandduque** [comment] 2020-05-08 12:32
use flutter build appbundle for android

**Comment by blasten** [comment] 2020-05-13 19:17
This is a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2516

**Closed by blasten** 2020-05-13 19:17 UTC
Labels: impact: critical, impact: crowd, platform: android, platform: ios, plugin: admob, type: bug
