### ISSUE TITLE
🐛 [Auth] Firebase Auth Anon Login lastSignInTime is incorrect.

### ISSUE THREAD

**Issue by pMertDogan** [FirebaseExtended/flutterfire#6362] opened 2021-06-10 21:49 UTC
Hi,

I just want to learn if a user is a new user or not when sing in successfully. For this purpose, I m using lastSignInTime == creationTime condition but its returns true if I just reopen the app. Unable find to way to get the latest lastSingInTime. I can use Systemtime to compare it with creationTime but why is the lastSignInTime is not updated?

```
  FirebaseAuthService() {
    streamSubs = auth.userChanges().listen((User? user) {
      // streamSubs = auth.authStateChanges().listen((User? user) {

      print('Şuanki kulllanıcı ******' + user.toString());
      //Bu iki kere çalışabilir,bilinen bir hata
      if (user != null) {
        print(user.providerData);
        // if (user.metadata.creationTime == user.metadata.lastSignInTime) {
        //
        // }
        streamController.add(Oyuncu(
            ID: user.uid,
            name: user.displayName,
            creationTime: user.metadata.creationTime,
            lastLoginDateTime: user.metadata.lastSignInTime,
            profilePicture: user.photoURL,
            //new provider new if else
            loginProvider: user.providerData.isEmpty
                ? LoginProvider.anon
                : user.providerData[0].providerId == 'firebase'
                    ? LoginProvider.firebase
                    : LoginProvider.google));
      } else {
        streamController.add(null);
      }
    });
  }
```

`Şuanki kulllanıcı ******User(displayName: null, email: null, emailVerified: false, isAnonymous: true, metadata: UserMetadata(creationTime: 2021-06-10 20:45:55.631, lastSignInTime: 2021-06-10 20:45:55.631), phoneNumber: null, photoURL: null, providerData, [], refreshToken: , tenantId: null, uid: gA5qsB7Bh6VI39LwHoGXFrTF4F52)`

**Describe the bug**

The lastSignInTime is not updated for Anon logged user if I just reopen the app. Always lastSignInTime is equal to creationTime

### Steps to reproduce
Login as Anon
Close app
Reopen app
Check is creationTime equal to lastSignInTime ?

### Expected behavior

lastSignInTime is cant be equal to creationTime after the first login operation. Closing the app and reopen action should be update lastSignInTime.

### Sample project

Its takes time to setup :/ 

---

## Additional context

Tested on Android Emulator provided by Android Studio

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
C:\Projeler\p763_quiz>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.2.1, on Microsoft Windows [Version 10.0.19042.985], locale tr-TR)
[!] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[!] Android Studio (not installed)
[√] VS Code (version 1.56.2)
[√] Connected device (3 available)

! Doctor found issues in 2 categories.

C:\Projeler\p763_quiz>

```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
C:\Projeler\p763_quiz>flutter pub deps -- --style=compact
Dart SDK 2.13.1
Flutter SDK 2.2.1
p763_quiz 1.0.0+1

dependencies:
- bot_toast 4.0.1 [flutter]
- cloud_firestore 2.2.1 [cloud_firestore_platform_interface cloud_firestore_web firebase_core firebase_core_platform_interface flutter meta]
- confetti 0.6.0-nullsafety [flutter random_color vector_math]
- cupertino_icons 1.0.3
- firebase_auth 1.3.0 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.2.1 [firebase_core_platform_interface firebase_core_web flutter meta]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_bloc 7.0.1 [flutter bloc provider]
- flutter_icons 1.1.1-nullsafety.0 [flutter]
- flutter_signin_button 2.0.0 [flutter font_awesome_flutter]
- flutter_svg 0.22.0 [flutter meta path_drawing vector_math xml]
- freezed_annotation 0.14.1 [collection json_annotation meta]
- google_sign_in 5.0.4 [google_sign_in_platform_interface google_sign_in_web flutter meta]
- internet_connection_checker 0.0.1+1 [universal_io]
- introduction_screen 2.1.0 [flutter dots_indicator]
- json_serializable 4.1.3 [analyzer build build_config collection json_annotation meta path source_gen]
- lottie 1.0.1 [archive characters charcode collection flutter logging meta path vector_math]
- persistent_bottom_nav_bar 4.0.2 [flutter]

dev dependencies:
- build_runner 2.0.2 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs
 http_multi_server io js logging meta mime package_config path pedantic pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_chan
nel yaml]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel strin
g_scanner term_glyph typed_data]
- freezed 0.14.1+3 [analyzer build build_config meta source_gen freezed_annotation]
- pedantic 1.11.0

transitive dependencies:
- _fe_analyzer_shared 21.0.0 [meta]
- analyzer 1.5.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml pedantic]
- archive 3.1.2 [crypto path]
- args 2.1.0
- async 2.5.0 [collection]
- bloc 7.0.0 [meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.0.1 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.1 [analyzer build crypto graphs logging path package_config pool pub_semver stream_transform]
- build_runner_core 7.0.0 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pedantic pool timing watcher
yaml]
- built_collection 5.0.0
- built_value 8.0.6 [built_collection collection fixnum]
- characters 1.1.0
- charcode 1.2.0
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.0 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.1.1 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.1.1 [cloud_firestore_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.0.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.0 [typed_data]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.1 [analyzer args path pub_semver source_span]
- dots_indicator 2.0.0 [flutter]
- fake_async 1.2.0 [clock collection]
- file 6.1.0 [meta path]
- firebase_auth_platform_interface 4.2.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 1.2.0 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.0.1 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.1.0 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- fixnum 1.0.0
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- font_awesome_flutter 9.0.0 [flutter]
- frontend_server_client 2.1.0 [async path]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_sign_in_platform_interface 2.0.1 [flutter meta quiver]
- google_sign_in_web 0.10.0 [google_sign_in_platform_interface flutter flutter_web_plugins meta js]
- graphs 2.0.0
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- intl 0.17.0 [clock path]
- io 1.0.0 [meta path string_scanner]
- js 0.6.3
- json_annotation 4.0.1
- logging 1.0.1
- matcher 0.12.10 [stack_trace]
- meta 1.3.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- package_config 2.0.0 [path]
- path 1.8.0
- path_drawing 0.5.1 [vector_math meta path_parsing flutter]
- path_parsing 0.2.1 [vector_math meta]
- petitparser 4.1.0 [meta]
- plugin_platform_interface 2.0.0 [meta]
- pool 1.5.0 [async stack_trace]
- provider 5.0.0 [collection flutter nested]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1 [matcher]
- random_color 1.0.6-nullsafety [flutter]
- shelf 1.1.1 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sky_engine 0.0.99
- source_gen 1.0.0 [analyzer async build dart_style glob meta path pedantic source_span]
- source_span 1.8.0 [charcode collection path term_glyph]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- term_glyph 1.2.0
- test_api 0.2.19 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- vector_math 2.1.0
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- xml 5.1.0 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]

```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-06-11 09:11
Hi @pMertDogan 
I'm not sure what the problem is exactly? The last log-in time gets updated when the user logs in, reopening the app in no way implies logging in unless you explicitly log the user out at app startup or something. Besides, an anonymous user can't update its last log-in time since it has no auth providers to log in with when it is created (and once an auth provider is added to the user it is no longer anonymous).
Closing the issue since the plugin seems to be working as expected here.

**Closed by markusaksli-nc** 2021-06-11 09:11 UTC
Labels: Needs Attention, in triage, type: bug

**Comment by pMertDogan** [comment] 2021-06-11 16:40
Hi,
If user keep using the same anon account for more than a two month or more. Is it still same? Logically isnt it should be updated? How this field can be updated? Is it updated only on register?  If yes why we have this field Its not make any sense

How can i Just let the user relog with the same anon user?  If I Just use logout, I cant relogin with the same a on account anymore

**Comment by markusaksli-nc** [comment] 2021-06-14 11:16
Like I said an anonymous user **can not log in**. By definition a user is anonymous if they have no auth providers, meaning no method to log in with. This is why using last log-in time doesn't make sense if you are only using anonymous users since all of your users will just be created and discarded once they log out since there is no way to "log back in" to an anonymous user.

As for letting the user relog - the solution here is to either provide something like email and password login so the accounts are not anonymous. Otherwise how would you even theoretically distinguish which anonymous user belongs to which actual user?
