### ISSUE TITLE
🐛 [flutterfire_ui] FirestoreQueryBuilder loads entire collection and does not trigger load more on scroll?

### ISSUE THREAD

**Issue by AlmogRnD** [FirebaseExtended/flutterfire#7850] opened 2022-01-12 10:28 UTC
## Bug report

**Describe the bug**
I'm using FirestoreQueryBuilder but on the initial page/view load its loads the entire Firetore collection even though it should only load the first 10 docs at the same time it does not trigger the load more when I scroll to the bottom of the list view builder. If I set the page limit to 5 for example it will still load the entire collection. 

### Steps to reproduce

Need to implement with list view builder 

### Expected behavior

Should not load the entire collection, and load the rest when  a user scrolls down to the bottom of the list 
### Sample project

Here is my code https://stackoverflow.com/questions/70669061/flutter-firestore-ui-firestorequerybuilder-loads-entire-collection-and-does-not

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-x64, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 13.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.63.2)
[✓] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.15.1
Flutter SDK 2.8.1
dogbase_app 1.0.0+1

dependencies:
- cached_network_image 3.1.0+1 [flutter flutter_cache_manager octo_image cached_network_image_platform_interface cached_network_image_web]
- cloud_firestore 3.1.6 [cloud_firestore_platform_interface cloud_firestore_web collection firebase_core firebase_core_platform_interface flutter meta]
- convex_bottom_bar 3.0.0 [flutter]
- dropdown_search 2.0.0 [flutter]
- duration_picker 1.1.0+1 [flutter_lints flutter]
- enum_to_string 2.0.1
- firebase_analytics 9.0.5 [firebase_analytics_platform_interface firebase_analytics_web firebase_core firebase_core_platform_interface flutter]
- firebase_auth 3.3.5 [firebase_auth_platform_interface firebase_auth_web firebase_core firebase_core_platform_interface flutter meta]
- firebase_core 1.11.0 [firebase_core_platform_interface firebase_core_web flutter meta]
- firebase_storage 10.2.5 [firebase_core firebase_core_platform_interface firebase_storage_platform_interface firebase_storage_web flutter]
- fl_chart 0.40.2 [flutter equatable]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_form_builder 7.0.0 [flutter intl]
- flutter_gravatar 2.0.2 [flutter flutter_test crypto]
- flutter_localizations 0.0.0 [flutter intl characters clock collection meta path typed_data vector_math]
- flutter_rating_bar 4.0.0 [flutter]
- flutter_svg 1.0.0 [flutter meta path_drawing vector_math xml]
- flutter_toggle_tab 1.1.7 [flutter]
- flutterfire_ui 0.3.1 [cloud_firestore collection crypto desktop_webview_auth email_validator firebase_auth firebase_core firebase_database firebase_dynamic_links flutter flutter_facebook_auth flutter_localizations flutter_svg google_sign_in sign_in_with_apple twitter_login]
- font_awesome_flutter 9.2.0 [flutter]
- form_builder_extra_fields 7.0.0 [flutter flutter_form_builder flutter_chips_input flutter_colorpicker dropdown_search signature flutter_touch_spin intl flutter_typeahead flutter_datetime_picker flutter_rating_bar]
- form_builder_validators 7.2.0 [flutter flutter_localizations intl collection]
- geocoding 2.0.1 [flutter geocoding_platform_interface]
- geolocator 7.7.1 [flutter geolocator_platform_interface geolocator_android geolocator_apple geolocator_web]
- google_maps_flutter 2.1.0 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- hive 2.0.4 [meta crypto]
- hive_flutter 1.1.0 [flutter hive path_provider path]
- image_picker 0.8.4+4 [flutter flutter_plugin_android_lifecycle image_picker_for_web image_picker_platform_interface]
- intl 0.17.0 [clock path]
- json_annotation 4.3.0 [meta]
- json_serializable 6.0.1 [analyzer async build build_config collection json_annotation meta path pub_semver pubspec_parse source_gen source_helper]
- lottie 1.2.1 [archive characters flutter path vector_math]
- modal_bottom_sheet 2.0.0 [flutter]
- multi_select_flutter 4.0.0 [flutter collection]
- package_info_plus 1.3.0 [flutter package_info_plus_platform_interface package_info_plus_linux package_info_plus_macos package_info_plus_windows package_info_plus_web]
- page_view_dot_indicator 1.1.0 [flutter]
- path 1.8.0
- provider 6.0.2 [collection flutter nested]
- share_plus 3.0.4 [meta mime flutter share_plus_platform_interface share_plus_linux share_plus_macos share_plus_windows share_plus_web]
- top_snackbar_flutter 1.0.2 [flutter]
- url_launcher 6.0.12 [flutter meta url_launcher_linux url_launcher_macos url_launcher_platform_interface url_launcher_web url_launcher_windows]

dev dependencies:
- build_runner 2.1.5 [args async analyzer build build_config build_daemon build_resolvers build_runner_core code_builder collection crypto dart_style frontend_server_client glob graphs http_multi_server io js logging meta mime package_config path pool pub_semver pubspec_parse shelf shelf_web_socket stack_trace stream_transform timing watcher web_socket_channel yaml]
- dependency_validator 3.1.0 [args build_config checked_yaml glob io json_annotation logging package_config path pub_semver pubspec_parse yaml]
- flutter_launcher_icons 0.9.2 [args image path yaml]
- flutter_native_splash 1.3.1 [args image meta path xml yaml universal_io]
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]
- hive_generator 1.1.1 [build source_gen hive analyzer source_helper]
- import_sorter 4.6.0 [args tint yaml]
- lint 1.7.2

transitive dependencies:
- _fe_analyzer_shared 30.0.0 [meta]
- analyzer 2.7.0 [_fe_analyzer_shared cli_util collection convert crypto glob meta package_config path pub_semver source_span watcher yaml]
- archive 3.1.6 [crypto path]
- args 2.3.0
- async 2.8.2 [collection meta]
- boolean_selector 2.1.0 [source_span string_scanner]
- build 2.1.0 [analyzer async convert crypto glob logging meta path]
- build_config 1.0.0 [checked_yaml json_annotation path pubspec_parse yaml]
- build_daemon 3.0.0 [built_collection built_value http_multi_server logging pedantic path pool shelf shelf_web_socket stream_transform watcher web_socket_channel]
- build_resolvers 2.0.4 [analyzer async build crypto graphs logging path package_config pool pub_semver stream_transform yaml]
- build_runner_core 7.2.2 [async build build_config build_resolvers collection convert crypto glob graphs json_annotation logging meta path package_config pool timing watcher yaml]
- built_collection 5.1.0
- built_value 8.1.1 [built_collection collection fixnum meta]
- cached_network_image_platform_interface 1.0.0 [flutter flutter_cache_manager]
- cached_network_image_web 1.0.1 [flutter flutter_cache_manager cached_network_image_platform_interface]
- characters 1.2.0
- charcode 1.3.1
- checked_yaml 2.0.1 [json_annotation source_span yaml]
- cli_util 0.3.3 [meta path]
- clock 1.1.0
- cloud_firestore_platform_interface 5.4.11 [collection firebase_core flutter meta plugin_platform_interface]
- cloud_firestore_web 2.6.6 [cloud_firestore_platform_interface collection firebase_core firebase_core_web flutter flutter_web_plugins js]
- code_builder 4.1.0 [built_collection built_value collection matcher meta]
- collection 1.15.0
- convert 3.0.1 [typed_data]
- cross_file 0.3.2 [flutter js meta]
- crypto 3.0.1 [collection typed_data]
- dart_style 2.0.3 [analyzer args path pub_semver source_span]
- desktop_webview_auth 0.0.2 [crypto flutter http]
- email_validator 2.0.1
- equatable 2.0.3 [collection meta]
- fake_async 1.2.0 [clock collection]
- ffi 1.1.2
- file 6.1.2 [meta path]
- firebase_analytics_platform_interface 3.0.4 [firebase_core flutter meta plugin_platform_interface]
- firebase_analytics_web 0.4.0+5 [firebase_analytics_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins js]
- firebase_auth_platform_interface 6.1.10 [firebase_core flutter meta plugin_platform_interface]
- firebase_auth_web 3.3.6 [firebase_auth_platform_interface firebase_core firebase_core_web flutter flutter_web_plugins http_parser intl js meta]
- firebase_core_platform_interface 4.2.3 [collection flutter meta plugin_platform_interface]
- firebase_core_web 1.5.3 [firebase_core_platform_interface flutter flutter_web_plugins js meta]
- firebase_database 9.0.5 [firebase_core firebase_core_platform_interface firebase_database_platform_interface firebase_database_web flutter]
- firebase_database_platform_interface 0.2.0+4 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_database_web 0.2.0+4 [firebase_core firebase_core_web firebase_database_platform_interface flutter flutter_web_plugins js]
- firebase_dynamic_links 4.0.4 [firebase_core firebase_core_platform_interface firebase_dynamic_links_platform_interface flutter meta plugin_platform_interface]
- firebase_dynamic_links_platform_interface 0.2.0+4 [firebase_core flutter meta plugin_platform_interface]
- firebase_storage_platform_interface 4.0.12 [collection firebase_core flutter meta plugin_platform_interface]
- firebase_storage_web 3.2.6 [async firebase_core firebase_core_web firebase_storage_platform_interface flutter flutter_web_plugins http js meta]
- fixnum 1.0.0
- flutter_blurhash 0.6.0 [flutter meta pedantic]
- flutter_cache_manager 3.1.2 [clock collection file flutter http path path_provider pedantic rxdart sqflite uuid]
- flutter_chips_input 1.10.0 [flutter]
- flutter_colorpicker 0.6.1 [flutter]
- flutter_datetime_picker 1.5.1 [flutter]
- flutter_facebook_auth 3.5.7 [flutter flutter_facebook_auth_platform_interface flutter_facebook_auth_web]
- flutter_facebook_auth_platform_interface 2.7.1 [flutter plugin_platform_interface]
- flutter_facebook_auth_web 2.6.0+2 [flutter flutter_web_plugins js flutter_facebook_auth_platform_interface]
- flutter_keyboard_visibility 5.1.0 [meta flutter_keyboard_visibility_platform_interface flutter_keyboard_visibility_web flutter]
- flutter_keyboard_visibility_platform_interface 2.0.0 [flutter meta plugin_platform_interface]
- flutter_keyboard_visibility_web 2.0.0 [flutter_keyboard_visibility_platform_interface flutter_web_plugins flutter]
- flutter_lints 1.0.4 [lints]
- flutter_plugin_android_lifecycle 2.0.2 [flutter]
- flutter_touch_spin 2.0.0-nullsafety.1 [flutter intl]
- flutter_typeahead 3.2.1 [flutter flutter_keyboard_visibility]
- flutter_web_plugins 0.0.0 [flutter js characters collection meta typed_data vector_math]
- frontend_server_client 2.1.0 [async path]
- geocoding_platform_interface 2.0.1 [flutter meta plugin_platform_interface]
- geolocator_android 2.1.0 [flutter geolocator_platform_interface]
- geolocator_apple 1.2.2 [flutter geolocator_platform_interface]
- geolocator_platform_interface 2.3.6 [flutter plugin_platform_interface vector_math meta]
- geolocator_web 2.0.6 [flutter flutter_web_plugins geolocator_platform_interface]
- glob 2.0.1 [async collection file path pedantic string_scanner]
- google_maps_flutter_platform_interface 2.1.3 [collection flutter meta plugin_platform_interface stream_transform]
- google_sign_in 5.2.2 [flutter google_sign_in_platform_interface google_sign_in_web]
- google_sign_in_platform_interface 2.1.1 [flutter quiver]
- google_sign_in_web 0.10.0+4 [flutter flutter_web_plugins google_sign_in_platform_interface js pedantic]
- graphs 2.0.0
- http 0.13.4 [async http_parser meta path]
- http_multi_server 3.0.1 [async]
- http_parser 4.0.0 [charcode collection source_span string_scanner typed_data]
- image 3.0.8 [archive meta xml]
- image_picker_for_web 2.1.4 [flutter flutter_web_plugins image_picker_platform_interface meta]
- image_picker_platform_interface 2.4.1 [flutter http meta plugin_platform_interface cross_file]
- io 1.0.3 [meta path string_scanner]
- js 0.6.3
- lints 1.0.1
- logging 1.0.1
- matcher 0.12.11 [stack_trace]
- meta 1.7.0
- mime 1.0.0
- nested 1.0.0 [flutter]
- octo_image 1.0.0+1 [flutter flutter_blurhash]
- package_config 2.0.0 [path]
- package_info_plus_linux 1.0.3 [package_info_plus_platform_interface flutter path]
- package_info_plus_macos 1.3.0 [flutter]
- package_info_plus_platform_interface 1.0.2 [flutter meta plugin_platform_interface]
- package_info_plus_web 1.0.4 [flutter flutter_web_plugins http meta package_info_plus_platform_interface]
- package_info_plus_windows 1.0.4 [package_info_plus_platform_interface ffi flutter win32]
- path_drawing 1.0.0 [vector_math meta path_parsing flutter]
- path_parsing 1.0.0 [vector_math meta]
- path_provider 2.0.2 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 2.0.2 [flutter path path_provider_platform_interface xdg_directories]
- path_provider_macos 2.0.2 [flutter]
- path_provider_platform_interface 2.0.1 [flutter meta platform plugin_platform_interface]
- path_provider_windows 2.0.3 [ffi flutter meta path path_provider_platform_interface win32]
- pedantic 1.11.1
- petitparser 4.4.0 [meta]
- platform 3.0.0
- plugin_platform_interface 2.1.2 [meta]
- pool 1.5.0 [async stack_trace]
- process 4.2.3 [file path platform]
- pub_semver 2.0.0 [collection]
- pubspec_parse 1.0.0 [checked_yaml collection json_annotation pub_semver yaml]
- quiver 3.0.1+1 [matcher]
- rxdart 0.27.1
- share_plus_linux 2.0.4 [share_plus_platform_interface file flutter meta url_launcher]
- share_plus_macos 2.0.2 [share_plus_platform_interface flutter]
- share_plus_platform_interface 2.0.1 [flutter meta mime plugin_platform_interface]
- share_plus_web 2.0.4 [share_plus_platform_interface url_launcher flutter flutter_web_plugins meta]
- share_plus_windows 2.0.3 [share_plus_platform_interface flutter meta url_launcher]
- shelf 1.2.0 [async collection http_parser path stack_trace stream_channel]
- shelf_web_socket 1.0.1 [shelf stream_channel web_socket_channel]
- sign_in_with_apple 3.3.0 [flutter meta sign_in_with_apple_platform_interface sign_in_with_apple_web]
- sign_in_with_apple_platform_interface 1.0.0 [flutter plugin_platform_interface meta]
- sign_in_with_apple_web 1.0.1 [flutter flutter_web_plugins sign_in_with_apple_platform_interface js]
- signature 4.1.1 [flutter image]
- sky_engine 0.0.99
- source_gen 1.0.3 [analyzer async build dart_style glob meta path pedantic source_span yaml]
- source_helper 1.3.0 [analyzer collection source_gen]
- source_span 1.8.1 [collection path term_glyph]
- sqflite 2.0.0+3 [flutter sqflite_common path]
- sqflite_common 2.0.0+2 [synchronized path meta]
- stack_trace 1.10.0 [path]
- stream_channel 2.1.0 [async]
- stream_transform 2.0.0
- string_scanner 1.1.0 [charcode source_span]
- synchronized 3.0.0
- term_glyph 1.2.0
- test_api 0.4.3 [async boolean_selector collection meta source_span stack_trace stream_channel string_scanner term_glyph matcher]
- timing 1.0.0 [json_annotation]
- tint 2.0.0
- twitter_login 4.0.1 [flutter crypto http]
- typed_data 1.3.0 [collection]
- universal_io 2.0.4 [collection crypto meta typed_data]
- url_launcher_linux 2.0.1 [flutter]
- url_launcher_macos 2.0.1 [flutter]
- url_launcher_platform_interface 2.0.4 [flutter plugin_platform_interface]
- url_launcher_web 2.0.4 [flutter flutter_web_plugins meta url_launcher_platform_interface]
- url_launcher_windows 2.0.2 [flutter]
- uuid 3.0.4 [crypto]
- vector_math 2.1.1
- watcher 1.0.0 [async path pedantic]
- web_socket_channel 2.1.0 [async crypto stream_channel]
- win32 2.2.5 [ffi]
- xdg_directories 0.2.0 [meta path process]
- xml 5.3.1 [collection meta petitparser]
- yaml 3.1.0 [collection source_span string_scanner]
```

</details>

---

**Comment by darshankawar** [comment] 2022-01-13 10:29
@AlmogRnD 
I tried to use the code sample from SO link you provided, but it seems to be incomplete. Can you provide us a complete minimal code sample (e.g: main.dart) which we can directly use and verify this behavior ?

**Comment by AlmogRnD** [comment] 2022-01-13 10:32
I will try to but I'm already looking at using something else. It just doest work just add the widget to any code and you will get the issue

**Comment by darshankawar** [comment] 2022-01-13 11:36
While I will also try to come up with a complete sample, you may try using the official [example](https://firebase.flutter.dev/docs/ui/firestore/) from the document and see if you still get same behavior with it or not.

**Comment by AlmogRnD** [comment] 2022-01-13 11:37
Same behavior

**Comment by AlmogRnD** [comment] 2022-01-14 11:59
@rrousselGit here a video showing how it's loading the entire collection all at once 
-

https://user-images.githubusercontent.com/169507/149511709-bd5014c9-ecbe-4038-b435-382df0483ddd.mp4


Video showing page limit set to 5 and it still loads the whole collection 
https://user-images.githubusercontent.com/169507/149511961-95b04eb5-277c-48bc-95c3-7907984ed747.mp4

My code is the same as the docs the only difference is ` child: FirestoreQueryBuilder<DogModel>(` is wrapped in a SizedBoxed and that is wrapped with `SingleChildScrollView` that has its own controller.

**Comment by AlmogRnD** [comment] 2022-01-14 12:15
For Android, I get some crazy flickering issues, and the same issues as the above page limit do not work, loads the entire collection at once

https://user-images.githubusercontent.com/169507/149514005-11e18bcb-7507-430b-97da-81d344c82903.mp4

**Comment by rrousselGit** [comment] 2022-01-14 12:16
This could be due to various reasons, such as your list potentially showing all the items for a split second (for example while the dog pictures are loading).

We need a minimal reproducible code as this isn't how the official example behaves.

**Comment by AlmogRnD** [comment] 2022-01-14 12:19
@rrousselGit I'm happy to give you access to my codebase if that helps but the "minimal reproducible code" just like your example works fine but is not actually a real-world example or real use case.  I mean I have it wrapped in different widgets for example. Let me know if you want access to the code. I have also been trying to debug it but not sure what is going on I removed the sizedbox and scrollchild still same issues

**Comment by rrousselGit** [comment] 2022-01-14 12:23
Having access to your codebase is not reasonable. Please find a way to extract the issue out of your project in a way that can be executed

**Comment by AlmogRnD** [comment] 2022-01-14 12:44
@rrousselGit in the video you sent its showing the Firestore list view I'm not using that widget do you have an example of FirestoreQueryBuilder in storybook that is working

**Comment by rrousselGit** [comment] 2022-01-14 12:46
FirestoreListView is using FirestoreQueryBuilder, it's just a syntax sugar.

**Comment by AlmogRnD** [comment] 2022-01-14 12:53
ok either way I just tested out FirestoreListView page size is not working either it just loads the whole collection

**Comment by AlmogRnD** [comment] 2022-01-14 16:04
@rrousselGit here is minimal reproducible code as you requested, it's a brand new clean flutter project created with the flutter create CLI command. I just add the firebase packages and connected to Firestore. Make sure to run flutter pub get

As you can see it loads the entire collection even with page size set to 5, and loads everything from the being regardless of the user scroll please let me know if you need anything else. 

Project - https://drive.google.com/file/d/1GCBZwZtAFxVEaTns0MOne7A4Nb9H3vH8/view?usp=sharing

**Comment by rrousselGit** [comment] 2022-01-17 09:04
I see, I was able to reproduce the problem

The issue is with the way you're rendering the list. You are always rendering all items, even the items that aren't visible., as such this isn't a bug with FirestoreListView bug your code instead.

 In particular, the usage of `shrinkWrap` is a problem. Try refactoring your layout such that it isn't needed.
A solution for that is to wrap the ListView in an Expanded within your Column, and remove the unnecessary SingleChildScrollView/SizedBox ancestors:


```dart
 return Scaffold(
    appBar: AppBar(
      title: Text(widget.title),
    ),
    body: FirestoreQueryBuilder<Map<String, dynamic>>(
      pageSize: 5,
      query: dogsQuery,
      builder: (context, snapshot, _) {
        //print(snapshot.hasData);
        //print(snapshot.hasError);
        //print(snapshot.error);
        if (snapshot.hasData && !snapshot.hasError) {
          return Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              const Padding(
                padding: EdgeInsets.only(
                  top: 65.0,
                  left: 18.0,
                  right: 18.0,
                ),
              ),
              Expanded(
                child: ListView.builder(
                  padding: const EdgeInsets.only(
                    top: 5,
                    bottom: 20,
                    left: 15,
                    right: 15,
                  ),
                  physics: const NeverScrollableScrollPhysics(),
                  itemCount: snapshot.docs.length,
                  itemBuilder: (context, index) {
                    print('build index $index');
                    final isLastItem = index + 1 == snapshot.docs.length;
                    if (isLastItem && snapshot.hasMore) {
                      print('keeps fetching more');
                      snapshot.fetchMore();
                    }

                    final dog = snapshot.docs[index].data();
                    return SizedBox(
                        height: 100,
                        child: Text("$index + ${dog['dogName']}"));
                  },
                ),
              ),
            ],
          );
        }

        return const Text('return');
      },
    ),
    // This trailing comma makes auto-formatting nicer for build methods.
  );
}
```

**Comment by rrousselGit** [comment] 2022-01-17 09:05
I'll close this as it is not a bug with FirestoreListView after-all

**Closed by rrousselGit** 2022-01-17 09:05 UTC
Labels: type: bug, Needs Attention, in triage

**Comment by AlmogRnD** [comment] 2022-01-17 13:48
@rrousselGit thanks I had a feeling it had something to do with shrinkWrap unfortunately I need to keep the parent SingleChildScrollView it's used for the widgets above the list view but also the app bar to change the background color on user scroll.  

One thing I did not understand "You are always rendering all items, even the items that aren't visible." what do you mean how is this happing or why?

**Comment by AlmogRnD** [comment] 2022-01-17 16:52
@rrousselGit  found a good work around.

**Comment by rrousselGit** [comment] 2022-01-17 18:06
> One thing I did not understand "You are always rendering all items, even the items that aren't visible." what do you mean how is this happing or why?

That's because of shrinkWrap.
shrinkWrap makes the Listview render all of its items so that ListView can size itself accordingly

**Comment by AlmogRnD** [comment] 2022-01-17 18:10
@rrousselGit thanks I was just deep diving the docs on shrinkWrap, I also thought it just expand the height of the list view. FYI I just wrapped my SingleChildScrollView in a ConstrainedBox and give it  maxHeight: MediaQuery.of(context).size.height, then used the expanded widget.
