### ISSUE TITLE
[firebase_messaging] clear intent after onLaunch invoked on Android

### ISSUE THREAD

**Issue by ekasetiawans** [FirebaseExtended/flutterfire#1887] opened 2020-01-28 06:27 UTC
I launch application and route to another page (not main page) by tapping a notification successfully. But I have problem, after I finished that page and return to main page and then close my application by pressing back button. Then I return to application by pressing recents button (task manager). My application will reopened the page with latest notification data.

**To Reproduce**
1. Let application in background
2. send a notification
3. that will show another page when onLaunch or onResume invoked after notification tapped
4. return back to main page of your application
5. press back button or close application (dont close from task manager)
6. open application from task manager (not from home screen)
7. application will shows just like step 3.

**Expected behavior**
Just clear intent data after onLaunch or onResume invoked.

**Additional context**
I have try to add [`clearTaskOnLaunch`](https://developer.android.com/guide/topics/manifest/activity-element?hl=id#clear) in AndroidManifest.xml but it's not work.

**Comment by iapicca** [comment] 2020-01-30 09:04
Hi @ekasetiawans 
can you please provide your `flutter doctor -v` ,
your `flutter run --verbose` 
and if possible a reproducible minimal code sample.
Thank you

**Comment by VladimirKalinichenko** [comment] 2020-02-10 10:06
Hello @iapicca,
I am having similar issue. Here is my flutter doctor:

[✓] Flutter (Channel unknown, v1.9.1+hotfix.6, on Mac OS X 10.14.4 18E226,
    locale en-UA)
[✓] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Android Studio (version 3.5)
[✓] Connected device (1 available)

• No issues found!

----------------------------------------------------

I am using: 
  firebase_core:                  "0.4.0+9"
  firebase_messaging:       "5.1.8"

Android API 28

----------------------------------------------------

Sample code:

```
import 'dart:async';
import 'package:firebase_messaging/firebase_messaging.dart';
import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';

void main() => runApp(App());

class App extends StatefulWidget {
  @override
  _AppState createState() => _AppState();
}

class _AppState extends State<App> {
  @override
  void initState() {
    FirebaseMessaging().onTokenRefresh.listen((fcmToken) {
      print('token: $fcmToken');
    });
    FirebaseMessaging().configure(
      onLaunch: (Map<String, dynamic> message) {
        handleAppLaunchFromPush(message);
      },
    );
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(home: Scaffold(body: Center(child: const Text('The app'))));
  }
}

Future<void> handleAppLaunchFromPush(Map message) async {
  const url = 'https://github.com/FirebaseExtended/flutterfire/issues/1887';
  await launch(url, forceSafariVC: false, forceWebView: false);
}
```

----------------------------------------------------

Steps to reproduce:
1) Make sure app is not in memory;
2) Open app from push notification;
3) Close app by tapping back button;
4) Use overview button to open the app (by double tapping or tapping app, not app icon - opening app by tapping app icon will not reproduce the bug);
5) (Optional) Repeat

Expected behaviour:
App opens external browser when app is launched from push notification. Only once and only when open from push notification.

Actual behaviour:
App opens external browser when launched from push notification and keeps opening external browser every time app is open from android apps overview. In other words: Firebase's `onLaunch` method is called multiple times for one push notification open action.

**Comment by ekasetiawans** [comment] 2020-02-10 14:20
> Hi @ekasetiawans
> can you please provide your `flutter doctor -v` ,
> your `flutter run --verbose`
> and if possible a reproducible minimal code sample.
> Thank you

here is my flutter doctor :

```
ekasetiawans@MacBookPro retgoo_mobile_portal % flutter doctor -v
[✓] Flutter (Channel beta, v1.14.6, on Mac OS X 10.15.3 19D76, locale en-ID)
    • Flutter version 1.14.6 at /Users/ekasetiawans/Development/flutter
    • Framework revision fabeb2a16f (13 days ago), 2020-01-28 07:56:51 -0800
    • Engine revision c4229bfbba
    • Dart version 2.8.0 (build 2.8.0-dev.5.0 fc3af737c7)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ekasetiawans/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.2
    • ANDROID_HOME = /Users/ekasetiawans/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.3.1, Build version 11C504
    • CocoaPods version 1.8.4

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 43.0.1
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.42.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.8.1

[✓] Connected device (2 available)
    • Chrome     • chrome     • web-javascript • Google Chrome 80.0.3987.87
    • Web Server • web-server • web-javascript • Flutter Tools

• No issues found!
```

@VladimirKalinichenko sample is enough to reproduce the problem

**Comment by MaikuB** [comment] 2020-08-12 04:23
I submitted a PR for this

**Comment by joharputr** [comment] 2020-09-27 07:22
i have this issue too

**Comment by billbull21** [comment] 2020-12-30 03:33
> I submitted a PR for this

are you have fixed this bug? because, i still facing this issue. i want to clear intent data from firebase. because the data still firing even i have use it.

**Comment by MaikuB** [comment] 2020-12-30 03:50
@billbull21 the PR didn't get merged and got closed as there's a prerelease version with changes that should solve the issue

**Comment by billbull21** [comment] 2020-12-30 04:03
> @billbull21 the PR didn't get merged and got closed as there's a prerelease version with changes that should solve the issue

okeeyy,, i will try to edit the code by my self based on the change that you have done.
and i just have a try to your code, and still haven't solve the problem :(

i don't know what did you do on that change, but i was fixed the same issue from flutter deeplink. i think the way to solve the problem is same as deeplink. btw, thanks for the code.

it's my article : https://oemampedia.medium.com/how-to-do-deeplink-in-flutter-b0c9a7e1aa9d
i was confused to do the same thing on firebase.

thanks in advance

**Comment by billbull21** [comment] 2020-12-30 04:42
heyy,,, i simply resolve the problem by doing a change to the code below

uncomment this code in onNewIntent()
![image](https://user-images.githubusercontent.com/31173853/103330305-77790580-4a93-11eb-89fb-647c04700c80.png)

and combine with some code that did you made it.
![image](https://user-images.githubusercontent.com/31173853/103330350-ae4f1b80-4a93-11eb-9b17-17a92400c3cc.png)
the point of condition that we check is,, if the activity have a intent or not. we can simplify by doing like the code below 
```
if (mainActivity != null && mainActivity.getIntent() != null) {
     sendMessageFromIntent("onLaunch", mainActivity.getIntent());
 }
```

thanks in advance.

**Comment by billbull21** [comment] 2020-12-30 05:44
@MaikuB i have done the test from my own change. and,, it's work fine.

please, correct me if am wrong. at least the code was working well.

this is my full code

```
// Copyright 2017 The Chromium Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

package io.flutter.plugins.firebasemessaging;

import android.app.Activity;
import android.content.BroadcastReceiver;
import android.content.Context;
import android.content.Intent;
import android.content.IntentFilter;
import android.os.Bundle;
import android.util.Log;
import androidx.annotation.NonNull;
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.iid.FirebaseInstanceId;
import com.google.firebase.iid.InstanceIdResult;
import com.google.firebase.messaging.FirebaseMessaging;
import com.google.firebase.messaging.RemoteMessage;
import io.flutter.embedding.engine.plugins.FlutterPlugin;
import io.flutter.embedding.engine.plugins.activity.ActivityAware;
import io.flutter.embedding.engine.plugins.activity.ActivityPluginBinding;
import io.flutter.plugin.common.BinaryMessenger;
import io.flutter.plugin.common.MethodCall;
import io.flutter.plugin.common.MethodChannel;
import io.flutter.plugin.common.MethodChannel.MethodCallHandler;
import io.flutter.plugin.common.MethodChannel.Result;
import io.flutter.plugin.common.PluginRegistry.NewIntentListener;
import io.flutter.plugin.common.PluginRegistry.Registrar;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

/** FirebaseMessagingPlugin */
public class FirebaseMessagingPlugin extends BroadcastReceiver
    implements MethodCallHandler, NewIntentListener, FlutterPlugin, ActivityAware {

  private static final String CLICK_ACTION_VALUE = "FLUTTER_NOTIFICATION_CLICK";
  private static final String TAG = "FirebaseMessagingPlugin";

  private MethodChannel channel;
  private Context applicationContext;
  private Activity mainActivity;
  private Intent myIntent;

  public static void registerWith(Registrar registrar) {
    FirebaseMessagingPlugin instance = new FirebaseMessagingPlugin();
    instance.setActivity(registrar.activity());
    registrar.addNewIntentListener(instance);
    instance.onAttachedToEngine(registrar.context(), registrar.messenger());
  }

  private void onAttachedToEngine(Context context, BinaryMessenger binaryMessenger) {
    this.applicationContext = context;
    channel = new MethodChannel(binaryMessenger, "plugins.flutter.io/firebase_messaging");
    final MethodChannel backgroundCallbackChannel =
        new MethodChannel(binaryMessenger, "plugins.flutter.io/firebase_messaging_background");

    channel.setMethodCallHandler(this);
    backgroundCallbackChannel.setMethodCallHandler(this);
    FlutterFirebaseMessagingService.setBackgroundChannel(backgroundCallbackChannel);

    // Register broadcast receiver
    IntentFilter intentFilter = new IntentFilter();
    intentFilter.addAction(FlutterFirebaseMessagingService.ACTION_TOKEN);
    intentFilter.addAction(FlutterFirebaseMessagingService.ACTION_REMOTE_MESSAGE);
    LocalBroadcastManager manager = LocalBroadcastManager.getInstance(applicationContext);
    manager.registerReceiver(this, intentFilter);
  }

  private void setActivity(Activity flutterActivity) {
    this.mainActivity = flutterActivity;
  }

  @Override
  public void onAttachedToEngine(FlutterPluginBinding binding) {
    onAttachedToEngine(binding.getApplicationContext(), binding.getBinaryMessenger());
  }

  @Override
  public void onDetachedFromEngine(FlutterPluginBinding binding) {
    LocalBroadcastManager.getInstance(binding.getApplicationContext()).unregisterReceiver(this);
  }

  @Override
  public void onAttachedToActivity(ActivityPluginBinding binding) {
    binding.addOnNewIntentListener(this);
    this.mainActivity = binding.getActivity();
    this.myIntent = binding.getActivity().getIntent();
  }

  @Override
  public void onDetachedFromActivityForConfigChanges() {
    this.mainActivity = null;
    this.myIntent = null;
  }

  @Override
  public void onReattachedToActivityForConfigChanges(ActivityPluginBinding binding) {
    binding.addOnNewIntentListener(this);
    this.mainActivity = binding.getActivity();
  }

  @Override
  public void onDetachedFromActivity() {
    this.mainActivity = null;
    this.myIntent = null;
  }

  // BroadcastReceiver implementation.
  @Override
  public void onReceive(Context context, Intent intent) {
    String action = intent.getAction();

    if (action == null) {
      return;
    }

    if (action.equals(FlutterFirebaseMessagingService.ACTION_TOKEN)) {
      String token = intent.getStringExtra(FlutterFirebaseMessagingService.EXTRA_TOKEN);
      channel.invokeMethod("onToken", token);
    } else if (action.equals(FlutterFirebaseMessagingService.ACTION_REMOTE_MESSAGE)) {
      RemoteMessage message =
          intent.getParcelableExtra(FlutterFirebaseMessagingService.EXTRA_REMOTE_MESSAGE);
      Map<String, Object> content = parseRemoteMessage(message);
      channel.invokeMethod("onMessage", content);
    }
  }

  @NonNull
  private Map<String, Object> parseRemoteMessage(RemoteMessage message) {
    Map<String, Object> content = new HashMap<>();
    content.put("data", message.getData());

    RemoteMessage.Notification notification = message.getNotification();

    Map<String, Object> notificationMap = new HashMap<>();

    String title = notification != null ? notification.getTitle() : null;
    notificationMap.put("title", title);

    String body = notification != null ? notification.getBody() : null;
    notificationMap.put("body", body);

    content.put("notification", notificationMap);
    return content;
  }

  @Override
  public void onMethodCall(final MethodCall call, final Result result) {
    /*  Even when the app is not active the `FirebaseMessagingService` extended by
     *  `FlutterFirebaseMessagingService` allows incoming FCM messages to be handled.
     *
     *  `FcmDartService#start` and `FcmDartService#initialized` are the two methods used
     *  to optionally setup handling messages received while the app is not active.
     *
     *  `FcmDartService#start` sets up the plumbing that allows messages received while
     *  the app is not active to be handled by a background isolate.
     *
     *  `FcmDartService#initialized` is called by the Dart side when the plumbing for
     *  background message handling is complete.
     */
    if ("FcmDartService#start".equals(call.method)) {
      long setupCallbackHandle = 0;
      long backgroundMessageHandle = 0;
      try {
        @SuppressWarnings("unchecked")
        Map<String, Long> callbacks = ((Map<String, Long>) call.arguments);
        setupCallbackHandle = callbacks.get("setupHandle");
        backgroundMessageHandle = callbacks.get("backgroundHandle");
      } catch (Exception e) {
        Log.e(TAG, "There was an exception when getting callback handle from Dart side");
        e.printStackTrace();
      }
      FlutterFirebaseMessagingService.setBackgroundSetupHandle(mainActivity, setupCallbackHandle);
      FlutterFirebaseMessagingService.startBackgroundIsolate(mainActivity, setupCallbackHandle);
      FlutterFirebaseMessagingService.setBackgroundMessageHandle(
          mainActivity, backgroundMessageHandle);
      result.success(true);
    } else if ("FcmDartService#initialized".equals(call.method)) {
      FlutterFirebaseMessagingService.onInitialized();
      result.success(true);
    } else if ("configure".equals(call.method)) {
      FirebaseInstanceId.getInstance()
          .getInstanceId()
          .addOnCompleteListener(
              new OnCompleteListener<InstanceIdResult>() {
                @Override
                public void onComplete(@NonNull Task<InstanceIdResult> task) {
                  if (!task.isSuccessful()) {
                    Log.w(TAG, "getToken, error fetching instanceID: ", task.getException());
                    return;
                  }
                  channel.invokeMethod("onToken", task.getResult().getToken());
                }
              });
      if (myIntent != null) {
        if (mainActivity != null && !launchedActivityFromHistory(mainActivity.getIntent())) {
          sendMessageFromIntent("onLaunch", myIntent);
        }
      }
      result.success(null);
    } else if ("subscribeToTopic".equals(call.method)) {
      String topic = call.arguments();
      FirebaseMessaging.getInstance()
          .subscribeToTopic(topic)
          .addOnCompleteListener(
              new OnCompleteListener<Void>() {
                @Override
                public void onComplete(@NonNull Task<Void> task) {
                  if (!task.isSuccessful()) {
                    Exception e = task.getException();
                    Log.w(TAG, "subscribeToTopic error", e);
                    result.error("subscribeToTopic", e.getMessage(), null);
                    return;
                  }
                  result.success(null);
                }
              });
    } else if ("unsubscribeFromTopic".equals(call.method)) {
      String topic = call.arguments();
      FirebaseMessaging.getInstance()
          .unsubscribeFromTopic(topic)
          .addOnCompleteListener(
              new OnCompleteListener<Void>() {
                @Override
                public void onComplete(@NonNull Task<Void> task) {
                  if (!task.isSuccessful()) {
                    Exception e = task.getException();
                    Log.w(TAG, "unsubscribeFromTopic error", e);
                    result.error("unsubscribeFromTopic", e.getMessage(), null);
                    return;
                  }
                  result.success(null);
                }
              });
    } else if ("getToken".equals(call.method)) {
      FirebaseInstanceId.getInstance()
          .getInstanceId()
          .addOnCompleteListener(
              new OnCompleteListener<InstanceIdResult>() {
                @Override
                public void onComplete(@NonNull Task<InstanceIdResult> task) {
                  if (!task.isSuccessful()) {
                    Log.w(TAG, "getToken, error fetching instanceID: ", task.getException());
                    result.success(null);
                    return;
                  }

                  result.success(task.getResult().getToken());
                }
              });
    } else if ("deleteInstanceID".equals(call.method)) {
      new Thread(
              new Runnable() {
                @Override
                public void run() {
                  try {
                    FirebaseInstanceId.getInstance().deleteInstanceId();
                    if (mainActivity != null) {
                      mainActivity.runOnUiThread(
                          new Runnable() {
                            @Override
                            public void run() {
                              result.success(true);
                            }
                          });
                    }
                  } catch (IOException ex) {
                    Log.e(TAG, "deleteInstanceID, error:", ex);
                    if (mainActivity != null) {
                      mainActivity.runOnUiThread(
                          new Runnable() {
                            @Override
                            public void run() {
                              result.success(false);
                            }
                          });
                    }
                  }
                }
              })
          .start();
    } else if ("autoInitEnabled".equals(call.method)) {
      result.success(FirebaseMessaging.getInstance().isAutoInitEnabled());
    } else if ("setAutoInitEnabled".equals(call.method)) {
      Boolean isEnabled = (Boolean) call.arguments();
      FirebaseMessaging.getInstance().setAutoInitEnabled(isEnabled);
      result.success(null);
    } else {
      result.notImplemented();
    }
  }

  private static boolean launchedActivityFromHistory(Intent intent) {
    return intent != null
            && (intent.getFlags() & Intent.FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY)
            == Intent.FLAG_ACTIVITY_LAUNCHED_FROM_HISTORY;
  }
  
  @Override
  public boolean onNewIntent(Intent intent) {
    boolean res = sendMessageFromIntent("onResume", intent);
//    if (res && mainActivity != null) {
//      mainActivity.setIntent(intent);
//    }
    return res;
  }

  /** @return true if intent contained a message to send. */
  private boolean sendMessageFromIntent(String method, Intent intent) {
    if (CLICK_ACTION_VALUE.equals(intent.getAction())
        || CLICK_ACTION_VALUE.equals(intent.getStringExtra("click_action"))) {
      Map<String, Object> message = new HashMap<>();
      Bundle extras = intent.getExtras();

      if (extras == null) {
        return false;
      }

      Map<String, Object> notificationMap = new HashMap<>();
      Map<String, Object> dataMap = new HashMap<>();

      for (String key : extras.keySet()) {
        Object extra = extras.get(key);
        if (extra != null) {
          dataMap.put(key, extra);
        }
      }

      message.put("notification", notificationMap);
      message.put("data", dataMap);

      myIntent = null;
      channel.invokeMethod(method, message);
      return true;
    }
    return false;
  }
}
```

**Comment by russellwheatley** [comment] 2021-04-23 09:30
hey @ekasetiawans, can you confirm if this behaviour still exists? We're a few major versions removed since you created the issue. v`9.1.2`.

**Comment by russellwheatley** [comment] 2021-06-29 10:07
I'm going to close this issue due to a lack of response, but I believe this issue has been resolved now. Will reopen if this is not the case.

**Closed by russellwheatley** 2021-06-29 10:07 UTC
Labels: impact: customer, platform: android, plugin: messaging, type: bug
