### ISSUE TITLE
Social login usage links are broken

### ISSUE THREAD

**Issue by ElihuJ** [FirebaseExtended/flutterfire#6989] opened 2021-09-12 09:01 UTC
From documentation in : https://firebase.flutter.dev/docs/auth/usage/

Links for social login usage as: https://firebase.flutter.dev/docs/auth/usage/social#apple or any other one provided are broken

**Comment by markusaksli-nc** [comment] 2021-09-13 07:49
Duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6751

**Closed by markusaksli-nc** 2021-09-13 07:49 UTC
Labels: type: documentation, good first issue, in triage
