### ISSUE TITLE
🐛 [firebase_auth] Cannot use new Firebase Auth Emulator

### ISSUE THREAD

**Issue by radvansky-tomas** [FirebaseExtended/flutterfire#3980] opened 2020-10-28 19:43 UTC
I think before I've added it here https://github.com/FirebaseExtended/flutterfire/discussions/3969

But basically plugin does not export useEmulator() method to use new Firebase Auth Emulator Suite

**Comment by radvansky-tomas** [comment] 2020-11-02 20:18
I've checked code briefly, and its using outdated native SDKs to support it. I am expecting that there is upcoming version bump, so can revisit later ;)

**Comment by Ehesp** [comment] 2020-11-03 08:41
This requires a SDK version updated, however some of the other plugins will break if we upgrade the BoM versions. There are potential workarounds we're looking into and have discussed.

**Comment by celesteking** [comment] 2020-11-17 19:11
Discussed with whom and where? Is this a feature that's supported? If not, it makes worth noting in docs that Firebase Auth Emulator isn't supported in flutter yet. Thanks.

**Comment by mikehardy** [comment] 2020-11-18 14:17
@celesteking There is one emulator suite, it contains a new auth emulator. The emulator requires minimum firebase-ios-sdk version 7.0.0 (7.1.0 is current) and firebase-android-sdk 26.0.0 (26.1.0 is current as of now). You are likely aware Invertase is currently working hard on FlutterFire, with a crew of between 4-6 at any given time, and the discussions are internal because there is a mountain of work to do - prioritizing it and scheduling it is the same as in any other work project. 

Looks to me like the docs are open source, you could PR a note to them at any time? https://github.com/FirebaseExtended/flutterfire/tree/master/docs/auth

I'm going to be doing a quick sizing exercise on fastest path towards an upgrade to the underlying SDKs starting shortly now that I've finished doing the same for react-native-firebase (https://github.com/invertase/react-native-firebase/pull/4471) and if it's possible quickly then I'll add auth emulator support similar to the same I just released over there (https://github.com/invertase/react-native-firebase/pull/4552)

Hopefully it's quick work but I'm not sure of the size of forward port so it's hard to say.

We'll be sure to keep this issue updated though!

**Comment by yulkin2002** [comment] 2020-12-04 17:36
any news on auth emulator support?

**Comment by mikehardy** [comment] 2020-12-04 18:24
Yes, it "works"! :-), #4263 but it's a breaking change to forward port, which is something that needs to be done at a measured pace with great documentation and planning

Plus the 2 PRs that take the repo through the breaking change and to the auth emulator support are still very rough.

But it is open source, anyone can use my branch. There are only a few key commits that do the forward port (ML items, RemoteConfig, and one Messaging item if I recall correctly) so it's not that large a change really.

**Comment by braamgenis** [comment] 2020-12-04 19:37
@yulkin2002 
> also, can anyone suggest a good workaround without having to disable all the auth code in my app?

Using remote auth with local firestore/cloud functions emulators works, if that's what you mean?

**Comment by mikehardy** [comment] 2020-12-04 19:50
Well, not sure on the depth and breadth of the tests in question, but at least from a maintainer perspective where we are frequently doing full CI runs against the same firebase project, we run into Auth API call rate limiting that flakes our CI frequently. Plus it's not nearly as fast - so I do see the need and for some projects it is a fairly serious one, but until the work is done, having an "isCI()" type flag and/or only running specific auth tests manually against the real APIs is the way to go.

Another consideration is that perhaps through no fault of the developer they do not have a test project with separate data to run against, and running tests against production data is not allowed.

**Comment by yulkin2002** [comment] 2020-12-07 15:19
@braamgenis thank you! I didn't realize they would work together.

**Comment by alejandroaap** [comment] 2020-12-15 11:39
Any news about this functionality? Why do flutter sdks lag far behind native sdks?

**Comment by mikehardy** [comment] 2020-12-15 13:34
@alejandroaap I don't recall any feedback from you testing my PR to bring them up to date? I'd love to hear how it worked for you. Thanks!

**Comment by jans-y** [comment] 2020-12-15 15:15
@mikehardy Hi, I have tried it but I couldn't build the app afterwards.

Since auth emulator is supported AFAIK from Firebase iOS SDK 7.2.0 or newer, changing globally all my Firebase CocoaPods plugins to that version (I wasn't able to do it for the Auth Pod only) resulted in multiple Swift/Objective C errors when building the App for the simulator and device.

I think that Remote Config was one of those plugins that couldn't build with the new Firebase iOS SDK.

Thank you for your efforts.

**Comment by mikehardy** [comment] 2020-12-15 15:38
@jans-y that is unexpected, as remote-config was one of the items considered, and handled in the port https://github.com/FirebaseExtended/flutterfire/pull/4263/commits/ea18fd2309247100a5204e9ad3967f12bee0d8fe and I specifically added test harness powers that ensured they built and passed tests

https://github.com/FirebaseExtended/flutterfire/pull/4263/commits/cf1b55f7bdde6a11c9dd82943b0454897681a445#diff-cd98883b899aa4ad62ac6b5c5c3db5146fd0a5465749d4d3de63a77c525c04d3R20

https://github.com/FirebaseExtended/flutterfire/pull/4263/commits/cf1b55f7bdde6a11c9dd82943b0454897681a445#diff-cd98883b899aa4ad62ac6b5c5c3db5146fd0a5465749d4d3de63a77c525c04d3R43-R44

https://github.com/FirebaseExtended/flutterfire/pull/4263/commits/cf1b55f7bdde6a11c9dd82943b0454897681a445#diff-cd98883b899aa4ad62ac6b5c5c3db5146fd0a5465749d4d3de63a77c525c04d3R110-R111

All of which work locally for me.

I'm not saying the PR is perfect, but the problems you had are unexpected vs the specific changes I made, and I suspect something locally was cached or similar. I added a "clean:deep" target to hopefully work around that with `melos run clean:deep` https://github.com/FirebaseExtended/flutterfire/pull/4263/commits/34902db8e75f89954000b4048edec865fd9d50eb

It is also possible that the tip of the main branch has moved on in an incompatible way since I posted the PR for consideration. I haven't attempted to run it in the last few days.

**Comment by alejandroaap** [comment] 2020-12-15 16:07
@mikehardy I am trying to test your PR and I am having the following problem when running the application on an iphone.

packages / firebase_auth / firebase_auth / ios / Classes / FLTFirebaseAuthPlugin.m: 557: 9: error: not visible @interface for 'FIRAuth' declares the selector 'useEmulatorWithHost: port:'
       [auth useEmulatorWithHost: arguments [@ "host"] port: arguments [@ "port"]];

Any idea why it might be?

Thank you.

**Comment by mikehardy** [comment] 2020-12-15 16:16
Sure, for some reason the underlying firebase-ios-sdk version is not updated correctly. You must have 7.0.0 or greater, 7.3.0 is current as of this writing. Where ever you have it specified, update it to 7.3.0

**Comment by alejandroaap** [comment] 2020-12-15 16:38
You're right, that was the problem, when will the PR be completed? Thank you

**Comment by mikehardy** [comment] 2020-12-15 17:36
@alejandroaap I'm not sure as I'm not in control of that in any way, but seeing users request it, and validate that it is working can only help. Make sure you're subscribed to it and have given a thumbs-up reaction to the issue itself at the top - those are a bit like votes, perhaps ask others to do so

**Comment by mikehardy** [comment] 2020-12-15 17:37
Also perhaps subscribe / thumbs-up the PR itself :-)

**Comment by jlubeck** [comment] 2020-12-16 17:56
@mikehardy Will this also work for using the firestore emulator? or only for auth? Do we need a new ticket for firestore? Couldn't find any reference to that...

**Comment by mikehardy** [comment] 2020-12-16 18:00
I believe that firestore and functions emulators are already working and usable. You may see examples of their usage in the code base here if you look in the .github/workflows directory as they are used for the e2e tests that run against commits and PRs here.

**Comment by alejandroaap** [comment] 2020-12-16 18:01
Hi @jlubeck With firestore it's already possible to use the emulator. Take a look at the documentation https://firebase.flutter.dev/docs/firestore/usage

`// Import foundation for [TargetPlatform].
import 'package:flutter/foundation.dart';

// Switch host based on platform.
String host = defaultTargetPlatform == TargetPlatform.android
    ? '10.0.2.2:8080'
    : 'localhost:8080';

// Set the host as soon as possible.
FirebaseFirestore.instance.settings =
    Settings(host: host, sslEnabled: false);
`

**Comment by jlubeck** [comment] 2020-12-16 18:09
Yes! Thank you @mikehardy and @alejandroaap that indeed works.
Looking forward to the auth emulator support. I'll see if i can test out that PR in the meantime.

**Comment by jlubeck** [comment] 2020-12-16 19:39
Hey, how can I use that PR as my dependency?  Should I reference the latest commit on that PR?

**Comment by jlubeck** [comment] 2020-12-16 19:51
I added this to my `pubspec.yaml`

```yaml
dependency_overrides:
  firebase_auth:
    git:
      url: https://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_auth/firebase_auth
      ref: b125b30b0bcec0292ccd0268a9a634dd6b87de22
  firebase_auth_platform_interface:
    git:
      url: https://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_auth/firebase_auth_platform_interface
      ref: b125b30b0bcec0292ccd0268a9a634dd6b87de22
  firebase_auth_web:
    git:
      url: https://github.com/FirebaseExtended/flutterfire
      path: packages/firebase_auth/firebase_auth_web
      ref: b125b30b0bcec0292ccd0268a9a634dd6b87de22
```

Hopefully that's the proper way? I got the `useEmulator` now... testing it right now

**Comment by jlubeck** [comment] 2020-12-16 20:04
> @mikehardy I am trying to test your PR and I am having the following problem when running the application on an iphone.
> 
> `packages / firebase_auth / firebase_auth / ios / Classes / FLTFirebaseAuthPlugin.m: 557: 9: error: not visible @interface for 'FIRAuth' declares the selector 'useEmulatorWithHost: port:' [auth useEmulatorWithHost: arguments [@ "host"] port: arguments [@ "port"]]; `
> 
> Any idea why it might be?
> 
> Thank you.

I'm running into this same issue, but I haven't set the Podfile manually anywhere... shouldn't the PR automatically change whatever needs to be changed in the Podfile to make it work? 

How did you fix this @alejandroaap ?

Thanks!

**Comment by mikehardy** [comment] 2020-12-16 20:11
The firebase_core module should have changed it use. There are docs showing how to override it if you like as well. 7.3.0 is current

**Comment by jlubeck** [comment] 2020-12-16 20:14
> The firebase_core module should have changed it yes. There are docs showing how to override it if you like as well. 7.3.0 is current

Sorry, I'm not sure I understand (english is not my main language, sorry). So you are saying that just by implementing that PR into my overrides it SHOULD have changed the Podfile to make it work?

Because if that's the case, that's not working as intended...

**Comment by jlubeck** [comment] 2020-12-17 02:56
@mikehardy @alejandroaap I can't seem to find those docs explaining how to override the podfile to use 7.3.0. Would you be so kind to point me to them please? Thanks!

**Comment by mikehardy** [comment] 2020-12-17 03:18
Apologies, English is my first language but I am not always clear in it :-), also I have learned another language and I know how hard it can be even when things are clear, so I empathize. That said...

You should be able to override the versions - I think - by setting `FirebaseSDKVersion` in your Podfile, that is what the cocoapod .podspec files seem to be looking for: 

https://github.com/FirebaseExtended/flutterfire/blob/985b811f9c680836fe25de35ec3dfcf860610d65/packages/cloud_firestore/cloud_firestore/ios/cloud_firestore.podspec#L6-L9

**Comment by jlubeck** [comment] 2020-12-17 05:01
Hi @mikehardy thank you for that. I added that variable in my Podfile, but i'm getting this error on `pod install` or `pod update`

```
Analyzing dependencies
cloud_firestore: Using user specified Firebase SDK version '7.0.0'
firebase_analytics: Using user specified Firebase SDK version '7.0.0'
firebase_auth: Using user specified Firebase SDK version '7.0.0'
firebase_core: Using user specified Firebase SDK version '7.0.0'
firebase_messaging: Using user specified Firebase SDK version '7.0.0'
firebase_storage: Using user specified Firebase SDK version '7.0.0'
[!] CocoaPods could not find compatible versions for pod "firebase_auth":
  In Podfile:
    firebase_auth (from `.symlinks/plugins/firebase_auth/ios`)

Specs satisfying the `firebase_auth (from `.symlinks/plugins/firebase_auth/ios`)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by mikehardy** [comment] 2020-12-17 05:03
All ios deployment minimums are bumped to 10, corresponding changes are required in the podfile, should get past that

**Comment by jlubeck** [comment] 2020-12-17 05:25
Step by step... 😓

Now if I do `pod update` I get this

```
jan@Jans-MacBook-Pro ios % pod update


Update all pods
Updating local specs repositories
Analyzing dependencies
cloud_firestore: Using user specified Firebase SDK version '7.0.0'
firebase_analytics: Using user specified Firebase SDK version '7.0.0'
firebase_auth: Using user specified Firebase SDK version '7.0.0'
firebase_core: Using user specified Firebase SDK version '7.0.0'
firebase_messaging: Using user specified Firebase SDK version '7.0.0'
firebase_storage: Using user specified Firebase SDK version '7.0.0'
Downloading dependencies
Installing DKImagePickerController 4.3.2 (was 4.2.2)
Installing DKPhotoGallery 0.0.17 (was 0.0.14)
Installing Firebase 7.0.0 (was 6.33.0)
Installing FirebaseAnalytics 7.0.0 (was 6.8.3)

[!] Error installing FirebaseAnalytics
[!] /usr/bin/curl -f -L -o /var/folders/6d/7fb8q3_576358cs38040dm8h0000gn/T/d20201217-97653-1r0va28/file.tgz https://dl.google.com/firebase/ios/analytics/85d51ebb1b58f88f/FirebaseAnalytics-7.0.0.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (7) Failed to connect to dl.google.com port 443: Bad file descriptor
```

If I do `pod install` I get this:

```
jan@Jans-MacBook-Pro ios % pod install
Analyzing dependencies
cloud_firestore: Using user specified Firebase SDK version '7.0.0'
firebase_analytics: Using user specified Firebase SDK version '7.0.0'
firebase_auth: Using user specified Firebase SDK version '7.0.0'
firebase_core: Using user specified Firebase SDK version '7.0.0'
firebase_messaging: Using user specified Firebase SDK version '7.0.0'
firebase_storage: Using user specified Firebase SDK version '7.0.0'
[!] CocoaPods could not find compatible versions for pod "Firebase/Firestore":
  In snapshot (Podfile.lock):
    Firebase/Firestore (= 6.33.0, ~> 6.33.0)

  In Podfile:
    cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.4, which depends on
      Firebase/Firestore (~> 7.0.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `Firebase/Firestore` inside your development pod `cloud_firestore`.
   You should run `pod update Firebase/Firestore` to apply changes you've made.
```

**Comment by Pcol10** [comment] 2020-12-17 07:49
> Step by step... 😓
> 
> Now if I do `pod update` I get this
> 
> ```
> jan@Jans-MacBook-Pro ios % pod update
> 
> 
> Update all pods
> Updating local specs repositories
> Analyzing dependencies
> cloud_firestore: Using user specified Firebase SDK version '7.0.0'
> firebase_analytics: Using user specified Firebase SDK version '7.0.0'
> firebase_auth: Using user specified Firebase SDK version '7.0.0'
> firebase_core: Using user specified Firebase SDK version '7.0.0'
> firebase_messaging: Using user specified Firebase SDK version '7.0.0'
> firebase_storage: Using user specified Firebase SDK version '7.0.0'
> Downloading dependencies
> Installing DKImagePickerController 4.3.2 (was 4.2.2)
> Installing DKPhotoGallery 0.0.17 (was 0.0.14)
> Installing Firebase 7.0.0 (was 6.33.0)
> Installing FirebaseAnalytics 7.0.0 (was 6.8.3)
> 
> [!] Error installing FirebaseAnalytics
> [!] /usr/bin/curl -f -L -o /var/folders/6d/7fb8q3_576358cs38040dm8h0000gn/T/d20201217-97653-1r0va28/file.tgz https://dl.google.com/firebase/ios/analytics/85d51ebb1b58f88f/FirebaseAnalytics-7.0.0.tar.gz --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.10.0 cocoapods-downloader/1.4.0'
> 
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
> curl: (7) Failed to connect to dl.google.com port 443: Bad file descriptor
> ```
> 
> If I do `pod install` I get this:
> 
> ```
> jan@Jans-MacBook-Pro ios % pod install
> Analyzing dependencies
> cloud_firestore: Using user specified Firebase SDK version '7.0.0'
> firebase_analytics: Using user specified Firebase SDK version '7.0.0'
> firebase_auth: Using user specified Firebase SDK version '7.0.0'
> firebase_core: Using user specified Firebase SDK version '7.0.0'
> firebase_messaging: Using user specified Firebase SDK version '7.0.0'
> firebase_storage: Using user specified Firebase SDK version '7.0.0'
> [!] CocoaPods could not find compatible versions for pod "Firebase/Firestore":
>   In snapshot (Podfile.lock):
>     Firebase/Firestore (= 6.33.0, ~> 6.33.0)
> 
>   In Podfile:
>     cloud_firestore (from `.symlinks/plugins/cloud_firestore/ios`) was resolved to 0.14.4, which depends on
>       Firebase/Firestore (~> 7.0.0)
> 
> 
> You have either:
>  * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
>  * changed the constraints of dependency `Firebase/Firestore` inside your development pod `cloud_firestore`.
>    You should run `pod update Firebase/Firestore` to apply changes you've made.
> ```
1. Delete Podfile.lock
2. run `pod repo update`
3. Now you Can try again your stuff

**Comment by mikehardy** [comment] 2020-12-17 15:49
Indeed - those steps should work. Sorry for not having complete instructions on all this, I've been doing cocoapods just long enough that all these things are reflex for me now (pod repo update, deleting locks, reupdating etc) but I definitely remember when I first started with cocoapods and it was all foreign and I had no idea what to do. Quite frustrating. Thanks @Pcol10 for helping!

**Comment by jlubeck** [comment] 2020-12-17 15:50
I'm about to give up... :( 

Now I'm getting a bunch of other errors, for example:

```
/Users/jan/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-7.0.3/ios/Classes/FLTFirebaseMessagingPlugin.m:291:63: error: property 'appData' not found on object of type '__strong id'
      [_channel invokeMethod:@"onMessage" arguments:remoteMessage.appData];
```

**Comment by mikehardy** [comment] 2020-12-17 16:08
:thinking: that is unexpected, I will not hold it against you at all if you give up, PRs are always hard to integrate and test, I think the way Flutter works makes it even harder with the unified global pub-cache, and this PR in particular is still pretty speculative. So no worries, no expectations. 

I'm about to refresh the PRs against tip of main branch to make sure they are still "alive"/"fresh" and it's possible something diverged and is not working right now until that is done.

You might make sure you are using firebase-ios-sdk 7.3.0 just in case that matters.

**Comment by jlubeck** [comment] 2020-12-17 20:17
thank you for your constantn help @mikehardy unfortunately even after using 7.3.0, cleaning the flutter projects, the pod files, etc, I'm still getting that last error that I shared. It might be like you said a mix of things...

Unless @alejandroaap can chime in to show how he got his working (maybe he doesn't use other Firebase packages like I'm using?), I'm not sure what else to do but wait for further progress on those other tickets.

**Comment by radvansky-tomas** [comment] 2021-01-12 05:14
Any updates ? With latest updates and bumped SDKs it should be pretty straightforward to enable this, right ?

**Comment by mikehardy** [comment] 2021-01-12 12:20
PR #4263 contains all progress, follow that for updates.

I think it's close (as in, may be ready today? Maybe tomorrow?) but software is notoriously hard to predict yes? So could be longer.

All of the necessary pre-requisite work has been completed and merged though (that is: forward-porting across a breaking change version of the underlying firebase SDKs). That took a while.

**Comment by Tinhorn** [comment] 2021-01-12 17:08
This is amazing.
Thank you for all the hard work.
This will make my workflow so much better

**Comment by LucasHenriqueAbreu** [comment] 2021-01-13 13:07
Mine too

**Comment by mikehardy** [comment] 2021-01-13 14:40
@LucasHenriqueAbreu @Tinhorn head on over and test the PR then, it should be working fully now as of around 16 hours ago, there are instruction in the PR that show how to test it #4263

**Comment by deep-randhawa** [comment] 2021-02-09 22:41
@mikehardy any updates on this?

**Comment by mikehardy** [comment] 2021-02-09 22:48
Did you check the PR @deep-randhawa ? It's merged. I think it's even been cherry-picked to the stable branch. There will be no further updates, this should be closed, the work is done now.

**Comment by markusaksli-nc** [comment] 2021-02-11 12:30
I guess I'll close this as fixed then

**Closed by markusaksli-nc** 2021-02-11 12:30 UTC
Labels: impact: crowd, plugin: auth, type: enhancement

**Comment by sderungs99** [comment] 2021-02-12 06:45
Shouldn't there be documentation how to use it here (https://firebase.flutter.dev/docs/auth/usage), before we close this?

**Comment by markusaksli-nc** [comment] 2021-02-12 10:09
@sderungs99 Do you mean something like https://firebase.flutter.dev/docs/firestore/usage#emulator-usage?

I think you can go ahead and make a separate documentation issue for this.

**Comment by sderungs99** [comment] 2021-02-12 11:51
Yes, that's exactly what I meant :-) I'm happy to raise an issue, but before I do that, I'm still a bit confused in which exact version of firebase_auth this is available. I checked the PR that is referred above, but that didn't help. Anyone can advise?

**Comment by markusaksli-nc** [comment] 2021-02-12 12:56
It isn't in stable yet but it will be soon

https://github.com/FirebaseExtended/flutterfire/pull/4263#issuecomment-768767985
https://github.com/FirebaseExtended/flutterfire/pull/4263#issuecomment-772583441

**Comment by Yirmeyah-d** [comment] 2021-02-26 01:43
@jlubeck  Same here, did you find a solution ?

**Comment by Yirmeyah-d** [comment] 2021-02-26 02:03
Nevermind i just had to update the versions of the firebase packages that where in the pubspec.yaml.
And after this, everything worked fine

**Comment by wtfiwtz** [comment] 2021-03-01 20:52
PR #5171 fixes an issue with web

**Comment by mikehardy** [comment] 2021-03-01 20:55
@wtfiwtz yes! Thanks for cross-linking it here. It comes along with the need to update the firebase-js-sdk dependency which has a known issue with firestore, but those are all being tracked separately. auth.useEmulator has now been successfully tested (by me at least) on iOS/Android/Web
