### ISSUE TITLE
[cloud_firestore] Bug report form play console java.lang.NullPointerException

### ISSUE THREAD

**Issue by kepuza** [FirebaseExtended/flutterfire#2480] opened 2020-05-02 18:14 UTC
my version cloud_firestore 0.13.5

and google play console give this report

Samsung Galaxy S9 (starlte), 3840MB RAM, Android 10

```
java.lang.NullPointerException: 
  at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.a (CloudFirestorePlugin.java:106)
  at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.a (CloudFirestorePlugin.java:2)
  at com.google.firebase.firestore.DocumentReference.a (DocumentReference.java:87)
  at com.google.firebase.firestore.DocumentReference$$Lambda$3.a (DocumentReference.java:6)
  at com.google.firebase.firestore.core.AsyncEventListener.a (AsyncEventListener.java:6)
  at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run (AsyncEventListener.java:6)
  at android.os.Handler.handleCallback (Handler.java:883)
  at android.os.Handler.dispatchMessage (Handler.java:100)
  at com.google.android.gms.internal.tasks.zzb.dispatchMessage (zzb.java)
  at android.os.Looper.loop (Looper.java:237)
  at android.app.ActivityThread.main (ActivityThread.java:7811)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1076)
```

**Comment by iapicca** [comment] 2020-05-04 14:51
Hi @kepuza 
can you please provide your `flutter doctor -v` , 
your `flutter run --release --verbose` (on android 10 device),
and your `pubspec.yaml`  
Thank you

**Comment by kepuza** [comment] 2020-05-13 00:05
```
[√] Flutter (Channel stable, v1.17.0, on Microsoft Windows [Version 10.0.18362.836], locale tr-TR)
    • Flutter version 1.17.0 at C:\src\flutter
    • Framework revision e6b34c2b5c (10 days ago), 2020-05-02 11:39:18 -0700
    • Engine revision 540786dd51
    • Dart version 2.8.1


[√] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at C:\Users\cenky\AppData\Local\Android\Sdk
    • Platform android-R, build-tools 29.0.2
    • ANDROID_SDK_ROOT = C:\Users\cenky\AppData\Local\Android\Sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[!] Connected device
    ! No devices available

! Doctor found issues in 1 category.
```

```
environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  flutter_facebook_login: ^3.0.0
  firebase_admob: ^0.9.3+2
  google_sign_in: ^4.4.4
  firebase_database: ^3.1.5
  firebase_remote_config: ^0.3.0+3
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  firebase_messaging: ^6.0.13
  in_app_purchase: ^0.3.3+1
  geolocator: ^5.3.1
  geocoder: ^0.2.1
  shared_preferences: ^0.5.7+1
  http: ^0.12.1
  cached_network_image: ^2.2.0+1
  flutter_swiper: ^1.1.6
  url_launcher: ^5.4.5
  intl: ^0.16.0
  intl_translation: ^0.17.9
  cupertino_icons: ^0.1.3
  connectivity: ^0.4.8+5
  fluttertoast: ^4.0.1
  reorderables: ^0.3.2
  cupertino_range_slider: ^1.0.1
  google_maps_webservice: ^0.0.16
  sliding_up_panel: ^1.0.2
  share: ^0.6.4+1
  photo_view: ^0.9.2
  image_picker: ^0.6.6+1
  flutter_local_notifications: ^1.4.3
  flutter_speed_dial: ^1.2.5
  rxdart: ^0.24.0
  location_permissions: ^2.0.5
  app_settings: ^4.0.0
  shimmer: ^1.1.1
  package_info: ^0.4.0+17
  flutter_keyboard_visibility: ^2.0.0
  after_layout: ^1.0.7+2
  wakelock: ^0.1.4+1
  dots_indicator: ^1.1.0
  flutter_audio_recorder: ^0.5.5
  audioplayers: ^0.15.1
  path_provider: ^1.6.7
  file: ^5.1.0
  flutter_tts: ^1.2.0
  googleapis_auth: ^0.2.11+1
  googleapis: ^0.55.0
  get_ip: ^0.4.0
```

**Comment by andcea** [comment] 2020-05-13 18:21
I'm seeing the same error in Crashlytics for a few users

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.flutter.plugin.common.MethodChannel.invokeMethod(java.lang.String, java.lang.Object)' on a null object reference
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent(CloudFirestorePlugin.java:106)
       at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent(CloudFirestorePlugin.java:2)
       at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2(DocumentReference.java:87)
       at com.google.firebase.firestore.DocumentReference$$Lambda$3.onEvent(DocumentReference.java:6)
       at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0(AsyncEventListener.java:6)
       at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run(AsyncEventListener.java:6)
       at android.os.Handler.handleCallback(Handler.java:873)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:226)
       at android.app.ActivityThread.main(ActivityThread.java:7208)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:499)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:942)
```

**Comment by kepuza** [comment] 2020-05-13 21:07
and i have this Exception

```
java.lang.NullPointerException: 
  at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent (CloudFirestorePlugin.java)
  at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent (CloudFirestorePlugin.java)
  at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent (CloudFirestorePlugin.java)
  at io.flutter.plugins.firebase.cloudfirestore.CloudFirestorePlugin$DocumentObserver.onEvent (CloudFirestorePlugin.java)
  at com.google.firebase.firestore.DocumentReference.addSnapshotListener (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.addSnapshotListener (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.addSnapshotListenerInternal (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.delete (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.forPath (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.get (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.internalOptions (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2 (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.lambda$get$0 (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1 (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.set (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.set (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.update (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference.update (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference$$Lambda$3.lambdaFactory$ (DocumentReference.java)
  at com.google.firebase.firestore.DocumentReference$$Lambda$3.onEvent (DocumentReference.java)
  at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0 (AsyncEventListener.java)
  at com.google.firebase.firestore.core.AsyncEventListener.mute (AsyncEventListener.java)
  at com.google.firebase.firestore.core.AsyncEventListener.onEvent (AsyncEventListener.java)
  at com.google.firebase.firestore.core.AsyncEventListener$$Lambda$1.run (AsyncEventListener.java)
  at android.os.Handler.handleCallback (Handler.java:836)
  at android.os.Handler.dispatchMessage (Handler.java:103)
  at com.google.android.gms.internal.tasks.zzb.dispatchMessage (zzb.java)
  at android.os.Looper.loop (Looper.java:203)
  at android.app.ActivityThread.main (ActivityThread.java:6251)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1063)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:924)
```

**Comment by TahaTesser** [comment] 2020-05-19 12:39
Hi @kepuza 
To better address the issue, would be helpful if you could post a minimal code sample to reproduce the problem with `cloud_firestore` and `firebase_core`  and not with other third party packages 
Thank you

**Comment by kepuza** [comment] 2020-05-19 20:50
I think I got the problem. I first understood how, When you press the back button on the main page, the application goes down and gives this error when the application is activated again.

I fixed with this plugins [https://pub.dev/packages/move_to_background](https://pub.dev/packages/move_to_background)

I dont know this right way ?

**Comment by TahaTesser** [comment] 2020-05-20 11:57
Hi @andcea 
That's not the solution but since you've provided any code sample 
I am closing duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2390

**Closed by TahaTesser** 2020-05-20 11:57 UTC

**Comment by andcea** [comment] 2020-05-20 13:17
@TahaTesser not sure what solution you're referring to.
I haven't provided a code sample because I haven't been able to reproduce the error, but I'm getting emails from Crashlytics and a lot of my users are experiencing crashes because of this error.

**Comment by TahaTesser** [comment] 2020-05-20 13:39
@a14n 
accidentally tagged you
