### ISSUE TITLE
Can't stop show notification when the app is foreground.

### ISSUE THREAD

**Issue by shinewanna** [FirebaseExtended/flutterfire#5752] opened 2021-04-13 15:59 UTC
## Bug report

**Describe the bug**
I use turn on and off notification feature. in firebase_messaging: ^7.0.3 version, it's work well but not work in ^8.0.0-dev.15.
I can't stop showing foreground notification. 

^7.0.3 registerNotification
```dart
  void registerNotification() {
    firebaseMessaging.configure(
      onMessage: (Map<String, dynamic> message) async {
        showNotification(message);
      },
      onBackgroundMessage: Platform.isIOS ? null : myBackgroundMessageHandler,
      onLaunch: (Map<String, dynamic> message) async {
        onSelectNotification(jsonEncode(message));
      },
      onResume: (Map<String, dynamic> message) async {
        onSelectNotification(jsonEncode(message));
      },
    );
    firebaseMessaging.getToken().then(_addToken);
  }

```

^8.0.0-dev.15 registerNotification.
```dart
  void registerNotification() async {
    //Can't stop showing foreground notification
    FirebaseMessaging.onMessage.listen((RemoteMessage message) {
      showNotification(message.notification);
    });
    
    FirebaseMessaging.onBackgroundMessage(myBackgroundMessageHandler);

    firebaseMessaging.getToken().then(_addToken);
  }
```

I manage to stop notification from showNotification function, in version 8 , foreground notification is showing notification itself not from my showNotificaion function.

Platform: Android

**Comment by markusaksli-nc** [comment] 2021-04-14 08:30
Hi @shinewanna
Does the issue persist on the latest version of the package?
Could you provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example)?
Could you please provide your `flutter doctor -v` and `flutter pub deps -- --style=compact`?
Thank you

**Comment by shinewanna** [comment] 2021-04-14 08:51
I can't update the plugin to latest one cause of package conflict. So i use ^8.0.0-dev.15 for fixing conflict.
Simple way to reproduce the issue bro.
Create a new project and use firebase_messaging with ^8.0.0-dev.15, and u'll see, it won't work as except but work as excepted in version 7.0.3

**Comment by markusaksli-nc** [comment] 2021-04-14 09:20
So do you mean that the `onMessage` stream doesn't fire when the event is received or what? I have no idea what your `showNotification` method does. Checking this with the official example the stream fires and it shows a local notification with the specified parameters so I'm not sure what exactly you are referring to here.

**Comment by shinewanna** [comment] 2021-04-14 10:43
yes onMessage doesn't listen foreground notification, it show itself
showNotification method is just showing the title and body with LocalNotification plugin.

**Comment by markusaksli-nc** [comment] 2021-04-14 10:51
So the official example doesn't work for you either?

https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib

Have you tried adding a print to make sure the issue is the stream?

**Comment by shinewanna** [comment] 2021-04-23 03:59
> So the official example doesn't work for you either?
> 
> https://github.com/FirebaseExtended/flutterfire/tree/master/packages/firebase_messaging/firebase_messaging/example/lib
> 
> Have you tried adding a print to make sure the issue is the stream?

Yes, i printed in stream, it's only showing in app notification print. 

Now, i updated to firebase and flutter latest version. My question is how i make a switch to showing notification and stop showing notification.

**Comment by markusaksli-nc** [comment] 2021-04-23 09:03
So the stream is receiving notifications? I don't really understand the question here. If you don't show the notification in the local notifications high importance channel it will not show up.

**Comment by shinewanna** [comment] 2021-04-23 10:59
The stream is not receiving foreground notification. It's receiving only in app notification. Foreground notification is shown by itself, it's not streamming from onMessage. So foreground notification is not using my local notification method. Do u understand my problem sir? 

I know the things is stop showing notification from onMessage stream but in app is foreground it's not using my local notification. Firebase shown by itself. I don't know how to explain more. Plz create new project and try to stop foreground notification then u'll know.

**Comment by markusaksli-nc** [comment] 2021-04-23 12:32
As mentioned before it would be really helpful if you could provide [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example) to demonstrate the exact issue.

**Comment by shinewanna** [comment] 2021-04-24 14:43
Finally, i found the bug, onMessage is calling and firebase is showing itself notification also.
So the notifications are appearing twice in android.
When i stop showing from onMessage, the default one is always showing. That's what i have as bug, please fix the the issue. Firebase is sending and showing itself and send from onMessage also. It's only happen in foreground.

**Comment by markusaksli-nc** [comment] 2021-04-26 13:57
As I mentioned the foreground notification is only shown as a heads up notification if you use the high priority notification channel. You still have not provided a complete code sample to demonstrate the issue and there is no such issue with the official example.

You need to provide some actual code that demonstrates this double notification issue.

**Comment by shinewanna** [comment] 2021-04-27 06:56
You can see, two notifications from below screenshot. I just send the from UI one time but it appear from onMessage once and itself once.
![179025959_564250967880530_4003083390494264297_n](https://user-images.githubusercontent.com/39454969/116197292-93976580-a75a-11eb-8f2a-0e6f331c771d.jpg)

UI, just click floating action button and go to the foreground. I added delay 2 second, you can go foreground gently. In app notification is work well. My raised problem is foreground problem, please keep that in mind.
![177286629_909240556287046_8169003367747372895_n](https://user-images.githubusercontent.com/39454969/116197537-e4a75980-a75a-11eb-8002-56d361ba74c1.jpg)

Add your google-sevice.json and add Firebase Messaging Server Token in app-constant as i show from below screenshot. Replace the serverToken key to yours.
![Screen Shot 2021-04-27 at 1 11 35 PM](https://user-images.githubusercontent.com/39454969/116197979-67c8af80-a75b-11eb-9325-9a5fe5faa7d0.png)

And I don't have that much time to quickly reproduce the problem, I want to reproduce the good sample code, so it takes time, I hope you'll understand. Now, sample project is done. You can fetch the code from my github. Github sample project link is [https://github.com/shinewanna/github-page-test](here).

**Comment by markusaksli-nc** [comment] 2021-04-27 12:45
I ran the code you provided with 
```yaml
environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^1.1.0
  firebase_messaging: ^9.1.3
  flutter_local_notifications: ^5.0.0+1
  dio: ^4.0.0
  shared_preferences: ^2.0.5
```
<details>
 <summary>flutter doctor -v</summary>

```
[√] Flutter (Channel master, 2.3.0-1.0.pre.104, on Microsoft Windows [Version 10.0.19041.928], locale et-EE)
    • Flutter version 2.3.0-1.0.pre.104 at C:\Development\flutter_master
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 6338bc0288 (3 hours ago), 2021-04-27 05:59:01 -0400
    • Engine revision 019a49948e
    • Dart version 2.14.0 (build 2.14.0-46.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7199119
    • Flutter plugin version 55.1.1
    • Dart plugin version 201.9380
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] IntelliJ IDEA Ultimate Edition (version 2021.1)
    • IntelliJ at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\IDEA-U\ch-0\211.6693.111
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.928]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 90.0.4430.85
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 90.0.818.46

• No issues found!
```
</details>

Only one notification is shown.

Could you try it with the latest version of the package? What device is this happening on?

**Comment by shinewanna** [comment] 2021-04-27 14:37
All of my devices receiving two notifications, please test properly. Did you click the send button and go to foreground like below gif. If you are in app, notification will show properly, but show twice in foreground, check from below link.
[Gif Link](https://im2.ezgif.com/tmp/ezgif-2-68fe2f8dd3dd.gif)

**Comment by markusaksli-nc** [comment] 2021-04-27 14:43
Oh well that finally explains the issue. You meant go to **background** not foreground. Since you are calling the `showNotification` function in the background message handler it is showing the notification twice. 

If you wish to only show the notification using the local notification package (not sure why you would do this, you can customize the notification using the payload itself, but its up to you) then you can remove the `notification` part of the payload and just use the `data` to send a title and body to use in the local notification package.

Closing this since the package is working as expected here.

**Closed by markusaksli-nc** 2021-04-27 14:43 UTC
Labels: Needs Attention, type: bug

**Comment by shinewanna** [comment] 2021-04-27 14:52
Hay, my question is I want to stop and start show notification by switch button. What i need is, I want to show notification with switch. the notification should not show, when user switch off the notification. I can only done with local notification, that's why i use local notification for switch off and on the notification. I hope u'll understand.

**Comment by markusaksli-nc** [comment] 2021-04-27 15:00
There are a couple of ways this can be done without having to use local notifications. The FCM HTTP v1 API has a `condition` send destination that you can use to define some boolean logic for if you want to send the notification at all or not.

https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

It's also possible to just use subscribing to topics and unsubscribing from them for this logic. Another way is if you use Cloud Functions to send notifications with some more advanced logic you can add some conditional logic in your function to determine whether to send a notification to a user or not.

The point is: Don't send the notification to the user at all if they don't want to receive it.

The package (and the native Firebase SDKs that define the behavior of it) are designed to receive these notifications unless the device permissions have blocked them.

**Comment by shinewanna** [comment] 2021-04-27 15:43
Ok, can i know more of other.
```dart
 _firebaseMessaging.sendMessage(to:'token');
```
there's a sendMessage, use for what.
I'm not sure. Is this send fcm notification without calling custom api call?
