### ISSUE TITLE
[firebase_messaging] Push message in background not handle

### ISSUE THREAD

**Issue by kaparray** [FirebaseExtended/flutterfire#1623] opened 2019-12-12 16:28 UTC
**Push message in background not handle**

I can't it turns out to intercept the message from the native in the application!

```bash
2019-12-12 18:51:34.487 19465-19645/com.example.push_demo E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method FcmDartService#initialized on channel plugins.flutter.io/firebase_messaging_background)
    #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
    <asynchronous suspension>
    #1      _fcmSetupBackgroundChannel (package:firebase_messaging/firebase_messaging.dart:50:21)
    #2      _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:45:6)
    #3      _fcmSetupBackgroundChannel (package:firebase_messaging/firebase_messaging.dart:23:32)
    #4      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:239:25)
    #5      _rootRun (dart:async/zone.dart:1126:13)
    #6      _CustomZone.run (dart:async/zone.dart:1023:19)
    #7      _runZoned (dart:async/zone.dart:1518:10)
    #8      runZoned (dart:async/zone.dart:1502:12)
    #9      _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:231:5)
    #10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:307:19)
    #11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:174:12)

```

Flutter:

flutter doctor -v
```bash
[✓] Flutter (Channel stable, v1.12.13+hotfix.5, on Mac OS X 10.15.1 19B88, locale en-GB)
    • Flutter version 1.12.13+hotfix.5 at /Users/admin/development/flutter
    • Framework revision 27321ebbad (2 days ago), 2019-12-10 18:15:01 -0800
    • Engine revision 2994f7e1e6
    • Dart version 2.7.0


[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at /Users/admin/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.2.1, Build version 11B500
    • CocoaPods version 1.8.4

[✓] Android Studio (version 3.5)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 39.0.3
    • Dart plugin version 191.8593
    • Java version OpenJDK Runtime Environment (build 1.8.0_202-release-1483-b49-5587405)

[✓] VS Code (version 1.40.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.7.1

[✓] Connected device (1 available)
    • iPhone (Kirill) • 01cc842b27ce459bd7f99be356d88688bdce0eec • ios • iOS 13.3

• No issues found!

```

**Comment by iapicca** [comment] 2019-12-13 13:51
possible duplicate of https://github.com/FirebaseExtended/flutterfire/issues/1558

**Comment by helenaford** [comment] 2020-04-27 11:23
closing this, duplicate of #116

**Closed by helenaford** 2020-04-27 11:23 UTC
Labels: type: bug
