### ISSUE TITLE
[firebase_messaging] set notification channel id (notification in background Not working)

### ISSUE THREAD

**Issue by MahmoodBakhshayesh** [FirebaseExtended/flutterfire#88] opened 2019-09-04 07:01 UTC
**Describe the bug**
the function onResume and onLunch not working on android platform, while they work fine on IOS,
i receive the following message on console instead of printed strings in those functions:

"W/FirebaseMessaging(24847): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used."

onMessage function works fine, the problem is when the app is in background

**To Reproduce**
try to print something in onResume and onLunch functions

**Expected behavior**
the functions be called on work fine as they do on IOS

**Additional context**
my guess is that it has something to do with android notification channel id which should be added in android manifest

when i add that to manifest the message change to :
"Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be `used."`

**Comment by kroikie** [comment] 2019-09-04 18:52
@MahmoodBakhshayesh Thanks for flagging this, looks like we don't currently have support for message channels. We should add this.

**Comment by KingWu** [comment] 2019-11-01 06:26
Any clear documents to setup firebase messaging?
I follow 5.1.6 instruction. Facing the above issue

**Comment by Masaokb** [comment] 2019-11-05 03:17
Any updates?

**Comment by digarahayu** [comment] 2019-11-25 11:46
Any update for this issue..? 
or it will be fix when stable version updated???

**Comment by hiuryanderson** [comment] 2019-12-04 21:42
Any update for this issue..?

**Comment by JemZubiri-Projects** [comment] 2019-12-11 07:22
Any updates for this?

**Comment by iapicca** [comment] 2020-01-28 08:34
Hi all
are you still experiencing the issue with the latest stable version of flutter 
and the latest version of firebase_messaging?
thank you

**Comment by Navil** [comment] 2020-03-08 18:34
Is there any update for this issue?

**Comment by bhanuka96** [comment] 2020-03-09 04:28
any update?

**Comment by EzequielMoroni** [comment] 2020-03-11 23:48
Did someone find a workaround for this issue? Thanks

**Comment by faldunate** [comment] 2020-03-18 00:56
Does anyone have a solution?

**Comment by fl-oe** [comment] 2020-03-23 19:51
I had the problem that the method registered with "onBackgroundMessage" was not called. Here I found that if the message sent from my Nodejs backend had a "notification" entity, the "onBackgroundMessage" was not called. Only the "data" entity may be contained here.

Wrong way:
```
const message = {
  token: 'myToken',
  notification:{
    title: 'My Title',
    body: 'The body data',
  },
  data: {
    time: 'My data',
    value: '2',
  }
}
 ```

Right way:
```
const message = {
  token: 'myToken',
  data: {
    time: 'My data',
    value: '2',
  }
}
 ```

If I send the "right way" message, background function will be called.

It could be the solution for #1269

**Comment by ajnaf** [comment] 2020-04-07 01:43
adding this to my sent data worked for me
 'click_action': 'FLUTTER_NOTIFICATION_CLICK'

**Comment by iapicca** [comment] 2020-04-08 11:43
Hi @MahmoodBakhshayesh 
did @ajnaf solution worked for you?
Thank you

**Comment by ayush221b** [comment] 2020-04-21 14:33
Hey, I am also facing the same issue. I can confirm that:


> adding this to my sent data worked for me
> 'click_action': 'FLUTTER_NOTIFICATION_CLICK'

does not solve this issue.

**Comment by Ehesp** [comment] 2020-04-22 07:59
Hello, just to give some insight on this.

That message is a information message only. If no channel is specified via your Android manifest then FCM creates & uses it's own notification channel (since they're required in later Android versions). The channel is only used to impact how the notification is shown - from memory this is a default priority notification with sound enabled.

If you created a custom channel (via https://pub.dev/packages/flutter_local_notifications for example), you could specify that channel ID in the manifest and the notification would use your custom one.

If you provide a channel ID to the notification and it doesn't exist on the device, FCM falls back to it's own channel (and you see that message).

Our plan is to make this more user-friendly to work with, however for now you can safely ignore this message. I'll leave open to track though.

**Comment by ayush221b** [comment] 2020-04-22 12:20
@Ehesp As you mentioned if no channel is specified then FCM should create and use its own notification channel, hence while sending the notification to the app, if we do not include an Android Notification Channel param then the it should be attributed to the default channel that FCM has created, but that that is not the case. When I do not specify any custom notification channel in my project and send a notification without the Android Notification Channel param even then I get this error when the app is not in foreground.

**Comment by Ehesp** [comment] 2020-04-22 12:39
@ayush221b it's not an error, it's just a message from FCM telling you it's using it's own channel. You can get around this for now by creating your own channel and assigning the channel ID to the message body when you send it from the server.

**Comment by ayush221b** [comment] 2020-04-22 12:43
@Ehesp I agree that it's just a warning, but then it shouldn't stop the onResume and onLaunch callbacks from executing right? But when the app is not in foreground, we get this warning/message and the onResume and onLaunch callbacks do not execute.

**Comment by azheennn** [comment] 2020-05-31 18:48
> I had the problem that the method registered with "onBackgroundMessage" was not called. Here I found that if the message sent from my Nodejs backend had a "notification" entity, the "onBackgroundMessage" was not called. Only the "data" entity may be contained here.
> 
> Wrong way:
> 
> ```
> const message = {
>   token: 'myToken',
>   notification:{
>     title: 'My Title',
>     body: 'The body data',
>   },
>   data: {
>     time: 'My data',
>     value: '2',
>   }
> }
> ```
> 
> Right way:
> 
> ```
> const message = {
>   token: 'myToken',
>   data: {
>     time: 'My data',
>     value: '2',
>   }
> }
> ```
> 
> If I send the "right way" message, background function will be called.
> 
> It could be the solution for #1269

hello, i've deleted the the notification and it still doesnt read my onbackgroundmessagehandler, what do i do

**Comment by QuentinSc** [comment] 2020-07-12 14:51
Hello,

I've reading a lot of comments since 6 months and still cannot figure out how to make onBackgroundMessage working. 
OnLaunch, OnResume and OnMessage works perfectly. 
If onBackgroundMessage still not working I will have to change framework :(

Someone successed to deal with it ? A sample app ?

Thanks you

**Comment by Gperez88** [comment] 2020-08-04 20:00
still happen!

**Comment by yourshinsuke** [comment] 2020-08-06 09:43
```
Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be used.
```
what is this??

Should I add there???

`android/app/src/main/AndroidManifest.xml`
`android/app/src/main/res/values/strings.xml`

`android/app/build.gradle`
`implementation 'com.google.firebase:firebase-messaging:20.1.5'`

```
android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java
```

document is useless

**Comment by yourshinsuke** [comment] 2020-08-06 09:43
`default_notification_channel_id` is needed? what ID???

**Comment by yourshinsuke** [comment] 2020-08-06 09:43
https://pub.dev/packages/firebase_messaging

**Comment by deep01code** [comment] 2020-08-07 01:50
@yourshinsuke please if you found the solution share it with me,,, I am not Android developer and I followed the documentation and unfortunately, I am struggling with very badly with the code..... PLEASE IF ANYONE CAN SHARE THE SOLUTION I WILL BE SO THANKFUL

**Comment by NoeLopez** [comment] 2020-08-07 03:05
My English is not perfect, but I solved it by adding a channel natively and then in the manifest where it says channel id I put the id of my channel created natively

**Comment by deep01code** [comment] 2020-08-07 03:48
@NoeLopez  thanks for your replay, can you please share your code ... thanks again

**Comment by NoeLopez** [comment] 2020-08-07 04:03
Yes of course,

In the Application file that flutter recommends you add a globar variable that will be the name of your id channel, for example

`public static final String CHANNEL_HIGH = "channel1";`

where channel1 is the id channel, then you create a method like the following

`private void createNotificationChannels() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channelHigh = new NotificationChannel(
                    CHANNEL_HIGH,
                    "Notificación Importante",
                    NotificationManager.IMPORTANCE_HIGH
            );

            channelHigh.setDescription("Canal Alto");

            NotificationManager manager = getSystemService(NotificationManager.class);
            manager.createNotificationChannel(channelHigh);

        }
    }`

where `Notificacion Importante` is the name that will appear in the notification settings on the cell phone, then add I'm in the AndroidManifest

`<application
        android:name=".Application"
        android:icon="@mipmap/ic_launcher"
        android:label="NotificacionPush">

        <activity
            android:name=".MainActivity" ...
           .......






<meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="channel1"/>

</application>`

Note that in android:value it must be the name of the channel ID, which you created in your public variable in the application class

**Comment by NoeLopez** [comment] 2020-08-07 04:12
Yes of course,

In the Application file that flutter recommends you add a globar variable that will be the name of your id channel, for example

`public static final String CHANNEL_HIGH = "channel1";`

where channel1 is the id channel, then you create a method like the following

```
private void createNotificationChannels() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            NotificationChannel channelHigh = new NotificationChannel(
                    CHANNEL_HIGH,
                    "Notificación Importante",
                    NotificationManager.IMPORTANCE_HIGH
            );

            channelHigh.setDescription("Canal Alto");

            NotificationManager manager = getSystemService(NotificationManager.class);
            manager.createNotificationChannel(channelHigh);

        }
    }
```

where `Notificacion Importante` is the name that will appear in the notification settings on the cell phone, then add I'm in the AndroidManifest

```
<application
        android:name=".Application"
        android:icon="@mipmap/ic_launcher"
        android:label="NotificacionPush">

        <activity
            android:name=".MainActivity" ...
           .......


   <meta-data
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="channel1"/>

</application>
```

Note that in android:value it must be the name of the channel ID, which you created in your public variable in the application class.

and with that the notifications will come out with bubble

**Comment by deep01code** [comment] 2020-08-07 04:14
@NoeLopez thank you so much I spent 2 days trying to solve this issue and I will try to use your solution, I really appreciate your kind replay and wish all the best.

**Comment by bhanuka96** [comment] 2020-08-07 04:16
I am facing the same issue and also this issue https://stackoverflow.com/q/63271091/8822337 (please check this too)

**Comment by NoeLopez** [comment] 2020-08-07 04:23
@bhanuka96 If you want to submit a group, you need to subscribe to a topic, in the documentation that mentions it, you would no longer send a single token, but would instead subscribe to a topic and submit it to that topic.

**Comment by bhanuka96** [comment] 2020-08-07 04:27
@NoeLopez are you sure? is it only support for topic? okay, but how group notification works on like whatsapp/gmail?

**Comment by NoeLopez** [comment] 2020-08-07 04:30
@bhanuka96 Do you mean that notifications are grouped when they arrive?

**Comment by deep01code** [comment] 2020-08-07 04:34
@NoeLopez  I still get this error :(
`W/FirebaseMessaging( 6367): Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be used.
`

**Comment by bhanuka96** [comment] 2020-08-07 04:34
> @bhanuka96 Do you mean that notifications are grouped when they arrive?

yes like this https://developer.android.com/training/notify-user/group . if "A" user sent multiple messages to the "B" user. currently, there are lots of notifications came to in my notification panel, I want to group notification for that. (it's mean like above image like gmail/whatsapp). if "C" user sent multiple message to the "B user". I want to 2 groups

**Comment by NoeLopez** [comment] 2020-08-07 04:38
@bhanuka96 Those types of implementations would have to be done with Local Notification

**Comment by NoeLopez** [comment] 2020-08-07 04:40
@deep01code It would be nice to be able to see your code to see where it goes wrong, remember to add it in Java class and in Android Manifest

**Comment by bhanuka96** [comment] 2020-08-07 04:45
> @bhanuka96 Those types of implementations would have to be done with Local Notification

I tried, not working on foreground or background... I saw this react native answer about same issue. I think this part of the firebase_messaging plugin right? https://github.com/invertase/react-native-firebase/issues/449#issuecomment-404701979

**Comment by NoeLopez** [comment] 2020-08-07 04:49
@bhanuka96 Apparently it seems like if it's a Firebase issue I'm really sorry I can't help you

**Comment by braysonjohn148** [comment] 2020-08-07 05:38
I followed exactly the tutorials on youtube on how to setup these notification, they don't do these staffs but they get notifications when the app is teriminated. I don't know what wrong with my code.

`firebase_messaging: ^6.0.16`

_backgroundMessageHandler i even tried calling FlutterLocalNotificationsPlugin, still don't show notifications when the app is terminated.

`<meta-data
                android:name="com.google.firebase.messaging.default_notification_icon"
                android:resource="@mipmap/ic_launcher" />
            <meta-data
                    android:name="com.google.firebase.messaging.android.channel_id"
                    android:value="mmne" />

            <meta-data android:name="com.google.firebase.messaging.default_notification_channel_id" android:value="@string/default_notification_channel_id"/>
             `

**Comment by NoeLopez** [comment] 2020-08-07 06:09
@braysonjohn148 If want to be notified in your app (via `onResume` and `onLaunch`, see below) when the user clicks on a notification in the system tray include the following `intent-filter` within the `<activity>` tag of your `android/app/src/main/AndroidManifest.xml:`

 ```
<intent-filter>
      <action android:name="FLUTTER_NOTIFICATION_CLICK" />
      <category android:name="android.intent.category.DEFAULT" />
  </intent-filter>
```

Optionally handle background messages

> Background message handling is intended to be performed quickly. Do not perform long running tasks as they may not be allowed to finish by the Android system

By default background messaging is not enabled. To handle messages in the background:

1) Add the `com.google.firebase:firebase-messaging` dependency in your app-level `build.gradle` file that is typically located at `<app-name>/android/app/build.gradle.`

```
dependencies {
  // ...

  implementation 'com.google.firebase:firebase-messaging:20.2.4'
}
```

you can find out what the latest version of the plugin is [here](https://firebase.google.com/support/release-notes/android#latest_sdk_versions)

2) Add an `Application.java` class to your app in the same directory as your `MainActivity.java.` This is typically found in <`app-name>/android/app/src/main/java/<app-organization-path>/.`

```
package com.domain.myapplication;

import io.flutter.app.FlutterApplication;
import io.flutter.plugin.common.PluginRegistry;
import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
import io.flutter.plugins.GeneratedPluginRegistrant;
import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;

public class Application extends FlutterApplication implements PluginRegistrantCallback {
  @Override
  public void onCreate() {
    super.onCreate();
    FlutterFirebaseMessagingService.setPluginRegistrant(this);
  }

  @Override
  public void registerWith(PluginRegistry registry) {
 FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
  }
}
```

3) In `Application.java`, make sure to change `package com.domain.myapplication`; to your package's identifier. Your package's identifier should be something like com.domain.myapplication for your application package

4) Set name property of application in `AndroidManifest.xml.` This is typically found in `<app-name>/android/app/src/main/.`

`<application android:name=".Application" ...>`

and the json that sends from Postman or from firebase in the data part has to go this, very important 

`"click_action": "FLUTTER_NOTIFICATION_CLICK"`

Aquí hay un ejemplo del cuerpo de un JSON que debe enviarse desde Postman

```
{
  "notification": {
    "body": "here you put the body of the message",
    "title": "here you put some title"
  },
  "priority": "high",
  "data": {
    "click_action": "FLUTTER_NOTIFICATION_CLICK",
    "other_data": "any message",
    .....
  },
  "to": "your token ......"
}
```

Hope this answer can help you solve your problem. Regards

**Comment by braysonjohn148** [comment] 2020-08-07 06:31
what i want is when an app is completely terminated. Meaning the phone is either in the pocket or user on other apps. When a new notification arrives the user to get a push notification even when the app is terminated. Currently when i close the app and send the notification. I cannot see the notification in the system tray. I even tried using the firebase console FCM to fire test messages on my app

**Comment by NoeLopez** [comment] 2020-08-07 06:37
@braysonjohn148 that is done in the onLaunch method (it is when the app has closed completely) and onResume is when the app is in the background, you just have to implement there the actions you want it to do

**Comment by amegodev** [comment] 2020-08-19 01:07
> @braysonjohn148 If want to be notified in your app (via `onResume` and `onLaunch`, see below) when the user clicks on a notification in the system tray include the following `intent-filter` within the `<activity>` tag of your `android/app/src/main/AndroidManifest.xml:`
> 
> ```
> <intent-filter>
>      <action android:name="FLUTTER_NOTIFICATION_CLICK" />
>      <category android:name="android.intent.category.DEFAULT" />
>  </intent-filter>
> ```
> 
> Optionally handle background messages
> 
> > Background message handling is intended to be performed quickly. Do not perform long running tasks as they may not be allowed to finish by the Android system
> 
> By default background messaging is not enabled. To handle messages in the background:
> 
> 1. Add the `com.google.firebase:firebase-messaging` dependency in your app-level `build.gradle` file that is typically located at `<app-name>/android/app/build.gradle.`
> 
> ```
> dependencies {
>   // ...
> 
>   implementation 'com.google.firebase:firebase-messaging:20.2.4'
> }
> ```
> 
> you can find out what the latest version of the plugin is [here](https://firebase.google.com/support/release-notes/android#latest_sdk_versions)
> 
> 1. Add an `Application.java` class to your app in the same directory as your `MainActivity.java.` This is typically found in <`app-name>/android/app/src/main/java/<app-organization-path>/.`
> 
> ```
> package com.domain.myapplication;
> 
> import io.flutter.app.FlutterApplication;
> import io.flutter.plugin.common.PluginRegistry;
> import io.flutter.plugin.common.PluginRegistry.PluginRegistrantCallback;
> import io.flutter.plugins.GeneratedPluginRegistrant;
> import io.flutter.plugins.firebasemessaging.FlutterFirebaseMessagingService;
> 
> public class Application extends FlutterApplication implements PluginRegistrantCallback {
>   @Override
>   public void onCreate() {
>     super.onCreate();
>     FlutterFirebaseMessagingService.setPluginRegistrant(this);
>   }
> 
>   @Override
>   public void registerWith(PluginRegistry registry) {
>  FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
>   }
> }
> ```
> 
> 1. In `Application.java`, make sure to change `package com.domain.myapplication`; to your package's identifier. Your package's identifier should be something like com.domain.myapplication for your application package
> 2. Set name property of application in `AndroidManifest.xml.` This is typically found in `<app-name>/android/app/src/main/.`
> 
> `<application android:name=".Application" ...>`
> 
> and the json that sends from Postman or from firebase in the data part has to go this, very important
> 
> `"click_action": "FLUTTER_NOTIFICATION_CLICK"`
> 
> Aquí hay un ejemplo del cuerpo de un JSON que debe enviarse desde Postman
> 
> ```
> {
>   "notification": {
>     "body": "here you put the body of the message",
>     "title": "here you put some title"
>   },
>   "priority": "high",
>   "data": {
>     "click_action": "FLUTTER_NOTIFICATION_CLICK",
>     "other_data": "any message",
>     .....
>   },
>   "to": "your token ......"
> }
> ```
> 
> Hope this answer can help you solve your problem. Regards

Thank you you save my day 😍😍

**Comment by yourshinsuke** [comment] 2020-08-24 06:25
```
W/FirebaseMessaging(17333): Missing Default Notification Channel metadata in AndroidManifest. Default value will be used.
```

**Comment by yourshinsuke** [comment] 2020-08-24 06:41
```
E/FlutterFcmService(18015): Fatal: failed to find callback
```

**Comment by fazil-augr** [comment] 2020-09-01 15:28
same issue is facing from me also

**Comment by danilomna** [comment] 2020-09-01 18:03
> Yes of course,
> 
> In the Application file that flutter recommends you add a globar variable that will be the name of your id channel, for example
> 
> `public static final String CHANNEL_HIGH = "channel1";`
> 
> where channel1 is the id channel, then you create a method like the following
> 
> ```
> private void createNotificationChannels() {
>         if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
>             NotificationChannel channelHigh = new NotificationChannel(
>                     CHANNEL_HIGH,
>                     "Notificación Importante",
>                     NotificationManager.IMPORTANCE_HIGH
>             );
> 
>             channelHigh.setDescription("Canal Alto");
> 
>             NotificationManager manager = getSystemService(NotificationManager.class);
>             manager.createNotificationChannel(channelHigh);
> 
>         }
>     }
> ```
> 
> where `Notificacion Importante` is the name that will appear in the notification settings on the cell phone, then add I'm in the AndroidManifest
> 
> ```
> <application
>         android:name=".Application"
>         android:icon="@mipmap/ic_launcher"
>         android:label="NotificacionPush">
> 
>         <activity
>             android:name=".MainActivity" ...
>            .......
> 
> 
>    <meta-data
>             android:name="com.google.firebase.messaging.default_notification_channel_id"
>             android:value="channel1"/>
> 
> </application>
> ```
> 
> Note that in android:value it must be the name of the channel ID, which you created in your public variable in the application class.
> 
> and with that the notifications will come out with bubble

Hi @NoeLopez , does this solve the onBackgroundMessage callback issue? Could you help with a full project example on github?

**Comment by danilomna** [comment] 2020-09-01 18:08
Does anybody found a workaround or fix to make onBackgroundMessage work?

**Comment by danilomna** [comment] 2020-09-02 01:29
> @NoeLopez I still get this error :(
> `W/FirebaseMessaging( 6367): Notification Channel set in AndroidManifest.xml has not been created by the app. Default value will be used. `

hi @deep01code  have you found a fix for this issue? It is not working for me too.

**Comment by yourshinsuke** [comment] 2020-09-10 08:44
What is this?

[6.0.13] Missing Default Notification Channel metadata in AndroidManifest #2266
Missing Default Notification Channel metadata in AndroidManifest. Default value will be used #343

**Comment by Stone2517** [comment] 2020-09-11 08:58
@yourshinsuke 

In order to get ride of this, you need to create android notification channel to your app.

Go to this link for more details -- https://developer.android.com/training/notify-user/channels

I have uploaded to Github repository -- https://github.com/Stone2517/Truact-1

AndroidManifest.xml
```
<application>
      <activity>
           .........
      </activity>
      <meta-data. 
            android:name="com.google.firebase.messaging.default_notification_channel_id"
            android:value="@string/default_notification_channel_id"/>  ----- Add this.
 </application>
```

Application.java
```
public class Application extends FlutterApplication implements PluginRegistrantCallback {
    @Override
    public void onCreate() {
        super.onCreate();
        this.createChannel();   ----- Add this.
        FlutterFirebaseMessagingService.setPluginRegistrant(this);
    }

    @Override
    public void registerWith(PluginRegistry registry) {
        io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin.registerWith(registry.registrarFor("io.flutter.plugins.firebasemessaging.FirebaseMessagingPlugin"));
        PathProviderPlugin.registerWith(registry.registrarFor("io.flutter.plugins.pathprovider.PathProviderPlugin"));
    }
    private void createChannel(){   ----- Add this.
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            // Create the NotificationChannel
            String name = getString(R.string.default_notification_channel_id);
            NotificationChannel channel = new NotificationChannel(name, "default", NotificationManager.IMPORTANCE_HIGH);
            NotificationManager notificationManager = (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);
            notificationManager.createNotificationChannel(channel);
        }
    }
}
```
string.xml
```
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <string name="default_notification_channel_id">default_notification_channel_id</string>  ----- Add this.
</resources>
```

**Comment by Stone2517** [comment] 2020-09-11 09:03
> E/FlutterFcmService(18015): Fatal: failed to find callback

 **reinstall the App**

**Comment by Salakar** [comment] 2020-11-04 15:58
Hey all 👋 

As part of our roadmap (#2582) we've just shipped a complete rework of the `firebase_messaging` plugin that aims to solve this and many other issues. 

If you can, please try out the dev release (see the [migration guide](https://firebase.flutter.dev/docs/migration/) for upgrading and for changes) and if you have any feedback then join in the discussion [here](https://github.com/FirebaseExtended/flutterfire/discussions/4023).

Given the scope of the rework I'm going to go ahead and close this issue in favor of trying out the latest plugin.

Thanks everyone 🤓

**Closed by Salakar** 2020-11-04 15:58 UTC
Labels: impact: crowd, platform: android, plugin: messaging, type: documentation, type: enhancement
