### ISSUE TITLE
Expose Firebase Storage's new ability to list files in Flutter

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#1077] opened 2019-10-13 19:37 UTC
The Firebase SDKs for Cloud Storage recently added the ability to list files in the storage bucket ([Android](https://firebase.google.com/docs/storage/android/list-files), [iOS](https://firebase.google.com/docs/storage/ios/list-files)). It would be great if this functionality were also available in the `firebase_storage` Flutter plugin.

**Comment by kroikie** [comment] 2019-10-13 19:37
@puf

The issue at https://github.com/flutter/flutter/issues/39054 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by BondarenkoStas** [comment] 2019-10-21 14:35
Duplicate of #83

**Closed by BondarenkoStas** 2019-10-21 14:35 UTC
