### ISSUE TITLE
Firebase Auth - OTP SMS no longer working

### ISSUE THREAD

**Issue by ISimplifyComplexity** [FirebaseExtended/flutterfire#2769] opened 2020-06-16 09:40 UTC
**Describe the bug**

**To Reproduce**
I've followed your example for the firebase auth. I'm trying to send an OTP to the phone. It worked the first time for my phone however after adding it. Tried to call signout on the phone 

``` dart 
FirebaseAuth.instance.signOut()
```
 I've deleted the account on firebase waited 24 hours and tried again. 

When I run the following: 

```dart 

await auth
        .verifyPhoneNumber(
            phoneNumber: phoneNumber,
            timeout: Duration(seconds: 60),
            verificationCompleted: verificationCompleted,
            verificationFailed: verificationFailed,
            codeSent: codeSent,
            codeAutoRetrievalTimeout: codeAutoRetrievalTimeout)
        .catchError((error) => {
              print(error),
            });
```

The OTP is not sent to my phone number. It simply goes to verificationCompleted. I then try to get the user info like so: 

```
  void verificationCompleted(AuthCredential phoneAuthCredential) async {
    var user = await FirebaseAuth.instance.currentUser();
    print("complted");
  }

```
however I only get null returned. 

**Expected behavior**
The current user should not be null or the OTP should be resent.

**Additional context**
The strange thing is that it worked the first time and does not work after that for my device. If I enter my friends iPhone he gets the OTP and I'm able to enter in his OTP on my phone and that works reliably. However my android phone does not re-send the OTP nor does it return a current user. It just jumps to verification completed.

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
[√] Flutter (Channel beta, 1.19.0-4.1.pre, on Microsoft Windows [Version 10.0.18363.900], locale en-GB)
    • Flutter version 1.19.0-4.1.pre at D:\Repos\Flutter\demo\flutter
    • Framework revision f994b76974 (6 days ago), 2020-06-09 15:53:13 -0700
    • Engine revision 9a28c3bcf4
    • Dart version 2.9.0 (build 2.9.0-14.1.beta)


[√] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
    • Android SDK at C:\Users\\zebco\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.0
    • ANDROID_HOME = C:\Users\\zebco\AppData\Local\Android\sdk
    • Java binary at: C:\Users\zebco\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6514223\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Android Studio (version 4.0)
    • Android Studio at C:\Users\zebco\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\193.6514223
    • Flutter plugin version 46.0.2
    • Dart plugin version 193.7361
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] VS Code, 64-bit edition (version 1.45.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.11.0

[√] Connected device (1 available)
    • ONEPLUS A5010 • 790d7a64 • android-arm64 • Android 9 (API 28)
```

**Console Output**

I noticed the below printing in my console window:

```terminal
W/FlutterActivity(23270): Tried to automatically register plugins with FlutterEngine (io.flutter.embedding.engine.FlutterEngine@c6ce3c0) but could not find and invoke the GeneratedPluginRegistrant.
Connecting to VM Service at ws://127.0.0.1:65403/ApKXATXqZ_I=/ws
W/IInputConnectionWrapper(23270): getTextBeforeCursor on inactive InputConnection
W/IInputConnectionWrapper(23270): getSelectedText on inactive InputConnection
W/IInputConnectionWrapper(23270): getTextAfterCursor on inactive InputConnection
I/BiChannelGoogleApi(23270): [FirebaseAuth: ] getGoogleApiForMethod() returned Gms: com.google.firebase.auth.api.internal.zzaq@abdc575
W/avalcade.bogot(23270): Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)

```

screenshot: 

![image](https://user-images.githubusercontent.com/4026553/84786032-1ea8ba80-afe4-11ea-813d-e4ef73ad2792.png)

**Comment by TahaTesser** [comment] 2020-06-16 13:15
duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2766

**Comment by ISimplifyComplexity** [comment] 2020-06-16 13:25
@TahaTesser actually this is not the same issue! It's different!

**Comment by Ehesp** [comment] 2020-06-29 12:21
When the `verificationCompleted` callback is called, it only gives a credential rather than logging the user in. You need to pass that credential to `signInWithCredential` or `linkWithCredential`.

**Comment by ISimplifyComplexity** [comment] 2020-07-06 15:10
@Ehesp thanks but the problem was that it just stop sending OTPs etc... even when the account was deleted on firebase. 

I just gave up with this in the end. I might revisit it later. I'm using Twilio now. It's more expensive but it seems to be reliable.

**Comment by shashwatadi** [comment] 2020-08-08 20:25
Same issue. Phone auth is broken.

**Comment by shashwatadi** [comment] 2020-08-08 20:32
Unhandled Exception: PlatformException(ERROR_SESSION_EXPIRED, The sms code has expired. Please re-send the verification code to try again., null)

Interestingly, there are issues not using flutter too. Like this: [](https://stackoverflow.com/questions/51747899/firebase-phone-authentication-not-working-for-own-device)

**Comment by Ehesp** [comment] 2020-08-25 14:41
Hi All,

With the latest update this should be working as intended. For more information on how to handle phone auth, see https://firebase.flutter.dev/docs/auth/phone

**Closed by Ehesp** 2020-08-25 14:41 UTC
Labels: blocked: customer-response, plugin: auth, resolution: needs-repro, type: bug
