### ISSUE TITLE
🐛 [Firebase] error: 'Firebase/Firebase.h' file not found #import <Firebase/Firebase.h> flutter

### ISSUE THREAD

**Issue by Bavon101** [FirebaseExtended/flutterfire#4835] opened 2021-01-28 06:48 UTC
## Bug report

**Describe the bug**
I migrated to ` firebase_messaging: ^8.0.0-dev.14` but it works great on android but on ios in throws this error,
` error: 'Firebase/Firebase.h' file not found #import <Firebase/Firebase.h> flutter`, when in run or build the app

### Steps to reproduce

1. upgrade to `firebase_core: ^0.7.0` and `firebase_messaging: ^8.0.0-dev.14`
2. add awesome notification package `awesome_notifications: ^0.0.5+4`
3.run pod install
4.build the app on ios 

### Expected behavior
```
This error will be thrown `error: 'Firebase/Firebase.h' file not found #import <Firebase/Firebase.h> flutter`
Xcode error
`Error output from Xcode build:
↳
    2021-01-28 09:42:26.651 xcodebuild[28598:201660] warning:  The file reference for "Firebase-iOS12.0.debug.xcconfig" is a member of multiple groups
    ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership
    in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    2021-01-28 09:42:26.651 xcodebuild[28598:201660] warning:  The file reference for "Firebase-iOS12.0.release.xcconfig" is a member of multiple groups
    ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership
    in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
    2021-01-28 09:42:26.651 xcodebuild[28598:201660] warning:  The file reference for "../Firebase-iOS14.3/Firebase-iOS14.3.debug.xcconfig" is a member of
    multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved
    (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the
    same path.
    2021-01-28 09:42:26.651 xcodebuild[28598:201660] warning:  The file reference for "../Firebase-iOS14.3/Firebase-iOS14.3.release.xcconfig" is a member of
    multiple groups ("Support Files" and "Support Files"); this indicates a malformed project.  Only the membership in one of the groups will be preserved
    (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the
    same path.
    2021-01-28 09:42:30.577 xcodebuild[28598:201660] [MT] DVTAssertions: Warning in
    /Library/Caches/com.apple.xbs/Sources/IDEPlugins_XCBuildSupport/IDEPlugins-17709/XCBuildSupport/XCBuildSupport/PIFGeneration/IDEPIFGenerationCategories.
    swift:193
    Details:  Could not find object with type target and signature TARGET@v11_hash=e29bbf2efdbca560dffe3b6f884eeb03
    Function: pifObjectsIncrementally(_:)
    Thread:   <NSThread: 0x7fd720e0a9e0>{number = 1, name = main}
    Please file a bug at https://feedbackassistant.apple.com with this warning message and any useful information you can provide.
    ** BUILD FAILED **`
Firebase error:
`In file included from
    /Users/air/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-8.0.0-dev.14/ios/Classes/FLTFirebaseMessagingPlugin.m:9:
    /Users/air/Documents/flutter/.pub-cache/hosted/pub.dartlang.org/firebase_messaging-8.0.0-dev.14/ios/Classes/FLTFirebaseMessagingPlugin.h:11:9: fatal
    error: 'Firebase/Firebase.h' file not found
    #import <Firebase/Firebase.h>
            ^~~~~~~~~~~~~~~~~~~~~`
```

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on Mac OS X 10.15.7 19H15 darwin-x64, locale en-KE)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

! Doctor found issues in 1 category.
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.5
Flutter SDK 1.22.6
moovn3 1.0.0+1

dependencies:
- animated_text_kit 3.1.0 [flutter characters]
- awesome_notifications 0.0.5+5 [flutter platform intl]
- cupertino_icons 1.0.0
- dio 3.0.10 [http_parser path]
- ez_flutter 0.5.2 [flutter flutter_localizations logging basic_utils global_configuration rxdart shared_preferences json_annotation]
- firebase_core 0.7.0 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_messaging 8.0.0-dev.14 [meta flutter firebase_core firebase_core_platform_interface firebase_messaging_platform_interface firebase_messaging_web]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- flutter_credit_card 0.1.4 [flutter]
- flutter_datetime_picker 1.5.0 [flutter]
- flutter_dialogs 1.1.0 [flutter]
- flutter_facebook_login 3.0.0 [flutter collection]
- flutter_launcher_icons 0.8.1 [image args yaml path]
- flutter_polyline_points 0.2.4 [flutter http]
- flutter_rating_bar 3.2.0+1 [flutter]
- flutter_signin_button 1.1.0 [flutter font_awesome_flutter]
- flutter_spinkit 4.1.2+1 [flutter]
- flutter_svg 0.19.1 [flutter meta path_drawing vector_math xml]
- flutter_webview_plugin 0.3.11 [flutter]
- fluttertoast 7.1.6 [flutter flutter_web_plugins]
- geocoder 0.2.1 [meta flutter]
- geolocator 6.1.14 [flutter geolocator_platform_interface]
- get_version 0.2.2 [flutter package_info]
- giffy_dialog 1.8.0 [flutter flare_flutter]
- google_fonts 1.1.2 [flutter http path_provider crypto]
- google_maps_flutter 1.0.10 [flutter flutter_plugin_android_lifecycle google_maps_flutter_platform_interface]
- google_maps_webservice 0.0.19 [http meta]
- http 0.12.2 [http_parser path pedantic]
- image_picker 0.6.7+21 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- in_app_update 1.1.15 [flutter]
- intl 0.16.1 [path]
- intl_phone_number_input 0.5.2+2 [flutter meta libphonenumber equatable]
- location 3.2.4 [flutter location_platform_interface location_web meta]
- lottie 0.7.0+1 [archive characters charcode collection flutter logging meta path vector_math]
- otp_text_field 1.0.2 [flutter]
- page_transition 1.1.7+6 [flutter]
- path_provider 1.6.27 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- progress_dialog 1.2.4 [flutter]
- provider 4.3.3 [collection flutter nested]
- searchable_dropdown 1.1.3 [flutter]
- share 0.6.5+4 [meta mime flutter]
- shared_preferences 0.5.12+4 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- stripe_payment 1.0.9 [flutter]
- upgrader 2.8.2 [flutter device_info flutter_device_locale http package_info shared_preferences url_launcher version xml]
- url_launcher 5.7.10 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- uuid 2.2.2 [crypto convert]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- archive 2.0.13 [crypto args path]
- args 1.6.0
- asn1lib 0.6.5
- async 2.5.0-nullsafety.1 [collection]
- basic_utils 2.6.3 [http logging json_annotation pointycastle asn1lib convert crypto]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- device_info 1.0.0 [flutter device_info_platform_interface]
- device_info_platform_interface 1.0.1 [flutter meta plugin_platform_interface]
- equatable 1.2.5 [collection meta]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase_core_platform_interface 3.0.1 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+3 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- firebase_messaging_platform_interface 1.0.0-dev.10 [flutter meta firebase_core plugin_platform_interface]
- firebase_messaging_web 0.1.0-dev.5 [flutter flutter_web_plugins meta firebase_core firebase_core_web firebase_messaging_platform_interface js service_worker]
- flare_dart 2.3.4
- flare_flutter 2.0.6 [flutter flare_dart meta]
- flutter_device_locale 0.4.0 [flutter flutter_web_plugins plugin_platform_interface]
- flutter_localizations 0.0.0 [flutter intl characters collection meta path typed_data vector_math]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- font_awesome_flutter 8.11.0 [flutter]
- geolocator_platform_interface 1.0.8 [flutter meta plugin_platform_interface vector_math]
- global_configuration 1.6.0 [flutter http]
- google_maps_flutter_platform_interface 1.0.5 [flutter meta plugin_platform_interface stream_transform]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image 2.1.19 [archive xml meta]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- js 0.6.2
- json_annotation 3.0.1
- libphonenumber 1.0.2 [flutter meta]
- location_platform_interface 1.1.0 [flutter meta plugin_platform_interface]
- location_web 1.0.1 [flutter flutter_web_plugins http_parser js location_platform_interface meta]
- logging 0.11.4
- matcher 0.12.10-nullsafety.1 [stack_trace]
- meta 1.3.0-nullsafety.3
- mime 0.9.7
- nested 0.0.4 [flutter]
- package_info 0.4.3+2 [flutter]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+8 [flutter]
- path_provider_platform_interface 1.0.4 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+3 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- pointycastle 1.0.2
- process 3.0.13 [file intl meta path platform]
- quiver 2.1.5 [matcher meta]
- rxdart 0.24.1
- service_worker 0.2.4 [js]
- shared_preferences_linux 0.0.2+4 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+11 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.2+2 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- stream_transform 1.2.0
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- typed_data 1.3.0-nullsafety.3 [collection]
- url_launcher_linux 0.0.1+4 [flutter]
- url_launcher_macos 0.0.1+9 [flutter]
- url_launcher_platform_interface 1.0.9 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.5+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+3 [flutter]
- vector_math 2.1.0-nullsafety.3
- version 1.2.0
- win32 1.7.4 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]
- yaml 2.2.1 [charcode collection string_scanner source_span]
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-01-28 10:29
Hi @Bavon101 
FlutterFire is not responsible for compatibility with third-party plugins that make use of the plugins.
Please consider opening an issue in https://github.com/rafaelsetragni/awesome_notifications/issues
Closing since this is not an issue with `firebase_messaging` itself.
Thank you

**Closed by markusaksli-nc** 2021-01-28 10:29 UTC
Labels: Needs Attention, type: bug

**Comment by Bavon101** [comment] 2021-01-28 11:03
> Hi @Bavon101
> FlutterFire is not responsible for compatibility with third-party plugins that make use of the plugins.
> Please consider opening an issue in https://github.com/rafaelsetragni/awesome_notifications/issues
> Closing since this is not an issue with `firebase_messaging` itself.
> Thank you

The error  points to  `firebase_messaging`

**Comment by markusaksli-nc** [comment] 2021-01-28 11:18
If the issue is still there without `awesome_notifications` this might be the case but the official example runs perfectly fine on the latest master `1.26.0-13.0.pre.231` with only
```yaml
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^0.7.0
  firebase_messaging: ^8.0.0-dev.14
  flutter_local_notifications: ^3.0.3
  http: ^0.12.2
```
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 1.26.0-13.0.pre.231, on Microsoft Windows [Version 10.0.19041.746], locale et-EE)
    • Flutter version 1.26.0-13.0.pre.231 at C:\Development\flutter_master
    • Framework revision 29e604e241 (2 hours ago), 2021-01-28 00:04:03 -0800
    • Engine revision 68cd4c42b5
    • Dart version 2.12.0 (build 2.12.0-267.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.7042882
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.746]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 87.0.664.75

• No issues found!
```
</details>

Please file an issue in the mentioned repository and if it turns out there that there is some mistake in `firebase_messaging` that prevents the implementation from working we can reopen this. Otherwise we can't be held responsible for how a third-party (unfinished) plugin is implemented.

It is also still possible that there is an issue in your local pub-cache or project files that is causing this.

For now this issue just isn't actionable here.

**Comment by Bavon101** [comment] 2021-01-28 11:25
> If the issue is still there without `awesome_notifications` this might be the case but the official example runs perfectly fine on the latest master `1.26.0-13.0.pre.231` with only
> 
> ```yaml
> dependencies:
>   flutter:
>     sdk: flutter
>   firebase_core: ^0.7.0
>   firebase_messaging: ^8.0.0-dev.14
>   flutter_local_notifications: ^3.0.3
>   http: ^0.12.2
> ```
> 
> flutter doctor -v
> Please file an issue in the mentioned repository and if it turns out there that there is some mistake in `firebase_messaging` that prevents the implementation from working we can reopen this. Otherwise we can't be held responsible for how a third-party (unfinished) plugin is implemented.
> 
> It is also still possible that there is an issue in your local pub-cache or project files that is causing this since you also have other Xcode warnings in your build log.
> 
> For now this issue just isn't actionable here.

Okay, thanks
