### ISSUE TITLE
[firebase_auth] Is there any way to implement forgot password and send verification mail  firebase

### ISSUE THREAD

**Issue by kroikie** [FirebaseExtended/flutterfire#957] opened 2019-10-13 19:24 UTC
Hi everyone,
Is there any way to implement forgot password and sending verification mail through firebase in flutter.

**Comment by kroikie** [comment] 2019-10-13 19:24
@vuppalasivakumar

The issue at https://github.com/flutter/flutter/issues/12459 has been closed and moved here. Future collaboration on this issue will be done here.

**Comment by fxsalazar** [comment] 2020-03-03 16:34
Isn't done this way:
```dart
final FirebaseAuth _firebaseAuth;
_firebaseAuth.sendPasswordResetEmail(email: '[email]');
(await _firebaseAuth.currentUser()).sendEmailVerification();
```

**Comment by kirstywilliams** [comment] 2020-04-21 11:22
Closing as not a bug.

**Closed by kirstywilliams** 2020-04-21 11:22 UTC
Labels: type: enhancement
