### ISSUE TITLE
cloud_functions - json is interpreted differently in Mobile / Web

### ISSUE THREAD

**Issue by alarmatwork** [FirebaseExtended/flutterfire#2548] opened 2020-05-13 08:43 UTC
**Describe the bug**
Getting error: Expected a value of type 'Map<String, dynamic>', but got one of type 'List<dynamic>'

While using HttpsCallable and making cloud function call in running flutter web (chrome).
It works very well on Android/iOS.

It seems that Cloud Fuction Call response JSON is interpreted differently in web/chrome profile.

**To Reproduce**
1. Create cloud function:
```
exports.findUserProfileByEmailOrPhone = functions.https.onCall((data: any, context: any) => {
  return [{firstName:'Albert'}, {firstName:'John'}];
```
2. Call the function from flutter code:

```
final HttpsCallable findByEmailOrPhone = cloudFuncInstance().getHttpsCallable(
  functionName: 'findUserProfileByEmailOrPhone',
);

Future<dynamic> getProfileIdByEmailOrPhone(String searchString) async {
  var callResponse = await findByEmailOrPhone.call({'searchString': searchString});
  return Future.value(callResponse.data);
}
////////
// Call the  fuction
getProfileIdByEmailOrPhone('someone@test.com');
```

**Expected behavior**
Expect flutter web to handle the result same way as android/ios does. Currently it is getting an error.

**Additional context**
Happens only with flutter web profile.
Tested with `cloud_functions: ^0.5.0`

**Flutter doctor**
Run `flutter doctor` and paste the output below:

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, 1.18.0-13.0.pre, on Mac OS X 10.15.4 19E287, locale en-GB)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] VS Code (version 1.44.2)
[✓] Connected device (4 available)
```

**Comment by alarmatwork** [comment] 2020-05-13 14:22
Found a workaround:

If your cloud function onCall

`return [{firstName:'Albert'}, {firstName:'John'}]`

instead of
`return {result:  [{firstName:'Albert'}, {firstName:'John'}]}`

**Comment by TahaTesser** [comment] 2020-05-13 14:42
```
Launching lib/main.dart on Chrome in debug mode...
Debug service listening on ws://127.0.0.1:59276/DSi9WhLctgE=
A null value was passed into a non-nullable parameter value
This will become a failure when runtime null safety is enabled.
caught generic exception
Expected a value of type 'Map<String, dynamic>', but got one of type 'List<dynamic>'

```

<details> 
<summary>flutter doctor -v</summary> 

``` 
[✓] Flutter (Channel dev, 1.19.0-1.0.pre, on Mac OS X 10.15.4 19E287, locale
    en-GB)
    • Flutter version 1.19.0-1.0.pre at /Users/tahatesser/Code/flutter_dev
    • Framework revision 456d80b9dd (2 days ago), 2020-05-11 11:45:03 -0400
    • Engine revision d96f962ca2
    • Dart version 2.9.0 (build 2.9.0-7.0.dev 092ed38a87)

 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at /Users/tahatesser/Code/SDK
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = /Users/tahatesser/Code/SDK
    • Java binary at: /Applications/Android
      Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 11.4.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 11.4.1, Build version 11E503a
    • CocoaPods version 1.9.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 3.6)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build
      1.8.0_212-release-1586-b4-5784211)

[✓] VS Code (version 1.45.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.10.1

[✓] Connected device (4 available)
    • SM M305F   • 32003c30dc19668f • android-arm64  • Android 10 (API 29)
    • macOS      • macOS            • darwin-x64     • Mac OS X 10.15.4 19E287
    • Web Server • web-server       • web-javascript • Flutter Tools
    • Chrome     • chrome           • web-javascript • Google Chrome
      81.0.4044.138

• No issues found!
``` 

</details>

**Comment by DannyJoinedApps** [comment] 2020-10-09 18:51
Just wanted to say thanks to the Estonian chap @alarmatwork for taking the time to post his work around. Saved me a lot of time as I would have taken a lot longer to work this out myself (and very possibly fail entirely).

Still an issue by the way, 9/10/2020, and I'm getting exactly as per original post. If this is by design then 'one codebase to fit them all' isn't quite working out in this instance.

> Found a workaround:
> 
> If your cloud function onCall
> 
> `return [{firstName:'Albert'}, {firstName:'John'}]`
> 
> instead of
> `return {result: [{firstName:'Albert'}, {firstName:'John'}]}`

**Comment by Salakar** [comment] 2021-04-01 17:25
Closing in favour of #4059

**Closed by Salakar** 2021-04-01 17:25 UTC
Labels: platform: web, plugin: functions, type: bug
