### ISSUE TITLE
🐛 [CLOUD_FIRESTORE] Unhandled Exception when using get() offline with default options on a non-existing document

### ISSUE THREAD

**Issue by osaxma** [FirebaseExtended/flutterfire#4585] opened 2021-01-07 08:03 UTC
## Bug report

**Describe the bug**

I was testing an iOS app offline on the simulator, and I received the following error when performing a `get()` operation with the default option (Source.serverAndCache):

```
[VERBOSE-2:shell.cc(210)] Unhandled Exception:: [cloud_firestore/unavailable] The service is currently unavailable. 
This is a most likely a transient condition and may be corrected by retrying with a backoff., 
stack trace: #0      MethodChannelDocumentReference.get
package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:80
<asynchronous suspension>
#1      DocumentReference.get
package:cloud_firestore/src/document_reference.dart:63
// # 2,3,4,5 trace to my functions
#6      _RootZone.runUnary (dart:async/zone.dart:1450:54)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8 <…>

```

### Steps to reproduce

 When offline, the following throws an error
```
final firestore = FirebaseFirestore.instance;
final snapshot = await firestore.doc(path).get();  //  ❌ exception
// or
final snapshot = await firestore.doc(path).get(GetOptions(source: Source.serverAndCache));  // ❌  also exception
```

When the source  is changed to cache only, the data is retrieved fine without an error:
```
final snapshot = await firestore.doc(path).get(GetOptions(source: Source.cache));  // ✅ works 
```

### Expected behavior

`Source.serverAndCache` behavior should be the same as `Source.cache` when offline. 

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 1.22.5, on Mac OS X 10.15.6 19G2021 darwin-x64, locale en)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 12.0)
[✓] Android Studio (version 4.0)
[✓] VS Code (version 1.52.1)
[✓] Connected device (1 available)

• No issues found!
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
Dart SDK 2.10.4
Flutter SDK 1.22.5

dependencies:
- cached_network_image 2.3.3 [flutter flutter_cache_manager octo_image]
- cloud_firestore 0.14.4 [flutter meta quiver firebase_core firebase_core_platform_interface cloud_firestore_platform_interface cloud_firestore_web]
- cloud_functions 0.7.2 [meta flutter firebase_core firebase_core_platform_interface cloud_functions_platform_interface cloud_functions_web]
- country_list_pick 1.0.1+2 [flutter]
- cupertino_icons 1.0.0
- file_picker 2.0.7 [flutter flutter_web_plugins flutter_plugin_android_lifecycle plugin_platform_interface]
- firebase_analytics 6.0.2 [meta flutter firebase_core firebase_analytics_web firebase_analytics_platform_interface]
- firebase_auth 0.18.4+1 [meta firebase_core firebase_core_platform_interface firebase_auth_platform_interface firebase_auth_web flutter]
- firebase_core 0.5.3 [firebase_core_platform_interface flutter quiver meta firebase_core_web]
- firebase_storage 4.0.1 [flutter firebase_core]
- flutter 0.0.0 [characters collection meta typed_data vector_math sky_engine]
- image_cropper 1.3.1 [flutter]
- image_picker 0.6.7+11 [flutter flutter_plugin_android_lifecycle image_picker_platform_interface]
- language_pickers 0.2.0+1 [flutter]
- provider 4.3.2+2 [flutter nested collection]
- sembast_sqflite 1.0.0 [sembast sqflite_common meta]
- shared_preferences 0.5.12 [meta flutter shared_preferences_platform_interface shared_preferences_linux shared_preferences_macos shared_preferences_web shared_preferences_windows]
- sqflite 1.3.2+1 [flutter sqflite_common path]
- zefyr 0.11.0 [flutter collection url_launcher quill_delta notus meta quiver_hashcode]

dev dependencies:
- flutter_test 0.0.0 [flutter test_api path fake_async clock stack_trace vector_math async boolean_selector characters charcode collection matcher meta source_span stream_channel string_scanner term_glyph typed_data]

transitive dependencies:
- async 2.5.0-nullsafety.1 [collection]
- boolean_selector 2.1.0-nullsafety.1 [source_span string_scanner]
- characters 1.1.0-nullsafety.3
- charcode 1.2.0-nullsafety.1
- clock 1.1.0-nullsafety.1
- cloud_firestore_platform_interface 2.2.1 [flutter meta collection firebase_core plugin_platform_interface]
- cloud_firestore_web 0.2.1+2 [flutter flutter_web_plugins http_parser meta firebase_core firebase_core_web cloud_firestore_platform_interface js]
- cloud_functions_platform_interface 3.0.3 [flutter meta firebase_core plugin_platform_interface]
- cloud_functions_web 3.1.1 [firebase_core firebase_core_web cloud_functions_platform_interface flutter flutter_web_plugins http_parser meta js]
- collection 1.15.0-nullsafety.3
- convert 2.1.1 [charcode typed_data]
- crypto 2.1.5 [collection convert typed_data]
- fake_async 1.2.0-nullsafety.1 [clock collection]
- ffi 0.1.3
- file 5.2.1 [intl meta path]
- firebase 7.3.0 [http http_parser js]
- firebase_analytics_platform_interface 1.0.3 [flutter meta]
- firebase_analytics_web 0.1.1 [flutter flutter_web_plugins firebase firebase_analytics_platform_interface meta]
- firebase_auth_platform_interface 2.1.4 [flutter meta firebase_core plugin_platform_interface]
- firebase_auth_web 0.3.2+3 [flutter flutter_web_plugins meta http_parser intl firebase_core firebase_core_web firebase_auth_platform_interface js]
- firebase_core_platform_interface 2.1.0 [flutter meta plugin_platform_interface quiver]
- firebase_core_web 0.2.1+1 [firebase_core_platform_interface flutter flutter_web_plugins meta js]
- flex_color_picker 1.1.2 [flutter]
- flutter_blurhash 0.5.0 [flutter meta]
- flutter_cache_manager 1.4.2 [flutter path_provider uuid http path sqflite pedantic clock file rxdart]
- flutter_circle_color_picker 0.2.0 [flutter]
- flutter_plugin_android_lifecycle 1.0.11 [flutter]
- flutter_svg 0.19.0 [path_drawing xml vector_math meta flutter]
- flutter_web_plugins 0.0.0 [flutter characters collection meta typed_data vector_math]
- http 0.12.2 [http_parser path pedantic]
- http_parser 3.1.4 [charcode collection source_span string_scanner typed_data]
- image_picker_platform_interface 1.1.1 [flutter meta http plugin_platform_interface]
- intl 0.16.1 [path]
- js 0.6.2
- matcher 0.12.10-nullsafety.1 [stack_trace]
- matrix_gesture_detector 0.1.0 [flutter vector_math]
- meta 1.3.0-nullsafety.3
- nested 0.0.4 [flutter]
- notus 0.1.5 [collection meta quill_delta quiver_hashcode]
- octo_image 0.3.0 [flutter flutter_blurhash]
- path 1.8.0-nullsafety.1
- path_drawing 0.4.1+1 [vector_math meta path_parsing flutter]
- path_parsing 0.1.4 [vector_math meta]
- path_provider 1.6.18 [flutter path_provider_platform_interface path_provider_macos path_provider_linux path_provider_windows]
- path_provider_linux 0.0.1+2 [path xdg_directories path_provider_platform_interface flutter]
- path_provider_macos 0.0.4+4 [flutter]
- path_provider_platform_interface 1.0.3 [flutter meta platform plugin_platform_interface]
- path_provider_windows 0.0.4+1 [path_provider_platform_interface meta path flutter ffi win32]
- pedantic 1.9.2 [meta]
- petitparser 3.1.0 [meta]
- platform 2.2.1
- plugin_platform_interface 1.0.3 [meta]
- process 3.0.13 [file intl meta path platform]
- quill_delta 1.1.3 [collection quiver_hashcode]
- quiver 2.1.3 [matcher meta]
- quiver_hashcode 2.0.0
- rxdart 0.24.1
- sembast 2.4.8+1 [meta path synchronized]
- shared_preferences_linux 0.0.2+2 [file flutter meta path path_provider_linux shared_preferences_platform_interface]
- shared_preferences_macos 0.0.1+10 [shared_preferences_platform_interface flutter]
- shared_preferences_platform_interface 1.0.4 [meta flutter]
- shared_preferences_web 0.1.2+7 [shared_preferences_platform_interface flutter flutter_web_plugins meta]
- shared_preferences_windows 0.0.1+1 [shared_preferences_platform_interface flutter ffi file meta path path_provider_platform_interface path_provider_windows]
- sky_engine 0.0.99
- source_span 1.8.0-nullsafety.2 [charcode collection path term_glyph]
- sqflite_common 1.0.2+1 [synchronized path meta]
- stack_trace 1.10.0-nullsafety.1 [path]
- stream_channel 2.1.0-nullsafety.1 [async]
- string_scanner 1.1.0-nullsafety.1 [charcode source_span]
- synchronized 2.2.0+2
- term_glyph 1.2.0-nullsafety.1
- test_api 0.2.19-nullsafety.2 [async boolean_selector collection meta path source_span stack_trace stream_channel string_scanner term_glyph matcher]
- tuple 1.0.3 [quiver]
- typed_data 1.3.0-nullsafety.3 [collection]
- undo 1.3.0+1
- url_launcher 5.7.2 [flutter url_launcher_platform_interface url_launcher_web url_launcher_linux url_launcher_macos url_launcher_windows]
- url_launcher_linux 0.0.1+1 [flutter]
- url_launcher_macos 0.0.1+8 [flutter]
- url_launcher_platform_interface 1.0.8 [flutter meta plugin_platform_interface]
- url_launcher_web 0.1.4+1 [url_launcher_platform_interface flutter flutter_web_plugins meta]
- url_launcher_windows 0.0.1+1 [flutter]
- uuid 2.2.2 [crypto convert]
- vector_math 2.1.0-nullsafety.3
- win32 1.7.3 [ffi]
- xdg_directories 0.1.2 [meta path process]
- xml 4.5.1 [collection convert meta petitparser]

```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-01-07 11:02
Hi @osaxma 
Have you run into this on a physical device as well?
Thank you

**Comment by osaxma** [comment] 2021-01-08 21:54
Hi @markusaksli-nc 

I just tested in a real device. The same error message and same behavior:

- The error only occurs with the `get()` method (streams are fine). 
- While offline, changing the code to `get(GetOptions(source: Source.cache))` retrieves the results immediately with hot reload. 

```
Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. 
This is a most likely a transient condition and may be corrected by retrying with a backoff.
#0      MethodChannelDocumentReference.get
package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:80
<asynchronous suspension>
#1      DocumentReference.get
package:cloud_firestore/src/document_reference.dart:63
// #2,3 trace to my function 
<asynchronous suspension>

```

**Comment by markusaksli-nc** [comment] 2021-01-11 10:41
I was not able to reproduce this on the latest master `1.26.0-2.0.pre.275` with `cloud_firestore: ^0.14.4`.
<details>
 <summary>flutter doctor -v</summary>

```
[✓] Flutter (Channel master, 1.26.0-2.0.pre.275, on macOS 11.1 20C69 darwin-arm, locale en-GB)
    • Flutter version 1.26.0-2.0.pre.275 at /Users/nevercode/development/flutter_master
    • Framework revision d9044a8a61 (2 days ago), 2021-01-09 04:04:04 -0500
    • Engine revision caf6a8191f
    • Dart version 2.12.0 (build 2.12.0-204.0.dev)

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
    • Android SDK at /Users/nevercode/Library/Android/sdk
    • Platform android-30, build-tools 30.0.3
    • Java binary at: /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.3, Build version 12C33
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.1)
    • Android Studio at /Users/nevercode/Library/Application Support/JetBrains/Toolbox/apps/AndroidStudio/ch-0/201.6953283/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      � https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] Connected device (4 available)
    • Nevercode’s iPhone (mobile) • b668e524315069f3db3661ac11ff1f66afafebdb • ios            • iOS 14.3
    • iPhone 12 Pro Max (mobile)  • 09D9E93F-A98D-4735-B6E6-6E57F9CD01D8     • ios            • com.apple.CoreSimulator.SimRuntime.iOS-14-3 (simulator)
    • macOS (desktop)             • macos                                    • darwin-arm64   • macOS 11.1 20C69 darwin-arm
    • Chrome (web)                • chrome                                   • web-javascript • Google Chrome 87.0.4280.141

• No issues found!
```
</details>
<details>
 <summary>Complete code sample</summary>

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

const String doc = 'test/geo';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      body: Center(
        child: Column(
          children: [
            ElevatedButton(
              child: const Text("Get default"),
              onPressed: () async {
                print((await FirebaseFirestore.instance.doc(doc).get()).data());
              },
            ),
            ElevatedButton(
              child: const Text("Get serverAndCache"),
              onPressed: () async {
                print((await FirebaseFirestore.instance.doc(doc).get(GetOptions(source: Source.serverAndCache))).data());
              },
            ),
            ElevatedButton(
              child: const Text("Get server"),
              onPressed: () async {
                print((await FirebaseFirestore.instance.doc(doc).get(GetOptions(source: Source.server))).data());
              },
            ),
            ElevatedButton(
              child: const Text("Get cached"),
              onPressed: () async {
                print((await FirebaseFirestore.instance.doc(doc).get(GetOptions(source: Source.cache))).data());
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>

When the data is cached it will retrieve it with default as expected.
Are you able to reproduce the issue with this code?

**Comment by osaxma** [comment] 2021-01-13 10:14
I guess I found the root cause after some digging. 

In short, the error occurs when:
- The device is `offline` 
- Using `get()` with the default `Source.serverAndCache`
- The is reference for a non-existing document. 

To demonstrate, this code throws an error when offline:
_using `flutter master 1.26.0-2.0.pre.275` and `cloud_firestore: ^0.14.4`_
```dart
    final firestore =  FirebaseFirestore.instance;
    final getOptions = GetOptions(source: Source.serverAndCache); 
    // this will work fine
    final existingDocument = await firestore.doc("collection/existingDocument").get(getOptions);
    // this will throw an error 
    final nonExistingDocument = await firestore.doc("collection/nonExistingDocument").get(getOptions); 
```

For the same code above and while offline, changing the source to `Source.cache` does not throw an error. And calling `nonExistingDocument.exists` returns `false` as expected. 


<details><summary>Exception Message</summary>

```sh
[VERBOSE-2:ui_dart_state.cc(186)] Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. 
This is a most likely a transient condition and may be corrected by retrying with a backoff.
#0      MethodChannelDocumentReference.get
package:cloud_firestore_platform_interface/…/method_channel/method_channel_document_reference.dart:80
<asynchronous suspension>
#1      DocumentReference.get
package:cloud_firestore/src/document_reference.dart:63
```

</details>

@markusaksli-nc Please let me know if you need any additional information.

**Comment by markusaksli-nc** [comment] 2021-01-13 11:25
I was able to reproduce this on the latest master `1.26.0-2.0.pre.313` with
```yaml
firebase_core: ^0.7.0
cloud_firestore: ^0.16.0
```
<details>
 <summary>flutter doctor -v</summary>

```console
[√] Flutter (Channel master, 1.26.0-2.0.pre.313, on Microsoft Windows [Version 10.0.19041.685], locale et-EE)
    • Flutter version 1.26.0-2.0.pre.313 at C:\Development\flutter_master
    • Framework revision 1cb0a24a46 (6 hours ago), 2021-01-12 21:39:27 -0800
    • Engine revision 10cee6abcb
    • Dart version 2.12.0 (build 2.12.0-214.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at C:\Users\marku\AppData\Local\Android\sdk
    • Platform android-30, build-tools 30.0.2
    • Java binary at: C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.7.7)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\Community
    • Visual Studio Community 2019 version 16.7.30621.155
    • Windows 10 SDK version 10.0.18362.0

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Users\marku\AppData\Local\JetBrains\Toolbox\apps\AndroidStudio\ch-0\201.6953283
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM G950F (mobile) • ce12171c51cc001c03 • android-arm64  • Android 9 (API 28)
    • Windows (desktop) • windows            • windows-x64    • Microsoft Windows [Version 10.0.19041.685]
    • Chrome (web)      • chrome             • web-javascript • Google Chrome 87.0.4280.141
    • Edge (web)        • edge               • web-javascript • Microsoft Edge 87.0.664.66

• No issues found!
```
</details>

<details>
 <summary>Minimal reproducible code sample</summary>

```dart
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

const String existingDoc = 'test/geo';
const String nonExistingDoc = 'test/ababab';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  FirebaseApp app = await Firebase.initializeApp();
  assert(app != null);
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Material App',
      theme: ThemeData.dark(),
      home: Home(),
    );
  }
}

class Home extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Firestore Example'),
      ),
      body: Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.spaceEvenly,
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            ElevatedButton(
              child: const Text("Get serverAndCache (existing)"),
              onPressed: () async {
                var doc = await FirebaseFirestore.instance.doc(existingDoc).get(GetOptions(source: Source.serverAndCache));
                print(doc.exists);
                print(doc.data());
              },
            ),
            ElevatedButton(
              child: const Text("Get serverAndCache (non existing)"),
              onPressed: () async {
                var doc = await FirebaseFirestore.instance.doc(nonExistingDoc).get(GetOptions(source: Source.serverAndCache));
                print(doc.exists);
                print(doc.data());
              },
            ),
            ElevatedButton(
              child: const Text("Get cache (existing)"),
              onPressed: () async {
                var doc = await FirebaseFirestore.instance.doc(existingDoc).get(GetOptions(source: Source.cache));
                print(doc.exists);
                print(doc.data());
              },
            ),
            ElevatedButton(
              child: const Text("Get cache (non existing)"),
              onPressed: () async {
                var doc = await FirebaseFirestore.instance.doc(nonExistingDoc).get(GetOptions(source: Source.cache));
                print(doc.exists);
                print(doc.data());
              },
            ),
          ],
        ),
      ),
    );
  }
}
```
</details>
<details>
 <summary>Logs (non existing doc default offline get)</summary>

```console
D/ViewRootImpl@b1c840b[MainActivity](19937): ViewPostIme pointer 0
D/ViewRootImpl@b1c840b[MainActivity](19937): ViewPostIme pointer 1
W/Firestore(19937): (22.0.1) [WatchStream]: (7b78670) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:436)
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:272)
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:228)
W/Firestore(19937): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Firestore(19937): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Firestore(19937): 	at java.lang.Thread.run(Thread.java:764)
W/Firestore(19937): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(19937): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
W/Firestore(19937): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
W/Firestore(19937): 	at java.net.InetAddress.getAllByName(InetAddress.java:1154)
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:646)
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:404)
W/Firestore(19937): 	... 5 more
W/Firestore(19937): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(19937): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore(19937): 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
W/Firestore(19937): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
W/Firestore(19937): 	... 9 more
W/Firestore(19937): }.
E/flutter (19937): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: [cloud_firestore/unavailable] The service is currently unavailable. This is a most likely a transient condition and may be corrected by retrying with a backoff.
E/flutter (19937): #0      MethodChannelDocumentReference.get (package:cloud_firestore_platform_interface/src/method_channel/method_channel_document_reference.dart:80:7)
E/flutter (19937): <asynchronous suspension>
E/flutter (19937): #1      DocumentReference.get (package:cloud_firestore/src/document_reference.dart:59:20)
E/flutter (19937): <asynchronous suspension>
E/flutter (19937): #2      Home.build.<anonymous closure> (package:triage/main.dart:50:27)
E/flutter (19937): <asynchronous suspension>
E/flutter (19937): 
W/Firestore(19937): (22.0.1) [WatchStream]: (7b78670) Stream closed with status: Status{code=UNAVAILABLE, description=Unable to resolve host firestore.googleapis.com, cause=java.lang.RuntimeException: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:436)
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:272)
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:228)
W/Firestore(19937): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/Firestore(19937): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/Firestore(19937): 	at java.lang.Thread.run(Thread.java:764)
W/Firestore(19937): Caused by: java.net.UnknownHostException: Unable to resolve host "firestore.googleapis.com": No address associated with hostname
W/Firestore(19937): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:157)
W/Firestore(19937): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
W/Firestore(19937): 	at java.net.InetAddress.getAllByName(InetAddress.java:1154)
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:646)
W/Firestore(19937): 	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:404)
W/Firestore(19937): 	... 5 more
W/Firestore(19937): Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
W/Firestore(19937): 	at libcore.io.Linux.android_getaddrinfo(Native Method)
W/Firestore(19937): 	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:172)
W/Firestore(19937): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:137)
W/Firestore(19937): 	... 9 more
W/Firestore(19937): }.
```
</details>
<details>
 <summary>Logs (existing doc cached offline get)</summary>

```console
D/ViewRootImpl@b1c840b[MainActivity](19937): ViewPostIme pointer 0
D/ViewRootImpl@b1c840b[MainActivity](19937): ViewPostIme pointer 1
I/flutter (19937): false
I/flutter (19937): null
```
</details>

**Comment by russellwheatley** [comment] 2021-02-24 15:32
Hey @osaxma, this is expected behaviour I'm afraid.  The underlying android or iOS sdk is trying to make a network request which is causing the `cloud_firestore/unavailable` error because the device is offline. When you set the `cache` option, it doesn't make a network request which is why there is no error. This is not something we have much control over as we're simply relaying the error from native back to user implementation.

**Comment by russellwheatley** [comment] 2021-04-20 10:36
As mentioned, this is expected behaviour so I'm going to close this issue.

**Closed by russellwheatley** 2021-04-20 10:36 UTC
Labels: plugin: cloud_firestore
