### ISSUE TITLE
[Firestore] Unable to run any fetch on iOS

### ISSUE THREAD

**Issue by sajunt4** [FirebaseExtended/flutterfire#3051] opened 2020-07-28 20:48 UTC
(This is based on the issue #2894 . I've updated all the packages to the dev new packages and the app still crashes)

I'm trying to run on iOS a Flutter app that works perfectly on Android, but it crashes as soon as it arribes to any get(). It does not return any Flutter error, just crashes the app.

The exact line that is causing the issue is:

```
(await FirebaseFirestore.instance.collection('users')
          .doc(firebaseUser.uid).get()).data();
```
Other Firebase services like Phone Auth are working, so I don't think is something related to the configuration steps.

The whole output from Xcode is the following:

```
2020-07-28 22:38:20.961632+0200 Runner[2008:222492] *** Assertion failure in void firebase::firestore::core::FirestoreClient::Initialize(const firebase::firestore::auth::User &, const firebase::firestore::api::Settings &)(), /Users/taco/StudioProjects/-/ios/Pods/FirebaseFirestore/Firestore/core/src/core/firestore_client.cc:180
2020-07-28 22:38:20.963407+0200 Runner[2008:222492] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Failed to open DB: Internal: Failed to open LevelDB database at : LevelDB error: IO error: /LOCK @ /Users/bldadmin/.jenkins/workspace/iot-sdk/release/release-ios-pipe/external/leveldb/util/env_posix.cc:445 virtual leveldb::Status leveldb::(anonymous namespace)::PosixEnv::LockFile(const std::string &, leveldb::FileLock **): Operation not permitted (expected created.ok())'
*** First throw call stack:
(0x1b1211984 0x1b0f2967c 0x1b111afc0 0x1b15e9490 0x100d1c168 0x100d1ba44 0x100e8a134 0x100e8a1e8 0x100d999ec 0x100da4bd4 0x100da4b80 0x100da4b34 0x100da4b0c 0x100da33c0 0x100c9b36c 0x100c98710 0x100c986d0 0x100c9dc1c 0x100c9dbdc 0x100c9db90 0x100c9db68 0x100c9c540 0x100c9b36c 0x100c98710 0x1010bbfc4 0x100d1d18c 0x113c91744 0x113c990fc 0x113c99e08 0x113ca5f84 0x1b0f1a908 0x1b0f2177c)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'FIRESTORE INTERNAL ASSERTION FAILED: Failed to open DB: Internal: Failed to open LevelDB database at : LevelDB error: IO error: /LOCK @ /Users/bldadmin/.jenkins/workspace/iot-sdk/release/release-ios-pipe/external/leveldb/util/env_posix.cc:445 virtual leveldb::Status leveldb::(anonymous namespace)::PosixEnv::LockFile(const std::string &, leveldb::FileLock **): Operation not permitted (expected created.ok())'
terminating with uncaught exception of type NSException
```
**To Reproduce**
1. Install firebase for flutter using pub.dev step by step.
2. Try to get some documents from firecloud.

**Expected behavior**
The app does not crash and I get everything working as it works on Android :)

**Additional context**
I'm using Firebase Auth with phone auth, I've configured everything necessary to make it work with phone auth and it's working fine.
I'm trying to run this app on an iPhone 11 simulator as I don't have a physical iPhone yet.
I've tried the always recommended flutter clean command, deleting Podfile and Podfile.lock so flutter recreates it, redownloading GoogleService-Info.plist, etc...

**Flutter doctor**
```
[✓] Flutter (Channel stable, v1.17.5, on Mac OS X 10.15.5 19F101, locale es-ES)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
 
[✓] Connected device (1 available)            

• No issues found!

```

I would gladly give you all any additional info required to make this work. It's been a week trying to solve this and nothing seem to work.
Thank you!

**Comment by kroikie** [comment] 2020-07-28 21:51
It looks like this is related to [this issue](https://github.com/firebase/firebase-ios-sdk/issues/5423) on the Firebase iOS SDK. Would you mind closing this issue and tracking the progress there since it is likely the issue is in the underlying iOS SDK and not the Flutter plugin?

**Comment by sajunt4** [comment] 2020-07-29 10:41
Mm... I've been reading the issue you mentioned and all related issues, and I can't see how this could be related.
I'm not making any fetch with the app in background, as the issue suggests. 
In fact, I've modified my app to make sure everything runs only if the app is active using WidgetsBindingObserver, and nothing has changed.

Maybe it has something to do with Phone Auth in iOS, that opens a Safari instance to verify reCaptcha? Maybe firebase is doing some work while in that Safari window and thus throwing that access error?

Anyway, I'm gonna ask in the Flutter iOS SDK git page.
Thank you!

**Comment by kroikie** [comment] 2020-07-29 15:07
Thanks @sajunt4 if you find any reason pointing to FlutterFire being the cause please feel free to file a new issue.

**Closed by kroikie** 2020-07-29 15:07 UTC
Labels: plugin: cloud_firestore
