### ISSUE TITLE
🐛 [cloud_firestore] dependency were found, but they     required a higher minimum deployment target. (Flutter in existing app)

### ISSUE THREAD

**Issue by yoman07** [FirebaseExtended/flutterfire#4820] opened 2021-01-27 07:57 UTC
## Bug report

**Describe the bug**
I updated firebase to the latest one, but there is no possibility to run `build ios --release --no-codesign `, because I get:
`cloud_firestore` dependency were found, but they required a higher minimum deployment target`.

I found some solutions that you can change Podfile and set `platform :ios, '10.0` but I use flutter as Add-to-app. There is no possibility to edit Podfile because on Continues Integration it is generated each time if you use add-to-app.  

---

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
[✓] Flutter (Channel stable, 1.22.6, on macOS 11.1 20C69 darwin-x64, locale en-PL)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 12.3)
[!] Android Studio (version 4.1)
    ✗ Flutter plugin not installed; this adds Flutter specific functionality.
    ✗ Dart plugin not installed; this adds Dart specific functionality.
[!] VS Code (version 1.52.1)
    ✗ Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter
```

</details>

---

---

**Comment by markusaksli-nc** [comment] 2021-01-27 10:17
Hi @yoman07 
That podfile line is commented out by default. You can just set the iOS target in the Xcode project instead.
Does this solve the issue for you?
Thank you

**Comment by yoman07** [comment] 2021-01-27 11:47
<img width="334" alt="Screenshot 2021-01-27 at 12 46 44" src="https://user-images.githubusercontent.com/1101367/105986837-b8b60280-609d-11eb-80d5-70592df3851d.png">
Yes, I set it in the application which embed flutter.

**Comment by yoman07** [comment] 2021-01-27 12:00
Podfile that is generated by flutter at path: `/Users/user//ExampleProject/flutter/.ios/Podfile`

looks like that:

`platform :ios, '9.0'

flutter_application_path = '../'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

use_frameworks!

target 'Runner' do
  install_flutter_engine_pod
  install_flutter_plugin_pods flutter_application_path
end
`

**Comment by yoman07** [comment] 2021-01-28 06:52
I think that needs to be changed in Flutter library itself to generate Podfile in `.ios/` that contains `platform :ios, '10.0'` instead of 9.0

**Comment by markusaksli-nc** [comment] 2021-01-28 09:40
It should be 
```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
```
What is the command do you use to generate the command?

**Comment by yoman07** [comment] 2021-01-28 13:07
It is generated automatically by flutter

**Comment by markusaksli-nc** [comment] 2021-01-29 08:05
`flutter build` runs `flutter pub get` and on stable it should contain the commented out lines I mentioned before.

This is an add-to-app scenario though so maybe that is causing this. Can you not include a fixed podfile in the source code? It shouldn't generate a new one in that case.

**Comment by yoman07** [comment] 2021-01-29 14:34
@markusaksli-nc are you sure? It is generated each time if do `flutter build ios` 
I think that it is flutter default template to have there iOS 9.0 [https://github.com/flutter/flutter/blob/60bdcf55fe8b2877ce2c295fe69bd146ea81cfbd/dev/integration_tests/ios_host_app/Podfile](url)

**Comment by markusaksli-nc** [comment] 2021-02-01 11:21
It might be the case for integration tests then.

As it stands however this is not an issue with the FlutterFire plugins themselves but rather with the generated podfile overwriting the ios version. If it isn't possible for you to add a step to the CI script for this then I'm not sure what the solution would be.

In any case, this is more of an upstream issue. I would recommend you take it to https://github.com/flutter/flutter/issues/new/choose

There really isn't much for us to do here. The iOS minimum target is a result of the constraint of the underlying Firebase iOS SDK.

I'm going to close this issue as it is caused by the flutter tool, rather than the Firebase plugins. Let me know if you disagree.
Thank you

**Closed by markusaksli-nc** 2021-02-01 11:21 UTC
Labels: Needs Attention, type: bug
