### ISSUE TITLE
🐛 [Firebase_Auth] signInAnonymously works fine but after signOut it does not remove record from database

### ISSUE THREAD

**Issue by uc-dve** [FirebaseExtended/flutterfire#6813] opened 2021-08-13 09:21 UTC
## Bug report

signInAnonymously works fine but after signOut, it does not remove records from the database, so it will create multiple IDs for 1 user may be more than 100 in just 1 week.
Either it should remove the record from DB on logout or after signing should not create new ID.

**Describe the bug**
  await Firebase.initializeApp();
  if (FirebaseAuth.instance.currentUser != null) {
    await FirebaseAuth.instance.signOut();
  }
  await FirebaseAuth.instance.signInAnonymously();
  print('1: ${FirebaseAuth.instance.currentUser.uid}');
  await FirebaseAuth.instance.signOut();
  await FirebaseAuth.instance.signInAnonymously();
  print('2: ${FirebaseAuth.instance.currentUser.uid}');

**Comment by markusaksli-nc** [comment] 2021-08-13 10:45
Hi @uc-dve 
First off this repository just wraps the native Firebase SDKs. We do not control this behavior. If you want anonymous users to be somehow automatically linked to the device they sign in from (I'm guessing this is what you mean?) you can contact https://firebase.google.com/support
Secondly, this is just how anonymous users work. Since they have no linked auth providers there is no way to sign in to them again once signed out. Thus a new one needs to be created on sign-in. With regards to deleting the user after sign-out - again we do not control this behavior so you can request it from Firebase support or set this behavior up yourself.

Because the issue is not actionable for us I'm going to close it.
Thank you.

**Closed by markusaksli-nc** 2021-08-13 10:45 UTC
Labels: type: bug, Needs Attention, in triage
