### ISSUE TITLE
'where' seems to be ignored in snapshots().listen() in Firestore

### ISSUE THREAD

**Issue by Gintasz** [FirebaseExtended/flutterfire#2225] opened 2020-03-23 09:29 UTC
Using `cloud_firestore: 0.13.4+2`. Here is a test code I used:
![image](https://user-images.githubusercontent.com/6189625/77302045-5a8bf680-6cf9-11ea-9c40-e8e7bab53849.png)

Callback is still called when I add a new object, or edit an object which does not have `PU9NeagFtG5u0TyNt9nb` in its `companyIds`. E.g. adding this object triggers the callback:
![image](https://user-images.githubusercontent.com/6189625/77302183-a3dc4600-6cf9-11ea-8726-22f37310c159.png)

**Comment by iapicca** [comment] 2020-03-25 10:46
Hi @Gintasz 
can you please provide your `flutter doctor -v` , 
your `flutter run --verbose` 
and your `pubspec.yaml` 
or if possible a reproducible minimal code sample.

Please refrain from posting pictures if not necessary.
Thank you

**Comment by shinewanna** [comment] 2020-06-29 05:43
I'm also facing the same problem, but here the problem is Open issues 
My Temporary Solution is
`        _firestore.collection('GroupDetail').snapshots().listen((rv) {
          _firestore
              .collection('GroupDetail')
              .where('id', whereIn: groupIdList)
              .orderBy('lastMessageCreateAt', descending: true)
              .snapshots()
              .listen((groupDoc) {
                   print(groupDoc['id']);
          });
        });`
Double looped the snapshots for temporary solution, i hope it'll help enough.

**Comment by Salakar** [comment] 2020-07-07 22:11
Hey all, as part of our on-going work for #2582, this has been resolved in our Firebase Firestore rework (#2913) - which has now been merged into master. We'll look at publishing some prereleases in the next few days. Thank you

**Closed by Salakar** 2020-07-07 22:11 UTC
Labels: plugin: cloud_firestore, type: bug
