### ISSUE TITLE
🐛 [firebase_core] MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)

### ISSUE THREAD

**Issue by DineshTaral123** [FirebaseExtended/flutterfire#4617] opened 2021-01-11 08:10 UTC
The app is working fine in Android but when i try to run same app in iOS (Real Device 14.3) it showing me an error " MissingPluginException(No implementation found for method Firebase#initializeCore on channel plugins.flutter.io/firebase_core)" . My all configurations with iOS is done as showing in Readme.md file, and also tried with different projects but getting same error.
my main.dart file is

void main()async{
WidgetsFlutterBinding.ensureInitialized();
try {
await Firebase.initializeApp();
}catch(err){
print("$err");
}
runZonedGuarded(() {
SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
runApp(MyApp());
}, (error, stackTrace) {
print('runZonedGuarded: Caught error in my root zone.');
});
}

**Comment by markusaksli-nc** [comment] 2021-01-11 13:44
Closing this as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4605

Please do not open multiple issues for the same problem

**Closed by markusaksli-nc** 2021-01-11 13:44 UTC
Labels: Needs Attention, type: bug
