### ISSUE TITLE
Firebase background handler

### ISSUE THREAD

**Issue by kratipandey57** [FirebaseExtended/flutterfire#2745] opened 2020-06-11 11:17 UTC
how to open app if onbackgroundhandler is called

**Comment by iapicca** [comment] 2020-06-12 13:12
Hi @kratipandey57 
From what I can see, the issue is related to a FlutterFire plugin rather than to Flutter itself. Please open the issue in the dedicated [repository](https://github.com/FirebaseExtended/flutterfire/issues).
Closing, as this isn't an issue with Flutter itself. If you disagree, please write in the comments, possibly providing a minimal reproducible code sample that does not use flutter fire or other 3rd party plugins, and I will reopen it.
Thank you

**Closed by iapicca** 2020-06-12 13:12 UTC
