### ISSUE TITLE
Plugin project :firebase_core_web not found. Please update settings.gradle.

### ISSUE THREAD

**Issue by jerfesoncam** [FirebaseExtended/flutterfire#2932] opened 2020-07-11 01:22 UTC
Plugin project :firebase_core_web not found. Please update settings.gradle.

**Comment by HandersonSilva** [comment] 2020-07-13 01:15
Estou com o mesmo problema..

**Comment by TahaTesser** [comment] 2020-07-14 12:39
Please check this https://github.com/FirebaseExtended/flutterfire/issues/2796#issuecomment-656606329
Closing as duplicate of https://github.com/FirebaseExtended/flutterfire/issues/2796

**Closed by TahaTesser** 2020-07-14 12:39 UTC
