### ISSUE TITLE
ML Vision is updated frequently and yet still uses the old ml vision library which doesn't compile anymore

### ISSUE THREAD

**Issue by Greatcallie** [FirebaseExtended/flutterfire#5994] opened 2021-05-01 11:05 UTC
This package is updated frequently and yet still uses the old ml vision library which doesn't compile anymore. 

I have tried to update to the new library : GoogleMLKit/FaceDetection, and now pod installs but face recognition
just doesn't work anymore.

**Comment by markusaksli-nc** [comment] 2021-05-04 14:06
Closing as a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/4625

**Closed by markusaksli-nc** 2021-05-04 14:06 UTC
Labels: in triage
