### ISSUE TITLE
🐛 firebase_messaging package error - FirebaseMessaging.onMessage.listen triggers message multiple times.

### ISSUE THREAD

**Issue by AngithaMani** [FirebaseExtended/flutterfire#6924] opened 2021-09-01 07:34 UTC
## Bug report

**Describe the bug**

### Steps to reproduce

2. '...'
4. See error or incorrect behavior

### Sample project

Providing a minimal example project which demonstrates the bug in isolation from your main App _greatly_ enhances the chance of a timely fix.
Please link to the public repository URL.

---

## Additional context

---

### Flutter doctor

Run `flutter doctor` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

### Flutter dependencies

Run `flutter pub deps -- --style=compact` and paste the output below:

<details><summary>Click To Expand</summary>

```
PASTE OUTPUT INSIDE HERE
```

</details>

---

**Comment by markusaksli-nc** [comment] 2021-09-01 09:51
Hi @AngithaMani 
When opening an issue, please try to provide all of the information indicated in the template.
Closing this issue, since no information has been provided.

Please try upgrading to the latest version of the package and if the issue persists open a new issue, fill out the template, and provide a [minimal complete reproducible code sample](https://stackoverflow.com/help/minimal-reproducible-example).
Thank you.

**Closed by markusaksli-nc** 2021-09-01 09:51 UTC
Labels: type: bug, Needs Attention, in triage
