### ISSUE TITLE
🐛 [FIREBASE_APP_CHECK] Cant get this to work with ios

### ISSUE THREAD

**Issue by febg11** [FirebaseExtended/flutterfire#6457] opened 2021-06-23 21:11 UTC
I just bought an apple dev license and have generated an api key with device check enabled. 

I have uploaded this to firebase and added the team ID/key ID. 

I have then made sure my signing profile is my new account. I have ran flutter clean and pub get. I also deleted the app from my device.  I have opened the workspace in xcode and have let it build.  It still doesn't authenticate

```[firebase_functions/unauthenticated] Unauthenticated```
``` [firebase_storage/unauthenticated] User is unauthenticated. Authenticate and try again.```

I have tried adding ```pod 'Firebase/AppCheck'``` to the pod file and running pod install as per this doc https://firebase.google.com/docs/app-check/ios but i doubt that is needed with the flutter lib. 

Is there something I am missing? Maybe something i need to do in xcode so it allows device check calls?

**Comment by varunbhalerao56** [comment] 2021-06-24 07:03
@febg11 Hey I am having the same problem with android, mind sharing how you got that working. I followed the docs but no luck.

**Comment by febg11** [comment] 2021-06-24 07:16
> @febg11 Hey I am having the same problem with android, mind sharing how you got that working. I followed the docs but no luck. (I haven't tried iOS yet but will check that too)

The thing that made android work for me is removing all sha1 keys from firebase and the app key on the credentials page on gcp. Make sure that no key restrictions are set aswell. Let me know if this works and if you have any luck with iOS

**Comment by Salakar** [comment] 2021-06-24 09:34
@febg11 have you tried re-downloading and integrating your iOS apps Google Services plist file since you added Apple configs to the Firebase Console?

**Comment by varunbhalerao56** [comment] 2021-06-24 10:16
@febg11 unfortunately I am unable to get it working on both android and iOS. But do try what Salakar commented might help out. 

I know this might be a dumb question but when it says pass in a jwt token how do I do that, I already have a jwt token from my gRPC server. I just want to authenticate using firebase's custom token. 

![image](https://user-images.githubusercontent.com/59999892/123245910-e4310200-d502-11eb-968e-1a9c3c5c3f9a.png)

**Comment by febg11** [comment] 2021-06-24 11:09
I'm not sure I'm best to answer any of these questions. Your android code looks like it's working though. Notice the App:Valid log. I think this means the app check token was from a valid device 

I haven't used custom tokens before so Im not too sure about  the rest of this. 

You get the same errors as me for iOS. We probably need a flutter Dev to help with these problems 

@Salakar the iOS app key has always been used it's just not working with app check. I will double check and generate a new one later today and let you know if it makes any difference

**Comment by enri90** [comment] 2021-06-24 14:26
not work on Web 

https://github.com/FirebaseExtended/flutterfire/issues/6310

**Comment by febg11** [comment] 2021-06-24 17:34
@Salakar just tried downloading the googleservices.plist again and its contents are the same as the one I am already using

**Comment by febg11** [comment] 2021-06-26 12:36
Somehow got this working on iOS. Honesty not sure whats different

**Comment by varunbhalerao56** [comment] 2021-06-27 08:05
> Somehow got this working on iOS. Honesty not sure whats different

@febg11 I know this is too much to ask but do you mind sharing with me the android and iOS folders (without the plist and json files ofc).

**Comment by seanyyyyyy** [comment] 2021-07-12 06:04
got this working on iOS today (Note: i only have App Attest enabled in Firebase, not Device Check), 

Steps i was missing:
- In Xcode, add the *App Attest capability to your app.
- In your project's .entitlements file, set the App Attest environment to production.
- build and run through Xcode then I can see the Firebase App Check debug token in Xcode logs (it doesn't appear in my IntelliJ logs for some reason...)
- copy this token and set it as debug token in Firebase 

Reference: https://firebase.google.com/docs/app-check/ios-app-attest

**Comment by wazini-john** [comment] 2021-07-24 08:54
@seanyyyyyy How does one build a flutter app through xcode?

**Comment by seanyyyyyy** [comment] 2021-07-24 12:39
> @seanyyyyyy How does one build a flutter app through xcode?

open up the Runner.xcworkspace file in the ios directory, choose your target device/simulator and press the Run button

**Comment by wazini-john** [comment] 2021-07-24 13:32
> > @seanyyyyyy How does one build a flutter app through xcode?
> 
> open up the Runner.xcworkspace file in the ios directory, choose your target device/simulator and press the Run button

Do you have like a step by step list I can follow to generate the token ?
All I'm getting is a SQFlite error `
Undefined symbol: _OBJC_CLASS_$_FMDatabaseQueue
`
Kinda new to xcode

**Comment by wazini-john** [comment] 2021-07-26 13:36
They have fixed it

**Comment by markusaksli-nc** [comment] 2021-08-24 07:04
The functions issue has been addressed in https://github.com/FirebaseExtended/flutterfire/issues/6794 and storage is a duplicate of https://github.com/FirebaseExtended/flutterfire/issues/6551

**Closed by markusaksli-nc** 2021-08-24 07:04 UTC
Labels: type: bug, platform: ios, plugin: app_check
